/* $OpenBSD: keywords.h,v 1.11 2004/09/22 01:07:10 jaredy Exp $ */

/* WARNING!  This file was generated by keywords.sh  */

extern struct keytab {
	char	*kt_cp;
	int	kt_i;
} keywords[];


#define	K_ADD	1
#define	K_BLACKHOLE	2
#define	K_CHANGE	3
#define	K_CLONING	4
#define	K_DELETE	5
#define	K_DST	6
#define	K_EXPIRE	7
#define	K_FLUSH	8
#define	K_GATEWAY	9
#define	K_GENMASK	10
#define	K_GET	11
#define	K_HOST	12
#define	K_HOPCOUNT	13
#define	K_IFACE	14
#define	K_INTERFACE	15
#define	K_IFA	16
#define	K_IFP	17
#define	K_INET	18
#define	K_INET6	19
#define	K_IPX	20
#define	K_LABEL	21
#define	K_LINK	22
#define	K_LLINFO	23
#define	K_LOCK	24
#define	K_LOCKREST	25
#define	K_MASK	26
#define	K_MONITOR	27
#define	K_MPATH	28
#define	K_MTU	29
#define	K_NET	30
#define	K_NETMASK	31
#define	K_NOSTATIC	32
#define	K_OSI	33
#define	K_PREFIXLEN	34
#define	K_PROTO1	35
#define	K_PROTO2	36
#define	K_RECVPIPE	37
#define	K_REJECT	38
#define	K_RTT	39
#define	K_RTTVAR	40
#define	K_SA	41
#define	K_SENDPIPE	42
#define	K_SHOW	43
#define	K_SSTHRESH	44
#define	K_STATIC	45
#define	K_X25	46
#define	K_XRESOLVE	47
