# !!!!!!!   DO NOT EDIT THIS FILE   !!!!!!!
# This file is machine-generated by lib/unicore/mktables from the Unicode
# database, Version 5.2.0.  Any changes made here will be lost!

# !!!!!!!   INTERNAL PERL USE ONLY   !!!!!!!
# This file is for internal use by the Perl program only.  The format and even
# the name or existence of this file are subject to change without notice.
# Don't use it directly.

# This file returns the 16_688 code points in Unicode Version 5.2.0 that
# match any of the following regular expression constructs:
# 
#         \p{NFKD_Quick_Check=No}
#         \p{NFKD_QC=N}
#         \p{Is_NFKD_Quick_Check=No}
#         \p{Is_NFKD_QC=N}
# 
#     Note that contrary to what you might expect, the above is NOT the same
#     as any of: \P{NFKD_Quick_Check}, \P{NFKD_QC}, \P{Is_NFKD_Quick_Check},
#     \P{Is_NFKD_QC}
# 
# perluniprops.pod should be consulted for the syntax rules for any of these,
# including if adding or subtracting white space, underscore, and hyphen
# characters matters or doesn't matter, and other permissible syntactic
# variants.  Upper/lower case distinctions never matter.
# 
# A colon can be substituted for the equals sign, and anything to the left of
# the equals (or colon) can be combined with anything to the right.  Thus,
# for example,
#         \p{Is_NFKD_QC: No}
# is also valid.
# 
# The format of the lines of this file is: START\tSTOP\twhere START is the
# starting code point of the range, in hex; STOP is the ending point, or if
# omitted, the range has just one code point.  Numbers in comments in
# [brackets] indicate how many code points are in the range.

return <<'END';
00A0		
00A8		
00AA		
00AF		
00B2	00B5	 # [4]
00B8	00BA	 # [3]
00BC	00BE	 # [3]
00C0	00C5	 # [6]
00C7	00CF	 # [9]
00D1	00D6	 # [6]
00D9	00DD	 # [5]
00E0	00E5	 # [6]
00E7	00EF	 # [9]
00F1	00F6	 # [6]
00F9	00FD	 # [5]
00FF	010F	 # [17]
0112	0125	 # [20]
0128	0130	 # [9]
0132	0137	 # [6]
0139	0140	 # [8]
0143	0149	 # [7]
014C	0151	 # [6]
0154	0165	 # [18]
0168	017F	 # [24]
01A0	01A1	 # [2]
01AF	01B0	 # [2]
01C4	01DC	 # [25]
01DE	01E3	 # [6]
01E6	01F5	 # [16]
01F8	021B	 # [36]
021E	021F	 # [2]
0226	0233	 # [14]
02B0	02B8	 # [9]
02D8	02DD	 # [6]
02E0	02E4	 # [5]
0340	0341	 # [2]
0343	0344	 # [2]
0374		
037A		
037E		
0384	038A	 # [7]
038C		
038E	0390	 # [3]
03AA	03B0	 # [7]
03CA	03CE	 # [5]
03D0	03D6	 # [7]
03F0	03F2	 # [3]
03F4	03F5	 # [2]
03F9		
0400	0401	 # [2]
0403		
0407		
040C	040E	 # [3]
0419		
0439		
0450	0451	 # [2]
0453		
0457		
045C	045E	 # [3]
0476	0477	 # [2]
04C1	04C2	 # [2]
04D0	04D3	 # [4]
04D6	04D7	 # [2]
04DA	04DF	 # [6]
04E2	04E7	 # [6]
04EA	04F5	 # [12]
04F8	04F9	 # [2]
0587		
0622	0626	 # [5]
0675	0678	 # [4]
06C0		
06C2		
06D3		
0929		
0931		
0934		
0958	095F	 # [8]
09CB	09CC	 # [2]
09DC	09DD	 # [2]
09DF		
0A33		
0A36		
0A59	0A5B	 # [3]
0A5E		
0B48		
0B4B	0B4C	 # [2]
0B5C	0B5D	 # [2]
0B94		
0BCA	0BCC	 # [3]
0C48		
0CC0		
0CC7	0CC8	 # [2]
0CCA	0CCB	 # [2]
0D4A	0D4C	 # [3]
0DDA		
0DDC	0DDE	 # [3]
0E33		
0EB3		
0EDC	0EDD	 # [2]
0F0C		
0F43		
0F4D		
0F52		
0F57		
0F5C		
0F69		
0F73		
0F75	0F79	 # [5]
0F81		
0F93		
0F9D		
0FA2		
0FA7		
0FAC		
0FB9		
1026		
10FC		
1B06		
1B08		
1B0A		
1B0C		
1B0E		
1B12		
1B3B		
1B3D		
1B40	1B41	 # [2]
1B43		
1D2C	1D2E	 # [3]
1D30	1D3A	 # [11]
1D3C	1D4D	 # [18]
1D4F	1D6A	 # [28]
1D78		
1D9B	1DBF	 # [37]
1E00	1E9B	 # [156]
1EA0	1EF9	 # [90]
1F00	1F15	 # [22]
1F18	1F1D	 # [6]
1F20	1F45	 # [38]
1F48	1F4D	 # [6]
1F50	1F57	 # [8]
1F59		
1F5B		
1F5D		
1F5F	1F7D	 # [31]
1F80	1FB4	 # [53]
1FB6	1FC4	 # [15]
1FC6	1FD3	 # [14]
1FD6	1FDB	 # [6]
1FDD	1FEF	 # [19]
1FF2	1FF4	 # [3]
1FF6	1FFE	 # [9]
2000	200A	 # [11]
2011		
2017		
2024	2026	 # [3]
202F		
2033	2034	 # [2]
2036	2037	 # [2]
203C		
203E		
2047	2049	 # [3]
2057		
205F		
2070	2071	 # [2]
2074	208E	 # [27]
2090	2094	 # [5]
20A8		
2100	2103	 # [4]
2105	2107	 # [3]
2109	2113	 # [11]
2115	2116	 # [2]
2119	211D	 # [5]
2120	2122	 # [3]
2124		
2126		
2128		
212A	212D	 # [4]
212F	2131	 # [3]
2133	2139	 # [7]
213B	2140	 # [6]
2145	2149	 # [5]
2150	217F	 # [48]
2189		
219A	219B	 # [2]
21AE		
21CD	21CF	 # [3]
2204		
2209		
220C		
2224		
2226		
222C	222D	 # [2]
222F	2230	 # [2]
2241		
2244		
2247		
2249		
2260		
2262		
226D	2271	 # [5]
2274	2275	 # [2]
2278	2279	 # [2]
2280	2281	 # [2]
2284	2285	 # [2]
2288	2289	 # [2]
22AC	22AF	 # [4]
22E0	22E3	 # [4]
22EA	22ED	 # [4]
2329	232A	 # [2]
2460	24EA	 # [139]
2A0C		
2A74	2A76	 # [3]
2ADC		
2C7C	2C7D	 # [2]
2D6F		
2E9F		
2EF3		
2F00	2FD5	 # [214]
3000		
3036		
3038	303A	 # [3]
304C		
304E		
3050		
3052		
3054		
3056		
3058		
305A		
305C		
305E		
3060		
3062		
3065		
3067		
3069		
3070	3071	 # [2]
3073	3074	 # [2]
3076	3077	 # [2]
3079	307A	 # [2]
307C	307D	 # [2]
3094		
309B	309C	 # [2]
309E	309F	 # [2]
30AC		
30AE		
30B0		
30B2		
30B4		
30B6		
30B8		
30BA		
30BC		
30BE		
30C0		
30C2		
30C5		
30C7		
30C9		
30D0	30D1	 # [2]
30D3	30D4	 # [2]
30D6	30D7	 # [2]
30D9	30DA	 # [2]
30DC	30DD	 # [2]
30F4		
30F7	30FA	 # [4]
30FE	30FF	 # [2]
3131	318E	 # [94]
3192	319F	 # [14]
3200	321E	 # [31]
3220	3247	 # [40]
3250	327E	 # [47]
3280	32FE	 # [127]
3300	33FF	 # [256]
A770		
AC00	D7A3	 # [11_172]
F900	FA0D	 # [270]
FA10		
FA12		
FA15	FA1E	 # [10]
FA20		
FA22		
FA25	FA26	 # [2]
FA2A	FA2D	 # [4]
FA30	FA6D	 # [62]
FA70	FAD9	 # [106]
FB00	FB06	 # [7]
FB13	FB17	 # [5]
FB1D		
FB1F	FB36	 # [24]
FB38	FB3C	 # [5]
FB3E		
FB40	FB41	 # [2]
FB43	FB44	 # [2]
FB46	FBB1	 # [108]
FBD3	FD3D	 # [363]
FD50	FD8F	 # [64]
FD92	FDC7	 # [54]
FDF0	FDFC	 # [13]
FE10	FE19	 # [10]
FE30	FE44	 # [21]
FE47	FE52	 # [12]
FE54	FE66	 # [19]
FE68	FE6B	 # [4]
FE70	FE72	 # [3]
FE74		
FE76	FEFC	 # [135]
FF01	FFBE	 # [190]
FFC2	FFC7	 # [6]
FFCA	FFCF	 # [6]
FFD2	FFD7	 # [6]
FFDA	FFDC	 # [3]
FFE0	FFE6	 # [7]
FFE8	FFEE	 # [7]
1109A		
1109C		
110AB		
1D15E	1D164	 # [7]
1D1BB	1D1C0	 # [6]
1D400	1D454	 # [85]
1D456	1D49C	 # [71]
1D49E	1D49F	 # [2]
1D4A2		
1D4A5	1D4A6	 # [2]
1D4A9	1D4AC	 # [4]
1D4AE	1D4B9	 # [12]
1D4BB		
1D4BD	1D4C3	 # [7]
1D4C5	1D505	 # [65]
1D507	1D50A	 # [4]
1D50D	1D514	 # [8]
1D516	1D51C	 # [7]
1D51E	1D539	 # [28]
1D53B	1D53E	 # [4]
1D540	1D544	 # [5]
1D546		
1D54A	1D550	 # [7]
1D552	1D6A5	 # [340]
1D6A8	1D7CB	 # [292]
1D7CE	1D7FF	 # [50]
1F100	1F10A	 # [11]
1F110	1F12E	 # [31]
1F131		
1F13D		
1F13F		
1F142		
1F146		
1F14A	1F14E	 # [5]
1F190		
1F200		
1F210	1F231	 # [34]
1F240	1F248	 # [9]
2F800	2FA1D	 # [542]
END
