./usr/bin/addr2line
./usr/bin/gccbug
./usr/bin/objcopy
./usr/bin/readelf
./usr/include/arm
./usr/include/arm/ansi.h
./usr/include/arm/armreg.h
./usr/include/arm/asm.h
./usr/include/arm/atomic.h
./usr/include/arm/blockio.h
./usr/include/arm/bus.h
./usr/include/arm/cdefs.h
./usr/include/arm/conf.h
./usr/include/arm/cpu.h
./usr/include/arm/cpuconf.h
./usr/include/arm/cpufunc.h
./usr/include/arm/db_machdep.h
./usr/include/arm/disklabel.h
./usr/include/arm/elf_abi.h
./usr/include/arm/endian.h
./usr/include/arm/fiq.h
./usr/include/arm/float.h
./usr/include/arm/fp.h
./usr/include/arm/frame.h
./usr/include/arm/ieee.h
./usr/include/arm/ieeefp.h
./usr/include/arm/internal_types.h
./usr/include/arm/isa_machdep.h
./usr/include/arm/katelib.h
./usr/include/arm/limits.h
./usr/include/arm/lock.h
./usr/include/arm/machdep.h
./usr/include/arm/math.h
./usr/include/arm/param.h
./usr/include/arm/pcb.h
./usr/include/arm/pci_machdep.h
./usr/include/arm/pio.h
./usr/include/arm/pmap.h
./usr/include/arm/proc.h
./usr/include/arm/profile.h
./usr/include/arm/pte.h
./usr/include/arm/ptrace.h
./usr/include/arm/reg.h
./usr/include/arm/reloc.h
./usr/include/arm/rtc.h
./usr/include/arm/setjmp.h
./usr/include/arm/signal.h
./usr/include/arm/softintr.h
./usr/include/arm/spinlock.h
./usr/include/arm/stdarg.h
./usr/include/arm/swi.h
./usr/include/arm/sysarch.h
./usr/include/arm/trap.h
./usr/include/arm/types.h
./usr/include/arm/undefined.h
./usr/include/arm/vmparam.h
./usr/include/bfd.h
./usr/include/bfdlink.h
./usr/include/cats
./usr/include/cats/ansi.h
./usr/include/cats/asm.h
./usr/include/cats/atomic.h
./usr/include/cats/bootconfig.h
./usr/include/cats/bus.h
./usr/include/cats/cdefs.h
./usr/include/cats/conf.h
./usr/include/cats/cpu.h
./usr/include/cats/cyclone_boot.h
./usr/include/cats/db_machdep.h
./usr/include/cats/disklabel.h
./usr/include/cats/elf_abi.h
./usr/include/cats/endian.h
./usr/include/cats/exec.h
./usr/include/cats/float.h
./usr/include/cats/fp.h
./usr/include/cats/frame.h
./usr/include/cats/ieee.h
./usr/include/cats/ieeefp.h
./usr/include/cats/internal_types.h
./usr/include/cats/intr.h
./usr/include/cats/irqhandler.h
./usr/include/cats/isa_machdep.h
./usr/include/cats/limits.h
./usr/include/cats/lock.h
./usr/include/cats/math.h
./usr/include/cats/param.h
./usr/include/cats/pcb.h
./usr/include/cats/pio.h
./usr/include/cats/pmap.h
./usr/include/cats/proc.h
./usr/include/cats/profile.h
./usr/include/cats/psl.h
./usr/include/cats/ptrace.h
./usr/include/cats/reg.h
./usr/include/cats/reloc.h
./usr/include/cats/rtc.h
./usr/include/cats/setjmp.h
./usr/include/cats/signal.h
./usr/include/cats/spinlock.h
./usr/include/cats/stdarg.h
./usr/include/cats/sysarch.h
./usr/include/cats/trap.h
./usr/include/cats/types.h
./usr/include/cats/vmparam.h
./usr/include/dis-asm.h
./usr/include/g++/arm-unknown-openbsd3.6
./usr/include/g++/arm-unknown-openbsd3.6/bits
./usr/include/g++/arm-unknown-openbsd3.6/bits/atomicity.h
./usr/include/g++/arm-unknown-openbsd3.6/bits/basic_file.h
./usr/include/g++/arm-unknown-openbsd3.6/bits/c++config.h
./usr/include/g++/arm-unknown-openbsd3.6/bits/c++io.h
./usr/include/g++/arm-unknown-openbsd3.6/bits/c++locale.h
./usr/include/g++/arm-unknown-openbsd3.6/bits/codecvt_specializations.h
./usr/include/g++/arm-unknown-openbsd3.6/bits/ctype_base.h
./usr/include/g++/arm-unknown-openbsd3.6/bits/ctype_inline.h
./usr/include/g++/arm-unknown-openbsd3.6/bits/ctype_noninline.h
./usr/include/g++/arm-unknown-openbsd3.6/bits/gthr-default.h
./usr/include/g++/arm-unknown-openbsd3.6/bits/gthr-posix.h
./usr/include/g++/arm-unknown-openbsd3.6/bits/gthr-single.h
./usr/include/g++/arm-unknown-openbsd3.6/bits/gthr.h
./usr/include/g++/arm-unknown-openbsd3.6/bits/messages_members.h
./usr/include/g++/arm-unknown-openbsd3.6/bits/os_defines.h
./usr/include/g++/arm-unknown-openbsd3.6/bits/time_members.h
./usr/include/g++/backward
./usr/include/g++/backward/algo.h
./usr/include/g++/backward/algobase.h
./usr/include/g++/backward/alloc.h
./usr/include/g++/backward/backward_warning.h
./usr/include/g++/backward/bvector.h
./usr/include/g++/backward/complex.h
./usr/include/g++/backward/defalloc.h
./usr/include/g++/backward/deque.h
./usr/include/g++/backward/fstream.h
./usr/include/g++/backward/function.h
./usr/include/g++/backward/hash_map.h
./usr/include/g++/backward/hash_set.h
./usr/include/g++/backward/hashtable.h
./usr/include/g++/backward/heap.h
./usr/include/g++/backward/iomanip.h
./usr/include/g++/backward/iostream.h
./usr/include/g++/backward/istream.h
./usr/include/g++/backward/iterator.h
./usr/include/g++/backward/list.h
./usr/include/g++/backward/map.h
./usr/include/g++/backward/multimap.h
./usr/include/g++/backward/multiset.h
./usr/include/g++/backward/new.h
./usr/include/g++/backward/ostream.h
./usr/include/g++/backward/pair.h
./usr/include/g++/backward/queue.h
./usr/include/g++/backward/rope.h
./usr/include/g++/backward/set.h
./usr/include/g++/backward/slist.h
./usr/include/g++/backward/stack.h
./usr/include/g++/backward/stream.h
./usr/include/g++/backward/streambuf.h
./usr/include/g++/backward/strstream
./usr/include/g++/backward/tempbuf.h
./usr/include/g++/backward/tree.h
./usr/include/g++/backward/vector.h
./usr/include/g++/bits
./usr/include/g++/bits/basic_ios.h
./usr/include/g++/bits/basic_ios.tcc
./usr/include/g++/bits/basic_string.h
./usr/include/g++/bits/basic_string.tcc
./usr/include/g++/bits/boost_concept_check.h
./usr/include/g++/bits/char_traits.h
./usr/include/g++/bits/cmath.tcc
./usr/include/g++/bits/codecvt.h
./usr/include/g++/bits/concept_check.h
./usr/include/g++/bits/cpp_type_traits.h
./usr/include/g++/bits/deque.tcc
./usr/include/g++/bits/fpos.h
./usr/include/g++/bits/fstream.tcc
./usr/include/g++/bits/functexcept.h
./usr/include/g++/bits/gslice.h
./usr/include/g++/bits/gslice_array.h
./usr/include/g++/bits/indirect_array.h
./usr/include/g++/bits/ios_base.h
./usr/include/g++/bits/istream.tcc
./usr/include/g++/bits/list.tcc
./usr/include/g++/bits/locale_classes.h
./usr/include/g++/bits/locale_facets.h
./usr/include/g++/bits/locale_facets.tcc
./usr/include/g++/bits/localefwd.h
./usr/include/g++/bits/mask_array.h
./usr/include/g++/bits/ostream.tcc
./usr/include/g++/bits/pthread_allocimpl.h
./usr/include/g++/bits/slice_array.h
./usr/include/g++/bits/sstream.tcc
./usr/include/g++/bits/stl_algo.h
./usr/include/g++/bits/stl_algobase.h
./usr/include/g++/bits/stl_alloc.h
./usr/include/g++/bits/stl_bvector.h
./usr/include/g++/bits/stl_construct.h
./usr/include/g++/bits/stl_deque.h
./usr/include/g++/bits/stl_function.h
./usr/include/g++/bits/stl_heap.h
./usr/include/g++/bits/stl_iterator.h
./usr/include/g++/bits/stl_iterator_base_funcs.h
./usr/include/g++/bits/stl_iterator_base_types.h
./usr/include/g++/bits/stl_list.h
./usr/include/g++/bits/stl_map.h
./usr/include/g++/bits/stl_multimap.h
./usr/include/g++/bits/stl_multiset.h
./usr/include/g++/bits/stl_numeric.h
./usr/include/g++/bits/stl_pair.h
./usr/include/g++/bits/stl_pthread_alloc.h
./usr/include/g++/bits/stl_queue.h
./usr/include/g++/bits/stl_raw_storage_iter.h
./usr/include/g++/bits/stl_relops.h
./usr/include/g++/bits/stl_set.h
./usr/include/g++/bits/stl_stack.h
./usr/include/g++/bits/stl_tempbuf.h
./usr/include/g++/bits/stl_threads.h
./usr/include/g++/bits/stl_tree.h
./usr/include/g++/bits/stl_uninitialized.h
./usr/include/g++/bits/stl_vector.h
./usr/include/g++/bits/stream_iterator.h
./usr/include/g++/bits/streambuf.tcc
./usr/include/g++/bits/streambuf_iterator.h
./usr/include/g++/bits/stringfwd.h
./usr/include/g++/bits/type_traits.h
./usr/include/g++/bits/valarray_array.h
./usr/include/g++/bits/valarray_array.tcc
./usr/include/g++/bits/valarray_meta.h
./usr/include/g++/bits/vector.tcc
./usr/include/g++/cxxabi.h
./usr/include/g++/exception_defines.h
./usr/include/g++/ext
./usr/include/g++/ext/algorithm
./usr/include/g++/ext/enc_filebuf.h
./usr/include/g++/ext/functional
./usr/include/g++/ext/hash_map
./usr/include/g++/ext/hash_set
./usr/include/g++/ext/iterator
./usr/include/g++/ext/memory
./usr/include/g++/ext/numeric
./usr/include/g++/ext/rb_tree
./usr/include/g++/ext/rope
./usr/include/g++/ext/ropeimpl.h
./usr/include/g++/ext/slist
./usr/include/g++/ext/stdio_filebuf.h
./usr/include/g++/ext/stl_hash_fun.h
./usr/include/g++/ext/stl_hashtable.h
./usr/include/g++/ext/stl_rope.h
./usr/include/g++/ios
./usr/include/g++/istream
./usr/include/g++/limits
./usr/include/g++/locale
./usr/include/g++/ostream
./usr/include/g++/streambuf
./usr/include/ieeefp.h
./usr/include/unwind.h
./usr/lib/crtbegin.o
./usr/lib/crtbeginS.o
./usr/lib/crtend.o
./usr/lib/crtendS.o
./usr/lib/gcc-lib/arm-unknown-openbsd3.6/3.3.5/include
./usr/lib/gcc-lib/arm-unknown-openbsd3.6/3.3.5/include/unwind.h
./usr/lib/gcc-lib/arm-unknown-openbsd3.6/3.3.5/libgcc.a
./usr/lib/libasn1_pic.a
./usr/lib/libbfd.a
./usr/lib/libbfd.la
./usr/lib/libc_pic.a
./usr/lib/libcom_err_pic.a
./usr/lib/libcrypto_pic.a
./usr/lib/libcurses++_pic.a
./usr/lib/libcurses_pic.a
./usr/lib/libdes_pic.a
./usr/lib/libedit_pic.a
./usr/lib/libform_pic.a
./usr/lib/libfrtbegin_pic.a
./usr/lib/libg2c_pic.a
./usr/lib/libgssapi_pic.a
./usr/lib/libiberty_pic.a
./usr/lib/libkadm5clnt_pic.a
./usr/lib/libkadm5srv_pic.a
./usr/lib/libkafs_pic.a
./usr/lib/libkrb5_pic.a
./usr/lib/libkvm_pic.a
./usr/lib/libm_pic.a
./usr/lib/libmenu_pic.a
./usr/lib/libncurses_pic.a
./usr/lib/libobjc_pic.a
./usr/lib/libocurses_pic.a
./usr/lib/libopcodes.a
./usr/lib/libopcodes.la
./usr/lib/libossaudio_pic.a
./usr/lib/libotermcap_pic.a
./usr/lib/libpanel_pic.a
./usr/lib/libpcap_pic.a
./usr/lib/libperl_pic.a
./usr/lib/libpthread_pic.a
./usr/lib/libreadline_pic.a
./usr/lib/libsectok_pic.a
./usr/lib/libskey_pic.a
./usr/lib/libssl_pic.a
./usr/lib/libsupc++.a
./usr/lib/libtermcap_pic.a
./usr/lib/libtermlib_pic.a
./usr/lib/libusbhid_pic.a
./usr/lib/libutil_pic.a
./usr/lib/libwrap_pic.a
./usr/lib/libz_pic.a
./usr/libdata/ldscripts
./usr/libdata/ldscripts/armelf_obsd.x
./usr/libdata/ldscripts/armelf_obsd.xbn
./usr/libdata/ldscripts/armelf_obsd.xc
./usr/libdata/ldscripts/armelf_obsd.xn
./usr/libdata/ldscripts/armelf_obsd.xr
./usr/libdata/ldscripts/armelf_obsd.xs
./usr/libdata/ldscripts/armelf_obsd.xsc
./usr/libdata/ldscripts/armelf_obsd.xu
./usr/libdata/ldscripts/armelf_obsd.xz
./usr/libdata/ldscripts/armelfb_obsd.x
./usr/libdata/ldscripts/armelfb_obsd.xbn
./usr/libdata/ldscripts/armelfb_obsd.xc
./usr/libdata/ldscripts/armelfb_obsd.xn
./usr/libdata/ldscripts/armelfb_obsd.xr
./usr/libdata/ldscripts/armelfb_obsd.xs
./usr/libdata/ldscripts/armelfb_obsd.xsc
./usr/libdata/ldscripts/armelfb_obsd.xu
./usr/libdata/ldscripts/armelfb_obsd.xz
./usr/share/man/cat1/objcopy.0
