# !!!!!!!   DO NOT EDIT THIS FILE   !!!!!!!
# This file is machine-generated by lib/unicore/mktables from the Unicode
# database, Version 6.2.0.  Any changes made here will be lost!

# !!!!!!!   INTERNAL PERL USE ONLY   !!!!!!!
# This file is for internal use by core Perl only.  The format and even the
# name or existence of this file are subject to change without notice.  Don't
# use it directly.


return <<'END';
0D82	0D83
0D85	0D96
0D9A	0DB1
0DB3	0DBB
0DBD		
0DC0	0DC6
0DCA		
0DCF	0DD4
0DD6		
0DD8	0DDF
0DF2	0DF4
END
