.\"	$OpenBSD: RAND_cleanup.3,v 1.2 2016/11/06 15:52:50 jmc Exp $
.\"
.Dd $Mdocdate: November 6 2016 $
.Dt RAND_CLEANUP 3
.Os
.Sh NAME
.Nm RAND_cleanup
.Nd erase the PRNG state
.Sh SYNOPSIS
.In openssl/rand.h
.Ft void
.Fn RAND_cleanup void
.Sh DESCRIPTION
.Fn RAND_cleanup
erases the memory used by the PRNG.
.Sh HISTORY
.Fn RAND_cleanup
is available in all versions of SSLeay and OpenSSL.
