.\"	$OpenBSD: grep.1,v 1.26 2004/04/17 20:10:55 jmc Exp $
.\" Copyright (c) 1980, 1990, 1993
.\"	The Regents of the University of California.  All rights reserved.
.\"
.\" Redistribution and use in source and binary forms, with or without
.\" modification, are permitted provided that the following conditions
.\" are met:
.\" 1. Redistributions of source code must retain the above copyright
.\"    notice, this list of conditions and the following disclaimer.
.\" 2. Redistributions in binary form must reproduce the above copyright
.\"    notice, this list of conditions and the following disclaimer in the
.\"    documentation and/or other materials provided with the distribution.
.\" 3. Neither the name of the University nor the names of its contributors
.\"    may be used to endorse or promote products derived from this software
.\"    without specific prior written permission.
.\"
.\" THIS SOFTWARE IS PROVIDED BY THE REGENTS AND CONTRIBUTORS ``AS IS'' AND
.\" ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE
.\" IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE
.\" ARE DISCLAIMED.  IN NO EVENT SHALL THE REGENTS OR CONTRIBUTORS BE LIABLE
.\" FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL
.\" DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS
.\" OR SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION)
.\" HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT
.\" LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY
.\" OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF
.\" SUCH DAMAGE.
.\"
.\"	@(#)grep.1	8.3 (Berkeley) 4/18/94
.\"
.Dd July 3, 1999
.Dt GREP 1
.Os
.Sh NAME
.Nm grep, egrep, fgrep, zgrep, zegrep, zfgrep
.Nd file pattern searcher
.Sh SYNOPSIS
.Nm grep
.Op Fl AB Ar num
.Op Fl CEFGHILPRSUVZabchilnoqsvwx
.Op Fl -context Ns Op = Ns Ar num
.Op Fl -binary-files Ns = Ns Ar value
.Op Fl -line-buffered
.Op Fl e Ar pattern
.Op Fl f Ar file
.Op Ar pattern
.Op Ar
.Sh DESCRIPTION
The
.Nm grep
utilities search the given input files selecting lines that match one
or more patterns.
By default, a pattern matches an input line if any regular expression
(RE) in the pattern matches the input line without its trailing
newline.
An empty expression matches every line.
Each input line that matches at least one of the patterns is written
to the standard output.
.Pp
The
.Nm grep
utility is used for simple patterns and
.Xr ex 1
or
.Xr ed 1
style regular expressions.
The
.Nm egrep
utility can handle extended regular expressions and multi-line
patterns.
The
.Nm fgrep
utility is quick but can handle only fixed patterns consisting of one
or more lines, allowing any of the pattern lines to match a portion of
the input.
The
.Nm zgrep ,
.Nm zegrep ,
and
.Nm zfgrep
utilities act like
.Nm grep ,
.Nm egrep ,
and
.Nm fgrep
respectively but accept input files compressed with the
.Xr compress 1
or
.Xr gzip 1
compression utilities.
.Pp
The following options are available:
.Bl -tag -width indent
.It Fl A Ar num
Print
.Ar num
lines of trailing context after each match.
.It Fl B Ar num
Print
.Ar num
lines of leading context before each match.
.It Fl C
Print 2 lines of leading and trailing context after each match.
Equivalent to
.Fl A
.Ar 2
.Fl B
.Ar 2 .
.It Fl E
Force
.Nm grep
to behave as
.Nm egrep .
.It Fl F
Force
.Nm grep
to behave as
.Nm fgrep .
.It Fl G
Force
.Nm grep
to behave as
.Nm grep .
.It Fl H
If
.Fl R
is specified, follow symbolic links only if they were explicitly listed
on the command line.
.It Fl I
Ignore binary files.
.It Fl L
Only the names of files not containing selected lines are written to
standard output.
Pathnames are listed once per file searched.
If the standard input is searched, the pathname
.Sq Fl
is written.
.It Fl P
If
.Fl R
is specified, no symbolic links are followed.
.It Fl R
Recursively search subdirectories listed.
.It Fl S
If
.Fl R
is specified, all symbolic links are followed.
.It Fl U
Search binary files, but do not attempt to print them.
.It Fl V
Display version information.
.It Fl Z
Force
.Nm grep
to behave as
.Nm zgrep .
.It Fl a
Treat all files as text.
.It Fl b
The offset in bytes of a matched pattern is
displayed in front of the respective matched line.
.It Fl c
Only a count of selected lines is written to standard output.
.It Fl e Ar expression
Specify a pattern used during the search of the input.
Multiple
.Fl e
options can be used to specify multiple patterns; an input line is
selected if it matches any of the specified patterns.
.It Fl f Ar pattern_file
Read one or more newline separated patterns from
.Ar pattern_file .
Newlines are not considered part of a pattern.
.It Fl h
Never print filename headers with output lines.
.It Fl i
Perform case insensitive matching.
.It Fl l
Only the names of files containing selected lines are written to
standard output.
Pathnames are listed once per file searched.
If the standard input is searched, the pathname
.Sq -
is written.
.It Fl n
Each output line is preceded by its relative line number in the file,
starting at line 1.
The line number counter is reset for each file processed.
This option is ignored if
.Fl c ,
.Fl l ,
or
.Fl q
is
specified.
.It Fl o
Always print filename headers with output lines.
.It Fl q
Suppress normal output.
.It Fl s
Silent mode.
Nonexistent and unreadable files are ignored.
.It Fl v
Selected lines are those
.Em not
matching any of the specified patterns.
.It Fl w
The expression is searched for as a word (as if surrounded by `[[:<:]]'
and `[[:>:]]', see
.Xr re_format 7 ) .
.It Fl x
Only input lines selected against an entire fixed string or regular
expression are considered to be matching lines.
.Sm off
.It Fl Fl context Op = Ar num
.Sm on
Print
.Ar num
lines of leading and trailing context.
Default is 2.
.Sm off
.It Fl Fl binary-files No = Ar value
.Sm on
Controls searching and printing of binary files.
Options are
.Ar binary ,
the default, search binary files but do not print them;
.Ar without-match ,
do not search binary files;
and
.Ar text ,
treat all files as text.
.It Fl Fl line-buffered
Force output to be line buffered.
By default, output is line buffered when standard output is a terminal
and block buffered otherwise.
.Pp
.El
If no file arguments are specified, the standard input is used.
.Sh RETURN VALUES
The
.Nm grep
utility exits with one of the following values:
.Pp
.Bl -tag -width flag -compact
.It Li 0
One or more lines were selected.
.It Li 1
No lines were selected.
.It Li >1
An error occurred.
.El
.Sh EXTENDED REGULAR EXPRESSIONS
The following characters are interpreted by
.Nm egrep :
.Pp
.Bl -tag -width flag -compact
.It Cm \&$
Align the match from the end of the line.
.It Cm \&^
Align the match from the beginning of the line.
.It Cm \&|
Add another pattern (see example below).
.It Cm \&?
Match 1 or less sequential repetitions of the pattern.
.It Cm \&+
Match 1 or more sequential repetitions of the pattern.
.It Cm \&*
Match 0 or more sequential repetitions of the pattern.
.It Cm \&{}
Match specified number of sequential repetitions of the pattern.
.It Cm \&[]
Match any single character or range of characters
enclosed in the brackets.
.It Cm \&\e
Escape special characters which have meaning to
.Nm egrep ,
the set of `$.^[]|?+*{}()\e'.
.El
.Sh EXAMPLES
To find all occurrences of the word patricia in a file:
.Pp
.Dl grep patricia myfile
.Pp
To find all occurrences of the pattern
.Ql \&.Pp
at the beginning of a line:
.Pp
.Dl grep '^\e.Pp'
.Pp
The apostrophes ensure the entire expression is evaluated by
.Nm grep
instead of by the
user's shell.
The caret
.Ql \&^
matches the null string at the beginning of a line,
and the
.Ql \&\e
escapes the
.Ql \&.
which would otherwise match any character.
.Pp
To find all lines in a file which do not contain the words foo or bar:
.Pp
.Dl grep -v -e foo -e bar myfile
.Pp
A simple example of an extended regular expression:
.Pp
.Dl egrep '19|20|25' calendar
.Pp
Peruses the file calendar looking for either 19, 20
or 25.
.Sh SEE ALSO
.Xr ed 1 ,
.Xr ex 1 ,
.Xr sed 1 ,
.Xr regex 3 ,
.Xr regexp 3 ,
.Xr re_format 7
.Sh HISTORY
The
.Nm grep
command appeared in
.At v6 .
