.\" $Id: reset_scanner.1,v 1.2 2000/04/15 11:46:01 aaron Exp $
.\" PINT Pint Is Not TWAIN - common scanner driver interface for UN*X
.\" Copyright (C) 1994 Kenneth Stailey kstailey@leidecker.gsfc.nasa.gov
.\"
.\" This program is free software; you can redistribute it and/or modify
.\" it under the terms of the GNU General Public License as published by
.\" the Free Software Foundation; either version 2 of the License, or
.\" (at your option) any later version.
.\"
.\" This program is distributed in the hope that it will be useful,
.\" but WITHOUT ANY WARRANTY; without even the implied warranty of
.\" MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
.\" GNU General Public License for more details.
.\"
.\" You should have received a copy of the GNU General Public License
.\" along with this program; if not, write to the Free Software
.\" Foundation, Inc., 675 Mass Ave, Cambridge, MA 02139, USA.
.\"
.TH reset-scanner 1 "25 October 1994"
.SH NAME
reset-scanner - clear error conditions on the scanner
.SH SYNOPSIS
.B reset-scanner
.RI [ -l <logical-name-of-scanner-to-use>]
.SH DESCRIPTION
If the scanner gets stuck and the error lights go on and you wish that
you could push the reset button on it but there isn't one, run this (as
the superuser) instead and it will send a Bus Device Reset (BDR) to the
scanner.
.SH AUTHOR
.nf
Kenneth Stailey (kstailey@gnu.ai.mit.edu, kstailey@leidecker.gsfc.nasa.gov)
.fi
