.\" Copyright (c) 2000 Kungliga Tekniska Högskolan
.\" (Royal Institute of Technology, Stockholm, Sweden).
.\" All rights reserved.
.\" 
.\" Redistribution and use in source and binary forms, with or without
.\" modification, are permitted provided that the following conditions
.\" are met:
.\" 
.\" 1. Redistributions of source code must retain the above copyright
.\"    notice, this list of conditions and the following disclaimer.
.\" 
.\" 2. Redistributions in binary form must reproduce the above copyright
.\"    notice, this list of conditions and the following disclaimer in the
.\"    documentation and/or other materials provided with the distribution.
.\" 
.\" 3. Neither the name of the Institute nor the names of its contributors
.\"    may be used to endorse or promote products derived from this software
.\"    without specific prior written permission.
.\" 
.\" THIS SOFTWARE IS PROVIDED BY THE INSTITUTE AND CONTRIBUTORS ``AS IS'' AND
.\" ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE
.\" IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE
.\" ARE DISCLAIMED.  IN NO EVENT SHALL THE INSTITUTE OR CONTRIBUTORS BE LIABLE
.\" FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL
.\" DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS
.\" OR SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION)
.\" HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT
.\" LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY
.\" OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF
.\" SUCH DAMAGE.
.\"
.\" $arla: aklog.1,v 1.8 2003/06/04 12:08:45 tol Exp $
.\"
.Dd August 06, 2000
.Dt AKLOG 1
.Os "The Arla Project"
.Sh NAME
.Nm aklog
.Nd
Fetches tokens from your ticket-file.
.Sh SYNOPSIS
.Nm
.Op Fl cell Ar <cell name>
.Op Fl createuser Ar <cell name>
.Op Fl debug Ar <cell name>
.Op Fl help Ar <cell name>
.Op Fl hosts Ar <cell name>
.Op Fl krbrealm Ar <cell name>
.Op Fl noprdb Ar <cell name>
.Op Fl path Ar <cell name>
.Op Fl quiet Ar <cell name>
.Op Fl unlog Ar <cell name>
.Op Fl version Ar <cell name>
.Op Fl zsubs Ar <cell name>
.Ar <cell or path>
.Sh DESCRIPTION
Supported options:
.Bl -tag -width Ds
.It Fl cell Ar <cell name>
cell to authenticate to
.It Fl createuser Ar <cell name>
create PTS user in remote cell
.It Fl debug Ar <cell name>
print debugging information
.It Fl help Ar <cell name>
print help
.It Fl hosts Ar <cell name>
print host address information (unimplemented)
.It Fl krbrealm Ar <cell name>
kerberos realm for cell
.It Fl noprdb Ar <cell name>
don't try to determine AFS ID
.It Fl path Ar <cell name>
AFS path to authenticate to
.It Fl quiet Ar <cell name>
fail silently if no ticket cache
.It Fl unlog Ar <cell name>
discard tokens
.It Fl version Ar <cell name>
print version
.It Fl zsubs Ar <cell name>
update zephyr subscriptions (unimplemented)
.El
.Sh ENVIRONMENT
.Nm
will look at the environment variable
.Ev AFSCELL
for the default cellname.
If will also use
.Ev HOME
to find the file ~/.TheseCells
.Sh FILES
.Nm
will look for the files
.Pa ThisCell ,
.Pa TheseCells ,
and
.Pa CellServDB
in the directories
.Pa /usr/arla/etc
and
.Pa /usr/vice/etc
.Sh DIAGNOSTICS
For debugging you can use the flag
.Ar Fl d
for debugging.
.Pp
.Bd -literal
datan# aklog -d
aklog: get_afs_id for lha in cell e.kth.se using pts-db
aklog: get_afs_id for lha@e.kth.se in cell stacken.kth.se using pts-db
aklog: get_afs_id for lha@e.kth.se in cell nada.kth.se using pts-db
aklog: get_afs_id for lha@e.kth.se in cell pdc.kth.se using pts-db
.Ed
.Sh SEE ALSO
.Xr aklog 1,
.Xr klog 1 ,
.Xr tokens 1 ,
.Xr unlog 1
