.\"	Copyright (c) 2000 Kungliga Tekniska Högskolan
.\" $arla: tokens.1,v 1.6 2003/04/25 18:10:26 lha Exp $
.\"
.Dd July 7, 1999
.Dt TOKENS 1
.Os "The Arla Project"
.Sh NAME
.Nm tokens
.Nd
lists all AFS tokens in your current PAG.
.Sh SYNOPSIS
.Nm
.Op Fl verbose , v
.Sh DESCRIPTION
The following flags are supported:
.Bl -tag -width xxxx
.It Fl verbose , v
Generate slightly more verbose output (not particularly useful except for
debugging purposes)
.El
.Pp
The
.Nm
lists all AFS tokens in your current PAG.
.Pp
It looks something like this:
.Bd -literal

Tokens held by Arla:

User's (AFS ID 913) tokens for afs@su.se [Expires Feb 15 02:27]
User's (AFS ID 913) tokens for afs@pdc.kth.se [Expires Feb 15 02:27]
User's (AFS ID 913) tokens for afs@nada.kth.se [Expires Feb 15 02:27]
User's (AFS ID 913) tokens for afs@stacken.kth.se [Expires Feb 15 02:27]
User's (AFS ID 913) tokens for afs@e.kth.se [Expires Feb 15 02:28]
   --End of list--
.Ed
.Pp
If there isn't any AFS tokens,
.Nm
just doesn't list any tokens
.Bd -literal
Tokens held by Arla:

   --End of list--
.Ed
.Pp
.Sh EXIT STATUS
.Nm
returns with exit status 0 (true) if the current PAG has at least 1 valid
AFS token. Otherwise, the exit status of
.Nm
is 1.
.Pp
Thus, you can call this program from a script to determine whether or not
AFS tokens are present. (e.g. in a login script)
.Sh NOTES
The AFS ID printed out may be arbitrary; it can be chosen at the time the
token is set and does not necessarily correspond to the actual AFS ID on
the kaserver.
.Pp
If you have AFS tokens, but they are all expired, the exit status of
.Nm
will be 1, not 0.
.Sh SEE ALSO
.Xr klist 1 ,
.Xr klog 1 ,
.Xr unlog 1
