#	$OpenBSD: Makefile,v 1.5 1998/12/05 00:06:31 espie Exp $
#	$NetBSD: Makefile,v 1.4 1996/11/06 17:59:31 christos Exp $

OBJ=lstAppend.o lstDupl.o lstInit.o lstOpen.o lstAtEnd.o lstEnQueue.o \
    lstInsert.o lstAtFront.o lstIsAtEnd.o lstClose.o lstFind.o lstIsEmpty.o \
    lstRemove.o lstConcat.o lstFindFrom.o lstLast.o lstReplace.o lstFirst.o \
    lstDatum.o lstForEach.o lstMember.o lstSucc.o lstDeQueue.o \
    lstForEachFrom.o lstDestroy.o lstNext.o 

CFLAGS+=-I..
all: ${OBJ}
