#	$OpenBSD: Makefile,v 1.2 2002/04/30 03:23:57 deraadt Exp $

.PATH: ${.CURDIR}/../ramdiskA
RAMDISK=RAMDISKC
XNAME=floppyC
NOBSDRD=1

.include "${.CURDIR}/../common/Makefile.inc"

LISTS+=		${.CURDIR}/list.local
