#	$OpenBSD: Makefile,v 1.1 2002/04/22 02:40:03 deraadt Exp $

.PATH: ${.CURDIR}/../ramdiskA
RAMDISK=RAMDISKC
XNAME=floppyC
NOBSDRD=1

.include "${.CURDIR}/../common/Makefile.inc"

CRUNCHCONFS+=	${.CURDIR}/crunch_local.conf
LISTS+=		${.CURDIR}/list.local
