.\"	$NetBSD: iteconfig_amiga.8,v 1.1 1995/05/12 21:04:30 leo Exp $
.\"
.\" Copyright (c) 1994 Christian E. Hopps
.\" All rights reserved.
.\"
.\" Redistribution and use in source and binary forms, with or without
.\" modification, are permitted provided that the following conditions
.\" are met:
.\" 1. Redistributions of source code must retain the above copyright
.\"    notice, this list of conditions and the following disclaimer.
.\" 2. Redistributions in binary form must reproduce the above copyright
.\"    notice, this list of conditions and the following disclaimer in the
.\"    documentation and/or other materials provided with the distribution.
.\" 3. All advertising materials mentioning features or use of this software
.\"    must display the following acknowledgement:
.\"      This product includes software developed by Christian E. Hopps.
.\" 3. The name of the author may not be used to endorse or promote products
.\"    derived from this software without specific prior written permission
.\"
.\" THIS SOFTWARE IS PROVIDED BY THE AUTHOR ``AS IS'' AND ANY EXPRESS OR
.\" IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED WARRANTIES
.\" OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE DISCLAIMED.
.\" IN NO EVENT SHALL THE AUTHOR BE LIABLE FOR ANY DIRECT, INDIRECT,
.\" INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT
.\" NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; LOSS OF USE,
.\" DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON ANY
.\" THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT
.\" (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF
.\" THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
.\"
.\"
.Dd February 3, 1994
.Dt ITECONFIG 8 amiga
.Os
.Sh NAME
.Nm iteconfig
.Nd modify console attributes at run time
.Sh SYNOPSIS
.Nm iteconfig
.Op Fl i
.Op Fl f Ar file
.Op Fl v Ar volume
.Op Fl p Ar pitch
.Op Fl t Ar msec
.Op Fl w Ar width
.Op Fl h Ar height
.Op Fl d Ar depth
.Op Fl x Ar offset
.Op Fl y Ar offset
.Op Fl b Ar seconds
.Op Ar color ...
.Sh DESCRIPTION
.Nm iteconfig
is used to modify or examine the attributes of the
.Tn Amiga's
console bell and bitmapped console display.
The console bell's volume, pitch, and count may be
specified, as well as
the bitmapped display's width, height, horizontal and
vertical offset, pixel depth, and color map.
.Pp
The following flags are interpreted by
.Nm iteconfig :
.Bl -tag -width indent
.It Fl i
After processing all other arguments,
print information about the console's state.
.It Fl f Ar file
Open and use the terminal named by
.Ar file
rather than the default console
.Pa /dev/ttye0 .
.It Fl v Ar volume
Set the volume of the console bell to
.Ar volume ,
which must be between 0 and 63, inclusive.
.It Fl p Ar pitch
Set the pitch of the console bell to
.Ar pitch ,
which must be between 10 and 1399.
.It Fl t Ar msec
Set the duration of the beep to
.Ar msec
milliseconds which must be between 1 and 5000 (5 seconds).
.It Fl w Ar width
Set the width of the console display to
.Ar width
pixel columns.
.Ar width
must be a positive integer.
.It Fl h Ar height
Set the height of the console display to
.Ar height
pixel rows.
.Ar height
must be a positive integer.
.It Fl d Ar depth
Set the number of bitplanes the console view should use to
.Ar depth .
For example, if
.Ar depth
is 3 then 8 colors will be used.
.It Fl x Ar offset
Set the horizontal offset of the console view on the monitor to
.Ar offset
pixel columns.  The horizontal offset may be a positive or a
negative integer, positive being an offset to the right, negative
to the left.
.It Fl y Ar offset
Set the vertical offset of the console view on the monitor to
.Ar offset
pixel rows.  The vertical offset may be a positive or a negative
integer, positive being an offset down, negative up.
.It Fl b Ar seconds
Set the console screen blanker to kick in after
.Ar seconds .
Disable the blanker if 
.Ar seconds
is 0.
.El
.Pp
Any additional arguments will be interpreted as colors and will
be used to supply the color values for the console view's
color map, starting with the first entry in the map.  (See the
.Sx COLOR SPECIFICATION
section of this manual page for information on how to specify
colors.)
If more colors are supplied than are usable by the console
view, a warning is printed and the extra colors are ignored.
.Sh COLOR SPECIFICATION
Colors are hexadecimal numbers which have one of the following
formats:
.Bl -tag -width "0xRRGGBB"
.It Ar 0xRRGGBB
.Ar RR ,
.Ar GG ,
and
.Ar BB
are taken to be 8-bit values specifying the
intensities of the red, green and blue components, respectively,
of the color to be used.  For example,
.Li 0xff0000
is bright red,
.Li 0xffffff
is white, and
.Li 0x008080
is dark cyan.
.It Ar 0xGG
.Ar GG
is taken to be an 8-bit value specifying the intensity
of grey to be used.  A value of
.Li 0x00
is black, a value of
.Li 0xff
is white, and a value of
.Li 0x80
is a grey
approximately halfway in-between.
.It Ar 0xM
.Ar M
is taken to be the 1-bit monochrome value to be used.
A value of
.Li 0x1
is black, and a value of
.Li 0x0
is white.
.El
