#	$OpenBSD: Makefile,v 1.23 2015/11/14 15:01:39 jmc Exp $
#	$NetBSD: Makefile,v 1.6 1994/12/22 10:50:05 cgd Exp $

# missing: term.7

MAN=	ascii.7 eqn.7 environ.7 glob.7 hier.7 hostname.7 intro.7 kgdb.7 \
	library-specs.7 mailaddr.7 \
	man.7 mandoc_char.7 mdoc.7 mirroring-ports.7 \
	operator.7 packages.7 packages-specs.7 pkgpath.7 ports.7 roff.7 \
	script.7 securelevel.7 tbl.7

.include <bsd.prog.mk>
