./dev/pccons
./dev/scan0
./sbin/fdisk
./sbin/ldconfig
./usr/bin/elf2aout
./usr/bin/ldd
./usr/include/mips
./usr/include/readline
./usr/lib/gcc-lib/mipsel-unknown-openbsd2.4
./usr/lib/gcc-lib/mipsel-unknown-openbsd2.4/2.8.1
./usr/lib/gcc-lib/mipsel-unknown-openbsd2.4/2.8.1/include
./usr/lib/gcc-lib/mipsel-unknown-openbsd2.4/2.8.1/include/objc
./usr/lib/libacl.so.4.1
./usr/lib/libc.so.21.0
./usr/lib/libcrypto.so.1.0
./usr/lib/libcurses.so.5.0
./usr/lib/libdes.so.6.0
./usr/lib/libedit.so.0.0
./usr/lib/libform.so.1.1
./usr/lib/libkadm.so.5.0
./usr/lib/libkafs.so.5.1
./usr/lib/libkdb.so.5.0
./usr/lib/libkrb.so.7.0
./usr/lib/libkvm.so.4.1
./usr/lib/libm.so.0.1
./usr/lib/libmenu.so.1.1
./usr/lib/libocurses.so.3.0
./usr/lib/libotermcap.so.3.0
./usr/lib/libpanel.so.1.1
./usr/lib/libpcap.so.0.2
./usr/lib/libresolv.so.2.0
./usr/lib/libskey.so.1.0
./usr/lib/libssl.so.1.0
./usr/lib/libtermcap.so.5.0
./usr/lib/libtermlib.so.5.0
./usr/lib/libutil.so.4.2
./usr/lib/libwrap.so.1.0
./usr/lib/libz.so.1.3
./usr/lib/perl5/mips-openbsd
./usr/lib/perl5/mips-openbsd/5.00404
./usr/lib/perl5/mips-openbsd/5.00404/CORE
./usr/lib/perl5/mips-openbsd/5.00404/CORE/EXTERN.h
./usr/lib/perl5/mips-openbsd/5.00404/CORE/INTERN.h
./usr/lib/perl5/mips-openbsd/5.00404/CORE/XSUB.h
./usr/lib/perl5/mips-openbsd/5.00404/CORE/av.h
./usr/lib/perl5/mips-openbsd/5.00404/CORE/config.h
./usr/lib/perl5/mips-openbsd/5.00404/CORE/cop.h
./usr/lib/perl5/mips-openbsd/5.00404/CORE/cv.h
./usr/lib/perl5/mips-openbsd/5.00404/CORE/dosish.h
./usr/lib/perl5/mips-openbsd/5.00404/CORE/embed.h
./usr/lib/perl5/mips-openbsd/5.00404/CORE/form.h
./usr/lib/perl5/mips-openbsd/5.00404/CORE/gv.h
./usr/lib/perl5/mips-openbsd/5.00404/CORE/handy.h
./usr/lib/perl5/mips-openbsd/5.00404/CORE/hv.h
./usr/lib/perl5/mips-openbsd/5.00404/CORE/keywords.h
./usr/lib/perl5/mips-openbsd/5.00404/CORE/libperl.a
./usr/lib/perl5/mips-openbsd/5.00404/CORE/mg.h
./usr/lib/perl5/mips-openbsd/5.00404/CORE/nostdio.h
./usr/lib/perl5/mips-openbsd/5.00404/CORE/op.h
./usr/lib/perl5/mips-openbsd/5.00404/CORE/opcode.h
./usr/lib/perl5/mips-openbsd/5.00404/CORE/patchlevel.h
./usr/lib/perl5/mips-openbsd/5.00404/CORE/perl.h
./usr/lib/perl5/mips-openbsd/5.00404/CORE/perlio.h
./usr/lib/perl5/mips-openbsd/5.00404/CORE/perlsdio.h
./usr/lib/perl5/mips-openbsd/5.00404/CORE/perlsfio.h
./usr/lib/perl5/mips-openbsd/5.00404/CORE/perly.h
./usr/lib/perl5/mips-openbsd/5.00404/CORE/pp.h
./usr/lib/perl5/mips-openbsd/5.00404/CORE/proto.h
./usr/lib/perl5/mips-openbsd/5.00404/CORE/regcomp.h
./usr/lib/perl5/mips-openbsd/5.00404/CORE/regexp.h
./usr/lib/perl5/mips-openbsd/5.00404/CORE/scope.h
./usr/lib/perl5/mips-openbsd/5.00404/CORE/sv.h
./usr/lib/perl5/mips-openbsd/5.00404/CORE/unixish.h
./usr/lib/perl5/mips-openbsd/5.00404/CORE/util.h
./usr/lib/perl5/mips-openbsd/5.00404/Config.pm
./usr/lib/perl5/mips-openbsd/5.00404/DynaLoader.pm
./usr/lib/perl5/mips-openbsd/5.00404/FileHandle.pm
./usr/lib/perl5/mips-openbsd/5.00404/auto
./usr/lib/perl5/mips-openbsd/5.00404/auto/DynaLoader
./usr/lib/perl5/mips-openbsd/5.00404/auto/DynaLoader/DynaLoader.a
./usr/lib/perl5/mips-openbsd/5.00404/auto/DynaLoader/autosplit.ix
./usr/lib/perl5/mips-openbsd/5.00404/auto/DynaLoader/dl_expandspec.al
./usr/lib/perl5/mips-openbsd/5.00404/auto/DynaLoader/dl_find_symbol_anywhere.al
./usr/lib/perl5/mips-openbsd/5.00404/auto/DynaLoader/dl_findfile.al
./usr/lib/perl5/mips-openbsd/5.00404/auto/DynaLoader/extralibs.ld
./usr/lib/perl5/mips-openbsd/5.00404/auto/Text
./usr/lib/perl5/mips-openbsd/5.00404/auto/Text/ParseWords
./usr/lib/perl5/mips-openbsd/5.00404/overload.pm
./usr/lib/perl5/mips-openbsd/5.00404/pod
./usr/lib/perl5/mips-openbsd/5.00404/pod/perldiag.pod
./usr/lib/perl5/site_perl/mips-openbsd
./usr/lib/perl5/site_perl/mips-openbsd/a.out.ph
./usr/lib/perl5/site_perl/mips-openbsd/ansidecl.ph
./usr/lib/perl5/site_perl/mips-openbsd/ar.ph
./usr/lib/perl5/site_perl/mips-openbsd/arpa
./usr/lib/perl5/site_perl/mips-openbsd/arpa/ftp.ph
./usr/lib/perl5/site_perl/mips-openbsd/arpa/inet.ph
./usr/lib/perl5/site_perl/mips-openbsd/arpa/nameser.ph
./usr/lib/perl5/site_perl/mips-openbsd/arpa/telnet.ph
./usr/lib/perl5/site_perl/mips-openbsd/arpa/tftp.ph
./usr/lib/perl5/site_perl/mips-openbsd/assert.ph
./usr/lib/perl5/site_perl/mips-openbsd/bfd.ph
./usr/lib/perl5/site_perl/mips-openbsd/bfdlink.ph
./usr/lib/perl5/site_perl/mips-openbsd/bitstring.ph
./usr/lib/perl5/site_perl/mips-openbsd/blf.ph
./usr/lib/perl5/site_perl/mips-openbsd/bm.ph
./usr/lib/perl5/site_perl/mips-openbsd/cast.ph
./usr/lib/perl5/site_perl/mips-openbsd/com_err.ph
./usr/lib/perl5/site_perl/mips-openbsd/cpio.ph
./usr/lib/perl5/site_perl/mips-openbsd/ctype.ph
./usr/lib/perl5/site_perl/mips-openbsd/curses.ph
./usr/lib/perl5/site_perl/mips-openbsd/db.ph
./usr/lib/perl5/site_perl/mips-openbsd/des.ph
./usr/lib/perl5/site_perl/mips-openbsd/dirent.ph
./usr/lib/perl5/site_perl/mips-openbsd/disktab.ph
./usr/lib/perl5/site_perl/mips-openbsd/dlfcn.ph
./usr/lib/perl5/site_perl/mips-openbsd/elf_abi.ph
./usr/lib/perl5/site_perl/mips-openbsd/err.ph
./usr/lib/perl5/site_perl/mips-openbsd/errno.ph
./usr/lib/perl5/site_perl/mips-openbsd/eti.ph
./usr/lib/perl5/site_perl/mips-openbsd/fcntl.ph
./usr/lib/perl5/site_perl/mips-openbsd/float.ph
./usr/lib/perl5/site_perl/mips-openbsd/fnmatch.ph
./usr/lib/perl5/site_perl/mips-openbsd/form.ph
./usr/lib/perl5/site_perl/mips-openbsd/frame.ph
./usr/lib/perl5/site_perl/mips-openbsd/fstab.ph
./usr/lib/perl5/site_perl/mips-openbsd/fts.ph
./usr/lib/perl5/site_perl/mips-openbsd/glob.ph
./usr/lib/perl5/site_perl/mips-openbsd/gmp.ph
./usr/lib/perl5/site_perl/mips-openbsd/grp.ph
./usr/lib/perl5/site_perl/mips-openbsd/histedit.ph
./usr/lib/perl5/site_perl/mips-openbsd/ieeefp.ph
./usr/lib/perl5/site_perl/mips-openbsd/inttypes.ph
./usr/lib/perl5/site_perl/mips-openbsd/iso646.ph
./usr/lib/perl5/site_perl/mips-openbsd/kvm.ph
./usr/lib/perl5/site_perl/mips-openbsd/langinfo.ph
./usr/lib/perl5/site_perl/mips-openbsd/libgen.ph
./usr/lib/perl5/site_perl/mips-openbsd/limits.ph
./usr/lib/perl5/site_perl/mips-openbsd/link.ph
./usr/lib/perl5/site_perl/mips-openbsd/locale.ph
./usr/lib/perl5/site_perl/mips-openbsd/machine
./usr/lib/perl5/site_perl/mips-openbsd/machine/ansi.ph
./usr/lib/perl5/site_perl/mips-openbsd/machine/apmvar.ph
./usr/lib/perl5/site_perl/mips-openbsd/machine/asm.ph
./usr/lib/perl5/site_perl/mips-openbsd/machine/biosvar.ph
./usr/lib/perl5/site_perl/mips-openbsd/machine/bus.ph
./usr/lib/perl5/site_perl/mips-openbsd/machine/cdefs.ph
./usr/lib/perl5/site_perl/mips-openbsd/machine/conf.ph
./usr/lib/perl5/site_perl/mips-openbsd/machine/cpu.ph
./usr/lib/perl5/site_perl/mips-openbsd/machine/cpufunc.ph
./usr/lib/perl5/site_perl/mips-openbsd/machine/cputypes.ph
./usr/lib/perl5/site_perl/mips-openbsd/machine/db_machdep.ph
./usr/lib/perl5/site_perl/mips-openbsd/machine/disklabel.ph
./usr/lib/perl5/site_perl/mips-openbsd/machine/endian.ph
./usr/lib/perl5/site_perl/mips-openbsd/machine/exec.ph
./usr/lib/perl5/site_perl/mips-openbsd/machine/float.ph
./usr/lib/perl5/site_perl/mips-openbsd/machine/frame.ph
./usr/lib/perl5/site_perl/mips-openbsd/machine/freebsd_machdep.ph
./usr/lib/perl5/site_perl/mips-openbsd/machine/gdt.ph
./usr/lib/perl5/site_perl/mips-openbsd/machine/ieeefp.ph
./usr/lib/perl5/site_perl/mips-openbsd/machine/intr.ph
./usr/lib/perl5/site_perl/mips-openbsd/machine/ioctl_fd.ph
./usr/lib/perl5/site_perl/mips-openbsd/machine/joystick.ph
./usr/lib/perl5/site_perl/mips-openbsd/machine/limits.ph
./usr/lib/perl5/site_perl/mips-openbsd/machine/linux_machdep.ph
./usr/lib/perl5/site_perl/mips-openbsd/machine/mouse.ph
./usr/lib/perl5/site_perl/mips-openbsd/machine/npx.ph
./usr/lib/perl5/site_perl/mips-openbsd/machine/param.ph
./usr/lib/perl5/site_perl/mips-openbsd/machine/pcb.ph
./usr/lib/perl5/site_perl/mips-openbsd/machine/pccons.ph
./usr/lib/perl5/site_perl/mips-openbsd/machine/pctr.ph
./usr/lib/perl5/site_perl/mips-openbsd/machine/pcvt_ioctl.ph
./usr/lib/perl5/site_perl/mips-openbsd/machine/pio.ph
./usr/lib/perl5/site_perl/mips-openbsd/machine/pmap.ph
./usr/lib/perl5/site_perl/mips-openbsd/machine/proc.ph
./usr/lib/perl5/site_perl/mips-openbsd/machine/profile.ph
./usr/lib/perl5/site_perl/mips-openbsd/machine/psl.ph
./usr/lib/perl5/site_perl/mips-openbsd/machine/pte.ph
./usr/lib/perl5/site_perl/mips-openbsd/machine/ptrace.ph
./usr/lib/perl5/site_perl/mips-openbsd/machine/reg.ph
./usr/lib/perl5/site_perl/mips-openbsd/machine/segments.ph
./usr/lib/perl5/site_perl/mips-openbsd/machine/setjmp.ph
./usr/lib/perl5/site_perl/mips-openbsd/machine/signal.ph
./usr/lib/perl5/site_perl/mips-openbsd/machine/specialreg.ph
./usr/lib/perl5/site_perl/mips-openbsd/machine/spkr.ph
./usr/lib/perl5/site_perl/mips-openbsd/machine/stdarg.ph
./usr/lib/perl5/site_perl/mips-openbsd/machine/svr4_machdep.ph
./usr/lib/perl5/site_perl/mips-openbsd/machine/sysarch.ph
./usr/lib/perl5/site_perl/mips-openbsd/machine/trap.ph
./usr/lib/perl5/site_perl/mips-openbsd/machine/tss.ph
./usr/lib/perl5/site_perl/mips-openbsd/machine/types.ph
./usr/lib/perl5/site_perl/mips-openbsd/machine/varargs.ph
./usr/lib/perl5/site_perl/mips-openbsd/machine/vm86.ph
./usr/lib/perl5/site_perl/mips-openbsd/machine/vmparam.ph
./usr/lib/perl5/site_perl/mips-openbsd/malloc.ph
./usr/lib/perl5/site_perl/mips-openbsd/math.ph
./usr/lib/perl5/site_perl/mips-openbsd/md4.ph
./usr/lib/perl5/site_perl/mips-openbsd/md5.ph
./usr/lib/perl5/site_perl/mips-openbsd/memory.ph
./usr/lib/perl5/site_perl/mips-openbsd/menu.ph
./usr/lib/perl5/site_perl/mips-openbsd/mpool.ph
./usr/lib/perl5/site_perl/mips-openbsd/ncurses.ph
./usr/lib/perl5/site_perl/mips-openbsd/ndbm.ph
./usr/lib/perl5/site_perl/mips-openbsd/net
./usr/lib/perl5/site_perl/mips-openbsd/net/bpf.ph
./usr/lib/perl5/site_perl/mips-openbsd/net/bpfdesc.ph
./usr/lib/perl5/site_perl/mips-openbsd/net/encap.ph
./usr/lib/perl5/site_perl/mips-openbsd/net/if.ph
./usr/lib/perl5/site_perl/mips-openbsd/net/if_arp.ph
./usr/lib/perl5/site_perl/mips-openbsd/net/if_atm.ph
./usr/lib/perl5/site_perl/mips-openbsd/net/if_dl.ph
./usr/lib/perl5/site_perl/mips-openbsd/net/if_enc.ph
./usr/lib/perl5/site_perl/mips-openbsd/net/if_fddi.ph
./usr/lib/perl5/site_perl/mips-openbsd/net/if_llc.ph
./usr/lib/perl5/site_perl/mips-openbsd/net/if_media.ph
./usr/lib/perl5/site_perl/mips-openbsd/net/if_ppp.ph
./usr/lib/perl5/site_perl/mips-openbsd/net/if_pppvar.ph
./usr/lib/perl5/site_perl/mips-openbsd/net/if_slvar.ph
./usr/lib/perl5/site_perl/mips-openbsd/net/if_stripvar.ph
./usr/lib/perl5/site_perl/mips-openbsd/net/if_tun.ph
./usr/lib/perl5/site_perl/mips-openbsd/net/if_types.ph
./usr/lib/perl5/site_perl/mips-openbsd/net/netisr.ph
./usr/lib/perl5/site_perl/mips-openbsd/net/pfkeyv2.ph
./usr/lib/perl5/site_perl/mips-openbsd/net/ppp-comp.ph
./usr/lib/perl5/site_perl/mips-openbsd/net/ppp_defs.ph
./usr/lib/perl5/site_perl/mips-openbsd/net/radix.ph
./usr/lib/perl5/site_perl/mips-openbsd/net/raw_cb.ph
./usr/lib/perl5/site_perl/mips-openbsd/net/route.ph
./usr/lib/perl5/site_perl/mips-openbsd/net/slcompress.ph
./usr/lib/perl5/site_perl/mips-openbsd/net/slip.ph
./usr/lib/perl5/site_perl/mips-openbsd/net/zlib.ph
./usr/lib/perl5/site_perl/mips-openbsd/netdb.ph
./usr/lib/perl5/site_perl/mips-openbsd/netgroup.ph
./usr/lib/perl5/site_perl/mips-openbsd/nl_types.ph
./usr/lib/perl5/site_perl/mips-openbsd/nlist.ph
./usr/lib/perl5/site_perl/mips-openbsd/obstack.ph
./usr/lib/perl5/site_perl/mips-openbsd/ocurses.ph
./usr/lib/perl5/site_perl/mips-openbsd/olf_abi.ph
./usr/lib/perl5/site_perl/mips-openbsd/panel.ph
./usr/lib/perl5/site_perl/mips-openbsd/paths.ph
./usr/lib/perl5/site_perl/mips-openbsd/pcap-namedb.ph
./usr/lib/perl5/site_perl/mips-openbsd/pcap.ph
./usr/lib/perl5/site_perl/mips-openbsd/poll.ph
./usr/lib/perl5/site_perl/mips-openbsd/protocols
./usr/lib/perl5/site_perl/mips-openbsd/protocols/dumprestore.ph
./usr/lib/perl5/site_perl/mips-openbsd/protocols/routed.ph
./usr/lib/perl5/site_perl/mips-openbsd/protocols/rwhod.ph
./usr/lib/perl5/site_perl/mips-openbsd/protocols/talkd.ph
./usr/lib/perl5/site_perl/mips-openbsd/protocols/timed.ph
./usr/lib/perl5/site_perl/mips-openbsd/pwd.ph
./usr/lib/perl5/site_perl/mips-openbsd/ranlib.ph
./usr/lib/perl5/site_perl/mips-openbsd/re_comp.ph
./usr/lib/perl5/site_perl/mips-openbsd/regex.ph
./usr/lib/perl5/site_perl/mips-openbsd/regexp.ph
./usr/lib/perl5/site_perl/mips-openbsd/resolv.ph
./usr/lib/perl5/site_perl/mips-openbsd/rmd160.ph
./usr/lib/perl5/site_perl/mips-openbsd/scsi.ph
./usr/lib/perl5/site_perl/mips-openbsd/search.ph
./usr/lib/perl5/site_perl/mips-openbsd/setjmp.ph
./usr/lib/perl5/site_perl/mips-openbsd/sgtty.ph
./usr/lib/perl5/site_perl/mips-openbsd/sha1.ph
./usr/lib/perl5/site_perl/mips-openbsd/signal.ph
./usr/lib/perl5/site_perl/mips-openbsd/skey.ph
./usr/lib/perl5/site_perl/mips-openbsd/soundcard.ph
./usr/lib/perl5/site_perl/mips-openbsd/stab.ph
./usr/lib/perl5/site_perl/mips-openbsd/stdarg.ph
./usr/lib/perl5/site_perl/mips-openbsd/stddef.ph
./usr/lib/perl5/site_perl/mips-openbsd/stdio.ph
./usr/lib/perl5/site_perl/mips-openbsd/stdlib.ph
./usr/lib/perl5/site_perl/mips-openbsd/string.ph
./usr/lib/perl5/site_perl/mips-openbsd/strings.ph
./usr/lib/perl5/site_perl/mips-openbsd/struct.ph
./usr/lib/perl5/site_perl/mips-openbsd/sys
./usr/lib/perl5/site_perl/mips-openbsd/sys/acct.ph
./usr/lib/perl5/site_perl/mips-openbsd/sys/audioio.ph
./usr/lib/perl5/site_perl/mips-openbsd/sys/buf.ph
./usr/lib/perl5/site_perl/mips-openbsd/sys/callout.ph
./usr/lib/perl5/site_perl/mips-openbsd/sys/cdefs.ph
./usr/lib/perl5/site_perl/mips-openbsd/sys/cdio.ph
./usr/lib/perl5/site_perl/mips-openbsd/sys/chio.ph
./usr/lib/perl5/site_perl/mips-openbsd/sys/clist.ph
./usr/lib/perl5/site_perl/mips-openbsd/sys/conf.ph
./usr/lib/perl5/site_perl/mips-openbsd/sys/core.ph
./usr/lib/perl5/site_perl/mips-openbsd/sys/device.ph
./usr/lib/perl5/site_perl/mips-openbsd/sys/dir.ph
./usr/lib/perl5/site_perl/mips-openbsd/sys/dirent.ph
./usr/lib/perl5/site_perl/mips-openbsd/sys/disk.ph
./usr/lib/perl5/site_perl/mips-openbsd/sys/disklabel.ph
./usr/lib/perl5/site_perl/mips-openbsd/sys/dkbad.ph
./usr/lib/perl5/site_perl/mips-openbsd/sys/dkio.ph
./usr/lib/perl5/site_perl/mips-openbsd/sys/dkstat.ph
./usr/lib/perl5/site_perl/mips-openbsd/sys/dmap.ph
./usr/lib/perl5/site_perl/mips-openbsd/sys/domain.ph
./usr/lib/perl5/site_perl/mips-openbsd/sys/endian.ph
./usr/lib/perl5/site_perl/mips-openbsd/sys/errno.ph
./usr/lib/perl5/site_perl/mips-openbsd/sys/exec.ph
./usr/lib/perl5/site_perl/mips-openbsd/sys/exec_aout.ph
./usr/lib/perl5/site_perl/mips-openbsd/sys/exec_ecoff.ph
./usr/lib/perl5/site_perl/mips-openbsd/sys/exec_elf.ph
./usr/lib/perl5/site_perl/mips-openbsd/sys/exec_olf.ph
./usr/lib/perl5/site_perl/mips-openbsd/sys/exec_script.ph
./usr/lib/perl5/site_perl/mips-openbsd/sys/extent.ph
./usr/lib/perl5/site_perl/mips-openbsd/sys/fcntl.ph
./usr/lib/perl5/site_perl/mips-openbsd/sys/file.ph
./usr/lib/perl5/site_perl/mips-openbsd/sys/filedesc.ph
./usr/lib/perl5/site_perl/mips-openbsd/sys/filio.ph
./usr/lib/perl5/site_perl/mips-openbsd/sys/gmon.ph
./usr/lib/perl5/site_perl/mips-openbsd/sys/ioccom.ph
./usr/lib/perl5/site_perl/mips-openbsd/sys/ioctl.ph
./usr/lib/perl5/site_perl/mips-openbsd/sys/ioctl_compat.ph
./usr/lib/perl5/site_perl/mips-openbsd/sys/ipc.ph
./usr/lib/perl5/site_perl/mips-openbsd/sys/kcore.ph
./usr/lib/perl5/site_perl/mips-openbsd/sys/kernel.ph
./usr/lib/perl5/site_perl/mips-openbsd/sys/ktrace.ph
./usr/lib/perl5/site_perl/mips-openbsd/sys/lkm.ph
./usr/lib/perl5/site_perl/mips-openbsd/sys/localedef.ph
./usr/lib/perl5/site_perl/mips-openbsd/sys/lock.ph
./usr/lib/perl5/site_perl/mips-openbsd/sys/lockf.ph
./usr/lib/perl5/site_perl/mips-openbsd/sys/malloc.ph
./usr/lib/perl5/site_perl/mips-openbsd/sys/map.ph
./usr/lib/perl5/site_perl/mips-openbsd/sys/mbuf.ph
./usr/lib/perl5/site_perl/mips-openbsd/sys/md5k.ph
./usr/lib/perl5/site_perl/mips-openbsd/sys/midiio.ph
./usr/lib/perl5/site_perl/mips-openbsd/sys/mman.ph
./usr/lib/perl5/site_perl/mips-openbsd/sys/mount.ph
./usr/lib/perl5/site_perl/mips-openbsd/sys/msg.ph
./usr/lib/perl5/site_perl/mips-openbsd/sys/msgbuf.ph
./usr/lib/perl5/site_perl/mips-openbsd/sys/mtio.ph
./usr/lib/perl5/site_perl/mips-openbsd/sys/namei.ph
./usr/lib/perl5/site_perl/mips-openbsd/sys/param.ph
./usr/lib/perl5/site_perl/mips-openbsd/sys/pipe.ph
./usr/lib/perl5/site_perl/mips-openbsd/sys/poll.ph
./usr/lib/perl5/site_perl/mips-openbsd/sys/proc.ph
./usr/lib/perl5/site_perl/mips-openbsd/sys/protosw.ph
./usr/lib/perl5/site_perl/mips-openbsd/sys/ptrace.ph
./usr/lib/perl5/site_perl/mips-openbsd/sys/queue.ph
./usr/lib/perl5/site_perl/mips-openbsd/sys/reboot.ph
./usr/lib/perl5/site_perl/mips-openbsd/sys/resource.ph
./usr/lib/perl5/site_perl/mips-openbsd/sys/resourcevar.ph
./usr/lib/perl5/site_perl/mips-openbsd/sys/scanio.ph
./usr/lib/perl5/site_perl/mips-openbsd/sys/scsiio.ph
./usr/lib/perl5/site_perl/mips-openbsd/sys/select.ph
./usr/lib/perl5/site_perl/mips-openbsd/sys/sem.ph
./usr/lib/perl5/site_perl/mips-openbsd/sys/shm.ph
./usr/lib/perl5/site_perl/mips-openbsd/sys/siginfo.ph
./usr/lib/perl5/site_perl/mips-openbsd/sys/signal.ph
./usr/lib/perl5/site_perl/mips-openbsd/sys/signalvar.ph
./usr/lib/perl5/site_perl/mips-openbsd/sys/simplelock.ph
./usr/lib/perl5/site_perl/mips-openbsd/sys/socket.ph
./usr/lib/perl5/site_perl/mips-openbsd/sys/socketvar.ph
./usr/lib/perl5/site_perl/mips-openbsd/sys/sockio.ph
./usr/lib/perl5/site_perl/mips-openbsd/sys/stat.ph
./usr/lib/perl5/site_perl/mips-openbsd/sys/syscall.ph
./usr/lib/perl5/site_perl/mips-openbsd/sys/syscallargs.ph
./usr/lib/perl5/site_perl/mips-openbsd/sys/sysctl.ph
./usr/lib/perl5/site_perl/mips-openbsd/sys/syslimits.ph
./usr/lib/perl5/site_perl/mips-openbsd/sys/syslog.ph
./usr/lib/perl5/site_perl/mips-openbsd/sys/systm.ph
./usr/lib/perl5/site_perl/mips-openbsd/sys/tablet.ph
./usr/lib/perl5/site_perl/mips-openbsd/sys/termios.ph
./usr/lib/perl5/site_perl/mips-openbsd/sys/time.ph
./usr/lib/perl5/site_perl/mips-openbsd/sys/timeb.ph
./usr/lib/perl5/site_perl/mips-openbsd/sys/times.ph
./usr/lib/perl5/site_perl/mips-openbsd/sys/timex.ph
./usr/lib/perl5/site_perl/mips-openbsd/sys/tprintf.ph
./usr/lib/perl5/site_perl/mips-openbsd/sys/trace.ph
./usr/lib/perl5/site_perl/mips-openbsd/sys/tty.ph
./usr/lib/perl5/site_perl/mips-openbsd/sys/ttychars.ph
./usr/lib/perl5/site_perl/mips-openbsd/sys/ttycom.ph
./usr/lib/perl5/site_perl/mips-openbsd/sys/ttydefaults.ph
./usr/lib/perl5/site_perl/mips-openbsd/sys/ttydev.ph
./usr/lib/perl5/site_perl/mips-openbsd/sys/types.ph
./usr/lib/perl5/site_perl/mips-openbsd/sys/ucred.ph
./usr/lib/perl5/site_perl/mips-openbsd/sys/uio.ph
./usr/lib/perl5/site_perl/mips-openbsd/sys/un.ph
./usr/lib/perl5/site_perl/mips-openbsd/sys/unistd.ph
./usr/lib/perl5/site_perl/mips-openbsd/sys/unpcb.ph
./usr/lib/perl5/site_perl/mips-openbsd/sys/user.ph
./usr/lib/perl5/site_perl/mips-openbsd/sys/utsname.ph
./usr/lib/perl5/site_perl/mips-openbsd/sys/vadvise.ph
./usr/lib/perl5/site_perl/mips-openbsd/sys/vcmd.ph
./usr/lib/perl5/site_perl/mips-openbsd/sys/vlimit.ph
./usr/lib/perl5/site_perl/mips-openbsd/sys/vmmeter.ph
./usr/lib/perl5/site_perl/mips-openbsd/sys/vnode.ph
./usr/lib/perl5/site_perl/mips-openbsd/sys/vnode_if.ph
./usr/lib/perl5/site_perl/mips-openbsd/sys/vsio.ph
./usr/lib/perl5/site_perl/mips-openbsd/sys/wait.ph
./usr/lib/perl5/site_perl/mips-openbsd/sysexits.ph
./usr/lib/perl5/site_perl/mips-openbsd/syslog.ph
./usr/lib/perl5/site_perl/mips-openbsd/tar.ph
./usr/lib/perl5/site_perl/mips-openbsd/tcpd.ph
./usr/lib/perl5/site_perl/mips-openbsd/term.ph
./usr/lib/perl5/site_perl/mips-openbsd/termios.ph
./usr/lib/perl5/site_perl/mips-openbsd/time.ph
./usr/lib/perl5/site_perl/mips-openbsd/ttyent.ph
./usr/lib/perl5/site_perl/mips-openbsd/tzfile.ph
./usr/lib/perl5/site_perl/mips-openbsd/unctrl.ph
./usr/lib/perl5/site_perl/mips-openbsd/unistd.ph
./usr/lib/perl5/site_perl/mips-openbsd/util.ph
./usr/lib/perl5/site_perl/mips-openbsd/utime.ph
./usr/lib/perl5/site_perl/mips-openbsd/utmp.ph
./usr/lib/perl5/site_perl/mips-openbsd/varargs.ph
./usr/lib/perl5/site_perl/mips-openbsd/vis.ph
./usr/lib/perl5/site_perl/mips-openbsd/zconf.ph
./usr/lib/perl5/site_perl/mips-openbsd/zlib.ph
./usr/lib/scrt0.o
./usr/libexec/ld.so
./usr/mdec/mbr
./usr/mdec/msdos5mb.gz
./usr/mipsel-unknown-openbsd2.4
./usr/mipsel-unknown-openbsd2.4/bin
./usr/mipsel-unknown-openbsd2.4/lib
./usr/mipsel-unknown-openbsd2.4/lib/ldscripts
./usr/lib/perl5/site_perl/mips-openbsd/dbm.ph
