# $OpenBSD: Makefile,v 1.2 2018/04/06 14:44:04 patrick Exp $

SUBDIR+=AST
SUBDIR+=Basic
SUBDIR+=Driver
SUBDIR+=Parse
SUBDIR+=Sema
SUBDIR+=Serialization
SUBDIR+=StaticAnalyzer/Checkers
SUBDIR+=intrin

.include <bsd.subdir.mk>
