.\"	$OpenBSD: forward.5,v 1.1 2012/09/12 17:53:32 gilles Exp $
.\"
.\" Copyright (c) 2012 Gilles Chehade <gilles@openbsd.org>
.\"
.\" Permission to use, copy, modify, and distribute this software for any
.\" purpose with or without fee is hereby granted, provided that the above
.\" copyright notice and this permission notice appear in all copies.
.\"
.\" THE SOFTWARE IS PROVIDED "AS IS" AND THE AUTHOR DISCLAIMS ALL WARRANTIES
.\" WITH REGARD TO THIS SOFTWARE INCLUDING ALL IMPLIED WARRANTIES OF
.\" MERCHANTABILITY AND FITNESS. IN NO EVENT SHALL THE AUTHOR BE LIABLE FOR
.\" ANY SPECIAL, DIRECT, INDIRECT, OR CONSEQUENTIAL DAMAGES OR ANY DAMAGES
.\" WHATSOEVER RESULTING FROM LOSS OF USE, DATA OR PROFITS, WHETHER IN AN
.\" ACTION OF CONTRACT, NEGLIGENCE OR OTHER TORTIOUS ACTION, ARISING OUT OF
.\" OR IN CONNECTION WITH THE USE OR PERFORMANCE OF THIS SOFTWARE.
.\"
.Dd $Mdocdate: September 12 2012 $
.Dt FORWARD 5
.Os
.Sh NAME
.Nm forward
.Nd email forwarding information file
.Sh DESCRIPTION
Users may put a file named
.Pa .forward
in their home directory.
If this file exists,
.Xr smtpd 8
will expand it to new delivery envelopes.
.Pp
A
.Pa .forward
file contains one or more lines where each line is a valid expansion
value according to
.Xr aliases 5 .
However, the
.Pa .forward
mechanism differs from the aliases mechanism in that is disallows
file inclusion and it performs expansion under the user ID of the
.Pa .forward
file owner.
.Pp
.Pa .forward
files must not be group or world writable.
The user's home directory should not be group writable.
The
.Pa .forward
file must be owned by and readable by the indicated user.
.Sh FILES
.Bl -tag -width $HOME/.forward -compact
.It Pa $HOME/.forward
e-mail forwarding information
.El
.Sh EXAMPLES
.Bd -literal -offset indent
# anything after # is ignored
# empty lines are ignored

user@example.com
"|/path/to/examplemda"
.Ed
.Sh SEE ALSO
.Xr aliases 5 ,
.Xr smtpd 8
