#	$OpenBSD: Makefile,v 1.5 2002/10/01 20:59:48 miod Exp $
#	from: @(#)Makefile	5.1 (Berkeley) 2/12/91
#	Id: Makefile,v 1.4 1995/12/14 05:41:38 deraadt Exp $

MAN=	abtn.4 adb.4 aed.4 akbd.4 ams.4 apm.4 autoconf.4 awacs.4 bm.4 \
	intro.4 mem.4 zs.4
MLINKS= mem.4 kmem.4
MLINKS+= zs.4 zsc.4 zs.4 zstty.4

MANSUBDIR=macppc

.include <bsd.prog.mk>
