# !!!!!!!   DO NOT EDIT THIS FILE   !!!!!!!
# This file is machine-generated by lib/unicore/mktables from the Unicode
# database, Version 6.3.0.  Any changes made here will be lost!

# !!!!!!!   INTERNAL PERL USE ONLY   !!!!!!!
# This file is for internal use by core Perl only.  The format and even the
# name or existence of this file are subject to change without notice.  Don't
# use it directly.  Use Unicode::UCD to access the Unicode character data
# base.


return <<'END';
V73
2144
2208
6832
6912
7296
7360
12256
12272
43488
43520
43824
43968
66048
66176
66272
66304
66384
66432
66528
66560
66736
67584
67680
67840
67904
67968
68224
68352
68480
68608
68688
69216
69248
69632
69968
70016
70112
71296
71376
73728
74880
77824
78896
92160
92736
93952
94112
110592
110848
118784
119376
119552
119680
119808
120832
126464
126720
126976
128592
128640
128896
131072
173792
173824
178208
194560
195104
917504
917632
917760
918000
983040
1114112
END
