.\"	$OpenBSD: boot_mac68k.8,v 1.7 1998/09/23 01:20:25 aaron Exp $
.\"	$NetBSD: boot_mac68k.8,v 1.1 1995/07/02 02:09:52 briggs Exp $
.\"
.\" Copyright (c) 1990, 1991 The Regents of the University of California.
.\" All rights reserved.
.\"
.\" This code is derived from software contributed to Berkeley by
.\" the Systems Programming Group of the University of Utah Computer
.\" Science Department.
.\"
.\" Redistribution and use in source and binary forms, with or without
.\" modification, are permitted provided that the following conditions
.\" are met:
.\" 1. Redistributions of source code must retain the above copyright
.\"    notice, this list of conditions and the following disclaimer.
.\" 2. Redistributions in binary form must reproduce the above copyright
.\"    notice, this list of conditions and the following disclaimer in the
.\"    documentation and/or other materials provided with the distribution.
.\" 3. All advertising materials mentioning features or use of this software
.\"    must display the following acknowledgement:
.\"	This product includes software developed by the University of
.\"	California, Berkeley and its contributors.
.\" 4. Neither the name of the University nor the names of its contributors
.\"    may be used to endorse or promote products derived from this software
.\"    without specific prior written permission.
.\"
.\" THIS SOFTWARE IS PROVIDED BY THE REGENTS AND CONTRIBUTORS ``AS IS'' AND
.\" ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE
.\" IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE
.\" ARE DISCLAIMED.  IN NO EVENT SHALL THE REGENTS OR CONTRIBUTORS BE LIABLE
.\" FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL
.\" DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS
.\" OR SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION)
.\" HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT
.\" LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY
.\" OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF
.\" SUCH DAMAGE.
.\"
.\"	From:
.\"	@(#)boot_hp300.8	8.2 (Berkeley) 4/19/94
.\"
.Dd July 1, 1995
.Dt BOOT_MAC68K 8 mac68k
.Os
.Sh NAME
.Nm boot
.Nd
system bootstrapping procedures
.Sh DESCRIPTION
.Ss Power fail and crash recovery
.Pp
Normally, the
.Ox
kernel on the mac68k architecture is booted from the native operating
system by means of an application program.  When the kernel takes over,
it initializes itself and proceeds to boot the system.  An automatic
consistency check of the file systems takes place, and unless this
fails, the system comes up to multi-user operations.  The proper way
to shut the system down is with the
.Xr shutdown 8
command.
.Pp
If the system crashes, it will enter the kernel debugger,
.Xr ddb 8 ,
if it is configured in the kernel.  If the debugger is not present
or has exited, the system will attempt a dump to the
configured dump device (which will be automatically recovered with
.Xr savecore 8
during the next boot cycle).  After the dump completes (successful
or not), the system will attempt a reboot.
.Pp
On most mac68k machines with "soft-power" after the IIcx, the power
switch can be physically rotated and locked in the ``on'' position.
The native OS can be configured to automatically start the
.Ox
boot program.  Additionally, the OpenBSD boot program can be configured
to boot
.Ox
without intervention.  When a system is so configured, it can crash
or lose power and reboot back to a fully multi-user state without
any intervention.
.Pp
.Ss The boot application
.Pp
The boot application runs in the native OS on the system.  It has a
dialog where booting preferences may be changed and an option whereby
these options may be saved.  The preferences are stored in the program
itself, not in a preferences folder, thus allowing two separate copies
of the program to be configured differently (e.g. to boot different
bsd or bsd.test, or to boot from two different drives).
.Pp
One option that may be specified is a boot to single-user mode.  This
stops the boot process very early on and allows system maintenence.
If one wishes to provide some security at this phase of the boot, remove
the
.Ql secure
option from ttye0 in the
.Xr ttys 5
file.
.Pp
Another useful option that may be specified is the "serial console"
option.  This will allow a serial device (terminal or computer) to
act as a console for the system.  This device must be configured to
use 9600 baud, eight bits, no parity, and one stop bit (9600-8N1).
Either the printer port or the modem port (tty01 and tty00,
respectively) may be used for this.
.Pp
It is sometimes useful to boot a kernel that resides in a folder
in native OS rather than from the usual location in the
.Ox
file system.  A radio button is supplied for this purpose.  Note that
some programs will not run properly if the kernel is not found as
.Pa /bsd
within the 
.Tn OpenBSD
file system.
.Sh FILES
.Bl -tag -width /bsd -compact
.It Pa /bsd
system kernel
.El
.Sh SEE ALSO
.Xr ttys 5 ,
.Xr ddb 8 ,
.Xr savecore 8 ,
.Xr shutdown 8
