'\" t
.TH menu_userptr 3X ""
.SH NAME
\fBmenu_userptr\fR - associate application data with a menu item
.SH SYNOPSIS
\fB#include <menu.h>\fR
.br
int set_menu_userptr(MENU *menu, char *userptr);
.br
char menu_userptr(MENU *menu);
.br
.SH DESCRIPTION
Every menu and every menu item has a field that can be used to hold
application-specific data (that is, the menu-driver code leaves it alone).
These functions get and set the menu user pointer field.
.SH RETURN VALUE
Except for \fBmenu_userptr\fR (which returns \fBNULL\fR on error), each
function returns one of the following:
.TP 5
\fBE_OK\fR
The routine succeeded.
.TP 5
\fBE_SYSTEM_ERROR\fR
System error occurred (see \fBerrno\fR).
.SH SEE ALSO
\fBcurses\fR(3X), \fBmenu\fR(3X).
.SH NOTES
The header file \fB<menu.h>\fR automatically includes the header file
\fB<curses.h>\fR.
.SH PORTABILITY
These routines emulate the System V menu library.  They were not supported on
Version 7 or BSD versions.

The user pointer should be a void pointer.  We leave it as a char pointer for
SVr4 compatibility.
.SH AUTHORS
Juergen Pfeifer.  Manual pages and adaptation for new curses by Eric
S. Raymond.
.\"#
.\"# The following sets edit modes for GNU EMACS
.\"# Local Variables:
.\"# mode:nroff
.\"# fill-column:79
.\"# End:
