.\"	$OpenBSD: boot_hppa.8,v 1.1 2002/10/17 23:18:51 miod Exp $
.\"
.\" Copyright (c) 2002, Miodrag Vallat.
.\" All rights reserved.
.\"
.\" Redistribution and use in source and binary forms, with or without
.\" modification, are permitted provided that the following conditions
.\" are met:
.\" 1. Redistributions of source code must retain the above copyright
.\"    notice, this list of conditions and the following disclaimer.
.\" 2. Redistributions in binary form must reproduce the above copyright
.\"    notice, this list of conditions and the following disclaimer in the
.\"    documentation and/or other materials provided with the distribution.
.\"
.\" THIS SOFTWARE IS PROVIDED BY THE AUTHOR ``AS IS'' AND ANY EXPRESS OR
.\" IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED
.\" WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE
.\" ARE DISCLAIMED.  IN NO EVENT SHALL THE REGENTS OR CONTRIBUTORS BE LIABLE
.\" FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL
.\" DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS
.\" OR SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION)
.\" HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT
.\" LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY
.\" OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF
.\" SUCH DAMAGE.
.\"
.Dd October 16, 2002
.Dt BOOT_HPPA 8 hppa
.Os
.Sh NAME
.Nm boot_hppa
.Nd hppa system bootstrapping procedures
.Sh DESCRIPTION
.Ss System starts
When powered on, after a panic, or if the system is rebooted via
.Xr reboot 8
or
.Xr shutdown 8 ,
the hppa firmware
.Pq Dq PDC
will proceed to its initialization, and will boot an operating system 
if autoboot is enabled.
.\"
.Ss Boot process description
System boot blocks are provided as a
.Dq LIF
.Pq Logical Interchange Format
archive, either on a disk device, or via the network, using the
.Em bootp
or
.Em rboot
protocols, depening on the PDC version.
.Ss PDC concepts
If autoboot is enabled, the PDC will attempt to boot from the specified
.Dq boot path
value.
If no
.Dq boot path
has been specified, the PDC will then scan for bootable devices and
boot from the first found, after a few seconds allowing the user to
interrupt the boot process.
If autoboot is disabled, the PDC will enter interactive mode, after an
optional device scan.
In all cases, it is possible to enter interactive mode by holding the
escape key during the selftests, or when prompted to do so to abort
the current operation, unless the PDC has been configured in
.Dq secure mode .
.\"
.Ss Old PDC operation
PDC ROM v1.4 and below are easily recognizable,
as they will start with a text banner.
There are two levels of interactive commands in this version.
The first level is a short menu:
.Bd -literal -offset indent
b)   Boot from specified device
s)   Search for bootable device
a)   Enter Boot Administration mode
x)   Exit and continue boot sequence

Select from menu:
.Ed
.Pp
which provides the following commands:
.Bl -tag -width "XXX" -offset indent -compact
.It b
boot from a device found during the scan,
either with its short
.Dq P#
form, or a complete name specification.
For example, to boot from the
.Tn SCSI
disk with id 6 off the built-in (first) controller,
one would enter
.Ic b Ar scsi.6.0 .
.It s
rescan for bootable devices.
.It a
enter the second part of interactive mode.
.It x
resume an interrupted boot sequence.
.El
.Pp
The
.Dq Boot Administration
mode, recognizable with its
.Em BOOT_ADMIN>
prompt, controls the various boot options.
The complete list of commands depends of the machine and PDC version.
The following list only mentions commands impacting the boot process.
.Bl -tag -width AUTOSELECT -offset indent
.It AUTOSELECT
Displays or changes the autoboot setting.
If autoselect is set to
.Dq on ,
the PDC will always attempt to boot the first bootable device found in
that order:
.Bl -enum -offset indent -compact
.It
boot device
.Em path
setting.
.It
.Tn SCSI
devices connected to the built-in
.Tn SCSI
controller,
the highest ID numbers being preferred.
.It
Network
.Em rboot
server.
.It
Other
.Tn SCSI
devices connected to secondary controllers,
the highest ID numbers being preferred.
.El
If the
.Em primary path
setting defines a bootable device, no device scan will occur.
.It BOOT
Boots off the specified device.
It is similar to the
.Ic b
command from the short menu above.
The
.Dq primary
and
.Dq alternate
path settings may be booted with
.Ic boot Ar pri
and
.Ic boot Ar alt
respectively.
.It PATH
Displays or changes the boot and console devices.
The boot device is defined as the
.Dq primary
path, and another setting may be stored as the
.Dq alternate
path for rescue purposes.
For example, to define the primary boot path to the
.Tn SCSI
disk with ID 5 connected to the built-in controller, one would enter
.Ic path primary Ar scsi.5
.Pp
When invoked without parameters,
.Ic path
will list the various path settings.
.El
.\"
.Ss Modern PDC operation
PDC ROM 1.5 and above will start with a small graphics window at the
screen center (unless you are using a serial console).
There is only one interactive mode, with a
.Em BOOT_ADMIN>
prompt, which provides both boot settings and commands.
The complete list of commands depends of the machine and PDC version.
The following list only mentions commands impacting the boot process.
.Bl -tag -width auto\ search -offset indent
.It auto\ boot
Displays or changes the autoboot setting.
If
.Ev auto\ boot
is set to
.Dq on ,
the PDC will always attempt to boot.
The booted device choosen will depend of the
.Ev auto\ search
setting.
.It auto\ search
Displays or changes the device scan setting.
If
.Ev auto\ search
is set to
.Dq on ,
the PDC will attempt to boot the first bootable device found in
that order:
.Bl -enum -offset indent -compact
.It
boot device
.Em path
setting.
.It
.Tn SCSI
devices connected to the built-in
.Tn SCSI
controller,
the highest ID numbers being preferred.
.It
Network
.Em bootp
server.
.It
Other
.Tn SCSI
devices connected to secondary controllers,
the highest ID numbers being preferred.
.El
If
.Ev auto\ search
is set to
.Dq off
and the primary boot path points to a bootable device,
no device scan will occur.
.Pp
Note that setting
.Ev auto\ search
to
.Dq on
will force autoboot, regardless of the
.Ev auto\ boot
value.
.It boot
Boots off the specified device.
The
.Dq primary
and
.Dq alternate
path settings may be booted with
.Ic boot Ar pri
and
.Ic boot Ar alt
respectively.
.It path
Displays or changes the boot and console devices.
The boot device is defined as the
.Dq primary
path, and another setting may be stored as the
.Dq alternate
path for rescue purposes.
For example, to define the primary boot path to the
.Tn SCSI
disk with ID 5 connected to the built-in controller, one would enter
.Ic path pri Ar scsi.5
.Pp
When invoked without parameters,
.Ic path
will list the various path settings.
.El
.\"
.Ss Boot process options
The
.Ox
hppa boot loader program is extensively described is a separate document,
.Xr boot 8 .
.Ss Abnormal system termination
If the system crashes, it will enter the kernel debugger,
.Xr ddb 4 ,
if it is configured in the kernel.
If the crash occurred during
initialization and the debugger is not present or is exited, the
kernel will halt the system.
If the crash occurred during normal operation and the debugger
is not present or is exited, the system will attempt a dump to the
configured dump device (which will be automatically recovered with
.Xr savecore 8
during the next multi-user boot cycle), and after the dump is complete
(successful or not) the kernel will attempt a reboot.
.Sh FILES
.Bl -tag -width boot.lif -compact
.It Pa /bsd
default system kernel
.It Pa boot.lif
network bootstrap and kernel combined image
.\" .It Pa /usr/mdec/boot
.\" system bootstrap (usually also installed as
.\" .Pa /boot )
.El
.Sh SEE ALSO
.Xr ddb 4 ,
.Xr boot 8 ,
.Xr halt 8 ,
.Xr init 8 ,
.\" .Xr installboot 8 ,
.Xr reboot 8 ,
.Xr savecore 8 ,
.Xr shutdown 8
