/*
 * THIS FILE AUTOMATICALLY GENERATED.  DO NOT EDIT.
 *
 * generated from:
 *	OpenBSD: pcidevs,v 1.80 1998/08/17 17:43:09 deraadt Exp 
 */

/*	$NetBSD: pcidevs,v 1.30 1997/06/24 06:20:24 thorpej Exp $ 	*/

struct pci_knowndev pci_knowndevs[] = {
	{
	    PCI_VENDOR_2MICRO, PCI_PRODUCT_2MICRO_OZ6832,
	    0,
	    "2 Micro Inc",
	    "OZ6832 CardBus Controller",
	},
	{
	    PCI_VENDOR_3COM, PCI_PRODUCT_3COM_3C590,
	    0,
	    "3Com",
	    "3c590 10Mbps",
	},
	{
	    PCI_VENDOR_3COM, PCI_PRODUCT_3COM_3C595TX,
	    0,
	    "3Com",
	    "3c595 100Base-TX",
	},
	{
	    PCI_VENDOR_3COM, PCI_PRODUCT_3COM_3C595T4,
	    0,
	    "3Com",
	    "3c595 100Base-T4",
	},
	{
	    PCI_VENDOR_3COM, PCI_PRODUCT_3COM_3C595MII,
	    0,
	    "3Com",
	    "3c595 10Mbps-MII",
	},
	{
	    PCI_VENDOR_3COM, PCI_PRODUCT_3COM_3C900TPO,
	    0,
	    "3Com",
	    "3c900 10Base-T",
	},
	{
	    PCI_VENDOR_3COM, PCI_PRODUCT_3COM_3C900COMBO,
	    0,
	    "3Com",
	    "3c900 10Mbps-Combo",
	},
	{
	    PCI_VENDOR_3COM, PCI_PRODUCT_3COM_3C905TX,
	    0,
	    "3Com",
	    "3c905 100Base-TX",
	},
	{
	    PCI_VENDOR_3COM, PCI_PRODUCT_3COM_3C905T4,
	    0,
	    "3Com",
	    "3c905 100Base-T4",
	},
	{
	    PCI_VENDOR_3COM, PCI_PRODUCT_3COM_3C905B,
	    0,
	    "3Com",
	    "3c905B 100Base-T4",
	},
	{
	    PCI_VENDOR_3COM, PCI_PRODUCT_3COM_3C980TX,
	    0,
	    "3Com",
	    "3c980 100Base-TX",
	},
	{
	    PCI_VENDOR_3DFX, PCI_PRODUCT_3DFX_VOODOO,
	    0,
	    "3DFX Interactive",
	    "Voodoo",
	},
	{
	    PCI_VENDOR_3DFX, PCI_PRODUCT_3DFX_VOODOO2,
	    0,
	    "3DFX Interactive",
	    "Voodoo2",
	},
	{
	    PCI_VENDOR_3DLABS, PCI_PRODUCT_3DLABS_300SX,
	    0,
	    "3D Labs",
	    "300SX (Glint)",
	},
	{
	    PCI_VENDOR_3DLABS, PCI_PRODUCT_3DLABS_500TX,
	    0,
	    "3D Labs",
	    "GLINT 500TX",
	},
	{
	    PCI_VENDOR_3DLABS, PCI_PRODUCT_3DLABS_DELTA,
	    0,
	    "3D Labs",
	    "GLINT DELTA",
	},
	{
	    PCI_VENDOR_3DLABS, PCI_PRODUCT_3DLABS_500MX,
	    0,
	    "3D Labs",
	    "GLINT 500MX",
	},
	{
	    PCI_VENDOR_ACC, PCI_PRODUCT_ACC_2188,
	    0,
	    "ACC Microelectronics",
	    "ACCM 2188 VL-PCI Bridge",
	},
	{
	    PCI_VENDOR_ACC, PCI_PRODUCT_ACC_2051_HB,
	    0,
	    "ACC Microelectronics",
	    "2051 PCI Single Chip Solution (host bridge)",
	},
	{
	    PCI_VENDOR_ACC, PCI_PRODUCT_ACC_2051_ISA,
	    0,
	    "ACC Microelectronics",
	    "2051 PCI Single Chip Solution (ISA bridge)",
	},
	{
	    PCI_VENDOR_ACER, PCI_PRODUCT_ACER_M1435,
	    0,
	    "Acer",
	    "M1435 VL-PCI Bridge",
	},
	{
	    PCI_VENDOR_ALI, PCI_PRODUCT_ALI_M1445,
	    0,
	    "Acer Labs",
	    "M1445 VL-PCI Bridge",
	},
	{
	    PCI_VENDOR_ALI, PCI_PRODUCT_ALI_M1449,
	    0,
	    "Acer Labs",
	    "M1449 PCI-ISA Bridge",
	},
	{
	    PCI_VENDOR_ALI, PCI_PRODUCT_ALI_M1451,
	    0,
	    "Acer Labs",
	    "M1451 Host-PCI Bridge",
	},
	{
	    PCI_VENDOR_ALI, PCI_PRODUCT_ALI_M1461,
	    0,
	    "Acer Labs",
	    "M1461 Host-PCI Bridge",
	},
	{
	    PCI_VENDOR_ALI, PCI_PRODUCT_ALI_M1521,
	    0,
	    "Acer Labs",
	    "M1523 Host-PCI Bridge",
	},
	{
	    PCI_VENDOR_ALI, PCI_PRODUCT_ALI_M1541,
	    0,
	    "Acer Labs",
	    "M1543 Host-PCI Bridge",
	},
	{
	    PCI_VENDOR_ALI, PCI_PRODUCT_ALI_M4803,
	    0,
	    "Acer Labs",
	    "M4803",
	},
	{
	    PCI_VENDOR_ALI, PCI_PRODUCT_ALI_M1523,
	    0,
	    "Acer Labs",
	    "M1523 PCI-ISA Bridge",
	},
	{
	    PCI_VENDOR_ALI, PCI_PRODUCT_ALI_M1543,
	    0,
	    "Acer Labs",
	    "M1543 PCI-ISA Bridge",
	},
	{
	    PCI_VENDOR_ALI, PCI_PRODUCT_ALI_M5219,
	    0,
	    "Acer Labs",
	    "M5219 UDMA IDE Controller",
	},
	{
	    PCI_VENDOR_ALI, PCI_PRODUCT_ALI_M5229,
	    0,
	    "Acer Labs",
	    "M5229 UDMA IDE Controller",
	},
	{
	    PCI_VENDOR_ALI, PCI_PRODUCT_ALI_M5237,
	    0,
	    "Acer Labs",
	    "M5237 USB Host Controller",
	},
	{
	    PCI_VENDOR_ALI, PCI_PRODUCT_ALI_M5243,
	    0,
	    "Acer Labs",
	    "M5243 AGP/PCI-PCI Bridge",
	},
	{
	    PCI_VENDOR_ALI, PCI_PRODUCT_ALI_M7101,
	    0,
	    "Acer Labs",
	    "M7101 Power Management Controller",
	},
	{
	    PCI_VENDOR_ADP, PCI_PRODUCT_ADP_AIC7810,
	    0,
	    "Adaptec",
	    "AIC-7810",
	},
	{
	    PCI_VENDOR_ADP, PCI_PRODUCT_ADP_AIC7850,
	    0,
	    "Adaptec",
	    "AIC-7850",
	},
	{
	    PCI_VENDOR_ADP, PCI_PRODUCT_ADP_AIC7855,
	    0,
	    "Adaptec",
	    "AIC-7855",
	},
	{
	    PCI_VENDOR_ADP, PCI_PRODUCT_ADP_AIC5900,
	    0,
	    "Adaptec",
	    "AIC-5900 ATM",
	},
	{
	    PCI_VENDOR_ADP, PCI_PRODUCT_ADP_AIC5905,
	    0,
	    "Adaptec",
	    "AIC-5905 ATM",
	},
	{
	    PCI_VENDOR_ADP, PCI_PRODUCT_ADP_AIC7860,
	    0,
	    "Adaptec",
	    "AIC-7860",
	},
	{
	    PCI_VENDOR_ADP, PCI_PRODUCT_ADP_2940AU,
	    0,
	    "Adaptec",
	    "AHA-2940A Ultra",
	},
	{
	    PCI_VENDOR_ADP, PCI_PRODUCT_ADP_AIC7870,
	    0,
	    "Adaptec",
	    "AIC-7870",
	},
	{
	    PCI_VENDOR_ADP, PCI_PRODUCT_ADP_2940,
	    0,
	    "Adaptec",
	    "AHA-2940",
	},
	{
	    PCI_VENDOR_ADP, PCI_PRODUCT_ADP_3940,
	    0,
	    "Adaptec",
	    "AHA-3940",
	},
	{
	    PCI_VENDOR_ADP, PCI_PRODUCT_ADP_3985,
	    0,
	    "Adaptec",
	    "AHA-3985",
	},
	{
	    PCI_VENDOR_ADP, PCI_PRODUCT_ADP_2944,
	    0,
	    "Adaptec",
	    "AHA-2944",
	},
	{
	    PCI_VENDOR_ADP, PCI_PRODUCT_ADP_AIC7880,
	    0,
	    "Adaptec",
	    "AIC-7880 Ultra",
	},
	{
	    PCI_VENDOR_ADP, PCI_PRODUCT_ADP_2940U,
	    0,
	    "Adaptec",
	    "AHA-2940 Ultra",
	},
	{
	    PCI_VENDOR_ADP, PCI_PRODUCT_ADP_3940U,
	    0,
	    "Adaptec",
	    "AHA-3940 Ultra",
	},
	{
	    PCI_VENDOR_ADP, PCI_PRODUCT_ADP_398XU,
	    0,
	    "Adaptec",
	    "AHA-398X Ultra",
	},
	{
	    PCI_VENDOR_ADP, PCI_PRODUCT_ADP_2944U,
	    0,
	    "Adaptec",
	    "AHA-2944 Ultra",
	},
	{
	    PCI_VENDOR_ALLIANCE, PCI_PRODUCT_ALLIANCE_AT24,
	    0,
	    "Alliance Semiconductor",
	    "AT24",
	},
	{
	    PCI_VENDOR_APPLE, PCI_PRODUCT_APPLE_BANDIT,
	    0,
	    "Apple Computer",
	    "PCI Controller",
	},
	{
	    PCI_VENDOR_AMD, PCI_PRODUCT_AMD_PCNET_PCI,
	    0,
	    "Advanced Micro Devices",
	    "79c970 PCnet-PCI LANCE Ethernet",
	},
	{
	    PCI_VENDOR_AMD, PCI_PRODUCT_AMD_PCSCSI_PCI,
	    0,
	    "Advanced Micro Devices",
	    "53c974 PCscsi-PCI SCSI",
	},
	{
	    PCI_VENDOR_AMD, PCI_PRODUCT_AMD_PCNETS_PCI,
	    0,
	    "Advanced Micro Devices",
	    "79C974 PCnet-PCI Ethernet & SCSI",
	},
	{
	    PCI_VENDOR_APPLE, PCI_PRODUCT_APPLE_BANDIT,
	    0,
	    "Apple Computer",
	    "PCI Controller",
	},
	{
	    PCI_VENDOR_ARC, PCI_PRODUCT_ARC_1000PV,
	    0,
	    "ARC Logic",
	    "1000PV",
	},
	{
	    PCI_VENDOR_ARC, PCI_PRODUCT_ARC_2000PV,
	    0,
	    "ARC Logic",
	    "2000PV",
	},
	{
	    PCI_VENDOR_ARC, PCI_PRODUCT_ARC_2000MT,
	    0,
	    "ARC Logic",
	    "2000MT",
	},
	{
	    PCI_VENDOR_ARC, PCI_PRODUCT_ARC_2000MI,
	    0,
	    "ARC Logic",
	    "2000MI",
	},
	{
	    PCI_VENDOR_ATI, PCI_PRODUCT_ATI_MACH32,
	    0,
	    "ATI Technologies",
	    "Mach32",
	},
	{
	    PCI_VENDOR_ATI, PCI_PRODUCT_ATI_MACH64_CT,
	    0,
	    "ATI Technologies",
	    "Mach64 CT",
	},
	{
	    PCI_VENDOR_ATI, PCI_PRODUCT_ATI_MACH64_CX,
	    0,
	    "ATI Technologies",
	    "Mach64 CX",
	},
	{
	    PCI_VENDOR_ATI, PCI_PRODUCT_ATI_MACH64_ET,
	    0,
	    "ATI Technologies",
	    "Mach64 ET",
	},
	{
	    PCI_VENDOR_ATI, PCI_PRODUCT_ATI_MACH64_VT,
	    0,
	    "ATI Technologies",
	    "Mach64 VT",
	},
	{
	    PCI_VENDOR_ATI, PCI_PRODUCT_ATI_MACH64_GT,
	    0,
	    "ATI Technologies",
	    "Mach64 GT",
	},
	{
	    PCI_VENDOR_ATI, PCI_PRODUCT_ATI_MACH64_GX,
	    0,
	    "ATI Technologies",
	    "Mach64 GX",
	},
	{
	    PCI_VENDOR_AMCIRCUITS, PCI_PRODUCT_AMCIRCUITS_S5933,
	    0,
	    "Applied Micro Circuits",
	    "S5933 PCI Matchmaker",
	},
	{
	    PCI_VENDOR_AMCIRCUITS, PCI_PRODUCT_AMCIRCUITS_LANAI,
	    0,
	    "Applied Micro Circuits",
	    "Myrinet LANai Interface",
	},
	{
	    PCI_VENDOR_ATRONICS, PCI_PRODUCT_ATRONICS_IDE_2015PL,
	    0,
	    "Atronics",
	    "IDE-2015PL",
	},
	{
	    PCI_VENDOR_AVANCE, PCI_PRODUCT_AVANCE_AVL2301,
	    0,
	    "Avance Logic",
	    "AVL2301",
	},
	{
	    PCI_VENDOR_AVANCE, PCI_PRODUCT_AVANCE_AVG2302,
	    0,
	    "Avance Logic",
	    "AVG2302",
	},
	{
	    PCI_VENDOR_AVANCE2, PCI_PRODUCT_AVANCE2_ALG2301,
	    0,
	    "Avance Logic (2nd ID)",
	    "ALG2301",
	},
	{
	    PCI_VENDOR_AVANCE2, PCI_PRODUCT_AVANCE2_ALG2302,
	    0,
	    "Avance Logic (2nd ID)",
	    "ALG2302",
	},
	{
	    PCI_VENDOR_BIT3, PCI_PRODUCT_BIT3_PCIVME617,
	    0,
	    "Bit3 Computer Corp.",
	    "PCI-VME Interface Mod. 617",
	},
	{
	    PCI_VENDOR_BROOKTREE, PCI_PRODUCT_BROOKTREE_BT848,
	    0,
	    "Brooktree",
	    "BT848",
	},
	{
	    PCI_VENDOR_BROOKTREE, PCI_PRODUCT_BROOKTREE_BT849,
	    0,
	    "Brooktree",
	    "BT849",
	},
	{
	    PCI_VENDOR_BUSLOGIC, PCI_PRODUCT_BUSLOGIC_MULTIMASTER_NC,
	    0,
	    "BusLogic",
	    "MultiMaster NC",
	},
	{
	    PCI_VENDOR_BUSLOGIC, PCI_PRODUCT_BUSLOGIC_MULTIMASTER,
	    0,
	    "BusLogic",
	    "MultiMaster",
	},
	{
	    PCI_VENDOR_BUSLOGIC, PCI_PRODUCT_BUSLOGIC_FLASHPOINT,
	    0,
	    "BusLogic",
	    "FlashPoint",
	},
	{
	    PCI_VENDOR_C4T, PCI_PRODUCT_C4T_GPPCI,
	    0,
	    "c't Magazin",
	    "GPPCI",
	},
	{
	    PCI_VENDOR_CHIPS, PCI_PRODUCT_CHIPS_64310,
	    0,
	    "Chips and Technologies",
	    "64310",
	},
	{
	    PCI_VENDOR_CHIPS, PCI_PRODUCT_CHIPS_65545,
	    0,
	    "Chips and Technologies",
	    "65545",
	},
	{
	    PCI_VENDOR_CHIPS, PCI_PRODUCT_CHIPS_65548,
	    0,
	    "Chips and Technologies",
	    "65548",
	},
	{
	    PCI_VENDOR_CHIPS, PCI_PRODUCT_CHIPS_65550,
	    0,
	    "Chips and Technologies",
	    "65550",
	},
	{
	    PCI_VENDOR_CHIPS, PCI_PRODUCT_CHIPS_65554,
	    0,
	    "Chips and Technologies",
	    "65554",
	},
	{
	    PCI_VENDOR_CHIPS, PCI_PRODUCT_CHIPS_65555,
	    0,
	    "Chips and Technologies",
	    "65555",
	},
	{
	    PCI_VENDOR_CIRRUS, PCI_PRODUCT_CIRRUS_CL_GD7548,
	    0,
	    "Cirrus Logic",
	    "CL-GD7548",
	},
	{
	    PCI_VENDOR_CIRRUS, PCI_PRODUCT_CIRRUS_CL_GD5430,
	    0,
	    "Cirrus Logic",
	    "CL-GD5430",
	},
	{
	    PCI_VENDOR_CIRRUS, PCI_PRODUCT_CIRRUS_CL_GD5434_4,
	    0,
	    "Cirrus Logic",
	    "CL-GD5434-4",
	},
	{
	    PCI_VENDOR_CIRRUS, PCI_PRODUCT_CIRRUS_CL_GD5434_8,
	    0,
	    "Cirrus Logic",
	    "CL-GD5434-8",
	},
	{
	    PCI_VENDOR_CIRRUS, PCI_PRODUCT_CIRRUS_CL_GD5436,
	    0,
	    "Cirrus Logic",
	    "CL-GD5436",
	},
	{
	    PCI_VENDOR_CIRRUS, PCI_PRODUCT_CIRRUS_CL_GD5446,
	    0,
	    "Cirrus Logic",
	    "CL-GD5446",
	},
	{
	    PCI_VENDOR_CIRRUS, PCI_PRODUCT_CIRRUS_CL_GD5480,
	    0,
	    "Cirrus Logic",
	    "CL-GD5480",
	},
	{
	    PCI_VENDOR_CIRRUS, PCI_PRODUCT_CIRRUS_CL_PD6729,
	    0,
	    "Cirrus Logic",
	    "CL-PD6729",
	},
	{
	    PCI_VENDOR_CIRRUS, PCI_PRODUCT_CIRRUS_CL_PD6832,
	    0,
	    "Cirrus Logic",
	    "CL-PD6832",
	},
	{
	    PCI_VENDOR_CIRRUS, PCI_PRODUCT_CIRRUS_CL_GD7542,
	    0,
	    "Cirrus Logic",
	    "CL-GD7542",
	},
	{
	    PCI_VENDOR_CIRRUS, PCI_PRODUCT_CIRRUS_CL_GD7543,
	    0,
	    "Cirrus Logic",
	    "CL-GD7543",
	},
	{
	    PCI_VENDOR_CIRRUS, PCI_PRODUCT_CIRRUS_CL_GD7541,
	    0,
	    "Cirrus Logic",
	    "CL-GD7541",
	},
	{
	    PCI_VENDOR_CMDTECH, PCI_PRODUCT_CMDTECH_640,
	    0,
	    "CMD Technology",
	    "PCI640",
	},
	{
	    PCI_VENDOR_CMDTECH, PCI_PRODUCT_CMDTECH_642,
	    0,
	    "CMD Technology",
	    "PCI0642",
	},
	{
	    PCI_VENDOR_CMDTECH, PCI_PRODUCT_CMDTECH_643,
	    0,
	    "CMD Technology",
	    "PCI0643",
	},
	{
	    PCI_VENDOR_CMDTECH, PCI_PRODUCT_CMDTECH_646,
	    0,
	    "CMD Technology",
	    "PCI0646",
	},
	{
	    PCI_VENDOR_CMDTECH, PCI_PRODUCT_CMDTECH_647,
	    0,
	    "CMD Technology",
	    "PCI0647",
	},
	{
	    PCI_VENDOR_CMDTECH, PCI_PRODUCT_CMDTECH_650A,
	    0,
	    "CMD Technology",
	    "PCI0650A",
	},
	{
	    PCI_VENDOR_CMDTECH, PCI_PRODUCT_CMDTECH_670,
	    0,
	    "CMD Technology",
	    "USB0670",
	},
	{
	    PCI_VENDOR_CMDTECH, PCI_PRODUCT_CMDTECH_673,
	    0,
	    "CMD Technology",
	    "USB0673",
	},
	{
	    PCI_VENDOR_COGENT, PCI_PRODUCT_COGENT_EM110TX,
	    0,
	    "Cogent Data Technologies",
	    "EX110TX PCI Fast Ethernet Adapter",
	},
	{
	    PCI_VENDOR_COMPAQ, PCI_PRODUCT_COMPAQ_PCI_EISA_BRIDGE,
	    0,
	    "Compaq",
	    "PCI-EISA Bridge",
	},
	{
	    PCI_VENDOR_COMPAQ, PCI_PRODUCT_COMPAQ_PCI_ISA_BRIDGE,
	    0,
	    "Compaq",
	    "PCI-ISA Bridge",
	},
	{
	    PCI_VENDOR_COMPAQ, PCI_PRODUCT_COMPAQ_TRIFLEX1,
	    0,
	    "Compaq",
	    "Triflex Host-PCI Bridge",
	},
	{
	    PCI_VENDOR_COMPAQ, PCI_PRODUCT_COMPAQ_TRIFLEX2,
	    0,
	    "Compaq",
	    "Triflex Host-PCI Bridge",
	},
	{
	    PCI_VENDOR_COMPAQ, PCI_PRODUCT_COMPAQ_QVISION_V0,
	    0,
	    "Compaq",
	    "QVision",
	},
	{
	    PCI_VENDOR_COMPAQ, PCI_PRODUCT_COMPAQ_QVISION_1280P,
	    0,
	    "Compaq",
	    "QVision 1280/p",
	},
	{
	    PCI_VENDOR_COMPAQ, PCI_PRODUCT_COMPAQ_QVISION_V2,
	    0,
	    "Compaq",
	    "QVision",
	},
	{
	    PCI_VENDOR_COMPAQ, PCI_PRODUCT_COMPAQ_TRIFLEX4,
	    0,
	    "Compaq",
	    "Triflex Host-PCI Bridge",
	},
	{
	    PCI_VENDOR_COMPAQ, PCI_PRODUCT_COMPAQ_USB,
	    0,
	    "Compaq",
	    "USB Controller",
	},
	{
	    PCI_VENDOR_COMPAQ, PCI_PRODUCT_COMPAQ_N100TX,
	    0,
	    "Compaq",
	    "Netelligent 10/100 TX",
	},
	{
	    PCI_VENDOR_COMPAQ, PCI_PRODUCT_COMPAQ_N10T,
	    0,
	    "Compaq",
	    "Netelligent 10 T",
	},
	{
	    PCI_VENDOR_COMPAQ, PCI_PRODUCT_COMPAQ_IntNF3P,
	    0,
	    "Compaq",
	    "Integrated NetFlex 3/P",
	},
	{
	    PCI_VENDOR_COMPAQ, PCI_PRODUCT_COMPAQ_IntPL100TX,
	    0,
	    "Compaq",
	    "ProLiant Integrated Netelligent 10/100 TX",
	},
	{
	    PCI_VENDOR_COMPAQ, PCI_PRODUCT_COMPAQ_DPNet100TX,
	    0,
	    "Compaq",
	    "Dual Port Netelligent 10/100 TX",
	},
	{
	    PCI_VENDOR_COMPAQ, PCI_PRODUCT_COMPAQ_DP4000,
	    0,
	    "Compaq",
	    "Deskpro 4000 5233MMX",
	},
	{
	    PCI_VENDOR_COMPAQ, PCI_PRODUCT_COMPAQ_NF3P,
	    0,
	    "Compaq",
	    "NetFlex 3/P",
	},
	{
	    PCI_VENDOR_COMPAQ, PCI_PRODUCT_COMPAQ_NF3P_BNC,
	    0,
	    "Compaq",
	    "NetFlex 3/P w/ BNC",
	},
	{
	    PCI_VENDOR_COMPEX, PCI_PRODUCT_COMPEX_COMPEXE,
	    0,
	    "Compex",
	    "Compex Ethernet",
	},
	{
	    PCI_VENDOR_CONTAQ, PCI_PRODUCT_CONTAQ_82C599,
	    0,
	    "Contaq Microsystems",
	    "82C599 PCI-VLB Bridge",
	},
	{
	    PCI_VENDOR_CONTAQ, PCI_PRODUCT_CONTAQ_SIO,
	    0,
	    "Contaq Microsystems",
	    "CY82C693U PCI-ISA Bridge (System I/O)",
	},
	{
	    PCI_VENDOR_COROLLARY, PCI_PRODUCT_COROLLARY_CBUSII_PCIB,
	    0,
	    "Corrollary",
	    "C-Bus II-PCI Bridge",
	},
	{
	    PCI_VENDOR_CYCLADES, PCI_PRODUCT_CYCLADES_CYCLOMY_1,
	    0,
	    "Cyclades",
	    "Cyclom-Y below 1M",
	},
	{
	    PCI_VENDOR_CYCLADES, PCI_PRODUCT_CYCLADES_CYCLOMY_2,
	    0,
	    "Cyclades",
	    "Cyclom-Y above 1M",
	},
	{
	    PCI_VENDOR_CYCLADES, PCI_PRODUCT_CYCLADES_CYCLOMZ_1,
	    0,
	    "Cyclades",
	    "Cyclom-Z below 1M",
	},
	{
	    PCI_VENDOR_CYCLADES, PCI_PRODUCT_CYCLADES_CYCLOMZ_2,
	    0,
	    "Cyclades",
	    "Cyclom-Z above 1M",
	},
	{
	    PCI_VENDOR_DEC, PCI_PRODUCT_DEC_21050,
	    0,
	    "Digital Equipment",
	    "DECchip 21050 PCI-PCI Bridge",
	},
	{
	    PCI_VENDOR_DEC, PCI_PRODUCT_DEC_21040,
	    0,
	    "Digital Equipment",
	    "DECchip 21040 (Tulip)",
	},
	{
	    PCI_VENDOR_DEC, PCI_PRODUCT_DEC_21030,
	    0,
	    "Digital Equipment",
	    "DECchip 21030 (TGA)",
	},
	{
	    PCI_VENDOR_DEC, PCI_PRODUCT_DEC_NVRAM,
	    0,
	    "Digital Equipment",
	    "Zephyr NV-RAM",
	},
	{
	    PCI_VENDOR_DEC, PCI_PRODUCT_DEC_KZPSA,
	    0,
	    "Digital Equipment",
	    "KZPSA",
	},
	{
	    PCI_VENDOR_DEC, PCI_PRODUCT_DEC_21140,
	    0,
	    "Digital Equipment",
	    "DECchip 21140 (FasterNet)",
	},
	{
	    PCI_VENDOR_DEC, PCI_PRODUCT_DEC_PBXGB,
	    0,
	    "Digital Equipment",
	    "TGA2",
	},
	{
	    PCI_VENDOR_DEC, PCI_PRODUCT_DEC_DEFPA,
	    0,
	    "Digital Equipment",
	    "DEFPA",
	},
	{
	    PCI_VENDOR_DEC, PCI_PRODUCT_DEC_21041,
	    0,
	    "Digital Equipment",
	    "DECchip 21041 (Tulip Pass 3)",
	},
	{
	    PCI_VENDOR_DEC, PCI_PRODUCT_DEC_DGLPB,
	    0,
	    "Digital Equipment",
	    "DGLPB (OPPO)",
	},
	{
	    PCI_VENDOR_DEC, PCI_PRODUCT_DEC_21142,
	    0,
	    "Digital Equipment",
	    "DECchip 21142/3",
	},
	{
	    PCI_VENDOR_DEC, PCI_PRODUCT_DEC_21052,
	    0,
	    "Digital Equipment",
	    "DECchip 21052 PCI-PCI Bridge",
	},
	{
	    PCI_VENDOR_DEC, PCI_PRODUCT_DEC_21150,
	    0,
	    "Digital Equipment",
	    "DECchip 21150 PCI-PCI Bridge",
	},
	{
	    PCI_VENDOR_DEC, PCI_PRODUCT_DEC_21152,
	    0,
	    "Digital Equipment",
	    "DECchip 21152 PCI-PCI Bridge",
	},
	{
	    PCI_VENDOR_DEC, PCI_PRODUCT_DEC_21153,
	    0,
	    "Digital Equipment",
	    "DECchip 21153 PCI-PCI Bridge",
	},
	{
	    PCI_VENDOR_DEC, PCI_PRODUCT_DEC_21154,
	    0,
	    "Digital Equipment",
	    "DECchip 21154 PCI-PCI Bridge",
	},
	{
	    PCI_VENDOR_DIAMOND, PCI_PRODUCT_DIAMOND_VIPER,
	    0,
	    "Diamond Computer Systems",
	    "Viper/PCI",
	},
	{
	    PCI_VENDOR_DIAMOND, PCI_PRODUCT_DIAMOND_MONSTER,
	    0,
	    "Diamond Computer Systems",
	    "Monster",
	},
	{
	    PCI_VENDOR_DPT, PCI_PRODUCT_DPT_SC_RAID,
	    0,
	    "Distributed Processing Technology",
	    "SmartCache/Raid",
	},
	{
	    PCI_VENDOR_DOLPHIN, PCI_PRODUCT_DOLPHIN_PCISCI,
	    0,
	    "Dolphin Interconnect Solutions",
	    "PCI-SCI Bridge",
	},
	{
	    PCI_VENDOR_EMULEX, PCI_PRODUCT_EMULEX_LPPFC,
	    0,
	    "Emulex",
	    "Light Pulse FibreChannel adapter",
	},
	{
	    PCI_VENDOR_ENSONIQ, PCI_PRODUCT_ENSONIQ_AUDIOPCI,
	    0,
	    "Ensoniq",
	    "AudioPCI",
	},
	{
	    PCI_VENDOR_ESSENTIAL, PCI_PRODUCT_ESSENTIAL_RR_HIPPI,
	    0,
	    "Essential Communications",
	    "RoadRunner HIPPI Interface",
	},
	{
	    PCI_VENDOR_ESSENTIAL, PCI_PRODUCT_ESSENTIAL_RR_GIGE,
	    0,
	    "Essential Communications",
	    "RoadRunner Gig-E Interface",
	},
	{
	    PCI_VENDOR_ES, PCI_PRODUCT_ES_FREEDOM,
	    0,
	    "Evans & Sutherland",
	    "Freedom PCI-GBus Interface",
	},
	{
	    PCI_VENDOR_FORE, PCI_PRODUCT_FORE_PCA200,
	    0,
	    "FORE Systems",
	    "ATM PCA-200",
	},
	{
	    PCI_VENDOR_FORE, PCI_PRODUCT_FORE_PCA200E,
	    0,
	    "FORE Systems",
	    "ATM PCA-200e",
	},
	{
	    PCI_VENDOR_FUTUREDOMAIN, PCI_PRODUCT_FUTUREDOMAIN_TMC_18C30,
	    0,
	    "Future Domain",
	    "TMC-18C30 (36C70)",
	},
	{
	    PCI_VENDOR_EFFICIENTNETS, PCI_PRODUCT_EFFICIENTNETS_ENI155PF,
	    0,
	    "Efficent Networks",
	    "155P-MF1 ATM (FPGA)",
	},
	{
	    PCI_VENDOR_EFFICIENTNETS, PCI_PRODUCT_EFFICIENTNETS_ENI155PA,
	    0,
	    "Efficent Networks",
	    "155P-MF1 ATM (ASIC)",
	},
	{
	    PCI_VENDOR_HP, PCI_PRODUCT_HP_J2585A,
	    0,
	    "Hewlett-Packard",
	    "J2585A",
	},
	{
	    PCI_VENDOR_IBM, PCI_PRODUCT_IBM_0x0002,
	    0,
	    "IBM",
	    "MCA Bridge",
	},
	{
	    PCI_VENDOR_IBM, PCI_PRODUCT_IBM_0x0005,
	    0,
	    "IBM",
	    "CPU Bridge - Alta Lite",
	},
	{
	    PCI_VENDOR_IBM, PCI_PRODUCT_IBM_0x0007,
	    0,
	    "IBM",
	    "CPU Bridge - Alta MP",
	},
	{
	    PCI_VENDOR_IBM, PCI_PRODUCT_IBM_0x000a,
	    0,
	    "IBM",
	    "ISA Bridge w/PnP",
	},
	{
	    PCI_VENDOR_IBM, PCI_PRODUCT_IBM_0x0017,
	    0,
	    "IBM",
	    "CPU Bridge",
	},
	{
	    PCI_VENDOR_IBM, PCI_PRODUCT_IBM_0x0018,
	    0,
	    "IBM",
	    "Auto LANStreamer",
	},
	{
	    PCI_VENDOR_IBM, PCI_PRODUCT_IBM_GXT150P,
	    0,
	    "IBM",
	    "GXT-150P 2D Accelerator",
	},
	{
	    PCI_VENDOR_IBM, PCI_PRODUCT_IBM_0x0020,
	    0,
	    "IBM",
	    "MCA Bridge",
	},
	{
	    PCI_VENDOR_IBM, PCI_PRODUCT_IBM_82351,
	    0,
	    "IBM",
	    "82351 PCI-PCI Bridge",
	},
	{
	    PCI_VENDOR_IBM, PCI_PRODUCT_IBM_0x0036,
	    0,
	    "IBM",
	    "Miami/PCI",
	},
	{
	    PCI_VENDOR_IDT, PCI_PRODUCT_IDT_77201,
	    0,
	    "IDT",
	    "77201/77211 ATM (NICStAR)",
	},
	{
	    PCI_VENDOR_IMS, PCI_PRODUCT_IMS_8849,
	    0,
	    "Integrated Micro Solutions",
	    "8849",
	},
	{
	    PCI_VENDOR_INTEL, PCI_PRODUCT_INTEL_PCEB,
	    0,
	    "Intel",
	    "82375EB PCI-EISA Bridge",
	},
	{
	    PCI_VENDOR_INTEL, PCI_PRODUCT_INTEL_CDC,
	    0,
	    "Intel",
	    "82424ZX (Saturn) Cache and DRAM controller",
	},
	{
	    PCI_VENDOR_INTEL, PCI_PRODUCT_INTEL_SIO,
	    0,
	    "Intel",
	    "82378IB PCI-ISA Bridge (System I/O)",
	},
	{
	    PCI_VENDOR_INTEL, PCI_PRODUCT_INTEL_82426EX,
	    0,
	    "Intel",
	    "82426EX PCI-to-ISA Bridge (PCIB)",
	},
	{
	    PCI_VENDOR_INTEL, PCI_PRODUCT_INTEL_PCMC,
	    0,
	    "Intel",
	    "82434LX/NX (Mercury/Neptune) PCI/Cache/DRAM Controller",
	},
	{
	    PCI_VENDOR_INTEL, PCI_PRODUCT_INTEL_82092AA,
	    0,
	    "Intel",
	    "82092AA IDE controller",
	},
	{
	    PCI_VENDOR_INTEL, PCI_PRODUCT_INTEL_SAA7116,
	    0,
	    "Intel",
	    "SAA7116",
	},
	{
	    PCI_VENDOR_INTEL, PCI_PRODUCT_INTEL_82596,
	    0,
	    "Intel",
	    "82596 Ethernet",
	},
	{
	    PCI_VENDOR_INTEL, PCI_PRODUCT_INTEL_EEPRO100,
	    0,
	    "Intel",
	    "EE Pro 100 10/100 Fast Ethernet",
	},
	{
	    PCI_VENDOR_INTEL, PCI_PRODUCT_INTEL_EEPRO100S,
	    0,
	    "Intel",
	    "EE Pro 100 Smart 10/100 Fast Ethernet",
	},
	{
	    PCI_VENDOR_INTEL, PCI_PRODUCT_INTEL_82557,
	    0,
	    "Intel",
	    "82557 Fast Ethernet",
	},
	{
	    PCI_VENDOR_INTEL, PCI_PRODUCT_INTEL_82437FX,
	    0,
	    "Intel",
	    "82437FX (Triton) PCI, Cache, and DRAM Controller",
	},
	{
	    PCI_VENDOR_INTEL, PCI_PRODUCT_INTEL_82371,
	    0,
	    "Intel",
	    "82371FB (Triton) PCI-ISA Bridge",
	},
	{
	    PCI_VENDOR_INTEL, PCI_PRODUCT_INTEL_82438,
	    0,
	    "Intel",
	    "82438 (Triton) IDE controller",
	},
	{
	    PCI_VENDOR_INTEL, PCI_PRODUCT_INTEL_82371MX,
	    0,
	    "Intel",
	    "82371 (Triton MX) PCI-ISA and IDE",
	},
	{
	    PCI_VENDOR_INTEL, PCI_PRODUCT_INTEL_82437MX,
	    0,
	    "Intel",
	    "82437 (Triton MX) PCI/CACHECOMP/DRAM Controller",
	},
	{
	    PCI_VENDOR_INTEL, PCI_PRODUCT_INTEL_82441FX,
	    0,
	    "Intel",
	    "82441FX PCI and Memory Controller (PMC)",
	},
	{
	    PCI_VENDOR_INTEL, PCI_PRODUCT_INTEL_82380AB,
	    0,
	    "Intel",
	    "82380AB Mobile PCI-to-ISA Bridge (MISA)",
	},
	{
	    PCI_VENDOR_INTEL, PCI_PRODUCT_INTEL_82380FB,
	    0,
	    "Intel",
	    "82380FB Mobile PCI-to-PCI Bridge (MPCI2)",
	},
	{
	    PCI_VENDOR_INTEL, PCI_PRODUCT_INTEL_82439HX,
	    0,
	    "Intel",
	    "82439HX (Triton II) TXC Host Bridge",
	},
	{
	    PCI_VENDOR_INTEL, PCI_PRODUCT_INTEL_82371SB,
	    0,
	    "Intel",
	    "82371SB (Triton II) PCI-ISA Bridge",
	},
	{
	    PCI_VENDOR_INTEL, PCI_PRODUCT_INTEL_82371IDE,
	    0,
	    "Intel",
	    "82371SB (Triton II) IDE controller",
	},
	{
	    PCI_VENDOR_INTEL, PCI_PRODUCT_INTEL_82371USB,
	    0,
	    "Intel",
	    "82371SB (Triton II) USB Interface",
	},
	{
	    PCI_VENDOR_INTEL, PCI_PRODUCT_INTEL_82437VX,
	    0,
	    "Intel",
	    "82437VX System Controller (TVX)",
	},
	{
	    PCI_VENDOR_INTEL, PCI_PRODUCT_INTEL_82439TX,
	    0,
	    "Intel",
	    "82439TX System Controller (MTXC)",
	},
	{
	    PCI_VENDOR_INTEL, PCI_PRODUCT_INTEL_82371AB,
	    0,
	    "Intel",
	    "82371AB PIIX4 ISA Bridge",
	},
	{
	    PCI_VENDOR_INTEL, PCI_PRODUCT_INTEL_82371AB_IDE,
	    0,
	    "Intel",
	    "82371AB IDE controller (PIIX4)",
	},
	{
	    PCI_VENDOR_INTEL, PCI_PRODUCT_INTEL_82371AB_USB,
	    0,
	    "Intel",
	    "82371AB USB Host Controller (PIIX4)",
	},
	{
	    PCI_VENDOR_INTEL, PCI_PRODUCT_INTEL_82371AB_PMC,
	    0,
	    "Intel",
	    "82371AB Power Management Controller (PIIX4)",
	},
	{
	    PCI_VENDOR_INTEL, PCI_PRODUCT_INTEL_82443LX,
	    0,
	    "Intel",
	    "82443LX PCI AGP Controller (PAC)",
	},
	{
	    PCI_VENDOR_INTEL, PCI_PRODUCT_INTEL_82443LX_AGP,
	    0,
	    "Intel",
	    "82443LX AGP Device (PAC)",
	},
	{
	    PCI_VENDOR_INTEL, PCI_PRODUCT_INTEL_82443BX,
	    0,
	    "Intel",
	    "82443BX PCI AGP Controller (PAC)",
	},
	{
	    PCI_VENDOR_INTEL, PCI_PRODUCT_INTEL_82443BX_AGP,
	    0,
	    "Intel",
	    "82443BX AGP Device (PAC)",
	},
	{
	    PCI_VENDOR_INTEL, PCI_PRODUCT_INTEL_PCI450_PB,
	    0,
	    "Intel",
	    "450 PCIset (Orion) Host-PCI bridge",
	},
	{
	    PCI_VENDOR_INTEL, PCI_PRODUCT_INTEL_PCI450_MC,
	    0,
	    "Intel",
	    "450 PCIset (Orion) Memory Controller",
	},
	{
	    PCI_VENDOR_ITT, PCI_PRODUCT_ITT_AGX016,
	    0,
	    "I. T. T.",
	    "AGX016",
	},
	{
	    PCI_VENDOR_ITT, PCI_PRODUCT_ITT_ITT3204,
	    0,
	    "I. T. T.",
	    "ITT3204 MPEG Decoder",
	},
	{
	    PCI_VENDOR_KTI, PCI_PRODUCT_KTI_KTIE,
	    0,
	    "KTI",
	    "KTI Ethernet",
	},
	{
	    PCI_VENDOR_LEADTEK, PCI_PRODUCT_LEADTEK_S3_805,
	    0,
	    "LeadTek Research",
	    "S3 805",
	},
	{
	    PCI_VENDOR_LITEON, PCI_PRODUCT_LITEON_PNIC,
	    0,
	    "Lite-On",
	    "PNIC",
	},
	{
	    PCI_VENDOR_MACRONIX, PCI_PRODUCT_MACRONIX_MX98713,
	    0,
	    "Macronix",
	    "PMAC 100/10base PCI MAC controller",
	},
	{
	    PCI_VENDOR_MADGE, PCI_PRODUCT_MADGE_COLLAGE25,
	    0,
	    "Madge Networks",
	    "Collage 25 ATM adapter",
	},
	{
	    PCI_VENDOR_MADGE, PCI_PRODUCT_MADGE_COLLAGE155,
	    0,
	    "Madge Networks",
	    "Collage 155 ATM adapter",
	},
	{
	    PCI_VENDOR_MATROX, PCI_PRODUCT_MATROX_IMPRESSION,
	    0,
	    "Matrox",
	    "MGA Impression",
	},
	{
	    PCI_VENDOR_MATROX, PCI_PRODUCT_MATROX_ATLAS,
	    0,
	    "Matrox",
	    "MGA PX2085 (Atlas)",
	},
	{
	    PCI_VENDOR_MATROX, PCI_PRODUCT_MATROX_MILLENIUM,
	    0,
	    "Matrox",
	    "MGA Millenium 2064W (Storm)",
	},
	{
	    PCI_VENDOR_MATROX, PCI_PRODUCT_MATROX_MYSTIQUE_220,
	    0,
	    "Matrox",
	    "MGA 1064SG 220MHz",
	},
	{
	    PCI_VENDOR_MATROX, PCI_PRODUCT_MATROX_MILLENNIUM_II,
	    0,
	    "Matrox",
	    "MGA Millennium II 2164W",
	},
	{
	    PCI_VENDOR_MATROX, PCI_PRODUCT_MATROX_MILLENNIUM_IIAGP,
	    0,
	    "Matrox",
	    "MGA Millennium II 2164WA-B AGP",
	},
	{
	    PCI_VENDOR_MATROX, PCI_PRODUCT_MATROX_MYSTIQUE,
	    0,
	    "Matrox",
	    "MGA 1064SG",
	},
	{
	    PCI_VENDOR_MATROX, PCI_PRODUCT_MATROX_PRODUCTIVA,
	    0,
	    "Matrox",
	    "MGA Productiva G100 AGP",
	},
	{
	    PCI_VENDOR_MYLEX, PCI_PRODUCT_MYLEX_960P,
	    0,
	    "Mylex",
	    "DAC960P RAID controller",
	},
	{
	    PCI_VENDOR_MUTECH, PCI_PRODUCT_MUTECH_MV1000,
	    0,
	    "Mutech",
	    "MV1000",
	},
	{
	    PCI_VENDOR_NS, PCI_PRODUCT_NS_DP83810,
	    0,
	    "National Semiconductor",
	    "DP83810 10/100 Ethernet",
	},
	{
	    PCI_VENDOR_NS, PCI_PRODUCT_NS_NS87410,
	    0,
	    "National Semiconductor",
	    "NS87410",
	},
	{
	    PCI_VENDOR_NEC, PCI_PRODUCT_NEC_XXX,
	    0,
	    "NEC",
	    "XXX USB",
	},
	{
	    PCI_VENDOR_NEC, PCI_PRODUCT_NEC_POWERVR2,
	    0,
	    "NEC",
	    "PowerVR PCX2",
	},
	{
	    PCI_VENDOR_NEOMAGIC, PCI_PRODUCT_NEOMAGIC_NM3160,
	    0,
	    "Neomagic",
	    "NM3160",
	},
	{
	    PCI_VENDOR_NETVIN, PCI_PRODUCT_NETVIN_NV5000,
	    0,
	    "NetVin",
	    "NetVin 5000",
	},
	{
	    PCI_VENDOR_SYMBIOS, PCI_PRODUCT_SYMBIOS_810,
	    0,
	    "Symbios Logic",
	    "53c810",
	},
	{
	    PCI_VENDOR_SYMBIOS, PCI_PRODUCT_SYMBIOS_820,
	    0,
	    "Symbios Logic",
	    "53c820",
	},
	{
	    PCI_VENDOR_SYMBIOS, PCI_PRODUCT_SYMBIOS_825,
	    0,
	    "Symbios Logic",
	    "53c825",
	},
	{
	    PCI_VENDOR_SYMBIOS, PCI_PRODUCT_SYMBIOS_815,
	    0,
	    "Symbios Logic",
	    "53c815",
	},
	{
	    PCI_VENDOR_SYMBIOS, PCI_PRODUCT_SYMBIOS_810AP,
	    0,
	    "Symbios Logic",
	    "53c810AP",
	},
	{
	    PCI_VENDOR_SYMBIOS, PCI_PRODUCT_SYMBIOS_860,
	    0,
	    "Symbios Logic",
	    "53c860",
	},
	{
	    PCI_VENDOR_SYMBIOS, PCI_PRODUCT_SYMBIOS_875,
	    0,
	    "Symbios Logic",
	    "53c875",
	},
	{
	    PCI_VENDOR_SYMBIOS, PCI_PRODUCT_SYMBIOS_875J,
	    0,
	    "Symbios Logic",
	    "53c875J",
	},
	{
	    PCI_VENDOR_SYMBIOS, PCI_PRODUCT_SYMBIOS_885,
	    0,
	    "Symbios Logic",
	    "53c885",
	},
	{
	    PCI_VENDOR_SYMBIOS, PCI_PRODUCT_SYMBIOS_895,
	    0,
	    "Symbios Logic",
	    "53c895",
	},
	{
	    PCI_VENDOR_SYMBIOS, PCI_PRODUCT_SYMBIOS_896,
	    0,
	    "Symbios Logic",
	    "53c896",
	},
	{
	    PCI_VENDOR_SYMBIOS, PCI_PRODUCT_SYMBIOS_PE_GNIC,
	    0,
	    "Symbios Logic",
	    "Packet Engines G-NIC Ethernet",
	},
	{
	    PCI_VENDOR_NEXGEN, PCI_PRODUCT_NEXGEN_NX82C501,
	    0,
	    "NexGen Microsystems",
	    "NX82C501 Host-PCI Bridge",
	},
	{
	    PCI_VENDOR_NKK, PCI_PRODUCT_NKK_NDR4600,
	    0,
	    "NKK",
	    "NDR4600 Host-PCI Bridge",
	},
	{
	    PCI_VENDOR_NUMBER9, PCI_PRODUCT_NUMBER9_I128,
	    0,
	    "Number 9 Computer Company",
	    "Imagine-128",
	},
	{
	    PCI_VENDOR_NUMBER9, PCI_PRODUCT_NUMBER9_I128_2,
	    0,
	    "Number 9 Computer Company",
	    "Imagine-128 II",
	},
	{
	    PCI_VENDOR_OAKTECH, PCI_PRODUCT_OAKTECH_OTI1007,
	    0,
	    "Oak Technology",
	    "OTI107",
	},
	{
	    PCI_VENDOR_OPTI, PCI_PRODUCT_OPTI_82C557,
	    0,
	    "Opti",
	    "82C557 Host Bridge",
	},
	{
	    PCI_VENDOR_OPTI, PCI_PRODUCT_OPTI_82C558,
	    0,
	    "Opti",
	    "82C558 PCI-ISA Bridge",
	},
	{
	    PCI_VENDOR_OPTI, PCI_PRODUCT_OPTI_82C621,
	    0,
	    "Opti",
	    "82C621 IDE",
	},
	{
	    PCI_VENDOR_OPTI, PCI_PRODUCT_OPTI_82C822,
	    0,
	    "Opti",
	    "82C822",
	},
	{
	    PCI_VENDOR_OPTI, PCI_PRODUCT_OPTI_RM861HA,
	    0,
	    "Opti",
	    "RM861HA",
	},
	{
	    PCI_VENDOR_PCTECH, PCI_PRODUCT_PCTECH_RZ1000,
	    0,
	    "PC Technology",
	    "RZ1000",
	},
	{
	    PCI_VENDOR_PROMISE, PCI_PRODUCT_PROMISE_DC5030,
	    0,
	    "Promise Technology",
	    "DC5030",
	},
	{
	    PCI_VENDOR_PROMISE, PCI_PRODUCT_PROMISE_ULTRA33,
	    0,
	    "Promise Technology",
	    "Ultra DMA/ATA Bus Master IDE Accelerator",
	},
	{
	    PCI_VENDOR_QLOGIC, PCI_PRODUCT_QLOGIC_ISP1020,
	    0,
	    "QLogic",
	    "ISP1020",
	},
	{
	    PCI_VENDOR_QLOGIC, PCI_PRODUCT_QLOGIC_ISP1022,
	    0,
	    "QLogic",
	    "ISP1022",
	},
	{
	    PCI_VENDOR_QLOGIC, PCI_PRODUCT_QLOGIC_ISP2100,
	    0,
	    "QLogic",
	    "ISP2100",
	},
	{
	    PCI_VENDOR_QUANTUMDESIGNS, PCI_PRODUCT_QUANTUMDESIGNS_8500,
	    0,
	    "Quantum Designs",
	    "8500",
	},
	{
	    PCI_VENDOR_QUANTUMDESIGNS, PCI_PRODUCT_QUANTUMDESIGNS_8580,
	    0,
	    "Quantum Designs",
	    "8580",
	},
	{
	    PCI_VENDOR_REALTEK, PCI_PRODUCT_REALTEK_RT8029,
	    0,
	    "Realtek Semiconductor",
	    "Ethernet",
	},
	{
	    PCI_VENDOR_REALTEK, PCI_PRODUCT_REALTEK_RT8139,
	    0,
	    "Realtek Semiconductor",
	    "100Mb Ethernet",
	},
	{
	    PCI_VENDOR_S3, PCI_PRODUCT_S3_VIRGE,
	    0,
	    "S3",
	    "ViRGE",
	},
	{
	    PCI_VENDOR_S3, PCI_PRODUCT_S3_TRIO32,
	    0,
	    "S3",
	    "Trio32",
	},
	{
	    PCI_VENDOR_S3, PCI_PRODUCT_S3_TRIO64,
	    0,
	    "S3",
	    "Trio32/64",
	},
	{
	    PCI_VENDOR_S3, PCI_PRODUCT_S3_AURORA64P,
	    0,
	    "S3",
	    "Aurora64V+",
	},
	{
	    PCI_VENDOR_S3, PCI_PRODUCT_S3_TRIO64UVP,
	    0,
	    "S3",
	    "Trio64UV+",
	},
	{
	    PCI_VENDOR_S3, PCI_PRODUCT_S3_868,
	    0,
	    "S3",
	    "868",
	},
	{
	    PCI_VENDOR_S3, PCI_PRODUCT_S3_VIRGE_VX,
	    0,
	    "S3",
	    "ViRGE VX",
	},
	{
	    PCI_VENDOR_S3, PCI_PRODUCT_S3_928,
	    0,
	    "S3",
	    "86C928",
	},
	{
	    PCI_VENDOR_S3, PCI_PRODUCT_S3_864_0,
	    0,
	    "S3",
	    "86C864-0 (Vision864)",
	},
	{
	    PCI_VENDOR_S3, PCI_PRODUCT_S3_864_1,
	    0,
	    "S3",
	    "86C864-1 (Vision864)",
	},
	{
	    PCI_VENDOR_S3, PCI_PRODUCT_S3_864_2,
	    0,
	    "S3",
	    "86C864-2 (Vision864)",
	},
	{
	    PCI_VENDOR_S3, PCI_PRODUCT_S3_864_3,
	    0,
	    "S3",
	    "86C864-3 (Vision864)",
	},
	{
	    PCI_VENDOR_S3, PCI_PRODUCT_S3_964_0,
	    0,
	    "S3",
	    "86C964-0 (Vision964)",
	},
	{
	    PCI_VENDOR_S3, PCI_PRODUCT_S3_964_1,
	    0,
	    "S3",
	    "86C964-1 (Vision964)",
	},
	{
	    PCI_VENDOR_S3, PCI_PRODUCT_S3_964_2,
	    0,
	    "S3",
	    "86C964-2 (Vision964)",
	},
	{
	    PCI_VENDOR_S3, PCI_PRODUCT_S3_964_3,
	    0,
	    "S3",
	    "86C964-3 (Vision964)",
	},
	{
	    PCI_VENDOR_S3, PCI_PRODUCT_S3_968_0,
	    0,
	    "S3",
	    "86C968-0 (Vision968)",
	},
	{
	    PCI_VENDOR_S3, PCI_PRODUCT_S3_968_1,
	    0,
	    "S3",
	    "86C968-1 (Vision968)",
	},
	{
	    PCI_VENDOR_S3, PCI_PRODUCT_S3_968_2,
	    0,
	    "S3",
	    "86C968-2 (Vision968)",
	},
	{
	    PCI_VENDOR_S3, PCI_PRODUCT_S3_968_3,
	    0,
	    "S3",
	    "86C968-3 (Vision968)",
	},
	{
	    PCI_VENDOR_S3, PCI_PRODUCT_S3_TRIO64V2_DX,
	    0,
	    "S3",
	    "Trio64V2/DX",
	},
	{
	    PCI_VENDOR_S3, PCI_PRODUCT_S3_PLATO,
	    0,
	    "S3",
	    "Plato",
	},
	{
	    PCI_VENDOR_S3, PCI_PRODUCT_S3_VIRGE_DX_GX,
	    0,
	    "S3",
	    "ViRGE DX/GX",
	},
	{
	    PCI_VENDOR_S3, PCI_PRODUCT_S3_VIRGE_GX2,
	    0,
	    "S3",
	    "ViRGE GX2",
	},
	{
	    PCI_VENDOR_S3, PCI_PRODUCT_S3_VIRGE_MX,
	    0,
	    "S3",
	    "ViRGE MX",
	},
	{
	    PCI_VENDOR_S3, PCI_PRODUCT_S3_VIRGE_MXP,
	    0,
	    "S3",
	    "ViRGE MXP",
	},
	{
	    PCI_VENDOR_S3, PCI_PRODUCT_S3_SONICVIBES,
	    0,
	    "S3",
	    "SonicVibes",
	},
	{
	    PCI_VENDOR_SGSTHOMSON, PCI_PRODUCT_SGSTHOMSON_2000,
	    0,
	    "SGS Thomson Microelectric",
	    "STG 2000X",
	},
	{
	    PCI_VENDOR_SGSTHOMSON, PCI_PRODUCT_SGSTHOMSON_1764,
	    0,
	    "SGS Thomson Microelectric",
	    "STG 1764X",
	},
	{
	    PCI_VENDOR_SIGMA, PCI_PRODUCT_SIGMA_64GX,
	    0,
	    "Sigma Designs",
	    "64GX",
	},
	{
	    PCI_VENDOR_SIS, PCI_PRODUCT_SIS_86C201,
	    0,
	    "Silicon Integrated System",
	    "86C201 Host-AGP Bridge",
	},
	{
	    PCI_VENDOR_SIS, PCI_PRODUCT_SIS_86C202,
	    0,
	    "Silicon Integrated System",
	    "86C202 VGA Controller",
	},
	{
	    PCI_VENDOR_SIS, PCI_PRODUCT_SIS_86C205,
	    0,
	    "Silicon Integrated System",
	    "86C205",
	},
	{
	    PCI_VENDOR_SIS, PCI_PRODUCT_SIS_85C503,
	    0,
	    "Silicon Integrated System",
	    "85C503 ISA Bridge",
	},
	{
	    PCI_VENDOR_SIS, PCI_PRODUCT_SIS_5595,
	    0,
	    "Silicon Integrated System",
	    "5595 PCI System I/O Chipset",
	},
	{
	    PCI_VENDOR_SIS, PCI_PRODUCT_SIS_85C501,
	    0,
	    "Silicon Integrated System",
	    "85C501",
	},
	{
	    PCI_VENDOR_SIS, PCI_PRODUCT_SIS_85C496,
	    0,
	    "Silicon Integrated System",
	    "85C496",
	},
	{
	    PCI_VENDOR_SIS, PCI_PRODUCT_SIS_85C596,
	    0,
	    "Silicon Integrated System",
	    "85C596",
	},
	{
	    PCI_VENDOR_SIS, PCI_PRODUCT_SIS_85C601,
	    0,
	    "Silicon Integrated System",
	    "85C601 EIDE Controller",
	},
	{
	    PCI_VENDOR_SIS, PCI_PRODUCT_SIS_5511,
	    0,
	    "Silicon Integrated System",
	    "5511",
	},
	{
	    PCI_VENDOR_SIS, PCI_PRODUCT_SIS_5512,
	    0,
	    "Silicon Integrated System",
	    "5512",
	},
	{
	    PCI_VENDOR_SIS, PCI_PRODUCT_SIS_5513,
	    0,
	    "Silicon Integrated System",
	    "5513 EIDE Controller",
	},
	{
	    PCI_VENDOR_SIS, PCI_PRODUCT_SIS_5581,
	    0,
	    "Silicon Integrated System",
	    "5581",
	},
	{
	    PCI_VENDOR_SIS, PCI_PRODUCT_SIS_5582,
	    0,
	    "Silicon Integrated System",
	    "5582",
	},
	{
	    PCI_VENDOR_SIS, PCI_PRODUCT_SIS_5591,
	    0,
	    "Silicon Integrated System",
	    "5591 Host-PCI Bridge",
	},
	{
	    PCI_VENDOR_SIS, PCI_PRODUCT_SIS_5596,
	    0,
	    "Silicon Integrated System",
	    "5596",
	},
	{
	    PCI_VENDOR_SIS, PCI_PRODUCT_SIS_5598,
	    0,
	    "Silicon Integrated System",
	    "5598",
	},
	{
	    PCI_VENDOR_SIS, PCI_PRODUCT_SIS_6204,
	    0,
	    "Silicon Integrated System",
	    "6204",
	},
	{
	    PCI_VENDOR_SIS, PCI_PRODUCT_SIS_6205,
	    0,
	    "Silicon Integrated System",
	    "6205",
	},
	{
	    PCI_VENDOR_SMC, PCI_PRODUCT_SMC_37C665,
	    0,
	    "Standard Microsystems",
	    "FDC 37C665",
	},
	{
	    PCI_VENDOR_SMC, PCI_PRODUCT_SMC_37C922,
	    0,
	    "Standard Microsystems",
	    "FDC 37C922",
	},
	{
	    PCI_VENDOR_SMC, PCI_PRODUCT_SMC_83C170,
	    0,
	    "Standard Microsystems",
	    "83C170 (EPIC/100) Fast Ethernet",
	},
	{
	    PCI_VENDOR_STB2, PCI_PRODUCT_STB2_RIVA128,
	    0,
	    "STB (2nd ID)",
	    "Velocity128",
	},
	{
	    PCI_VENDOR_SURECOM, PCI_PRODUCT_SURECOM_NE34,
	    0,
	    "Surecom Technology",
	    "Surecom NE-34",
	},
	{
	    PCI_VENDOR_SYMPHONY, PCI_PRODUCT_SYMPHONY_82C101,
	    0,
	    "Symphony Labs",
	    "82C101",
	},
	{
	    PCI_VENDOR_SYMPHONY, PCI_PRODUCT_SYMPHONY_82C103,
	    0,
	    "Symphony Labs",
	    "82C103",
	},
	{
	    PCI_VENDOR_SYMPHONY, PCI_PRODUCT_SYMPHONY_82C105,
	    0,
	    "Symphony Labs",
	    "82C105",
	},
	{
	    PCI_VENDOR_SYMPHONY2, PCI_PRODUCT_SYMPHONY2_82C101,
	    0,
	    "Symphony Labs (2nd ID)",
	    "82C101",
	},
	{
	    PCI_VENDOR_TEKRAM, PCI_PRODUCT_TEKRAM_DC290,
	    0,
	    "Tekram Technology (1st ID)",
	    "DC-290(M)",
	},
	{
	    PCI_VENDOR_TEKRAM2, PCI_PRODUCT_TEKRAM2_DC690C,
	    0,
	    "Tekram Technology (2nd ID)",
	    "DC-690C",
	},
	{
	    PCI_VENDOR_TI, PCI_PRODUCT_TI_TLAN,
	    0,
	    "Texas Instruments",
	    "TLAN",
	},
	{
	    PCI_VENDOR_TI, PCI_PRODUCT_TI_PCI1130,
	    0,
	    "Texas Instruments",
	    "PCI1130 PCI-CardBus Bridge",
	},
	{
	    PCI_VENDOR_TI, PCI_PRODUCT_TI_PCI1131,
	    0,
	    "Texas Instruments",
	    "PCI1131",
	},
	{
	    PCI_VENDOR_TI, PCI_PRODUCT_TI_PCI1250,
	    0,
	    "Texas Instruments",
	    "PCI1250",
	},
	{
	    PCI_VENDOR_TI, PCI_PRODUCT_TI_PCI1220,
	    0,
	    "Texas Instruments",
	    "PCI1220 PCI-CardBus Bridge",
	},
	{
	    PCI_VENDOR_TI, PCI_PRODUCT_TI_PCI2030,
	    0,
	    "Texas Instruments",
	    "PCI2030",
	},
	{
	    PCI_VENDOR_TOSHIBA, PCI_PRODUCT_TOSHIBA_R4X00,
	    0,
	    "Toshiba America",
	    "R4x00 Host-PCI Bridge",
	},
	{
	    PCI_VENDOR_TOSHIBA, PCI_PRODUCT_TOSHIBA_TC35856F,
	    0,
	    "Toshiba America",
	    "TC35856F ATM (Meteor)",
	},
	{
	    PCI_VENDOR_TRIDENT, PCI_PRODUCT_TRIDENT_TGUI_9320,
	    0,
	    "Trident Microsystems",
	    "TGUI 9320",
	},
	{
	    PCI_VENDOR_TRIDENT, PCI_PRODUCT_TRIDENT_TGUI_9350,
	    0,
	    "Trident Microsystems",
	    "TGUI 9350",
	},
	{
	    PCI_VENDOR_TRIDENT, PCI_PRODUCT_TRIDENT_TGUI_9360,
	    0,
	    "Trident Microsystems",
	    "TGUI 9360",
	},
	{
	    PCI_VENDOR_TRIDENT, PCI_PRODUCT_TRIDENT_TGUI_9420,
	    0,
	    "Trident Microsystems",
	    "TGUI 9420",
	},
	{
	    PCI_VENDOR_TRIDENT, PCI_PRODUCT_TRIDENT_TGUI_9440,
	    0,
	    "Trident Microsystems",
	    "TGUI 9440",
	},
	{
	    PCI_VENDOR_TRIDENT, PCI_PRODUCT_TRIDENT_TGUI_9660,
	    0,
	    "Trident Microsystems",
	    "TGUI 9660",
	},
	{
	    PCI_VENDOR_TRIDENT, PCI_PRODUCT_TRIDENT_TGUI_9680,
	    0,
	    "Trident Microsystems",
	    "TGUI 9680",
	},
	{
	    PCI_VENDOR_TRIDENT, PCI_PRODUCT_TRIDENT_TGUI_9682,
	    0,
	    "Trident Microsystems",
	    "TGUI 9682",
	},
	{
	    PCI_VENDOR_TRITECH, PCI_PRODUCT_TRITECH_TR25202,
	    0,
	    "TriTech Microelectronics",
	    "Pyramid3D TR25202",
	},
	{
	    PCI_VENDOR_TSENG, PCI_PRODUCT_TSENG_ET4000_W32P_A,
	    0,
	    "Tseng Labs",
	    "ET4000w32p rev A",
	},
	{
	    PCI_VENDOR_TSENG, PCI_PRODUCT_TSENG_ET4000_W32P_B,
	    0,
	    "Tseng Labs",
	    "ET4000w32p rev B",
	},
	{
	    PCI_VENDOR_TSENG, PCI_PRODUCT_TSENG_ET4000_W32P_C,
	    0,
	    "Tseng Labs",
	    "ET4000w32p rev C",
	},
	{
	    PCI_VENDOR_TSENG, PCI_PRODUCT_TSENG_ET4000_W32P_D,
	    0,
	    "Tseng Labs",
	    "ET4000w32p rev D",
	},
	{
	    PCI_VENDOR_TSENG, PCI_PRODUCT_TSENG_ET6000,
	    0,
	    "Tseng Labs",
	    "ET6000",
	},
	{
	    PCI_VENDOR_UMC, PCI_PRODUCT_UMC_UM82C881,
	    0,
	    "United Microelectronics",
	    "UM82C881 486 Chipset",
	},
	{
	    PCI_VENDOR_UMC, PCI_PRODUCT_UMC_UM82C886,
	    0,
	    "United Microelectronics",
	    "UM82C886 ISA Bridge",
	},
	{
	    PCI_VENDOR_UMC, PCI_PRODUCT_UMC_UM8673F,
	    0,
	    "United Microelectronics",
	    "UM8673F EIDE Controller",
	},
	{
	    PCI_VENDOR_UMC, PCI_PRODUCT_UMC_UM8881,
	    0,
	    "United Microelectronics",
	    "UM8881 HB4 486 PCI Chipset",
	},
	{
	    PCI_VENDOR_UMC, PCI_PRODUCT_UMC_UM82C891,
	    0,
	    "United Microelectronics",
	    "UM82C891",
	},
	{
	    PCI_VENDOR_UMC, PCI_PRODUCT_UMC_UM886A,
	    0,
	    "United Microelectronics",
	    "UM886A",
	},
	{
	    PCI_VENDOR_UMC, PCI_PRODUCT_UMC_UM8886BF,
	    0,
	    "United Microelectronics",
	    "UM8886BF",
	},
	{
	    PCI_VENDOR_UMC, PCI_PRODUCT_UMC_UM8710,
	    0,
	    "United Microelectronics",
	    "UM8710",
	},
	{
	    PCI_VENDOR_UMC, PCI_PRODUCT_UMC_UM8886,
	    0,
	    "United Microelectronics",
	    "UM8886",
	},
	{
	    PCI_VENDOR_UMC, PCI_PRODUCT_UMC_UM8881F,
	    0,
	    "United Microelectronics",
	    "UM8881F PCI-Host bridge",
	},
	{
	    PCI_VENDOR_UMC, PCI_PRODUCT_UMC_UM8886F,
	    0,
	    "United Microelectronics",
	    "UM8886F PCI-ISA bridge",
	},
	{
	    PCI_VENDOR_UMC, PCI_PRODUCT_UMC_UM8886A,
	    0,
	    "United Microelectronics",
	    "UM8886A",
	},
	{
	    PCI_VENDOR_UMC, PCI_PRODUCT_UMC_UM8891A,
	    0,
	    "United Microelectronics",
	    "UM8891A",
	},
	{
	    PCI_VENDOR_UMC, PCI_PRODUCT_UMC_UM9017F,
	    0,
	    "United Microelectronics",
	    "UM9017F",
	},
	{
	    PCI_VENDOR_UMC, PCI_PRODUCT_UMC_UM8886N,
	    0,
	    "United Microelectronics",
	    "UM8886N",
	},
	{
	    PCI_VENDOR_UMC, PCI_PRODUCT_UMC_UM8891N,
	    0,
	    "United Microelectronics",
	    "UM8891N",
	},
	{
	    PCI_VENDOR_ULSI, PCI_PRODUCT_ULSI_US201,
	    0,
	    "ULSI Systems",
	    "US201",
	},
	{
	    PCI_VENDOR_V3, PCI_PRODUCT_V3_V292PBC,
	    0,
	    "V3 Semiconductor",
	    "V292PBC AMD290x0 Host-PCI Bridge",
	},
	{
	    PCI_VENDOR_V3, PCI_PRODUCT_V3_V960PBC,
	    0,
	    "V3 Semiconductor",
	    "V960PBC i960 Host-PCI Bridge",
	},
	{
	    PCI_VENDOR_V3, PCI_PRODUCT_V3_V96DPC,
	    0,
	    "V3 Semiconductor",
	    "V96DPC i960 (Dual) Host-PCI Bridge",
	},
	{
	    PCI_VENDOR_VIATECH, PCI_PRODUCT_VIATECH_VT82C505,
	    0,
	    "VIA Technologies",
	    "VT82C505 (Pluto)",
	},
	{
	    PCI_VENDOR_VIATECH, PCI_PRODUCT_VIATECH_VT82C561,
	    0,
	    "VIA Technologies",
	    "VT82C561",
	},
	{
	    PCI_VENDOR_VIATECH, PCI_PRODUCT_VIATECH_VT82C586_IDE,
	    0,
	    "VIA Technologies",
	    "VT82C586 (Apollo VP) IDE Controller",
	},
	{
	    PCI_VENDOR_VIATECH, PCI_PRODUCT_VIATECH_VT82C576,
	    0,
	    "VIA Technologies",
	    "VT82C576 3V",
	},
	{
	    PCI_VENDOR_VIATECH, PCI_PRODUCT_VIATECH_VT82C585,
	    0,
	    "VIA Technologies",
	    "VT82C585 (Apollo) PCI-ISA Bridge",
	},
	{
	    PCI_VENDOR_VIATECH, PCI_PRODUCT_VIATECH_VT82C586,
	    0,
	    "VIA Technologies",
	    "VT82C586 (Apollo VP) PCI-ISA Bridge",
	},
	{
	    PCI_VENDOR_VIATECH, PCI_PRODUCT_VIATECH_VT82C595,
	    0,
	    "VIA Technologies",
	    "VT82C595 (Apollo VP2) Host-PCI Bridge",
	},
	{
	    PCI_VENDOR_VIATECH, PCI_PRODUCT_VIATECH_VT82C597PCI,
	    0,
	    "VIA Technologies",
	    "VT82C597 (Apollo VP3) Host-PCI Bridge",
	},
	{
	    PCI_VENDOR_VIATECH, PCI_PRODUCT_VIATECH_VT82C598PCI,
	    0,
	    "VIA Technologies",
	    "VT82C598 (Apollo MVP3) Host-PCI Bridge",
	},
	{
	    PCI_VENDOR_VIATECH, PCI_PRODUCT_VIATECH_VT86C926,
	    0,
	    "VIA Technologies",
	    "VT86C926 Amazon PCI-Ethernet Controller",
	},
	{
	    PCI_VENDOR_VIATECH, PCI_PRODUCT_VIATECH_VT82C570M,
	    0,
	    "VIA Technologies",
	    "VT82C570M (Apollo) Host-PCI Bridge",
	},
	{
	    PCI_VENDOR_VIATECH, PCI_PRODUCT_VIATECH_VT82C570MV,
	    0,
	    "VIA Technologies",
	    "VT82C570M (Apollo) PCI-ISA Bridge",
	},
	{
	    PCI_VENDOR_VIATECH, PCI_PRODUCT_VIATECH_VT82C416MV,
	    0,
	    "VIA Technologies",
	    "VT82C416MV",
	},
	{
	    PCI_VENDOR_VIATECH, PCI_PRODUCT_VIATECH_VT82C1595,
	    0,
	    "VIA Technologies",
	    "VT82C1595 (Apollo VP2) Host-PCI Bridge",
	},
	{
	    PCI_VENDOR_VIATECH, PCI_PRODUCT_VIATECH_VT83C572,
	    0,
	    "VIA Technologies",
	    "VT83C572 USB Controller",
	},
	{
	    PCI_VENDOR_VIATECH, PCI_PRODUCT_VIATECH_VT82C586_PWR,
	    0,
	    "VIA Technologies",
	    "VT82C586 (Apollo VP) Power Management Controller",
	},
	{
	    PCI_VENDOR_VIATECH, PCI_PRODUCT_VIATECH_VT82C597AGP,
	    0,
	    "VIA Technologies",
	    "VT82C597 (Apollo VP3) PCI-AGP Bridge",
	},
	{
	    PCI_VENDOR_VIATECH, PCI_PRODUCT_VIATECH_VT82C598AGP,
	    0,
	    "VIA Technologies",
	    "VT82C598 (Apollo MVP3) PCI-AGP Bridge",
	},
	{
	    PCI_VENDOR_VORTEX, PCI_PRODUCT_VORTEX_GDT_6000B,
	    0,
	    "Vortex Computer Systems",
	    "GDT 6000b",
	},
	{
	    PCI_VENDOR_VLSI, PCI_PRODUCT_VLSI_82C592,
	    0,
	    "VLSI Technology",
	    "82C592 CPU Bridge",
	},
	{
	    PCI_VENDOR_VLSI, PCI_PRODUCT_VLSI_82C593,
	    0,
	    "VLSI Technology",
	    "82C593 ISA Bridge",
	},
	{
	    PCI_VENDOR_VLSI, PCI_PRODUCT_VLSI_82C594,
	    0,
	    "VLSI Technology",
	    "82C594 Wildcat System Controller",
	},
	{
	    PCI_VENDOR_VLSI, PCI_PRODUCT_VLSI_82C596597,
	    0,
	    "VLSI Technology",
	    "82C596/597 Wildcat ISA Bridge",
	},
	{
	    PCI_VENDOR_VLSI, PCI_PRODUCT_VLSI_82C541,
	    0,
	    "VLSI Technology",
	    "82C541",
	},
	{
	    PCI_VENDOR_VLSI, PCI_PRODUCT_VLSI_82C543,
	    0,
	    "VLSI Technology",
	    "82C543",
	},
	{
	    PCI_VENDOR_VLSI, PCI_PRODUCT_VLSI_82C532,
	    0,
	    "VLSI Technology",
	    "82C532",
	},
	{
	    PCI_VENDOR_VLSI, PCI_PRODUCT_VLSI_82C534,
	    0,
	    "VLSI Technology",
	    "82C534",
	},
	{
	    PCI_VENDOR_VLSI, PCI_PRODUCT_VLSI_82C535,
	    0,
	    "VLSI Technology",
	    "82C535",
	},
	{
	    PCI_VENDOR_VLSI, PCI_PRODUCT_VLSI_82C147,
	    0,
	    "VLSI Technology",
	    "82C147",
	},
	{
	    PCI_VENDOR_VLSI, PCI_PRODUCT_VLSI_82C975,
	    0,
	    "VLSI Technology",
	    "82C975",
	},
	{
	    PCI_VENDOR_VLSI, PCI_PRODUCT_VLSI_82C925,
	    0,
	    "VLSI Technology",
	    "82C925",
	},
	{
	    PCI_VENDOR_WEITEK, PCI_PRODUCT_WEITEK_P9000,
	    0,
	    "Weitek",
	    "P9000",
	},
	{
	    PCI_VENDOR_WEITEK, PCI_PRODUCT_WEITEK_P9100,
	    0,
	    "Weitek",
	    "P9100",
	},
	{
	    PCI_VENDOR_WD, PCI_PRODUCT_WD_WD33C193A,
	    0,
	    "Western Digital",
	    "WD33C193A",
	},
	{
	    PCI_VENDOR_WD, PCI_PRODUCT_WD_WD33C196A,
	    0,
	    "Western Digital",
	    "WD33C196A",
	},
	{
	    PCI_VENDOR_WD, PCI_PRODUCT_WD_WD33C197A,
	    0,
	    "Western Digital",
	    "WD33C197A",
	},
	{
	    PCI_VENDOR_WD, PCI_PRODUCT_WD_WD7193,
	    0,
	    "Western Digital",
	    "WD7193",
	},
	{
	    PCI_VENDOR_WD, PCI_PRODUCT_WD_WD7197,
	    0,
	    "Western Digital",
	    "WD7197",
	},
	{
	    PCI_VENDOR_WD, PCI_PRODUCT_WD_WD33C296A,
	    0,
	    "Western Digital",
	    "WD33C296A",
	},
	{
	    PCI_VENDOR_WD, PCI_PRODUCT_WD_WD34C296,
	    0,
	    "Western Digital",
	    "WD34C296",
	},
	{
	    PCI_VENDOR_WD, PCI_PRODUCT_WD_90C,
	    0,
	    "Western Digital",
	    "90C",
	},
	{
	    PCI_VENDOR_WINBOND, PCI_PRODUCT_WINBOND_W83769F,
	    0,
	    "Winbond Electronics",
	    "W83769F",
	},
	{
	    PCI_VENDOR_WINBOND, PCI_PRODUCT_WINBOND_W89C940F,
	    0,
	    "Winbond Electronics",
	    "Linksys EtherPCI II",
	},
	{
	    PCI_VENDOR_WINBOND2, PCI_PRODUCT_WINBOND2_W89C940,
	    0,
	    "Winbond Electronics (2nd ID)",
	    "Linksys EtherPCI",
	},
	{
	    PCI_VENDOR_ZEINET, PCI_PRODUCT_ZEINET_1221,
	    0,
	    "Zeinet",
	    "1221",
	},
	{
	    PCI_VENDOR_ZIATECH, PCI_PRODUCT_ZIATECH_ZT8905,
	    0,
	    "Ziatech",
	    "PCI-ST32 Bridge",
	},
	{
	    PCI_VENDOR_MARTINMARIETTA, 0,
	    PCI_KNOWNDEV_NOPROD,
	    "Martin-Marietta",
	    NULL,
	},
	{
	    PCI_VENDOR_COMPAQ, 0,
	    PCI_KNOWNDEV_NOPROD,
	    "Compaq",
	    NULL,
	},
	{
	    PCI_VENDOR_SYMBIOS, 0,
	    PCI_KNOWNDEV_NOPROD,
	    "Symbios Logic",
	    NULL,
	},
	{
	    PCI_VENDOR_ATI, 0,
	    PCI_KNOWNDEV_NOPROD,
	    "ATI Technologies",
	    NULL,
	},
	{
	    PCI_VENDOR_ULSI, 0,
	    PCI_KNOWNDEV_NOPROD,
	    "ULSI Systems",
	    NULL,
	},
	{
	    PCI_VENDOR_VLSI, 0,
	    PCI_KNOWNDEV_NOPROD,
	    "VLSI Technology",
	    NULL,
	},
	{
	    PCI_VENDOR_AVANCE, 0,
	    PCI_KNOWNDEV_NOPROD,
	    "Avance Logic",
	    NULL,
	},
	{
	    PCI_VENDOR_REPLY, 0,
	    PCI_KNOWNDEV_NOPROD,
	    "Reply Group",
	    NULL,
	},
	{
	    PCI_VENDOR_NETFRAME, 0,
	    PCI_KNOWNDEV_NOPROD,
	    "NetFrame Systems",
	    NULL,
	},
	{
	    PCI_VENDOR_EPSON, 0,
	    PCI_KNOWNDEV_NOPROD,
	    "Epson",
	    NULL,
	},
	{
	    PCI_VENDOR_PHOENIX, 0,
	    PCI_KNOWNDEV_NOPROD,
	    "Phoenix Technologies",
	    NULL,
	},
	{
	    PCI_VENDOR_NS, 0,
	    PCI_KNOWNDEV_NOPROD,
	    "National Semiconductor",
	    NULL,
	},
	{
	    PCI_VENDOR_TSENG, 0,
	    PCI_KNOWNDEV_NOPROD,
	    "Tseng Labs",
	    NULL,
	},
	{
	    PCI_VENDOR_AST, 0,
	    PCI_KNOWNDEV_NOPROD,
	    "AST Research",
	    NULL,
	},
	{
	    PCI_VENDOR_WEITEK, 0,
	    PCI_KNOWNDEV_NOPROD,
	    "Weitek",
	    NULL,
	},
	{
	    PCI_VENDOR_VIDEOLOGIC, 0,
	    PCI_KNOWNDEV_NOPROD,
	    "Video Logic",
	    NULL,
	},
	{
	    PCI_VENDOR_DEC, 0,
	    PCI_KNOWNDEV_NOPROD,
	    "Digital Equipment",
	    NULL,
	},
	{
	    PCI_VENDOR_MICRONICS, 0,
	    PCI_KNOWNDEV_NOPROD,
	    "Micronics Computers",
	    NULL,
	},
	{
	    PCI_VENDOR_CIRRUS, 0,
	    PCI_KNOWNDEV_NOPROD,
	    "Cirrus Logic",
	    NULL,
	},
	{
	    PCI_VENDOR_IBM, 0,
	    PCI_KNOWNDEV_NOPROD,
	    "IBM",
	    NULL,
	},
	{
	    PCI_VENDOR_LSIL, 0,
	    PCI_KNOWNDEV_NOPROD,
	    "LSI Logic Corp of Canada",
	    NULL,
	},
	{
	    PCI_VENDOR_ICLPERSONAL, 0,
	    PCI_KNOWNDEV_NOPROD,
	    "ICL Personal Systems",
	    NULL,
	},
	{
	    PCI_VENDOR_SPEA, 0,
	    PCI_KNOWNDEV_NOPROD,
	    "SPEA Software",
	    NULL,
	},
	{
	    PCI_VENDOR_UNISYS, 0,
	    PCI_KNOWNDEV_NOPROD,
	    "Unisys Systems",
	    NULL,
	},
	{
	    PCI_VENDOR_ELITEGROUP, 0,
	    PCI_KNOWNDEV_NOPROD,
	    "Elitegroup Computer Systems",
	    NULL,
	},
	{
	    PCI_VENDOR_NCR, 0,
	    PCI_KNOWNDEV_NOPROD,
	    "AT&T Global Information Systems",
	    NULL,
	},
	{
	    PCI_VENDOR_VITESSE, 0,
	    PCI_KNOWNDEV_NOPROD,
	    "Vitesse Semiconductor",
	    NULL,
	},
	{
	    PCI_VENDOR_WD, 0,
	    PCI_KNOWNDEV_NOPROD,
	    "Western Digital",
	    NULL,
	},
	{
	    PCI_VENDOR_AMI, 0,
	    PCI_KNOWNDEV_NOPROD,
	    "American Megatrends",
	    NULL,
	},
	{
	    PCI_VENDOR_PICTURETEL, 0,
	    PCI_KNOWNDEV_NOPROD,
	    "PictureTel",
	    NULL,
	},
	{
	    PCI_VENDOR_HITACHICOMP, 0,
	    PCI_KNOWNDEV_NOPROD,
	    "Hitachi Computer Products",
	    NULL,
	},
	{
	    PCI_VENDOR_OKI, 0,
	    PCI_KNOWNDEV_NOPROD,
	    "OKI Electric Industry",
	    NULL,
	},
	{
	    PCI_VENDOR_AMD, 0,
	    PCI_KNOWNDEV_NOPROD,
	    "Advanced Micro Devices",
	    NULL,
	},
	{
	    PCI_VENDOR_TRIDENT, 0,
	    PCI_KNOWNDEV_NOPROD,
	    "Trident Microsystems",
	    NULL,
	},
	{
	    PCI_VENDOR_ZENITH, 0,
	    PCI_KNOWNDEV_NOPROD,
	    "Zenith Data Systems",
	    NULL,
	},
	{
	    PCI_VENDOR_ACER, 0,
	    PCI_KNOWNDEV_NOPROD,
	    "Acer",
	    NULL,
	},
	{
	    PCI_VENDOR_DELL, 0,
	    PCI_KNOWNDEV_NOPROD,
	    "Dell Computer",
	    NULL,
	},
	{
	    PCI_VENDOR_SNI, 0,
	    PCI_KNOWNDEV_NOPROD,
	    "Siemens Nixdorf AG",
	    NULL,
	},
	{
	    PCI_VENDOR_LSILOGIC, 0,
	    PCI_KNOWNDEV_NOPROD,
	    "LSI Logic, Headland div.",
	    NULL,
	},
	{
	    PCI_VENDOR_MATROX, 0,
	    PCI_KNOWNDEV_NOPROD,
	    "Matrox",
	    NULL,
	},
	{
	    PCI_VENDOR_CHIPS, 0,
	    PCI_KNOWNDEV_NOPROD,
	    "Chips and Technologies",
	    NULL,
	},
	{
	    PCI_VENDOR_WYSE, 0,
	    PCI_KNOWNDEV_NOPROD,
	    "WYSE Technology",
	    NULL,
	},
	{
	    PCI_VENDOR_OLIVETTI, 0,
	    PCI_KNOWNDEV_NOPROD,
	    "Olivetti Advanced Technology",
	    NULL,
	},
	{
	    PCI_VENDOR_TOSHIBA, 0,
	    PCI_KNOWNDEV_NOPROD,
	    "Toshiba America",
	    NULL,
	},
	{
	    PCI_VENDOR_TMCRESEARCH, 0,
	    PCI_KNOWNDEV_NOPROD,
	    "TMC Research",
	    NULL,
	},
	{
	    PCI_VENDOR_MIRO, 0,
	    PCI_KNOWNDEV_NOPROD,
	    "Miro Computer Products",
	    NULL,
	},
	{
	    PCI_VENDOR_COMPAQ2, 0,
	    PCI_KNOWNDEV_NOPROD,
	    "Compaq (2nd ID)",
	    NULL,
	},
	{
	    PCI_VENDOR_NEC, 0,
	    PCI_KNOWNDEV_NOPROD,
	    "NEC",
	    NULL,
	},
	{
	    PCI_VENDOR_BURNDY, 0,
	    PCI_KNOWNDEV_NOPROD,
	    "Burndy",
	    NULL,
	},
	{
	    PCI_VENDOR_COMPCOMM, 0,
	    PCI_KNOWNDEV_NOPROD,
	    "Comp. & Comm. Research Lab",
	    NULL,
	},
	{
	    PCI_VENDOR_FUTUREDOMAIN, 0,
	    PCI_KNOWNDEV_NOPROD,
	    "Future Domain",
	    NULL,
	},
	{
	    PCI_VENDOR_HITACHIMICRO, 0,
	    PCI_KNOWNDEV_NOPROD,
	    "Hitach Microsystems",
	    NULL,
	},
	{
	    PCI_VENDOR_AMP, 0,
	    PCI_KNOWNDEV_NOPROD,
	    "AMP",
	    NULL,
	},
	{
	    PCI_VENDOR_SIS, 0,
	    PCI_KNOWNDEV_NOPROD,
	    "Silicon Integrated System",
	    NULL,
	},
	{
	    PCI_VENDOR_SEIKOEPSON, 0,
	    PCI_KNOWNDEV_NOPROD,
	    "Seiko Epson",
	    NULL,
	},
	{
	    PCI_VENDOR_TATUNGAMERICA, 0,
	    PCI_KNOWNDEV_NOPROD,
	    "Tatung Co. of America",
	    NULL,
	},
	{
	    PCI_VENDOR_HP, 0,
	    PCI_KNOWNDEV_NOPROD,
	    "Hewlett-Packard",
	    NULL,
	},
	{
	    PCI_VENDOR_SOLLIDAY, 0,
	    PCI_KNOWNDEV_NOPROD,
	    "Solliday Engineering",
	    NULL,
	},
	{
	    PCI_VENDOR_LOGICMODELLING, 0,
	    PCI_KNOWNDEV_NOPROD,
	    "Logic Modeling",
	    NULL,
	},
	{
	    PCI_VENDOR_KPC, 0,
	    PCI_KNOWNDEV_NOPROD,
	    "Kubota Pacific",
	    NULL,
	},
	{
	    PCI_VENDOR_COMPUTREND, 0,
	    PCI_KNOWNDEV_NOPROD,
	    "Computrend",
	    NULL,
	},
	{
	    PCI_VENDOR_PCTECH, 0,
	    PCI_KNOWNDEV_NOPROD,
	    "PC Technology",
	    NULL,
	},
	{
	    PCI_VENDOR_ASUSTEK, 0,
	    PCI_KNOWNDEV_NOPROD,
	    "Asustek Computer",
	    NULL,
	},
	{
	    PCI_VENDOR_DPT, 0,
	    PCI_KNOWNDEV_NOPROD,
	    "Distributed Processing Technology",
	    NULL,
	},
	{
	    PCI_VENDOR_OPTI, 0,
	    PCI_KNOWNDEV_NOPROD,
	    "Opti",
	    NULL,
	},
	{
	    PCI_VENDOR_IPCCORP, 0,
	    PCI_KNOWNDEV_NOPROD,
	    "IPC Corporation",
	    NULL,
	},
	{
	    PCI_VENDOR_GENOA, 0,
	    PCI_KNOWNDEV_NOPROD,
	    "Genoa Systems",
	    NULL,
	},
	{
	    PCI_VENDOR_ELSA, 0,
	    PCI_KNOWNDEV_NOPROD,
	    "Elsa",
	    NULL,
	},
	{
	    PCI_VENDOR_FOUNTAINTECH, 0,
	    PCI_KNOWNDEV_NOPROD,
	    "Fountain Technology",
	    NULL,
	},
	{
	    PCI_VENDOR_SGSTHOMSON, 0,
	    PCI_KNOWNDEV_NOPROD,
	    "SGS Thomson Microelectric",
	    NULL,
	},
	{
	    PCI_VENDOR_BUSLOGIC, 0,
	    PCI_KNOWNDEV_NOPROD,
	    "BusLogic",
	    NULL,
	},
	{
	    PCI_VENDOR_TI, 0,
	    PCI_KNOWNDEV_NOPROD,
	    "Texas Instruments",
	    NULL,
	},
	{
	    PCI_VENDOR_SONY, 0,
	    PCI_KNOWNDEV_NOPROD,
	    "Sony",
	    NULL,
	},
	{
	    PCI_VENDOR_OAKTECH, 0,
	    PCI_KNOWNDEV_NOPROD,
	    "Oak Technology",
	    NULL,
	},
	{
	    PCI_VENDOR_COTIME, 0,
	    PCI_KNOWNDEV_NOPROD,
	    "Co-time Computer",
	    NULL,
	},
	{
	    PCI_VENDOR_WINBOND, 0,
	    PCI_KNOWNDEV_NOPROD,
	    "Winbond Electronics",
	    NULL,
	},
	{
	    PCI_VENDOR_ANIGMA, 0,
	    PCI_KNOWNDEV_NOPROD,
	    "Anigma",
	    NULL,
	},
	{
	    PCI_VENDOR_YOUNGMICRO, 0,
	    PCI_KNOWNDEV_NOPROD,
	    "Young Micro Systems",
	    NULL,
	},
	{
	    PCI_VENDOR_HITACHI, 0,
	    PCI_KNOWNDEV_NOPROD,
	    "Hitachi",
	    NULL,
	},
	{
	    PCI_VENDOR_EFARMICRO, 0,
	    PCI_KNOWNDEV_NOPROD,
	    "Efar Microsystems",
	    NULL,
	},
	{
	    PCI_VENDOR_ICL, 0,
	    PCI_KNOWNDEV_NOPROD,
	    "ICL",
	    NULL,
	},
	{
	    PCI_VENDOR_MOT, 0,
	    PCI_KNOWNDEV_NOPROD,
	    "Motorola",
	    NULL,
	},
	{
	    PCI_VENDOR_ETR, 0,
	    PCI_KNOWNDEV_NOPROD,
	    "Electronics & Telec. RSH",
	    NULL,
	},
	{
	    PCI_VENDOR_TEKNOR, 0,
	    PCI_KNOWNDEV_NOPROD,
	    "Teknor Microsystems",
	    NULL,
	},
	{
	    PCI_VENDOR_PROMISE, 0,
	    PCI_KNOWNDEV_NOPROD,
	    "Promise Technology",
	    NULL,
	},
	{
	    PCI_VENDOR_FOXCONN, 0,
	    PCI_KNOWNDEV_NOPROD,
	    "Foxconn International",
	    NULL,
	},
	{
	    PCI_VENDOR_WIPRO, 0,
	    PCI_KNOWNDEV_NOPROD,
	    "Wipro Infotech",
	    NULL,
	},
	{
	    PCI_VENDOR_NUMBER9, 0,
	    PCI_KNOWNDEV_NOPROD,
	    "Number 9 Computer Company",
	    NULL,
	},
	{
	    PCI_VENDOR_VTECH, 0,
	    PCI_KNOWNDEV_NOPROD,
	    "Vtech Computers",
	    NULL,
	},
	{
	    PCI_VENDOR_INFOTRONIC, 0,
	    PCI_KNOWNDEV_NOPROD,
	    "Infotronic America",
	    NULL,
	},
	{
	    PCI_VENDOR_UMC, 0,
	    PCI_KNOWNDEV_NOPROD,
	    "United Microelectronics",
	    NULL,
	},
	{
	    PCI_VENDOR_ITT, 0,
	    PCI_KNOWNDEV_NOPROD,
	    "I. T. T.",
	    NULL,
	},
	{
	    PCI_VENDOR_MASPAR, 0,
	    PCI_KNOWNDEV_NOPROD,
	    "MasPar Computer",
	    NULL,
	},
	{
	    PCI_VENDOR_OCEANOA, 0,
	    PCI_KNOWNDEV_NOPROD,
	    "Ocean Office Automation",
	    NULL,
	},
	{
	    PCI_VENDOR_ALCATEL, 0,
	    PCI_KNOWNDEV_NOPROD,
	    "Alcatel CIT",
	    NULL,
	},
	{
	    PCI_VENDOR_TEXASMICRO, 0,
	    PCI_KNOWNDEV_NOPROD,
	    "Texas Microsystems",
	    NULL,
	},
	{
	    PCI_VENDOR_PICOPOWER, 0,
	    PCI_KNOWNDEV_NOPROD,
	    "Picopower Technology",
	    NULL,
	},
	{
	    PCI_VENDOR_MITSUBISHI, 0,
	    PCI_KNOWNDEV_NOPROD,
	    "Mitsubishi Electronics",
	    NULL,
	},
	{
	    PCI_VENDOR_DIVERSIFIED, 0,
	    PCI_KNOWNDEV_NOPROD,
	    "Diversified Technology",
	    NULL,
	},
	{
	    PCI_VENDOR_MYLEX, 0,
	    PCI_KNOWNDEV_NOPROD,
	    "Mylex",
	    NULL,
	},
	{
	    PCI_VENDOR_ATEN, 0,
	    PCI_KNOWNDEV_NOPROD,
	    "Aten Research",
	    NULL,
	},
	{
	    PCI_VENDOR_APPLE, 0,
	    PCI_KNOWNDEV_NOPROD,
	    "Apple Computer",
	    NULL,
	},
	{
	    PCI_VENDOR_HYUNDAI, 0,
	    PCI_KNOWNDEV_NOPROD,
	    "Hyundai Electronics America",
	    NULL,
	},
	{
	    PCI_VENDOR_SEQUENT, 0,
	    PCI_KNOWNDEV_NOPROD,
	    "Sequent",
	    NULL,
	},
	{
	    PCI_VENDOR_DFI, 0,
	    PCI_KNOWNDEV_NOPROD,
	    "DFI",
	    NULL,
	},
	{
	    PCI_VENDOR_CITYGATE, 0,
	    PCI_KNOWNDEV_NOPROD,
	    "City Gate Development",
	    NULL,
	},
	{
	    PCI_VENDOR_DAEWOO, 0,
	    PCI_KNOWNDEV_NOPROD,
	    "Daewoo Telecom",
	    NULL,
	},
	{
	    PCI_VENDOR_MITAC, 0,
	    PCI_KNOWNDEV_NOPROD,
	    "Mitac",
	    NULL,
	},
	{
	    PCI_VENDOR_GIT, 0,
	    PCI_KNOWNDEV_NOPROD,
	    "GIT Co.",
	    NULL,
	},
	{
	    PCI_VENDOR_YAMAHA, 0,
	    PCI_KNOWNDEV_NOPROD,
	    "Yamaha",
	    NULL,
	},
	{
	    PCI_VENDOR_NEXGEN, 0,
	    PCI_KNOWNDEV_NOPROD,
	    "NexGen Microsystems",
	    NULL,
	},
	{
	    PCI_VENDOR_AIR, 0,
	    PCI_KNOWNDEV_NOPROD,
	    "Advanced Integration Research",
	    NULL,
	},
	{
	    PCI_VENDOR_CHAINTECH, 0,
	    PCI_KNOWNDEV_NOPROD,
	    "Chaintech Computer",
	    NULL,
	},
	{
	    PCI_VENDOR_QLOGIC, 0,
	    PCI_KNOWNDEV_NOPROD,
	    "QLogic",
	    NULL,
	},
	{
	    PCI_VENDOR_CYRIX, 0,
	    PCI_KNOWNDEV_NOPROD,
	    "Cyrix",
	    NULL,
	},
	{
	    PCI_VENDOR_IBUS, 0,
	    PCI_KNOWNDEV_NOPROD,
	    "I-Bus",
	    NULL,
	},
	{
	    PCI_VENDOR_NETWORTH, 0,
	    PCI_KNOWNDEV_NOPROD,
	    "NetWorth",
	    NULL,
	},
	{
	    PCI_VENDOR_GATEWAY, 0,
	    PCI_KNOWNDEV_NOPROD,
	    "Gateway 2000",
	    NULL,
	},
	{
	    PCI_VENDOR_GOLDSTART, 0,
	    PCI_KNOWNDEV_NOPROD,
	    "Goldstar",
	    NULL,
	},
	{
	    PCI_VENDOR_LEADTEK, 0,
	    PCI_KNOWNDEV_NOPROD,
	    "LeadTek Research",
	    NULL,
	},
	{
	    PCI_VENDOR_INTERPHASE, 0,
	    PCI_KNOWNDEV_NOPROD,
	    "Interphase",
	    NULL,
	},
	{
	    PCI_VENDOR_DATATECH, 0,
	    PCI_KNOWNDEV_NOPROD,
	    "Data Technology Corporation",
	    NULL,
	},
	{
	    PCI_VENDOR_CONTAQ, 0,
	    PCI_KNOWNDEV_NOPROD,
	    "Contaq Microsystems",
	    NULL,
	},
	{
	    PCI_VENDOR_SUPERMAC, 0,
	    PCI_KNOWNDEV_NOPROD,
	    "Supermac Technology",
	    NULL,
	},
	{
	    PCI_VENDOR_EFA, 0,
	    PCI_KNOWNDEV_NOPROD,
	    "EFA",
	    NULL,
	},
	{
	    PCI_VENDOR_FOREX, 0,
	    PCI_KNOWNDEV_NOPROD,
	    "Forex Computer",
	    NULL,
	},
	{
	    PCI_VENDOR_PARADOR, 0,
	    PCI_KNOWNDEV_NOPROD,
	    "Parador",
	    NULL,
	},
	{
	    PCI_VENDOR_TULIP, 0,
	    PCI_KNOWNDEV_NOPROD,
	    "Tulip Computers",
	    NULL,
	},
	{
	    PCI_VENDOR_JBOND, 0,
	    PCI_KNOWNDEV_NOPROD,
	    "J. Bond Computer Systems",
	    NULL,
	},
	{
	    PCI_VENDOR_CACHECOMP, 0,
	    PCI_KNOWNDEV_NOPROD,
	    "Cache Computer",
	    NULL,
	},
	{
	    PCI_VENDOR_MICROCOMP, 0,
	    PCI_KNOWNDEV_NOPROD,
	    "Microcomputer Systems",
	    NULL,
	},
	{
	    PCI_VENDOR_DG, 0,
	    PCI_KNOWNDEV_NOPROD,
	    "Data General",
	    NULL,
	},
	{
	    PCI_VENDOR_BIT3, 0,
	    PCI_KNOWNDEV_NOPROD,
	    "Bit3 Computer Corp.",
	    NULL,
	},
	{
	    PCI_VENDOR_ELONEX, 0,
	    PCI_KNOWNDEV_NOPROD,
	    "Elonex PLC c/o Oakleigh Systems",
	    NULL,
	},
	{
	    PCI_VENDOR_OLICOM, 0,
	    PCI_KNOWNDEV_NOPROD,
	    "Olicom",
	    NULL,
	},
	{
	    PCI_VENDOR_SUN, 0,
	    PCI_KNOWNDEV_NOPROD,
	    "Sun Microsystems",
	    NULL,
	},
	{
	    PCI_VENDOR_SYSTEMSOFT, 0,
	    PCI_KNOWNDEV_NOPROD,
	    "Systemsoft",
	    NULL,
	},
	{
	    PCI_VENDOR_ENCORE, 0,
	    PCI_KNOWNDEV_NOPROD,
	    "Encore Computer",
	    NULL,
	},
	{
	    PCI_VENDOR_INTERGRAPH, 0,
	    PCI_KNOWNDEV_NOPROD,
	    "Intergraph",
	    NULL,
	},
	{
	    PCI_VENDOR_DIAMOND, 0,
	    PCI_KNOWNDEV_NOPROD,
	    "Diamond Computer Systems",
	    NULL,
	},
	{
	    PCI_VENDOR_NATIONALINST, 0,
	    PCI_KNOWNDEV_NOPROD,
	    "National Instruments",
	    NULL,
	},
	{
	    PCI_VENDOR_FICOMP, 0,
	    PCI_KNOWNDEV_NOPROD,
	    "First Int'l Computers",
	    NULL,
	},
	{
	    PCI_VENDOR_CMDTECH, 0,
	    PCI_KNOWNDEV_NOPROD,
	    "CMD Technology",
	    NULL,
	},
	{
	    PCI_VENDOR_ALACRON, 0,
	    PCI_KNOWNDEV_NOPROD,
	    "Alacron",
	    NULL,
	},
	{
	    PCI_VENDOR_APPIAN, 0,
	    PCI_KNOWNDEV_NOPROD,
	    "Appian Technology",
	    NULL,
	},
	{
	    PCI_VENDOR_QUANTUMDESIGNS, 0,
	    PCI_KNOWNDEV_NOPROD,
	    "Quantum Designs",
	    NULL,
	},
	{
	    PCI_VENDOR_SAMSUNGELEC, 0,
	    PCI_KNOWNDEV_NOPROD,
	    "Samsung Electronics",
	    NULL,
	},
	{
	    PCI_VENDOR_PACKARDBELL, 0,
	    PCI_KNOWNDEV_NOPROD,
	    "Packard Bell",
	    NULL,
	},
	{
	    PCI_VENDOR_GEMLIGHT, 0,
	    PCI_KNOWNDEV_NOPROD,
	    "Gemlight Computer",
	    NULL,
	},
	{
	    PCI_VENDOR_MEGACHIPS, 0,
	    PCI_KNOWNDEV_NOPROD,
	    "Megachips",
	    NULL,
	},
	{
	    PCI_VENDOR_ZIDA, 0,
	    PCI_KNOWNDEV_NOPROD,
	    "Zida Technologies",
	    NULL,
	},
	{
	    PCI_VENDOR_BROOKTREE, 0,
	    PCI_KNOWNDEV_NOPROD,
	    "Brooktree",
	    NULL,
	},
	{
	    PCI_VENDOR_TRIGEM, 0,
	    PCI_KNOWNDEV_NOPROD,
	    "Trigem Computer",
	    NULL,
	},
	{
	    PCI_VENDOR_MEIDENSHA, 0,
	    PCI_KNOWNDEV_NOPROD,
	    "Meidensha",
	    NULL,
	},
	{
	    PCI_VENDOR_JUKO, 0,
	    PCI_KNOWNDEV_NOPROD,
	    "Juko Electronics",
	    NULL,
	},
	{
	    PCI_VENDOR_QUANTUM, 0,
	    PCI_KNOWNDEV_NOPROD,
	    "Quantum",
	    NULL,
	},
	{
	    PCI_VENDOR_EVEREX, 0,
	    PCI_KNOWNDEV_NOPROD,
	    "Everex Systems",
	    NULL,
	},
	{
	    PCI_VENDOR_GLOBE, 0,
	    PCI_KNOWNDEV_NOPROD,
	    "Globe Manufacturing Sales",
	    NULL,
	},
	{
	    PCI_VENDOR_RACAL, 0,
	    PCI_KNOWNDEV_NOPROD,
	    "Racal Interlan",
	    NULL,
	},
	{
	    PCI_VENDOR_INFORMTECH, 0,
	    PCI_KNOWNDEV_NOPROD,
	    "Informtech Industrial",
	    NULL,
	},
	{
	    PCI_VENDOR_BENCHMARQ, 0,
	    PCI_KNOWNDEV_NOPROD,
	    "Benchmarq Microelectronics",
	    NULL,
	},
	{
	    PCI_VENDOR_SIERRA, 0,
	    PCI_KNOWNDEV_NOPROD,
	    "Sierra Semiconductor",
	    NULL,
	},
	{
	    PCI_VENDOR_SGI, 0,
	    PCI_KNOWNDEV_NOPROD,
	    "Silicon Graphics",
	    NULL,
	},
	{
	    PCI_VENDOR_ACC, 0,
	    PCI_KNOWNDEV_NOPROD,
	    "ACC Microelectronics",
	    NULL,
	},
	{
	    PCI_VENDOR_DIGICOM, 0,
	    PCI_KNOWNDEV_NOPROD,
	    "Digicom",
	    NULL,
	},
	{
	    PCI_VENDOR_HONEYWELL, 0,
	    PCI_KNOWNDEV_NOPROD,
	    "Honeywell IASD",
	    NULL,
	},
	{
	    PCI_VENDOR_SYMPHONY, 0,
	    PCI_KNOWNDEV_NOPROD,
	    "Symphony Labs",
	    NULL,
	},
	{
	    PCI_VENDOR_CORNERSTONE, 0,
	    PCI_KNOWNDEV_NOPROD,
	    "Cornerstone Technology",
	    NULL,
	},
	{
	    PCI_VENDOR_MICROCOMPSON, 0,
	    PCI_KNOWNDEV_NOPROD,
	    "Micro Computer Sysytems (M) SON",
	    NULL,
	},
	{
	    PCI_VENDOR_CARDEXPER, 0,
	    PCI_KNOWNDEV_NOPROD,
	    "CardExpert Technology",
	    NULL,
	},
	{
	    PCI_VENDOR_CABLETRON, 0,
	    PCI_KNOWNDEV_NOPROD,
	    "Cabletron Systems",
	    NULL,
	},
	{
	    PCI_VENDOR_RAYETHON, 0,
	    PCI_KNOWNDEV_NOPROD,
	    "Raytheon",
	    NULL,
	},
	{
	    PCI_VENDOR_DATABOOK, 0,
	    PCI_KNOWNDEV_NOPROD,
	    "Databook",
	    NULL,
	},
	{
	    PCI_VENDOR_STB, 0,
	    PCI_KNOWNDEV_NOPROD,
	    "STB Systems",
	    NULL,
	},
	{
	    PCI_VENDOR_PLX, 0,
	    PCI_KNOWNDEV_NOPROD,
	    "PLX Technology",
	    NULL,
	},
	{
	    PCI_VENDOR_MADGE, 0,
	    PCI_KNOWNDEV_NOPROD,
	    "Madge Networks",
	    NULL,
	},
	{
	    PCI_VENDOR_3COM, 0,
	    PCI_KNOWNDEV_NOPROD,
	    "3Com",
	    NULL,
	},
	{
	    PCI_VENDOR_SMC, 0,
	    PCI_KNOWNDEV_NOPROD,
	    "Standard Microsystems",
	    NULL,
	},
	{
	    PCI_VENDOR_ALI, 0,
	    PCI_KNOWNDEV_NOPROD,
	    "Acer Labs",
	    NULL,
	},
	{
	    PCI_VENDOR_MITSUBISHIELEC, 0,
	    PCI_KNOWNDEV_NOPROD,
	    "Mitsubishi Electronics",
	    NULL,
	},
	{
	    PCI_VENDOR_DAPHA, 0,
	    PCI_KNOWNDEV_NOPROD,
	    "Dapha Electronics",
	    NULL,
	},
	{
	    PCI_VENDOR_ALR, 0,
	    PCI_KNOWNDEV_NOPROD,
	    "Advanced Logic Research",
	    NULL,
	},
	{
	    PCI_VENDOR_SURECOM, 0,
	    PCI_KNOWNDEV_NOPROD,
	    "Surecom Technology",
	    NULL,
	},
	{
	    PCI_VENDOR_TSENGLABS, 0,
	    PCI_KNOWNDEV_NOPROD,
	    "Tseng Labs International",
	    NULL,
	},
	{
	    PCI_VENDOR_MOST, 0,
	    PCI_KNOWNDEV_NOPROD,
	    "Most",
	    NULL,
	},
	{
	    PCI_VENDOR_BOCA, 0,
	    PCI_KNOWNDEV_NOPROD,
	    "Boca Research",
	    NULL,
	},
	{
	    PCI_VENDOR_ICM, 0,
	    PCI_KNOWNDEV_NOPROD,
	    "ICM",
	    NULL,
	},
	{
	    PCI_VENDOR_AUSPEX, 0,
	    PCI_KNOWNDEV_NOPROD,
	    "Auspex Systems",
	    NULL,
	},
	{
	    PCI_VENDOR_SAMSUNGSEMI, 0,
	    PCI_KNOWNDEV_NOPROD,
	    "Samsung Semiconductors",
	    NULL,
	},
	{
	    PCI_VENDOR_AWARD, 0,
	    PCI_KNOWNDEV_NOPROD,
	    "Award Software Int'l",
	    NULL,
	},
	{
	    PCI_VENDOR_XEROX, 0,
	    PCI_KNOWNDEV_NOPROD,
	    "Xerox",
	    NULL,
	},
	{
	    PCI_VENDOR_RAMBUS, 0,
	    PCI_KNOWNDEV_NOPROD,
	    "Rambus",
	    NULL,
	},
	{
	    PCI_VENDOR_MEDIAVIS, 0,
	    PCI_KNOWNDEV_NOPROD,
	    "Media Vision",
	    NULL,
	},
	{
	    PCI_VENDOR_NEOMAGIC, 0,
	    PCI_KNOWNDEV_NOPROD,
	    "Neomagic",
	    NULL,
	},
	{
	    PCI_VENDOR_DATAEXPERT, 0,
	    PCI_KNOWNDEV_NOPROD,
	    "Dataexpert",
	    NULL,
	},
	{
	    PCI_VENDOR_FUJITSU, 0,
	    PCI_KNOWNDEV_NOPROD,
	    "Fujitsu",
	    NULL,
	},
	{
	    PCI_VENDOR_OMRON, 0,
	    PCI_KNOWNDEV_NOPROD,
	    "Omron",
	    NULL,
	},
	{
	    PCI_VENDOR_MENTOR, 0,
	    PCI_KNOWNDEV_NOPROD,
	    "Mentor ARC",
	    NULL,
	},
	{
	    PCI_VENDOR_ADVSYSPROD, 0,
	    PCI_KNOWNDEV_NOPROD,
	    "Advanced System Products",
	    NULL,
	},
	{
	    PCI_VENDOR_RADIUS, 0,
	    PCI_KNOWNDEV_NOPROD,
	    "Radius",
	    NULL,
	},
	{
	    PCI_VENDOR_CITICORP, 0,
	    PCI_KNOWNDEV_NOPROD,
	    "Citicorp TTI",
	    NULL,
	},
	{
	    PCI_VENDOR_FUJITSU2, 0,
	    PCI_KNOWNDEV_NOPROD,
	    "Fujitsu Limited (2nd ID)",
	    NULL,
	},
	{
	    PCI_VENDOR_FUTUREPLUS, 0,
	    PCI_KNOWNDEV_NOPROD,
	    "Future+ Systems",
	    NULL,
	},
	{
	    PCI_VENDOR_MOLEX, 0,
	    PCI_KNOWNDEV_NOPROD,
	    "Molex",
	    NULL,
	},
	{
	    PCI_VENDOR_JABIL, 0,
	    PCI_KNOWNDEV_NOPROD,
	    "Jabil Circuit",
	    NULL,
	},
	{
	    PCI_VENDOR_HAULON, 0,
	    PCI_KNOWNDEV_NOPROD,
	    "Hualon Microelectronics",
	    NULL,
	},
	{
	    PCI_VENDOR_AUTOLOGIC, 0,
	    PCI_KNOWNDEV_NOPROD,
	    "Autologic",
	    NULL,
	},
	{
	    PCI_VENDOR_CETIA, 0,
	    PCI_KNOWNDEV_NOPROD,
	    "Cetia",
	    NULL,
	},
	{
	    PCI_VENDOR_BCM, 0,
	    PCI_KNOWNDEV_NOPROD,
	    "BCM Advanced",
	    NULL,
	},
	{
	    PCI_VENDOR_APL, 0,
	    PCI_KNOWNDEV_NOPROD,
	    "Advanced Peripherals Labs",
	    NULL,
	},
	{
	    PCI_VENDOR_MACRONIX, 0,
	    PCI_KNOWNDEV_NOPROD,
	    "Macronix",
	    NULL,
	},
	{
	    PCI_VENDOR_THOMASCONRAD, 0,
	    PCI_KNOWNDEV_NOPROD,
	    "Thomas-Conrad",
	    NULL,
	},
	{
	    PCI_VENDOR_ROHM, 0,
	    PCI_KNOWNDEV_NOPROD,
	    "Rohm Research",
	    NULL,
	},
	{
	    PCI_VENDOR_CERN, 0,
	    PCI_KNOWNDEV_NOPROD,
	    "CERN/ECP/EDU",
	    NULL,
	},
	{
	    PCI_VENDOR_ES, 0,
	    PCI_KNOWNDEV_NOPROD,
	    "Evans & Sutherland",
	    NULL,
	},
	{
	    PCI_VENDOR_NVIDIA, 0,
	    PCI_KNOWNDEV_NOPROD,
	    "Nvidia",
	    NULL,
	},
	{
	    PCI_VENDOR_EMULEX, 0,
	    PCI_KNOWNDEV_NOPROD,
	    "Emulex",
	    NULL,
	},
	{
	    PCI_VENDOR_IMS, 0,
	    PCI_KNOWNDEV_NOPROD,
	    "Integrated Micro Solutions",
	    NULL,
	},
	{
	    PCI_VENDOR_TEKRAM, 0,
	    PCI_KNOWNDEV_NOPROD,
	    "Tekram Technology (1st ID)",
	    NULL,
	},
	{
	    PCI_VENDOR_APTIX, 0,
	    PCI_KNOWNDEV_NOPROD,
	    "Aptix",
	    NULL,
	},
	{
	    PCI_VENDOR_NEWBRIDGE, 0,
	    PCI_KNOWNDEV_NOPROD,
	    "Newbridge Microsystems",
	    NULL,
	},
	{
	    PCI_VENDOR_TANDEM, 0,
	    PCI_KNOWNDEV_NOPROD,
	    "Tandem Computers",
	    NULL,
	},
	{
	    PCI_VENDOR_MICROINDUSTRIES, 0,
	    PCI_KNOWNDEV_NOPROD,
	    "Micro Industries",
	    NULL,
	},
	{
	    PCI_VENDOR_GAINBERY, 0,
	    PCI_KNOWNDEV_NOPROD,
	    "Gainbery Computer Products",
	    NULL,
	},
	{
	    PCI_VENDOR_VADEM, 0,
	    PCI_KNOWNDEV_NOPROD,
	    "Vadem",
	    NULL,
	},
	{
	    PCI_VENDOR_AMCIRCUITS, 0,
	    PCI_KNOWNDEV_NOPROD,
	    "Applied Micro Circuits",
	    NULL,
	},
	{
	    PCI_VENDOR_ALPSELECTIC, 0,
	    PCI_KNOWNDEV_NOPROD,
	    "Alps Electric",
	    NULL,
	},
	{
	    PCI_VENDOR_INTERGRAPHICS, 0,
	    PCI_KNOWNDEV_NOPROD,
	    "Integraphics Systems",
	    NULL,
	},
	{
	    PCI_VENDOR_ARTISTSGRAPHICS, 0,
	    PCI_KNOWNDEV_NOPROD,
	    "Artists Graphics",
	    NULL,
	},
	{
	    PCI_VENDOR_REALTEK, 0,
	    PCI_KNOWNDEV_NOPROD,
	    "Realtek Semiconductor",
	    NULL,
	},
	{
	    PCI_VENDOR_ASCIICORP, 0,
	    PCI_KNOWNDEV_NOPROD,
	    "ASCII Corporation",
	    NULL,
	},
	{
	    PCI_VENDOR_XILINX, 0,
	    PCI_KNOWNDEV_NOPROD,
	    "Xilinx",
	    NULL,
	},
	{
	    PCI_VENDOR_RACORE, 0,
	    PCI_KNOWNDEV_NOPROD,
	    "Racore Computer Products",
	    NULL,
	},
	{
	    PCI_VENDOR_PERITEK, 0,
	    PCI_KNOWNDEV_NOPROD,
	    "Peritek",
	    NULL,
	},
	{
	    PCI_VENDOR_TYAN, 0,
	    PCI_KNOWNDEV_NOPROD,
	    "Tyan Computer",
	    NULL,
	},
	{
	    PCI_VENDOR_ACHME, 0,
	    PCI_KNOWNDEV_NOPROD,
	    "Achme Computer",
	    NULL,
	},
	{
	    PCI_VENDOR_ALARIS, 0,
	    PCI_KNOWNDEV_NOPROD,
	    "Alaris",
	    NULL,
	},
	{
	    PCI_VENDOR_SMOS, 0,
	    PCI_KNOWNDEV_NOPROD,
	    "S-MOS Systems",
	    NULL,
	},
	{
	    PCI_VENDOR_NKK, 0,
	    PCI_KNOWNDEV_NOPROD,
	    "NKK",
	    NULL,
	},
	{
	    PCI_VENDOR_CREATIVE, 0,
	    PCI_KNOWNDEV_NOPROD,
	    "Creative Electronic Systems",
	    NULL,
	},
	{
	    PCI_VENDOR_MATSUSHITA, 0,
	    PCI_KNOWNDEV_NOPROD,
	    "Matsushita",
	    NULL,
	},
	{
	    PCI_VENDOR_ALTOS, 0,
	    PCI_KNOWNDEV_NOPROD,
	    "Altos India",
	    NULL,
	},
	{
	    PCI_VENDOR_PCDIRECT, 0,
	    PCI_KNOWNDEV_NOPROD,
	    "PC Direct",
	    NULL,
	},
	{
	    PCI_VENDOR_TRUEVISIO, 0,
	    PCI_KNOWNDEV_NOPROD,
	    "Truevision",
	    NULL,
	},
	{
	    PCI_VENDOR_THESYS, 0,
	    PCI_KNOWNDEV_NOPROD,
	    "Thesys Ges. F. Mikroelektronik",
	    NULL,
	},
	{
	    PCI_VENDOR_IODATA, 0,
	    PCI_KNOWNDEV_NOPROD,
	    "I-O Data Device",
	    NULL,
	},
	{
	    PCI_VENDOR_SOYO, 0,
	    PCI_KNOWNDEV_NOPROD,
	    "Soyo Technology",
	    NULL,
	},
	{
	    PCI_VENDOR_FAST, 0,
	    PCI_KNOWNDEV_NOPROD,
	    "Fast Electronic",
	    NULL,
	},
	{
	    PCI_VENDOR_NCUBE, 0,
	    PCI_KNOWNDEV_NOPROD,
	    "NCube",
	    NULL,
	},
	{
	    PCI_VENDOR_JAZZ, 0,
	    PCI_KNOWNDEV_NOPROD,
	    "Jazz Multimedia",
	    NULL,
	},
	{
	    PCI_VENDOR_INITIO, 0,
	    PCI_KNOWNDEV_NOPROD,
	    "Initio",
	    NULL,
	},
	{
	    PCI_VENDOR_CREATIVELABS, 0,
	    PCI_KNOWNDEV_NOPROD,
	    "Creative Labs",
	    NULL,
	},
	{
	    PCI_VENDOR_TRIONES, 0,
	    PCI_KNOWNDEV_NOPROD,
	    "Triones Technologies",
	    NULL,
	},
	{
	    PCI_VENDOR_RASTEROPS, 0,
	    PCI_KNOWNDEV_NOPROD,
	    "RasterOps",
	    NULL,
	},
	{
	    PCI_VENDOR_SIGMA, 0,
	    PCI_KNOWNDEV_NOPROD,
	    "Sigma Designs",
	    NULL,
	},
	{
	    PCI_VENDOR_VIATECH, 0,
	    PCI_KNOWNDEV_NOPROD,
	    "VIA Technologies",
	    NULL,
	},
	{
	    PCI_VENDOR_STRATIS, 0,
	    PCI_KNOWNDEV_NOPROD,
	    "Stratus Computer",
	    NULL,
	},
	{
	    PCI_VENDOR_PROTEON, 0,
	    PCI_KNOWNDEV_NOPROD,
	    "Proteon",
	    NULL,
	},
	{
	    PCI_VENDOR_COGENT, 0,
	    PCI_KNOWNDEV_NOPROD,
	    "Cogent Data Technologies",
	    NULL,
	},
	{
	    PCI_VENDOR_SIEMENS, 0,
	    PCI_KNOWNDEV_NOPROD,
	    "Siemens AG / Siemens Nixdorf AG",
	    NULL,
	},
	{
	    PCI_VENDOR_XENON, 0,
	    PCI_KNOWNDEV_NOPROD,
	    "Xenon Microsystems",
	    NULL,
	},
	{
	    PCI_VENDOR_MINIMAX, 0,
	    PCI_KNOWNDEV_NOPROD,
	    "Mini-Max Technology",
	    NULL,
	},
	{
	    PCI_VENDOR_ZNYX, 0,
	    PCI_KNOWNDEV_NOPROD,
	    "Znyx Advanced Systems",
	    NULL,
	},
	{
	    PCI_VENDOR_CPUTECH, 0,
	    PCI_KNOWNDEV_NOPROD,
	    "CPU Technology",
	    NULL,
	},
	{
	    PCI_VENDOR_ROSS, 0,
	    PCI_KNOWNDEV_NOPROD,
	    "Ross Technology",
	    NULL,
	},
	{
	    PCI_VENDOR_POWERHOUSE, 0,
	    PCI_KNOWNDEV_NOPROD,
	    "Powerhouse Systems",
	    NULL,
	},
	{
	    PCI_VENDOR_SCO, 0,
	    PCI_KNOWNDEV_NOPROD,
	    "Santa Cruz Operation",
	    NULL,
	},
	{
	    PCI_VENDOR_RNS, 0,
	    PCI_KNOWNDEV_NOPROD,
	    "RNS",
	    NULL,
	},
	{
	    PCI_VENDOR_ACCTON, 0,
	    PCI_KNOWNDEV_NOPROD,
	    "Accton Technology",
	    NULL,
	},
	{
	    PCI_VENDOR_ATMEL, 0,
	    PCI_KNOWNDEV_NOPROD,
	    "Atmel",
	    NULL,
	},
	{
	    PCI_VENDOR_DUPONT, 0,
	    PCI_KNOWNDEV_NOPROD,
	    "DuPont Pixel Systems",
	    NULL,
	},
	{
	    PCI_VENDOR_DATATRANSLATION, 0,
	    PCI_KNOWNDEV_NOPROD,
	    "Data Translation",
	    NULL,
	},
	{
	    PCI_VENDOR_DATACUBE, 0,
	    PCI_KNOWNDEV_NOPROD,
	    "Datacube",
	    NULL,
	},
	{
	    PCI_VENDOR_BERG, 0,
	    PCI_KNOWNDEV_NOPROD,
	    "Berg Electronics",
	    NULL,
	},
	{
	    PCI_VENDOR_VORTEX, 0,
	    PCI_KNOWNDEV_NOPROD,
	    "Vortex Computer Systems",
	    NULL,
	},
	{
	    PCI_VENDOR_EFFICIENTNETS, 0,
	    PCI_KNOWNDEV_NOPROD,
	    "Efficent Networks",
	    NULL,
	},
	{
	    PCI_VENDOR_TELEDYNE, 0,
	    PCI_KNOWNDEV_NOPROD,
	    "Teledyne Electronic Systems",
	    NULL,
	},
	{
	    PCI_VENDOR_TRICORD, 0,
	    PCI_KNOWNDEV_NOPROD,
	    "Tricord Systems",
	    NULL,
	},
	{
	    PCI_VENDOR_IDT, 0,
	    PCI_KNOWNDEV_NOPROD,
	    "IDT",
	    NULL,
	},
	{
	    PCI_VENDOR_ELDEC, 0,
	    PCI_KNOWNDEV_NOPROD,
	    "Eldec",
	    NULL,
	},
	{
	    PCI_VENDOR_PDI, 0,
	    PCI_KNOWNDEV_NOPROD,
	    "Prescision Digital Images",
	    NULL,
	},
	{
	    PCI_VENDOR_EMC, 0,
	    PCI_KNOWNDEV_NOPROD,
	    "Emc",
	    NULL,
	},
	{
	    PCI_VENDOR_ZILOG, 0,
	    PCI_KNOWNDEV_NOPROD,
	    "Zilog",
	    NULL,
	},
	{
	    PCI_VENDOR_MULTITECH, 0,
	    PCI_KNOWNDEV_NOPROD,
	    "Multi-tech Systems",
	    NULL,
	},
	{
	    PCI_VENDOR_LEUTRON, 0,
	    PCI_KNOWNDEV_NOPROD,
	    "Leutron Vision",
	    NULL,
	},
	{
	    PCI_VENDOR_EUROCORE, 0,
	    PCI_KNOWNDEV_NOPROD,
	    "Eurocore/Vigra",
	    NULL,
	},
	{
	    PCI_VENDOR_VIGRA, 0,
	    PCI_KNOWNDEV_NOPROD,
	    "Vigra",
	    NULL,
	},
	{
	    PCI_VENDOR_FORE, 0,
	    PCI_KNOWNDEV_NOPROD,
	    "FORE Systems",
	    NULL,
	},
	{
	    PCI_VENDOR_FIRMWORKS, 0,
	    PCI_KNOWNDEV_NOPROD,
	    "Firmworks",
	    NULL,
	},
	{
	    PCI_VENDOR_HERMES, 0,
	    PCI_KNOWNDEV_NOPROD,
	    "Hermes Electronics",
	    NULL,
	},
	{
	    PCI_VENDOR_LINOTYPE, 0,
	    PCI_KNOWNDEV_NOPROD,
	    "Linotype",
	    NULL,
	},
	{
	    PCI_VENDOR_RAVICAD, 0,
	    PCI_KNOWNDEV_NOPROD,
	    "Ravicad",
	    NULL,
	},
	{
	    PCI_VENDOR_INFOMEDIA, 0,
	    PCI_KNOWNDEV_NOPROD,
	    "Infomedia Microelectronics",
	    NULL,
	},
	{
	    PCI_VENDOR_IMAGINGTECH, 0,
	    PCI_KNOWNDEV_NOPROD,
	    "Imaging Technlogy",
	    NULL,
	},
	{
	    PCI_VENDOR_COMPUTERVISION, 0,
	    PCI_KNOWNDEV_NOPROD,
	    "Computervision",
	    NULL,
	},
	{
	    PCI_VENDOR_PHILIPS, 0,
	    PCI_KNOWNDEV_NOPROD,
	    "Philips",
	    NULL,
	},
	{
	    PCI_VENDOR_MITEL, 0,
	    PCI_KNOWNDEV_NOPROD,
	    "Mitel",
	    NULL,
	},
	{
	    PCI_VENDOR_EICON, 0,
	    PCI_KNOWNDEV_NOPROD,
	    "Eicon Technology",
	    NULL,
	},
	{
	    PCI_VENDOR_MCS, 0,
	    PCI_KNOWNDEV_NOPROD,
	    "Mercury Computer Systems",
	    NULL,
	},
	{
	    PCI_VENDOR_FUJIXEROX, 0,
	    PCI_KNOWNDEV_NOPROD,
	    "Fuji Xerox",
	    NULL,
	},
	{
	    PCI_VENDOR_MOMENTUM, 0,
	    PCI_KNOWNDEV_NOPROD,
	    "Momentum Data Systems",
	    NULL,
	},
	{
	    PCI_VENDOR_CISCO, 0,
	    PCI_KNOWNDEV_NOPROD,
	    "Cisco Systems",
	    NULL,
	},
	{
	    PCI_VENDOR_ZIATECH, 0,
	    PCI_KNOWNDEV_NOPROD,
	    "Ziatech",
	    NULL,
	},
	{
	    PCI_VENDOR_DYNPIC, 0,
	    PCI_KNOWNDEV_NOPROD,
	    "Dynamic Pictures",
	    NULL,
	},
	{
	    PCI_VENDOR_FWB, 0,
	    PCI_KNOWNDEV_NOPROD,
	    "FWB",
	    NULL,
	},
	{
	    PCI_VENDOR_CYCLONE, 0,
	    PCI_KNOWNDEV_NOPROD,
	    "Cyclone Micro",
	    NULL,
	},
	{
	    PCI_VENDOR_LEADINGEDGE, 0,
	    PCI_KNOWNDEV_NOPROD,
	    "Leading Edge",
	    NULL,
	},
	{
	    PCI_VENDOR_SANYO, 0,
	    PCI_KNOWNDEV_NOPROD,
	    "Sanyo Electric",
	    NULL,
	},
	{
	    PCI_VENDOR_EQUINOX, 0,
	    PCI_KNOWNDEV_NOPROD,
	    "Equinox Systems",
	    NULL,
	},
	{
	    PCI_VENDOR_INTERVOICE, 0,
	    PCI_KNOWNDEV_NOPROD,
	    "Intervoice",
	    NULL,
	},
	{
	    PCI_VENDOR_CREST, 0,
	    PCI_KNOWNDEV_NOPROD,
	    "Crest Microsystem",
	    NULL,
	},
	{
	    PCI_VENDOR_ALLIANCE, 0,
	    PCI_KNOWNDEV_NOPROD,
	    "Alliance Semiconductor",
	    NULL,
	},
	{
	    PCI_VENDOR_NETPOWER, 0,
	    PCI_KNOWNDEV_NOPROD,
	    "NetPower",
	    NULL,
	},
	{
	    PCI_VENDOR_CINMILACRON, 0,
	    PCI_KNOWNDEV_NOPROD,
	    "Cincinnati Milacron",
	    NULL,
	},
	{
	    PCI_VENDOR_WORKBIT, 0,
	    PCI_KNOWNDEV_NOPROD,
	    "Workbit",
	    NULL,
	},
	{
	    PCI_VENDOR_FORCE, 0,
	    PCI_KNOWNDEV_NOPROD,
	    "Force Computers",
	    NULL,
	},
	{
	    PCI_VENDOR_INTERFACE, 0,
	    PCI_KNOWNDEV_NOPROD,
	    "Interface",
	    NULL,
	},
	{
	    PCI_VENDOR_SCHNEIDERKOCH, 0,
	    PCI_KNOWNDEV_NOPROD,
	    "Schneider & Koch",
	    NULL,
	},
	{
	    PCI_VENDOR_WINSYSTEM, 0,
	    PCI_KNOWNDEV_NOPROD,
	    "Win System",
	    NULL,
	},
	{
	    PCI_VENDOR_VMIC, 0,
	    PCI_KNOWNDEV_NOPROD,
	    "VMIC",
	    NULL,
	},
	{
	    PCI_VENDOR_CANOPUS, 0,
	    PCI_KNOWNDEV_NOPROD,
	    "Canopus",
	    NULL,
	},
	{
	    PCI_VENDOR_ANNABOOKS, 0,
	    PCI_KNOWNDEV_NOPROD,
	    "Annabooks",
	    NULL,
	},
	{
	    PCI_VENDOR_IC, 0,
	    PCI_KNOWNDEV_NOPROD,
	    "IC Corporation",
	    NULL,
	},
	{
	    PCI_VENDOR_NIKON, 0,
	    PCI_KNOWNDEV_NOPROD,
	    "Nikon Systems",
	    NULL,
	},
	{
	    PCI_VENDOR_DIGIINTERNAT, 0,
	    PCI_KNOWNDEV_NOPROD,
	    "Digi International",
	    NULL,
	},
	{
	    PCI_VENDOR_TMC, 0,
	    PCI_KNOWNDEV_NOPROD,
	    "Thinking Machines",
	    NULL,
	},
	{
	    PCI_VENDOR_JAE, 0,
	    PCI_KNOWNDEV_NOPROD,
	    "JAE Electronics",
	    NULL,
	},
	{
	    PCI_VENDOR_MEGATEK, 0,
	    PCI_KNOWNDEV_NOPROD,
	    "Megatek",
	    NULL,
	},
	{
	    PCI_VENDOR_LANDWIN, 0,
	    PCI_KNOWNDEV_NOPROD,
	    "Land Win Electronic",
	    NULL,
	},
	{
	    PCI_VENDOR_MELCO, 0,
	    PCI_KNOWNDEV_NOPROD,
	    "Melco",
	    NULL,
	},
	{
	    PCI_VENDOR_PINETECH, 0,
	    PCI_KNOWNDEV_NOPROD,
	    "Pine Technology",
	    NULL,
	},
	{
	    PCI_VENDOR_PERISCOPE, 0,
	    PCI_KNOWNDEV_NOPROD,
	    "Periscope Engineering",
	    NULL,
	},
	{
	    PCI_VENDOR_AVSYS, 0,
	    PCI_KNOWNDEV_NOPROD,
	    "Avsys",
	    NULL,
	},
	{
	    PCI_VENDOR_VOARX, 0,
	    PCI_KNOWNDEV_NOPROD,
	    "Voarx R & D",
	    NULL,
	},
	{
	    PCI_VENDOR_MUTECH, 0,
	    PCI_KNOWNDEV_NOPROD,
	    "Mutech",
	    NULL,
	},
	{
	    PCI_VENDOR_HARLEQUIN, 0,
	    PCI_KNOWNDEV_NOPROD,
	    "Harlequin",
	    NULL,
	},
	{
	    PCI_VENDOR_PARALLAX, 0,
	    PCI_KNOWNDEV_NOPROD,
	    "Parallax Graphics",
	    NULL,
	},
	{
	    PCI_VENDOR_XIRCOM, 0,
	    PCI_KNOWNDEV_NOPROD,
	    "Xircom",
	    NULL,
	},
	{
	    PCI_VENDOR_PEERPROTO, 0,
	    PCI_KNOWNDEV_NOPROD,
	    "Peer Protocols",
	    NULL,
	},
	{
	    PCI_VENDOR_MAXTOR, 0,
	    PCI_KNOWNDEV_NOPROD,
	    "Maxtor",
	    NULL,
	},
	{
	    PCI_VENDOR_MEGASOFT, 0,
	    PCI_KNOWNDEV_NOPROD,
	    "Megasoft",
	    NULL,
	},
	{
	    PCI_VENDOR_PFU, 0,
	    PCI_KNOWNDEV_NOPROD,
	    "PFU Limited",
	    NULL,
	},
	{
	    PCI_VENDOR_OALAB, 0,
	    PCI_KNOWNDEV_NOPROD,
	    "OA Laboratory",
	    NULL,
	},
	{
	    PCI_VENDOR_SYNEMA, 0,
	    PCI_KNOWNDEV_NOPROD,
	    "Synema",
	    NULL,
	},
	{
	    PCI_VENDOR_APT, 0,
	    PCI_KNOWNDEV_NOPROD,
	    "Advanced Peripherals Technologies",
	    NULL,
	},
	{
	    PCI_VENDOR_IMAGRAPH, 0,
	    PCI_KNOWNDEV_NOPROD,
	    "Imagraph",
	    NULL,
	},
	{
	    PCI_VENDOR_PEQUR, 0,
	    PCI_KNOWNDEV_NOPROD,
	    "Pequr Technology",
	    NULL,
	},
	{
	    PCI_VENDOR_MUTOH, 0,
	    PCI_KNOWNDEV_NOPROD,
	    "Mutoh Industries",
	    NULL,
	},
	{
	    PCI_VENDOR_THINE, 0,
	    PCI_KNOWNDEV_NOPROD,
	    "Thine Electronics",
	    NULL,
	},
	{
	    PCI_VENDOR_CDAC, 0,
	    PCI_KNOWNDEV_NOPROD,
	    "Centre for Dev. of Advanced Computing",
	    NULL,
	},
	{
	    PCI_VENDOR_POLARIS, 0,
	    PCI_KNOWNDEV_NOPROD,
	    "Polaris Communications",
	    NULL,
	},
	{
	    PCI_VENDOR_CONNECTWARE, 0,
	    PCI_KNOWNDEV_NOPROD,
	    "Connectware",
	    NULL,
	},
	{
	    PCI_VENDOR_WSTECH, 0,
	    PCI_KNOWNDEV_NOPROD,
	    "Workstation Technology",
	    NULL,
	},
	{
	    PCI_VENDOR_INVENTEC, 0,
	    PCI_KNOWNDEV_NOPROD,
	    "Inventec",
	    NULL,
	},
	{
	    PCI_VENDOR_LOUGHSOUND, 0,
	    PCI_KNOWNDEV_NOPROD,
	    "Loughborough Sound Images",
	    NULL,
	},
	{
	    PCI_VENDOR_ALTERA, 0,
	    PCI_KNOWNDEV_NOPROD,
	    "Altera Corperation",
	    NULL,
	},
	{
	    PCI_VENDOR_ADOBE, 0,
	    PCI_KNOWNDEV_NOPROD,
	    "Adobe Systems",
	    NULL,
	},
	{
	    PCI_VENDOR_BRIDGEPORT, 0,
	    PCI_KNOWNDEV_NOPROD,
	    "Bridgeport Machines",
	    NULL,
	},
	{
	    PCI_VENDOR_MIRTRON, 0,
	    PCI_KNOWNDEV_NOPROD,
	    "Mitron Computer",
	    NULL,
	},
	{
	    PCI_VENDOR_SBE, 0,
	    PCI_KNOWNDEV_NOPROD,
	    "SBE",
	    NULL,
	},
	{
	    PCI_VENDOR_SILICONENG, 0,
	    PCI_KNOWNDEV_NOPROD,
	    "Silicon Engineering",
	    NULL,
	},
	{
	    PCI_VENDOR_ALFA, 0,
	    PCI_KNOWNDEV_NOPROD,
	    "Alfa",
	    NULL,
	},
	{
	    PCI_VENDOR_TOSHIBA2, 0,
	    PCI_KNOWNDEV_NOPROD,
	    "Toshiba Info Systems (2nd ID)",
	    NULL,
	},
	{
	    PCI_VENDOR_ATREND, 0,
	    PCI_KNOWNDEV_NOPROD,
	    "A-Trend Technology",
	    NULL,
	},
	{
	    PCI_VENDOR_ATTO, 0,
	    PCI_KNOWNDEV_NOPROD,
	    "Atto Technology",
	    NULL,
	},
	{
	    PCI_VENDOR_TR, 0,
	    PCI_KNOWNDEV_NOPROD,
	    "T/R Systems",
	    NULL,
	},
	{
	    PCI_VENDOR_RICOH, 0,
	    PCI_KNOWNDEV_NOPROD,
	    "Ricoh",
	    NULL,
	},
	{
	    PCI_VENDOR_TELEMATICS, 0,
	    PCI_KNOWNDEV_NOPROD,
	    "Telematics International",
	    NULL,
	},
	{
	    PCI_VENDOR_FUJIKURA, 0,
	    PCI_KNOWNDEV_NOPROD,
	    "Fujikura",
	    NULL,
	},
	{
	    PCI_VENDOR_FORKS, 0,
	    PCI_KNOWNDEV_NOPROD,
	    "Forks",
	    NULL,
	},
	{
	    PCI_VENDOR_DATAWORLD, 0,
	    PCI_KNOWNDEV_NOPROD,
	    "Dataworld",
	    NULL,
	},
	{
	    PCI_VENDOR_DLINK, 0,
	    PCI_KNOWNDEV_NOPROD,
	    "D-Link Systems",
	    NULL,
	},
	{
	    PCI_VENDOR_ATL, 0,
	    PCI_KNOWNDEV_NOPROD,
	    "Advanced Techonoloy Labratories",
	    NULL,
	},
	{
	    PCI_VENDOR_SHIMA, 0,
	    PCI_KNOWNDEV_NOPROD,
	    "Shima Seiki Manufacturing",
	    NULL,
	},
	{
	    PCI_VENDOR_MATSUSHITA2, 0,
	    PCI_KNOWNDEV_NOPROD,
	    "Matsushita Electronics (2nd ID)",
	    NULL,
	},
	{
	    PCI_VENDOR_HILEVEL, 0,
	    PCI_KNOWNDEV_NOPROD,
	    "HiLevel Technology",
	    NULL,
	},
	{
	    PCI_VENDOR_COROLLARY, 0,
	    PCI_KNOWNDEV_NOPROD,
	    "Corrollary",
	    NULL,
	},
	{
	    PCI_VENDOR_BITFLOW, 0,
	    PCI_KNOWNDEV_NOPROD,
	    "BitFlow",
	    NULL,
	},
	{
	    PCI_VENDOR_HERMSTEDT, 0,
	    PCI_KNOWNDEV_NOPROD,
	    "Hermstedt",
	    NULL,
	},
	{
	    PCI_VENDOR_ARTOP, 0,
	    PCI_KNOWNDEV_NOPROD,
	    "Artop Electric",
	    NULL,
	},
	{
	    PCI_VENDOR_DENSAN, 0,
	    PCI_KNOWNDEV_NOPROD,
	    "Densan",
	    NULL,
	},
	{
	    PCI_VENDOR_ZEINET, 0,
	    PCI_KNOWNDEV_NOPROD,
	    "Zeinet",
	    NULL,
	},
	{
	    PCI_VENDOR_TOUCAN, 0,
	    PCI_KNOWNDEV_NOPROD,
	    "Toucan Technology",
	    NULL,
	},
	{
	    PCI_VENDOR_RATOC, 0,
	    PCI_KNOWNDEV_NOPROD,
	    "Ratoc System",
	    NULL,
	},
	{
	    PCI_VENDOR_HYTEC, 0,
	    PCI_KNOWNDEV_NOPROD,
	    "Hytec Electronic",
	    NULL,
	},
	{
	    PCI_VENDOR_GAGE, 0,
	    PCI_KNOWNDEV_NOPROD,
	    "Gage Applied Sciences",
	    NULL,
	},
	{
	    PCI_VENDOR_LAMBDA, 0,
	    PCI_KNOWNDEV_NOPROD,
	    "Lambda Systems",
	    NULL,
	},
	{
	    PCI_VENDOR_DCA, 0,
	    PCI_KNOWNDEV_NOPROD,
	    "Digital Communications Associates",
	    NULL,
	},
	{
	    PCI_VENDOR_MINDSHARE, 0,
	    PCI_KNOWNDEV_NOPROD,
	    "Mind Share",
	    NULL,
	},
	{
	    PCI_VENDOR_OMEGA, 0,
	    PCI_KNOWNDEV_NOPROD,
	    "Omega Micro",
	    NULL,
	},
	{
	    PCI_VENDOR_ITI, 0,
	    PCI_KNOWNDEV_NOPROD,
	    "Information Technology Institute",
	    NULL,
	},
	{
	    PCI_VENDOR_BUG, 0,
	    PCI_KNOWNDEV_NOPROD,
	    "Bug Sapporo",
	    NULL,
	},
	{
	    PCI_VENDOR_FUJITSU3, 0,
	    PCI_KNOWNDEV_NOPROD,
	    "Fujitsu (3th PCI Vendor ID)",
	    NULL,
	},
	{
	    PCI_VENDOR_BULL, 0,
	    PCI_KNOWNDEV_NOPROD,
	    "Bull Hn Information Systems",
	    NULL,
	},
	{
	    PCI_VENDOR_CONVEX, 0,
	    PCI_KNOWNDEV_NOPROD,
	    "Convex Computer",
	    NULL,
	},
	{
	    PCI_VENDOR_HAMAMATSU, 0,
	    PCI_KNOWNDEV_NOPROD,
	    "Hamamatsu Photonics",
	    NULL,
	},
	{
	    PCI_VENDOR_SIERRA2, 0,
	    PCI_KNOWNDEV_NOPROD,
	    "Sierra Research & Technology (2nd ID)",
	    NULL,
	},
	{
	    PCI_VENDOR_BARCO, 0,
	    PCI_KNOWNDEV_NOPROD,
	    "Barco",
	    NULL,
	},
	{
	    PCI_VENDOR_MICROUNITY, 0,
	    PCI_KNOWNDEV_NOPROD,
	    "MicroUnity Systems Engineering",
	    NULL,
	},
	{
	    PCI_VENDOR_PUREDATA, 0,
	    PCI_KNOWNDEV_NOPROD,
	    "Pure Data",
	    NULL,
	},
	{
	    PCI_VENDOR_POWERCC, 0,
	    PCI_KNOWNDEV_NOPROD,
	    "Power Computing",
	    NULL,
	},
	{
	    PCI_VENDOR_INNOSYS, 0,
	    PCI_KNOWNDEV_NOPROD,
	    "InnoSys",
	    NULL,
	},
	{
	    PCI_VENDOR_ACTEL, 0,
	    PCI_KNOWNDEV_NOPROD,
	    "Actel",
	    NULL,
	},
	{
	    PCI_VENDOR_GALILEO, 0,
	    PCI_KNOWNDEV_NOPROD,
	    "Galileo Technology",
	    NULL,
	},
	{
	    PCI_VENDOR_CANNON, 0,
	    PCI_KNOWNDEV_NOPROD,
	    "Cannon IS",
	    NULL,
	},
	{
	    PCI_VENDOR_LITEON, 0,
	    PCI_KNOWNDEV_NOPROD,
	    "Lite-On",
	    NULL,
	},
	{
	    PCI_VENDOR_SCITEX, 0,
	    PCI_KNOWNDEV_NOPROD,
	    "Scitex",
	    NULL,
	},
	{
	    PCI_VENDOR_PROLOG, 0,
	    PCI_KNOWNDEV_NOPROD,
	    "Pro-Log",
	    NULL,
	},
	{
	    PCI_VENDOR_V3, 0,
	    PCI_KNOWNDEV_NOPROD,
	    "V3 Semiconductor",
	    NULL,
	},
	{
	    PCI_VENDOR_APRICOT, 0,
	    PCI_KNOWNDEV_NOPROD,
	    "Apricot Computer",
	    NULL,
	},
	{
	    PCI_VENDOR_KODAK, 0,
	    PCI_KNOWNDEV_NOPROD,
	    "Eastman Kodak",
	    NULL,
	},
	{
	    PCI_VENDOR_BARR, 0,
	    PCI_KNOWNDEV_NOPROD,
	    "Barr Systems",
	    NULL,
	},
	{
	    PCI_VENDOR_LEITECH, 0,
	    PCI_KNOWNDEV_NOPROD,
	    "Leitch Technology",
	    NULL,
	},
	{
	    PCI_VENDOR_RADSTONE, 0,
	    PCI_KNOWNDEV_NOPROD,
	    "Radstone Technology",
	    NULL,
	},
	{
	    PCI_VENDOR_UNITEDVIDEO, 0,
	    PCI_KNOWNDEV_NOPROD,
	    "United Video",
	    NULL,
	},
	{
	    PCI_VENDOR_MOT2, 0,
	    PCI_KNOWNDEV_NOPROD,
	    "Motorola (2nd ID)",
	    NULL,
	},
	{
	    PCI_VENDOR_XPOINT, 0,
	    PCI_KNOWNDEV_NOPROD,
	    "Xpoint Technologies",
	    NULL,
	},
	{
	    PCI_VENDOR_PATHLIGHT, 0,
	    PCI_KNOWNDEV_NOPROD,
	    "Pathlight Technology",
	    NULL,
	},
	{
	    PCI_VENDOR_VIDEOTRON, 0,
	    PCI_KNOWNDEV_NOPROD,
	    "VideoTron",
	    NULL,
	},
	{
	    PCI_VENDOR_PYRAMID, 0,
	    PCI_KNOWNDEV_NOPROD,
	    "Pyramid Technologies",
	    NULL,
	},
	{
	    PCI_VENDOR_NETPERIPH, 0,
	    PCI_KNOWNDEV_NOPROD,
	    "Network Peripherals",
	    NULL,
	},
	{
	    PCI_VENDOR_PINNACLE, 0,
	    PCI_KNOWNDEV_NOPROD,
	    "Pinnacle Systems",
	    NULL,
	},
	{
	    PCI_VENDOR_IMI, 0,
	    PCI_KNOWNDEV_NOPROD,
	    "International Microcircuts",
	    NULL,
	},
	{
	    PCI_VENDOR_NEC2, 0,
	    PCI_KNOWNDEV_NOPROD,
	    "NEC (2nd ID)",
	    NULL,
	},
	{
	    PCI_VENDOR_DOCTECH, 0,
	    PCI_KNOWNDEV_NOPROD,
	    "Document Technologies",
	    NULL,
	},
	{
	    PCI_VENDOR_SHIVA, 0,
	    PCI_KNOWNDEV_NOPROD,
	    "Shiva",
	    NULL,
	},
	{
	    PCI_VENDOR_DCMDATA, 0,
	    PCI_KNOWNDEV_NOPROD,
	    "DCM Data Systems",
	    NULL,
	},
	{
	    PCI_VENDOR_DOLPHIN, 0,
	    PCI_KNOWNDEV_NOPROD,
	    "Dolphin Interconnect Solutions",
	    NULL,
	},
	{
	    PCI_VENDOR_MRTMAGMA, 0,
	    PCI_KNOWNDEV_NOPROD,
	    "Mesa Ridge Technologies (MAGMA)",
	    NULL,
	},
	{
	    PCI_VENDOR_LSISYS, 0,
	    PCI_KNOWNDEV_NOPROD,
	    "LSI Systems",
	    NULL,
	},
	{
	    PCI_VENDOR_SPECIALIX, 0,
	    PCI_KNOWNDEV_NOPROD,
	    "Specialix Research",
	    NULL,
	},
	{
	    PCI_VENDOR_MKC, 0,
	    PCI_KNOWNDEV_NOPROD,
	    "Michels & Kleberhoff Computer",
	    NULL,
	},
	{
	    PCI_VENDOR_HAL, 0,
	    PCI_KNOWNDEV_NOPROD,
	    "HAL Computer Systems",
	    NULL,
	},
	{
	    PCI_VENDOR_ZORAN, 0,
	    PCI_KNOWNDEV_NOPROD,
	    "Zoran",
	    NULL,
	},
	{
	    PCI_VENDOR_COMPEX, 0,
	    PCI_KNOWNDEV_NOPROD,
	    "Compex",
	    NULL,
	},
	{
	    PCI_VENDOR_PMCSIERRA, 0,
	    PCI_KNOWNDEV_NOPROD,
	    "PMC-Sierra",
	    NULL,
	},
	{
	    PCI_VENDOR_CYCLADES, 0,
	    PCI_KNOWNDEV_NOPROD,
	    "Cyclades",
	    NULL,
	},
	{
	    PCI_VENDOR_ESSENTIAL, 0,
	    PCI_KNOWNDEV_NOPROD,
	    "Essential Communications",
	    NULL,
	},
	{
	    PCI_VENDOR_2MICRO, 0,
	    PCI_KNOWNDEV_NOPROD,
	    "2 Micro Inc",
	    NULL,
	},
	{
	    PCI_VENDOR_3DFX, 0,
	    PCI_KNOWNDEV_NOPROD,
	    "3DFX Interactive",
	    NULL,
	},
	{
	    PCI_VENDOR_ARIEL, 0,
	    PCI_KNOWNDEV_NOPROD,
	    "Ariel",
	    NULL,
	},
	{
	    PCI_VENDOR_AZTECH, 0,
	    PCI_KNOWNDEV_NOPROD,
	    "Aztech",
	    NULL,
	},
	{
	    PCI_VENDOR_3DO, 0,
	    PCI_KNOWNDEV_NOPROD,
	    "The 3D0 Company",
	    NULL,
	},
	{
	    PCI_VENDOR_STALLION, 0,
	    PCI_KNOWNDEV_NOPROD,
	    "Stallion Technologies",
	    NULL,
	},
	{
	    PCI_VENDOR_LINEARSYS, 0,
	    PCI_KNOWNDEV_NOPROD,
	    "Linear Systems",
	    NULL,
	},
	{
	    PCI_VENDOR_AURORA, 0,
	    PCI_KNOWNDEV_NOPROD,
	    "Aurora Technologies",
	    NULL,
	},
	{
	    PCI_VENDOR_ENSONIQ, 0,
	    PCI_KNOWNDEV_NOPROD,
	    "Ensoniq",
	    NULL,
	},
	{
	    PCI_VENDOR_NETAPP, 0,
	    PCI_KNOWNDEV_NOPROD,
	    "Network Appliance",
	    NULL,
	},
	{
	    PCI_VENDOR_ROCKWELL, 0,
	    PCI_KNOWNDEV_NOPROD,
	    "Rockwell Semiconductor Systems",
	    NULL,
	},
	{
	    PCI_VENDOR_TRITECH, 0,
	    PCI_KNOWNDEV_NOPROD,
	    "TriTech Microelectronics",
	    NULL,
	},
	{
	    PCI_VENDOR_KOFAX, 0,
	    PCI_KNOWNDEV_NOPROD,
	    "Kofax Image Products",
	    NULL,
	},
	{
	    PCI_VENDOR_PICTUREEL, 0,
	    PCI_KNOWNDEV_NOPROD,
	    "Picture Elements",
	    NULL,
	},
	{
	    PCI_VENDOR_STB2, 0,
	    PCI_KNOWNDEV_NOPROD,
	    "STB (2nd ID)",
	    NULL,
	},
	{
	    PCI_VENDOR_SYMPHONY2, 0,
	    PCI_KNOWNDEV_NOPROD,
	    "Symphony Labs (2nd ID)",
	    NULL,
	},
	{
	    PCI_VENDOR_TEKRAM2, 0,
	    PCI_KNOWNDEV_NOPROD,
	    "Tekram Technology (2nd ID)",
	    NULL,
	},
	{
	    PCI_VENDOR_3DLABS, 0,
	    PCI_KNOWNDEV_NOPROD,
	    "3D Labs",
	    NULL,
	},
	{
	    PCI_VENDOR_AVANCE2, 0,
	    PCI_KNOWNDEV_NOPROD,
	    "Avance Logic (2nd ID)",
	    NULL,
	},
	{
	    PCI_VENDOR_NETVIN, 0,
	    PCI_KNOWNDEV_NOPROD,
	    "NetVin",
	    NULL,
	},
	{
	    PCI_VENDOR_BUSLOGIC2, 0,
	    PCI_KNOWNDEV_NOPROD,
	    "Buslogic (2nd ID)",
	    NULL,
	},
	{
	    PCI_VENDOR_S3, 0,
	    PCI_KNOWNDEV_NOPROD,
	    "S3",
	    NULL,
	},
	{
	    PCI_VENDOR_NETPOWER2, 0,
	    PCI_KNOWNDEV_NOPROD,
	    "NetPower (2nd ID)",
	    NULL,
	},
	{
	    PCI_VENDOR_C4T, 0,
	    PCI_KNOWNDEV_NOPROD,
	    "c't Magazin",
	    NULL,
	},
	{
	    PCI_VENDOR_QUANCM, 0,
	    PCI_KNOWNDEV_NOPROD,
	    "Quancm Electronic GmbH",
	    NULL,
	},
	{
	    PCI_VENDOR_INTEL, 0,
	    PCI_KNOWNDEV_NOPROD,
	    "Intel",
	    NULL,
	},
	{
	    PCI_VENDOR_TRIGEM2, 0,
	    PCI_KNOWNDEV_NOPROD,
	    "Trigem Computer (2nd ID)",
	    NULL,
	},
	{
	    PCI_VENDOR_WINBOND2, 0,
	    PCI_KNOWNDEV_NOPROD,
	    "Winbond Electronics (2nd ID)",
	    NULL,
	},
	{
	    PCI_VENDOR_COMPUTONE, 0,
	    PCI_KNOWNDEV_NOPROD,
	    "Computone Corperation",
	    NULL,
	},
	{
	    PCI_VENDOR_KTI, 0,
	    PCI_KNOWNDEV_NOPROD,
	    "KTI",
	    NULL,
	},
	{
	    PCI_VENDOR_ADP, 0,
	    PCI_KNOWNDEV_NOPROD,
	    "Adaptec",
	    NULL,
	},
	{
	    PCI_VENDOR_ATRONICS, 0,
	    PCI_KNOWNDEV_NOPROD,
	    "Atronics",
	    NULL,
	},
	{
	    PCI_VENDOR_ARC, 0,
	    PCI_KNOWNDEV_NOPROD,
	    "ARC Logic",
	    NULL,
	},
	{
	    PCI_VENDOR_INVALID, 0,
	    PCI_KNOWNDEV_NOPROD,
	    "INVALID VENDOR ID",
	    NULL,
	},
	{ 0, 0, 0, NULL, NULL, }
};
