/*
 * THIS FILE AUTOMATICALLY GENERATED.  DO NOT EDIT.
 *
 * generated from:
 *	OpenBSD: pcidevs,v 1.14 1996/11/28 23:28:11 niklas Exp 
 */
/*	$NetBSD: pcidevs,v 1.20 1996/10/19 13:01:49 jonathan Exp $	*/


struct pci_knowndev pci_knowndevs[] = {
	{
	    PCI_VENDOR_3COM, PCI_PRODUCT_3COM_3C590,
	    0,
	    "3Com",
	    "3c590 10Mbps",
	},
	{
	    PCI_VENDOR_3COM, PCI_PRODUCT_3COM_3C595TX,
	    0,
	    "3Com",
	    "3c595 100Base-TX",
	},
	{
	    PCI_VENDOR_3COM, PCI_PRODUCT_3COM_3C595T4,
	    0,
	    "3Com",
	    "3c595 100Base-T4",
	},
	{
	    PCI_VENDOR_3COM, PCI_PRODUCT_3COM_3C595MII,
	    0,
	    "3Com",
	    "3c595 10Mbps-MII",
	},
	{
	    PCI_VENDOR_3COM, PCI_PRODUCT_3COM_3C900TPO,
	    0,
	    "3Com",
	    "3c900 10Base-T",
	},
	{
	    PCI_VENDOR_3COM, PCI_PRODUCT_3COM_3C900COMBO,
	    0,
	    "3Com",
	    "3c900 10Mbps-Combo",
	},
	{
	    PCI_VENDOR_3COM, PCI_PRODUCT_3COM_3C905TX,
	    0,
	    "3Com",
	    "3c905 100Base-TX",
	},
	{
	    PCI_VENDOR_3COM, PCI_PRODUCT_3COM_3C905T4,
	    0,
	    "3Com",
	    "3c905 100Base-T4",
	},
	{
	    PCI_VENDOR_ALI, PCI_PRODUCT_ALI_M1445,
	    0,
	    "Acer Labs",
	    "M1445",
	},
	{
	    PCI_VENDOR_ALI, PCI_PRODUCT_ALI_M1449,
	    0,
	    "Acer Labs",
	    "M1449",
	},
	{
	    PCI_VENDOR_ALI, PCI_PRODUCT_ALI_M1451,
	    0,
	    "Acer Labs",
	    "M1451",
	},
	{
	    PCI_VENDOR_ALI, PCI_PRODUCT_ALI_M4803,
	    0,
	    "Acer Labs",
	    "M4803",
	},
	{
	    PCI_VENDOR_ADP, PCI_PRODUCT_ADP_AIC7850,
	    0,
	    "Adaptec",
	    "AIC-7850",
	},
	{
	    PCI_VENDOR_ADP, PCI_PRODUCT_ADP_AIC7855,
	    0,
	    "Adaptec",
	    "AIC-7855",
	},
	{
	    PCI_VENDOR_ADP, PCI_PRODUCT_ADP_AIC7860,
	    0,
	    "Adaptec",
	    "AIC-7860",
	},
	{
	    PCI_VENDOR_ADP, PCI_PRODUCT_ADP_2940AU,
	    0,
	    "Adaptec",
	    "AHA-2940A Ultra",
	},
	{
	    PCI_VENDOR_ADP, PCI_PRODUCT_ADP_AIC7870,
	    0,
	    "Adaptec",
	    "AIC-7870",
	},
	{
	    PCI_VENDOR_ADP, PCI_PRODUCT_ADP_2940,
	    0,
	    "Adaptec",
	    "AHA-2940",
	},
	{
	    PCI_VENDOR_ADP, PCI_PRODUCT_ADP_3940,
	    0,
	    "Adaptec",
	    "AHA-3940",
	},
	{
	    PCI_VENDOR_ADP, PCI_PRODUCT_ADP_2944,
	    0,
	    "Adaptec",
	    "AHA-2944",
	},
	{
	    PCI_VENDOR_ADP, PCI_PRODUCT_ADP_AIC7880,
	    0,
	    "Adaptec",
	    "AIC-7880 Ultra",
	},
	{
	    PCI_VENDOR_ADP, PCI_PRODUCT_ADP_2940U,
	    0,
	    "Adaptec",
	    "AHA-2940 Ultra",
	},
	{
	    PCI_VENDOR_ADP, PCI_PRODUCT_ADP_3940U,
	    0,
	    "Adaptec",
	    "AHA-3940 Ultra",
	},
	{
	    PCI_VENDOR_ADP, PCI_PRODUCT_ADP_2944U,
	    0,
	    "Adaptec",
	    "AHA-2944 Ultra",
	},
	{
	    PCI_VENDOR_AMD, PCI_PRODUCT_AMD_PCNET_PCI,
	    0,
	    "AMD",
	    "79c970 PCnet-PCI LANCE Ethernet",
	},
	{
	    PCI_VENDOR_AMD, PCI_PRODUCT_AMD_PCSCSI_PCI,
	    0,
	    "AMD",
	    "53c974 PCscsi-PCI SCSI",
	},
	{
	    PCI_VENDOR_ARK, PCI_PRODUCT_ARK_1000PV,
	    0,
	    "Ark Logic (or Arc? or Hercules?)",
	    "1000PV",
	},
	{
	    PCI_VENDOR_ARK, PCI_PRODUCT_ARK_2000PV,
	    0,
	    "Ark Logic (or Arc? or Hercules?)",
	    "2000PV",
	},
	{
	    PCI_VENDOR_ATI, PCI_PRODUCT_ATI_MACH32,
	    0,
	    "ATI Technologies",
	    "Mach32",
	},
	{
	    PCI_VENDOR_ATI, PCI_PRODUCT_ATI_MACH64_CT,
	    0,
	    "ATI Technologies",
	    "Mach64 CT",
	},
	{
	    PCI_VENDOR_ATI, PCI_PRODUCT_ATI_MACH64_CX,
	    0,
	    "ATI Technologies",
	    "Mach64 CX",
	},
	{
	    PCI_VENDOR_ATI, PCI_PRODUCT_ATI_MACH64_ET,
	    0,
	    "ATI Technologies",
	    "Mach64 ET",
	},
	{
	    PCI_VENDOR_ATI, PCI_PRODUCT_ATI_MACH64_VT,
	    0,
	    "ATI Technologies",
	    "Mach64 VT",
	},
	{
	    PCI_VENDOR_ATI, PCI_PRODUCT_ATI_MACH64_GT,
	    0,
	    "ATI Technologies",
	    "Mach64 GT",
	},
	{
	    PCI_VENDOR_ATI, PCI_PRODUCT_ATI_MACH64_GX,
	    0,
	    "ATI Technologies",
	    "Mach64 GX",
	},
	{
	    PCI_VENDOR_ATRONICS, PCI_PRODUCT_ATRONICS_IDE_2015PL,
	    0,
	    "Atronics",
	    "IDE-2015PL",
	},
	{
	    PCI_VENDOR_AVANCE, PCI_PRODUCT_AVANCE_ALG2301,
	    0,
	    "Avance Logic",
	    "ALG2301",
	},
	{
	    PCI_VENDOR_BUSLOGIC, PCI_PRODUCT_BUSLOGIC_OLD946C,
	    0,
	    "BusLogic",
	    "946C 01",
	},
	{
	    PCI_VENDOR_BUSLOGIC, PCI_PRODUCT_BUSLOGIC_946C,
	    0,
	    "BusLogic",
	    "946C 10",
	},
	{
	    PCI_VENDOR_CHIPS, PCI_PRODUCT_CHIPS_65545,
	    0,
	    "Chips and Technologies",
	    "65545",
	},
	{
	    PCI_VENDOR_CIRRUS, PCI_PRODUCT_CIRRUS_GD_5430,
	    0,
	    "Cirrus Logic",
	    "GD 5430",
	},
	{
	    PCI_VENDOR_CIRRUS, PCI_PRODUCT_CIRRUS_GD_5434_4,
	    0,
	    "Cirrus Logic",
	    "GD 5434-4",
	},
	{
	    PCI_VENDOR_CIRRUS, PCI_PRODUCT_CIRRUS_GD_5434_8,
	    0,
	    "Cirrus Logic",
	    "GD 5434-8",
	},
	{
	    PCI_VENDOR_CIRRUS, PCI_PRODUCT_CIRRUS_GD_5436,
	    0,
	    "Cirrus Logic",
	    "GD 5436",
	},
	{
	    PCI_VENDOR_CIRRUS, PCI_PRODUCT_CIRRUS_CL_6729,
	    0,
	    "Cirrus Logic",
	    "CL 6729",
	},
	{
	    PCI_VENDOR_CIRRUS, PCI_PRODUCT_CIRRUS_CL_7542,
	    0,
	    "Cirrus Logic",
	    "CL 7542",
	},
	{
	    PCI_VENDOR_CMDTECH, PCI_PRODUCT_CMDTECH_640A,
	    0,
	    "CMD Technology",
	    "640A",
	},
	{
	    PCI_VENDOR_CONTAQ, PCI_PRODUCT_CONTAQ_82C599,
	    0,
	    "Contaq Microsystems",
	    "82C599",
	},
	{
	    PCI_VENDOR_DEC, PCI_PRODUCT_DEC_21050,
	    0,
	    "Digital Equipment",
	    "DECchip 21050 PCI-PCI Bridge",
	},
	{
	    PCI_VENDOR_DEC, PCI_PRODUCT_DEC_21040,
	    0,
	    "Digital Equipment",
	    "DECchip 21040 (\"Tulip\")",
	},
	{
	    PCI_VENDOR_DEC, PCI_PRODUCT_DEC_21030,
	    0,
	    "Digital Equipment",
	    "DECchip 21030 (\"TGA\")",
	},
	{
	    PCI_VENDOR_DEC, PCI_PRODUCT_DEC_NVRAM,
	    0,
	    "Digital Equipment",
	    "Zephyr NV-RAM",
	},
	{
	    PCI_VENDOR_DEC, PCI_PRODUCT_DEC_KZPSA,
	    0,
	    "Digital Equipment",
	    "KZPSA",
	},
	{
	    PCI_VENDOR_DEC, PCI_PRODUCT_DEC_21140,
	    0,
	    "Digital Equipment",
	    "DECchip 21140 (\"FasterNet\")",
	},
	{
	    PCI_VENDOR_DEC, PCI_PRODUCT_DEC_PBXGB,
	    0,
	    "Digital Equipment",
	    "TGA2",
	},
	{
	    PCI_VENDOR_DEC, PCI_PRODUCT_DEC_DEFPA,
	    0,
	    "Digital Equipment",
	    "DEFPA",
	},
	{
	    PCI_VENDOR_DEC, PCI_PRODUCT_DEC_21041,
	    0,
	    "Digital Equipment",
	    "DECchip 21041 (\"Tulip Pass 3\")",
	},
	{
	    PCI_VENDOR_DEC, PCI_PRODUCT_DEC_DGLPB,
	    0,
	    "Digital Equipment",
	    "DGLPB (\"OPPO\")",
	},
	{
	    PCI_VENDOR_DIAMOND, PCI_PRODUCT_DIAMOND_vIPER,
	    0,
	    "Diamond Computer Systems",
	    "Viper/PCI",
	},
	{
	    PCI_VENDOR_DPT, PCI_PRODUCT_DPT_SC_RAID,
	    0,
	    "Distributed Processing Technology",
	    "SmartCache/Raid",
	},
	{
	    PCI_VENDOR_FORE, PCI_PRODUCT_FORE_PCA200,
	    0,
	    "FORE Systems",
	    "ATM PCA-200",
	},
	{
	    PCI_VENDOR_FORE, PCI_PRODUCT_FORE_PCA200E,
	    0,
	    "FORE Systems",
	    "ATM PCA-200e",
	},
	{
	    PCI_VENDOR_FUTUREDOMAIN, PCI_PRODUCT_FUTUREDOMAIN_TMC_18C30,
	    0,
	    "Future Domain",
	    "TMC-18C30 (36C70)",
	},
	{
	    PCI_VENDOR_EFFICIENTNETS, PCI_PRODUCT_EFFICIENTNETS_ENI155P,
	    0,
	    "Efficent Networks",
	    "155P-MF1 ATM",
	},
	{
	    PCI_VENDOR_HP, PCI_PRODUCT_HP_J2585A,
	    0,
	    "Hewlett-Packard",
	    "J2585A",
	},
	{
	    PCI_VENDOR_IBM, PCI_PRODUCT_IBM_82351,
	    0,
	    "IBM",
	    "82351 PCI-PCI Bridge",
	},
	{
	    PCI_VENDOR_IMS, PCI_PRODUCT_IMS_8849,
	    0,
	    "Integrated Micro Solutions",
	    "8849",
	},
	{
	    PCI_VENDOR_INTEL, PCI_PRODUCT_INTEL_PCEB,
	    0,
	    "Intel",
	    "82375EB PCI-EISA Bridge",
	},
	{
	    PCI_VENDOR_INTEL, PCI_PRODUCT_INTEL_CDC,
	    0,
	    "Intel",
	    "82424ZX Cache and DRAM controller",
	},
	{
	    PCI_VENDOR_INTEL, PCI_PRODUCT_INTEL_SIO,
	    0,
	    "Intel",
	    "82378IB PCI-ISA Bridge (System I/O)",
	},
	{
	    PCI_VENDOR_INTEL, PCI_PRODUCT_INTEL_PCIB,
	    0,
	    "Intel",
	    "82426EX PCI-ISA Bridge",
	},
	{
	    PCI_VENDOR_INTEL, PCI_PRODUCT_INTEL_PCMC,
	    0,
	    "Intel",
	    "82434LX PCI, Cache, and Memory Controller",
	},
	{
	    PCI_VENDOR_INTEL, PCI_PRODUCT_INTEL_SAA7116,
	    0,
	    "Intel",
	    "SAA7116",
	},
	{
	    PCI_VENDOR_INTEL, PCI_PRODUCT_INTEL_82437,
	    0,
	    "Intel",
	    "82437 Triton",
	},
	{
	    PCI_VENDOR_INTEL, PCI_PRODUCT_INTEL_82471,
	    0,
	    "Intel",
	    "82471 Triton",
	},
	{
	    PCI_VENDOR_INTEL, PCI_PRODUCT_INTEL_82438,
	    0,
	    "Intel",
	    "82438",
	},
	{
	    PCI_VENDOR_INTEL, PCI_PRODUCT_INTEL_82440FX,
	    0,
	    "Intel",
	    "82440FX Natoma, PCI and memory controller",
	},
	{
	    PCI_VENDOR_INTEL, PCI_PRODUCT_INTEL_82371SBa,
	    0,
	    "Intel",
	    "82371SB PCI-ISA bridge",
	},
	{
	    PCI_VENDOR_INTEL, PCI_PRODUCT_INTEL_82371SBb,
	    0,
	    "Intel",
	    "82371SB IDE interface",
	},
	{
	    PCI_VENDOR_INTEL, PCI_PRODUCT_INTEL_82450KX,
	    0,
	    "Intel",
	    "82450KX Orion, PCI memory controller",
	},
	{
	    PCI_VENDOR_INTEL, PCI_PRODUCT_INTEL_82454GX,
	    0,
	    "Intel",
	    "82454GX Orion, host to PCI bridge",
	},
	{
	    PCI_VENDOR_ITT, PCI_PRODUCT_ITT_AGX016,
	    0,
	    "I. T. T. (or X technology?)",
	    "AGX016",
	},
	{
	    PCI_VENDOR_LEADTEK, PCI_PRODUCT_LEADTEK_S3_805,
	    0,
	    "LeadTek Research",
	    "S3 805",
	},
	{
	    PCI_VENDOR_MATROX, PCI_PRODUCT_MATROX_ATLAS,
	    0,
	    "Matrox",
	    "MGA-2 Atlas PX2085",
	},
	{
	    PCI_VENDOR_MATROX, PCI_PRODUCT_MATROX_IMPRESSION,
	    0,
	    "Matrox",
	    "MGA Impression",
	},
	{
	    PCI_VENDOR_MYLEX, PCI_PRODUCT_MYLEX_960P,
	    0,
	    "Mylex",
	    "RAID controller",
	},
	{
	    PCI_VENDOR_MUTECH, PCI_PRODUCT_MUTECH_MV1000,
	    0,
	    "Mutech",
	    "MV1000",
	},
	{
	    PCI_VENDOR_NS, PCI_PRODUCT_NS_87410,
	    0,
	    "National Semiconductor",
	    "87410",
	},
	{
	    PCI_VENDOR_OLDNCR, PCI_PRODUCT_OLDNCR_810,
	    0,
	    "NCR",
	    "53c810",
	},
	{
	    PCI_VENDOR_OLDNCR, PCI_PRODUCT_OLDNCR_820,
	    0,
	    "NCR",
	    "53c820",
	},
	{
	    PCI_VENDOR_OLDNCR, PCI_PRODUCT_OLDNCR_825,
	    0,
	    "NCR",
	    "53c825",
	},
	{
	    PCI_VENDOR_OLDNCR, PCI_PRODUCT_OLDNCR_815,
	    0,
	    "NCR",
	    "53c815",
	},
	{
	    PCI_VENDOR_OLDNCR, PCI_PRODUCT_OLDNCR_810AP,
	    0,
	    "NCR",
	    "53c810AP",
	},
	{
	    PCI_VENDOR_OLDNCR, PCI_PRODUCT_OLDNCR_860,
	    0,
	    "NCR",
	    "53c860",
	},
	{
	    PCI_VENDOR_OLDNCR, PCI_PRODUCT_OLDNCR_875,
	    0,
	    "NCR",
	    "53c875",
	},
	{
	    PCI_VENDOR_NUMBER9, PCI_PRODUCT_NUMBER9_IMAG128,
	    0,
	    "Number 9 Computer Company",
	    "Imagine-128",
	},
	{
	    PCI_VENDOR_OPTI, PCI_PRODUCT_OPTI_82C557,
	    0,
	    "Opti",
	    "82C557",
	},
	{
	    PCI_VENDOR_OPTI, PCI_PRODUCT_OPTI_82C558,
	    0,
	    "Opti",
	    "82C558",
	},
	{
	    PCI_VENDOR_OPTI, PCI_PRODUCT_OPTI_82C621,
	    0,
	    "Opti",
	    "82C621",
	},
	{
	    PCI_VENDOR_OPTI, PCI_PRODUCT_OPTI_82C822,
	    0,
	    "Opti",
	    "82C822",
	},
	{
	    PCI_VENDOR_PROMISE, PCI_PRODUCT_PROMISE_DC5030,
	    0,
	    "Promise Technology",
	    "DC5030",
	},
	{
	    PCI_VENDOR_QLOGIC, PCI_PRODUCT_QLOGIC_ISP1020,
	    0,
	    "Q Logic",
	    "ISP1020",
	},
	{
	    PCI_VENDOR_QLOGIC, PCI_PRODUCT_QLOGIC_ISP1022,
	    0,
	    "Q Logic",
	    "ISP1022",
	},
	{
	    PCI_VENDOR_QUANTUMDESIGNS, PCI_PRODUCT_QUANTUMDESIGNS_8500,
	    0,
	    "Quantum Designs (or Vision?)",
	    "8500",
	},
	{
	    PCI_VENDOR_QUANTUMDESIGNS, PCI_PRODUCT_QUANTUMDESIGNS_8580,
	    0,
	    "Quantum Designs (or Vision?)",
	    "8580",
	},
	{
	    PCI_VENDOR_REALTEK, PCI_PRODUCT_REALTEK_RT8029,
	    0,
	    "Realtek Semiconductor",
	    "Ethernet",
	},
	{
	    PCI_VENDOR_S3, PCI_PRODUCT_S3_TRIO64,
	    0,
	    "S3",
	    "Trio32/64",
	},
	{
	    PCI_VENDOR_S3, PCI_PRODUCT_S3_868,
	    0,
	    "S3",
	    "868",
	},
	{
	    PCI_VENDOR_S3, PCI_PRODUCT_S3_928,
	    0,
	    "S3",
	    "928",
	},
	{
	    PCI_VENDOR_S3, PCI_PRODUCT_S3_864_0,
	    0,
	    "S3",
	    "864-0",
	},
	{
	    PCI_VENDOR_S3, PCI_PRODUCT_S3_864_1,
	    0,
	    "S3",
	    "864-1",
	},
	{
	    PCI_VENDOR_S3, PCI_PRODUCT_S3_964_0,
	    0,
	    "S3",
	    "964-0",
	},
	{
	    PCI_VENDOR_S3, PCI_PRODUCT_S3_964_1,
	    0,
	    "S3",
	    "964-1",
	},
	{
	    PCI_VENDOR_S3, PCI_PRODUCT_S3_968,
	    0,
	    "S3",
	    "968",
	},
	{
	    PCI_VENDOR_SIS, PCI_PRODUCT_SIS_86C201,
	    0,
	    "Silicon Integrated System",
	    "86C201",
	},
	{
	    PCI_VENDOR_SIS, PCI_PRODUCT_SIS_86C202,
	    0,
	    "Silicon Integrated System",
	    "86C202",
	},
	{
	    PCI_VENDOR_SIS, PCI_PRODUCT_SIS_86C205,
	    0,
	    "Silicon Integrated System",
	    "86C205",
	},
	{
	    PCI_VENDOR_SIS, PCI_PRODUCT_SIS_85C503,
	    0,
	    "Silicon Integrated System",
	    "85C503",
	},
	{
	    PCI_VENDOR_SIS, PCI_PRODUCT_SIS_85C501,
	    0,
	    "Silicon Integrated System",
	    "85C501",
	},
	{
	    PCI_VENDOR_SIS, PCI_PRODUCT_SIS_85C496,
	    0,
	    "Silicon Integrated System",
	    "85C496",
	},
	{
	    PCI_VENDOR_SIS, PCI_PRODUCT_SIS_85C601,
	    0,
	    "Silicon Integrated System",
	    "85C601",
	},
	{
	    PCI_VENDOR_SMC, PCI_PRODUCT_SMC_37C665,
	    0,
	    "Standard Microsystems",
	    "FDC 37C665",
	},
	{
	    PCI_VENDOR_SYMPHONY, PCI_PRODUCT_SYMPHONY_82C101,
	    0,
	    "Symphony Labs",
	    "82C101",
	},
	{
	    PCI_VENDOR_TEKRAM, PCI_PRODUCT_TEKRAM_DC290,
	    0,
	    "Tekram Technology",
	    "DC290",
	},
	{
	    PCI_VENDOR_TRIDENT, PCI_PRODUCT_TRIDENT_TGUI_9320,
	    0,
	    "Trident Microsystems",
	    "TGUI 9320",
	},
	{
	    PCI_VENDOR_TRIDENT, PCI_PRODUCT_TRIDENT_TGUI_9420,
	    0,
	    "Trident Microsystems",
	    "TGUI 9420",
	},
	{
	    PCI_VENDOR_TRIDENT, PCI_PRODUCT_TRIDENT_TGUI_9440,
	    0,
	    "Trident Microsystems",
	    "TGUI 9440",
	},
	{
	    PCI_VENDOR_TRIDENT, PCI_PRODUCT_TRIDENT_TGUI_9660,
	    0,
	    "Trident Microsystems",
	    "TGUI 9660",
	},
	{
	    PCI_VENDOR_TRIDENT, PCI_PRODUCT_TRIDENT_TGUI_9680,
	    0,
	    "Trident Microsystems",
	    "TGUI 9680",
	},
	{
	    PCI_VENDOR_TRIDENT, PCI_PRODUCT_TRIDENT_TGUI_9682,
	    0,
	    "Trident Microsystems",
	    "TGUI 9682",
	},
	{
	    PCI_VENDOR_TSENG, PCI_PRODUCT_TSENG_ET4000_W32P_A,
	    0,
	    "Tseng Labs",
	    "ET4000w32p rev A",
	},
	{
	    PCI_VENDOR_TSENG, PCI_PRODUCT_TSENG_ET4000_W32P_B,
	    0,
	    "Tseng Labs",
	    "ET4000w32p rev B",
	},
	{
	    PCI_VENDOR_TSENG, PCI_PRODUCT_TSENG_ET4000_W32P_C,
	    0,
	    "Tseng Labs",
	    "ET4000w32p rev C",
	},
	{
	    PCI_VENDOR_TSENG, PCI_PRODUCT_TSENG_ET4000_W32P_D,
	    0,
	    "Tseng Labs",
	    "ET4000w32p rev D",
	},
	{
	    PCI_VENDOR_TSENG, PCI_PRODUCT_TSENG_ET6000,
	    0,
	    "Tseng Labs",
	    "ET6000",
	},
	{
	    PCI_VENDOR_UMC, PCI_PRODUCT_UMC_UM8673F,
	    0,
	    "United Microelectronics",
	    "UM8673F",
	},
	{
	    PCI_VENDOR_UMC, PCI_PRODUCT_UMC_UM8881F,
	    0,
	    "United Microelectronics",
	    "UM8881F PCI-Host bridge",
	},
	{
	    PCI_VENDOR_UMC, PCI_PRODUCT_UMC_UM8886F,
	    0,
	    "United Microelectronics",
	    "UM8886F PCI-ISA bridge",
	},
	{
	    PCI_VENDOR_UMC, PCI_PRODUCT_UMC_UM8886A,
	    0,
	    "United Microelectronics",
	    "UM8886A",
	},
	{
	    PCI_VENDOR_UMC, PCI_PRODUCT_UMC_UM8891A,
	    0,
	    "United Microelectronics",
	    "UM8891A",
	},
	{
	    PCI_VENDOR_VIATECH, PCI_PRODUCT_VIATECH_82C505,
	    0,
	    "VIA Technologies",
	    "82C505",
	},
	{
	    PCI_VENDOR_VIATECH, PCI_PRODUCT_VIATECH_ALT_82C505,
	    0,
	    "VIA Technologies",
	    "82C505",
	},
	{
	    PCI_VENDOR_VIATECH, PCI_PRODUCT_VIATECH_82C576,
	    0,
	    "VIA Technologies",
	    "82C576 3V",
	},
	{
	    PCI_VENDOR_VORTEX, PCI_PRODUCT_VORTEX_GDT_6000B,
	    0,
	    "Vortex Computer Systems",
	    "GDT 6000b",
	},
	{
	    PCI_VENDOR_VLSI, PCI_PRODUCT_VLSI_82C592_FC1,
	    0,
	    "VLSI Technology",
	    "82C592-FC1",
	},
	{
	    PCI_VENDOR_VLSI, PCI_PRODUCT_VLSI_82C593_FC1,
	    0,
	    "VLSI Technology",
	    "82C593-FC1",
	},
	{
	    PCI_VENDOR_WEITEK, PCI_PRODUCT_WEITEK_P9000,
	    0,
	    "Weitek",
	    "P9000",
	},
	{
	    PCI_VENDOR_WEITEK, PCI_PRODUCT_WEITEK_P9100,
	    0,
	    "Weitek",
	    "P9100",
	},
	{
	    PCI_VENDOR_WINBOND, PCI_PRODUCT_WINBOND_W83769F,
	    0,
	    "Winbond Electronics",
	    "W83769F",
	},
	{
	    PCI_VENDOR_ZEINET, PCI_PRODUCT_ZEINET_1221,
	    0,
	    "Zeinet",
	    "1221",
	},
	{
	    PCI_VENDOR_CYCLADES, PCI_PRODUCT_CYCLADES_CYCLOMY_1,
	    0,
	    "Cyclades",
	    "Cyclom-Y below 1M",
	},
	{
	    PCI_VENDOR_CYCLADES, PCI_PRODUCT_CYCLADES_CYCLOMY_2,
	    0,
	    "Cyclades",
	    "Cyclom-Y above 1M",
	},
	{
	    PCI_VENDOR_CYCLADES, PCI_PRODUCT_CYCLADES_CYCLOMY_1,
	    0,
	    "Cyclades",
	    "Cyclom-Y below 1M",
	},
	{
	    PCI_VENDOR_CYCLADES, PCI_PRODUCT_CYCLADES_CYCLOMY_2,
	    0,
	    "Cyclades",
	    "Cyclom-Y above 1M",
	},
	{
	    PCI_VENDOR_OLDCOMPAQ, 0,
	    PCI_KNOWNDEV_NOPROD,
	    "Compaq",
	    NULL,
	},
	{
	    PCI_VENDOR_OLDNCR, 0,
	    PCI_KNOWNDEV_NOPROD,
	    "NCR",
	    NULL,
	},
	{
	    PCI_VENDOR_ATI, 0,
	    PCI_KNOWNDEV_NOPROD,
	    "ATI Technologies",
	    NULL,
	},
	{
	    PCI_VENDOR_ULSI, 0,
	    PCI_KNOWNDEV_NOPROD,
	    "ULSI Systems",
	    NULL,
	},
	{
	    PCI_VENDOR_VLSI, 0,
	    PCI_KNOWNDEV_NOPROD,
	    "VLSI Technology",
	    NULL,
	},
	{
	    PCI_VENDOR_AVANCE, 0,
	    PCI_KNOWNDEV_NOPROD,
	    "Avance Logic",
	    NULL,
	},
	{
	    PCI_VENDOR_REPLY, 0,
	    PCI_KNOWNDEV_NOPROD,
	    "Reply Group",
	    NULL,
	},
	{
	    PCI_VENDOR_NETFRAME, 0,
	    PCI_KNOWNDEV_NOPROD,
	    "NetFrame Systems",
	    NULL,
	},
	{
	    PCI_VENDOR_EPSON, 0,
	    PCI_KNOWNDEV_NOPROD,
	    "Epson",
	    NULL,
	},
	{
	    PCI_VENDOR_PHOENIX, 0,
	    PCI_KNOWNDEV_NOPROD,
	    "Phoenix Technologies",
	    NULL,
	},
	{
	    PCI_VENDOR_NS, 0,
	    PCI_KNOWNDEV_NOPROD,
	    "National Semiconductor",
	    NULL,
	},
	{
	    PCI_VENDOR_TSENG, 0,
	    PCI_KNOWNDEV_NOPROD,
	    "Tseng Labs",
	    NULL,
	},
	{
	    PCI_VENDOR_AST, 0,
	    PCI_KNOWNDEV_NOPROD,
	    "AST Research",
	    NULL,
	},
	{
	    PCI_VENDOR_WEITEK, 0,
	    PCI_KNOWNDEV_NOPROD,
	    "Weitek",
	    NULL,
	},
	{
	    PCI_VENDOR_VIDEOLOGIC, 0,
	    PCI_KNOWNDEV_NOPROD,
	    "Video Logic, Ltd.",
	    NULL,
	},
	{
	    PCI_VENDOR_DEC, 0,
	    PCI_KNOWNDEV_NOPROD,
	    "Digital Equipment",
	    NULL,
	},
	{
	    PCI_VENDOR_MICRONICS, 0,
	    PCI_KNOWNDEV_NOPROD,
	    "Micronics Computers",
	    NULL,
	},
	{
	    PCI_VENDOR_CIRRUS, 0,
	    PCI_KNOWNDEV_NOPROD,
	    "Cirrus Logic",
	    NULL,
	},
	{
	    PCI_VENDOR_IBM, 0,
	    PCI_KNOWNDEV_NOPROD,
	    "IBM",
	    NULL,
	},
	{
	    PCI_VENDOR_ICLPERSONAL, 0,
	    PCI_KNOWNDEV_NOPROD,
	    "ICL Personal Systems",
	    NULL,
	},
	{
	    PCI_VENDOR_SPEA, 0,
	    PCI_KNOWNDEV_NOPROD,
	    "SPEA Software",
	    NULL,
	},
	{
	    PCI_VENDOR_UNISYS, 0,
	    PCI_KNOWNDEV_NOPROD,
	    "Unisys Systems",
	    NULL,
	},
	{
	    PCI_VENDOR_ELITEGROUP, 0,
	    PCI_KNOWNDEV_NOPROD,
	    "Elitegroup Computer Systems",
	    NULL,
	},
	{
	    PCI_VENDOR_NCR, 0,
	    PCI_KNOWNDEV_NOPROD,
	    "NCR",
	    NULL,
	},
	{
	    PCI_VENDOR_VITESSE, 0,
	    PCI_KNOWNDEV_NOPROD,
	    "Vitesse Semiconductor",
	    NULL,
	},
	{
	    PCI_VENDOR_WD, 0,
	    PCI_KNOWNDEV_NOPROD,
	    "Western Digital",
	    NULL,
	},
	{
	    PCI_VENDOR_AMI, 0,
	    PCI_KNOWNDEV_NOPROD,
	    "American Megatrends",
	    NULL,
	},
	{
	    PCI_VENDOR_PICTURETEL, 0,
	    PCI_KNOWNDEV_NOPROD,
	    "PictureTel",
	    NULL,
	},
	{
	    PCI_VENDOR_HITACHICOMP, 0,
	    PCI_KNOWNDEV_NOPROD,
	    "Hitachi Computer Products",
	    NULL,
	},
	{
	    PCI_VENDOR_OKI, 0,
	    PCI_KNOWNDEV_NOPROD,
	    "OKI Electric Industry",
	    NULL,
	},
	{
	    PCI_VENDOR_AMD, 0,
	    PCI_KNOWNDEV_NOPROD,
	    "AMD",
	    NULL,
	},
	{
	    PCI_VENDOR_TRIDENT, 0,
	    PCI_KNOWNDEV_NOPROD,
	    "Trident Microsystems",
	    NULL,
	},
	{
	    PCI_VENDOR_ZENITH, 0,
	    PCI_KNOWNDEV_NOPROD,
	    "Zenith Data Systems",
	    NULL,
	},
	{
	    PCI_VENDOR_ACER, 0,
	    PCI_KNOWNDEV_NOPROD,
	    "Acer",
	    NULL,
	},
	{
	    PCI_VENDOR_DELL, 0,
	    PCI_KNOWNDEV_NOPROD,
	    "Dell Computer",
	    NULL,
	},
	{
	    PCI_VENDOR_SIEMENS, 0,
	    PCI_KNOWNDEV_NOPROD,
	    "Siemens Nixdorf IS",
	    NULL,
	},
	{
	    PCI_VENDOR_LSILOGIC, 0,
	    PCI_KNOWNDEV_NOPROD,
	    "LSI Logic, Headland div.",
	    NULL,
	},
	{
	    PCI_VENDOR_MATROX, 0,
	    PCI_KNOWNDEV_NOPROD,
	    "Matrox",
	    NULL,
	},
	{
	    PCI_VENDOR_CHIPS, 0,
	    PCI_KNOWNDEV_NOPROD,
	    "Chips and Technologies",
	    NULL,
	},
	{
	    PCI_VENDOR_WYSE, 0,
	    PCI_KNOWNDEV_NOPROD,
	    "WYSE Technology",
	    NULL,
	},
	{
	    PCI_VENDOR_OLIVETTI, 0,
	    PCI_KNOWNDEV_NOPROD,
	    "Olivetti Advanced Technology",
	    NULL,
	},
	{
	    PCI_VENDOR_TOSHIBA, 0,
	    PCI_KNOWNDEV_NOPROD,
	    "Toshiba America",
	    NULL,
	},
	{
	    PCI_VENDOR_TMCRESEARCH, 0,
	    PCI_KNOWNDEV_NOPROD,
	    "TMC Research",
	    NULL,
	},
	{
	    PCI_VENDOR_MIRO, 0,
	    PCI_KNOWNDEV_NOPROD,
	    "Miro Computer Products",
	    NULL,
	},
	{
	    PCI_VENDOR_COMPAQ, 0,
	    PCI_KNOWNDEV_NOPROD,
	    "Compaq",
	    NULL,
	},
	{
	    PCI_VENDOR_NEC, 0,
	    PCI_KNOWNDEV_NOPROD,
	    "NEC",
	    NULL,
	},
	{
	    PCI_VENDOR_BURNDY, 0,
	    PCI_KNOWNDEV_NOPROD,
	    "Burndy",
	    NULL,
	},
	{
	    PCI_VENDOR_COMPCOMM, 0,
	    PCI_KNOWNDEV_NOPROD,
	    "Comp. & Comm. Research Lab",
	    NULL,
	},
	{
	    PCI_VENDOR_FUTUREDOMAIN, 0,
	    PCI_KNOWNDEV_NOPROD,
	    "Future Domain",
	    NULL,
	},
	{
	    PCI_VENDOR_HITACHIMICRO, 0,
	    PCI_KNOWNDEV_NOPROD,
	    "Hitach Microsystems",
	    NULL,
	},
	{
	    PCI_VENDOR_AMP, 0,
	    PCI_KNOWNDEV_NOPROD,
	    "AMP",
	    NULL,
	},
	{
	    PCI_VENDOR_SIS, 0,
	    PCI_KNOWNDEV_NOPROD,
	    "Silicon Integrated System",
	    NULL,
	},
	{
	    PCI_VENDOR_SEIKOEPSON, 0,
	    PCI_KNOWNDEV_NOPROD,
	    "Seiko Epson",
	    NULL,
	},
	{
	    PCI_VENDOR_TATUNGAMERICA, 0,
	    PCI_KNOWNDEV_NOPROD,
	    "Tatung Co. of America",
	    NULL,
	},
	{
	    PCI_VENDOR_HP, 0,
	    PCI_KNOWNDEV_NOPROD,
	    "Hewlett-Packard",
	    NULL,
	},
	{
	    PCI_VENDOR_SOLLIDAY, 0,
	    PCI_KNOWNDEV_NOPROD,
	    "Solliday Engineering",
	    NULL,
	},
	{
	    PCI_VENDOR_LOGICMODELLING, 0,
	    PCI_KNOWNDEV_NOPROD,
	    "Logic Modeling",
	    NULL,
	},
	{
	    PCI_VENDOR_KPC, 0,
	    PCI_KNOWNDEV_NOPROD,
	    "Kubota Pacific",
	    NULL,
	},
	{
	    PCI_VENDOR_COMPUTREND, 0,
	    PCI_KNOWNDEV_NOPROD,
	    "Computrend",
	    NULL,
	},
	{
	    PCI_VENDOR_PCTECH, 0,
	    PCI_KNOWNDEV_NOPROD,
	    "PC Technology",
	    NULL,
	},
	{
	    PCI_VENDOR_ASUSTEK, 0,
	    PCI_KNOWNDEV_NOPROD,
	    "Asustek Computer",
	    NULL,
	},
	{
	    PCI_VENDOR_DPT, 0,
	    PCI_KNOWNDEV_NOPROD,
	    "Distributed Processing Technology",
	    NULL,
	},
	{
	    PCI_VENDOR_OPTI, 0,
	    PCI_KNOWNDEV_NOPROD,
	    "Opti",
	    NULL,
	},
	{
	    PCI_VENDOR_IPCCORP, 0,
	    PCI_KNOWNDEV_NOPROD,
	    "IPC Corporation",
	    NULL,
	},
	{
	    PCI_VENDOR_GENOA, 0,
	    PCI_KNOWNDEV_NOPROD,
	    "Genoa Systems",
	    NULL,
	},
	{
	    PCI_VENDOR_ELSA, 0,
	    PCI_KNOWNDEV_NOPROD,
	    "Elsa",
	    NULL,
	},
	{
	    PCI_VENDOR_FOUNTAINTECH, 0,
	    PCI_KNOWNDEV_NOPROD,
	    "Fountain Technology",
	    NULL,
	},
	{
	    PCI_VENDOR_SGSTHOMSON, 0,
	    PCI_KNOWNDEV_NOPROD,
	    "SGS Thomson Microelectric",
	    NULL,
	},
	{
	    PCI_VENDOR_BUSLOGIC, 0,
	    PCI_KNOWNDEV_NOPROD,
	    "BusLogic",
	    NULL,
	},
	{
	    PCI_VENDOR_TI, 0,
	    PCI_KNOWNDEV_NOPROD,
	    "Texas Instruments",
	    NULL,
	},
	{
	    PCI_VENDOR_SONY, 0,
	    PCI_KNOWNDEV_NOPROD,
	    "Sony",
	    NULL,
	},
	{
	    PCI_VENDOR_OAKTECH, 0,
	    PCI_KNOWNDEV_NOPROD,
	    "Oak Technology",
	    NULL,
	},
	{
	    PCI_VENDOR_COTIME, 0,
	    PCI_KNOWNDEV_NOPROD,
	    "Co-time Computer",
	    NULL,
	},
	{
	    PCI_VENDOR_WINBOND, 0,
	    PCI_KNOWNDEV_NOPROD,
	    "Winbond Electronics",
	    NULL,
	},
	{
	    PCI_VENDOR_ANIGMA, 0,
	    PCI_KNOWNDEV_NOPROD,
	    "Anigma",
	    NULL,
	},
	{
	    PCI_VENDOR_YOUNGMICRO, 0,
	    PCI_KNOWNDEV_NOPROD,
	    "Young Micro Systems",
	    NULL,
	},
	{
	    PCI_VENDOR_HITACHI, 0,
	    PCI_KNOWNDEV_NOPROD,
	    "Hitachi",
	    NULL,
	},
	{
	    PCI_VENDOR_EFARMICRO, 0,
	    PCI_KNOWNDEV_NOPROD,
	    "Efar Microsystems",
	    NULL,
	},
	{
	    PCI_VENDOR_ICL, 0,
	    PCI_KNOWNDEV_NOPROD,
	    "ICL",
	    NULL,
	},
	{
	    PCI_VENDOR_MOT, 0,
	    PCI_KNOWNDEV_NOPROD,
	    "Motorola",
	    NULL,
	},
	{
	    PCI_VENDOR_ETR, 0,
	    PCI_KNOWNDEV_NOPROD,
	    "Electronics & Telec. RSH",
	    NULL,
	},
	{
	    PCI_VENDOR_TEKNOR, 0,
	    PCI_KNOWNDEV_NOPROD,
	    "Teknor Microsystems",
	    NULL,
	},
	{
	    PCI_VENDOR_PROMISE, 0,
	    PCI_KNOWNDEV_NOPROD,
	    "Promise Technology",
	    NULL,
	},
	{
	    PCI_VENDOR_FOXCONN, 0,
	    PCI_KNOWNDEV_NOPROD,
	    "Foxconn International",
	    NULL,
	},
	{
	    PCI_VENDOR_WIPRO, 0,
	    PCI_KNOWNDEV_NOPROD,
	    "Wipro Infotech",
	    NULL,
	},
	{
	    PCI_VENDOR_NUMBER9, 0,
	    PCI_KNOWNDEV_NOPROD,
	    "Number 9 Computer Company",
	    NULL,
	},
	{
	    PCI_VENDOR_VTECH, 0,
	    PCI_KNOWNDEV_NOPROD,
	    "Vtech Computers",
	    NULL,
	},
	{
	    PCI_VENDOR_INFOTRONIC, 0,
	    PCI_KNOWNDEV_NOPROD,
	    "Infotronic America",
	    NULL,
	},
	{
	    PCI_VENDOR_UMC, 0,
	    PCI_KNOWNDEV_NOPROD,
	    "United Microelectronics",
	    NULL,
	},
	{
	    PCI_VENDOR_ITT, 0,
	    PCI_KNOWNDEV_NOPROD,
	    "I. T. T. (or X technology?)",
	    NULL,
	},
	{
	    PCI_VENDOR_MASPAR, 0,
	    PCI_KNOWNDEV_NOPROD,
	    "Maspar Computer",
	    NULL,
	},
	{
	    PCI_VENDOR_OCEANOA, 0,
	    PCI_KNOWNDEV_NOPROD,
	    "Ocean Office Automation",
	    NULL,
	},
	{
	    PCI_VENDOR_ALCATEL, 0,
	    PCI_KNOWNDEV_NOPROD,
	    "Alcatel CIT",
	    NULL,
	},
	{
	    PCI_VENDOR_TEXASMICRO, 0,
	    PCI_KNOWNDEV_NOPROD,
	    "Texas Microsystems",
	    NULL,
	},
	{
	    PCI_VENDOR_PICOPOWER, 0,
	    PCI_KNOWNDEV_NOPROD,
	    "Picopower Technology",
	    NULL,
	},
	{
	    PCI_VENDOR_MITSUBISHI, 0,
	    PCI_KNOWNDEV_NOPROD,
	    "Mitsubishi",
	    NULL,
	},
	{
	    PCI_VENDOR_DIVERSIFIED, 0,
	    PCI_KNOWNDEV_NOPROD,
	    "Diversified Technology",
	    NULL,
	},
	{
	    PCI_VENDOR_MYLEX, 0,
	    PCI_KNOWNDEV_NOPROD,
	    "Mylex",
	    NULL,
	},
	{
	    PCI_VENDOR_ATEN, 0,
	    PCI_KNOWNDEV_NOPROD,
	    "Aten Research",
	    NULL,
	},
	{
	    PCI_VENDOR_APPLE, 0,
	    PCI_KNOWNDEV_NOPROD,
	    "Apple",
	    NULL,
	},
	{
	    PCI_VENDOR_HYUNDAI, 0,
	    PCI_KNOWNDEV_NOPROD,
	    "Hyundai Electronics America",
	    NULL,
	},
	{
	    PCI_VENDOR_SEQUENT, 0,
	    PCI_KNOWNDEV_NOPROD,
	    "Sequent",
	    NULL,
	},
	{
	    PCI_VENDOR_DFI, 0,
	    PCI_KNOWNDEV_NOPROD,
	    "DFI",
	    NULL,
	},
	{
	    PCI_VENDOR_CITYGATE, 0,
	    PCI_KNOWNDEV_NOPROD,
	    "City Gate Development",
	    NULL,
	},
	{
	    PCI_VENDOR_DAEWOO, 0,
	    PCI_KNOWNDEV_NOPROD,
	    "Daewoo Telecom",
	    NULL,
	},
	{
	    PCI_VENDOR_MITAC, 0,
	    PCI_KNOWNDEV_NOPROD,
	    "Mitac",
	    NULL,
	},
	{
	    PCI_VENDOR_GIT, 0,
	    PCI_KNOWNDEV_NOPROD,
	    "GIT Co.",
	    NULL,
	},
	{
	    PCI_VENDOR_YAMAHA, 0,
	    PCI_KNOWNDEV_NOPROD,
	    "Yamaha",
	    NULL,
	},
	{
	    PCI_VENDOR_NEXGEN, 0,
	    PCI_KNOWNDEV_NOPROD,
	    "NexGen Microsystems",
	    NULL,
	},
	{
	    PCI_VENDOR_AIR, 0,
	    PCI_KNOWNDEV_NOPROD,
	    "Advanced Integration Research",
	    NULL,
	},
	{
	    PCI_VENDOR_CHAINTECH, 0,
	    PCI_KNOWNDEV_NOPROD,
	    "Chaintech Computer",
	    NULL,
	},
	{
	    PCI_VENDOR_QLOGIC, 0,
	    PCI_KNOWNDEV_NOPROD,
	    "Q Logic",
	    NULL,
	},
	{
	    PCI_VENDOR_CYRIX, 0,
	    PCI_KNOWNDEV_NOPROD,
	    "Cyrix Corporation",
	    NULL,
	},
	{
	    PCI_VENDOR_IBUS, 0,
	    PCI_KNOWNDEV_NOPROD,
	    "I-Bus",
	    NULL,
	},
	{
	    PCI_VENDOR_NETWORTH, 0,
	    PCI_KNOWNDEV_NOPROD,
	    "NetWorth",
	    NULL,
	},
	{
	    PCI_VENDOR_GATEWAY, 0,
	    PCI_KNOWNDEV_NOPROD,
	    "Gateway 2000",
	    NULL,
	},
	{
	    PCI_VENDOR_GOLDSTART, 0,
	    PCI_KNOWNDEV_NOPROD,
	    "Goldstar",
	    NULL,
	},
	{
	    PCI_VENDOR_LEADTEK, 0,
	    PCI_KNOWNDEV_NOPROD,
	    "LeadTek Research",
	    NULL,
	},
	{
	    PCI_VENDOR_INTERPHASE, 0,
	    PCI_KNOWNDEV_NOPROD,
	    "Interphase",
	    NULL,
	},
	{
	    PCI_VENDOR_DATATECH, 0,
	    PCI_KNOWNDEV_NOPROD,
	    "Data Technology Corporation",
	    NULL,
	},
	{
	    PCI_VENDOR_CONTAQ, 0,
	    PCI_KNOWNDEV_NOPROD,
	    "Contaq Microsystems",
	    NULL,
	},
	{
	    PCI_VENDOR_SUPERMAC, 0,
	    PCI_KNOWNDEV_NOPROD,
	    "Supermac Technology",
	    NULL,
	},
	{
	    PCI_VENDOR_EFA, 0,
	    PCI_KNOWNDEV_NOPROD,
	    "EFA Corporation of America",
	    NULL,
	},
	{
	    PCI_VENDOR_FOREX, 0,
	    PCI_KNOWNDEV_NOPROD,
	    "Forex Computer",
	    NULL,
	},
	{
	    PCI_VENDOR_PARADOR, 0,
	    PCI_KNOWNDEV_NOPROD,
	    "Parador",
	    NULL,
	},
	{
	    PCI_VENDOR_TULIP, 0,
	    PCI_KNOWNDEV_NOPROD,
	    "Tulip Computers",
	    NULL,
	},
	{
	    PCI_VENDOR_JBOND, 0,
	    PCI_KNOWNDEV_NOPROD,
	    "J. Bond Computer Systems",
	    NULL,
	},
	{
	    PCI_VENDOR_CACHECOMP, 0,
	    PCI_KNOWNDEV_NOPROD,
	    "Cache Computer",
	    NULL,
	},
	{
	    PCI_VENDOR_MICROCOMP, 0,
	    PCI_KNOWNDEV_NOPROD,
	    "Microcomputer Systems",
	    NULL,
	},
	{
	    PCI_VENDOR_DG, 0,
	    PCI_KNOWNDEV_NOPROD,
	    "Data General Corporation",
	    NULL,
	},
	{
	    PCI_VENDOR_BIT3, 0,
	    PCI_KNOWNDEV_NOPROD,
	    "Bit3 Computer Corp.",
	    NULL,
	},
	{
	    PCI_VENDOR_OAKLEIGH, 0,
	    PCI_KNOWNDEV_NOPROD,
	    "Oakleigh Systems",
	    NULL,
	},
	{
	    PCI_VENDOR_OLICOM, 0,
	    PCI_KNOWNDEV_NOPROD,
	    "Olicom",
	    NULL,
	},
	{
	    PCI_VENDOR_SYSTEMSOFT, 0,
	    PCI_KNOWNDEV_NOPROD,
	    "Systemsoft",
	    NULL,
	},
	{
	    PCI_VENDOR_ENCORE, 0,
	    PCI_KNOWNDEV_NOPROD,
	    "Encore Computer",
	    NULL,
	},
	{
	    PCI_VENDOR_INTERGRAPH, 0,
	    PCI_KNOWNDEV_NOPROD,
	    "Intergraph",
	    NULL,
	},
	{
	    PCI_VENDOR_DIAMOND, 0,
	    PCI_KNOWNDEV_NOPROD,
	    "Diamond Computer Systems",
	    NULL,
	},
	{
	    PCI_VENDOR_NATIONALINST, 0,
	    PCI_KNOWNDEV_NOPROD,
	    "National Instruments",
	    NULL,
	},
	{
	    PCI_VENDOR_FICOMP, 0,
	    PCI_KNOWNDEV_NOPROD,
	    "First Int'l Computers",
	    NULL,
	},
	{
	    PCI_VENDOR_CMDTECH, 0,
	    PCI_KNOWNDEV_NOPROD,
	    "CMD Technology",
	    NULL,
	},
	{
	    PCI_VENDOR_ALACRON, 0,
	    PCI_KNOWNDEV_NOPROD,
	    "Alacron",
	    NULL,
	},
	{
	    PCI_VENDOR_APPIAN, 0,
	    PCI_KNOWNDEV_NOPROD,
	    "Appian Technology",
	    NULL,
	},
	{
	    PCI_VENDOR_QUANTUMDESIGNS, 0,
	    PCI_KNOWNDEV_NOPROD,
	    "Quantum Designs (or Vision?)",
	    NULL,
	},
	{
	    PCI_VENDOR_SAMSUNGELEC, 0,
	    PCI_KNOWNDEV_NOPROD,
	    "Samsung Electronics",
	    NULL,
	},
	{
	    PCI_VENDOR_PACKARDBELL, 0,
	    PCI_KNOWNDEV_NOPROD,
	    "Packard Bell",
	    NULL,
	},
	{
	    PCI_VENDOR_GEMLIGHT, 0,
	    PCI_KNOWNDEV_NOPROD,
	    "Gemlight Computer",
	    NULL,
	},
	{
	    PCI_VENDOR_MEGACHIPS, 0,
	    PCI_KNOWNDEV_NOPROD,
	    "Megachips",
	    NULL,
	},
	{
	    PCI_VENDOR_ZIDA, 0,
	    PCI_KNOWNDEV_NOPROD,
	    "Zida Technologies",
	    NULL,
	},
	{
	    PCI_VENDOR_BROOKTREE, 0,
	    PCI_KNOWNDEV_NOPROD,
	    "Brooktree",
	    NULL,
	},
	{
	    PCI_VENDOR_TRIGEM, 0,
	    PCI_KNOWNDEV_NOPROD,
	    "Trigem Computer",
	    NULL,
	},
	{
	    PCI_VENDOR_MEIDENSHA, 0,
	    PCI_KNOWNDEV_NOPROD,
	    "Meidensha",
	    NULL,
	},
	{
	    PCI_VENDOR_JUKO, 0,
	    PCI_KNOWNDEV_NOPROD,
	    "Juko Electronics",
	    NULL,
	},
	{
	    PCI_VENDOR_QUANTUM, 0,
	    PCI_KNOWNDEV_NOPROD,
	    "Quantum",
	    NULL,
	},
	{
	    PCI_VENDOR_EVEREX, 0,
	    PCI_KNOWNDEV_NOPROD,
	    "Everex Systems",
	    NULL,
	},
	{
	    PCI_VENDOR_GLOBE, 0,
	    PCI_KNOWNDEV_NOPROD,
	    "Globe Manufacturing Sales",
	    NULL,
	},
	{
	    PCI_VENDOR_RACAL, 0,
	    PCI_KNOWNDEV_NOPROD,
	    "Racal Interlan",
	    NULL,
	},
	{
	    PCI_VENDOR_INFORMTECH, 0,
	    PCI_KNOWNDEV_NOPROD,
	    "Informtech Industrial",
	    NULL,
	},
	{
	    PCI_VENDOR_BENCHMARQ, 0,
	    PCI_KNOWNDEV_NOPROD,
	    "Benchmarq Microelectronics",
	    NULL,
	},
	{
	    PCI_VENDOR_SIERRA, 0,
	    PCI_KNOWNDEV_NOPROD,
	    "Sierra Semiconductor",
	    NULL,
	},
	{
	    PCI_VENDOR_SGI, 0,
	    PCI_KNOWNDEV_NOPROD,
	    "Silicon Graphics",
	    NULL,
	},
	{
	    PCI_VENDOR_ACC, 0,
	    PCI_KNOWNDEV_NOPROD,
	    "ACC Microelectronics",
	    NULL,
	},
	{
	    PCI_VENDOR_DIGICOM, 0,
	    PCI_KNOWNDEV_NOPROD,
	    "Digicom",
	    NULL,
	},
	{
	    PCI_VENDOR_HONEYWELL, 0,
	    PCI_KNOWNDEV_NOPROD,
	    "Honeywell IASD",
	    NULL,
	},
	{
	    PCI_VENDOR_CORNERSTONE, 0,
	    PCI_KNOWNDEV_NOPROD,
	    "Cornerstone Technology",
	    NULL,
	},
	{
	    PCI_VENDOR_MICROCOMPSON, 0,
	    PCI_KNOWNDEV_NOPROD,
	    "Micro Computer Sysytems (M) SON",
	    NULL,
	},
	{
	    PCI_VENDOR_CARDEXPER, 0,
	    PCI_KNOWNDEV_NOPROD,
	    "CardExpert Technology",
	    NULL,
	},
	{
	    PCI_VENDOR_CABLETRON, 0,
	    PCI_KNOWNDEV_NOPROD,
	    "Cabletron Systems",
	    NULL,
	},
	{
	    PCI_VENDOR_RAYETHON, 0,
	    PCI_KNOWNDEV_NOPROD,
	    "Raytheon",
	    NULL,
	},
	{
	    PCI_VENDOR_DATABOOK, 0,
	    PCI_KNOWNDEV_NOPROD,
	    "Databook",
	    NULL,
	},
	{
	    PCI_VENDOR_STB, 0,
	    PCI_KNOWNDEV_NOPROD,
	    "STB Systems",
	    NULL,
	},
	{
	    PCI_VENDOR_PLX, 0,
	    PCI_KNOWNDEV_NOPROD,
	    "PLX Technology",
	    NULL,
	},
	{
	    PCI_VENDOR_MADGE, 0,
	    PCI_KNOWNDEV_NOPROD,
	    "Madge Networks",
	    NULL,
	},
	{
	    PCI_VENDOR_3COM, 0,
	    PCI_KNOWNDEV_NOPROD,
	    "3Com",
	    NULL,
	},
	{
	    PCI_VENDOR_SMC, 0,
	    PCI_KNOWNDEV_NOPROD,
	    "Standard Microsystems",
	    NULL,
	},
	{
	    PCI_VENDOR_ALI, 0,
	    PCI_KNOWNDEV_NOPROD,
	    "Acer Labs",
	    NULL,
	},
	{
	    PCI_VENDOR_MITSUBISHIELEC, 0,
	    PCI_KNOWNDEV_NOPROD,
	    "Mitsubishi Electronics",
	    NULL,
	},
	{
	    PCI_VENDOR_DAPHA, 0,
	    PCI_KNOWNDEV_NOPROD,
	    "Dapha Electronics",
	    NULL,
	},
	{
	    PCI_VENDOR_ALR, 0,
	    PCI_KNOWNDEV_NOPROD,
	    "Advanced Logic Research",
	    NULL,
	},
	{
	    PCI_VENDOR_SURECOM, 0,
	    PCI_KNOWNDEV_NOPROD,
	    "Surecom Technology",
	    NULL,
	},
	{
	    PCI_VENDOR_TSENGLABS, 0,
	    PCI_KNOWNDEV_NOPROD,
	    "Tseng Labs International",
	    NULL,
	},
	{
	    PCI_VENDOR_MOST, 0,
	    PCI_KNOWNDEV_NOPROD,
	    "Most",
	    NULL,
	},
	{
	    PCI_VENDOR_BOCA, 0,
	    PCI_KNOWNDEV_NOPROD,
	    "Boca Research",
	    NULL,
	},
	{
	    PCI_VENDOR_ICM, 0,
	    PCI_KNOWNDEV_NOPROD,
	    "ICM",
	    NULL,
	},
	{
	    PCI_VENDOR_AUSPEX, 0,
	    PCI_KNOWNDEV_NOPROD,
	    "Auspex Systems",
	    NULL,
	},
	{
	    PCI_VENDOR_SAMSUNGSEMI, 0,
	    PCI_KNOWNDEV_NOPROD,
	    "Samsung Semiconductors",
	    NULL,
	},
	{
	    PCI_VENDOR_AWARD, 0,
	    PCI_KNOWNDEV_NOPROD,
	    "Award Software Int'l",
	    NULL,
	},
	{
	    PCI_VENDOR_XEROX, 0,
	    PCI_KNOWNDEV_NOPROD,
	    "Xerox",
	    NULL,
	},
	{
	    PCI_VENDOR_RAMBUS, 0,
	    PCI_KNOWNDEV_NOPROD,
	    "Rambus",
	    NULL,
	},
	{
	    PCI_VENDOR_MEDIAVIS, 0,
	    PCI_KNOWNDEV_NOPROD,
	    "Media Vision",
	    NULL,
	},
	{
	    PCI_VENDOR_NEOMAGIC, 0,
	    PCI_KNOWNDEV_NOPROD,
	    "Neomagic",
	    NULL,
	},
	{
	    PCI_VENDOR_DATAEXPERT, 0,
	    PCI_KNOWNDEV_NOPROD,
	    "Dataexpert",
	    NULL,
	},
	{
	    PCI_VENDOR_FUJITSU, 0,
	    PCI_KNOWNDEV_NOPROD,
	    "Fujitsu",
	    NULL,
	},
	{
	    PCI_VENDOR_OMRON, 0,
	    PCI_KNOWNDEV_NOPROD,
	    "Omron",
	    NULL,
	},
	{
	    PCI_VENDOR_MENTOR, 0,
	    PCI_KNOWNDEV_NOPROD,
	    "Mentor ARC",
	    NULL,
	},
	{
	    PCI_VENDOR_ADVSYSPROD, 0,
	    PCI_KNOWNDEV_NOPROD,
	    "Advanced System Products",
	    NULL,
	},
	{
	    PCI_VENDOR_RADIUS, 0,
	    PCI_KNOWNDEV_NOPROD,
	    "Radius",
	    NULL,
	},
	{
	    PCI_VENDOR_CITICORP, 0,
	    PCI_KNOWNDEV_NOPROD,
	    "Citicorp TTI",
	    NULL,
	},
	{
	    PCI_VENDOR_FUJUTSU, 0,
	    PCI_KNOWNDEV_NOPROD,
	    "Fujitsu Limited",
	    NULL,
	},
	{
	    PCI_VENDOR_FUTUREPLUS, 0,
	    PCI_KNOWNDEV_NOPROD,
	    "Future+ Systems",
	    NULL,
	},
	{
	    PCI_VENDOR_MOLEX, 0,
	    PCI_KNOWNDEV_NOPROD,
	    "Molex",
	    NULL,
	},
	{
	    PCI_VENDOR_JABIL, 0,
	    PCI_KNOWNDEV_NOPROD,
	    "Jabil Circuit",
	    NULL,
	},
	{
	    PCI_VENDOR_HAULON, 0,
	    PCI_KNOWNDEV_NOPROD,
	    "Hualon Microelectronics",
	    NULL,
	},
	{
	    PCI_VENDOR_AUTOLOGIC, 0,
	    PCI_KNOWNDEV_NOPROD,
	    "Autologic",
	    NULL,
	},
	{
	    PCI_VENDOR_CETIA, 0,
	    PCI_KNOWNDEV_NOPROD,
	    "Cetia",
	    NULL,
	},
	{
	    PCI_VENDOR_BCM, 0,
	    PCI_KNOWNDEV_NOPROD,
	    "BCM Advanced",
	    NULL,
	},
	{
	    PCI_VENDOR_APL, 0,
	    PCI_KNOWNDEV_NOPROD,
	    "Advanced Peripherals Labs",
	    NULL,
	},
	{
	    PCI_VENDOR_MACRONIX, 0,
	    PCI_KNOWNDEV_NOPROD,
	    "Macronix",
	    NULL,
	},
	{
	    PCI_VENDOR_THOMASCONRAD, 0,
	    PCI_KNOWNDEV_NOPROD,
	    "Thomas-Conrad",
	    NULL,
	},
	{
	    PCI_VENDOR_ROHM, 0,
	    PCI_KNOWNDEV_NOPROD,
	    "Rohm Research",
	    NULL,
	},
	{
	    PCI_VENDOR_CERN, 0,
	    PCI_KNOWNDEV_NOPROD,
	    "CERN/ECP/EDU",
	    NULL,
	},
	{
	    PCI_VENDOR_ES, 0,
	    PCI_KNOWNDEV_NOPROD,
	    "Evans & Sutherland",
	    NULL,
	},
	{
	    PCI_VENDOR_NVIDIA, 0,
	    PCI_KNOWNDEV_NOPROD,
	    "Nvidia Corporation",
	    NULL,
	},
	{
	    PCI_VENDOR_EMULEX, 0,
	    PCI_KNOWNDEV_NOPROD,
	    "Emulex",
	    NULL,
	},
	{
	    PCI_VENDOR_IMS, 0,
	    PCI_KNOWNDEV_NOPROD,
	    "Integrated Micro Solutions",
	    NULL,
	},
	{
	    PCI_VENDOR_APTIX, 0,
	    PCI_KNOWNDEV_NOPROD,
	    "Aptix Corporation",
	    NULL,
	},
	{
	    PCI_VENDOR_NEWBRIDGE, 0,
	    PCI_KNOWNDEV_NOPROD,
	    "Newbridge Microsystems",
	    NULL,
	},
	{
	    PCI_VENDOR_TANDEM, 0,
	    PCI_KNOWNDEV_NOPROD,
	    "Tandem Computers",
	    NULL,
	},
	{
	    PCI_VENDOR_MICROINDUSTRIES, 0,
	    PCI_KNOWNDEV_NOPROD,
	    "Micro Industries",
	    NULL,
	},
	{
	    PCI_VENDOR_GAINBERY, 0,
	    PCI_KNOWNDEV_NOPROD,
	    "Gainbery Computer Products",
	    NULL,
	},
	{
	    PCI_VENDOR_VADEM, 0,
	    PCI_KNOWNDEV_NOPROD,
	    "Vadem",
	    NULL,
	},
	{
	    PCI_VENDOR_AMCIRCUITS, 0,
	    PCI_KNOWNDEV_NOPROD,
	    "Applied Micro Circuits",
	    NULL,
	},
	{
	    PCI_VENDOR_ALPSELECTIC, 0,
	    PCI_KNOWNDEV_NOPROD,
	    "Alps Electric",
	    NULL,
	},
	{
	    PCI_VENDOR_INTERGRAPHICS, 0,
	    PCI_KNOWNDEV_NOPROD,
	    "Integraphics Systems",
	    NULL,
	},
	{
	    PCI_VENDOR_ARTISTSGRAPHICS, 0,
	    PCI_KNOWNDEV_NOPROD,
	    "Artists Graphics",
	    NULL,
	},
	{
	    PCI_VENDOR_REALTEK, 0,
	    PCI_KNOWNDEV_NOPROD,
	    "Realtek Semiconductor",
	    NULL,
	},
	{
	    PCI_VENDOR_ASCIICORP, 0,
	    PCI_KNOWNDEV_NOPROD,
	    "ASCII Corporation",
	    NULL,
	},
	{
	    PCI_VENDOR_XILINX, 0,
	    PCI_KNOWNDEV_NOPROD,
	    "Xilinx",
	    NULL,
	},
	{
	    PCI_VENDOR_RACORE, 0,
	    PCI_KNOWNDEV_NOPROD,
	    "Racore Computer Products",
	    NULL,
	},
	{
	    PCI_VENDOR_PERITEK, 0,
	    PCI_KNOWNDEV_NOPROD,
	    "Peritek",
	    NULL,
	},
	{
	    PCI_VENDOR_TYAN, 0,
	    PCI_KNOWNDEV_NOPROD,
	    "Tyan Computer",
	    NULL,
	},
	{
	    PCI_VENDOR_ACHME, 0,
	    PCI_KNOWNDEV_NOPROD,
	    "Achme Computer",
	    NULL,
	},
	{
	    PCI_VENDOR_ALARIS, 0,
	    PCI_KNOWNDEV_NOPROD,
	    "Alaris",
	    NULL,
	},
	{
	    PCI_VENDOR_SMOS, 0,
	    PCI_KNOWNDEV_NOPROD,
	    "S-MOS Systems",
	    NULL,
	},
	{
	    PCI_VENDOR_MKK, 0,
	    PCI_KNOWNDEV_NOPROD,
	    "NKK Corporation",
	    NULL,
	},
	{
	    PCI_VENDOR_CREATIVE, 0,
	    PCI_KNOWNDEV_NOPROD,
	    "Creative Electronic Systems",
	    NULL,
	},
	{
	    PCI_VENDOR_MATSUSHITA, 0,
	    PCI_KNOWNDEV_NOPROD,
	    "Matsushita",
	    NULL,
	},
	{
	    PCI_VENDOR_ALTOS, 0,
	    PCI_KNOWNDEV_NOPROD,
	    "Altos India",
	    NULL,
	},
	{
	    PCI_VENDOR_PCDIRECT, 0,
	    PCI_KNOWNDEV_NOPROD,
	    "PC Direct",
	    NULL,
	},
	{
	    PCI_VENDOR_TRUEVISIO, 0,
	    PCI_KNOWNDEV_NOPROD,
	    "Truevision",
	    NULL,
	},
	{
	    PCI_VENDOR_THESYS, 0,
	    PCI_KNOWNDEV_NOPROD,
	    "Thesys Ges. F. Mikroelektronik",
	    NULL,
	},
	{
	    PCI_VENDOR_IODATA, 0,
	    PCI_KNOWNDEV_NOPROD,
	    "I-O Data Device",
	    NULL,
	},
	{
	    PCI_VENDOR_SOYO, 0,
	    PCI_KNOWNDEV_NOPROD,
	    "Soyo Technology",
	    NULL,
	},
	{
	    PCI_VENDOR_FAST, 0,
	    PCI_KNOWNDEV_NOPROD,
	    "Fast Electronic",
	    NULL,
	},
	{
	    PCI_VENDOR_NCUBE, 0,
	    PCI_KNOWNDEV_NOPROD,
	    "NCube",
	    NULL,
	},
	{
	    PCI_VENDOR_JAZZ, 0,
	    PCI_KNOWNDEV_NOPROD,
	    "Jazz Multimedia",
	    NULL,
	},
	{
	    PCI_VENDOR_INITIO, 0,
	    PCI_KNOWNDEV_NOPROD,
	    "Initio",
	    NULL,
	},
	{
	    PCI_VENDOR_CREATIVELABS, 0,
	    PCI_KNOWNDEV_NOPROD,
	    "Creative Labs",
	    NULL,
	},
	{
	    PCI_VENDOR_TRIONES, 0,
	    PCI_KNOWNDEV_NOPROD,
	    "Triones Technologies",
	    NULL,
	},
	{
	    PCI_VENDOR_RASTEROPS, 0,
	    PCI_KNOWNDEV_NOPROD,
	    "RasterOps",
	    NULL,
	},
	{
	    PCI_VENDOR_SIGMA, 0,
	    PCI_KNOWNDEV_NOPROD,
	    "Sigma Designs",
	    NULL,
	},
	{
	    PCI_VENDOR_VIATECH, 0,
	    PCI_KNOWNDEV_NOPROD,
	    "VIA Technologies",
	    NULL,
	},
	{
	    PCI_VENDOR_STRATIS, 0,
	    PCI_KNOWNDEV_NOPROD,
	    "Stratus Computer",
	    NULL,
	},
	{
	    PCI_VENDOR_PROTEON, 0,
	    PCI_KNOWNDEV_NOPROD,
	    "Proteon",
	    NULL,
	},
	{
	    PCI_VENDOR_COGENT, 0,
	    PCI_KNOWNDEV_NOPROD,
	    "Cogent Data Technologies",
	    NULL,
	},
	{
	    PCI_VENDOR_XENON, 0,
	    PCI_KNOWNDEV_NOPROD,
	    "Xenon Microsystems",
	    NULL,
	},
	{
	    PCI_VENDOR_MINIMAX, 0,
	    PCI_KNOWNDEV_NOPROD,
	    "Mini-Max Technology",
	    NULL,
	},
	{
	    PCI_VENDOR_ZNYX, 0,
	    PCI_KNOWNDEV_NOPROD,
	    "Znyx Advanced Systems",
	    NULL,
	},
	{
	    PCI_VENDOR_CPUTECH, 0,
	    PCI_KNOWNDEV_NOPROD,
	    "CPU Technology",
	    NULL,
	},
	{
	    PCI_VENDOR_ROSS, 0,
	    PCI_KNOWNDEV_NOPROD,
	    "Ross Technology",
	    NULL,
	},
	{
	    PCI_VENDOR_POWERHOUSE, 0,
	    PCI_KNOWNDEV_NOPROD,
	    "Powerhouse Systems",
	    NULL,
	},
	{
	    PCI_VENDOR_SCO, 0,
	    PCI_KNOWNDEV_NOPROD,
	    "Santa Cruz Operation",
	    NULL,
	},
	{
	    PCI_VENDOR_ROCKWELL, 0,
	    PCI_KNOWNDEV_NOPROD,
	    "Rockwell Network Systems",
	    NULL,
	},
	{
	    PCI_VENDOR_ACCTON, 0,
	    PCI_KNOWNDEV_NOPROD,
	    "Accton Technology",
	    NULL,
	},
	{
	    PCI_VENDOR_ATMEL, 0,
	    PCI_KNOWNDEV_NOPROD,
	    "Atmel",
	    NULL,
	},
	{
	    PCI_VENDOR_3DLABS, 0,
	    PCI_KNOWNDEV_NOPROD,
	    "3D Labs",
	    NULL,
	},
	{
	    PCI_VENDOR_DATATRANSLATION, 0,
	    PCI_KNOWNDEV_NOPROD,
	    "Data Translation",
	    NULL,
	},
	{
	    PCI_VENDOR_DATACUBE, 0,
	    PCI_KNOWNDEV_NOPROD,
	    "Datacube",
	    NULL,
	},
	{
	    PCI_VENDOR_BERG, 0,
	    PCI_KNOWNDEV_NOPROD,
	    "Berg Electronics",
	    NULL,
	},
	{
	    PCI_VENDOR_VORTEX, 0,
	    PCI_KNOWNDEV_NOPROD,
	    "Vortex Computer Systems",
	    NULL,
	},
	{
	    PCI_VENDOR_EFFICIENTNETS, 0,
	    PCI_KNOWNDEV_NOPROD,
	    "Efficent Networks",
	    NULL,
	},
	{
	    PCI_VENDOR_TELEDYNE, 0,
	    PCI_KNOWNDEV_NOPROD,
	    "Teledyne Electronic Systems",
	    NULL,
	},
	{
	    PCI_VENDOR_TRICORD, 0,
	    PCI_KNOWNDEV_NOPROD,
	    "Tricord Systems",
	    NULL,
	},
	{
	    PCI_VENDOR_IDT, 0,
	    PCI_KNOWNDEV_NOPROD,
	    "IDT",
	    NULL,
	},
	{
	    PCI_VENDOR_ELDEC, 0,
	    PCI_KNOWNDEV_NOPROD,
	    "Eldec",
	    NULL,
	},
	{
	    PCI_VENDOR_PDI, 0,
	    PCI_KNOWNDEV_NOPROD,
	    "Prescision Digital Images",
	    NULL,
	},
	{
	    PCI_VENDOR_EMC, 0,
	    PCI_KNOWNDEV_NOPROD,
	    "Emc",
	    NULL,
	},
	{
	    PCI_VENDOR_ZILOG, 0,
	    PCI_KNOWNDEV_NOPROD,
	    "Zilog",
	    NULL,
	},
	{
	    PCI_VENDOR_MULTITECH, 0,
	    PCI_KNOWNDEV_NOPROD,
	    "Multi-tech Systems",
	    NULL,
	},
	{
	    PCI_VENDOR_LEUTRON, 0,
	    PCI_KNOWNDEV_NOPROD,
	    "Leutron Vision",
	    NULL,
	},
	{
	    PCI_VENDOR_EUROCORE, 0,
	    PCI_KNOWNDEV_NOPROD,
	    "Eurocore",
	    NULL,
	},
	{
	    PCI_VENDOR_VIGRA, 0,
	    PCI_KNOWNDEV_NOPROD,
	    "Vigra",
	    NULL,
	},
	{
	    PCI_VENDOR_FORE, 0,
	    PCI_KNOWNDEV_NOPROD,
	    "FORE Systems",
	    NULL,
	},
	{
	    PCI_VENDOR_FIRMWORKS, 0,
	    PCI_KNOWNDEV_NOPROD,
	    "Firmworks",
	    NULL,
	},
	{
	    PCI_VENDOR_HERMES, 0,
	    PCI_KNOWNDEV_NOPROD,
	    "Hermes Electronics",
	    NULL,
	},
	{
	    PCI_VENDOR_LINOTYPE, 0,
	    PCI_KNOWNDEV_NOPROD,
	    "Linotype",
	    NULL,
	},
	{
	    PCI_VENDOR_RAVICAD, 0,
	    PCI_KNOWNDEV_NOPROD,
	    "Ravicad",
	    NULL,
	},
	{
	    PCI_VENDOR_INFOMEDIA, 0,
	    PCI_KNOWNDEV_NOPROD,
	    "Infomedia Microelectronics",
	    NULL,
	},
	{
	    PCI_VENDOR_IMAGINGTECH, 0,
	    PCI_KNOWNDEV_NOPROD,
	    "Imaging Technlogy",
	    NULL,
	},
	{
	    PCI_VENDOR_COMPUTERVISION, 0,
	    PCI_KNOWNDEV_NOPROD,
	    "Computervision",
	    NULL,
	},
	{
	    PCI_VENDOR_PHILIPS, 0,
	    PCI_KNOWNDEV_NOPROD,
	    "Philips",
	    NULL,
	},
	{
	    PCI_VENDOR_MITEL, 0,
	    PCI_KNOWNDEV_NOPROD,
	    "Mitel",
	    NULL,
	},
	{
	    PCI_VENDOR_EICON, 0,
	    PCI_KNOWNDEV_NOPROD,
	    "Eicon Technology",
	    NULL,
	},
	{
	    PCI_VENDOR_MCS, 0,
	    PCI_KNOWNDEV_NOPROD,
	    "Mercury Computer Systems",
	    NULL,
	},
	{
	    PCI_VENDOR_FUJIXEROX, 0,
	    PCI_KNOWNDEV_NOPROD,
	    "Fuji Xerox",
	    NULL,
	},
	{
	    PCI_VENDOR_MOMENTUM, 0,
	    PCI_KNOWNDEV_NOPROD,
	    "Momentum Data Systems",
	    NULL,
	},
	{
	    PCI_VENDOR_CISCO, 0,
	    PCI_KNOWNDEV_NOPROD,
	    "Cisco Systems",
	    NULL,
	},
	{
	    PCI_VENDOR_ZIATECH, 0,
	    PCI_KNOWNDEV_NOPROD,
	    "Ziatech",
	    NULL,
	},
	{
	    PCI_VENDOR_DYNPIC, 0,
	    PCI_KNOWNDEV_NOPROD,
	    "Dynamic Pictures",
	    NULL,
	},
	{
	    PCI_VENDOR_FWB, 0,
	    PCI_KNOWNDEV_NOPROD,
	    "FWB",
	    NULL,
	},
	{
	    PCI_VENDOR_CYCLONE, 0,
	    PCI_KNOWNDEV_NOPROD,
	    "Cyclone Micro",
	    NULL,
	},
	{
	    PCI_VENDOR_LEADINGEDGE, 0,
	    PCI_KNOWNDEV_NOPROD,
	    "Leading Edge",
	    NULL,
	},
	{
	    PCI_VENDOR_SANYO, 0,
	    PCI_KNOWNDEV_NOPROD,
	    "Sanyo Electric",
	    NULL,
	},
	{
	    PCI_VENDOR_EQUINOX, 0,
	    PCI_KNOWNDEV_NOPROD,
	    "Equinox Systems",
	    NULL,
	},
	{
	    PCI_VENDOR_INTERVOICE, 0,
	    PCI_KNOWNDEV_NOPROD,
	    "Intervoice",
	    NULL,
	},
	{
	    PCI_VENDOR_CREST, 0,
	    PCI_KNOWNDEV_NOPROD,
	    "Crest Microsystem",
	    NULL,
	},
	{
	    PCI_VENDOR_ALLIANCE, 0,
	    PCI_KNOWNDEV_NOPROD,
	    "Alliance Semiconductor",
	    NULL,
	},
	{
	    PCI_VENDOR_NETPOWER, 0,
	    PCI_KNOWNDEV_NOPROD,
	    "NetPower",
	    NULL,
	},
	{
	    PCI_VENDOR_CINMILACRON, 0,
	    PCI_KNOWNDEV_NOPROD,
	    "Cincinnati Milacron",
	    NULL,
	},
	{
	    PCI_VENDOR_WORKBIT, 0,
	    PCI_KNOWNDEV_NOPROD,
	    "Workbit",
	    NULL,
	},
	{
	    PCI_VENDOR_FORCE, 0,
	    PCI_KNOWNDEV_NOPROD,
	    "Force Computers",
	    NULL,
	},
	{
	    PCI_VENDOR_INTERFACE, 0,
	    PCI_KNOWNDEV_NOPROD,
	    "Interface",
	    NULL,
	},
	{
	    PCI_VENDOR_SCHNEIDERKOCH, 0,
	    PCI_KNOWNDEV_NOPROD,
	    "Schneider & Koch",
	    NULL,
	},
	{
	    PCI_VENDOR_WINSYSTEM, 0,
	    PCI_KNOWNDEV_NOPROD,
	    "Win System",
	    NULL,
	},
	{
	    PCI_VENDOR_VMIC, 0,
	    PCI_KNOWNDEV_NOPROD,
	    "VMIC",
	    NULL,
	},
	{
	    PCI_VENDOR_CANOPUS, 0,
	    PCI_KNOWNDEV_NOPROD,
	    "Canopus",
	    NULL,
	},
	{
	    PCI_VENDOR_ANNABOOKS, 0,
	    PCI_KNOWNDEV_NOPROD,
	    "Annabooks",
	    NULL,
	},
	{
	    PCI_VENDOR_IC, 0,
	    PCI_KNOWNDEV_NOPROD,
	    "IC Corporation",
	    NULL,
	},
	{
	    PCI_VENDOR_NIKON, 0,
	    PCI_KNOWNDEV_NOPROD,
	    "Nikon Systems",
	    NULL,
	},
	{
	    PCI_VENDOR_DIGIINTERNAT, 0,
	    PCI_KNOWNDEV_NOPROD,
	    "Digi International",
	    NULL,
	},
	{
	    PCI_VENDOR_TMC, 0,
	    PCI_KNOWNDEV_NOPROD,
	    "Thinking Machines",
	    NULL,
	},
	{
	    PCI_VENDOR_JAE, 0,
	    PCI_KNOWNDEV_NOPROD,
	    "JAE Electronics",
	    NULL,
	},
	{
	    PCI_VENDOR_MEGATEK, 0,
	    PCI_KNOWNDEV_NOPROD,
	    "Megatek",
	    NULL,
	},
	{
	    PCI_VENDOR_LANDWIN, 0,
	    PCI_KNOWNDEV_NOPROD,
	    "Land Win Electronic",
	    NULL,
	},
	{
	    PCI_VENDOR_MELCO, 0,
	    PCI_KNOWNDEV_NOPROD,
	    "Melco",
	    NULL,
	},
	{
	    PCI_VENDOR_PINETECH, 0,
	    PCI_KNOWNDEV_NOPROD,
	    "Pine Technology",
	    NULL,
	},
	{
	    PCI_VENDOR_PERISCOPE, 0,
	    PCI_KNOWNDEV_NOPROD,
	    "Periscope Engineering",
	    NULL,
	},
	{
	    PCI_VENDOR_AVSYS, 0,
	    PCI_KNOWNDEV_NOPROD,
	    "Avsys",
	    NULL,
	},
	{
	    PCI_VENDOR_VOARX, 0,
	    PCI_KNOWNDEV_NOPROD,
	    "Voarx R & D",
	    NULL,
	},
	{
	    PCI_VENDOR_MUTECH, 0,
	    PCI_KNOWNDEV_NOPROD,
	    "Mutech",
	    NULL,
	},
	{
	    PCI_VENDOR_HARLEQUIN, 0,
	    PCI_KNOWNDEV_NOPROD,
	    "Harlequin",
	    NULL,
	},
	{
	    PCI_VENDOR_PARALLAX, 0,
	    PCI_KNOWNDEV_NOPROD,
	    "Parallax Graphics",
	    NULL,
	},
	{
	    PCI_VENDOR_XIRCOM, 0,
	    PCI_KNOWNDEV_NOPROD,
	    "Xircom",
	    NULL,
	},
	{
	    PCI_VENDOR_PEERPROTO, 0,
	    PCI_KNOWNDEV_NOPROD,
	    "Peer Protocols",
	    NULL,
	},
	{
	    PCI_VENDOR_MAXTOR, 0,
	    PCI_KNOWNDEV_NOPROD,
	    "Maxtor",
	    NULL,
	},
	{
	    PCI_VENDOR_MEGASOFT, 0,
	    PCI_KNOWNDEV_NOPROD,
	    "Megasoft",
	    NULL,
	},
	{
	    PCI_VENDOR_PFU, 0,
	    PCI_KNOWNDEV_NOPROD,
	    "PFU Limited",
	    NULL,
	},
	{
	    PCI_VENDOR_OALAB, 0,
	    PCI_KNOWNDEV_NOPROD,
	    "OA Laboratory",
	    NULL,
	},
	{
	    PCI_VENDOR_SYNEMA, 0,
	    PCI_KNOWNDEV_NOPROD,
	    "Synema Corporation",
	    NULL,
	},
	{
	    PCI_VENDOR_APT, 0,
	    PCI_KNOWNDEV_NOPROD,
	    "Advanced Peripherals Technologies",
	    NULL,
	},
	{
	    PCI_VENDOR_IMAGRAPH, 0,
	    PCI_KNOWNDEV_NOPROD,
	    "Imagraph",
	    NULL,
	},
	{
	    PCI_VENDOR_PEQUR, 0,
	    PCI_KNOWNDEV_NOPROD,
	    "Pequr Technology",
	    NULL,
	},
	{
	    PCI_VENDOR_MUTOH, 0,
	    PCI_KNOWNDEV_NOPROD,
	    "Mutoh Industries",
	    NULL,
	},
	{
	    PCI_VENDOR_THINE, 0,
	    PCI_KNOWNDEV_NOPROD,
	    "Thine Electronics",
	    NULL,
	},
	{
	    PCI_VENDOR_CDAC, 0,
	    PCI_KNOWNDEV_NOPROD,
	    "Centre for Dev. of Advanced Computing",
	    NULL,
	},
	{
	    PCI_VENDOR_POLARIS, 0,
	    PCI_KNOWNDEV_NOPROD,
	    "Polaris Communications",
	    NULL,
	},
	{
	    PCI_VENDOR_CONNECTWARE, 0,
	    PCI_KNOWNDEV_NOPROD,
	    "Connectware",
	    NULL,
	},
	{
	    PCI_VENDOR_MARTINMARIETTA, 0,
	    PCI_KNOWNDEV_NOPROD,
	    "Martin-Marietta",
	    NULL,
	},
	{
	    PCI_VENDOR_WSTECH, 0,
	    PCI_KNOWNDEV_NOPROD,
	    "Workstation Technology",
	    NULL,
	},
	{
	    PCI_VENDOR_INVENTEC, 0,
	    PCI_KNOWNDEV_NOPROD,
	    "Inventec",
	    NULL,
	},
	{
	    PCI_VENDOR_ZEITNET, 0,
	    PCI_KNOWNDEV_NOPROD,
	    "ZeitNet",
	    NULL,
	},
	{
	    PCI_VENDOR_SPECIALIX, 0,
	    PCI_KNOWNDEV_NOPROD,
	    "Specialix",
	    NULL,
	},
	{
	    PCI_VENDOR_CYCLADES, 0,
	    PCI_KNOWNDEV_NOPROD,
	    "Cyclades",
	    NULL,
	},
	{
	    PCI_VENDOR_ZEINET, 0,
	    PCI_KNOWNDEV_NOPROD,
	    "Zeinet",
	    NULL,
	},
	{
	    PCI_VENDOR_SYMPHONY, 0,
	    PCI_KNOWNDEV_NOPROD,
	    "Symphony Labs",
	    NULL,
	},
	{
	    PCI_VENDOR_TEKRAM, 0,
	    PCI_KNOWNDEV_NOPROD,
	    "Tekram Technology",
	    NULL,
	},
	{
	    PCI_VENDOR_AVANCE2, 0,
	    PCI_KNOWNDEV_NOPROD,
	    "Avance Logic (mistyped? see 0x1005)",
	    NULL,
	},
	{
	    PCI_VENDOR_S3, 0,
	    PCI_KNOWNDEV_NOPROD,
	    "S3",
	    NULL,
	},
	{
	    PCI_VENDOR_INTEL, 0,
	    PCI_KNOWNDEV_NOPROD,
	    "Intel",
	    NULL,
	},
	{
	    PCI_VENDOR_ADP, 0,
	    PCI_KNOWNDEV_NOPROD,
	    "Adaptec",
	    NULL,
	},
	{
	    PCI_VENDOR_ATRONICS, 0,
	    PCI_KNOWNDEV_NOPROD,
	    "Atronics",
	    NULL,
	},
	{
	    PCI_VENDOR_NETPOWERNEW, 0,
	    PCI_KNOWNDEV_NOPROD,
	    "NetPower",
	    NULL,
	},
	{
	    PCI_VENDOR_ARK, 0,
	    PCI_KNOWNDEV_NOPROD,
	    "Ark Logic (or Arc? or Hercules?)",
	    NULL,
	},
	{ 0, 0, 0, NULL, NULL, }
};
