@c Copyright (c) 1998 - 2000 Kungliga Tekniska Högskolan
@c (Royal Institute of Technology, Stockholm, Sweden).
@c All rights reserved.

@c $arla: authors.texi,v 1.15 2002/09/07 10:43:49 lha Exp $

@node Authors, Acknowledgments, Arla timeline, Top
@comment  node-name,  next,  previous,  up
@chapter Authors

Currently writing on arla are

@table @asis
@item Assar Westerlund, Everything
@item Magnus Ahltorp, Everything
@item Artur Grabowski, BSD nnpfs, OpenBSD maintainer
@item Love Hörnquist-Åstrand, Everything
@item Robert Burgess, fs, Solaris nnpfs
@item Johan Danielsson, OSF/1 nnpfs
@item Hans Insulander, pts, OpenBSD maintainer
@item Mattias Amnefelt, vos, milko
@item Harald Barth, doc
@item Tomas Olsson, milko
@item Mikael Vidstedt (userland, some milko stuff)
@item Jimmy Engelbercht (bos)
@end table

Rhapsody nnpfs port was contributed by Alexandra Ellwood <lxs@@MIT.EDU>
Later, Rhapsody was renamed Darwin.

Disconnected code is written by:

@table @asis
@item WUWEI SHEN <wwshen@@engin.umich.edu>
@item Cheng Jin <chengjin@@eecs.umich.edu>
@item Paul Callaway <pcallawa@@umich.edu>
@end table

For contributors, see @ref{Acknowledgments}.

