#	$OpenBSD: Makefile,v 1.5 1996/08/17 10:51:21 michaels Exp $
#
#	@(#)Makefile	8.1 (Berkeley) 6/6/93

PROG=	locate.bigram
NOMAN=	noman
BINDIR=	${LIBEXECDIR}
CFLAGS+= -I${.CURDIR}/../locate

.include "../Makefile.inc"
.include <bsd.prog.mk>
