#	$OpenBSD: Makefile,v 1.7 2000/05/25 21:55:07 deraadt Exp $
#	$NetBSD: Makefile,v 1.15 1997/06/01 03:39:03 mrg Exp $

.if ${MACHINE} == "sparc"
SUBDIR= libsa libkern libz boot bootxx binstall
.endif

SUBDIR=	installboot

.include <bsd.subdir.mk>
