#	$OpenBSD: Makefile,v 1.6 1997/09/17 10:46:07 downsj Exp $
#	$NetBSD: Makefile,v 1.15 1997/06/01 03:39:03 mrg Exp $

SUBDIR= libsa libkern libz boot bootxx installboot binstall

.include <bsd.subdir.mk>
