#	$OpenBSD: Makefile,v 1.7 1999/01/24 23:08:48 d Exp $

# Missing: ching dungeon warp
# Moved: chess
# Don't belong: xneko xroach

SUBDIR=	adventure arithmetic atc backgammon banner battlestar bcd boggle \
	bs caesar canfield cribbage dm factor fish fortune gomoku grdc hack \
	hangman larn mille monop morse number phantasia pig pom ppt \
	primes quiz rain random robots rogue sail snake tetris trek wargames \
	worm worms wump

.include <bsd.subdir.mk>
