.\"	$OpenBSD: ospfd.8,v 1.6 2005/02/03 10:49:29 jmc Exp $
.\"
.\" Copyright (c) 2004, 2005 Esben Norby <norby@openbsd.org>
.\"
.\" Permission to use, copy, modify, and distribute this software for any
.\" purpose with or without fee is hereby granted, provided that the above
.\" copyright notice and this permission notice appear in all copies.
.\"
.\" THE SOFTWARE IS PROVIDED "AS IS" AND THE AUTHOR DISCLAIMS ALL WARRANTIES
.\" WITH REGARD TO THIS SOFTWARE INCLUDING ALL IMPLIED WARRANTIES OF
.\" MERCHANTABILITY AND FITNESS. IN NO EVENT SHALL THE AUTHOR BE LIABLE FOR
.\" ANY SPECIAL, DIRECT, INDIRECT, OR CONSEQUENTIAL DAMAGES OR ANY DAMAGES
.\" WHATSOEVER RESULTING FROM LOSS OF USE, DATA OR PROFITS, WHETHER IN AN
.\" ACTION OF CONTRACT, NEGLIGENCE OR OTHER TORTIOUS ACTION, ARISING OUT OF
.\" OR IN CONNECTION WITH THE USE OR PERFORMANCE OF THIS SOFTWARE.
.\"
.Dd November 4, 2004
.Dt OSPFD 8
.Os
.Sh NAME
.Nm ospfd
.Nd "Open Shortest Path First daemon"
.Sh SYNOPSIS
.Nm
.Op Fl d
.Op Fl f Ar file
.Sh DESCRIPTION
.Nm
is an Open Shortest Path First
.Pq OSPF
daemon which manages routing tables.
Its main purpose is to keep AS internal routing tables in sync.
.Pp
A running
.Nm
can be controlled with the
.Xr ospfctl 8
utility.
.Pp
The options are as follows:
.Bl -tag -width Ds
.It Fl d
Do not daemonize.
If this option is specified,
.Nm
will run in the foreground and log to
.Em stderr .
.It Fl f Ar file
Specify an alternative configuration file.
.El
.Sh FILES
.Bl -tag -width "/etc/ospfd.confXXXX" -compact
.It /etc/ospfd.conf
.Nm
configuration file.
.El
.Sh SEE ALSO
.Xr ospfd.conf 5 ,
.Xr ospfctl 8
.Rs
.%R RFC 2328
.%T "OSPF Version 2"
.%D April 1998
.Re
.Sh HISTORY
The
.Nm
program first appeared in
.Ox 3.7 .
