#	$OpenBSD: Makefile,v 1.2 2000/03/01 22:10:00 todd Exp $
#	$NetBSD: Makefile,v 1.1.1.1 1995/04/17 19:08:51 leo Exp $

TOP=		${.CURDIR}/..

.include "${TOP}/Makefile.inc"
IMAGE=		inst-${REV}.fs

.include "${TOP}/inst-common/Makefile.inc"
