#	$OpenBSD: Makefile,v 1.4 2001/09/11 19:02:49 millert Exp $

PROG=	praliases
MAN=	praliases.1
ENVDEF=	-DNOT_SENDMAIL

WANT_LIBSM=1
WANT_LIBSMDB=1
WANT_LIBSMUTIL=1

.include "../../Makefile.inc"
.include <bsd.prog.mk>
