.\"	$OpenBSD: top.1,v 1.8 1999/03/22 23:41:56 pjanzen Exp $
.\"
.\" Copyright (c) 1997, Jason Downs.  All rights reserved.
.\"
.\" Redistribution and use in source and binary forms, with or without
.\" modification, are permitted provided that the following conditions
.\" are met:
.\" 1. Redistributions of source code must retain the above copyright
.\"    notice, this list of conditions and the following disclaimer.
.\" 2. Redistributions in binary form must reproduce the above copyright
.\"    notice, this list of conditions and the following disclaimer in the
.\"    documentation and/or other materials provided with the distribution.
.\" 3. All advertising materials mentioning features or use of this software
.\"    must display the following acknowledgement:
.\"      This product includes software developed by Jason Downs for the
.\"      OpenBSD system.
.\" 4. Neither the name(s) of the author(s) nor the name OpenBSD
.\"    may be used to endorse or promote products derived from this software
.\"    without specific prior written permission.
.\"
.\" THIS SOFTWARE IS PROVIDED BY THE AUTHOR(S) ``AS IS'' AND ANY EXPRESS
.\" OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED
.\" WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE
.\" DISCLAIMED.  IN NO EVENT SHALL THE AUTHOR(S) BE LIABLE FOR ANY DIRECT,
.\" INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES
.\" (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR
.\" SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER
.\" CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT
.\" LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY
.\" OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF
.\" SUCH DAMAGE.
.\"
.Dd August 14, 1997
.Dt TOP 1
.Os OpenBSD
.Sh NAME
.Nm top
.Nd display and update information about the top CPU processes
.Sh SYNOPSIS
.Nm top
.Op Fl SbiInqu
.Op Fl d Ar count
.Op Fl s Ar time
.Op Fl o Ar field
.Op Fl U Ar username
.Op Ar number
.Sh DESCRIPTION
.Nm
displays the top processes on the system and periodically updates this
information.  If standard output is an intelligent terminal (see below) then
as many processes as will fit on the terminal screen are displayed
by default.  Otherwise, a good number of them are shown (around 20).
Raw CPU percentage is used to rank the processes.  If
.Ar number
is given, then the top
.Ar number
processes will be displayed instead of the default.
.Pp
.Nm
makes a distinction between terminals that support advanced capabilities
and those that do not.  This
distinction affects the choice of defaults for certain options.  In the
remainder of this document, an 
.Em intelligent
terminal is one that supports cursor addressing, clear screen, and clear
to end of line.  Conversely, a 
.Em dumb
terminal is one that does not support such features.  If the output of
.Nm
is redirected to a file, it acts as if it were being run on a dumb
terminal.
.Sh OPTIONS
.Bl -tag -width XxXXXXXXXXX
.It Fl S
Show system processes in the display.  Normally, system processes such as
the pager and the swapper are not shown.  This option makes them visible.
.It Fl b
Use
.Em batch
mode.  In this mode, all input from the terminal is
ignored.  Interrupt characters (such as ^C and ^\e) still have an effect.
This is the default on a dumb terminal, or when the output is not a terminal.
.It Fl i
Use
.Em interactive
mode.  In this mode, any input is immediately read for processing.  See the
section on
.Sx INTERACTIVE MODE
for an explanation of which keys perform what functions.  After the command
is processed, the screen will immediately be updated, even if the command was
not understood.  This mode is the default when standard output is an
intelligent terminal.
.It Fl I
Do not display idle processes.
By default, top displays both active and idle processes.
.It Fl n
Use 
.Em non-interactive
mode.  This is identical to
.Em batch
mode.
.It Fl q
Renice
.Nm
to -20 so that it will run faster.  This can be used when the system is
being very sluggish to improve the possibility of discovering the problem.
This option can only be used by root.
.It Fl u
Do not take the time to map UID numbers to usernames.  Normally,
.Nm
will read as much of the password database as is necessary to map
all the user ID numbers it encounters into login names.  This option
disables all that, while possibly decreasing execution time.  The UID
numbers are displayed instead of the names.
.It Fl d Ar count
Show only
.Ar count
displays, then exit.  A display is considered to be one update of the
screen.  This option allows the user to select the number of displays
to be shown before
.Nm
automatically exits.  For intelligent terminals, no upper limit
is set.  The default is 1 for dumb terminals.
.It Fl s Ar time
Set the delay between screen updates to
.Ar time
seconds.  The default delay between updates is 5 seconds.
.It Fl o Ar field
Sort the process display area using the specified field as the primary
key.  The field name is the name of the column as seen in the output,
but in lower case.  The
.Ox
version of top supports
.Ar cpu ,
.Ar size ,
.Ar res ,
.Ar time ,
and
.Ar pri .
.It Fl U Ar username
Show only those processes owned by
.Ar username .
This option currently only accepts usernames and will not understand
UID numbers.
.El
.Pp
Both
.Ar count
and
.Ar number
fields can be specified as
.Li infinite ,
indicating that they can stretch as far as possible.  This is accomplished
by using any proper prefix of the keywords
.Li infinity ,
.Li maximum ,
or
.Li all .
The default for
.Ar count
on an intelligent terminal is, in fact,
.Li infinity .
.Pp
The environment variable
.Ev TOP
is examined for options before the command line is scanned.  This enables
a user to set his or her own defaults.  The number of processes to display
can also be specified in the environment variable
.Ev TOP .
.Pp
The options
.Fl I ,
.Fl S ,
and
.Fl u
are actually toggles.  A second specification of any of these options
will negate the first.  Thus a user who has the environment variable
.Ev TOP
set to 
.Dq -I
may use the command 
.Dq top -I
to see idle processes.
.Sh INTERACTIVE MODE
When
.Nm
is running in
.Em interactive mode ,
it reads commands from the terminal and acts upon them accordingly.  In this
mode, the terminal is put in
.Dv CBREAK ,
so that a character will be processed as soon as it is typed.  Almost always,
a key will be pressed when
.Nm
is between displays; that is, while it is waiting for
.Ar time
seconds to elapse.  If this is the case, the command will be
processed and the display will be updated immediately thereafter
(reflecting any changes that the command may have specified).  This
happens even if the command was incorrect.  If a key is pressed while 
.Nm
is in the middle of updating the display, it will finish the update and
then process the command.  Some commands require additional information,
and the user will be prompted accordingly.  While typing this information
in, the user's erase and kill keys (as set up by the command
.Xr stty 1 )
are recognized, and a newline terminates the input.
.Pp
These commands are currently recognized (^L refers to control-L):
.Bl -tag -width XxXXXX
.It ^L
Redraw the screen.
.It h or ?
Display a summary of the commands (help screen).
.It q
Quit
.Nm top .
.It d
Change the number of displays to show (prompt for new number).
Remember that the next display counts as one, so typing
.Dq d1
will make
.Nm
show one final display and then immediately exit.
.It n or #
Change the number of processes to display (prompt for new number).
.It s
Change the number of seconds to delay between displays
(prompt for new number).
.It k
Send a signal
.Ns ( Dv TERM
by default) to a list of processes.  This acts similarly to the command
.Xr kill 1 .
.It r
Change the priority (the
.Em nice )
of a list of processes.  This acts similarly to the command
.Xr renice 8 .
.It u
Display only processes owned by a specific username (prompt for username).
If the username specified is simply
.Dq + ,
then processes belonging to all users will be displayed.
.It e
Display a list of system errors (if any) generated by the last
.Li kill
or
.Li renice
command.
.It i or I
Toggle the display of idle processes.
.El
.Sh THE DISPLAY
.\" The actual display varies depending on the specific variant of Unix
.\" that the machine is running.  This description may not exactly match
.\" what is seen by top running on this particular machine.  Differences
.\" are listed at the end of this manual entry.
.\" .Pp
The top few lines of the display show general information
about the state of the system, including
the last process ID assigned to a process,
.\" (on most systems),
the three load averages,
the current time,
the number of existing processes,
the number of processes in each state
(sleeping, running, starting, zombies, and stopped),
and a percentage of time spent in each of the processor states
(user, nice, system, and idle).
It also includes information about physial and virtual memory allocation.
.Pp
The remainder of the screen displays information about individual
processes.  This display is similar in spirit to
.Xr ps 1
but it is not exactly the same.  PID is the process ID, USERNAME is the name
of the process's owner (if
.Fl u
is specified, a UID column will be substituted for USERNAME),
PRI is the current priority of the process,
NICE is the nice amount (in the range -20 to 20),
SIZE is the total size of the process (text, data, and stack),
RES is the current amount of resident memory (both SIZE and RES are
given in kilobytes),
STATE is the current state (one of
.Li sleep ,
.Li WAIT ,
.Li run ,
.Li idl ,
.Li zomb ,
or
.Li stop ) ,
TIME is the number of system and user CPU seconds that the process has used,
WCPU, when displayed, is the weighted CPU percentage (this is the same
value that
.Xr ps 1
displays as CPU),
CPU is the raw percentage and is the field that is sorted to determine
the order of the processes, and
COMMAND is the name of the command that the process is currently running
(if the process is swapped out, this column is marked
.Li <swapped> ) .
.Sh NOTES
The
.Em ABANDONED
state (known in the kernel as
.Em SWAIT Ns )
was abandoned, thus the name.  A process should never end up in this state.
.Sh AUTHOR
William LeFebvre, EECS Department, Northwestern University
.Sh ENVIRONMENT
.Bl -tag -width XxXXXX
.It Ev TOP
User-configurable defaults for options.
.El
.Sh FILES
.Bl -tag -width XxXXXXXXX -compact
.It Pa /dev/kmem
kernel memory
.It Pa /dev/mem
physical memory
.It Pa /bsd
kernel image
.Sh BUGS
Don't shoot me, but the default for
.Fl I
has changed once again.  So many people were confused by the fact that
.Nm
wasn't showing them all the processes that I have decided to make the
default behavior show idle processes, just like it did in version 2.
But to appease folks who can't stand that behavior, I have added the
ability to set
.Li default
options in the environment variable
.Ev TOP
(see the
.Sx OPTIONS
section).  Those who want the behavior that version 3.0 had need only set
the environment variable
.Ev TOP
to
.Li -I .
.Pp
The command name for swapped processes should be tracked down, but this
would make the program run slower.
.Pp
As with
.Xr ps 1 ,
things can change while
.Nm
is collecting information for an update.  The picture it gives is only a
close approximation to reality.
.Sh SEE ALSO
.Xr kill 1 ,
.Xr ps 1 ,
.Xr stty 1 ,
.Xr mem 4 ,
.Xr renice 8 ,
.Xr systat 1
