.\" 	$OpenBSD: pxaudc.4,v 1.10 2007/05/31 19:19:57 jmc Exp $
.\"
.\" Copyright (c) 2005 David Gwynne <dlg@openbsd.org>
.\"
.\" Permission to use, copy, modify, and distribute this software for any
.\" purpose with or without fee is hereby granted, provided that the above
.\" copyright notice and this permission notice appear in all copies.
.\"
.\" THE SOFTWARE IS PROVIDED "AS IS" AND THE AUTHOR DISCLAIMS ALL WARRANTIES
.\" WITH REGARD TO THIS SOFTWARE INCLUDING ALL IMPLIED WARRANTIES OF
.\" MERCHANTABILITY AND FITNESS. IN NO EVENT SHALL THE AUTHOR BE LIABLE FOR
.\" ANY SPECIAL, DIRECT, INDIRECT, OR CONSEQUENTIAL DAMAGES OR ANY DAMAGES
.\" WHATSOEVER RESULTING FROM LOSS OF USE, DATA OR PROFITS, WHETHER IN AN
.\" ACTION OF CONTRACT, NEGLIGENCE OR OTHER TORTIOUS ACTION, ARISING OUT OF
.\" OR IN CONNECTION WITH THE USE OR PERFORMANCE OF THIS SOFTWARE.
.\"
.Dd $Mdocdate: May 31 2007 $
.Dt PXAUDC 4 zaurus
.Os
.Sh NAME
.Nm pxaudc
.Nd PXA27x USB device controller
.Sh SYNOPSIS
.Cd "pxaudc0 at pxaip?"
.Cd "usbf* at pxaudc?"
.Sh DESCRIPTION
The PXA27x USB Device Controller supplies bus interface functions
so that
the USB Function support driver,
.Xr usbf 4 ,
can support client-cable USB functions.
.Pp
The
.Nm
driver is able to detect the presence of either host or client cables.
If a host cable is detected, the USB pins are routed to
the USB host controller,
.Xr ohci 4 ,
which supplies USB device support for many devices as described in
.Xr usb 4 .
If a client cable is detected, the USB pins are directly used by
.Nm
to support USB client functionality, as described in
.Xr usbf 4 .
.Sh SEE ALSO
.Xr ohci 4 ,
.Xr usb 4 ,
.Xr usbf 4
.Sh AUTHORS
.An -nosplit
The initial
.Nm
driver was written by
.An David Gwynne Aq dlg@openbsd.org .
USB Client support was later developed by
.An Uwe Stuehler Aq uwe@openbsd.org
and completed by
.An Dale Rahn Aq drahn@openbsd.org .
