host=ldap+tls://1.2.3.4:8389
host=ldap://localhost
cacert=/etc/ssl/ca-ldap.pem
scope=sub
basedn=dc=example,dc=com
binddn=cn=admin,dc=example,dc=com
bindpw=password
# Filter for RFC 2307 POSIX accounts
filter=(&(objectClass=posixAccount)(uid=%u))
# Filter for Microsoft Active Directory accounts
#filter=(&(objectCategory=person)(sAMAccountName=%u))
