# $OpenBSD: Makefile.inc,v 1.3 2026/08/22 09:04:01 jsing Exp $

SRCS += sha1_amd64.c
SRCS += sha1_amd64_generic.S
SRCS += sha1_amd64_shani.S
SRCS += sha256_amd64.c
SRCS += sha256_amd64_generic.S
SRCS += sha256_amd64_shani.S
SRCS += sha512_amd64.c
SRCS += sha512_amd64_generic.S
