#	$OpenBSD: Makefile,v 1.25 2011/07/06 18:32:58 miod Exp $
#	$NetBSD: Makefile,v 1.6 1996/03/03 17:13:09 thorpej Exp $
#	from: @(#)Makefile	5.4 (Berkeley) 5/11/90

MAN=	asc.4 autoconf.4 cons.4 de.4 dhu.4 dz.4 fwio.4 gpx.4 \
	ibus.4 intro.4 lcg.4 lcspx.4 le.4 led.4 legss.4 lkkbd.4 lkms.4 \
	mbus.4 mem.4 mscpbus.4 mt.4 mtc.4 ncr.4 qe.4 qsc.4 ra.4 rx.4 \
	sii.4 smg.4 uba.4 uda.4 vsbus.4 vxtbus.4 ze.4
MLINKS=	mem.4 kmem.4
MANSUBDIR=vax

.include <bsd.prog.mk>
