#	$OpenBSD: Makefile,v 1.3 2002/05/11 00:20:20 espie Exp $
#	$NetBSD: Makefile,v 1.1 1996/02/02 15:26:21 mrg Exp $

.PATH:	${.CURDIR}/../man

CFLAGS+=${INCLUDE} ${CONFIG}

PROG=	dnsquery

.include <bsd.prog.mk>
.include "../../Makefile.inc"
