#!/bin/sh
# $Id: dequeue,v 1.1 1999/07/13 23:02:07 deraadt Exp $

L=/home/ctm/log.dequeue
/usr/sbin/ctm_dequeue -n 1 -l $L /home/ctm/queue/ctm-cvs-cur
/usr/sbin/ctm_dequeue -n 1 -l $L /home/ctm/queue/ctm-src-cur
