./usr/share/info/as.info
./usr/share/info/as.info-1
./usr/share/info/bfd.info
./usr/share/info/bfd.info-1
./usr/share/info/binutils.info
./usr/share/info/binutils.info-1
./usr/share/info/ld.info
./usr/share/info/ld.info-1
./usr/share/man/cat1/ld.so.0
