./usr/share/man/cat1/elf2aout.0
./usr/share/man/cat1/elf2ecoff.0
./usr/share/man/cat1/ldd.0
./usr/share/man/cat4/autoconf.4
./usr/share/man/cat4/com.4
./usr/share/man/cat4/ed.4
./usr/share/man/cat4ep.4
./usr/share/man/cat4/intro.4
./usr/share/man/cat4/joy.4
./usr/share/man/cat4/le.4
./usr/share/man/cat4/lpt.4
./usr/share/man/cat4/pms.4
./usr/share/man/cat4/wd.4
./usr/share/man/cat8/fdisk.0
./usr/share/man/cat8/ld.so.0
./usr/share/man/cat8/ldconfig.0
