./usr/share/info/annotate.info
./usr/share/info/as.info
./usr/share/info/bfd.info
./usr/share/info/binutils.info
./usr/share/info/ld.info
./usr/share/info/stabs.info
./usr/share/man/cat1/ld.so.0
./usr/share/man/cat1/ldd.0
./usr/share/man/cat8/ldconfig.0
