#	$OpenBSD: Makefile,v 1.14 2018/04/19 01:10:41 bluhm Exp $

SUBDIR +=	etherip gif loop
SUBDIR +=	pf_divert pf_forward pf_fragment pf_print pf_state pf_table
SUBDIR +=	rdomains rtable vxlan

.include <bsd.subdir.mk>
