#!/bin/sh
#
# $OpenBSD: amd,v 1.6 2013/09/01 15:02:35 ajacoutot Exp $

daemon="/usr/sbin/amd"

. /etc/rc.d/rc.subr

rc_reload=NO
rc_stop=NO

rc_pre() {
	[ -e ${amd_master} ] || return 1
	daemon_flags="${daemon_flags} $(print -rn -- $(< ${amd_master}))"
}

rc_start() {
	${rcexec} "cd /etc/amd; ${daemon} ${daemon_flags}"
}

rc_cmd $1
