#!/bin/sh
#
# $OpenBSD: ypbind,v 1.3 2011/07/08 02:15:34 robert Exp $

daemon="/usr/sbin/ypbind"

. /etc/rc.d/rc.subr

rc_bg=YES
rc_reload=NO

rc_pre() {
	[ X"`domainname`" != X"" -a -d /var/yp/binding ]
}

rc_cmd $1
