.\"	$OpenBSD: cvsd.conf.5,v 1.3 2004/12/02 22:38:30 jmc Exp $
.\"
.\" Copyright (c) 2004 Jean-Francois Brousseau <jfb@openbsd.org>
.\"
.\" Redistribution and use in source and binary forms, with or without
.\" modification, are permitted provided that the following conditions
.\" are met:
.\" 1. Redistributions of source code must retain the above copyright
.\"    notice, this list of conditions and the following disclaimer.
.\" 2. Redistributions in binary form must reproduce the above copyright
.\"    notice, this list of conditions and the following disclaimer in the
.\"    documentation and/or other materials provided with the distribution.
.\" 3. The name of the author may not be used to endorse or promote products
.\"    derived from this software without specific prior written permission.
.\"
.\" THIS SOFTWARE IS PROVIDED BY THE AUTHOR ``AS IS'' AND ANY EXPRESS OR
.\" IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED WARRANTIES
.\" OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE DISCLAIMED.
.\" IN NO EVENT SHALL THE AUTHOR BE LIABLE FOR ANY DIRECT, INDIRECT,
.\" INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT
.\" NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; LOSS OF USE,
.\" DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON ANY
.\" THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT
.\" (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF
.\" THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
.\"
.Dd July 20, 2004
.Dt CVSD.CONF 5
.Os
.Sh NAME
.Nm cvsd.conf
.Nd CVS daemon configuration file format
.Sh DESCRIPTION
The
.Nm
configuration file format is used by the
.Xr cvsd 8
server.
The server's configuration file is read upon startup and reparsed on every
server restart.
.Pp
It is a human-readable text file consisting of one-line directives that
the server handles to modify its configuration and Access Control List rules
to control operations on the repository.
Comments can be inserted anywhere in the file by putting a
.Sq #
character before them and span to the end of the line.
.Sh MACROS
To simplify maintenance of the configuration, the format allows for the
definition of variables that can later be used for interpolation throughout
the configuration file by preceding them with the
.Sq $
character.
These variables are refered to as macros throughout the rest of the document.
A macro name must start with a letter and can be composed of letters, digits,
and underscores.
.Pp
Here is an example of macro usage:
.Bd -literal -offset indent
rootdir = /usr/local/cvs

cvsroot $rootdir

reqsock $rootdir/CVSROOT/cvsd.sock
.Ed
.Pp
To assign a value containing spaces to a macro, the whole value string must
be quoted using double quotes.
.Sh DIRECTIVES
The following directives are supported by the server:
.Bl -tag -width xxxxx
.It Sy cvsroot Ar path
Set the server's CVS root directory to
.Ar path .
.It Sy listen Ar addr
Add the address
.Ar addr
to the list of addresses on which the server will listen for incoming
connections.
This is currently parsed but ignored, as the CVS daemon doesn't support
direct TCP connections yet.
.It Sy maxchild Ar num
Set the server's maximum number of child processes to
.Ar num .
.It Sy minchild Ar num
Set the server's minimum number of child processes to
.Ar num .
.It Sy reqsock Ar path
Set the server's local socket path to
.Ar path .
In order for this to work, the
.Xr cvs 1
client must be aware of the socket's path.
.El
.Sh ACL GRAMMAR
The Access Control Lists grammar is expressed in BNF (Backus-Naur Form)
notation.
In this representation, terminals are displayed as normal text and nonterminals
are in bold.
.Po
.Ql [
and
.Ql \&]
.Pc
is optional.
The pipe character
.Pq Ql \&|
is used to separate multiple choices.
.Pp
Here is the BNF syntax for
.Nm
rules:
.Bl -tag -width "this is a test"
.It Ic action
::= allow | deny
.It Ic line
::=
.It Ic op
::= add | commit | tag | update
.It Ic option
::= quick | log
.It Ic optlist
::=
.Ic option
|
.Ic optlist ,
.Ic option
.It Ic rule
::=
.Ic action
.Bo
.Ic optlist
.Bc
.Ic op
[ branch
.Ic branch
]
.Pp
[ from
.Ic userlist
]
.It Ic userlist
::=
.El
.Sh EXAMPLES
The following rule denies all operations:
.Bd -literal -offset indent
deny quick any
.Ed
.Sh FILES
.Bl -tag -width /etc/cvsd.conf -compact
.It Pa /etc/cvsd.conf
Default configuration file for
.Xr cvsd 8 .
.El
.Sh SEE ALSO
.Xr cvs 1 ,
.Xr rcsfile 5 ,
.Xr cvsd 8
.Sh HISTORY
The
.Nm
file format was introduced along with the CVS daemon as part of the
OpenCVS project.
.Sh AUTHORS
.An Jean-Francois Brousseau
