#	$OpenBSD: Makefile,v 1.3 2001/01/29 02:11:16 niklas Exp $
#	$NetBSD: Makefile,v 1.6 1995/09/06 21:36:34 jtc Exp $

MAN=	MAKEDEV.8 boot_hp300.8 format.8
MLINKS=	MAKEDEV.8 makedev.8
MANSUBDIR=/hp300

.include <bsd.prog.mk>
