#!/bin/csh -f

set arch=`machine`
set listsdir=`pwd`/lists

set TMPFILE=/tmp/_LIST.$$

set lists=(base comp etc game)
# SPECIAL: man misc

foreach setname ($lists)
	cat $listsdir/$setname/mi $listsdir/$setname/md.${arch} >>! $TMPFILE
end

set setname=man
grep ${arch} $listsdir/man/md_share | \
    cat $listsdir/$setname/mi $listsdir/$setname/md.${arch} - >>! $TMPFILE

set setname=misc
grep -v ${arch} $listsdir/man/md_share | \
    cat $listsdir/$setname/mi $listsdir/$setname/md.${arch} - >>! $TMPFILE

sort $TMPFILE
/bin/rm $TMPFILE
