#!/bin/sh
#	$OpenBSD: makeflist,v 1.6 2001/12/25 01:30:22 deraadt Exp $

arch=`machine`

TMP=`mktemp /tmp/_mkr.XXXXXX` || exit 1
trap 'rm -f $TMP' 0 1 15

for i in base comp etc game; do
	cat ./lists/$i/mi ./lists/$i/md.${arch} >> $TMP
done
cat ./lists/man/mi ./lists/man/md.${arch} >> $TMP
cat ./lists/misc/mi ./lists/misc/md.${arch} >> $TMP

sort $TMP
