$set 1
$ EPERM
1 Handeling niet toegestaan
$ ENOENT
2 Bestand of schuif niet gevonden
$ ESRCH
3 Taak bestaat niet
$ EINTR
4 Onderbroken systeem aanroep
$ EIO
5 Invoer/uitvoer fout
$ ENXIO
6 Toestel niet geconfigureerd
$ E2BIG
7 Argumenten lijst is te lang
$ ENOEXEC
8 Programmabestand kan niet worden uitgevoerd
$ EBADF
9 Ongeldige bestandsverwijzing
$ ECHILD
10 Er zijn geen spruiten meer
$ EDEADLK
11 Een "deadlock" is vermeden
$ ENOMEM
12 Kan geen geheugen meer verkrijgen
$ EACCES
13 Toegang gewijgerd
$ EFAULT
14 Ongeldig adres
$ ENOTBLK
15 Een "Block device" is vereist
$ EBUSY
16 Toestel is verlet
$ EEXIST
17 Bestand bestaat reeds
$ EXDEV
18 Onmogelijke verbinding tussen apparaten
$ ENODEV
19 Verrichting wordt door dit toestel niet ondersteund
$ ENOTDIR
20 Dit is geen schuif
$ EISDIR
21 Dit is een schuif
$ EINVAL
22 Ongeldig argument
$ ENFILE
23 Te veel open bestanden in het systeem
$ EMFILE
24 Te veel open bestanden
$ ENOTTY
25 Ontoepasselijke ioctl voor dit toestel
$ ETXTBSY
26 Programma bestand is verlet
$ EFBIG
27 Bestand is te groot
$ ENOSPC
28 Geen ruimte meer op dit toestel
$ ESPIPE
29 Onuitvoerbare zoekopdracht
$ EROFS
30 Van dit bestandsysteem kan allen worden gelezen
$ EMLINK
31 Te veel verbindingen
$ EPIPE
32 Gebroken pijp
$ EDOM
33 Numeriek argument valt buiten domein
$ ERANGE
34 Resultaat te groot
$ EAGAIN, EWOULDBLOCK
35 Hulpmiddel tijdelijk onbeschikbaar
$ EINPROGRESS
36 Bewerking in gang gezet
$ EALREADY
37 Bewerking is al in gang gezet
$ ENOTSOCK
38 Voor deze handeling is een contactdoos vereist
$ EDESTADDRREQ
39 Een bestemmingsadres is vereist
$ EMSGSIZE
40 Grote boodschap
$ EPROTOTYPE
41 Protocol past niet bij deze contactdoos
$ ENOPROTOOPT
42 Protocol is niet beschikbaar
$ EPROTONOSUPPORT
43 Protocol is niet ondersteund
$ ESOCKTNOSUPPORT
44 Stekerdoos model niet ondersteund
$ EOPNOTSUPP
45 Bewerking niet ondersteund
$ EPFNOSUPPORT
46 Protocol familie niet ondersteund
$ EAFNOSUPPORT
47 Addressen familie niet ondersteund door protocol familie
$ EADDRINUSE
48 Addres is al in gebruik
$ EADDRNOTAVAIL
49 Het gevraagde adres kan niet worden toegekend
$ ENETDOWN
50 Netwerk is plat
$ ENETUNREACH
51 Netwerk is onbereikbaar
$ ENETRESET
52 Netwerk onderbrak verbinding tijdens herstart
$ ECONNABORTED
53 Verbroken verbinding veroorzaakt door software
$ ECONNRESET
54 Verbinding werd aan de andere kant verbroken
$ ENOBUFS
55 Geen buffer ruimte meer beschikbaar
$ EISCONN
56 Deze contactdoos heeft al een verbinding aanwezig
$ ENOTCONN
57 Contactdoos is niet verbonden
$ ESHUTDOWN
58 Een dichtgezette contactdoos kan geen gegevens meer verzenden
$ ETOOMANYREFS
59 Te veel verwijzingen: splitsen niet mogelijk
$ ETIMEDOUT
60 Verbinding "timed out"
$ ECONNREFUSED
61 Verbinding gewijgerd
$ ELOOP
62 Te veel niveaus van symbolische verwijzingen
$ ENAMETOOLONG
63 Bestandsnaam te lang
$ EHOSTDOWN
64 Gastheer is terneergeslagen
$ EHOSTUNREACH
65 Gastheer is onaanspreekbaar
$ ENOTEMPTY
66 Deze schuif is niet leeg
$ EPROCLIM
67 Te veel taken
$ EUSERS
68 Te veel gebruikers
$ EDQUOT
69 Schijf quota overschreden
$ ESTALE
70 Verschaalde NFS bestandsverwijzing
$ EREMOTE
71 Te veel televerwijzingen op dit pad
$ EBADRPC
72 RPC struct is niet welgevormd
$ ERPCMISMATCH
73 RPC versie is verkeerd
$ EPROGUNAVAIL
74 RPC prog. niet beschikbaar
$ EPROGMISMATCH
75 Program versie is verkeerd
$ EPROCUNAVAIL
76 Taak kan door dit programma niet worden uitgevoerd
$ ENOLCK
77 Geen versperringen beschikbaar
$ ENOSYS
78 Deze function is niet verwezenlijkt
$ EFTYPE
79 Ontoepasselijk bestandsformaat
$set 2
$ SIGHUP
1 Opgehangen
$ SIGINT
2 Onderbroken
$ SIGQUIT
3 Opgegeven
$ SIGILL
4 Verboden instructie
$ SIGTRAP
5 Spoor/BPT val
$ SIGABRT
6 Abort val
$ SIGEMT
7 EMT val
$ SIGFPE
8 Drijvende comma fout
$ SIGKILL
9 Killed
$ SIGBUS
10 Bus fout
$ SIGSEGV
11 Segmentatie fout
$ SIGSYS
12 Onbekende systeem aanroep
$ SIGPIPE
13 Gebroken pijp
$ SIGALRM
14 Wekker
$ SIGTERM
15 Verscheiden
$ SIGURG
16 Dringende I/O opgemerkt
$ SIGSTOP
17 Gestopt (signaal)
$ SIGTSTP
18 Gestopt
$ SIGCONT
19 Voortgezet
$ SIGCHLD
20 Verscheiden spruit
$ SIGTTIN
21 Gestopt (tty invoer)
$ SIGTTOU
22 Gestopt (tty uitvoer)
$ SIGIO
23 I/O mogelijk
$ SIGXCPU
24 Te veel CVE tijd verbruikt
$ SIGXFSZ
25 Maximum bestandsgrootte overschreden
$ SIGVTALRM
26 Virtuele wekker
$ SIGPROF
27 Profiling wekker
$ SIGWINCH
28 Vensterafmeting veranderd
$ SIGINFO
29 Informatie verzoek
$ SIGUSR1
30 Gebruikersignaal 1
$ SIGUSR2
31 Gebruikersignaal 2
