$set 1
$ EPERM
1 Operationway otnay ermittedpay
$ ENOENT
2 Onay uchsay ilefay orway irectoryday
$ ESRCH
3 Onay uchsay ocesspray
$ EINTR
4 Interruptedway ystemsay allcay
$ EIO
5 Inputway/outputway errorway
$ ENXIO
6 Eviceday otnay onfiguredcay
$ E2BIG
7 Argumentway istlay ootay onglay
$ ENOEXEC
8 Execway ormatfay errorway
$ EBADF
9 Adbay ilefay escriptorday
$ ECHILD
10 Onay ildchay ocessespray
$ EDEADLK
11 Esourceray eadlockday avoidedway
$ ENOMEM
12 Annotcay allocateway emorymay
$ EACCES
13 Ermissionpay eniedday
$ EFAULT
14 Adbay addressway
$ ENOTBLK
15 Ockblay eviceday equiredray
$ EBUSY
16 Eviceday usybay
$ EEXIST
17 Ilefay existsway
$ EXDEV
18 Osscray-eviceday inklay
$ ENODEV
19 Operationway otnay upportedsay ybay eviceday
$ ENOTDIR
20 Otnay away irectoryday
$ EISDIR
21 Isway away irectoryday
$ EINVAL
22 Invalidway argumentway
$ ENFILE
23 Ootay anymay openway ilesfay inway ystemsay
$ EMFILE
24 Ootay anymay openway ilesfay
$ ENOTTY
25 Inappropriateway ioctlway orfay eviceday
$ ETXTBSY
26 Exttay ilefay usybay
$ EFBIG
27 Ilefay ootay argelay
$ ENOSPC
28 Onay acespay eftlay onway eviceday
$ ESPIPE
29 Illegalway eeksay
$ EROFS
30 Eadray-onlyway ilefay ystemsay
$ EMLINK
31 Ootay anymay inkslay
$ EPIPE
32 Okenbray ipepay
$ EDOM
33 Umericalnay argumentway outway ofway omainday
$ ERANGE
34 Esultray ootay argelay
$ EAGAIN, EWOULDBLOCK
35 Esourceray emporarilytay unavailableway
$ EINPROGRESS
36 Operationway ownay inway ogresspray
$ EALREADY
37 Operationway alreadyway inway ogresspray
$ ENOTSOCK
38 Ocketsay operationway onway onnay-ocketsay
$ EDESTADDRREQ
39 Estinationday addressway equiredray
$ EMSGSIZE
40 Essagemay ootay onglay
$ EPROTOTYPE
41 Otocolpray ongwray ypetay orfay ocketsay
$ ENOPROTOOPT
42 Otocolpray otnay availableway
$ EPROTONOSUPPORT
43 Otocolpray otnay upportedsay
$ ESOCKTNOSUPPORT
44 Ocketsay ypetay otnay upportedsay
$ EOPNOTSUPP
45 Operationway otnay upportedsay
$ EPFNOSUPPORT
46 Otocolpray amilyfay otnay upportedsay
$ EAFNOSUPPORT
47 Addressway amilyfay otnay upportedsay ybay otocolpray amilyfay
$ EADDRINUSE
48 Addressway alreadyway inway useway
$ EADDRNOTAVAIL
49 Ancay'tay assignway equestedray addressway
$ ENETDOWN
50 Etworknay isway ownday
$ ENETUNREACH
51 Etworknay isway unreachableway
$ ENETRESET
52 Etworknay oppeddray onnectioncay onway esetray
$ ECONNABORTED
53 Oftwaresay ausedcay onnectioncay abortway
$ ECONNRESET
54 Onnectioncay esetray ybay eerpay
$ ENOBUFS
55 Onay ufferbay acespay availableway
$ EISCONN
56 Ocketsay isway alreadyway onnectedcay
$ ENOTCONN
57 Ocketsay isway otnay onnectedcay
$ ESHUTDOWN
58 Ancay'tay endsay afterway ocketsay utdownshay
$ ETOOMANYREFS
59 Ootay anymay eferencesray: ancay'tay icesplay
$ ETIMEDOUT
60 Onnectioncay imedtay outway
$ ECONNREFUSED
61 Onnectioncay efusedray
$ ELOOP
62 Ootay anymay evelslay ofway ymbolicsay inkslay
$ ENAMETOOLONG
63 Ilefay amenay ootay onglay
$ EHOSTDOWN
64 Osthay isway ownday
$ EHOSTUNREACH
65 Onay outeray otay osthay
$ ENOTEMPTY
66 Irectoryday otnay emptyway
$ EPROCLIM
67 Ootay anymay ocessespray
$ EUSERS
68 Ootay anymay usersway
$ EDQUOT
69 Iscday otaquay exceededway
$ ESTALE
70 Alestay NFSay ilefay andlehay
$ EREMOTE
71 Ootay anymay evelslay ofway emoteray inway athpay
$ EBADRPC
72 RPCay uctstray isway adbay
$ ERPCMISMATCH
73 RPCay ersionvay ongwray
$ EPROGUNAVAIL
74 RPCay ogpray. otnay availway
$ EPROGMISMATCH
75 Ogrampray ersionvay ongwray
$ EPROCUNAVAIL
76 Adbay ocedurepray orfay ogrampray
$ ENOLCK
77 Onay ockslay availableway
$ ENOSYS
78 Unctionfay otnay implementedway
$ EFTYPE
79 Inappropriateway ilefay ypetay orway ormatfay
$set 2
$ SIGHUP
1 Anguphay
$ SIGINT
2 Interruptway
$ SIGQUIT
3 Itquay
$ SIGILL
4 Illegalway instructionway
$ SIGTRAP
5 aceTray/BPTay aptray
$ SIGABRT
6 Abortway aptray
$ SIGEMT
7 EMTway aptray
$ SIGFPE
8 Oatingflay ointpay exceptionway
$ SIGKILL
9 Illedkay
$ SIGBUS
10 Usbay errorway
$ SIGSEGV
11 Egmentationsay aultfay
$ SIGSYS
12 Adbay ystemsay allcay
$ SIGPIPE
13 Okenbray ipepay
$ SIGALRM
14 Alarmway ockclay
$ SIGTERM
15 Erminatedtay
$ SIGURG
16 Urgentway Iway/Oway onditioncay
$ SIGSTOP
17 Oppedstay (ignalsay)
$ SIGTSTP
18 Oppedstay
$ SIGCONT
19 Ontinuedcay
$ SIGCHLD
20 Ildchay exitedway
$ SIGTTIN
21 Oppedstay (yttay inputway)
$ SIGTTOU
22 Oppedstay (yttay outputway)
$ SIGIO
23 Iway/Oway ossiblepay
$ SIGXCPU
24 Utimecpay imitlay exceededway
$ SIGXFSZ
25 Ilesizefay imitlay exceededway
$ SIGVTALRM
26 Irtualvay imertay expiredway
$ SIGPROF
27 Ofilingpray imertay expiredway
$ SIGWINCH
28 Indowway izesay angeschay
$ SIGINFO
29 Informationway equestray
$ SIGUSR1
30 Userway efinedday ignalsay 1
$ SIGUSR2
31 Userway efinedday ignalsay 2
