test-2.c:16: warning: conversion from 'int' to 'unsigned char' may lose accuracy
test-2.c:17: warning: conversion from 'int' to 'unsigned char' may lose accuracy
test-2.c:21: warning: conversion from 'int' to 'unsigned char' may lose accuracy
test-2.c:22: warning: right shift of 8-bit quantity by 8 bits
test-2.c:22: warning: conversion from 'int' to 'unsigned char' may lose accuracy
test-2.c:24: warning: right shift of 8-bit quantity by 8 bits
test-2.c:26: warning: conversion from 'int' to 'unsigned char' may lose accuracy
test-2.c:27: warning: right shift of 8-bit quantity by 9 bits
test-2.c:27: warning: conversion from 'int' to 'unsigned char' may lose accuracy
test-2.c:29: warning: right shift of 8-bit quantity by 9 bits
test-2.c:31: warning: conversion from 'int' to 'unsigned char' may lose accuracy
test-2.c:32: warning: right shift of 8-bit quantity by 10 bits
test-2.c:32: warning: conversion from 'int' to 'unsigned char' may lose accuracy
test-2.c:34: warning: right shift of 8-bit quantity by 10 bits
Lint pass2:
