#	$OpenBSD: Makefile,v 1.2 2014/04/17 07:52:08 jsg Exp $

SUBDIR= \
	bf \
	bn \
	cast \
	des \
	dh \
	dsa \
	ec \
	ecdh \
	ecdsa \
	engine \
	evp \
	exp \
	hmac \
	idea \
	ige \
	md4 \
	md5 \
	mdc2 \
	rand \
	rc2 \
	rc4 \
	rmd \
	sha \
	sha1

install:

.include <bsd.subdir.mk>
