/*
 * THIS FILE AUTOMATICALLY GENERATED. DO NOT EDIT.
 * generated from:
 *	OpenBSD: cpudevs,v 1.8 1999/02/17 03:21:43 mickey Exp 
 */

#define	HPPA_TYPE_CPU	0
#define	HPPA_TYPE_MEMORY	1
#define	HPPA_TYPE_BDMA	2
#define	HPPA_TYPE_BDIRECT	3
#define	HPPA_TYPE_ADMA	4
#define	HPPA_TYPE_ADIRECT	5
#define	HPPA_TYPE_OTHER	6
#define	HPPA_TYPE_BCP	7
#define	HPPA_TYPE_CIO	8
#define	HPPA_TYPE_CONSOLE	9
#define	HPPA_TYPE_FIO	10
#define	HPPA_TYPE_BHA	11
#define	HPPA_TYPE_MULTI	12
#define	HPPA_TYPE_FAULTY	31
#define	HPPA_CPU_HPPA10	0
#define	HPPA_CPU_HPPA11	4
#define	HPPA_CPU_HPPA20	8
#define	HPPA_MEMORY_ARCH	0x8
#define	HPPA_MEMORY_PDEP	0x9
#define	HPPA_OTHER_SPECFB	0x48
#define	HPPA_OTHER_SPECCTL	0x49
#define	HPPA_BHA_DIO	0x03
#define	HPPA_BHA_SGC	0x05
#define	HPPA_BHA_GSC	0x07
#define	HPPA_BHA_ASP	0x70
#define	HPPA_BHA_EISA	0x76
#define	HPPA_BHA_VME	0x78
#define	HPPA_BHA_LASI	0x81
#define	HPPA_BHA_WAX	0x8e
#define	HPPA_BHA_WEISA	0x90
#define	HPPA_ADMA_FWSCSI	0x89
#define	HPPA_ADMA_MYRI	0x95
#define	HPPA_FIO_SCSI	0x71
#define	HPPA_FIO_LAN	0x72
#define	HPPA_FIO_HIL	0x73
#define	HPPA_FIO_CENT	0x74
#define	HPPA_FIO_RS232	0x75
#define	HPPA_FIO_SGC	0x77
#define	HPPA_FIO_A1	0x7a
#define	HPPA_FIO_A2NB	0x7b
#define	HPPA_FIO_FWSCSI	0x7c
#define	HPPA_FIO_FDDI	0x7d
#define	HPPA_FIO_A1NB	0x7e
#define	HPPA_FIO_A2	0x7f
#define	HPPA_FIO_HPIB	0x80
#define	HPPA_FIO_GSCSI	0x82
#define	HPPA_FIO_GPCFD	0x83
#define	HPPA_FIO_GPCIO	0x84
#define	HPPA_FIO_GSGC	0x85
#define	HPPA_FIO_GSCSCSI	0x89
#define	HPPA_FIO_GLAN	0x8a
#define	HPPA_FIO_GRS232	0x8c
