.\"	$OpenBSD: unwind.conf.5,v 1.1 2019/01/23 13:11:00 florian Exp $
.\"
.\" Copyright (c) 2018 Florian Obser <florian@openbsd.org>
.\" Copyright (c) 2005 Esben Norby <norby@openbsd.org>
.\" Copyright (c) 2004 Claudio Jeker <claudio@openbsd.org>
.\" Copyright (c) 2003, 2004 Henning Brauer <henning@openbsd.org>
.\" Copyright (c) 2002 Daniel Hartmeier <dhartmei@openbsd.org>
.\"
.\" Permission to use, copy, modify, and distribute this software for any
.\" purpose with or without fee is hereby granted, provided that the above
.\" copyright notice and this permission notice appear in all copies.
.\"
.\" THE SOFTWARE IS PROVIDED "AS IS" AND THE AUTHOR DISCLAIMS ALL WARRANTIES
.\" WITH REGARD TO THIS SOFTWARE INCLUDING ALL IMPLIED WARRANTIES OF
.\" MERCHANTABILITY AND FITNESS. IN NO EVENT SHALL THE AUTHOR BE LIABLE FOR
.\" ANY SPECIAL, DIRECT, INDIRECT, OR CONSEQUENTIAL DAMAGES OR ANY DAMAGES
.\" WHATSOEVER RESULTING FROM LOSS OF USE, DATA OR PROFITS, WHETHER IN AN
.\" ACTION OF CONTRACT, NEGLIGENCE OR OTHER TORTIOUS ACTION, ARISING OUT OF
.\" OR IN CONNECTION WITH THE USE OR PERFORMANCE OF THIS SOFTWARE.
.\"
.Dd $Mdocdate: January 23 2019 $
.Dt UNWIND.CONF 5
.Os
.Sh NAME
.Nm unwind.conf
.Nd validating DNS resolver configuration file
.Sh DESCRIPTION
The
.Xr unwind 8
daemon is a validating DNS resolver.
.Pp
The
.Nm
config file is divided into the following main sections:
.Bl -tag -width xxxx
.It Sy Macros
User-defined variables may be defined and used later, simplifying the
configuration file.
.It Sy Global Configuration
Global settings for
.Xr unwind 8 .
.El
.Pp
Additional configuration files can be included with the
.Ic include
keyword.
.Sh MACROS
Macros can be defined that will later be expanded in context.
Macro names must start with a letter, digit, or underscore,
and may contain any of those characters.
Macro names may not be reserved words.
Macros are not expanded inside quotes.
.Sh GLOBAL CONFIGURATION
.Bl -tag -width Ds
.It Ic forwarder Brq forwarder list
list of addresses of DNS name servers to forward queries to.
.El
.Sh FILES
.Bl -tag -width "/etc/unwind.conf" -compact
.It Pa /etc/unwind.conf
.Xr unwind 8
configuration file
.El
.Sh SEE ALSO
.Xr rc.conf.local 8 ,
.Xr unwind 8 ,
.Xr unwindctl 8
.Sh HISTORY
The
.Nm
file format first appeared in
.Ox 6.5 .
