    POPUP "&View"
    BEGIN
	MENUITEM "Show &Source\tF4",	ID_REAL_CMD_BUTTON_SRCWIN_SHOWSOURCE,
	MENUITEM "Show &Assembly\tF6",	ID_REAL_CMD_BUTTON_SRCWIN_SHOWASM,
	MENUITEM "Show &Line Numbers",  ID_REAL_CMD_BUTTON_SRCWIN_SHOWLINE,
	MENUITEM "Show &Breakpoint locs", ID_REAL_CMD_BUTTON_SRCWIN_SHOWBPT,
    END

