authority pebble {
	account key "${.OBJDIR}/etc/acme/privkey.pem"
	api url https://127.0.0.1:14000/dir
	insecure
}
domain localhost {
	domain key "${.OBJDIR}/etc/ssl/acme/private/privkey.pem"
	domain certificate "${.OBJDIR}/etc/ssl/acme/cert.pem"
	domain name 127.0.0.1
	alternative names {::1, "localhost"}
	profile "shortlived"
	sign with "pebble"
	challengedir "${.OBJDIR}/www/acme"
}

domain ::1 {
	domain key "${.OBJDIR}/etc/ssl/acme/private/privkey2.pem"
	domain certificate "${.OBJDIR}/etc/ssl/acme/cert2.pem"
	profile "shortlived"
	sign with "pebble"
	challengedir "${.OBJDIR}/www/acme"
}
