authority pebble-eab {
	account key "${.OBJDIR}/etc/acme/privkey-eab.pem"
	api url https://127.0.0.1:14001/dir
	insecure
}
domain localhost {
	domain key "${.OBJDIR}/etc/ssl/acme/private/privkey.pem"
	domain certificate "${.OBJDIR}/etc/ssl/acme/cert.pem"
	sign with "pebble-eab"
	challengedir "${.OBJDIR}/www/acme"
}
