.\"	$OpenBSD: mknetid.8,v 1.7 2000/03/19 17:57:18 aaron Exp $
.\"
.\" Copyright (c) 1996 Mats O Jansson <moj@stacken.kth.se>
.\" All rights reserved.
.\"
.\" Redistribution and use in source and binary forms, with or without
.\" modification, are permitted provided that the following conditions
.\" are met:
.\" 1. Redistributions of source code must retain the above copyright
.\"    notice, this list of conditions and the following disclaimer.
.\" 2. Redistributions in binary form must reproduce the above copyright
.\"    notice, this list of conditions and the following disclaimer in the
.\"    documentation and/or other materials provided with the distribution.
.\" 3. All advertising materials mentioning features or use of this software
.\"    must display the following acknowledgement:
.\"      This product includes software developed by Mats O Jansson
.\" 4. The name of the author may not be used to endorse or promote products
.\"    derived from this software without specific prior written permission.
.\"
.\" THIS SOFTWARE IS PROVIDED BY THE AUTHOR ``AS IS'' AND ANY EXPRESS
.\" OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED
.\" WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE
.\" ARE DISCLAIMED.  IN NO EVENT SHALL THE AUTHOR BE LIABLE FOR ANY
.\" DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL
.\" DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS
.\" OR SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION)
.\" HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT
.\" LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY
.\" OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF
.\" SUCH DAMAGE.
.\"
.Dd January 13, 1996
.Dt MKNETID 8
.Os
.Sh NAME
.Nm mknetid
.Nd a YP filter program
.Sh SYNOPSIS
.Nm mknetid
.Op Fl d Ar domain
.Op Fl q
.Op Fl p Ar passwdfile
.Op Fl g Ar groupfile
.Op Fl h Ar hostfile
.Op Fl m Ar netidfile
.Sh DESCRIPTION
.Nm
is used to create a map named
.Ar netid.byname .
The map consists of information from
.Xr passwd 5 ,
.Xr group 5
and
.Xr hosts 5
eventually concatenated with a
.Xr netid 5
file.
.Pp
The options are as follows:
.Bl -tag -width indent
.It Fl d Ar domain
Which yp-domain if not default yp-domain.
.It Fl q
Keep quiet about multiple occurrences of a UID.
Ignore all but the first.
.It Fl p Ar passwdfile
Alternate
.Xr passwd 5
file.
Default is
.Pa /etc/passwd .
.It Fl g Ar groupfile
Alternate
.Xr group 5
file.
Default is
.Pa /etc/group .
.It Fl h Ar hostfile
Alternate
.Xr hosts 5
file.
Default is
.Pa /etc/hosts .
.It Fl m Ar netidfile
Alternate
.Xr netid 5
file.
Default is
.Pa /etc/netid .
file.
.El
.Sh FILES
.Bl -tag -width /etc/passwd -compact
.It Pa /etc/passwd
.It Pa /etc/group
.It Pa /etc/hosts
.It Pa /etc/netid
.El
.Sh SEE ALSO
.Xr group 5 ,
.Xr hosts 5 ,
.Xr netid 5 ,
.Xr passwd 5 ,
.Xr yp 8
.Sh AUTHOR
Mats O Jansson <moj@stacken.kth.se>
