#	$OpenBSD: Makefile,v 1.9 2001/12/04 21:01:06 jason Exp $

# TODO: auxio.4 beeper.4 clock.4 ebus.4 pcons.4 psycho.4 sbus.4 timer.4
MAN=	audioce.4 audiocs.4 autoconf.4 be.4 cgsix.4 esp.4 gem.4 hme.4 intro.4 \
	le.4 mem.4 openprom.4 pcons.4 qe.4 qec.4 sab.4 zs.4
MLINKS=	mem.4 kmem.4 \
	sab.4 sabtty.4
MANSUBDIR=sparc64

.include <bsd.prog.mk>
