#	$OpenBSD: Makefile,v 1.42 2003/11/04 07:38:08 mickey Exp $

SUBDIR+= execve getrusage kqueue mmap mmap2 mmap3 dup2 minherit rlimit-file
SUBDIR+= fcntl_dup dup2_self pread preadv exit wait mbuf pwrite pwritev
SUBDIR+= syscall __syscall unfdpass accept nanosleep sysvmsg sysvsem
SUBDIR+= sysvshm rfork gettimeofday signal exec_self noexec
SUBDIR+= rcvtimeo

install:

.include <bsd.subdir.mk>
