#	$OpenBSD: Makefile,v 1.48 2005/04/21 17:45:52 miod Exp $

SUBDIR+= execve getrusage kqueue mmap mmap2 mmap3 dup2 minherit rlimit-file
SUBDIR+= fcntl_dup dup2_self ptmget pread preadv exit wait mbuf pwrite pwritev
SUBDIR+= syscall __syscall unfdpass accept nanosleep sysvmsg sysvsem
SUBDIR+= sysvshm gettimeofday signal exec_self noexec signal-stress
SUBDIR+= rcvtimeo itimer extent
#SUBDIR+= mquery rfork

install:

.include <bsd.subdir.mk>
