# $OpenBSD: Makefile,v 1.2 2000/03/01 22:10:12 todd Exp $
# $NetBSD: Makefile,v 1.1.1.1 1995/10/08 23:08:47 gwr Exp $
# Tiny ls  (i.e. for boot media)

PROG=	tls
NOMAN=

all: ${PROG}

.include <bsd.prog.mk>
