#	from: @(#)Makefile	5.1 (Berkeley) 6/29/90
#	$OpenBSD: Makefile,v 1.13 2006/01/10 07:37:31 miod Exp $

MAN=	adb.4 ae.4 akbd.4 ams.4 asc.4 autoconf.4 esp.4 intro.4 \
	macfb.4 mainbus.4 mc.4 mem.4 \
	ncrscsi.4 nubus.4 obio.4 sn.4 zsc.4
MLINKS=	mem.4 kmem.4 \
	ncrscsi.4 sbc.4 \
	zsc.4 zstty.4

MANSUBDIR=mac68k

.include <bsd.prog.mk>
