#	from: @(#)Makefile	5.1 (Berkeley) 6/29/90
#	$OpenBSD: Makefile,v 1.11 2005/01/29 13:38:37 martin Exp $

# TODO intvid nubus macvid grf ite
MAN=	adb.4 ae.4 asc.4 autoconf.4 esp.4 intro.4 mainbus.4 mc.4 mem.4 \
	ncrscsi.4 obio.4 sn.4 zsc.4
MLINKS=	mem.4 kmem.4 \
	ncrscsi.4 sbc.4 \
	zsc.4 zstty.4

MANSUBDIR=mac68k

.include <bsd.prog.mk>
