#	from: @(#)Makefile	5.1 (Berkeley) 6/29/90
#	$OpenBSD: Makefile,v 1.4 1998/02/05 09:26:11 deraadt Exp $

MAN=	ae.4 adb.4 autoconf.4 intro.4 mainbus.4 mem.4 sn.4
MLINKS=	mem.4 kmem.4
MANSUBDIR=/mac68k

.include <bsd.prog.mk>
