#	$OpenBSD: Makefile,v 1.12 2018/04/09 13:48:26 visa Exp $

MAN=	amdcf.4 cnmac.4 octcib.4 octcit.4 octciu.4 octcrypto.4 octmmc.4 \
	octrng.4 octrtc.4 octsctl.4 octuctl.4 octxctl.4
MANSUBDIR=octeon

.include <bsd.prog.mk>
