#	$OpenBSD: Makefile,v 1.15 2019/04/23 16:34:27 denis Exp $

MAN=	amdcf.4 cnmac.4 octcib.4 octcit.4 octciu.4 octcrypto.4 octgpio.4 \
	octiic.4 octmmc.4 octrng.4 octrtc.4 octsctl.4 octuctl.4 octxctl.4 \
	openprom.4
MANSUBDIR=octeon

.include <bsd.prog.mk>
