#	$OpenBSD: Makefile,v 1.19 2019/09/15 07:23:38 visa Exp $

MAN=	amdcf.4 cn30xxgmx.4 cnmac.4 octcf.4 octcib.4 octcit.4 octciu.4 \
	octcrypto.4 octgpio.4 octiic.4 octmmc.4 octpcie.4 octpip.4 \
	octrng.4 octrtc.4 octsctl.4 octuctl.4 octxctl.4

MANSUBDIR=octeon

.include <bsd.prog.mk>
