#	from: @(#)Makefile	5.10 (Berkeley) 5/11/90
#	$OpenBSD: Makefile,v 1.3 2000/03/28 05:54:39 deraadt Exp $

PROG=	ntalkd
SRCS=	talkd.c announce.c process.c table.c print.c
MAN=	talkd.8
MLINKS=	talkd.8 ntalkd.8

.include <bsd.prog.mk>
