.\"	$OpenBSD: CellServDB.5,v 1.1 2000/04/27 22:49:05 hin Exp $
.Dd April 19, 2000
.Dt CellServDB 5
.Os
.Sh NAME
.Nm CellServDB
.Nd AFS cells and database servers
.Sh DESCRIPTION
The file
.Nm
lists AFS cells known to the local AFS cache manager.
Each entry describes the name of an AFS cell and specifies the
servers for that cell.
.Pp
Here is an example of the format of an entry in the file:
.Bd -literal
>cellname		# Freetext comment describing the cell
ip-address		#first.server.for.cell
ip-address		#second.server.for.cell
ip-adresss		#third.server.for.cell
.Ed
.Pp
.Nm
is read when 
.Nm afsd
is started, normally when the system boots.
.Sh FILES
.Pa /etc/afs/CellServDB
.Sh SEE ALSO
.Xr afsd 8