.\"	$OpenBSD: ThisCell.5,v 1.2 2000/04/27 22:57:37 hin Exp $
.Dd April 19, 2000
.Dt ThisCell 5
.Os
.Sh NAME
.Nm ThisCell
.Nd specify a hosts home AFS cell
.Sh DESCRIPTION
The file
.Nm
specifies which cell the AFS cache manager belongs to. This affects the
default cell to use for commands such as
.Xr pts 1 ,
.Xr fs 1 ,
.Xr vos 8 ,
.Xr kauth 1 ,
.Xr kinit 1 ,
.Xr afslog 1 ,
but other cells can still be used.
It also affects where the cache manager reads the root of afs, so having
good connectivity to the default cell is very important.
.Sh SEE ALSO
.Xr afsd 8 ,
.Xr CellServDB 5
