#	$Id: Makefile,v 1.1.1.1 1995/10/18 08:46:25 deraadt Exp $

CFLAGS += -I${.CURDIR}/.. -I.

NOMAN = I mean it!

SRCS = mkhits.c dohits.c asc_ebc.c ebc_disp.c
PROG = mkhits

.include <bsd.prog.mk>

.PATH: ${.CURDIR}/../../api
