#	$OpenBSD: Makefile,v 1.2 1996/03/09 01:33:40 niklas Exp $

CFLAGS += -I${.CURDIR}/.. -I.

NOMAN = I mean it!

SRCS = mkhits.c dohits.c asc_ebc.c ebc_disp.c
PROG = mkhits

.include <bsd.prog.mk>

.PATH: ${.CURDIR}/../../api
