.\"	$OpenBSD: sgmsi.4,v 1.1 2025/12/02 20:03:19 kettenis Exp $
.\"
.\" Copyright (c) 2025 Mark Kettenis <kettenisg@openbsd.org>
.\"
.\" Permission to use, copy, modify, and distribute this software for any
.\" purpose with or without fee is hereby granted, provided that the above
.\" copyright notice and this permission notice appear in all copies.
.\"
.\" THE SOFTWARE IS PROVIDED "AS IS" AND THE AUTHOR DISCLAIMS ALL WARRANTIES
.\" WITH REGARD TO THIS SOFTWARE INCLUDING ALL IMPLIED WARRANTIES OF
.\" MERCHANTABILITY AND FITNESS. IN NO EVENT SHALL THE AUTHOR BE LIABLE FOR
.\" ANY SPECIAL, DIRECT, INDIRECT, OR CONSEQUENTIAL DAMAGES OR ANY DAMAGES
.\" WHATSOEVER RESULTING FROM LOSS OF USE, DATA OR PROFITS, WHETHER IN AN
.\" ACTION OF CONTRACT, NEGLIGENCE OR OTHER TORTIOUS ACTION, ARISING OUT OF
.\" OR IN CONNECTION WITH THE USE OR PERFORMANCE OF THIS SOFTWARE.
.\"
.Dd $Mdocdate: December 2 2025 $
.Dt SGMSI 4 riscv64
.Os
.Sh NAME
.Nm sgmsi
.Nd Sophgo MSI controller
.Sh SYNOPSIS
.Cd "sgmsi* at fdt?"
.Sh DESCRIPTION
The
.Nm
driver provides support for the MSI implementation found on Sophgo
SG2042 SoCs.
.Sh SEE ALSO
.Xr intro 4
.Sh HISTORY
The
.Nm
device driver first appeared in
.Ox 7.9 .
.Sh AUTHORS
.An -nosplit
The
.Nm
driver was written by
.An Mark Kettenis Aq Mt kettenis@openbsd.org .
