#!/bin/sh

# Copyright (c) 1999 Sendmail, Inc. and its suppliers.
#	All rights reserved.
#
# By using this file, you agree to the terms and conditions set
# forth in the LICENSE file which can be found at the top level of
# the sendmail distribution.
#
#
#	$Sendmail: Build,v 8.1 1999/05/21 22:56:21 gshapiro Exp $

exec ../devtools/bin/Build $*
