#	from: @(#)Makefile	8.1 (Berkeley) 6/4/93
#	$Id: Makefile,v 1.1.1.1 1995/10/18 08:43:13 deraadt Exp $

LIB=	util
CFLAGS+=-DLIBC_SCCS
SRCS=	login.c login_tty.c logout.c logwtmp.c pty.c

.include <bsd.lib.mk>
