/* radeon_drv.c -- ATI Radeon driver -*- linux-c -*-
 * Created: Wed Feb 14 17:10:04 2001 by gareth@valinux.com
 */
/*-
 * Copyright 2000 VA Linux Systems, Inc., Sunnyvale, California.
 * All Rights Reserved.
 *
 * Permission is hereby granted, free of charge, to any person obtaining a
 * copy of this software and associated documentation files (the "Software"),
 * to deal in the Software without restriction, including without limitation
 * the rights to use, copy, modify, merge, publish, distribute, sublicense,
 * and/or sell copies of the Software, and to permit persons to whom the
 * Software is furnished to do so, subject to the following conditions:
 *
 * The above copyright notice and this permission notice (including the next
 * paragraph) shall be included in all copies or substantial portions of the
 * Software.
 *
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
 * IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
 * FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT.  IN NO EVENT SHALL
 * VA LINUX SYSTEMS AND/OR ITS SUPPLIERS BE LIABLE FOR ANY CLAIM, DAMAGES OR
 * OTHER LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE,
 * ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR
 * OTHER DEALINGS IN THE SOFTWARE.
 *
 * Authors:
 *    Gareth Hughes <gareth@valinux.com>
 *
 */

#include "drmP.h"
#include "drm.h"
#include "radeon_drm.h"
#include "radeon_drv.h"

int	radeondrm_probe(struct device *, void *, void *);
void	radeondrm_attach(struct device *, struct device *, void *);
int	radeondrm_ioctl(struct drm_device *, u_long, caddr_t, struct drm_file *);

int radeon_no_wb;

static drm_pci_id_list_t radeon_pciidlist[] = {
	{PCI_VENDOR_ATI, PCI_PRODUCT_ATI_RADEON_M241P, CHIP_RV380|RADEON_IS_MOBILITY, "ATI Radeon Mobility X600 M24"},
	{PCI_VENDOR_ATI, PCI_PRODUCT_ATI_RADEON_X300M24, CHIP_RV380|RADEON_IS_MOBILITY|RADEON_NEW_MEMMAP, "ATI Radeon Mobility X300 M24"},
	{PCI_VENDOR_ATI, PCI_PRODUCT_ATI_FIREGL_M24GL, CHIP_RV380|RADEON_IS_MOBILITY|RADEON_NEW_MEMMAP, "ATI FireGL M24 GL"},
	{PCI_VENDOR_ATI, PCI_PRODUCT_ATI_RADEON_X600_RV380, CHIP_RV380|RADEON_NEW_MEMMAP, "ATI Radeon RV380 X600"},
	{PCI_VENDOR_ATI, PCI_PRODUCT_ATI_FIREGL_V3200, CHIP_RV380|RADEON_NEW_MEMMAP, "ATI FireGL V3200 RV380"},
	{PCI_VENDOR_ATI, PCI_PRODUCT_ATI_RADEON_IGP320, CHIP_RS100|RADEON_IS_IGP, "ATI Radeon RS100 IGP 320"},
	{PCI_VENDOR_ATI, PCI_PRODUCT_ATI_RADEON_IGP340, CHIP_RS200|RADEON_IS_IGP, "ATI Radeon RS200 IGP 340"},
	{PCI_VENDOR_ATI, PCI_PRODUCT_ATI_RADEON_9500PRO, CHIP_R300, "ATI Radeon AD 9500"},
	{PCI_VENDOR_ATI, PCI_PRODUCT_ATI_RADEON_AE9700PRO, CHIP_R300, "ATI Radeon AE 9700 Pro"},
	{PCI_VENDOR_ATI, PCI_PRODUCT_ATI_RADEON_AF9600TX, CHIP_R300, "ATI Radeon AF R300 9600TX"},
	{PCI_VENDOR_ATI, PCI_PRODUCT_ATI_FIREGL_AGZ1, CHIP_R300, "ATI FireGL AG Z1"},
	{PCI_VENDOR_ATI, PCI_PRODUCT_ATI_RADEON_AH_9800SE, CHIP_R350, "ATI Radeon AH 9800 SE"},
	{PCI_VENDOR_ATI, PCI_PRODUCT_ATI_RADEON_AI_9800, CHIP_R350, "ATI Radeon AI 9800"},
	{PCI_VENDOR_ATI, PCI_PRODUCT_ATI_RADEON_AJ_9800, CHIP_R350, "ATI Radeon AJ 9800"},
	{PCI_VENDOR_ATI, PCI_PRODUCT_ATI_FIREGL_AKX2, CHIP_R350, "ATI FireGL AK X2"},
	{PCI_VENDOR_ATI, PCI_PRODUCT_ATI_RADEON_9600PRO, CHIP_RV350, "ATI Radeon AP 9600"},
	{PCI_VENDOR_ATI, PCI_PRODUCT_ATI_RADEON_9600LE, CHIP_RV350, "ATI Radeon AQ 9600 SE"},
	{PCI_VENDOR_ATI, PCI_PRODUCT_ATI_RADEON_9600XT, CHIP_RV350, "ATI Radeon AR 9600 XT"},
	{PCI_VENDOR_ATI, PCI_PRODUCT_ATI_RADEON_9550, CHIP_RV350, "ATI Radeon AS 9550"},
	{PCI_VENDOR_ATI, PCI_PRODUCT_ATI_FIREGL_ATT2, CHIP_RV350, "ATI FireGL AT T2"},
	{PCI_VENDOR_ATI, PCI_PRODUCT_ATI_RADEON_9650, CHIP_RV350, "ATI Radeon 9650"},
	{PCI_VENDOR_ATI, PCI_PRODUCT_ATI_FIREGL_AVT2, CHIP_RV350, "ATI FireGL AV RV360 T2"},
	{PCI_VENDOR_ATI, PCI_PRODUCT_ATI_RADEON_IGP_RS250, CHIP_RS200|RADEON_IS_IGP, "ATI Radeon RS250 IGP"},
	{PCI_VENDOR_ATI, PCI_PRODUCT_ATI_R200_BB, CHIP_R200, "ATI Radeon BB R200 AIW 8500DV"},
	{PCI_VENDOR_ATI, PCI_PRODUCT_ATI_R200_BC, CHIP_R200, "ATI Radeon BC R200"},
	{PCI_VENDOR_ATI, PCI_PRODUCT_ATI_RADEON_IGP320M, CHIP_RS100|RADEON_IS_IGP|RADEON_IS_MOBILITY, "ATI Radeon RS100 Mobility U1"},
	{PCI_VENDOR_ATI, PCI_PRODUCT_ATI_MOBILITY_M6, CHIP_RS200|RADEON_IS_IGP|RADEON_IS_MOBILITY, "ATI Radeon RS200 Mobility IGP 340M"},
	{PCI_VENDOR_ATI, PCI_PRODUCT_ATI_RADEON_MIGP_RS250, CHIP_RS200|RADEON_IS_IGP|RADEON_IS_MOBILITY, "ATI Radeon RS250 Mobility IGP"},
	{PCI_VENDOR_ATI, PCI_PRODUCT_ATI_RV250, CHIP_RV250, "ATI Radeon If RV250 9000"},
	{PCI_VENDOR_ATI, PCI_PRODUCT_ATI_RADEON_IG9000, CHIP_RV250, "ATI Radeon Ig RV250 9000"},
	{PCI_VENDOR_ATI, PCI_PRODUCT_ATI_RADEON_JHX800, CHIP_R420|RADEON_NEW_MEMMAP, "ATI Radeon JH R420 X800"},
	{PCI_VENDOR_ATI, PCI_PRODUCT_ATI_RADEON_X800PRO, CHIP_R420|RADEON_NEW_MEMMAP, "ATI Radeon JI R420 X800 Pro"},
	{PCI_VENDOR_ATI, PCI_PRODUCT_ATI_RADEON_X800SE, CHIP_R420|RADEON_NEW_MEMMAP, "ATI Radeon JJ R420 X800 SE"},
	{PCI_VENDOR_ATI, PCI_PRODUCT_ATI_RADEON_X800XT, CHIP_R420|RADEON_NEW_MEMMAP, "ATI Radeon JK R420 X800 XT"},
	{PCI_VENDOR_ATI, PCI_PRODUCT_ATI_RADEON_X800, CHIP_R420|RADEON_NEW_MEMMAP, "ATI Radeon JL R420 X800"},
	{PCI_VENDOR_ATI, PCI_PRODUCT_ATI_FIREGL_X3256, CHIP_R420|RADEON_NEW_MEMMAP, "ATI FireGL JM X3-256"},
	{PCI_VENDOR_ATI, PCI_PRODUCT_ATI_MOBILITY_M18, CHIP_R420|RADEON_IS_MOBILITY|RADEON_NEW_MEMMAP, "ATI Radeon JN R420 Mobility M18"},
	{PCI_VENDOR_ATI, PCI_PRODUCT_ATI_RADEON_JOX800SE, CHIP_R420|RADEON_NEW_MEMMAP, "ATI Radeon JO R420 X800 SE"},
	{PCI_VENDOR_ATI, PCI_PRODUCT_ATI_RADEON_X800XTPE, CHIP_R420|RADEON_NEW_MEMMAP, "ATI Radeon JP R420 X800 XT PE"},
	{PCI_VENDOR_ATI, PCI_PRODUCT_ATI_RADEON_AIW_X800VE, CHIP_R420|RADEON_NEW_MEMMAP, "ATI Radeon JT R420 AIW X800 VE"},
	{PCI_VENDOR_ATI, PCI_PRODUCT_ATI_RADEON_X850XT, CHIP_R420|RADEON_NEW_MEMMAP, "ATI Radeon R481 X850 XT"},
	{PCI_VENDOR_ATI, PCI_PRODUCT_ATI_RADEON_X850SE, CHIP_R420|RADEON_NEW_MEMMAP, "ATI Radeon R481 X850 SE"},
	{PCI_VENDOR_ATI, PCI_PRODUCT_ATI_RADEON_X850PRO, CHIP_R420|RADEON_NEW_MEMMAP, "ATI Radeon R481 X850 Pro"},
	{PCI_VENDOR_ATI, PCI_PRODUCT_ATI_RADEON_X850XTPE, CHIP_R420|RADEON_NEW_MEMMAP, "ATI Radeon R481 X850 XT PE"},
	{PCI_VENDOR_ATI, PCI_PRODUCT_ATI_RADEON_M7LW, CHIP_RV200|RADEON_IS_MOBILITY, "ATI Radeon LW RV200 Mobility 7500 M7"},
	{PCI_VENDOR_ATI, PCI_PRODUCT_ATI_FIREGL_M7, CHIP_RV200|RADEON_IS_MOBILITY, "ATI Radeon LX RV200 Mobility FireGL 7800 M7"},
	{PCI_VENDOR_ATI, PCI_PRODUCT_ATI_RADEON_M6LY, CHIP_RV100|RADEON_IS_MOBILITY, "ATI Radeon LY RV100 Mobility M6"},
	{PCI_VENDOR_ATI, PCI_PRODUCT_ATI_RADEON_M6LZ, CHIP_RV100|RADEON_IS_MOBILITY, "ATI Radeon LZ RV100 Mobility M6"},
	{PCI_VENDOR_ATI, PCI_PRODUCT_ATI_RADEON_M9LD, CHIP_RV250|RADEON_IS_MOBILITY, "ATI Radeon Ld RV250 Mobility 9000 M9"},
	{PCI_VENDOR_ATI, PCI_PRODUCT_ATI_RADEON_M9Lf, CHIP_RV250, "ATI Radeon Lf RV250 Mobility 9000 M9 / FireMV 2400 PCI"},
	{PCI_VENDOR_ATI, PCI_PRODUCT_ATI_RADEON_M9Lg, CHIP_RV250|RADEON_IS_MOBILITY, "ATI Radeon Lg RV250 Mobility 9000 M9"},
	{PCI_VENDOR_ATI, PCI_PRODUCT_ATI_R300, CHIP_R300, "ATI Radeon ND R300 9700 Pro"},
	{PCI_VENDOR_ATI, PCI_PRODUCT_ATI_RADEON9500_PRO, CHIP_R300, "ATI Radeon NE R300 9500 Pro / 9700"},
	{PCI_VENDOR_ATI, PCI_PRODUCT_ATI_RADEON9600TX, CHIP_R300, "ATI Radeon NF R300 9600TX"},
	{PCI_VENDOR_ATI, PCI_PRODUCT_ATI_FIREGL_X1, CHIP_R300, "ATI Radeon NG R300 FireGL X1"},
	{PCI_VENDOR_ATI, PCI_PRODUCT_ATI_R350, CHIP_R350, "ATI Radeon NH R350 9800 Pro"},
	{PCI_VENDOR_ATI, PCI_PRODUCT_ATI_RADEON9800, CHIP_R350, "ATI Radeon NI R350 9800"},
	{PCI_VENDOR_ATI, PCI_PRODUCT_ATI_RADEON_9800XT, CHIP_R350, "ATI Radeon NJ R360 9800 XT"},
	{PCI_VENDOR_ATI, PCI_PRODUCT_ATI_FIREGL_X2, CHIP_R350, "ATI FireGL NK X2"},
	{PCI_VENDOR_ATI, PCI_PRODUCT_ATI_RV350, CHIP_RV350|RADEON_IS_MOBILITY, "ATI Radeon RV350 Mobility 9600 M10 NP"},
	{PCI_VENDOR_ATI, PCI_PRODUCT_ATI_RV350NQ, CHIP_RV350|RADEON_IS_MOBILITY, "ATI Radeon RV350 Mobility 9600 M10 NQ"},
	{PCI_VENDOR_ATI, PCI_PRODUCT_ATI_RV350NR, CHIP_RV350|RADEON_IS_MOBILITY, "ATI Radeon RV350 Mobility 9600 M11 NR"},
	{PCI_VENDOR_ATI, PCI_PRODUCT_ATI_RV350NS, CHIP_RV350|RADEON_IS_MOBILITY, "ATI Radeon RV350 Mobility 9600 M10 NS"},
	{PCI_VENDOR_ATI, PCI_PRODUCT_ATI_RV350_WS, CHIP_RV350|RADEON_IS_MOBILITY, "ATI FireGL T2/T2e"},
	{PCI_VENDOR_ATI, PCI_PRODUCT_ATI_MOBILITY_9550, CHIP_RV350|RADEON_IS_MOBILITY, "ATI Radeon Mobility 9550"},
	{PCI_VENDOR_ATI, PCI_PRODUCT_ATI_RADEON_AIW, CHIP_R100|RADEON_SINGLE_CRTC, "ATI Radeon QD R100"},
	{PCI_VENDOR_ATI, PCI_PRODUCT_ATI_RADEON_QE, CHIP_R100|RADEON_SINGLE_CRTC, "ATI Radeon QE R100"},
	{PCI_VENDOR_ATI, PCI_PRODUCT_ATI_RADEON_QF, CHIP_R100|RADEON_SINGLE_CRTC, "ATI Radeon QF R100"},
	{PCI_VENDOR_ATI, PCI_PRODUCT_ATI_RADEON_QG, CHIP_R100|RADEON_SINGLE_CRTC, "ATI Radeon QG R100"},
	{PCI_VENDOR_ATI, PCI_PRODUCT_ATI_RADEON_QH, CHIP_R200, "ATI Radeon QH R200 8500"},
	{PCI_VENDOR_ATI, PCI_PRODUCT_ATI_R200_QL, CHIP_R200, "ATI Radeon QL R200 8500 LE"},
	{PCI_VENDOR_ATI, PCI_PRODUCT_ATI_R200_QM, CHIP_R200, "ATI Radeon QM R200 9100"},
	{PCI_VENDOR_ATI, PCI_PRODUCT_ATI_RV200_QW, CHIP_RV200, "ATI Radeon QW RV200 7500"},
	{PCI_VENDOR_ATI, PCI_PRODUCT_ATI_RV200_QX, CHIP_RV200, "ATI Radeon QX RV200 7500"},
	{PCI_VENDOR_ATI, PCI_PRODUCT_ATI_RADEON_QY, CHIP_RV100, "ATI Radeon QY RV100 7000/VE"},
	{PCI_VENDOR_ATI, PCI_PRODUCT_ATI_RADEON_QZ, CHIP_RV100, "ATI Radeon QZ RV100 7000/VE"},
	{PCI_VENDOR_ATI, PCI_PRODUCT_ATI_ES1000_1, CHIP_RV100, "ATI ES1000 RN50"},
	{PCI_VENDOR_ATI, PCI_PRODUCT_ATI_RADEON_M300_M22, CHIP_RV380|RADEON_IS_MOBILITY, "ATI Radeon Mobility X300 M22"},
	{PCI_VENDOR_ATI, PCI_PRODUCT_ATI_RADEON_X600_M24C, CHIP_RV380|RADEON_IS_MOBILITY, "ATI Radeon Mobility X600 SE M24C"},
	{PCI_VENDOR_ATI, PCI_PRODUCT_ATI_FIREGL_M44, CHIP_RV380|RADEON_IS_MOBILITY, "ATI FireGL M22 GL 5464"},
	{PCI_VENDOR_ATI, PCI_PRODUCT_ATI_RADEON_X800_RV423, CHIP_R423|RADEON_NEW_MEMMAP, "ATI Radeon R423 X800"},
	{PCI_VENDOR_ATI, PCI_PRODUCT_ATI_RADEON_X800PRORV423, CHIP_R423|RADEON_NEW_MEMMAP, "ATI Radeon R423 X800 Pro"},
	{PCI_VENDOR_ATI, PCI_PRODUCT_ATI_RADEON_X800XT_RV423, CHIP_R423|RADEON_NEW_MEMMAP, "ATI Radeon R423 X800 XT PE"},
	{PCI_VENDOR_ATI, PCI_PRODUCT_ATI_RADEON_X800SE_RV423, CHIP_R423|RADEON_NEW_MEMMAP, "ATI Radeon R423 X800 SE"},
	{PCI_VENDOR_ATI, PCI_PRODUCT_ATI_RADEON_X800XTPRV430, CHIP_R423|RADEON_NEW_MEMMAP, "ATI Radeon R430 X800 XTP"},
	{PCI_VENDOR_ATI, PCI_PRODUCT_ATI_RADEON_X800XL_RV430, CHIP_R423|RADEON_NEW_MEMMAP, "ATI Radeon R430 X800 XL"},
	{PCI_VENDOR_ATI, PCI_PRODUCT_ATI_RADEON_X800SE_RV430, CHIP_R423|RADEON_NEW_MEMMAP, "ATI Radeon R430 X800 SE"},
	{PCI_VENDOR_ATI, PCI_PRODUCT_ATI_RADEON_X800_RV430, CHIP_R423|RADEON_NEW_MEMMAP, "ATI Radeon R430 X800"},
	{PCI_VENDOR_ATI, PCI_PRODUCT_ATI_FIREGL_V7100_RV423, CHIP_R423|RADEON_NEW_MEMMAP, "ATI FireGL V7100 R423"},
	{PCI_VENDOR_ATI, PCI_PRODUCT_ATI_FIREGL_V5100_RV423, CHIP_R423|RADEON_NEW_MEMMAP, "ATI FireGL V5100 R423 UQ"},
	{PCI_VENDOR_ATI, PCI_PRODUCT_ATI_FIREGL_UR_RV423, CHIP_R423|RADEON_NEW_MEMMAP, "ATI FireGL unknown R423 UR"},
	{PCI_VENDOR_ATI, PCI_PRODUCT_ATI_FIREGL_UT_RV423, CHIP_R423|RADEON_NEW_MEMMAP, "ATI FireGL unknown R423 UT"},
	{PCI_VENDOR_ATI, PCI_PRODUCT_ATI_FIREGL_V5000_M26, CHIP_RV410|RADEON_IS_MOBILITY|RADEON_NEW_MEMMAP, "ATI Mobility FireGL V5000 M26"},
	{PCI_VENDOR_ATI, PCI_PRODUCT_ATI_FIREGL_V5000_M26b, CHIP_RV410|RADEON_IS_MOBILITY|RADEON_NEW_MEMMAP, "ATI Mobility FireGL V5000 M26"},
	{PCI_VENDOR_ATI, PCI_PRODUCT_ATI_RADEON_X700XL_M26, CHIP_RV410|RADEON_IS_MOBILITY|RADEON_NEW_MEMMAP, "ATI Radeon Mobility X700 XL M26"},
	{PCI_VENDOR_ATI, PCI_PRODUCT_ATI_RADEON_X700_M26_1, CHIP_RV410|RADEON_IS_MOBILITY|RADEON_NEW_MEMMAP, "ATI Radeon Mobility X700 M26"},
	{PCI_VENDOR_ATI, PCI_PRODUCT_ATI_RADEON_X700_M26_2, CHIP_RV410|RADEON_IS_MOBILITY|RADEON_NEW_MEMMAP, "ATI Radeon Mobility X700 M26"},
	{PCI_VENDOR_ATI, PCI_PRODUCT_ATI_RADEON_X550XTX, CHIP_RV410|RADEON_NEW_MEMMAP, "ATI Radeon X550XTX"},
	{PCI_VENDOR_ATI, PCI_PRODUCT_ATI_RADEON_IGP9100_IGP, CHIP_RS300|RADEON_IS_IGP, "ATI Radeon RS300 9100 IGP"},
	{PCI_VENDOR_ATI, PCI_PRODUCT_ATI_RADEON_IGP9100, CHIP_RS300|RADEON_IS_IGP|RADEON_IS_MOBILITY, "ATI Radeon RS300 Mobility IGP"},
	{PCI_VENDOR_ATI, PCI_PRODUCT_ATI_RADEON_RS480, CHIP_RS480|RADEON_IS_IGP|RADEON_IS_IGPGART, "ATI RS480 XPRESS 200G"},
	{PCI_VENDOR_ATI, PCI_PRODUCT_ATI_RADEON_RS480_B, CHIP_RS480|RADEON_IS_IGP|RADEON_IS_MOBILITY|RADEON_IS_IGPGART, "ATI Radeon XPRESS 200M 5955"},
	{PCI_VENDOR_ATI, PCI_PRODUCT_ATI_RADEON_RS482, CHIP_RS480|RADEON_IS_IGP|RADEON_IS_MOBILITY|RADEON_IS_IGPGART, "ATI Radeon RS482 XPRESS 200"},
	{PCI_VENDOR_ATI, PCI_PRODUCT_ATI_RADEON_RS482_B, CHIP_RS480|RADEON_IS_IGP|RADEON_IS_MOBILITY|RADEON_IS_IGPGART, "ATI Radeon RS485 XPRESS 1100 IGP"},
	{PCI_VENDOR_ATI, PCI_PRODUCT_ATI_RADEON_RV280_PRO, CHIP_RV280, "ATI Radeon RV280 9250"},
	{PCI_VENDOR_ATI, PCI_PRODUCT_ATI_RADEON_RV280, CHIP_RV280, "ATI Radeon RV280 9200"},
	{PCI_VENDOR_ATI, PCI_PRODUCT_ATI_RADEON_RV280_B, CHIP_RV280, "ATI Radeon RV280 9200"},
	{PCI_VENDOR_ATI, PCI_PRODUCT_ATI_RADEON_RV280_SE_S, CHIP_RV280, "ATI Radeon RV280 9200 SE"},
	{PCI_VENDOR_ATI, PCI_PRODUCT_ATI_FIREMV_2200, CHIP_RV280, "ATI FireMV 2200 PCI"},
	{PCI_VENDOR_ATI, PCI_PRODUCT_ATI_ES1000, CHIP_RV100, "ATI ES1000 RN50"},
	{PCI_VENDOR_ATI, PCI_PRODUCT_ATI_RADEON_RS400, CHIP_RS400|RADEON_IS_IGP|RADEON_IS_IGPGART, "ATI Radeon XPRESS 200 5A41 (PCIE)"},
	{PCI_VENDOR_ATI, PCI_PRODUCT_ATI_RADEON_RS400_B, CHIP_RS400|RADEON_IS_IGP|RADEON_IS_MOBILITY|RADEON_IS_IGPGART, "ATI Radeon XPRESS 200M 5A42 (PCIE)"},
	{PCI_VENDOR_ATI, PCI_PRODUCT_ATI_RADEON_RC410, CHIP_RS400|RADEON_IS_IGP|RADEON_IS_IGPGART, "ATI Radeon RC410 XPRESS 200"},
	{PCI_VENDOR_ATI, PCI_PRODUCT_ATI_RADEON_RC410_B, CHIP_RS400|RADEON_IS_IGP|RADEON_IS_MOBILITY|RADEON_IS_IGPGART, "ATI Radeon RC410 XPRESS 200M"},
	{PCI_VENDOR_ATI, PCI_PRODUCT_ATI_RADEON_X300, CHIP_RV380|RADEON_NEW_MEMMAP, "ATI Radeon RV370 X300 SE"},
	{PCI_VENDOR_ATI, PCI_PRODUCT_ATI_RADEON_X600_RV370, CHIP_RV380|RADEON_NEW_MEMMAP, "ATI Radeon RV370 X600 Pro"},
	{PCI_VENDOR_ATI, PCI_PRODUCT_ATI_RADEON_X550, CHIP_RV380|RADEON_NEW_MEMMAP, "ATI Radeon RV370 X550"},
	{PCI_VENDOR_ATI, PCI_PRODUCT_ATI_FIREGL_RV370, CHIP_RV380|RADEON_NEW_MEMMAP, "ATI FireGL V3100 (RV370) 5B64"},
	{PCI_VENDOR_ATI, PCI_PRODUCT_ATI_FIREMV_2200_5B65, CHIP_RV380|RADEON_NEW_MEMMAP, "ATI FireMV 2200 PCIE (RV370) 5B65"},
	{PCI_VENDOR_ATI, PCI_PRODUCT_ATI_RADEON_RV280_M, CHIP_RV280|RADEON_IS_MOBILITY, "ATI Radeon RV280 Mobility"},
	{PCI_VENDOR_ATI, PCI_PRODUCT_ATI_RADEON_M9PLUS, CHIP_RV280|RADEON_IS_MOBILITY, "ATI Radeon RV280 Mobility"},
	{PCI_VENDOR_ATI, PCI_PRODUCT_ATI_RADEON_X800XT_M28, CHIP_R423|RADEON_IS_MOBILITY|RADEON_NEW_MEMMAP, "ATI Mobility Radeon X800 XT M28"},
	{PCI_VENDOR_ATI, PCI_PRODUCT_ATI_FIREGL_V5100_M28, CHIP_R423|RADEON_IS_MOBILITY|RADEON_NEW_MEMMAP, "ATI Mobility FireGL V5100 M28"},
	{PCI_VENDOR_ATI, PCI_PRODUCT_ATI_MOBILITY_X800_M28, CHIP_R423|RADEON_IS_MOBILITY|RADEON_NEW_MEMMAP, "ATI Mobility Radeon X800 M28"},
	{PCI_VENDOR_ATI, PCI_PRODUCT_ATI_RADEON_X850_R480, CHIP_R423|RADEON_NEW_MEMMAP, "ATI Radeon R480 X850"},
	{PCI_VENDOR_ATI, PCI_PRODUCT_ATI_RADEON_X850XTPER480, CHIP_R423|RADEON_NEW_MEMMAP, "ATI Radeon R480 X850 XT PE"},
	{PCI_VENDOR_ATI, PCI_PRODUCT_ATI_RADEON_X850SE_R480, CHIP_R423|RADEON_NEW_MEMMAP, "ATI Radeon R480 X850 SE"},
	{PCI_VENDOR_ATI, PCI_PRODUCT_ATI_RADEON_X800_GTO, CHIP_R423|RADEON_NEW_MEMMAP, "ATI Radeon R480 X850 Pro"},
	{PCI_VENDOR_ATI, PCI_PRODUCT_ATI_FIREGL_R480, CHIP_R423|RADEON_NEW_MEMMAP, "ATI unknown Radeon / FireGL R480"},
	{PCI_VENDOR_ATI, PCI_PRODUCT_ATI_RADEON_X850XT_R480, CHIP_R423|RADEON_NEW_MEMMAP, "ATI Radeon R480 X850 XT"},
	{PCI_VENDOR_ATI, PCI_PRODUCT_ATI_RADEON_X800XT_R423, CHIP_R423|RADEON_NEW_MEMMAP, "ATI Radeon R423 X800 XT"},
	{PCI_VENDOR_ATI, PCI_PRODUCT_ATI_FIREGL_V5000_R410, CHIP_RV410|RADEON_NEW_MEMMAP, "ATI FireGL V5000 RV410"},
	{PCI_VENDOR_ATI, PCI_PRODUCT_ATI_RADEON_X700XT_R410, CHIP_RV410|RADEON_NEW_MEMMAP, "ATI Radeon RV410 X700 XT"},
	{PCI_VENDOR_ATI, PCI_PRODUCT_ATI_RADEON_X700PRO_R410, CHIP_RV410|RADEON_NEW_MEMMAP, "ATI Radeon RV410 X700 Pro"},
	{PCI_VENDOR_ATI, PCI_PRODUCT_ATI_RADEON_X700SE_R410, CHIP_RV410|RADEON_NEW_MEMMAP, "ATI Radeon RV410 X700 SE"},
	{PCI_VENDOR_ATI, PCI_PRODUCT_ATI_RADEON_X700_PCIE, CHIP_RV410|RADEON_NEW_MEMMAP, "ATI Radeon RV410 X700"},
	{PCI_VENDOR_ATI, PCI_PRODUCT_ATI_RADEON_X700SE_PCIE, CHIP_RV410|RADEON_NEW_MEMMAP, "ATI Radeon RV410 X700 SE"},
	{PCI_VENDOR_ATI, PCI_PRODUCT_ATI_RADEON_X1800A, CHIP_R520|RADEON_NEW_MEMMAP, "ATI Radeon X1800"},
	{PCI_VENDOR_ATI, PCI_PRODUCT_ATI_RADEON_X1800XT, CHIP_R520|RADEON_IS_MOBILITY|RADEON_NEW_MEMMAP, "ATI Mobility Radeon X1800 XT"},
	{PCI_VENDOR_ATI, PCI_PRODUCT_ATI_MOBILITY_X1800, CHIP_R520|RADEON_IS_MOBILITY|RADEON_NEW_MEMMAP, "ATI Mobility Radeon X1800"},
	{PCI_VENDOR_ATI, PCI_PRODUCT_ATI_FIREGL_M_V7200, CHIP_R520|RADEON_IS_MOBILITY|RADEON_NEW_MEMMAP, "ATI Mobility FireGL V7200"},
	{PCI_VENDOR_ATI, PCI_PRODUCT_ATI_FIREGL_M_V7200, CHIP_R520|RADEON_NEW_MEMMAP, "ATI FireGL V7200"},
	{PCI_VENDOR_ATI, PCI_PRODUCT_ATI_FIREGL_V5300, CHIP_R520|RADEON_NEW_MEMMAP, "ATI FireGL V5300"},
	{PCI_VENDOR_ATI, PCI_PRODUCT_ATI_FIREGL_M_V7100, CHIP_R520|RADEON_IS_MOBILITY|RADEON_NEW_MEMMAP, "ATI Mobility FireGL V7100"},
	{PCI_VENDOR_ATI, PCI_PRODUCT_ATI_RADEON_X1800B, CHIP_R520|RADEON_NEW_MEMMAP, "ATI Radeon X1800"},
	{PCI_VENDOR_ATI, PCI_PRODUCT_ATI_RADEON_X1800C, CHIP_R520|RADEON_NEW_MEMMAP, "ATI Radeon X1800"},
	{PCI_VENDOR_ATI, PCI_PRODUCT_ATI_RADEON_X1800D, CHIP_R520|RADEON_NEW_MEMMAP, "ATI Radeon X1800"},
	{PCI_VENDOR_ATI, PCI_PRODUCT_ATI_RADEON_X1800E, CHIP_R520|RADEON_NEW_MEMMAP, "ATI Radeon X1800"},
	{PCI_VENDOR_ATI, PCI_PRODUCT_ATI_RADEON_X1800F, CHIP_R520|RADEON_NEW_MEMMAP, "ATI Radeon X1800"},
	{PCI_VENDOR_ATI, PCI_PRODUCT_ATI_FIREGL_V7300, CHIP_R520|RADEON_NEW_MEMMAP, "ATI FireGL V7300"},
	{PCI_VENDOR_ATI, PCI_PRODUCT_ATI_FIREGL_V7350, CHIP_R520|RADEON_NEW_MEMMAP, "ATI FireGL V7350"},
	{PCI_VENDOR_ATI, PCI_PRODUCT_ATI_RADEON_X1600, CHIP_RV515|RADEON_NEW_MEMMAP, "ATI Radeon X1600"},
	{PCI_VENDOR_ATI, PCI_PRODUCT_ATI_RV505_1, CHIP_RV515|RADEON_NEW_MEMMAP, "ATI RV505"},
	{PCI_VENDOR_ATI, PCI_PRODUCT_ATI_RADEON_X1300_X1550, CHIP_RV515|RADEON_NEW_MEMMAP, "ATI Radeon X1300/X1550"},
	{PCI_VENDOR_ATI, PCI_PRODUCT_ATI_RADEON_X1550, CHIP_RV515|RADEON_NEW_MEMMAP, "ATI Radeon X1550"},
	{PCI_VENDOR_ATI, PCI_PRODUCT_ATI_M54_GL, CHIP_RV515|RADEON_IS_MOBILITY|RADEON_NEW_MEMMAP, "ATI M54-GL"},
	{PCI_VENDOR_ATI, PCI_PRODUCT_ATI_RADEON_X1400, CHIP_RV515|RADEON_IS_MOBILITY|RADEON_NEW_MEMMAP, "ATI Mobility Radeon X1400"},
	{PCI_VENDOR_ATI, PCI_PRODUCT_ATI_RADEON_X1550_X1300, CHIP_RV515|RADEON_NEW_MEMMAP, "ATI Radeon X1300/X1550"},
	{PCI_VENDOR_ATI, PCI_PRODUCT_ATI_RADEON_X1550_64, CHIP_RV515|RADEON_NEW_MEMMAP, "ATI Radeon X1550 64-bit"},
	{PCI_VENDOR_ATI, PCI_PRODUCT_ATI_RADEON_X1300_M52, CHIP_RV515|RADEON_IS_MOBILITY|RADEON_NEW_MEMMAP, "ATI Mobility Radeon X1300"},
	{PCI_VENDOR_ATI, PCI_PRODUCT_ATI_MOBILITY_X1300_4A, CHIP_RV515|RADEON_IS_MOBILITY|RADEON_NEW_MEMMAP, "ATI Mobility Radeon X1300"},
	{PCI_VENDOR_ATI, PCI_PRODUCT_ATI_MOBILITY_X1300_4B, CHIP_RV515|RADEON_IS_MOBILITY|RADEON_NEW_MEMMAP, "ATI Mobility Radeon X1300"},
	{PCI_VENDOR_ATI, PCI_PRODUCT_ATI_MOBILITY_X1300_4C, CHIP_RV515|RADEON_IS_MOBILITY|RADEON_NEW_MEMMAP, "ATI Mobility Radeon X1300"},
	{PCI_VENDOR_ATI, PCI_PRODUCT_ATI_RADEON_X1300_4D, CHIP_RV515|RADEON_NEW_MEMMAP, "ATI Radeon X1300"},
	{PCI_VENDOR_ATI, PCI_PRODUCT_ATI_RADEON_X1300_4E, CHIP_RV515|RADEON_NEW_MEMMAP, "ATI Radeon X1300"},
	{PCI_VENDOR_ATI, PCI_PRODUCT_ATI_RV505_2, CHIP_RV515|RADEON_NEW_MEMMAP, "ATI RV505"},
	{PCI_VENDOR_ATI, PCI_PRODUCT_ATI_RV505_3, CHIP_RV515|RADEON_NEW_MEMMAP, "ATI RV505"},
	{PCI_VENDOR_ATI, PCI_PRODUCT_ATI_FIREGL_V3300, CHIP_RV515|RADEON_NEW_MEMMAP, "ATI FireGL V3300"},
	{PCI_VENDOR_ATI, PCI_PRODUCT_ATI_FIREGL_V3350, CHIP_RV515|RADEON_NEW_MEMMAP, "ATI FireGL V3350"},
	{PCI_VENDOR_ATI, PCI_PRODUCT_ATI_RADEON_X1300_5E, CHIP_RV515|RADEON_NEW_MEMMAP, "ATI Radeon X1300"},
	{PCI_VENDOR_ATI, PCI_PRODUCT_ATI_RADEON_X1550_64_2, CHIP_RV515|RADEON_NEW_MEMMAP, "ATI Radeon X1550 64-bit"},
	{PCI_VENDOR_ATI, PCI_PRODUCT_ATI_RADEON_X1300X1550, CHIP_RV515|RADEON_NEW_MEMMAP, "ATI Radeon X1300/X1550"},
	{PCI_VENDOR_ATI, PCI_PRODUCT_ATI_RADEON_X1600_81, CHIP_RV515|RADEON_NEW_MEMMAP, "ATI Radeon X1600"},
	{PCI_VENDOR_ATI, PCI_PRODUCT_ATI_RADEON_X1300PRO, CHIP_RV515|RADEON_NEW_MEMMAP, "ATI Radeon X1300/X1550"},
	{PCI_VENDOR_ATI, PCI_PRODUCT_ATI_RADEON_X1450, CHIP_RV515|RADEON_IS_MOBILITY|RADEON_NEW_MEMMAP, "ATI Mobility Radeon X1450"},
	{PCI_VENDOR_ATI, PCI_PRODUCT_ATI_RADEON_X1300, CHIP_RV515|RADEON_NEW_MEMMAP, "ATI Radeon X1300/X1550"},
	{PCI_VENDOR_ATI, PCI_PRODUCT_ATI_RADEON_X2300, CHIP_RV515|RADEON_IS_MOBILITY|RADEON_NEW_MEMMAP, "ATI Mobility Radeon X2300"},
	{PCI_VENDOR_ATI, PCI_PRODUCT_ATI_RADEON_X2300_2, CHIP_RV515|RADEON_IS_MOBILITY|RADEON_NEW_MEMMAP, "ATI Mobility Radeon X2300"},
	{PCI_VENDOR_ATI, PCI_PRODUCT_ATI_MOBILITY_X1350, CHIP_RV515|RADEON_IS_MOBILITY|RADEON_NEW_MEMMAP, "ATI Mobility Radeon X1350"},
	{PCI_VENDOR_ATI, PCI_PRODUCT_ATI_MOBILITY_X1350_2, CHIP_RV515|RADEON_IS_MOBILITY|RADEON_NEW_MEMMAP, "ATI Mobility Radeon X1350"},
	{PCI_VENDOR_ATI, PCI_PRODUCT_ATI_MOBILITY_X1450, CHIP_RV515|RADEON_IS_MOBILITY|RADEON_NEW_MEMMAP, "ATI Mobility Radeon X1450"},
	{PCI_VENDOR_ATI, PCI_PRODUCT_ATI_RADEON_X1300_8F, CHIP_RV515|RADEON_NEW_MEMMAP, "ATI Radeon X1300"},
	{PCI_VENDOR_ATI, PCI_PRODUCT_ATI_RADEON_X1550_2, CHIP_RV515|RADEON_NEW_MEMMAP, "ATI Radeon X1550"},
	{PCI_VENDOR_ATI, PCI_PRODUCT_ATI_MOBILITY_X1350_3, CHIP_RV515|RADEON_IS_MOBILITY|RADEON_NEW_MEMMAP, "ATI Mobility Radeon X1350"},
	{PCI_VENDOR_ATI, PCI_PRODUCT_ATI_FIREMV_2250, CHIP_RV515|RADEON_NEW_MEMMAP, "ATI FireMV 2250"},
	{PCI_VENDOR_ATI, PCI_PRODUCT_ATI_RADEON_X1550_64_3, CHIP_RV515|RADEON_NEW_MEMMAP, "ATI Radeon X1550 64-bit"},
	{PCI_VENDOR_ATI, PCI_PRODUCT_ATI_RADEON_X1600_C0, CHIP_RV530|RADEON_NEW_MEMMAP, "ATI Radeon X1600"},
	{PCI_VENDOR_ATI, PCI_PRODUCT_ATI_RADEON_X1650, CHIP_RV530|RADEON_NEW_MEMMAP, "ATI Radeon X1650"},
	{PCI_VENDOR_ATI, PCI_PRODUCT_ATI_RADEON_X1600_PRO, CHIP_RV530|RADEON_NEW_MEMMAP, "ATI Radeon X1600"},
	{PCI_VENDOR_ATI, PCI_PRODUCT_ATI_RADEON_X1600_C3, CHIP_RV530|RADEON_NEW_MEMMAP, "ATI Radeon X1600"},
	{PCI_VENDOR_ATI, PCI_PRODUCT_ATI_FIREGL_V5200, CHIP_RV530|RADEON_IS_MOBILITY|RADEON_NEW_MEMMAP, "ATI Mobility FireGL V5200"},
	{PCI_VENDOR_ATI, PCI_PRODUCT_ATI_RADEON_X1600_M, CHIP_RV530|RADEON_IS_MOBILITY|RADEON_NEW_MEMMAP, "ATI Mobility Radeon X1600"},
	{PCI_VENDOR_ATI, PCI_PRODUCT_ATI_RADEON_X1650_PRO, CHIP_RV530|RADEON_NEW_MEMMAP, "ATI Radeon X1650"},
	{PCI_VENDOR_ATI, PCI_PRODUCT_ATI_RADEON_X1650_PRO2, CHIP_RV530|RADEON_NEW_MEMMAP, "ATI Radeon X1650"},
	{PCI_VENDOR_ATI, PCI_PRODUCT_ATI_RADEON_X1600_CD, CHIP_RV530|RADEON_NEW_MEMMAP, "ATI Radeon X1600"},
	{PCI_VENDOR_ATI, PCI_PRODUCT_ATI_RADEON_X1300_XT, CHIP_RV530|RADEON_NEW_MEMMAP, "ATI Radeon X1300 XT/X1600 Pro"},
	{PCI_VENDOR_ATI, PCI_PRODUCT_ATI_FIREGL_V3400, CHIP_RV530|RADEON_NEW_MEMMAP, "ATI FireGL V3400"},
	{PCI_VENDOR_ATI, PCI_PRODUCT_ATI_RV530_M56, CHIP_RV530|RADEON_IS_MOBILITY|RADEON_NEW_MEMMAP, "ATI Mobility FireGL V5250"},
	{PCI_VENDOR_ATI, PCI_PRODUCT_ATI_RADEON_X1700, CHIP_RV530|RADEON_IS_MOBILITY|RADEON_NEW_MEMMAP, "ATI Mobility Radeon X1700"},
	{PCI_VENDOR_ATI, PCI_PRODUCT_ATI_RADEON_X1700XT, CHIP_RV530|RADEON_IS_MOBILITY|RADEON_NEW_MEMMAP, "ATI Mobility Radeon X1700 XT"},
	{PCI_VENDOR_ATI, PCI_PRODUCT_ATI_FIREGL_V5200_1, CHIP_RV530|RADEON_NEW_MEMMAP, "ATI FireGL V5200"},
	{PCI_VENDOR_ATI, PCI_PRODUCT_ATI_MOBILITY_X1700, CHIP_RV530|RADEON_IS_MOBILITY|RADEON_NEW_MEMMAP, "ATI Mobility Radeon X1700"},
	{PCI_VENDOR_ATI, PCI_PRODUCT_ATI_RADEON_X2300HD, CHIP_RV515|RADEON_NEW_MEMMAP, "ATI  Radeon X2300HD"},
	{PCI_VENDOR_ATI, PCI_PRODUCT_ATI_MOBILITY_X2300HD, CHIP_RV515|RADEON_IS_MOBILITY|RADEON_NEW_MEMMAP, "ATI Mobility Radeon HD 2300"},
	{PCI_VENDOR_ATI, PCI_PRODUCT_ATI_MOBILITY_X2300HD_1, CHIP_RV515|RADEON_IS_MOBILITY|RADEON_NEW_MEMMAP, "ATI Mobility Radeon HD 2300"},
	{PCI_VENDOR_ATI, PCI_PRODUCT_ATI_RADEON_X1950_40, CHIP_R580|RADEON_NEW_MEMMAP, "ATI Radeon X1950"},
	{PCI_VENDOR_ATI, PCI_PRODUCT_ATI_RADEON_X1900_43, CHIP_R580|RADEON_NEW_MEMMAP, "ATI Radeon X1900"},
	{PCI_VENDOR_ATI, PCI_PRODUCT_ATI_RADEON_X1950_44, CHIP_R580|RADEON_NEW_MEMMAP, "ATI Radeon X1950"},
	{PCI_VENDOR_ATI, PCI_PRODUCT_ATI_RADEON_X1900_45, CHIP_R580|RADEON_NEW_MEMMAP, "ATI Radeon X1900"},
	{PCI_VENDOR_ATI, PCI_PRODUCT_ATI_RADEON_X1900_46, CHIP_R580|RADEON_NEW_MEMMAP, "ATI Radeon X1900"},
	{PCI_VENDOR_ATI, PCI_PRODUCT_ATI_RADEON_X1900_47, CHIP_R580|RADEON_NEW_MEMMAP, "ATI Radeon X1900"},
	{PCI_VENDOR_ATI, PCI_PRODUCT_ATI_RADEON_X1900_48, CHIP_R580|RADEON_NEW_MEMMAP, "ATI Radeon X1900"},
	{PCI_VENDOR_ATI, PCI_PRODUCT_ATI_RADEON_X1900_49, CHIP_R580|RADEON_NEW_MEMMAP, "ATI Radeon X1900"},
	{PCI_VENDOR_ATI, PCI_PRODUCT_ATI_RADEON_X1900_4A, CHIP_R580|RADEON_NEW_MEMMAP, "ATI Radeon X1900"},
	{PCI_VENDOR_ATI, PCI_PRODUCT_ATI_RADEON_X1900_4B, CHIP_R580|RADEON_NEW_MEMMAP, "ATI Radeon X1900"},
	{PCI_VENDOR_ATI, PCI_PRODUCT_ATI_RADEON_X1900_4C, CHIP_R580|RADEON_NEW_MEMMAP, "ATI Radeon X1900"},
	{PCI_VENDOR_ATI, PCI_PRODUCT_ATI_RADEON_X1900_4D, CHIP_R580|RADEON_NEW_MEMMAP, "ATI Radeon X1900"},
	{PCI_VENDOR_ATI, PCI_PRODUCT_ATI_STREAM_PROCESSOR, CHIP_R580|RADEON_NEW_MEMMAP, "ATI AMD Stream Processor"},
	{PCI_VENDOR_ATI, PCI_PRODUCT_ATI_RADEON_X1900_4F, CHIP_R580|RADEON_NEW_MEMMAP, "ATI Radeon X1900"},
	{PCI_VENDOR_ATI, PCI_PRODUCT_ATI_RADEON_X1950_PRO, CHIP_RV570|RADEON_NEW_MEMMAP, "ATI Radeon X1950"},
	{PCI_VENDOR_ATI, PCI_PRODUCT_ATI_RV560, CHIP_RV560|RADEON_NEW_MEMMAP, "ATI RV560"},
	{PCI_VENDOR_ATI, PCI_PRODUCT_ATI_RV560_1, CHIP_RV560|RADEON_NEW_MEMMAP, "ATI RV560"},
	{PCI_VENDOR_ATI, PCI_PRODUCT_ATI_MOBILITY_X1900, CHIP_R580|RADEON_IS_MOBILITY|RADEON_NEW_MEMMAP, "ATI Mobility Radeon X1900"},
	{PCI_VENDOR_ATI, PCI_PRODUCT_ATI_RV560_2, CHIP_RV560|RADEON_NEW_MEMMAP, "ATI RV560"},
	{PCI_VENDOR_ATI, PCI_PRODUCT_ATI_RADEON_X1950GT, CHIP_RV570|RADEON_NEW_MEMMAP, "ATI Radeon X1950 GT"},
	{PCI_VENDOR_ATI, PCI_PRODUCT_ATI_RV570, CHIP_RV570|RADEON_NEW_MEMMAP, "ATI RV570"},
	{PCI_VENDOR_ATI, PCI_PRODUCT_ATI_RV570_2, CHIP_RV570|RADEON_NEW_MEMMAP, "ATI RV570"},
	{PCI_VENDOR_ATI, PCI_PRODUCT_ATI_FIREGL_V7400, CHIP_RV570|RADEON_NEW_MEMMAP, "ATI ATI FireGL V7400"},
	{PCI_VENDOR_ATI, PCI_PRODUCT_ATI_RV560_3, CHIP_RV560|RADEON_NEW_MEMMAP, "ATI RV560"},
	{PCI_VENDOR_ATI, PCI_PRODUCT_ATI_RADEON_RX1650_XT, CHIP_RV560|RADEON_NEW_MEMMAP, "ATI Radeon X1650"},
	{PCI_VENDOR_ATI, PCI_PRODUCT_ATI_RADEON_X1650_1, CHIP_RV560|RADEON_NEW_MEMMAP, "ATI Radeon X1650"},
	{PCI_VENDOR_ATI, PCI_PRODUCT_ATI_RV560_4, CHIP_RV560|RADEON_NEW_MEMMAP, "ATI RV560"},
	{PCI_VENDOR_ATI, PCI_PRODUCT_ATI_RADEON_9000IGP, CHIP_RS300|RADEON_IS_IGP|RADEON_NEW_MEMMAP, "ATI Radeon RS350 9000/9100 IGP"},
	{PCI_VENDOR_ATI, PCI_PRODUCT_ATI_RADEON_RS350IGP, CHIP_RS300|RADEON_IS_IGP|RADEON_IS_MOBILITY|RADEON_NEW_MEMMAP, "ATI Radeon RS350 Mobility IGP"},
	{PCI_VENDOR_ATI, PCI_PRODUCT_ATI_RADEON_X1250, CHIP_RS690|RADEON_IS_IGP|RADEON_NEW_MEMMAP|RADEON_IS_IGPGART, "ATI Radeon RS690 X1250 IGP"},
	{PCI_VENDOR_ATI, PCI_PRODUCT_ATI_RADEON_X1250IGP, CHIP_RS690|RADEON_IS_IGP|RADEON_NEW_MEMMAP|RADEON_IS_IGPGART, "ATI Radeon RS690 X1270 IGP"},
        {0, 0, 0, NULL}
};

static const struct drm_driver_info radeon_driver = {
	.buf_priv_size		= sizeof(drm_radeon_buf_priv_t),
	.load			= radeon_driver_load,
	.unload			= radeon_driver_unload,
	.firstopen		= radeon_driver_firstopen,
	.open			= radeon_driver_open,
	.ioctl			= radeondrm_ioctl,
	.preclose		= radeon_driver_preclose,
	.postclose		= radeon_driver_postclose,
	.lastclose		= radeon_driver_lastclose,
	.get_vblank_counter	= radeon_get_vblank_counter,
	.enable_vblank		= radeon_enable_vblank,
	.disable_vblank		= radeon_disable_vblank,
	.irq_preinstall		= radeon_driver_irq_preinstall,
	.irq_postinstall	= radeon_driver_irq_postinstall,
	.irq_uninstall		= radeon_driver_irq_uninstall,
	.irq_handler		= radeon_driver_irq_handler,
	.dma_ioctl		= radeon_cp_buffers,

	.name			= DRIVER_NAME,
	.desc			= DRIVER_DESC,
	.date			= DRIVER_DATE,
	.major			= DRIVER_MAJOR,
	.minor			= DRIVER_MINOR,
	.patchlevel		= DRIVER_PATCHLEVEL,

	.flags			= DRIVER_AGP | DRIVER_MTRR | DRIVER_SG |
				    DRIVER_DMA | DRIVER_IRQ,
};

int
radeondrm_probe(struct device *parent, void *match, void *aux)
{
	return drm_probe((struct pci_attach_args *)aux, radeon_pciidlist);
}

void
radeondrm_attach(struct device *parent, struct device *self, void *aux)
{
	struct pci_attach_args *pa = aux;
	struct drm_device *dev = (struct drm_device *)self;

	dev->driver = &radeon_driver;
	return drm_attach(parent, self, pa, radeon_pciidlist);
}

struct cfattach radeondrm_ca = {
        sizeof (struct drm_device), radeondrm_probe, radeondrm_attach, 
	drm_detach, drm_activate
}; 

struct cfdriver radeondrm_cd = {
	NULL, "radeondrm", DV_DULL
}; 

int
radeondrm_ioctl(struct drm_device *dev, u_long cmd, caddr_t data,
    struct drm_file *file_priv)
{
	if (file_priv->authenticated == 1) {
		switch (cmd) {
		case DRM_IOCTL_RADEON_CP_IDLE:
			return (radeon_cp_idle(dev, data, file_priv));
		case DRM_IOCTL_RADEON_CP_RESUME:
			return (radeon_cp_resume(dev, data, file_priv));
		case DRM_IOCTL_RADEON_RESET:
			return (radeon_engine_reset(dev, data, file_priv));
		case DRM_IOCTL_RADEON_FULLSCREEN:
			return (radeon_fullscreen(dev, data, file_priv));
		case DRM_IOCTL_RADEON_SWAP:
			return (radeon_cp_swap(dev, data, file_priv));
		case DRM_IOCTL_RADEON_CLEAR:
			return (radeon_cp_clear(dev, data, file_priv));
		case DRM_IOCTL_RADEON_VERTEX:
			return (radeon_cp_vertex(dev, data, file_priv));
		case DRM_IOCTL_RADEON_INDICES:
			return (radeon_cp_indices(dev, data, file_priv));
		case DRM_IOCTL_RADEON_TEXTURE:
			return (radeon_cp_texture(dev, data, file_priv));
		case DRM_IOCTL_RADEON_STIPPLE:
			return (radeon_cp_stipple(dev, data, file_priv));
		case DRM_IOCTL_RADEON_VERTEX2:
			return (radeon_cp_vertex2(dev, data, file_priv));
		case DRM_IOCTL_RADEON_CMDBUF:
			return (radeon_cp_cmdbuf(dev, data, file_priv));
		case DRM_IOCTL_RADEON_GETPARAM:
			return (radeon_cp_getparam(dev, data, file_priv));
		case DRM_IOCTL_RADEON_FLIP:
			return (radeon_cp_flip(dev, data, file_priv));
		case DRM_IOCTL_RADEON_ALLOC:
			return (radeon_mem_alloc(dev, data, file_priv));
		case DRM_IOCTL_RADEON_FREE:
			return (radeon_mem_free(dev, data, file_priv));
		case DRM_IOCTL_RADEON_IRQ_EMIT:
			return (radeon_irq_emit(dev, data, file_priv));
		case DRM_IOCTL_RADEON_IRQ_WAIT:
			return (radeon_irq_wait(dev, data, file_priv));
		case DRM_IOCTL_RADEON_SETPARAM:
			return (radeon_cp_setparam(dev, data, file_priv));
		case DRM_IOCTL_RADEON_SURF_ALLOC:
			return (radeon_surface_alloc(dev, data, file_priv));
		case DRM_IOCTL_RADEON_SURF_FREE:
			return (radeon_surface_free(dev, data, file_priv));
		}
	}

	if (file_priv->master == 1) {
		switch (cmd) {
		case DRM_IOCTL_RADEON_CP_INIT:
			return (radeon_cp_init(dev, data, file_priv));
		case DRM_IOCTL_RADEON_CP_START:
			return (radeon_cp_start(dev, data, file_priv));
		case DRM_IOCTL_RADEON_CP_STOP:
			return (radeon_cp_stop(dev, data, file_priv));
		case DRM_IOCTL_RADEON_CP_RESET:
			return (radeon_cp_reset(dev, data, file_priv));
		case DRM_IOCTL_RADEON_INDIRECT:
			return (radeon_cp_indirect(dev, data, file_priv));
		case DRM_IOCTL_RADEON_INIT_HEAP:
			return (radeon_mem_init_heap(dev, data, file_priv));
		}
	}
	return (EINVAL);
}
