#	$OpenBSD: Makefile.inc,v 1.8 2014/11/30 19:43:56 deraadt Exp $

SRCS+=	bcopy.c memcpy.c memmove.c \
	index.c rindex.c strchr.c strrchr.c \
	bcmp.c bzero.c ffs.c memchr.c memcmp.c \
	memset.c strcat.c strcmp.c strcpy.c strcspn.c strlen.c \
	strlcat.c strlcpy.c strncat.c strncmp.c strncpy.c \
	strpbrk.c strsep.c strspn.c strstr.c swab.c
