.\"	$OpenBSD: lock.1,v 1.20 2019/07/24 20:23:09 schwarze Exp $
.\"
.\" Copyright (c) 1987, 1990, 1993
.\"	The Regents of the University of California.  All rights reserved.
.\"
.\" Redistribution and use in source and binary forms, with or without
.\" modification, are permitted provided that the following conditions
.\" are met:
.\" 1. Redistributions of source code must retain the above copyright
.\"    notice, this list of conditions and the following disclaimer.
.\" 2. Redistributions in binary form must reproduce the above copyright
.\"    notice, this list of conditions and the following disclaimer in the
.\"    documentation and/or other materials provided with the distribution.
.\" 3. Neither the name of the University nor the names of its contributors
.\"    may be used to endorse or promote products derived from this software
.\"    without specific prior written permission.
.\"
.\" THIS SOFTWARE IS PROVIDED BY THE REGENTS AND CONTRIBUTORS ``AS IS'' AND
.\" ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE
.\" IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE
.\" ARE DISCLAIMED.  IN NO EVENT SHALL THE REGENTS OR CONTRIBUTORS BE LIABLE
.\" FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL
.\" DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS
.\" OR SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION)
.\" HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT
.\" LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY
.\" OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF
.\" SUCH DAMAGE.
.\"
.\"	@(#)lock.1	8.1 (Berkeley) 6/6/93
.\"
.Dd $Mdocdate: July 24 2019 $
.Dt LOCK 1
.Os
.Sh NAME
.Nm lock
.Nd reserve a terminal
.Sh SYNOPSIS
.Nm lock
.Op Fl np
.Op Fl a Ar style
.Op Fl t Ar timeout
.Sh DESCRIPTION
.Nm
requests a password from the user, reads it again for verification
and then will normally not relinquish the terminal until the password is
repeated.
.Pp
The options are as follows:
.Bl -tag -width Ds
.It Fl a Ar style
The specified
.Bx
Authentication login
.Ar style
(as specified in
.Pa /etc/login.conf )
will be used to authenticate the user.
If the particular
.Ar style
requires a challenge/response handshake or a special prompt, the
user may enter the name of the
.Ar style
to get the standard prompt for that
.Ar style .
.It Fl n
Lock the terminal forever.
This overrides
.Fl t
and is the default on
.Ox
unless
.Fl t
is specified.
.It Fl p
A password is not requested, instead the user's current login password
is used.
If the user has an S/Key key, they may also use it to unlock the terminal.
To do this the user should enter
.Qq s/key
at the unlock
.Dq Key:
prompt.
The user will then be issued an S/Key
challenge to which they may respond with a six-word S/Key one-time
password.
.It Fl t Ar timeout
Unlock the terminal after
.Ar timeout
minutes unless
.Fl n
is also specified.
When used in this manner
.Nm
should be invoked so that the user is safely logged out
if the timeout elapses:
.Pp
.Dl $ lock -t 15 || exit
.El
.Sh SEE ALSO
.Xr skey 1 ,
.Xr login.conf 5
.Sh HISTORY
The
.Nm
command first appeared in
.Bx 2 .
.Sh AUTHORS
.An Kurt Shoens .
