.\"	$OpenBSD: bcd.6,v 1.18 2014/11/06 19:35:13 tedu Exp $
.\"
.\" Copyright (c) 1988, 1991, 1993
.\"	The Regents of the University of California.  All rights reserved.
.\"
.\" Redistribution and use in source and binary forms, with or without
.\" modification, are permitted provided that the following conditions
.\" are met:
.\" 1. Redistributions of source code must retain the above copyright
.\"    notice, this list of conditions and the following disclaimer.
.\" 2. Redistributions in binary form must reproduce the above copyright
.\"    notice, this list of conditions and the following disclaimer in the
.\"    documentation and/or other materials provided with the distribution.
.\" 3. Neither the name of the University nor the names of its contributors
.\"    may be used to endorse or promote products derived from this software
.\"    without specific prior written permission.
.\"
.\" THIS SOFTWARE IS PROVIDED BY THE REGENTS AND CONTRIBUTORS ``AS IS'' AND
.\" ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE
.\" IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE
.\" ARE DISCLAIMED.  IN NO EVENT SHALL THE REGENTS OR CONTRIBUTORS BE LIABLE
.\" FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL
.\" DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS
.\" OR SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION)
.\" HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT
.\" LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY
.\" OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF
.\" SUCH DAMAGE.
.\"
.\"	@(#)bcd.6	8.1 (Berkeley) 5/31/93
.\"
.Dd $Mdocdate: November 6 2014 $
.Dt BCD 6
.Os
.Sh NAME
.Nm bcd ,
.Nm ppt ,
.Nm morse
.Nd reformat input as punch cards, paper tape or morse code
.Sh SYNOPSIS
.Nm bcd
.Oo
.Fl d Oc \*(Ba
.Ar string ...
.Oc
.Nm ppt
.Oo
.Fl d Oo Fl b Oc \*(Ba
.Ar string ...
.Oc
.Nm morse
.Op Fl d | s
.Op Ar string ...
.Sh DESCRIPTION
The
.Nm bcd ,
.Nm ppt ,
and
.Nm morse
commands read the given input and reformat it in the form of
punched cards, paper tape, or morse code, respectively.
Acceptable input are command line arguments or the standard input.
.Pp
Available options for
.Nm bcd :
.Bl -tag -width Ds
.It Fl d
The
.Fl d
option for
.Nm bcd
decodes punch cards on the standard input back to ASCII.
.El
.Pp
Available options for
.Nm ppt :
.Bl -tag -width Ds
.It Fl d Op Fl b
The
.Fl d
option for
.Nm ppt
decodes paper tape on the standard input back to ASCII.
Unprintable characters are visually encoded with
.Xr vis 3
unless the
.Fl b
flag (binary) is also specified.
A lowercase
.Sq x
is printed for undecipherable input lines.
.El
.Pp
Available options for
.Nm morse :
.Bl -tag -width Ds
.It Fl d
The
.Fl d
option for
.Nm morse
decodes dot-dash morse
.Po
as generated by using the
.Fl s
option
.Pc
back into text.
A lowercase
.Sq x
is printed for undecipherable input; otherwise, text is returned uppercase.
If the morse to be translated is given on the command line, it should be
preceded by
.Sq --
to keep it from being mistaken for options.
.It Fl s
The
.Fl s
option for
.Nm morse
produces dots and dashes rather than words.
.El
.Sh SEE ALSO
.Rs
.%I ISO 1681:1973
.%R "Information processing--Unpunched paper cards--Specification"
.Re
.Rs
.%I ISO 1682:1973
.%R "Information processing--80 columns punched paper cards--Dimensions and location of rectangular punched holes"
.Re
.Rs
.%I ECMA-10
.%R "ECMA Standard for Data Interchange on Punched Tape"
.Re
.Rs
.%I ITU-T Recommendation F.1
.%R "Operational provisions for the international public telegram service"
.%O Division B, I. Morse code
.Re
