/* Public Domain */


struct sxipio_pin sun4i_a10_pins[] = {
	{ SXIPIO_PIN(A, 0), {
		{ "gpio_in", 0 },
		{ "gpio_out", 1 },
		{ "emac", 2 },
		{ "spi1", 3 },
		{ "uart2", 4 },
	} },
	{ SXIPIO_PIN(A, 1), {
		{ "gpio_in", 0 },
		{ "gpio_out", 1 },
		{ "emac", 2 },
		{ "spi1", 3 },
		{ "uart2", 4 },
	} },
	{ SXIPIO_PIN(A, 2), {
		{ "gpio_in", 0 },
		{ "gpio_out", 1 },
		{ "emac", 2 },
		{ "spi1", 3 },
		{ "uart2", 4 },
	} },
	{ SXIPIO_PIN(A, 3), {
		{ "gpio_in", 0 },
		{ "gpio_out", 1 },
		{ "emac", 2 },
		{ "spi1", 3 },
		{ "uart2", 4 },
	} },
	{ SXIPIO_PIN(A, 4), {
		{ "gpio_in", 0 },
		{ "gpio_out", 1 },
		{ "emac", 2 },
		{ "spi1", 3 },
	} },
	{ SXIPIO_PIN(A, 5), {
		{ "gpio_in", 0 },
		{ "gpio_out", 1 },
		{ "emac", 2 },
		{ "spi3", 3 },
	} },
	{ SXIPIO_PIN(A, 6), {
		{ "gpio_in", 0 },
		{ "gpio_out", 1 },
		{ "emac", 2 },
		{ "spi3", 3 },
	} },
	{ SXIPIO_PIN(A, 7), {
		{ "gpio_in", 0 },
		{ "gpio_out", 1 },
		{ "emac", 2 },
		{ "spi3", 3 },
	} },
	{ SXIPIO_PIN(A, 8), {
		{ "gpio_in", 0 },
		{ "gpio_out", 1 },
		{ "emac", 2 },
		{ "spi3", 3 },
	} },
	{ SXIPIO_PIN(A, 9), {
		{ "gpio_in", 0 },
		{ "gpio_out", 1 },
		{ "emac", 2 },
		{ "spi3", 3 },
	} },
	{ SXIPIO_PIN(A, 10), {
		{ "gpio_in", 0 },
		{ "gpio_out", 1 },
		{ "emac", 2 },
		{ "uart1", 4 },
	} },
	{ SXIPIO_PIN(A, 11), {
		{ "gpio_in", 0 },
		{ "gpio_out", 1 },
		{ "emac", 2 },
		{ "uart1", 4 },
	} },
	{ SXIPIO_PIN(A, 12), {
		{ "gpio_in", 0 },
		{ "gpio_out", 1 },
		{ "emac", 2 },
		{ "uart6", 3 },
		{ "uart1", 4 },
	} },
	{ SXIPIO_PIN(A, 13), {
		{ "gpio_in", 0 },
		{ "gpio_out", 1 },
		{ "emac", 2 },
		{ "uart6", 3 },
		{ "uart1", 4 },
	} },
	{ SXIPIO_PIN(A, 14), {
		{ "gpio_in", 0 },
		{ "gpio_out", 1 },
		{ "emac", 2 },
		{ "uart7", 3 },
		{ "uart1", 4 },
	} },
	{ SXIPIO_PIN(A, 15), {
		{ "gpio_in", 0 },
		{ "gpio_out", 1 },
		{ "emac", 2 },
		{ "uart7", 3 },
		{ "uart1", 4 },
	} },
	{ SXIPIO_PIN(A, 16), {
		{ "gpio_in", 0 },
		{ "gpio_out", 1 },
		{ "emac", 2 },
		{ "can", 3 },
		{ "uart1", 4 },
	} },
	{ SXIPIO_PIN(A, 17), {
		{ "gpio_in", 0 },
		{ "gpio_out", 1 },
		{ "emac", 2 },
		{ "can", 3 },
		{ "uart1", 4 },
	} },
	{ SXIPIO_PIN(B, 0), {
		{ "gpio_in", 0 },
		{ "gpio_out", 1 },
		{ "i2c0", 2 },
	} },
	{ SXIPIO_PIN(B, 1), {
		{ "gpio_in", 0 },
		{ "gpio_out", 1 },
		{ "i2c0", 2 },
	} },
	{ SXIPIO_PIN(B, 2), {
		{ "gpio_in", 0 },
		{ "gpio_out", 1 },
		{ "pwm", 2 },
	} },
	{ SXIPIO_PIN(B, 3), {
		{ "gpio_in", 0 },
		{ "gpio_out", 1 },
		{ "ir0", 2 },
		{ "spdif", 4 },
	} },
	{ SXIPIO_PIN(B, 4), {
		{ "gpio_in", 0 },
		{ "gpio_out", 1 },
		{ "ir0", 2 },
	} },
	{ SXIPIO_PIN(B, 5), {
		{ "gpio_in", 0 },
		{ "gpio_out", 1 },
		{ "i2s", 2 },
		{ "ac97", 3 },
	} },
	{ SXIPIO_PIN(B, 6), {
		{ "gpio_in", 0 },
		{ "gpio_out", 1 },
		{ "i2s", 2 },
		{ "ac97", 3 },
	} },
	{ SXIPIO_PIN(B, 7), {
		{ "gpio_in", 0 },
		{ "gpio_out", 1 },
		{ "i2s", 2 },
		{ "ac97", 3 },
	} },
	{ SXIPIO_PIN(B, 8), {
		{ "gpio_in", 0 },
		{ "gpio_out", 1 },
		{ "i2s", 2 },
		{ "ac97", 3 },
	} },
	{ SXIPIO_PIN(B, 9), {
		{ "gpio_in", 0 },
		{ "gpio_out", 1 },
		{ "i2s", 2 },
	} },
	{ SXIPIO_PIN(B, 10), {
		{ "gpio_in", 0 },
		{ "gpio_out", 1 },
		{ "i2s", 2 },
	} },
	{ SXIPIO_PIN(B, 11), {
		{ "gpio_in", 0 },
		{ "gpio_out", 1 },
		{ "i2s", 2 },
	} },
	{ SXIPIO_PIN(B, 12), {
		{ "gpio_in", 0 },
		{ "gpio_out", 1 },
		{ "i2s", 2 },
		{ "ac97", 3 },
		{ "spdif", 4 },
	} },
	{ SXIPIO_PIN(B, 13), {
		{ "gpio_in", 0 },
		{ "gpio_out", 1 },
		{ "spi2", 2 },
		{ "spdif", 4 },
	} },
	{ SXIPIO_PIN(B, 14), {
		{ "gpio_in", 0 },
		{ "gpio_out", 1 },
		{ "spi2", 2 },
		{ "jtag", 3 },
	} },
	{ SXIPIO_PIN(B, 15), {
		{ "gpio_in", 0 },
		{ "gpio_out", 1 },
		{ "spi2", 2 },
		{ "jtag", 3 },
	} },
	{ SXIPIO_PIN(B, 16), {
		{ "gpio_in", 0 },
		{ "gpio_out", 1 },
		{ "spi2", 2 },
		{ "jtag", 3 },
	} },
	{ SXIPIO_PIN(B, 17), {
		{ "gpio_in", 0 },
		{ "gpio_out", 1 },
		{ "spi2", 2 },
		{ "jtag", 3 },
	} },
	{ SXIPIO_PIN(B, 18), {
		{ "gpio_in", 0 },
		{ "gpio_out", 1 },
		{ "i2c1", 2 },
	} },
	{ SXIPIO_PIN(B, 19), {
		{ "gpio_in", 0 },
		{ "gpio_out", 1 },
		{ "i2c1", 2 },
	} },
	{ SXIPIO_PIN(B, 20), {
		{ "gpio_in", 0 },
		{ "gpio_out", 1 },
		{ "i2c2", 2 },
	} },
	{ SXIPIO_PIN(B, 21), {
		{ "gpio_in", 0 },
		{ "gpio_out", 1 },
		{ "i2c2", 2 },
	} },
	{ SXIPIO_PIN(B, 22), {
		{ "gpio_in", 0 },
		{ "gpio_out", 1 },
		{ "uart0", 2 },
		{ "ir1", 3 },
	} },
	{ SXIPIO_PIN(B, 23), {
		{ "gpio_in", 0 },
		{ "gpio_out", 1 },
		{ "uart0", 2 },
		{ "ir1", 3 },
	} },
	{ SXIPIO_PIN(C, 0), {
		{ "gpio_in", 0 },
		{ "gpio_out", 1 },
		{ "nand0", 2 },
		{ "spi0", 3 },
	} },
	{ SXIPIO_PIN(C, 1), {
		{ "gpio_in", 0 },
		{ "gpio_out", 1 },
		{ "nand0", 2 },
		{ "spi0", 3 },
	} },
	{ SXIPIO_PIN(C, 2), {
		{ "gpio_in", 0 },
		{ "gpio_out", 1 },
		{ "nand0", 2 },
		{ "spi0", 3 },
	} },
	{ SXIPIO_PIN(C, 3), {
		{ "gpio_in", 0 },
		{ "gpio_out", 1 },
		{ "nand0", 2 },
	} },
	{ SXIPIO_PIN(C, 4), {
		{ "gpio_in", 0 },
		{ "gpio_out", 1 },
		{ "nand0", 2 },
	} },
	{ SXIPIO_PIN(C, 5), {
		{ "gpio_in", 0 },
		{ "gpio_out", 1 },
		{ "nand0", 2 },
	} },
	{ SXIPIO_PIN(C, 6), {
		{ "gpio_in", 0 },
		{ "gpio_out", 1 },
		{ "nand0", 2 },
		{ "mmc2", 3 },
	} },
	{ SXIPIO_PIN(C, 7), {
		{ "gpio_in", 0 },
		{ "gpio_out", 1 },
		{ "nand0", 2 },
		{ "mmc2", 3 },
	} },
	{ SXIPIO_PIN(C, 8), {
		{ "gpio_in", 0 },
		{ "gpio_out", 1 },
		{ "nand0", 2 },
		{ "mmc2", 3 },
	} },
	{ SXIPIO_PIN(C, 9), {
		{ "gpio_in", 0 },
		{ "gpio_out", 1 },
		{ "nand0", 2 },
		{ "mmc2", 3 },
	} },
	{ SXIPIO_PIN(C, 10), {
		{ "gpio_in", 0 },
		{ "gpio_out", 1 },
		{ "nand0", 2 },
		{ "mmc2", 3 },
	} },
	{ SXIPIO_PIN(C, 11), {
		{ "gpio_in", 0 },
		{ "gpio_out", 1 },
		{ "nand0", 2 },
		{ "mmc2", 3 },
	} },
	{ SXIPIO_PIN(C, 12), {
		{ "gpio_in", 0 },
		{ "gpio_out", 1 },
		{ "nand0", 2 },
	} },
	{ SXIPIO_PIN(C, 13), {
		{ "gpio_in", 0 },
		{ "gpio_out", 1 },
		{ "nand0", 2 },
	} },
	{ SXIPIO_PIN(C, 14), {
		{ "gpio_in", 0 },
		{ "gpio_out", 1 },
		{ "nand0", 2 },
	} },
	{ SXIPIO_PIN(C, 15), {
		{ "gpio_in", 0 },
		{ "gpio_out", 1 },
		{ "nand0", 2 },
	} },
	{ SXIPIO_PIN(C, 16), {
		{ "gpio_in", 0 },
		{ "gpio_out", 1 },
		{ "nand0", 2 },
	} },
	{ SXIPIO_PIN(C, 17), {
		{ "gpio_in", 0 },
		{ "gpio_out", 1 },
		{ "nand0", 2 },
	} },
	{ SXIPIO_PIN(C, 18), {
		{ "gpio_in", 0 },
		{ "gpio_out", 1 },
		{ "nand0", 2 },
	} },
	{ SXIPIO_PIN(C, 19), {
		{ "gpio_in", 0 },
		{ "gpio_out", 1 },
		{ "nand0", 2 },
		{ "spi2", 3 },
	} },
	{ SXIPIO_PIN(C, 20), {
		{ "gpio_in", 0 },
		{ "gpio_out", 1 },
		{ "nand0", 2 },
		{ "spi2", 3 },
	} },
	{ SXIPIO_PIN(C, 21), {
		{ "gpio_in", 0 },
		{ "gpio_out", 1 },
		{ "nand0", 2 },
		{ "spi2", 3 },
	} },
	{ SXIPIO_PIN(C, 22), {
		{ "gpio_in", 0 },
		{ "gpio_out", 1 },
		{ "nand0", 2 },
		{ "spi2", 3 },
	} },
	{ SXIPIO_PIN(C, 23), {
		{ "gpio_in", 0 },
		{ "gpio_out", 1 },
		{ "spi0", 3 },
	} },
	{ SXIPIO_PIN(C, 24), {
		{ "gpio_in", 0 },
		{ "gpio_out", 1 },
		{ "nand0", 2 },
	} },
	{ SXIPIO_PIN(D, 0), {
		{ "gpio_in", 0 },
		{ "gpio_out", 1 },
		{ "lcd0", 2 },
		{ "lvds0", 3 },
	} },
	{ SXIPIO_PIN(D, 1), {
		{ "gpio_in", 0 },
		{ "gpio_out", 1 },
		{ "lcd0", 2 },
		{ "lvds0", 3 },
	} },
	{ SXIPIO_PIN(D, 2), {
		{ "gpio_in", 0 },
		{ "gpio_out", 1 },
		{ "lcd0", 2 },
		{ "lvds0", 3 },
	} },
	{ SXIPIO_PIN(D, 3), {
		{ "gpio_in", 0 },
		{ "gpio_out", 1 },
		{ "lcd0", 2 },
		{ "lvds0", 3 },
	} },
	{ SXIPIO_PIN(D, 4), {
		{ "gpio_in", 0 },
		{ "gpio_out", 1 },
		{ "lcd0", 2 },
		{ "lvds0", 3 },
	} },
	{ SXIPIO_PIN(D, 5), {
		{ "gpio_in", 0 },
		{ "gpio_out", 1 },
		{ "lcd0", 2 },
		{ "lvds0", 3 },
	} },
	{ SXIPIO_PIN(D, 6), {
		{ "gpio_in", 0 },
		{ "gpio_out", 1 },
		{ "lcd0", 2 },
		{ "lvds0", 3 },
	} },
	{ SXIPIO_PIN(D, 7), {
		{ "gpio_in", 0 },
		{ "gpio_out", 1 },
		{ "lcd0", 2 },
		{ "lvds0", 3 },
	} },
	{ SXIPIO_PIN(D, 8), {
		{ "gpio_in", 0 },
		{ "gpio_out", 1 },
		{ "lcd0", 2 },
		{ "lvds0", 3 },
	} },
	{ SXIPIO_PIN(D, 9), {
		{ "gpio_in", 0 },
		{ "gpio_out", 1 },
		{ "lcd0", 2 },
		{ "lvds0", 3 },
	} },
	{ SXIPIO_PIN(D, 10), {
		{ "gpio_in", 0 },
		{ "gpio_out", 1 },
		{ "lcd0", 2 },
		{ "lvds1", 3 },
	} },
	{ SXIPIO_PIN(D, 11), {
		{ "gpio_in", 0 },
		{ "gpio_out", 1 },
		{ "lcd0", 2 },
		{ "lvds1", 3 },
	} },
	{ SXIPIO_PIN(D, 12), {
		{ "gpio_in", 0 },
		{ "gpio_out", 1 },
		{ "lcd0", 2 },
		{ "lvds1", 3 },
	} },
	{ SXIPIO_PIN(D, 13), {
		{ "gpio_in", 0 },
		{ "gpio_out", 1 },
		{ "lcd0", 2 },
		{ "lvds1", 3 },
	} },
	{ SXIPIO_PIN(D, 14), {
		{ "gpio_in", 0 },
		{ "gpio_out", 1 },
		{ "lcd0", 2 },
		{ "lvds1", 3 },
	} },
	{ SXIPIO_PIN(D, 15), {
		{ "gpio_in", 0 },
		{ "gpio_out", 1 },
		{ "lcd0", 2 },
		{ "lvds1", 3 },
	} },
	{ SXIPIO_PIN(D, 16), {
		{ "gpio_in", 0 },
		{ "gpio_out", 1 },
		{ "lcd0", 2 },
		{ "lvds1", 3 },
	} },
	{ SXIPIO_PIN(D, 17), {
		{ "gpio_in", 0 },
		{ "gpio_out", 1 },
		{ "lcd0", 2 },
		{ "lvds1", 3 },
	} },
	{ SXIPIO_PIN(D, 18), {
		{ "gpio_in", 0 },
		{ "gpio_out", 1 },
		{ "lcd0", 2 },
		{ "lvds1", 3 },
	} },
	{ SXIPIO_PIN(D, 19), {
		{ "gpio_in", 0 },
		{ "gpio_out", 1 },
		{ "lcd0", 2 },
		{ "lvds1", 3 },
	} },
	{ SXIPIO_PIN(D, 20), {
		{ "gpio_in", 0 },
		{ "gpio_out", 1 },
		{ "lcd0", 2 },
		{ "csi1", 3 },
	} },
	{ SXIPIO_PIN(D, 21), {
		{ "gpio_in", 0 },
		{ "gpio_out", 1 },
		{ "lcd0", 2 },
		{ "sim", 3 },
	} },
	{ SXIPIO_PIN(D, 22), {
		{ "gpio_in", 0 },
		{ "gpio_out", 1 },
		{ "lcd0", 2 },
		{ "sim", 3 },
	} },
	{ SXIPIO_PIN(D, 23), {
		{ "gpio_in", 0 },
		{ "gpio_out", 1 },
		{ "lcd0", 2 },
		{ "sim", 3 },
	} },
	{ SXIPIO_PIN(D, 24), {
		{ "gpio_in", 0 },
		{ "gpio_out", 1 },
		{ "lcd0", 2 },
		{ "sim", 3 },
	} },
	{ SXIPIO_PIN(D, 25), {
		{ "gpio_in", 0 },
		{ "gpio_out", 1 },
		{ "lcd0", 2 },
		{ "sim", 3 },
	} },
	{ SXIPIO_PIN(D, 26), {
		{ "gpio_in", 0 },
		{ "gpio_out", 1 },
		{ "lcd0", 2 },
		{ "sim", 3 },
	} },
	{ SXIPIO_PIN(D, 27), {
		{ "gpio_in", 0 },
		{ "gpio_out", 1 },
		{ "lcd0", 2 },
		{ "sim", 3 },
	} },
	{ SXIPIO_PIN(E, 0), {
		{ "gpio_in", 0 },
		{ "gpio_out", 1 },
		{ "ts0", 2 },
		{ "csi0", 3 },
	} },
	{ SXIPIO_PIN(E, 1), {
		{ "gpio_in", 0 },
		{ "gpio_out", 1 },
		{ "ts0", 2 },
		{ "csi0", 3 },
	} },
	{ SXIPIO_PIN(E, 2), {
		{ "gpio_in", 0 },
		{ "gpio_out", 1 },
		{ "ts0", 2 },
		{ "csi0", 3 },
	} },
	{ SXIPIO_PIN(E, 3), {
		{ "gpio_in", 0 },
		{ "gpio_out", 1 },
		{ "ts0", 2 },
		{ "csi0", 3 },
	} },
	{ SXIPIO_PIN(E, 4), {
		{ "gpio_in", 0 },
		{ "gpio_out", 1 },
		{ "ts0", 2 },
		{ "csi0", 3 },
	} },
	{ SXIPIO_PIN(E, 5), {
		{ "gpio_in", 0 },
		{ "gpio_out", 1 },
		{ "ts0", 2 },
		{ "csi0", 3 },
		{ "sim", 4 },
	} },
	{ SXIPIO_PIN(E, 6), {
		{ "gpio_in", 0 },
		{ "gpio_out", 1 },
		{ "ts0", 2 },
		{ "csi0", 3 },
	} },
	{ SXIPIO_PIN(E, 7), {
		{ "gpio_in", 0 },
		{ "gpio_out", 1 },
		{ "ts0", 2 },
		{ "csi0", 3 },
	} },
	{ SXIPIO_PIN(E, 8), {
		{ "gpio_in", 0 },
		{ "gpio_out", 1 },
		{ "ts0", 2 },
		{ "csi0", 3 },
	} },
	{ SXIPIO_PIN(E, 9), {
		{ "gpio_in", 0 },
		{ "gpio_out", 1 },
		{ "ts0", 2 },
		{ "csi0", 3 },
	} },
	{ SXIPIO_PIN(E, 10), {
		{ "gpio_in", 0 },
		{ "gpio_out", 1 },
		{ "ts0", 2 },
		{ "csi0", 3 },
	} },
	{ SXIPIO_PIN(E, 11), {
		{ "gpio_in", 0 },
		{ "gpio_out", 1 },
		{ "ts0", 2 },
		{ "csi0", 3 },
	} },
	{ SXIPIO_PIN(F, 0), {
		{ "gpio_in", 0 },
		{ "gpio_out", 1 },
		{ "mmc0", 2 },
		{ "jtag", 4 },
	} },
	{ SXIPIO_PIN(F, 1), {
		{ "gpio_in", 0 },
		{ "gpio_out", 1 },
		{ "mmc0", 2 },
		{ "jtag", 4 },
	} },
	{ SXIPIO_PIN(F, 2), {
		{ "gpio_in", 0 },
		{ "gpio_out", 1 },
		{ "mmc0", 2 },
		{ "uart0", 4 },
	} },
	{ SXIPIO_PIN(F, 3), {
		{ "gpio_in", 0 },
		{ "gpio_out", 1 },
		{ "mmc0", 2 },
		{ "jtag", 4 },
	} },
	{ SXIPIO_PIN(F, 4), {
		{ "gpio_in", 0 },
		{ "gpio_out", 1 },
		{ "mmc0", 2 },
		{ "uart0", 4 },
	} },
	{ SXIPIO_PIN(F, 5), {
		{ "gpio_in", 0 },
		{ "gpio_out", 1 },
		{ "mmc0", 2 },
		{ "jtag", 4 },
	} },
	{ SXIPIO_PIN(G, 0), {
		{ "gpio_in", 0 },
		{ "gpio_out", 1 },
		{ "ts1", 2 },
		{ "csi1", 3 },
		{ "mmc1", 4 },
	} },
	{ SXIPIO_PIN(G, 1), {
		{ "gpio_in", 0 },
		{ "gpio_out", 1 },
		{ "ts1", 2 },
		{ "csi1", 3 },
		{ "mmc1", 4 },
	} },
	{ SXIPIO_PIN(G, 2), {
		{ "gpio_in", 0 },
		{ "gpio_out", 1 },
		{ "ts1", 2 },
		{ "csi1", 3 },
		{ "mmc1", 4 },
	} },
	{ SXIPIO_PIN(G, 3), {
		{ "gpio_in", 0 },
		{ "gpio_out", 1 },
		{ "ts1", 2 },
		{ "csi1", 3 },
		{ "mmc1", 4 },
	} },
	{ SXIPIO_PIN(G, 4), {
		{ "gpio_in", 0 },
		{ "gpio_out", 1 },
		{ "ts1", 2 },
		{ "csi1", 3 },
		{ "mmc1", 4 },
		{ "csi0", 5 },
	} },
	{ SXIPIO_PIN(G, 5), {
		{ "gpio_in", 0 },
		{ "gpio_out", 1 },
		{ "ts1", 2 },
		{ "csi1", 3 },
		{ "mmc1", 4 },
		{ "csi0", 5 },
	} },
	{ SXIPIO_PIN(G, 6), {
		{ "gpio_in", 0 },
		{ "gpio_out", 1 },
		{ "ts1", 2 },
		{ "csi1", 3 },
		{ "uart3", 4 },
		{ "csi0", 5 },
	} },
	{ SXIPIO_PIN(G, 7), {
		{ "gpio_in", 0 },
		{ "gpio_out", 1 },
		{ "ts1", 2 },
		{ "csi1", 3 },
		{ "uart3", 4 },
		{ "csi0", 5 },
	} },
	{ SXIPIO_PIN(G, 8), {
		{ "gpio_in", 0 },
		{ "gpio_out", 1 },
		{ "ts1", 2 },
		{ "csi1", 3 },
		{ "uart3", 4 },
		{ "csi0", 5 },
	} },
	{ SXIPIO_PIN(G, 9), {
		{ "gpio_in", 0 },
		{ "gpio_out", 1 },
		{ "ts1", 2 },
		{ "csi1", 3 },
		{ "uart3", 4 },
		{ "csi0", 5 },
	} },
	{ SXIPIO_PIN(G, 10), {
		{ "gpio_in", 0 },
		{ "gpio_out", 1 },
		{ "ts1", 2 },
		{ "csi1", 3 },
		{ "uart4", 4 },
		{ "csi0", 5 },
	} },
	{ SXIPIO_PIN(G, 11), {
		{ "gpio_in", 0 },
		{ "gpio_out", 1 },
		{ "ts1", 2 },
		{ "csi1", 3 },
		{ "uart4", 4 },
		{ "csi0", 5 },
	} },
	{ SXIPIO_PIN(H, 0), {
		{ "gpio_in", 0 },
		{ "gpio_out", 1 },
		{ "lcd1", 2 },
		{ "pata", 3 },
		{ "uart3", 4 },
		{ "irq", 6 },
		{ "csi1", 7 },
	} },
	{ SXIPIO_PIN(H, 1), {
		{ "gpio_in", 0 },
		{ "gpio_out", 1 },
		{ "lcd1", 2 },
		{ "pata", 3 },
		{ "uart3", 4 },
		{ "irq", 6 },
		{ "csi1", 7 },
	} },
	{ SXIPIO_PIN(H, 2), {
		{ "gpio_in", 0 },
		{ "gpio_out", 1 },
		{ "lcd1", 2 },
		{ "pata", 3 },
		{ "uart3", 4 },
		{ "irq", 6 },
		{ "csi1", 7 },
	} },
	{ SXIPIO_PIN(H, 3), {
		{ "gpio_in", 0 },
		{ "gpio_out", 1 },
		{ "lcd1", 2 },
		{ "pata", 3 },
		{ "uart3", 4 },
		{ "irq", 6 },
		{ "csi1", 7 },
	} },
	{ SXIPIO_PIN(H, 4), {
		{ "gpio_in", 0 },
		{ "gpio_out", 1 },
		{ "lcd1", 2 },
		{ "pata", 3 },
		{ "uart4", 4 },
		{ "irq", 6 },
		{ "csi1", 7 },
	} },
	{ SXIPIO_PIN(H, 5), {
		{ "gpio_in", 0 },
		{ "gpio_out", 1 },
		{ "lcd1", 2 },
		{ "pata", 3 },
		{ "uart4", 4 },
		{ "irq", 6 },
		{ "csi1", 7 },
	} },
	{ SXIPIO_PIN(H, 6), {
		{ "gpio_in", 0 },
		{ "gpio_out", 1 },
		{ "lcd1", 2 },
		{ "pata", 3 },
		{ "uart5", 4 },
		{ "ms", 5 },
		{ "irq", 6 },
		{ "csi1", 7 },
	} },
	{ SXIPIO_PIN(H, 7), {
		{ "gpio_in", 0 },
		{ "gpio_out", 1 },
		{ "lcd1", 2 },
		{ "pata", 3 },
		{ "uart5", 4 },
		{ "ms", 5 },
		{ "irq", 6 },
		{ "csi1", 7 },
	} },
	{ SXIPIO_PIN(H, 8), {
		{ "gpio_in", 0 },
		{ "gpio_out", 1 },
		{ "lcd1", 2 },
		{ "pata", 3 },
		{ "keypad", 4 },
		{ "ms", 5 },
		{ "irq", 6 },
		{ "csi1", 7 },
	} },
	{ SXIPIO_PIN(H, 9), {
		{ "gpio_in", 0 },
		{ "gpio_out", 1 },
		{ "lcd1", 2 },
		{ "pata", 3 },
		{ "keypad", 4 },
		{ "ms", 5 },
		{ "irq", 6 },
		{ "csi1", 7 },
	} },
	{ SXIPIO_PIN(H, 10), {
		{ "gpio_in", 0 },
		{ "gpio_out", 1 },
		{ "lcd1", 2 },
		{ "pata", 3 },
		{ "keypad", 4 },
		{ "ms", 5 },
		{ "irq", 6 },
		{ "csi1", 7 },
	} },
	{ SXIPIO_PIN(H, 11), {
		{ "gpio_in", 0 },
		{ "gpio_out", 1 },
		{ "lcd1", 2 },
		{ "pata", 3 },
		{ "keypad", 4 },
		{ "ms", 5 },
		{ "irq", 6 },
		{ "csi1", 7 },
	} },
	{ SXIPIO_PIN(H, 12), {
		{ "gpio_in", 0 },
		{ "gpio_out", 1 },
		{ "lcd1", 2 },
		{ "pata", 3 },
		{ "ps2", 4 },
		{ "irq", 6 },
		{ "csi1", 7 },
	} },
	{ SXIPIO_PIN(H, 13), {
		{ "gpio_in", 0 },
		{ "gpio_out", 1 },
		{ "lcd1", 2 },
		{ "pata", 3 },
		{ "ps2", 4 },
		{ "sim", 5 },
		{ "irq", 6 },
		{ "csi1", 7 },
	} },
	{ SXIPIO_PIN(H, 14), {
		{ "gpio_in", 0 },
		{ "gpio_out", 1 },
		{ "lcd1", 2 },
		{ "pata", 3 },
		{ "keypad", 4 },
		{ "sim", 5 },
		{ "irq", 6 },
		{ "csi1", 7 },
	} },
	{ SXIPIO_PIN(H, 15), {
		{ "gpio_in", 0 },
		{ "gpio_out", 1 },
		{ "lcd1", 2 },
		{ "pata", 3 },
		{ "keypad", 4 },
		{ "sim", 5 },
		{ "irq", 6 },
		{ "csi1", 7 },
	} },
	{ SXIPIO_PIN(H, 16), {
		{ "gpio_in", 0 },
		{ "gpio_out", 1 },
		{ "lcd1", 2 },
		{ "pata", 3 },
		{ "keypad", 4 },
		{ "irq", 6 },
		{ "csi1", 7 },
	} },
	{ SXIPIO_PIN(H, 17), {
		{ "gpio_in", 0 },
		{ "gpio_out", 1 },
		{ "lcd1", 2 },
		{ "pata", 3 },
		{ "keypad", 4 },
		{ "sim", 5 },
		{ "irq", 6 },
		{ "csi1", 7 },
	} },
	{ SXIPIO_PIN(H, 18), {
		{ "gpio_in", 0 },
		{ "gpio_out", 1 },
		{ "lcd1", 2 },
		{ "pata", 3 },
		{ "keypad", 4 },
		{ "sim", 5 },
		{ "irq", 6 },
		{ "csi1", 7 },
	} },
	{ SXIPIO_PIN(H, 19), {
		{ "gpio_in", 0 },
		{ "gpio_out", 1 },
		{ "lcd1", 2 },
		{ "pata", 3 },
		{ "keypad", 4 },
		{ "sim", 5 },
		{ "irq", 6 },
		{ "csi1", 7 },
	} },
	{ SXIPIO_PIN(H, 20), {
		{ "gpio_in", 0 },
		{ "gpio_out", 1 },
		{ "lcd1", 2 },
		{ "pata", 3 },
		{ "can", 4 },
		{ "irq", 6 },
		{ "csi1", 7 },
	} },
	{ SXIPIO_PIN(H, 21), {
		{ "gpio_in", 0 },
		{ "gpio_out", 1 },
		{ "lcd1", 2 },
		{ "pata", 3 },
		{ "can", 4 },
		{ "irq", 6 },
		{ "csi1", 7 },
	} },
	{ SXIPIO_PIN(H, 22), {
		{ "gpio_in", 0 },
		{ "gpio_out", 1 },
		{ "lcd1", 2 },
		{ "pata", 3 },
		{ "keypad", 4 },
		{ "mmc1", 5 },
		{ "csi1", 7 },
	} },
	{ SXIPIO_PIN(H, 23), {
		{ "gpio_in", 0 },
		{ "gpio_out", 1 },
		{ "lcd1", 2 },
		{ "pata", 3 },
		{ "keypad", 4 },
		{ "mmc1", 5 },
		{ "csi1", 7 },
	} },
	{ SXIPIO_PIN(H, 24), {
		{ "gpio_in", 0 },
		{ "gpio_out", 1 },
		{ "lcd1", 2 },
		{ "pata", 3 },
		{ "keypad", 4 },
		{ "mmc1", 5 },
		{ "csi1", 7 },
	} },
	{ SXIPIO_PIN(H, 25), {
		{ "gpio_in", 0 },
		{ "gpio_out", 1 },
		{ "lcd1", 2 },
		{ "pata", 3 },
		{ "keypad", 4 },
		{ "mmc1", 5 },
		{ "csi1", 7 },
	} },
	{ SXIPIO_PIN(H, 26), {
		{ "gpio_in", 0 },
		{ "gpio_out", 1 },
		{ "lcd1", 2 },
		{ "pata", 3 },
		{ "keypad", 4 },
		{ "mmc1", 5 },
		{ "csi1", 7 },
	} },
	{ SXIPIO_PIN(H, 27), {
		{ "gpio_in", 0 },
		{ "gpio_out", 1 },
		{ "lcd1", 2 },
		{ "pata", 3 },
		{ "keypad", 4 },
		{ "mmc1", 5 },
		{ "csi1", 7 },
	} },
	{ SXIPIO_PIN(I, 0), {
		{ "gpio_in", 0 },
		{ "gpio_out", 1 },
	} },
	{ SXIPIO_PIN(I, 1), {
		{ "gpio_in", 0 },
		{ "gpio_out", 1 },
	} },
	{ SXIPIO_PIN(I, 2), {
		{ "gpio_in", 0 },
		{ "gpio_out", 1 },
	} },
	{ SXIPIO_PIN(I, 3), {
		{ "gpio_in", 0 },
		{ "gpio_out", 1 },
		{ "pwm", 2 },
	} },
	{ SXIPIO_PIN(I, 4), {
		{ "gpio_in", 0 },
		{ "gpio_out", 1 },
		{ "mmc3", 2 },
	} },
	{ SXIPIO_PIN(I, 5), {
		{ "gpio_in", 0 },
		{ "gpio_out", 1 },
		{ "mmc3", 2 },
	} },
	{ SXIPIO_PIN(I, 6), {
		{ "gpio_in", 0 },
		{ "gpio_out", 1 },
		{ "mmc3", 2 },
	} },
	{ SXIPIO_PIN(I, 7), {
		{ "gpio_in", 0 },
		{ "gpio_out", 1 },
		{ "mmc3", 2 },
	} },
	{ SXIPIO_PIN(I, 8), {
		{ "gpio_in", 0 },
		{ "gpio_out", 1 },
		{ "mmc3", 2 },
	} },
	{ SXIPIO_PIN(I, 9), {
		{ "gpio_in", 0 },
		{ "gpio_out", 1 },
		{ "mmc3", 2 },
	} },
	{ SXIPIO_PIN(I, 10), {
		{ "gpio_in", 0 },
		{ "gpio_out", 1 },
		{ "spi0", 2 },
		{ "uart5", 3 },
		{ "irq", 6 },
	} },
	{ SXIPIO_PIN(I, 11), {
		{ "gpio_in", 0 },
		{ "gpio_out", 1 },
		{ "spi0", 2 },
		{ "uart5", 3 },
		{ "irq", 6 },
	} },
	{ SXIPIO_PIN(I, 12), {
		{ "gpio_in", 0 },
		{ "gpio_out", 1 },
		{ "spi0", 2 },
		{ "uart6", 3 },
		{ "irq", 6 },
	} },
	{ SXIPIO_PIN(I, 13), {
		{ "gpio_in", 0 },
		{ "gpio_out", 1 },
		{ "spi0", 2 },
		{ "uart6", 3 },
		{ "irq", 6 },
	} },
	{ SXIPIO_PIN(I, 14), {
		{ "gpio_in", 0 },
		{ "gpio_out", 1 },
		{ "spi0", 2 },
		{ "ps2", 3 },
		{ "timer4", 4 },
		{ "irq", 6 },
	} },
	{ SXIPIO_PIN(I, 15), {
		{ "gpio_in", 0 },
		{ "gpio_out", 1 },
		{ "spi1", 2 },
		{ "ps2", 3 },
		{ "timer5", 4 },
		{ "irq", 6 },
	} },
	{ SXIPIO_PIN(I, 16), {
		{ "gpio_in", 0 },
		{ "gpio_out", 1 },
		{ "spi1", 2 },
		{ "uart2", 3 },
		{ "irq", 6 },
	} },
	{ SXIPIO_PIN(I, 17), {
		{ "gpio_in", 0 },
		{ "gpio_out", 1 },
		{ "spi1", 2 },
		{ "uart2", 3 },
		{ "irq", 6 },
	} },
	{ SXIPIO_PIN(I, 18), {
		{ "gpio_in", 0 },
		{ "gpio_out", 1 },
		{ "spi1", 2 },
		{ "uart2", 3 },
		{ "irq", 6 },
	} },
	{ SXIPIO_PIN(I, 19), {
		{ "gpio_in", 0 },
		{ "gpio_out", 1 },
		{ "spi1", 2 },
		{ "uart2", 3 },
		{ "irq", 6 },
	} },
	{ SXIPIO_PIN(I, 20), {
		{ "gpio_in", 0 },
		{ "gpio_out", 1 },
		{ "ps2", 2 },
		{ "uart7", 3 },
		{ "hdmi", 4 },
	} },
	{ SXIPIO_PIN(I, 21), {
		{ "gpio_in", 0 },
		{ "gpio_out", 1 },
		{ "ps2", 2 },
		{ "uart7", 3 },
		{ "hdmi", 4 },
	} },
};

struct sxipio_pin sun5i_a13_pins[] = {
	{ SXIPIO_PIN(B, 0), {
		{ "gpio_in", 0 },
		{ "gpio_out", 1 },
		{ "i2c0", 2 },
	} },
	{ SXIPIO_PIN(B, 1), {
		{ "gpio_in", 0 },
		{ "gpio_out", 1 },
		{ "i2c0", 2 },
	} },
	{ SXIPIO_PIN(B, 2), {
		{ "gpio_in", 0 },
		{ "gpio_out", 1 },
		{ "pwm", 2 },
		{ "irq", 6 },
	} },
	{ SXIPIO_PIN(B, 3), {
		{ "gpio_in", 0 },
		{ "gpio_out", 1 },
		{ "ir0", 2 },
		{ "irq", 6 },
	} },
	{ SXIPIO_PIN(B, 4), {
		{ "gpio_in", 0 },
		{ "gpio_out", 1 },
		{ "ir0", 2 },
		{ "irq", 6 },
	} },
	{ SXIPIO_PIN(B, 10), {
		{ "gpio_in", 0 },
		{ "gpio_out", 1 },
		{ "spi2", 2 },
		{ "irq", 6 },
	} },
	{ SXIPIO_PIN(B, 15), {
		{ "gpio_in", 0 },
		{ "gpio_out", 1 },
		{ "i2c1", 2 },
	} },
	{ SXIPIO_PIN(B, 16), {
		{ "gpio_in", 0 },
		{ "gpio_out", 1 },
		{ "i2c1", 2 },
	} },
	{ SXIPIO_PIN(B, 17), {
		{ "gpio_in", 0 },
		{ "gpio_out", 1 },
		{ "i2c2", 2 },
	} },
	{ SXIPIO_PIN(B, 18), {
		{ "gpio_in", 0 },
		{ "gpio_out", 1 },
		{ "i2c2", 2 },
	} },
	{ SXIPIO_PIN(C, 0), {
		{ "gpio_in", 0 },
		{ "gpio_out", 1 },
		{ "nand0", 2 },
		{ "spi0", 3 },
	} },
	{ SXIPIO_PIN(C, 1), {
		{ "gpio_in", 0 },
		{ "gpio_out", 1 },
		{ "nand0", 2 },
		{ "spi0", 3 },
	} },
	{ SXIPIO_PIN(C, 2), {
		{ "gpio_in", 0 },
		{ "gpio_out", 1 },
		{ "nand0", 2 },
		{ "spi0", 3 },
	} },
	{ SXIPIO_PIN(C, 3), {
		{ "gpio_in", 0 },
		{ "gpio_out", 1 },
		{ "nand0", 2 },
		{ "spi0", 3 },
	} },
	{ SXIPIO_PIN(C, 4), {
		{ "gpio_in", 0 },
		{ "gpio_out", 1 },
		{ "nand0", 2 },
	} },
	{ SXIPIO_PIN(C, 5), {
		{ "gpio_in", 0 },
		{ "gpio_out", 1 },
		{ "nand0", 2 },
	} },
	{ SXIPIO_PIN(C, 6), {
		{ "gpio_in", 0 },
		{ "gpio_out", 1 },
		{ "nand0", 2 },
		{ "mmc2", 3 },
	} },
	{ SXIPIO_PIN(C, 7), {
		{ "gpio_in", 0 },
		{ "gpio_out", 1 },
		{ "nand0", 2 },
		{ "mmc2", 3 },
	} },
	{ SXIPIO_PIN(C, 8), {
		{ "gpio_in", 0 },
		{ "gpio_out", 1 },
		{ "nand0", 2 },
		{ "mmc2", 3 },
	} },
	{ SXIPIO_PIN(C, 9), {
		{ "gpio_in", 0 },
		{ "gpio_out", 1 },
		{ "nand0", 2 },
		{ "mmc2", 3 },
	} },
	{ SXIPIO_PIN(C, 10), {
		{ "gpio_in", 0 },
		{ "gpio_out", 1 },
		{ "nand0", 2 },
		{ "mmc2", 3 },
	} },
	{ SXIPIO_PIN(C, 11), {
		{ "gpio_in", 0 },
		{ "gpio_out", 1 },
		{ "nand0", 2 },
		{ "mmc2", 3 },
	} },
	{ SXIPIO_PIN(C, 12), {
		{ "gpio_in", 0 },
		{ "gpio_out", 1 },
		{ "nand0", 2 },
		{ "mmc2", 3 },
	} },
	{ SXIPIO_PIN(C, 13), {
		{ "gpio_in", 0 },
		{ "gpio_out", 1 },
		{ "nand0", 2 },
		{ "mmc2", 3 },
	} },
	{ SXIPIO_PIN(C, 14), {
		{ "gpio_in", 0 },
		{ "gpio_out", 1 },
		{ "nand0", 2 },
		{ "mmc2", 3 },
	} },
	{ SXIPIO_PIN(C, 15), {
		{ "gpio_in", 0 },
		{ "gpio_out", 1 },
		{ "nand0", 2 },
		{ "mmc2", 3 },
	} },
	{ SXIPIO_PIN(C, 19), {
		{ "gpio_in", 0 },
		{ "gpio_out", 1 },
		{ "nand0", 2 },
		{ "uart3", 4 },
	} },
	{ SXIPIO_PIN(D, 2), {
		{ "gpio_in", 0 },
		{ "gpio_out", 1 },
		{ "lcd0", 2 },
	} },
	{ SXIPIO_PIN(D, 3), {
		{ "gpio_in", 0 },
		{ "gpio_out", 1 },
		{ "lcd0", 2 },
	} },
	{ SXIPIO_PIN(D, 4), {
		{ "gpio_in", 0 },
		{ "gpio_out", 1 },
		{ "lcd0", 2 },
	} },
	{ SXIPIO_PIN(D, 5), {
		{ "gpio_in", 0 },
		{ "gpio_out", 1 },
		{ "lcd0", 2 },
	} },
	{ SXIPIO_PIN(D, 6), {
		{ "gpio_in", 0 },
		{ "gpio_out", 1 },
		{ "lcd0", 2 },
	} },
	{ SXIPIO_PIN(D, 7), {
		{ "gpio_in", 0 },
		{ "gpio_out", 1 },
		{ "lcd0", 2 },
	} },
	{ SXIPIO_PIN(D, 10), {
		{ "gpio_in", 0 },
		{ "gpio_out", 1 },
		{ "lcd0", 2 },
	} },
	{ SXIPIO_PIN(D, 11), {
		{ "gpio_in", 0 },
		{ "gpio_out", 1 },
		{ "lcd0", 2 },
	} },
	{ SXIPIO_PIN(D, 12), {
		{ "gpio_in", 0 },
		{ "gpio_out", 1 },
		{ "lcd0", 2 },
	} },
	{ SXIPIO_PIN(D, 13), {
		{ "gpio_in", 0 },
		{ "gpio_out", 1 },
		{ "lcd0", 2 },
	} },
	{ SXIPIO_PIN(D, 14), {
		{ "gpio_in", 0 },
		{ "gpio_out", 1 },
		{ "lcd0", 2 },
	} },
	{ SXIPIO_PIN(D, 15), {
		{ "gpio_in", 0 },
		{ "gpio_out", 1 },
		{ "lcd0", 2 },
	} },
	{ SXIPIO_PIN(D, 18), {
		{ "gpio_in", 0 },
		{ "gpio_out", 1 },
		{ "lcd0", 2 },
	} },
	{ SXIPIO_PIN(D, 19), {
		{ "gpio_in", 0 },
		{ "gpio_out", 1 },
		{ "lcd0", 2 },
	} },
	{ SXIPIO_PIN(D, 20), {
		{ "gpio_in", 0 },
		{ "gpio_out", 1 },
		{ "lcd0", 2 },
	} },
	{ SXIPIO_PIN(D, 21), {
		{ "gpio_in", 0 },
		{ "gpio_out", 1 },
		{ "lcd0", 2 },
	} },
	{ SXIPIO_PIN(D, 22), {
		{ "gpio_in", 0 },
		{ "gpio_out", 1 },
		{ "lcd0", 2 },
	} },
	{ SXIPIO_PIN(D, 23), {
		{ "gpio_in", 0 },
		{ "gpio_out", 1 },
		{ "lcd0", 2 },
	} },
	{ SXIPIO_PIN(D, 24), {
		{ "gpio_in", 0 },
		{ "gpio_out", 1 },
		{ "lcd0", 2 },
	} },
	{ SXIPIO_PIN(D, 25), {
		{ "gpio_in", 0 },
		{ "gpio_out", 1 },
		{ "lcd0", 2 },
	} },
	{ SXIPIO_PIN(D, 26), {
		{ "gpio_in", 0 },
		{ "gpio_out", 1 },
		{ "lcd0", 2 },
	} },
	{ SXIPIO_PIN(D, 27), {
		{ "gpio_in", 0 },
		{ "gpio_out", 1 },
		{ "lcd0", 2 },
	} },
	{ SXIPIO_PIN(E, 0), {
		{ "gpio_in", 0 },
		{ "csi0", 3 },
		{ "spi2", 4 },
		{ "irq", 6 },
	} },
	{ SXIPIO_PIN(E, 1), {
		{ "gpio_in", 0 },
		{ "csi0", 3 },
		{ "spi2", 4 },
		{ "irq", 6 },
	} },
	{ SXIPIO_PIN(E, 2), {
		{ "gpio_in", 0 },
		{ "csi0", 3 },
		{ "spi2", 4 },
	} },
	{ SXIPIO_PIN(E, 3), {
		{ "gpio_in", 0 },
		{ "gpio_out", 1 },
		{ "csi0", 3 },
		{ "spi2", 4 },
	} },
	{ SXIPIO_PIN(E, 4), {
		{ "gpio_in", 0 },
		{ "gpio_out", 1 },
		{ "csi0", 3 },
		{ "mmc2", 4 },
	} },
	{ SXIPIO_PIN(E, 5), {
		{ "gpio_in", 0 },
		{ "gpio_out", 1 },
		{ "csi0", 3 },
		{ "mmc2", 4 },
	} },
	{ SXIPIO_PIN(E, 6), {
		{ "gpio_in", 0 },
		{ "gpio_out", 1 },
		{ "csi0", 3 },
		{ "mmc2", 4 },
	} },
	{ SXIPIO_PIN(E, 7), {
		{ "gpio_in", 0 },
		{ "gpio_out", 1 },
		{ "csi0", 3 },
		{ "mmc2", 4 },
	} },
	{ SXIPIO_PIN(E, 8), {
		{ "gpio_in", 0 },
		{ "gpio_out", 1 },
		{ "csi0", 3 },
		{ "mmc2", 4 },
	} },
	{ SXIPIO_PIN(E, 9), {
		{ "gpio_in", 0 },
		{ "gpio_out", 1 },
		{ "csi0", 3 },
		{ "mmc2", 4 },
	} },
	{ SXIPIO_PIN(E, 10), {
		{ "gpio_in", 0 },
		{ "gpio_out", 1 },
		{ "csi0", 3 },
		{ "uart1", 4 },
	} },
	{ SXIPIO_PIN(E, 11), {
		{ "gpio_in", 0 },
		{ "gpio_out", 1 },
		{ "csi0", 3 },
		{ "uart1", 4 },
	} },
	{ SXIPIO_PIN(F, 0), {
		{ "gpio_in", 0 },
		{ "gpio_out", 1 },
		{ "mmc0", 2 },
	} },
	{ SXIPIO_PIN(F, 1), {
		{ "gpio_in", 0 },
		{ "gpio_out", 1 },
		{ "mmc0", 2 },
	} },
	{ SXIPIO_PIN(F, 2), {
		{ "gpio_in", 0 },
		{ "gpio_out", 1 },
		{ "mmc0", 2 },
	} },
	{ SXIPIO_PIN(F, 3), {
		{ "gpio_in", 0 },
		{ "gpio_out", 1 },
		{ "mmc0", 2 },
	} },
	{ SXIPIO_PIN(F, 4), {
		{ "gpio_in", 0 },
		{ "gpio_out", 1 },
		{ "mmc0", 2 },
	} },
	{ SXIPIO_PIN(F, 5), {
		{ "gpio_in", 0 },
		{ "gpio_out", 1 },
		{ "mmc0", 2 },
	} },
	{ SXIPIO_PIN(G, 0), {
		{ "gpio_in", 0 },
		{ "irq", 6 },
	} },
	{ SXIPIO_PIN(G, 1), {
		{ "gpio_in", 0 },
		{ "irq", 6 },
	} },
	{ SXIPIO_PIN(G, 2), {
		{ "gpio_in", 0 },
		{ "irq", 6 },
	} },
	{ SXIPIO_PIN(G, 3), {
		{ "gpio_in", 0 },
		{ "gpio_out", 1 },
		{ "mmc1", 2 },
		{ "uart1", 4 },
		{ "irq", 6 },
	} },
	{ SXIPIO_PIN(G, 4), {
		{ "gpio_in", 0 },
		{ "gpio_out", 1 },
		{ "mmc1", 2 },
		{ "uart1", 4 },
		{ "irq", 6 },
	} },
	{ SXIPIO_PIN(G, 9), {
		{ "gpio_in", 0 },
		{ "gpio_out", 1 },
		{ "spi1", 2 },
		{ "uart3", 3 },
		{ "irq", 6 },
	} },
	{ SXIPIO_PIN(G, 10), {
		{ "gpio_in", 0 },
		{ "gpio_out", 1 },
		{ "spi1", 2 },
		{ "uart3", 3 },
		{ "irq", 6 },
	} },
	{ SXIPIO_PIN(G, 11), {
		{ "gpio_in", 0 },
		{ "gpio_out", 1 },
		{ "spi1", 2 },
		{ "uart3", 3 },
		{ "irq", 6 },
	} },
	{ SXIPIO_PIN(G, 12), {
		{ "gpio_in", 0 },
		{ "gpio_out", 1 },
		{ "spi1", 2 },
		{ "uart3", 3 },
		{ "irq", 6 },
	} },
};

struct sxipio_pin sun5i_a10s_pins[] = {
	{ SXIPIO_PIN(A, 0), {
		{ "gpio_in", 0 },
		{ "gpio_out", 1 },
		{ "emac", 2 },
		{ "ts0", 3 },
		{ "keypad", 5 },
	} },
	{ SXIPIO_PIN(A, 1), {
		{ "gpio_in", 0 },
		{ "gpio_out", 1 },
		{ "emac", 2 },
		{ "ts0", 3 },
		{ "keypad", 5 },
	} },
	{ SXIPIO_PIN(A, 2), {
		{ "gpio_in", 0 },
		{ "gpio_out", 1 },
		{ "emac", 2 },
		{ "ts0", 3 },
		{ "keypad", 5 },
	} },
	{ SXIPIO_PIN(A, 3), {
		{ "gpio_in", 0 },
		{ "gpio_out", 1 },
		{ "emac", 2 },
		{ "ts0", 3 },
		{ "keypad", 5 },
	} },
	{ SXIPIO_PIN(A, 4), {
		{ "gpio_in", 0 },
		{ "gpio_out", 1 },
		{ "emac", 2 },
		{ "ts0", 3 },
		{ "keypad", 5 },
	} },
	{ SXIPIO_PIN(A, 5), {
		{ "gpio_in", 0 },
		{ "gpio_out", 1 },
		{ "emac", 2 },
		{ "ts0", 3 },
		{ "keypad", 5 },
	} },
	{ SXIPIO_PIN(A, 6), {
		{ "gpio_in", 0 },
		{ "gpio_out", 1 },
		{ "emac", 2 },
		{ "ts0", 3 },
		{ "keypad", 5 },
	} },
	{ SXIPIO_PIN(A, 7), {
		{ "gpio_in", 0 },
		{ "gpio_out", 1 },
		{ "emac", 2 },
		{ "ts0", 3 },
		{ "keypad", 5 },
	} },
	{ SXIPIO_PIN(A, 8), {
		{ "gpio_in", 0 },
		{ "gpio_out", 1 },
		{ "emac", 2 },
		{ "ts0", 3 },
		{ "uart1", 4 },
		{ "keypad", 5 },
	} },
	{ SXIPIO_PIN(A, 9), {
		{ "gpio_in", 0 },
		{ "gpio_out", 1 },
		{ "emac", 2 },
		{ "ts0", 3 },
		{ "uart1", 4 },
		{ "keypad", 5 },
	} },
	{ SXIPIO_PIN(A, 10), {
		{ "gpio_in", 0 },
		{ "gpio_out", 1 },
		{ "emac", 2 },
		{ "ts0", 3 },
		{ "uart1", 4 },
		{ "keypad", 5 },
	} },
	{ SXIPIO_PIN(A, 11), {
		{ "gpio_in", 0 },
		{ "gpio_out", 1 },
		{ "emac", 2 },
		{ "ts0", 3 },
		{ "uart1", 4 },
		{ "keypad", 5 },
	} },
	{ SXIPIO_PIN(A, 12), {
		{ "gpio_in", 0 },
		{ "gpio_out", 1 },
		{ "emac", 2 },
		{ "uart1", 3 },
		{ "keypad", 5 },
	} },
	{ SXIPIO_PIN(A, 13), {
		{ "gpio_in", 0 },
		{ "gpio_out", 1 },
		{ "emac", 2 },
		{ "uart1", 3 },
		{ "keypad", 5 },
	} },
	{ SXIPIO_PIN(A, 14), {
		{ "gpio_in", 0 },
		{ "gpio_out", 1 },
		{ "emac", 2 },
		{ "uart1", 3 },
		{ "uart3", 4 },
		{ "keypad", 5 },
	} },
	{ SXIPIO_PIN(A, 15), {
		{ "gpio_in", 0 },
		{ "gpio_out", 1 },
		{ "emac", 2 },
		{ "uart1", 3 },
		{ "uart3", 4 },
		{ "keypad", 5 },
	} },
	{ SXIPIO_PIN(A, 16), {
		{ "gpio_in", 0 },
		{ "gpio_out", 1 },
		{ "emac", 2 },
		{ "uart2", 3 },
	} },
	{ SXIPIO_PIN(A, 17), {
		{ "gpio_in", 0 },
		{ "gpio_out", 1 },
		{ "emac", 2 },
		{ "uart2", 3 },
		{ "irq", 6 },
	} },
	{ SXIPIO_PIN(B, 0), {
		{ "gpio_in", 0 },
		{ "gpio_out", 1 },
		{ "i2c0", 2 },
	} },
	{ SXIPIO_PIN(B, 1), {
		{ "gpio_in", 0 },
		{ "gpio_out", 1 },
		{ "i2c0", 2 },
	} },
	{ SXIPIO_PIN(B, 2), {
		{ "gpio_in", 0 },
		{ "gpio_out", 1 },
		{ "pwm", 2 },
		{ "irq", 6 },
	} },
	{ SXIPIO_PIN(B, 3), {
		{ "gpio_in", 0 },
		{ "gpio_out", 1 },
		{ "ir0", 2 },
		{ "irq", 6 },
	} },
	{ SXIPIO_PIN(B, 4), {
		{ "gpio_in", 0 },
		{ "gpio_out", 1 },
		{ "ir0", 2 },
		{ "irq", 6 },
	} },
	{ SXIPIO_PIN(B, 5), {
		{ "gpio_in", 0 },
		{ "gpio_out", 1 },
		{ "i2s", 2 },
		{ "irq", 6 },
	} },
	{ SXIPIO_PIN(B, 6), {
		{ "gpio_in", 0 },
		{ "gpio_out", 1 },
		{ "i2s", 2 },
		{ "irq", 6 },
	} },
	{ SXIPIO_PIN(B, 7), {
		{ "gpio_in", 0 },
		{ "gpio_out", 1 },
		{ "i2s", 2 },
		{ "irq", 6 },
	} },
	{ SXIPIO_PIN(B, 8), {
		{ "gpio_in", 0 },
		{ "gpio_out", 1 },
		{ "i2s", 2 },
		{ "irq", 6 },
	} },
	{ SXIPIO_PIN(B, 9), {
		{ "gpio_in", 0 },
		{ "gpio_out", 1 },
		{ "i2s", 2 },
		{ "irq", 6 },
	} },
	{ SXIPIO_PIN(B, 10), {
		{ "gpio_in", 0 },
		{ "gpio_out", 1 },
		{ "spi2", 2 },
		{ "irq", 6 },
	} },
	{ SXIPIO_PIN(B, 11), {
		{ "gpio_in", 0 },
		{ "gpio_out", 1 },
		{ "spi2", 2 },
		{ "jtag", 3 },
		{ "irq", 6 },
	} },
	{ SXIPIO_PIN(B, 12), {
		{ "gpio_in", 0 },
		{ "gpio_out", 1 },
		{ "spi2", 2 },
		{ "jtag", 3 },
		{ "irq", 6 },
	} },
	{ SXIPIO_PIN(B, 13), {
		{ "gpio_in", 0 },
		{ "gpio_out", 1 },
		{ "spi2", 2 },
		{ "jtag", 3 },
		{ "irq", 6 },
	} },
	{ SXIPIO_PIN(B, 14), {
		{ "gpio_in", 0 },
		{ "gpio_out", 1 },
		{ "spi2", 2 },
		{ "jtag", 3 },
		{ "irq", 6 },
	} },
	{ SXIPIO_PIN(B, 15), {
		{ "gpio_in", 0 },
		{ "gpio_out", 1 },
		{ "i2c1", 2 },
	} },
	{ SXIPIO_PIN(B, 16), {
		{ "gpio_in", 0 },
		{ "gpio_out", 1 },
		{ "i2c1", 2 },
	} },
	{ SXIPIO_PIN(B, 17), {
		{ "gpio_in", 0 },
		{ "gpio_out", 1 },
		{ "i2c2", 2 },
	} },
	{ SXIPIO_PIN(B, 18), {
		{ "gpio_in", 0 },
		{ "gpio_out", 1 },
		{ "i2c2", 2 },
	} },
	{ SXIPIO_PIN(B, 19), {
		{ "gpio_in", 0 },
		{ "gpio_out", 1 },
		{ "uart0", 2 },
		{ "irq", 6 },
	} },
	{ SXIPIO_PIN(B, 20), {
		{ "gpio_in", 0 },
		{ "gpio_out", 1 },
		{ "uart0", 2 },
		{ "irq", 6 },
	} },
	{ SXIPIO_PIN(C, 0), {
		{ "gpio_in", 0 },
		{ "gpio_out", 1 },
		{ "nand0", 2 },
		{ "spi0", 3 },
	} },
	{ SXIPIO_PIN(C, 1), {
		{ "gpio_in", 0 },
		{ "gpio_out", 1 },
		{ "nand0", 2 },
		{ "spi0", 3 },
	} },
	{ SXIPIO_PIN(C, 2), {
		{ "gpio_in", 0 },
		{ "gpio_out", 1 },
		{ "nand0", 2 },
		{ "spi0", 3 },
	} },
	{ SXIPIO_PIN(C, 3), {
		{ "gpio_in", 0 },
		{ "gpio_out", 1 },
		{ "nand0", 2 },
		{ "spi0", 3 },
	} },
	{ SXIPIO_PIN(C, 4), {
		{ "gpio_in", 0 },
		{ "gpio_out", 1 },
		{ "nand0", 2 },
	} },
	{ SXIPIO_PIN(C, 5), {
		{ "gpio_in", 0 },
		{ "gpio_out", 1 },
		{ "nand0", 2 },
	} },
	{ SXIPIO_PIN(C, 6), {
		{ "gpio_in", 0 },
		{ "gpio_out", 1 },
		{ "nand0", 2 },
		{ "mmc2", 3 },
	} },
	{ SXIPIO_PIN(C, 7), {
		{ "gpio_in", 0 },
		{ "gpio_out", 1 },
		{ "nand0", 2 },
		{ "mmc2", 3 },
	} },
	{ SXIPIO_PIN(C, 8), {
		{ "gpio_in", 0 },
		{ "gpio_out", 1 },
		{ "nand0", 2 },
		{ "mmc2", 3 },
	} },
	{ SXIPIO_PIN(C, 9), {
		{ "gpio_in", 0 },
		{ "gpio_out", 1 },
		{ "nand0", 2 },
		{ "mmc2", 3 },
	} },
	{ SXIPIO_PIN(C, 10), {
		{ "gpio_in", 0 },
		{ "gpio_out", 1 },
		{ "nand0", 2 },
		{ "mmc2", 3 },
	} },
	{ SXIPIO_PIN(C, 11), {
		{ "gpio_in", 0 },
		{ "gpio_out", 1 },
		{ "nand0", 2 },
		{ "mmc2", 3 },
	} },
	{ SXIPIO_PIN(C, 12), {
		{ "gpio_in", 0 },
		{ "gpio_out", 1 },
		{ "nand0", 2 },
		{ "mmc2", 3 },
	} },
	{ SXIPIO_PIN(C, 13), {
		{ "gpio_in", 0 },
		{ "gpio_out", 1 },
		{ "nand0", 2 },
		{ "mmc2", 3 },
	} },
	{ SXIPIO_PIN(C, 14), {
		{ "gpio_in", 0 },
		{ "gpio_out", 1 },
		{ "nand0", 2 },
		{ "mmc2", 3 },
	} },
	{ SXIPIO_PIN(C, 15), {
		{ "gpio_in", 0 },
		{ "gpio_out", 1 },
		{ "nand0", 2 },
		{ "mmc2", 3 },
	} },
	{ SXIPIO_PIN(C, 16), {
		{ "gpio_in", 0 },
		{ "gpio_out", 1 },
		{ "nand0", 2 },
		{ "uart3", 4 },
	} },
	{ SXIPIO_PIN(C, 17), {
		{ "gpio_in", 0 },
		{ "gpio_out", 1 },
		{ "nand0", 2 },
		{ "uart3", 4 },
	} },
	{ SXIPIO_PIN(C, 18), {
		{ "gpio_in", 0 },
		{ "gpio_out", 1 },
		{ "nand0", 2 },
		{ "uart2", 3 },
		{ "uart3", 4 },
	} },
	{ SXIPIO_PIN(C, 19), {
		{ "gpio_in", 0 },
		{ "gpio_out", 1 },
		{ "nand0", 2 },
		{ "uart2", 3 },
		{ "uart3", 4 },
	} },
	{ SXIPIO_PIN(D, 0), {
		{ "gpio_in", 0 },
		{ "gpio_out", 1 },
		{ "lcd0", 2 },
	} },
	{ SXIPIO_PIN(D, 1), {
		{ "gpio_in", 0 },
		{ "gpio_out", 1 },
		{ "lcd0", 2 },
	} },
	{ SXIPIO_PIN(D, 2), {
		{ "gpio_in", 0 },
		{ "gpio_out", 1 },
		{ "lcd0", 2 },
		{ "uart2", 3 },
	} },
	{ SXIPIO_PIN(D, 3), {
		{ "gpio_in", 0 },
		{ "gpio_out", 1 },
		{ "lcd0", 2 },
		{ "uart2", 3 },
	} },
	{ SXIPIO_PIN(D, 4), {
		{ "gpio_in", 0 },
		{ "gpio_out", 1 },
		{ "lcd0", 2 },
		{ "uart2", 3 },
	} },
	{ SXIPIO_PIN(D, 5), {
		{ "gpio_in", 0 },
		{ "gpio_out", 1 },
		{ "lcd0", 2 },
		{ "uart2", 3 },
	} },
	{ SXIPIO_PIN(D, 6), {
		{ "gpio_in", 0 },
		{ "gpio_out", 1 },
		{ "lcd0", 2 },
		{ "emac", 3 },
	} },
	{ SXIPIO_PIN(D, 7), {
		{ "gpio_in", 0 },
		{ "gpio_out", 1 },
		{ "lcd0", 2 },
		{ "emac", 3 },
	} },
	{ SXIPIO_PIN(D, 8), {
		{ "gpio_in", 0 },
		{ "gpio_out", 1 },
		{ "lcd0", 2 },
	} },
	{ SXIPIO_PIN(D, 9), {
		{ "gpio_in", 0 },
		{ "gpio_out", 1 },
		{ "lcd0", 2 },
	} },
	{ SXIPIO_PIN(D, 10), {
		{ "gpio_in", 0 },
		{ "gpio_out", 1 },
		{ "lcd0", 2 },
		{ "emac", 3 },
	} },
	{ SXIPIO_PIN(D, 11), {
		{ "gpio_in", 0 },
		{ "gpio_out", 1 },
		{ "lcd0", 2 },
		{ "emac", 3 },
	} },
	{ SXIPIO_PIN(D, 12), {
		{ "gpio_in", 0 },
		{ "gpio_out", 1 },
		{ "lcd0", 2 },
		{ "emac", 3 },
	} },
	{ SXIPIO_PIN(D, 13), {
		{ "gpio_in", 0 },
		{ "gpio_out", 1 },
		{ "lcd0", 2 },
		{ "emac", 3 },
	} },
	{ SXIPIO_PIN(D, 14), {
		{ "gpio_in", 0 },
		{ "gpio_out", 1 },
		{ "lcd0", 2 },
		{ "emac", 3 },
	} },
	{ SXIPIO_PIN(D, 15), {
		{ "gpio_in", 0 },
		{ "gpio_out", 1 },
		{ "lcd0", 2 },
		{ "emac", 3 },
	} },
	{ SXIPIO_PIN(D, 16), {
		{ "gpio_in", 0 },
		{ "gpio_out", 1 },
		{ "lcd0", 2 },
	} },
	{ SXIPIO_PIN(D, 17), {
		{ "gpio_in", 0 },
		{ "gpio_out", 1 },
		{ "lcd0", 2 },
	} },
	{ SXIPIO_PIN(D, 18), {
		{ "gpio_in", 0 },
		{ "gpio_out", 1 },
		{ "lcd0", 2 },
		{ "emac", 3 },
	} },
	{ SXIPIO_PIN(D, 19), {
		{ "gpio_in", 0 },
		{ "gpio_out", 1 },
		{ "lcd0", 2 },
		{ "emac", 3 },
	} },
	{ SXIPIO_PIN(D, 20), {
		{ "gpio_in", 0 },
		{ "gpio_out", 1 },
		{ "lcd0", 2 },
		{ "emac", 3 },
	} },
	{ SXIPIO_PIN(D, 21), {
		{ "gpio_in", 0 },
		{ "gpio_out", 1 },
		{ "lcd0", 2 },
		{ "emac", 3 },
	} },
	{ SXIPIO_PIN(D, 22), {
		{ "gpio_in", 0 },
		{ "gpio_out", 1 },
		{ "lcd0", 2 },
		{ "emac", 3 },
	} },
	{ SXIPIO_PIN(D, 23), {
		{ "gpio_in", 0 },
		{ "gpio_out", 1 },
		{ "lcd0", 2 },
		{ "emac", 3 },
	} },
	{ SXIPIO_PIN(D, 24), {
		{ "gpio_in", 0 },
		{ "gpio_out", 1 },
		{ "lcd0", 2 },
		{ "emac", 3 },
	} },
	{ SXIPIO_PIN(D, 25), {
		{ "gpio_in", 0 },
		{ "gpio_out", 1 },
		{ "lcd0", 2 },
		{ "emac", 3 },
	} },
	{ SXIPIO_PIN(D, 26), {
		{ "gpio_in", 0 },
		{ "gpio_out", 1 },
		{ "lcd0", 2 },
		{ "emac", 3 },
	} },
	{ SXIPIO_PIN(D, 27), {
		{ "gpio_in", 0 },
		{ "gpio_out", 1 },
		{ "lcd0", 2 },
		{ "emac", 3 },
	} },
	{ SXIPIO_PIN(E, 0), {
		{ "gpio_in", 0 },
		{ "ts0", 2 },
		{ "csi0", 3 },
		{ "spi2", 4 },
		{ "irq", 6 },
	} },
	{ SXIPIO_PIN(E, 1), {
		{ "gpio_in", 0 },
		{ "ts0", 2 },
		{ "csi0", 3 },
		{ "spi2", 4 },
		{ "irq", 6 },
	} },
	{ SXIPIO_PIN(E, 2), {
		{ "gpio_in", 0 },
		{ "ts0", 2 },
		{ "csi0", 3 },
		{ "spi2", 4 },
	} },
	{ SXIPIO_PIN(E, 3), {
		{ "gpio_in", 0 },
		{ "gpio_out", 1 },
		{ "ts0", 2 },
		{ "csi0", 3 },
		{ "spi2", 4 },
	} },
	{ SXIPIO_PIN(E, 4), {
		{ "gpio_in", 0 },
		{ "gpio_out", 1 },
		{ "ts0", 2 },
		{ "csi0", 3 },
		{ "mmc2", 4 },
	} },
	{ SXIPIO_PIN(E, 5), {
		{ "gpio_in", 0 },
		{ "gpio_out", 1 },
		{ "ts0", 2 },
		{ "csi0", 3 },
		{ "mmc2", 4 },
	} },
	{ SXIPIO_PIN(E, 6), {
		{ "gpio_in", 0 },
		{ "gpio_out", 1 },
		{ "ts0", 2 },
		{ "csi0", 3 },
		{ "mmc2", 4 },
	} },
	{ SXIPIO_PIN(E, 7), {
		{ "gpio_in", 0 },
		{ "gpio_out", 1 },
		{ "ts0", 2 },
		{ "csi0", 3 },
		{ "mmc2", 4 },
	} },
	{ SXIPIO_PIN(E, 8), {
		{ "gpio_in", 0 },
		{ "gpio_out", 1 },
		{ "ts0", 2 },
		{ "csi0", 3 },
		{ "mmc2", 4 },
	} },
	{ SXIPIO_PIN(E, 9), {
		{ "gpio_in", 0 },
		{ "gpio_out", 1 },
		{ "ts0", 2 },
		{ "csi0", 3 },
		{ "mmc2", 4 },
	} },
	{ SXIPIO_PIN(E, 10), {
		{ "gpio_in", 0 },
		{ "gpio_out", 1 },
		{ "ts0", 2 },
		{ "csi0", 3 },
		{ "uart1", 4 },
	} },
	{ SXIPIO_PIN(E, 11), {
		{ "gpio_in", 0 },
		{ "gpio_out", 1 },
		{ "ts0", 2 },
		{ "csi0", 3 },
		{ "uart1", 4 },
	} },
	{ SXIPIO_PIN(F, 0), {
		{ "gpio_in", 0 },
		{ "gpio_out", 1 },
		{ "mmc0", 2 },
		{ "jtag", 4 },
	} },
	{ SXIPIO_PIN(F, 1), {
		{ "gpio_in", 0 },
		{ "gpio_out", 1 },
		{ "mmc0", 2 },
		{ "jtag", 4 },
	} },
	{ SXIPIO_PIN(F, 2), {
		{ "gpio_in", 0 },
		{ "gpio_out", 1 },
		{ "mmc0", 2 },
		{ "uart0", 4 },
	} },
	{ SXIPIO_PIN(F, 3), {
		{ "gpio_in", 0 },
		{ "gpio_out", 1 },
		{ "mmc0", 2 },
		{ "jtag", 4 },
	} },
	{ SXIPIO_PIN(F, 4), {
		{ "gpio_in", 0 },
		{ "gpio_out", 1 },
		{ "mmc0", 2 },
		{ "uart0", 4 },
	} },
	{ SXIPIO_PIN(F, 5), {
		{ "gpio_in", 0 },
		{ "gpio_out", 1 },
		{ "mmc0", 2 },
		{ "jtag", 4 },
	} },
	{ SXIPIO_PIN(G, 0), {
		{ "gpio_in", 0 },
		{ "gps", 2 },
		{ "irq", 6 },
	} },
	{ SXIPIO_PIN(G, 1), {
		{ "gpio_in", 0 },
		{ "gps", 2 },
		{ "irq", 6 },
	} },
	{ SXIPIO_PIN(G, 2), {
		{ "gpio_in", 0 },
		{ "gps", 2 },
		{ "irq", 6 },
	} },
	{ SXIPIO_PIN(G, 3), {
		{ "gpio_in", 0 },
		{ "gpio_out", 1 },
		{ "mmc1", 2 },
		{ "uart1", 4 },
		{ "irq", 6 },
	} },
	{ SXIPIO_PIN(G, 4), {
		{ "gpio_in", 0 },
		{ "gpio_out", 1 },
		{ "mmc1", 2 },
		{ "uart1", 4 },
		{ "irq", 6 },
	} },
	{ SXIPIO_PIN(G, 5), {
		{ "gpio_in", 0 },
		{ "gpio_out", 1 },
		{ "mmc1", 2 },
		{ "uart1", 4 },
		{ "irq", 6 },
	} },
	{ SXIPIO_PIN(G, 6), {
		{ "gpio_in", 0 },
		{ "gpio_out", 1 },
		{ "mmc1", 2 },
		{ "uart1", 4 },
		{ "uart2", 5 },
		{ "irq", 6 },
	} },
	{ SXIPIO_PIN(G, 7), {
		{ "gpio_in", 0 },
		{ "gpio_out", 1 },
		{ "mmc1", 2 },
		{ "uart2", 5 },
		{ "irq", 6 },
	} },
	{ SXIPIO_PIN(G, 8), {
		{ "gpio_in", 0 },
		{ "gpio_out", 1 },
		{ "mmc1", 2 },
		{ "uart2", 5 },
		{ "irq", 6 },
	} },
	{ SXIPIO_PIN(G, 9), {
		{ "gpio_in", 0 },
		{ "gpio_out", 1 },
		{ "spi1", 2 },
		{ "uart3", 3 },
		{ "irq", 6 },
	} },
	{ SXIPIO_PIN(G, 10), {
		{ "gpio_in", 0 },
		{ "gpio_out", 1 },
		{ "spi1", 2 },
		{ "uart3", 3 },
		{ "irq", 6 },
	} },
	{ SXIPIO_PIN(G, 11), {
		{ "gpio_in", 0 },
		{ "gpio_out", 1 },
		{ "spi1", 2 },
		{ "uart3", 3 },
		{ "irq", 6 },
	} },
	{ SXIPIO_PIN(G, 12), {
		{ "gpio_in", 0 },
		{ "gpio_out", 1 },
		{ "spi1", 2 },
		{ "uart3", 3 },
		{ "irq", 6 },
	} },
	{ SXIPIO_PIN(G, 13), {
		{ "gpio_in", 0 },
		{ "gpio_out", 1 },
		{ "spi1", 2 },
		{ "pwm", 3 },
		{ "uart2", 5 },
		{ "irq", 6 },
	} },
};

struct sxipio_pin sun7i_a20_pins[] = {
	{ SXIPIO_PIN(A, 0), {
		{ "gpio_in", 0 },
		{ "gpio_out", 1 },
		{ "emac", 2 },
		{ "spi1", 3 },
		{ "uart2", 4 },
		{ "gmac", 5 },
	} },
	{ SXIPIO_PIN(A, 1), {
		{ "gpio_in", 0 },
		{ "gpio_out", 1 },
		{ "emac", 2 },
		{ "spi1", 3 },
		{ "uart2", 4 },
		{ "gmac", 5 },
	} },
	{ SXIPIO_PIN(A, 2), {
		{ "gpio_in", 0 },
		{ "gpio_out", 1 },
		{ "emac", 2 },
		{ "spi1", 3 },
		{ "uart2", 4 },
		{ "gmac", 5 },
	} },
	{ SXIPIO_PIN(A, 3), {
		{ "gpio_in", 0 },
		{ "gpio_out", 1 },
		{ "emac", 2 },
		{ "spi1", 3 },
		{ "uart2", 4 },
		{ "gmac", 5 },
	} },
	{ SXIPIO_PIN(A, 4), {
		{ "gpio_in", 0 },
		{ "gpio_out", 1 },
		{ "emac", 2 },
		{ "spi1", 3 },
		{ "gmac", 5 },
	} },
	{ SXIPIO_PIN(A, 5), {
		{ "gpio_in", 0 },
		{ "gpio_out", 1 },
		{ "emac", 2 },
		{ "spi3", 3 },
		{ "gmac", 5 },
	} },
	{ SXIPIO_PIN(A, 6), {
		{ "gpio_in", 0 },
		{ "gpio_out", 1 },
		{ "emac", 2 },
		{ "spi3", 3 },
		{ "gmac", 5 },
	} },
	{ SXIPIO_PIN(A, 7), {
		{ "gpio_in", 0 },
		{ "gpio_out", 1 },
		{ "emac", 2 },
		{ "spi3", 3 },
		{ "gmac", 5 },
	} },
	{ SXIPIO_PIN(A, 8), {
		{ "gpio_in", 0 },
		{ "gpio_out", 1 },
		{ "emac", 2 },
		{ "spi3", 3 },
		{ "gmac", 5 },
	} },
	{ SXIPIO_PIN(A, 9), {
		{ "gpio_in", 0 },
		{ "gpio_out", 1 },
		{ "emac", 2 },
		{ "spi3", 3 },
		{ "gmac", 5 },
		{ "i2s1", 6 },
	} },
	{ SXIPIO_PIN(A, 10), {
		{ "gpio_in", 0 },
		{ "gpio_out", 1 },
		{ "emac", 2 },
		{ "uart1", 4 },
		{ "gmac", 5 },
	} },
	{ SXIPIO_PIN(A, 11), {
		{ "gpio_in", 0 },
		{ "gpio_out", 1 },
		{ "emac", 2 },
		{ "uart1", 4 },
		{ "gmac", 5 },
	} },
	{ SXIPIO_PIN(A, 12), {
		{ "gpio_in", 0 },
		{ "gpio_out", 1 },
		{ "emac", 2 },
		{ "uart6", 3 },
		{ "uart1", 4 },
		{ "gmac", 5 },
	} },
	{ SXIPIO_PIN(A, 13), {
		{ "gpio_in", 0 },
		{ "gpio_out", 1 },
		{ "emac", 2 },
		{ "uart6", 3 },
		{ "uart1", 4 },
		{ "gmac", 5 },
	} },
	{ SXIPIO_PIN(A, 14), {
		{ "gpio_in", 0 },
		{ "gpio_out", 1 },
		{ "emac", 2 },
		{ "uart7", 3 },
		{ "uart1", 4 },
		{ "gmac", 5 },
		{ "i2s1", 6 },
	} },
	{ SXIPIO_PIN(A, 15), {
		{ "gpio_in", 0 },
		{ "gpio_out", 1 },
		{ "emac", 2 },
		{ "uart7", 3 },
		{ "uart1", 4 },
		{ "gmac", 5 },
		{ "i2s1", 6 },
	} },
	{ SXIPIO_PIN(A, 16), {
		{ "gpio_in", 0 },
		{ "gpio_out", 1 },
		{ "emac", 2 },
		{ "can", 3 },
		{ "uart1", 4 },
		{ "gmac", 5 },
		{ "i2s1", 6 },
	} },
	{ SXIPIO_PIN(A, 17), {
		{ "gpio_in", 0 },
		{ "gpio_out", 1 },
		{ "emac", 2 },
		{ "can", 3 },
		{ "uart1", 4 },
		{ "gmac", 5 },
		{ "i2s1", 6 },
	} },
	{ SXIPIO_PIN(B, 0), {
		{ "gpio_in", 0 },
		{ "gpio_out", 1 },
		{ "i2c0", 2 },
	} },
	{ SXIPIO_PIN(B, 1), {
		{ "gpio_in", 0 },
		{ "gpio_out", 1 },
		{ "i2c0", 2 },
	} },
	{ SXIPIO_PIN(B, 2), {
		{ "gpio_in", 0 },
		{ "gpio_out", 1 },
		{ "pwm", 2 },
	} },
	{ SXIPIO_PIN(B, 3), {
		{ "gpio_in", 0 },
		{ "gpio_out", 1 },
		{ "ir0", 2 },
		{ "spdif", 4 },
	} },
	{ SXIPIO_PIN(B, 4), {
		{ "gpio_in", 0 },
		{ "gpio_out", 1 },
		{ "ir0", 2 },
	} },
	{ SXIPIO_PIN(B, 5), {
		{ "gpio_in", 0 },
		{ "gpio_out", 1 },
		{ "i2s0", 2 },
		{ "ac97", 3 },
	} },
	{ SXIPIO_PIN(B, 6), {
		{ "gpio_in", 0 },
		{ "gpio_out", 1 },
		{ "i2s0", 2 },
		{ "ac97", 3 },
	} },
	{ SXIPIO_PIN(B, 7), {
		{ "gpio_in", 0 },
		{ "gpio_out", 1 },
		{ "i2s0", 2 },
		{ "ac97", 3 },
	} },
	{ SXIPIO_PIN(B, 8), {
		{ "gpio_in", 0 },
		{ "gpio_out", 1 },
		{ "i2s0", 2 },
		{ "ac97", 3 },
	} },
	{ SXIPIO_PIN(B, 9), {
		{ "gpio_in", 0 },
		{ "gpio_out", 1 },
		{ "i2s0", 2 },
	} },
	{ SXIPIO_PIN(B, 10), {
		{ "gpio_in", 0 },
		{ "gpio_out", 1 },
		{ "i2s0", 2 },
	} },
	{ SXIPIO_PIN(B, 11), {
		{ "gpio_in", 0 },
		{ "gpio_out", 1 },
		{ "i2s0", 2 },
	} },
	{ SXIPIO_PIN(B, 12), {
		{ "gpio_in", 0 },
		{ "gpio_out", 1 },
		{ "i2s0", 2 },
		{ "ac97", 3 },
		{ "spdif", 4 },
	} },
	{ SXIPIO_PIN(B, 13), {
		{ "gpio_in", 0 },
		{ "gpio_out", 1 },
		{ "spi2", 2 },
		{ "spdif", 4 },
	} },
	{ SXIPIO_PIN(B, 14), {
		{ "gpio_in", 0 },
		{ "gpio_out", 1 },
		{ "spi2", 2 },
		{ "jtag", 3 },
	} },
	{ SXIPIO_PIN(B, 15), {
		{ "gpio_in", 0 },
		{ "gpio_out", 1 },
		{ "spi2", 2 },
		{ "jtag", 3 },
	} },
	{ SXIPIO_PIN(B, 16), {
		{ "gpio_in", 0 },
		{ "gpio_out", 1 },
		{ "spi2", 2 },
		{ "jtag", 3 },
	} },
	{ SXIPIO_PIN(B, 17), {
		{ "gpio_in", 0 },
		{ "gpio_out", 1 },
		{ "spi2", 2 },
		{ "jtag", 3 },
	} },
	{ SXIPIO_PIN(B, 18), {
		{ "gpio_in", 0 },
		{ "gpio_out", 1 },
		{ "i2c1", 2 },
	} },
	{ SXIPIO_PIN(B, 19), {
		{ "gpio_in", 0 },
		{ "gpio_out", 1 },
		{ "i2c1", 2 },
	} },
	{ SXIPIO_PIN(B, 20), {
		{ "gpio_in", 0 },
		{ "gpio_out", 1 },
		{ "i2c2", 2 },
	} },
	{ SXIPIO_PIN(B, 21), {
		{ "gpio_in", 0 },
		{ "gpio_out", 1 },
		{ "i2c2", 2 },
	} },
	{ SXIPIO_PIN(B, 22), {
		{ "gpio_in", 0 },
		{ "gpio_out", 1 },
		{ "uart0", 2 },
		{ "ir1", 3 },
	} },
	{ SXIPIO_PIN(B, 23), {
		{ "gpio_in", 0 },
		{ "gpio_out", 1 },
		{ "uart0", 2 },
		{ "ir1", 3 },
	} },
	{ SXIPIO_PIN(C, 0), {
		{ "gpio_in", 0 },
		{ "gpio_out", 1 },
		{ "nand0", 2 },
		{ "spi0", 3 },
	} },
	{ SXIPIO_PIN(C, 1), {
		{ "gpio_in", 0 },
		{ "gpio_out", 1 },
		{ "nand0", 2 },
		{ "spi0", 3 },
	} },
	{ SXIPIO_PIN(C, 2), {
		{ "gpio_in", 0 },
		{ "gpio_out", 1 },
		{ "nand0", 2 },
		{ "spi0", 3 },
	} },
	{ SXIPIO_PIN(C, 3), {
		{ "gpio_in", 0 },
		{ "gpio_out", 1 },
		{ "nand0", 2 },
	} },
	{ SXIPIO_PIN(C, 4), {
		{ "gpio_in", 0 },
		{ "gpio_out", 1 },
		{ "nand0", 2 },
	} },
	{ SXIPIO_PIN(C, 5), {
		{ "gpio_in", 0 },
		{ "gpio_out", 1 },
		{ "nand0", 2 },
	} },
	{ SXIPIO_PIN(C, 6), {
		{ "gpio_in", 0 },
		{ "gpio_out", 1 },
		{ "nand0", 2 },
		{ "mmc2", 3 },
	} },
	{ SXIPIO_PIN(C, 7), {
		{ "gpio_in", 0 },
		{ "gpio_out", 1 },
		{ "nand0", 2 },
		{ "mmc2", 3 },
	} },
	{ SXIPIO_PIN(C, 8), {
		{ "gpio_in", 0 },
		{ "gpio_out", 1 },
		{ "nand0", 2 },
		{ "mmc2", 3 },
	} },
	{ SXIPIO_PIN(C, 9), {
		{ "gpio_in", 0 },
		{ "gpio_out", 1 },
		{ "nand0", 2 },
		{ "mmc2", 3 },
	} },
	{ SXIPIO_PIN(C, 10), {
		{ "gpio_in", 0 },
		{ "gpio_out", 1 },
		{ "nand0", 2 },
		{ "mmc2", 3 },
	} },
	{ SXIPIO_PIN(C, 11), {
		{ "gpio_in", 0 },
		{ "gpio_out", 1 },
		{ "nand0", 2 },
		{ "mmc2", 3 },
	} },
	{ SXIPIO_PIN(C, 12), {
		{ "gpio_in", 0 },
		{ "gpio_out", 1 },
		{ "nand0", 2 },
	} },
	{ SXIPIO_PIN(C, 13), {
		{ "gpio_in", 0 },
		{ "gpio_out", 1 },
		{ "nand0", 2 },
	} },
	{ SXIPIO_PIN(C, 14), {
		{ "gpio_in", 0 },
		{ "gpio_out", 1 },
		{ "nand0", 2 },
	} },
	{ SXIPIO_PIN(C, 15), {
		{ "gpio_in", 0 },
		{ "gpio_out", 1 },
		{ "nand0", 2 },
	} },
	{ SXIPIO_PIN(C, 16), {
		{ "gpio_in", 0 },
		{ "gpio_out", 1 },
		{ "nand0", 2 },
	} },
	{ SXIPIO_PIN(C, 17), {
		{ "gpio_in", 0 },
		{ "gpio_out", 1 },
		{ "nand0", 2 },
	} },
	{ SXIPIO_PIN(C, 18), {
		{ "gpio_in", 0 },
		{ "gpio_out", 1 },
		{ "nand0", 2 },
	} },
	{ SXIPIO_PIN(C, 19), {
		{ "gpio_in", 0 },
		{ "gpio_out", 1 },
		{ "nand0", 2 },
		{ "spi2", 3 },
	} },
	{ SXIPIO_PIN(C, 20), {
		{ "gpio_in", 0 },
		{ "gpio_out", 1 },
		{ "nand0", 2 },
		{ "spi2", 3 },
	} },
	{ SXIPIO_PIN(C, 21), {
		{ "gpio_in", 0 },
		{ "gpio_out", 1 },
		{ "nand0", 2 },
		{ "spi2", 3 },
	} },
	{ SXIPIO_PIN(C, 22), {
		{ "gpio_in", 0 },
		{ "gpio_out", 1 },
		{ "nand0", 2 },
		{ "spi2", 3 },
	} },
	{ SXIPIO_PIN(C, 23), {
		{ "gpio_in", 0 },
		{ "gpio_out", 1 },
		{ "spi0", 3 },
	} },
	{ SXIPIO_PIN(C, 24), {
		{ "gpio_in", 0 },
		{ "gpio_out", 1 },
		{ "nand0", 2 },
	} },
	{ SXIPIO_PIN(D, 0), {
		{ "gpio_in", 0 },
		{ "gpio_out", 1 },
		{ "lcd0", 2 },
		{ "lvds0", 3 },
	} },
	{ SXIPIO_PIN(D, 1), {
		{ "gpio_in", 0 },
		{ "gpio_out", 1 },
		{ "lcd0", 2 },
		{ "lvds0", 3 },
	} },
	{ SXIPIO_PIN(D, 2), {
		{ "gpio_in", 0 },
		{ "gpio_out", 1 },
		{ "lcd0", 2 },
		{ "lvds0", 3 },
	} },
	{ SXIPIO_PIN(D, 3), {
		{ "gpio_in", 0 },
		{ "gpio_out", 1 },
		{ "lcd0", 2 },
		{ "lvds0", 3 },
	} },
	{ SXIPIO_PIN(D, 4), {
		{ "gpio_in", 0 },
		{ "gpio_out", 1 },
		{ "lcd0", 2 },
		{ "lvds0", 3 },
	} },
	{ SXIPIO_PIN(D, 5), {
		{ "gpio_in", 0 },
		{ "gpio_out", 1 },
		{ "lcd0", 2 },
		{ "lvds0", 3 },
	} },
	{ SXIPIO_PIN(D, 6), {
		{ "gpio_in", 0 },
		{ "gpio_out", 1 },
		{ "lcd0", 2 },
		{ "lvds0", 3 },
	} },
	{ SXIPIO_PIN(D, 7), {
		{ "gpio_in", 0 },
		{ "gpio_out", 1 },
		{ "lcd0", 2 },
		{ "lvds0", 3 },
	} },
	{ SXIPIO_PIN(D, 8), {
		{ "gpio_in", 0 },
		{ "gpio_out", 1 },
		{ "lcd0", 2 },
		{ "lvds0", 3 },
	} },
	{ SXIPIO_PIN(D, 9), {
		{ "gpio_in", 0 },
		{ "gpio_out", 1 },
		{ "lcd0", 2 },
		{ "lvds0", 3 },
	} },
	{ SXIPIO_PIN(D, 10), {
		{ "gpio_in", 0 },
		{ "gpio_out", 1 },
		{ "lcd0", 2 },
		{ "lvds1", 3 },
	} },
	{ SXIPIO_PIN(D, 11), {
		{ "gpio_in", 0 },
		{ "gpio_out", 1 },
		{ "lcd0", 2 },
		{ "lvds1", 3 },
	} },
	{ SXIPIO_PIN(D, 12), {
		{ "gpio_in", 0 },
		{ "gpio_out", 1 },
		{ "lcd0", 2 },
		{ "lvds1", 3 },
	} },
	{ SXIPIO_PIN(D, 13), {
		{ "gpio_in", 0 },
		{ "gpio_out", 1 },
		{ "lcd0", 2 },
		{ "lvds1", 3 },
	} },
	{ SXIPIO_PIN(D, 14), {
		{ "gpio_in", 0 },
		{ "gpio_out", 1 },
		{ "lcd0", 2 },
		{ "lvds1", 3 },
	} },
	{ SXIPIO_PIN(D, 15), {
		{ "gpio_in", 0 },
		{ "gpio_out", 1 },
		{ "lcd0", 2 },
		{ "lvds1", 3 },
	} },
	{ SXIPIO_PIN(D, 16), {
		{ "gpio_in", 0 },
		{ "gpio_out", 1 },
		{ "lcd0", 2 },
		{ "lvds1", 3 },
	} },
	{ SXIPIO_PIN(D, 17), {
		{ "gpio_in", 0 },
		{ "gpio_out", 1 },
		{ "lcd0", 2 },
		{ "lvds1", 3 },
	} },
	{ SXIPIO_PIN(D, 18), {
		{ "gpio_in", 0 },
		{ "gpio_out", 1 },
		{ "lcd0", 2 },
		{ "lvds1", 3 },
	} },
	{ SXIPIO_PIN(D, 19), {
		{ "gpio_in", 0 },
		{ "gpio_out", 1 },
		{ "lcd0", 2 },
		{ "lvds1", 3 },
	} },
	{ SXIPIO_PIN(D, 20), {
		{ "gpio_in", 0 },
		{ "gpio_out", 1 },
		{ "lcd0", 2 },
		{ "csi1", 3 },
	} },
	{ SXIPIO_PIN(D, 21), {
		{ "gpio_in", 0 },
		{ "gpio_out", 1 },
		{ "lcd0", 2 },
		{ "sim", 3 },
	} },
	{ SXIPIO_PIN(D, 22), {
		{ "gpio_in", 0 },
		{ "gpio_out", 1 },
		{ "lcd0", 2 },
		{ "sim", 3 },
	} },
	{ SXIPIO_PIN(D, 23), {
		{ "gpio_in", 0 },
		{ "gpio_out", 1 },
		{ "lcd0", 2 },
		{ "sim", 3 },
	} },
	{ SXIPIO_PIN(D, 24), {
		{ "gpio_in", 0 },
		{ "gpio_out", 1 },
		{ "lcd0", 2 },
		{ "sim", 3 },
	} },
	{ SXIPIO_PIN(D, 25), {
		{ "gpio_in", 0 },
		{ "gpio_out", 1 },
		{ "lcd0", 2 },
		{ "sim", 3 },
	} },
	{ SXIPIO_PIN(D, 26), {
		{ "gpio_in", 0 },
		{ "gpio_out", 1 },
		{ "lcd0", 2 },
		{ "sim", 3 },
	} },
	{ SXIPIO_PIN(D, 27), {
		{ "gpio_in", 0 },
		{ "gpio_out", 1 },
		{ "lcd0", 2 },
		{ "sim", 3 },
	} },
	{ SXIPIO_PIN(E, 0), {
		{ "gpio_in", 0 },
		{ "gpio_out", 1 },
		{ "ts0", 2 },
		{ "csi0", 3 },
	} },
	{ SXIPIO_PIN(E, 1), {
		{ "gpio_in", 0 },
		{ "gpio_out", 1 },
		{ "ts0", 2 },
		{ "csi0", 3 },
	} },
	{ SXIPIO_PIN(E, 2), {
		{ "gpio_in", 0 },
		{ "gpio_out", 1 },
		{ "ts0", 2 },
		{ "csi0", 3 },
	} },
	{ SXIPIO_PIN(E, 3), {
		{ "gpio_in", 0 },
		{ "gpio_out", 1 },
		{ "ts0", 2 },
		{ "csi0", 3 },
	} },
	{ SXIPIO_PIN(E, 4), {
		{ "gpio_in", 0 },
		{ "gpio_out", 1 },
		{ "ts0", 2 },
		{ "csi0", 3 },
	} },
	{ SXIPIO_PIN(E, 5), {
		{ "gpio_in", 0 },
		{ "gpio_out", 1 },
		{ "ts0", 2 },
		{ "csi0", 3 },
		{ "sim", 4 },
	} },
	{ SXIPIO_PIN(E, 6), {
		{ "gpio_in", 0 },
		{ "gpio_out", 1 },
		{ "ts0", 2 },
		{ "csi0", 3 },
	} },
	{ SXIPIO_PIN(E, 7), {
		{ "gpio_in", 0 },
		{ "gpio_out", 1 },
		{ "ts0", 2 },
		{ "csi0", 3 },
	} },
	{ SXIPIO_PIN(E, 8), {
		{ "gpio_in", 0 },
		{ "gpio_out", 1 },
		{ "ts0", 2 },
		{ "csi0", 3 },
	} },
	{ SXIPIO_PIN(E, 9), {
		{ "gpio_in", 0 },
		{ "gpio_out", 1 },
		{ "ts0", 2 },
		{ "csi0", 3 },
	} },
	{ SXIPIO_PIN(E, 10), {
		{ "gpio_in", 0 },
		{ "gpio_out", 1 },
		{ "ts0", 2 },
		{ "csi0", 3 },
	} },
	{ SXIPIO_PIN(E, 11), {
		{ "gpio_in", 0 },
		{ "gpio_out", 1 },
		{ "ts0", 2 },
		{ "csi0", 3 },
	} },
	{ SXIPIO_PIN(F, 0), {
		{ "gpio_in", 0 },
		{ "gpio_out", 1 },
		{ "mmc0", 2 },
		{ "jtag", 4 },
	} },
	{ SXIPIO_PIN(F, 1), {
		{ "gpio_in", 0 },
		{ "gpio_out", 1 },
		{ "mmc0", 2 },
		{ "jtag", 4 },
	} },
	{ SXIPIO_PIN(F, 2), {
		{ "gpio_in", 0 },
		{ "gpio_out", 1 },
		{ "mmc0", 2 },
		{ "uart0", 4 },
	} },
	{ SXIPIO_PIN(F, 3), {
		{ "gpio_in", 0 },
		{ "gpio_out", 1 },
		{ "mmc0", 2 },
		{ "jtag", 4 },
	} },
	{ SXIPIO_PIN(F, 4), {
		{ "gpio_in", 0 },
		{ "gpio_out", 1 },
		{ "mmc0", 2 },
		{ "uart0", 4 },
	} },
	{ SXIPIO_PIN(F, 5), {
		{ "gpio_in", 0 },
		{ "gpio_out", 1 },
		{ "mmc0", 2 },
		{ "jtag", 4 },
	} },
	{ SXIPIO_PIN(G, 0), {
		{ "gpio_in", 0 },
		{ "gpio_out", 1 },
		{ "ts1", 2 },
		{ "csi1", 3 },
		{ "mmc1", 4 },
	} },
	{ SXIPIO_PIN(G, 1), {
		{ "gpio_in", 0 },
		{ "gpio_out", 1 },
		{ "ts1", 2 },
		{ "csi1", 3 },
		{ "mmc1", 4 },
	} },
	{ SXIPIO_PIN(G, 2), {
		{ "gpio_in", 0 },
		{ "gpio_out", 1 },
		{ "ts1", 2 },
		{ "csi1", 3 },
		{ "mmc1", 4 },
	} },
	{ SXIPIO_PIN(G, 3), {
		{ "gpio_in", 0 },
		{ "gpio_out", 1 },
		{ "ts1", 2 },
		{ "csi1", 3 },
		{ "mmc1", 4 },
	} },
	{ SXIPIO_PIN(G, 4), {
		{ "gpio_in", 0 },
		{ "gpio_out", 1 },
		{ "ts1", 2 },
		{ "csi1", 3 },
		{ "mmc1", 4 },
		{ "csi0", 5 },
	} },
	{ SXIPIO_PIN(G, 5), {
		{ "gpio_in", 0 },
		{ "gpio_out", 1 },
		{ "ts1", 2 },
		{ "csi1", 3 },
		{ "mmc1", 4 },
		{ "csi0", 5 },
	} },
	{ SXIPIO_PIN(G, 6), {
		{ "gpio_in", 0 },
		{ "gpio_out", 1 },
		{ "ts1", 2 },
		{ "csi1", 3 },
		{ "uart3", 4 },
		{ "csi0", 5 },
	} },
	{ SXIPIO_PIN(G, 7), {
		{ "gpio_in", 0 },
		{ "gpio_out", 1 },
		{ "ts1", 2 },
		{ "csi1", 3 },
		{ "uart3", 4 },
		{ "csi0", 5 },
	} },
	{ SXIPIO_PIN(G, 8), {
		{ "gpio_in", 0 },
		{ "gpio_out", 1 },
		{ "ts1", 2 },
		{ "csi1", 3 },
		{ "uart3", 4 },
		{ "csi0", 5 },
	} },
	{ SXIPIO_PIN(G, 9), {
		{ "gpio_in", 0 },
		{ "gpio_out", 1 },
		{ "ts1", 2 },
		{ "csi1", 3 },
		{ "uart3", 4 },
		{ "csi0", 5 },
	} },
	{ SXIPIO_PIN(G, 10), {
		{ "gpio_in", 0 },
		{ "gpio_out", 1 },
		{ "ts1", 2 },
		{ "csi1", 3 },
		{ "uart4", 4 },
		{ "csi0", 5 },
	} },
	{ SXIPIO_PIN(G, 11), {
		{ "gpio_in", 0 },
		{ "gpio_out", 1 },
		{ "ts1", 2 },
		{ "csi1", 3 },
		{ "uart4", 4 },
		{ "csi0", 5 },
	} },
	{ SXIPIO_PIN(H, 0), {
		{ "gpio_in", 0 },
		{ "gpio_out", 1 },
		{ "lcd1", 2 },
		{ "uart3", 4 },
		{ "irq", 6 },
		{ "csi1", 7 },
	} },
	{ SXIPIO_PIN(H, 1), {
		{ "gpio_in", 0 },
		{ "gpio_out", 1 },
		{ "lcd1", 2 },
		{ "uart3", 4 },
		{ "irq", 6 },
		{ "csi1", 7 },
	} },
	{ SXIPIO_PIN(H, 2), {
		{ "gpio_in", 0 },
		{ "gpio_out", 1 },
		{ "lcd1", 2 },
		{ "uart3", 4 },
		{ "irq", 6 },
		{ "csi1", 7 },
	} },
	{ SXIPIO_PIN(H, 3), {
		{ "gpio_in", 0 },
		{ "gpio_out", 1 },
		{ "lcd1", 2 },
		{ "uart3", 4 },
		{ "irq", 6 },
		{ "csi1", 7 },
	} },
	{ SXIPIO_PIN(H, 4), {
		{ "gpio_in", 0 },
		{ "gpio_out", 1 },
		{ "lcd1", 2 },
		{ "uart4", 4 },
		{ "irq", 6 },
		{ "csi1", 7 },
	} },
	{ SXIPIO_PIN(H, 5), {
		{ "gpio_in", 0 },
		{ "gpio_out", 1 },
		{ "lcd1", 2 },
		{ "uart4", 4 },
		{ "irq", 6 },
		{ "csi1", 7 },
	} },
	{ SXIPIO_PIN(H, 6), {
		{ "gpio_in", 0 },
		{ "gpio_out", 1 },
		{ "lcd1", 2 },
		{ "uart5", 4 },
		{ "ms", 5 },
		{ "irq", 6 },
		{ "csi1", 7 },
	} },
	{ SXIPIO_PIN(H, 7), {
		{ "gpio_in", 0 },
		{ "gpio_out", 1 },
		{ "lcd1", 2 },
		{ "uart5", 4 },
		{ "ms", 5 },
		{ "irq", 6 },
		{ "csi1", 7 },
	} },
	{ SXIPIO_PIN(H, 8), {
		{ "gpio_in", 0 },
		{ "gpio_out", 1 },
		{ "lcd1", 2 },
		{ "emac", 3 },
		{ "keypad", 4 },
		{ "ms", 5 },
		{ "irq", 6 },
		{ "csi1", 7 },
	} },
	{ SXIPIO_PIN(H, 9), {
		{ "gpio_in", 0 },
		{ "gpio_out", 1 },
		{ "lcd1", 2 },
		{ "emac", 3 },
		{ "keypad", 4 },
		{ "ms", 5 },
		{ "irq", 6 },
		{ "csi1", 7 },
	} },
	{ SXIPIO_PIN(H, 10), {
		{ "gpio_in", 0 },
		{ "gpio_out", 1 },
		{ "lcd1", 2 },
		{ "emac", 3 },
		{ "keypad", 4 },
		{ "ms", 5 },
		{ "irq", 6 },
		{ "csi1", 7 },
	} },
	{ SXIPIO_PIN(H, 11), {
		{ "gpio_in", 0 },
		{ "gpio_out", 1 },
		{ "lcd1", 2 },
		{ "emac", 3 },
		{ "keypad", 4 },
		{ "ms", 5 },
		{ "irq", 6 },
		{ "csi1", 7 },
	} },
	{ SXIPIO_PIN(H, 12), {
		{ "gpio_in", 0 },
		{ "gpio_out", 1 },
		{ "lcd1", 2 },
		{ "ps2", 4 },
		{ "irq", 6 },
		{ "csi1", 7 },
	} },
	{ SXIPIO_PIN(H, 13), {
		{ "gpio_in", 0 },
		{ "gpio_out", 1 },
		{ "lcd1", 2 },
		{ "ps2", 4 },
		{ "sim", 5 },
		{ "irq", 6 },
		{ "csi1", 7 },
	} },
	{ SXIPIO_PIN(H, 14), {
		{ "gpio_in", 0 },
		{ "gpio_out", 1 },
		{ "lcd1", 2 },
		{ "emac", 3 },
		{ "keypad", 4 },
		{ "sim", 5 },
		{ "irq", 6 },
		{ "csi1", 7 },
	} },
	{ SXIPIO_PIN(H, 15), {
		{ "gpio_in", 0 },
		{ "gpio_out", 1 },
		{ "lcd1", 2 },
		{ "emac", 3 },
		{ "keypad", 4 },
		{ "sim", 5 },
		{ "irq", 6 },
		{ "csi1", 7 },
	} },
	{ SXIPIO_PIN(H, 16), {
		{ "gpio_in", 0 },
		{ "gpio_out", 1 },
		{ "lcd1", 2 },
		{ "emac", 3 },
		{ "keypad", 4 },
		{ "irq", 6 },
		{ "csi1", 7 },
	} },
	{ SXIPIO_PIN(H, 17), {
		{ "gpio_in", 0 },
		{ "gpio_out", 1 },
		{ "lcd1", 2 },
		{ "emac", 3 },
		{ "keypad", 4 },
		{ "sim", 5 },
		{ "irq", 6 },
		{ "csi1", 7 },
	} },
	{ SXIPIO_PIN(H, 18), {
		{ "gpio_in", 0 },
		{ "gpio_out", 1 },
		{ "lcd1", 2 },
		{ "emac", 3 },
		{ "keypad", 4 },
		{ "sim", 5 },
		{ "irq", 6 },
		{ "csi1", 7 },
	} },
	{ SXIPIO_PIN(H, 19), {
		{ "gpio_in", 0 },
		{ "gpio_out", 1 },
		{ "lcd1", 2 },
		{ "emac", 3 },
		{ "keypad", 4 },
		{ "sim", 5 },
		{ "irq", 6 },
		{ "csi1", 7 },
	} },
	{ SXIPIO_PIN(H, 20), {
		{ "gpio_in", 0 },
		{ "gpio_out", 1 },
		{ "lcd1", 2 },
		{ "emac", 3 },
		{ "can", 4 },
		{ "irq", 6 },
		{ "csi1", 7 },
	} },
	{ SXIPIO_PIN(H, 21), {
		{ "gpio_in", 0 },
		{ "gpio_out", 1 },
		{ "lcd1", 2 },
		{ "emac", 3 },
		{ "can", 4 },
		{ "irq", 6 },
		{ "csi1", 7 },
	} },
	{ SXIPIO_PIN(H, 22), {
		{ "gpio_in", 0 },
		{ "gpio_out", 1 },
		{ "lcd1", 2 },
		{ "emac", 3 },
		{ "keypad", 4 },
		{ "mmc1", 5 },
		{ "csi1", 7 },
	} },
	{ SXIPIO_PIN(H, 23), {
		{ "gpio_in", 0 },
		{ "gpio_out", 1 },
		{ "lcd1", 2 },
		{ "emac", 3 },
		{ "keypad", 4 },
		{ "mmc1", 5 },
		{ "csi1", 7 },
	} },
	{ SXIPIO_PIN(H, 24), {
		{ "gpio_in", 0 },
		{ "gpio_out", 1 },
		{ "lcd1", 2 },
		{ "emac", 3 },
		{ "keypad", 4 },
		{ "mmc1", 5 },
		{ "csi1", 7 },
	} },
	{ SXIPIO_PIN(H, 25), {
		{ "gpio_in", 0 },
		{ "gpio_out", 1 },
		{ "lcd1", 2 },
		{ "emac", 3 },
		{ "keypad", 4 },
		{ "mmc1", 5 },
		{ "csi1", 7 },
	} },
	{ SXIPIO_PIN(H, 26), {
		{ "gpio_in", 0 },
		{ "gpio_out", 1 },
		{ "lcd1", 2 },
		{ "emac", 3 },
		{ "keypad", 4 },
		{ "mmc1", 5 },
		{ "csi1", 7 },
	} },
	{ SXIPIO_PIN(H, 27), {
		{ "gpio_in", 0 },
		{ "gpio_out", 1 },
		{ "lcd1", 2 },
		{ "emac", 3 },
		{ "keypad", 4 },
		{ "mmc1", 5 },
		{ "csi1", 7 },
	} },
	{ SXIPIO_PIN(I, 0), {
		{ "gpio_in", 0 },
		{ "gpio_out", 1 },
		{ "i2c3", 3 },
	} },
	{ SXIPIO_PIN(I, 1), {
		{ "gpio_in", 0 },
		{ "gpio_out", 1 },
		{ "i2c3", 3 },
	} },
	{ SXIPIO_PIN(I, 2), {
		{ "gpio_in", 0 },
		{ "gpio_out", 1 },
		{ "i2c4", 3 },
	} },
	{ SXIPIO_PIN(I, 3), {
		{ "gpio_in", 0 },
		{ "gpio_out", 1 },
		{ "pwm", 2 },
		{ "i2c4", 3 },
	} },
	{ SXIPIO_PIN(I, 4), {
		{ "gpio_in", 0 },
		{ "gpio_out", 1 },
		{ "mmc3", 2 },
	} },
	{ SXIPIO_PIN(I, 5), {
		{ "gpio_in", 0 },
		{ "gpio_out", 1 },
		{ "mmc3", 2 },
	} },
	{ SXIPIO_PIN(I, 6), {
		{ "gpio_in", 0 },
		{ "gpio_out", 1 },
		{ "mmc3", 2 },
	} },
	{ SXIPIO_PIN(I, 7), {
		{ "gpio_in", 0 },
		{ "gpio_out", 1 },
		{ "mmc3", 2 },
	} },
	{ SXIPIO_PIN(I, 8), {
		{ "gpio_in", 0 },
		{ "gpio_out", 1 },
		{ "mmc3", 2 },
	} },
	{ SXIPIO_PIN(I, 9), {
		{ "gpio_in", 0 },
		{ "gpio_out", 1 },
		{ "mmc3", 2 },
	} },
	{ SXIPIO_PIN(I, 10), {
		{ "gpio_in", 0 },
		{ "gpio_out", 1 },
		{ "spi0", 2 },
		{ "uart5", 3 },
		{ "irq", 6 },
	} },
	{ SXIPIO_PIN(I, 11), {
		{ "gpio_in", 0 },
		{ "gpio_out", 1 },
		{ "spi0", 2 },
		{ "uart5", 3 },
		{ "irq", 6 },
	} },
	{ SXIPIO_PIN(I, 12), {
		{ "gpio_in", 0 },
		{ "gpio_out", 1 },
		{ "spi0", 2 },
		{ "uart6", 3 },
		{ "clk_out_a", 4 },
		{ "irq", 6 },
	} },
	{ SXIPIO_PIN(I, 13), {
		{ "gpio_in", 0 },
		{ "gpio_out", 1 },
		{ "spi0", 2 },
		{ "uart6", 3 },
		{ "clk_out_b", 4 },
		{ "irq", 6 },
	} },
	{ SXIPIO_PIN(I, 14), {
		{ "gpio_in", 0 },
		{ "gpio_out", 1 },
		{ "spi0", 2 },
		{ "ps2", 3 },
		{ "timer4", 4 },
		{ "irq", 6 },
	} },
	{ SXIPIO_PIN(I, 15), {
		{ "gpio_in", 0 },
		{ "gpio_out", 1 },
		{ "spi1", 2 },
		{ "ps2", 3 },
		{ "timer5", 4 },
		{ "irq", 6 },
	} },
	{ SXIPIO_PIN(I, 16), {
		{ "gpio_in", 0 },
		{ "gpio_out", 1 },
		{ "spi1", 2 },
		{ "uart2", 3 },
		{ "irq", 6 },
	} },
	{ SXIPIO_PIN(I, 17), {
		{ "gpio_in", 0 },
		{ "gpio_out", 1 },
		{ "spi1", 2 },
		{ "uart2", 3 },
		{ "irq", 6 },
	} },
	{ SXIPIO_PIN(I, 18), {
		{ "gpio_in", 0 },
		{ "gpio_out", 1 },
		{ "spi1", 2 },
		{ "uart2", 3 },
		{ "irq", 6 },
	} },
	{ SXIPIO_PIN(I, 19), {
		{ "gpio_in", 0 },
		{ "gpio_out", 1 },
		{ "spi1", 2 },
		{ "uart2", 3 },
		{ "irq", 6 },
	} },
	{ SXIPIO_PIN(I, 20), {
		{ "gpio_in", 0 },
		{ "gpio_out", 1 },
		{ "ps2", 2 },
		{ "uart7", 3 },
		{ "hdmi", 4 },
	} },
	{ SXIPIO_PIN(I, 21), {
		{ "gpio_in", 0 },
		{ "gpio_out", 1 },
		{ "ps2", 2 },
		{ "uart7", 3 },
		{ "hdmi", 4 },
	} },
};
