#	$OpenBSD: Makefile,v 1.2 1997/09/18 17:18:40 deraadt Exp $
#	$NetBSD: Makefile,v 1.2 1995/10/12 21:16:53 gwr Exp $

# at this point only the floppies directory has object, ramdisk and
# miniroot are just architeture dependent inclusions for ../ramdisk, etc.
SUBDIR=	floppies
SUBDIR+= ../ramdisk ../miniroot

.include <bsd.subdir.mk>
