#!/bin/sh -
#	$OpenBSD: monthly,v 1.5 1998/02/02 23:08:57 millert Exp $

if [ -f /etc/monthly.local ];then
	echo ""
	echo "Running monthly.local:"
	. /etc/monthly.local
else
	echo "Nothing to do!"
fi

# echo ""
# echo "Doing login accounting:"
# ac -p | sort -nr +1

#echo "."
