#	$OpenBSD: Makefile,v 1.11 2011/11/29 04:38:37 kurt Exp $

SUBDIR+= elf hidden weak dlsym dlopen dlclose lazy
#SUBDIR+= constructor 
SUBDIR+= link-order edgecases initfirst

install:

.include <bsd.subdir.mk>
