#	$OpenBSD: Makefile,v 1.16 2016/03/20 05:13:22 guenther Exp $

SUBDIR+= elf hidden weak dlsym dlopen dlclose lazy
#SUBDIR+= constructor 
SUBDIR+= link-order edgecases initfirst
SUBDIR+= df_1_noopen randomdata subst dependencies
SUBDIR+= init-env

install:

.include <bsd.subdir.mk>
