#	$OpenBSD: Makefile,v 1.7 2015/10/25 21:23:42 jca Exp $

PROG=	rtadvd
SRCS=	rtadvd.c rrenum.c advcap.c if.c config.c timer.c dump.c log.c

CFLAGS+=-Wall
MAN=	rtadvd.8 rtadvd.conf.5

.include <bsd.prog.mk>
