# !!!!!!!   DO NOT EDIT THIS FILE   !!!!!!!
# This file is machine-generated by lib/unicore/mktables from the Unicode
# database, Version 5.2.0.  Any changes made here will be lost!

# !!!!!!!   INTERNAL PERL USE ONLY   !!!!!!!
# This file is for internal use by the Perl program only.  The format and even
# the name or existence of this file are subject to change without notice.
# Don't use it directly.

# This file returns the 1064 code points in Unicode Version 5.2.0 that match
# any of the following regular expression constructs:
# 
#         \p{General_Category=Number}
#         \p{Gc=N}
#         \p{Category=Number}
#         \p{Is_General_Category=N}
#         \p{Is_Gc=Number}
#         \p{Is_Category=N}
# 
#         \p{Number}
#         \p{Is_Number}
#         \p{N}
#         \p{Is_N}
# 
# perluniprops.pod should be consulted for the syntax rules for any of these,
# including if adding or subtracting white space, underscore, and hyphen
# characters matters or doesn't matter, and other permissible syntactic
# variants.  Upper/lower case distinctions never matter.
# 
# A colon can be substituted for the equals sign, and anything to the left of
# the equals (or colon) can be combined with anything to the right.  Thus,
# for example,
#         \p{Is_Category: Number}
# is also valid.
# 
# The format of the lines of this file is: START\tSTOP\twhere START is the
# starting code point of the range, in hex; STOP is the ending point, or if
# omitted, the range has just one code point.  Numbers in comments in
# [brackets] indicate how many code points are in the range.

return <<'END';
0030	0039	 # [10]
00B2	00B3	 # [2]
00B9		
00BC	00BE	 # [3]
0660	0669	 # [10]
06F0	06F9	 # [10]
07C0	07C9	 # [10]
0966	096F	 # [10]
09E6	09EF	 # [10]
09F4	09F9	 # [6]
0A66	0A6F	 # [10]
0AE6	0AEF	 # [10]
0B66	0B6F	 # [10]
0BE6	0BF2	 # [13]
0C66	0C6F	 # [10]
0C78	0C7E	 # [7]
0CE6	0CEF	 # [10]
0D66	0D75	 # [16]
0E50	0E59	 # [10]
0ED0	0ED9	 # [10]
0F20	0F33	 # [20]
1040	1049	 # [10]
1090	1099	 # [10]
1369	137C	 # [20]
16EE	16F0	 # [3]
17E0	17E9	 # [10]
17F0	17F9	 # [10]
1810	1819	 # [10]
1946	194F	 # [10]
19D0	19DA	 # [11]
1A80	1A89	 # [10]
1A90	1A99	 # [10]
1B50	1B59	 # [10]
1BB0	1BB9	 # [10]
1C40	1C49	 # [10]
1C50	1C59	 # [10]
2070		
2074	2079	 # [6]
2080	2089	 # [10]
2150	2182	 # [51]
2185	2189	 # [5]
2460	249B	 # [60]
24EA	24FF	 # [22]
2776	2793	 # [30]
2CFD		
3007		
3021	3029	 # [9]
3038	303A	 # [3]
3192	3195	 # [4]
3220	3229	 # [10]
3251	325F	 # [15]
3280	3289	 # [10]
32B1	32BF	 # [15]
A620	A629	 # [10]
A6E6	A6EF	 # [10]
A830	A835	 # [6]
A8D0	A8D9	 # [10]
A900	A909	 # [10]
A9D0	A9D9	 # [10]
AA50	AA59	 # [10]
ABF0	ABF9	 # [10]
FF10	FF19	 # [10]
10107	10133	 # [45]
10140	10178	 # [57]
1018A		
10320	10323	 # [4]
10341		
1034A		
103D1	103D5	 # [5]
104A0	104A9	 # [10]
10858	1085F	 # [8]
10916	1091B	 # [6]
10A40	10A47	 # [8]
10A7D	10A7E	 # [2]
10B58	10B5F	 # [8]
10B78	10B7F	 # [8]
10E60	10E7E	 # [31]
12400	12462	 # [99]
1D360	1D371	 # [18]
1D7CE	1D7FF	 # [50]
1F100	1F10A	 # [11]
END
