# !!!!!!!   DO NOT EDIT THIS FILE   !!!!!!!
# This file is machine-generated by lib/unicore/mktables from the Unicode
# database, Version 6.1.0.  Any changes made here will be lost!

# !!!!!!!   INTERNAL PERL USE ONLY   !!!!!!!
# This file is for internal use by core Perl only.  The format and even the
# name or existence of this file are subject to change without notice.  Don't
# use it directly.


return <<'END';
00B2	00B3
00B9		
00BC	00BE
09F4	09F9
0B72	0B77
0BF0	0BF2
0C78	0C7E
0D70	0D75
0F2A	0F33
1369	137C
17F0	17F9
19DA		
2070		
2074	2079
2080	2089
2150	215F
2189		
2460	249B
24EA	24FF
2776	2793
2CFD		
3192	3195
3220	3229
3248	324F
3251	325F
3280	3289
32B1	32BF
A830	A835
10107	10133
10175	10178
1018A		
10320	10323
10858	1085F
10916	1091B
10A40	10A47
10A7D	10A7E
10B58	10B5F
10B78	10B7F
10E60	10E7E
11052	11065
1D360	1D371
1F100	1F10A
END
