# !!!!!!!   DO NOT EDIT THIS FILE   !!!!!!!
# This file is machine-generated by lib/unicore/mktables from the Unicode
# database, Version 5.2.0.  Any changes made here will be lost!

# !!!!!!!   INTERNAL PERL USE ONLY   !!!!!!!
# This file is for internal use by the Perl program only.  The format and even
# the name or existence of this file are subject to change without notice.
# Don't use it directly.

# This file returns the 4499 code points in Unicode Version 5.2.0 that match
# any of the following regular expression constructs:
# 
#         \p{General_Category=Symbol}
#         \p{Gc=S}
#         \p{Category=Symbol}
#         \p{Is_General_Category=S}
#         \p{Is_Gc=Symbol}
#         \p{Is_Category=S}
# 
#         \p{Symbol}
#         \p{Is_Symbol}
#         \p{S}
#         \p{Is_S}
# 
# perluniprops.pod should be consulted for the syntax rules for any of these,
# including if adding or subtracting white space, underscore, and hyphen
# characters matters or doesn't matter, and other permissible syntactic
# variants.  Upper/lower case distinctions never matter.
# 
# A colon can be substituted for the equals sign, and anything to the left of
# the equals (or colon) can be combined with anything to the right.  Thus,
# for example,
#         \p{Is_Category: Symbol}
# is also valid.
# 
# The format of the lines of this file is: START\tSTOP\twhere START is the
# starting code point of the range, in hex; STOP is the ending point, or if
# omitted, the range has just one code point.  Numbers in comments in
# [brackets] indicate how many code points are in the range.

return <<'END';
0024		
002B		
003C	003E	 # [3]
005E		
0060		
007C		
007E		
00A2	00A9	 # [8]
00AC		
00AE	00B1	 # [4]
00B4		
00B6		
00B8		
00D7		
00F7		
02C2	02C5	 # [4]
02D2	02DF	 # [14]
02E5	02EB	 # [7]
02ED		
02EF	02FF	 # [17]
0375		
0384	0385	 # [2]
03F6		
0482		
0606	0608	 # [3]
060B		
060E	060F	 # [2]
06E9		
06FD	06FE	 # [2]
07F6		
09F2	09F3	 # [2]
09FA	09FB	 # [2]
0AF1		
0B70		
0BF3	0BFA	 # [8]
0C7F		
0CF1	0CF2	 # [2]
0D79		
0E3F		
0F01	0F03	 # [3]
0F13	0F17	 # [5]
0F1A	0F1F	 # [6]
0F34		
0F36		
0F38		
0FBE	0FC5	 # [8]
0FC7	0FCC	 # [6]
0FCE	0FCF	 # [2]
0FD5	0FD8	 # [4]
109E	109F	 # [2]
1360		
1390	1399	 # [10]
17DB		
1940		
19E0	19FF	 # [32]
1B61	1B6A	 # [10]
1B74	1B7C	 # [9]
1FBD		
1FBF	1FC1	 # [3]
1FCD	1FCF	 # [3]
1FDD	1FDF	 # [3]
1FED	1FEF	 # [3]
1FFD	1FFE	 # [2]
2044		
2052		
207A	207C	 # [3]
208A	208C	 # [3]
20A0	20B8	 # [25]
2100	2101	 # [2]
2103	2106	 # [4]
2108	2109	 # [2]
2114		
2116	2118	 # [3]
211E	2123	 # [6]
2125		
2127		
2129		
212E		
213A	213B	 # [2]
2140	2144	 # [5]
214A	214D	 # [4]
214F		
2190	2328	 # [409]
232B	23E8	 # [190]
2400	2426	 # [39]
2440	244A	 # [11]
249C	24E9	 # [78]
2500	26CD	 # [462]
26CF	26E1	 # [19]
26E3		
26E8	26FF	 # [24]
2701	2704	 # [4]
2706	2709	 # [4]
270C	2727	 # [28]
2729	274B	 # [35]
274D		
274F	2752	 # [4]
2756	275E	 # [9]
2761	2767	 # [7]
2794		
2798	27AF	 # [24]
27B1	27BE	 # [14]
27C0	27C4	 # [5]
27C7	27CA	 # [4]
27CC		
27D0	27E5	 # [22]
27F0	2982	 # [403]
2999	29D7	 # [63]
29DC	29FB	 # [32]
29FE	2B4C	 # [335]
2B50	2B59	 # [10]
2CE5	2CEA	 # [6]
2E80	2E99	 # [26]
2E9B	2EF3	 # [89]
2F00	2FD5	 # [214]
2FF0	2FFB	 # [12]
3004		
3012	3013	 # [2]
3020		
3036	3037	 # [2]
303E	303F	 # [2]
309B	309C	 # [2]
3190	3191	 # [2]
3196	319F	 # [10]
31C0	31E3	 # [36]
3200	321E	 # [31]
322A	3250	 # [39]
3260	327F	 # [32]
328A	32B0	 # [39]
32C0	32FE	 # [63]
3300	33FF	 # [256]
4DC0	4DFF	 # [64]
A490	A4C6	 # [55]
A700	A716	 # [23]
A720	A721	 # [2]
A789	A78A	 # [2]
A828	A82B	 # [4]
A836	A839	 # [4]
AA77	AA79	 # [3]
FB29		
FDFC	FDFD	 # [2]
FE62		
FE64	FE66	 # [3]
FE69		
FF04		
FF0B		
FF1C	FF1E	 # [3]
FF3E		
FF40		
FF5C		
FF5E		
FFE0	FFE6	 # [7]
FFE8	FFEE	 # [7]
FFFC	FFFD	 # [2]
10102		
10137	1013F	 # [9]
10179	10189	 # [17]
10190	1019B	 # [12]
101D0	101FC	 # [45]
1D000	1D0F5	 # [246]
1D100	1D126	 # [39]
1D129	1D164	 # [60]
1D16A	1D16C	 # [3]
1D183	1D184	 # [2]
1D18C	1D1A9	 # [30]
1D1AE	1D1DD	 # [48]
1D200	1D241	 # [66]
1D245		
1D300	1D356	 # [87]
1D6C1		
1D6DB		
1D6FB		
1D715		
1D735		
1D74F		
1D76F		
1D789		
1D7A9		
1D7C3		
1F000	1F02B	 # [44]
1F030	1F093	 # [100]
1F110	1F12E	 # [31]
1F131		
1F13D		
1F13F		
1F142		
1F146		
1F14A	1F14E	 # [5]
1F157		
1F15F		
1F179		
1F17B	1F17C	 # [2]
1F17F		
1F18A	1F18D	 # [4]
1F190		
1F200		
1F210	1F231	 # [34]
1F240	1F248	 # [9]
END
