# !!!!!!!   DO NOT EDIT THIS FILE   !!!!!!!
# This file is machine-generated by lib/unicore/mktables from the Unicode
# database, Version 6.2.0.  Any changes made here will be lost!

# !!!!!!!   INTERNAL PERL USE ONLY   !!!!!!!
# This file is for internal use by core Perl only.  The format and even the
# name or existence of this file are subject to change without notice.  Don't
# use it directly.


return <<'END';
005E		
0060		
00A8		
00AF		
00B4		
00B8		
02C2	02C5
02D2	02DF
02E5	02EB
02ED		
02EF	02FF
0375		
0384	0385
1FBD		
1FBF	1FC1
1FCD	1FCF
1FDD	1FDF
1FED	1FEF
1FFD	1FFE
309B	309C
A700	A716
A720	A721
A789	A78A
FBB2	FBC1
FF3E		
FF40		
FFE3		
END
