.\"	$OpenBSD: asc.4,v 1.1 2002/09/30 18:09:48 miod Exp $
.\"
.\" Copyright (c) 1998 The OpenBSD Project
.\" All rights reserved.
.\"
.\"
.Dd March 4, 1998
.Dt ASC 4 alpha
.Os
.Sh NAME
.Nm asc
.Nd NCR 53c[f]94 on-board or TURBOchannel SCSI controller
.Sh SYNOPSIS
.Cd "tcds* at tc? slot ? offset ?" Pq " TURBOchannel PMAZ cards"
.Cd "asc* at tcds? chip ?"
.Cd "asc* at tc? slot ? offset ?" Pq "on-board SCSI"
.Cd "scsibus* at asc?"
.Sh DESCRIPTION
The
.Nm
is an on-board or TURBOchannel SCSI controller based on the
NCR 53c[f]94 chips, found on DEC 3000/[3456789]00 series Alpha workstations.
.Sh SEE ALSO
.Xr cd 4 ,
.Xr ch 4 ,
.Xr intro 4,
.Xr scsi 4 ,
.Xr sd 4 ,
.Xr ss 4 ,
.Xr st 4 ,
.Xr uk 4
