.\"     $OpenBSD: intro.4,v 1.1 1998/03/08 00:09:39 johns Exp $
.\"
.\" Copyright (c) 1998 The OpenBSD Project
.\" All Rights Reserved.
.\"
.Dd March 7, 1998
.Dt INTRO 4 alpha
.Os
.Sh NAME
.Nm intro
.Nd introduction to special files and hardware support
.Sh DESCRIPTION
This section describes the special files, related driver functions,
and networking support
available in the system.
In this part of the manual, the
.Tn SYNOPSIS
section of
each configurable device gives a sample specification
for use in constructing a system description for the
.Xr config 8
program.
The
.Tn DIAGNOSTICS
section lists messages which may appear on the console
and/or in the system error log
.Pa /var/log/messages
due to errors in device operation;
see
.Xr syslogd 8
for more information.
.Pp
This section contains both devices
which may be configured into the system
and network related information.
The networking support is introduced in
.Xr netintro 4 .
.Sh DEVICE SUPPORT
This section describes the hardware supported on the Alpha
platform.
Software support for these devices comes in two forms.  A hardware
device may be supported with a character or block
.Em device driver ,
or it may be used within the networking subsystem and have a
.Em network interface driver .
Block and character devices are accessed through files in the file
system of a special type; see
.Xr mknod 8 .
Network interfaces are indirectly accessed through the interprocess
communication facilities provided by the system; see
.Xr socket 2 .
.Pp
A hardware device is identified to the system at configuration time
and the appropriate device or network interface driver is then compiled
into the system.  When the resultant system is booted, the
autoconfiguration facilities in the system probe for the device
and, if found, enable the software support for it.
If a device does not respond at autoconfiguration
time it is not accessible at any time afterwards.
To enable a device which did not autoconfigure,
the system must be rebooted.
.Pp
The autoconfiguration system is described in
.Xr autoconf 4 .
A list of the supported devices is given below.
.Sh SEE ALSO
.Xr cd 4 ,
.Xr sd 4 ,
.Xr ss 4 ,
.Xr st 4 ,
.Xr autoconf 4 ,
.Xr config 8 .
.Sh SUPPORTED SYSTEMS
The following Alpha system architectures and models are supported:
.Bl -tag -width speaker
.It DEC 3000/[3456789]00 series Alpha systems.
.It AlphaStation 200/250/255/400/500 and AXPpci systems.
.El
.Pp
The DECpc AXP 150 systems (EISA-bus PC-like systems), 
Alpha "server" systems (other than perhaps the AlphaServer 400, which
might actually be an AlphaStation 400 in disguise), and multiprocessor
Alpha systems are not supported.
.Sh HISTORY
The
Alpha
.Nm 
first appeared with OpenBSD 2.3.
