#	$OpenBSD: Makefile,v 1.14 2003/03/06 22:42:30 mickey Exp $

MAN=	apecs.4 asc.4 autoconf.4 cia.4 intro.4 irongate.4 \
	lca.4 le.4 mem.4 scc.4 tcasic.4 tga.4 tsc.4 tsp.4
MLINKS=	mem.4 kmem.4
MANSUBDIR=alpha

.include <bsd.prog.mk>
