#!/bin/sh
# $Id: discon-tar2,v 1.1 2000/09/11 14:41:29 art Exp $
if test "X$FAST" != "X" ; then echo "Not running $0" ;  exit 0 ; fi
FS=${FS:-${objdir}/../appl/fs/fs}
TARBOLL=$AFSROOT/stacken.kth.se/ftp/pub/gnu/emacs/emacs-20.5a.tar.gz
file $TARBOLL >&4 || exit 1
mkdir one || exit 1
(cd one && gzip -dc $TARBOLL | tar xvf - >&4 || exit 1)
${FS} conn disconn
mkdir two || exit 1
(cd two && gzip -dc $TARBOLL | tar xvf - >&4 || exit 1)
${FS} conn conn
diff -r one two >/dev/null || exit 1
