# !!!!!!!   DO NOT EDIT THIS FILE   !!!!!!!
# This file is machine-generated by lib/unicore/mktables from the Unicode
# database, Version 6.1.0.  Any changes made here will be lost!

# !!!!!!!   INTERNAL PERL USE ONLY   !!!!!!!
# This file is for internal use by core Perl only.  The format and even the
# name or existence of this file are subject to change without notice.  Don't
# use it directly.


return <<'END';
0061		
0066		
0068	006A
0073	0074
0077		
0079		
02BC		
0308		
0313		
0342		
03AC		
03AE		
03B1		
03B7		
03B9		
03C1		
03C5		
03C9		
03CE		
0565		
0574		
057E		
1F00	1F07
1F20	1F27
1F60	1F67
1F70		
1F74		
1F7C		
END
