#	$OpenBSD: Makefile,v 1.1 1996/04/22 01:27:21 deraadt Exp $
#	from: @(#)Makefile	5.1 (Berkeley) 2/12/91

MAN=	intro.4 asc.4 autoconf.4 beep.4 com.4
MAN+=	csc.4 ea.4 eb.4 kbd.4 lpt.4 mainbus.4 mem.4
MAN+=	podulebus.4 quadmouse.4 rd.4 wd.4

MLINKS=	mem.4 kmem.4
MANSUBDIR=/arm32

.include <bsd.prog.mk>
