.\"	$OpenBSD: mount_tcfs.8,v 1.9 2002/12/11 12:24:28 henning Exp $
.\"
.\" Copyright (c) 1980, 1989, 1991, 1993
.\"	The Regents of the University of California.  All rights reserved.
.\"
.\" Redistribution and use in source and binary forms, with or without
.\" modification, are permitted provided that the following conditions
.\" are met:
.\" 1. Redistributions of source code must retain the above copyright
.\"    notice, this list of conditions and the following disclaimer.
.\" 2. Redistributions in binary form must reproduce the above copyright
.\"    notice, this list of conditions and the following disclaimer in the
.\"    documentation and/or other materials provided with the distribution.
.\" 3. All advertising materials mentioning features or use of this software
.\"    must display the following acknowledgement:
.\"	This product includes software developed by the University of
.\"	California, Berkeley and its contributors.
.\" 4. Neither the name of the University nor the names of its contributors
.\"    may be used to endorse or promote products derived from this software
.\"    without specific prior written permission.
.\"
.\" THIS SOFTWARE IS PROVIDED BY THE REGENTS AND CONTRIBUTORS ``AS IS'' AND
.\" ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE
.\" IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE
.\" ARE DISCLAIMED.  IN NO EVENT SHALL THE REGENTS OR CONTRIBUTORS BE LIABLE
.\" FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL
.\" DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS
.\" OR SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION)
.\" HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT
.\" LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY
.\" OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF
.\" SUCH DAMAGE.
.\"
.Dd Nov 3, 1999
.Dt MOUNT_TCFS 8
.Os
.Sh NAME
.Nm mount_tcfs
.Nd mount a tcfs filesystem sub-tree
.Sh SYNOPSIS
.Nm mount_tcfs
.Op Fl o Ar options
.Ar path node
.Sh DESCRIPTION
The
.Nm
command creates a Transparent Cryptographic File System (TCFS) layer, mapping
a sub-tree of the file system name space (path) into another part of the
global file system (node) where some cryptographic features are provided.
.Pp
Access to objects existing on the new file system can be allowed only to
users who own a proper key.
.Sh EXAMPLES
The command
.Bd -literal -offset indent
# mount_tcfs -o cipher=2 /mnt2 /mnt/tcfs
.Ed
.Pp
mount the ffs filesystem
.Ar /mnt2
on mountpoint
.Ar /mnt/tcfs
as TCFS file system using cipher 2.
.Sh SEE ALSO
.Xr mount 2 ,
.Xr fstab 5 ,
.Xr mount 8 ,
.Xr umount 8
.Sh HISTORY
A
.Nm
command appeared in
.Ox 2.7 .
.Sh BUGS
This is a preliminary version, only for developers.
Any other use is discouraged.
.Pp
Sorry, no docs.
