.\" $OpenBSD: skeyinfo.1,v 1.5 2001/06/19 01:49:45 millert Exp $
.\"
.Dd 17 June 2001
.Dt SKEYINFO 1
.Os
.Sh NAME
.Nm skeyinfo
.Nd obtain the next S/Key challenge for a user
.Sh SYNOPSIS
.Nm skeyinfo
.Op Fl a Ar auth-type
.Op Fl v
.Op Ar user
.Sh DESCRIPTION
.Nm
prints out the next S/Key challenge for the specified user or for the
current user if no user is specified.
.Pp
The options are as follows:
.Bl -tag -width auth-typeXXXX
.It Fl a Ar auth-type
Specify an authentication type instead of the default
.Dq skey .
This can be used to get a challenge for a challenge/response authentication
mechanism other than S/Key, or if a remote S/Key server is in use.
Note that this will cause an error if the selected type
does not support challenge/response style authentication.
.It Fl v
Print the hash algorithm as well.
.El
.Sh EXAMPLES
% skey -n <number of passwords to print> `skeyinfo` | lpr
.Pp
This would print out a list of S/Key passwords for use over
an untrusted network (perhaps for use at a conference).
.Sh SEE ALSO
.Xr skey 1 ,
.Xr skeyinit 1
.Sh CAVEATS
If the user does not have an entry in the S/Key database a fake
challenge will be printed.
