.\"	$OpenBSD: iec.4,v 1.3 2009/11/03 18:52:41 miod Exp $
.\"
.\" Copyright (c) 2009 Miodrag Vallat.
.\"
.\" Permission to use, copy, modify, and distribute this software for any
.\" purpose with or without fee is hereby granted, provided that the above
.\" copyright notice and this permission notice appear in all copies.
.\"
.\" THE SOFTWARE IS PROVIDED "AS IS" AND THE AUTHOR DISCLAIMS ALL WARRANTIES
.\" WITH REGARD TO THIS SOFTWARE INCLUDING ALL IMPLIED WARRANTIES OF
.\" MERCHANTABILITY AND FITNESS. IN NO EVENT SHALL THE AUTHOR BE LIABLE FOR
.\" ANY SPECIAL, DIRECT, INDIRECT, OR CONSEQUENTIAL DAMAGES OR ANY DAMAGES
.\" WHATSOEVER RESULTING FROM LOSS OF USE, DATA OR PROFITS, WHETHER IN AN
.\" ACTION OF CONTRACT, NEGLIGENCE OR OTHER TORTIOUS ACTION, ARISING OUT OF
.\" OR IN CONNECTION WITH THE USE OR PERFORMANCE OF THIS SOFTWARE.
.\"
.Dd $Mdocdate: November 3 2009 $
.Dt IEC 4 sgi
.Os
.Sh NAME
.Nm iec
.Nd IOC3 Ethernet interface
.Sh SYNOPSIS
.Cd "iec* at ioc?"
.Cd "icsphy* at mii?"
.Cd "nsphy* at mii?"
.Cd "nsphyter* at mii?"
.Sh DESCRIPTION
The
.Nm
driver provides support for the 10/100 Mbit/s Ethernet controller
found on
.Xr ioc 4
devices.
.Sh SEE ALSO
.Xr arp 4 ,
.Xr icsphy 4 ,
.Xr ifmedia 4 ,
.Xr intro 4 ,
.Xr ioc 4 ,
.Xr netintro 4 ,
.Xr nsphy 4 ,
.Xr nsphyter 4 ,
.Xr hostname.if 5 ,
.Xr ifconfig 8
.Sh HISTORY
The
.Nm
device driver first appeared in
.Ox 4.7 .
.\" .Sh AUTHORS
.\" The
.\" .Nm
.\" driver was written by
.\" .An Miod Vallat ,
.\" borrowing significant parts from the
.\" .Xr mec 4
.\" driver written by Izumi Tsutsui and Christopher Sekiya.
