#	$OpenBSD: Makefile,v 1.24 2016/03/30 06:38:44 jmc Exp $

MAN=	dpclock.4 dsclock.4 dsrtc.4 gbe.4 gio.4 grtwo.4 hpc.4 iec.4 imc.4 \
	impact.4 intro.4 ioc.4 iockbc.4 iof.4 light.4 \
	macebus.4 mavb.4 mec.4 mkbc.4 newport.4 odyssey.4 \
	owmac.4 owserial.4 panel.4 power.4 \
	sq.4 xbow.4 xbridge.4 xheart.4 zs.4

MANSUBDIR=sgi

.include <bsd.prog.mk>
