#	$OpenBSD: Makefile,v 1.4 2005/01/02 22:05:57 kettenis Exp $

# Not applicable: crime.4 dpclock.4 dsclock.4 gio.4 haltwo.4 hpc.4
#		  imc.4 newport.4 pic.4 wdsc.4
MAN=	intro.4 macebus.4 mavb.4 mec.4
MLINKS=	macebus.4 macepcibr.4
MANSUBDIR=sgi

.include <bsd.prog.mk>
