#	$OpenBSD: Makefile,v 1.13 2009/08/18 19:34:47 miod Exp $

MAN=	dsrtc.4 gbe.4 intro.4 ioc.4 iof.4 macebus.4 mavb.4 mec.4 mkbc.4
MAN+=	owmac.4 owserial.4 power.4 xbow.4 xbridge.4 xheart.4
MLINKS=	macebus.4 macepcibr.4
MANSUBDIR=sgi

.include <bsd.prog.mk>
