# test with pf tcp state
pass proto tcp from $FAKE_NET_ADDR to $REMOTE_ADDR flags S/SA keep state
# scapy packets go through bfp and do not create state, allow respone
pass proto tcp from $REMOTE_ADDR to $FAKE_NET_ADDR flags A/A no state

# turning on and off pf via ssh connection does not work with states
pass proto tcp from port ssh flags A/SA no state
pass proto tcp to port ssh flags A/SA no state
