.\" $OpenBSD: at.1,v 1.26 2002/07/15 19:13:29 millert Exp $
.\" $FreeBSD: at.man,v 1.6 1997/02/22 19:54:05 peter Exp $
.Dd May 13, 2002
.Dt AT 1
.Os
.Sh NAME
.Nm at ,
.Nm batch
.Nd queue, examine or delete jobs for later execution
.Sh SYNOPSIS
.Nm at
.Op Fl blmr
.Op Fl f Ar file
.Op Fl q Ar queue
.Fl t Ar time_arg
.Nm at
.Op Fl blmr
.Op Fl f Ar file
.Op Fl q Ar queue
.Ar timespec
.Nm at
.Fl c Ar job Op Ar job ...
.Nm batch
.Op Fl m
.Op Fl f Ar file
.Op Fl q Ar queue
.Op Ar timespec
.Sh DESCRIPTION
.Nm at
and
.Nm batch
read commands from standard input or a specified file which
are to be executed at a later time, via the user's shell as
specified by the
.Ev SHELL
environment variable.
If
.Ev SHELL   
is not set, the shell in the user's password database entry is used
instead.
If all else fails,
.Xr sh 1
will be used.
.Pp
The related programs are as follows:
.Bl -tag -width Ds
.It Nm at
Executes commands at a specified time.
.It Nm batch
Executes commands when system load levels permit.
In other words, when
the load average drops below 1.5, or the value specified in the invocation of
.Xr cron 8 .
.El
.Pp
The options are as follows:
.Bl -tag -width indent
.It Fl b
An alias for
.Nm batch .
.It Fl c
Prints the jobs listed on the command line to standard output.
.It Fl f Ar file
Reads the job from
.Ar file
rather than standard input.
.It Fl l
Lists the user's pending jobs, unless the user is the superuser.
In that case, all users' jobs are listed.
.\" XXX - should document that user names may be specified (like atq)
.It Fl m
Send mail to the user when the job has completed, even if there was no
output.
.It Fl q Ar queue
Uses the specified queue.
A queue designation consists of a single letter.
Valid queue designations range from
.Sy a
to
.Sy z
and
.Sy A
to
.Sy Z .
The
.Sy c
queue is the default for
.Nm at
and the
.Sy E
queue for
.Nm batch .
Queues with higher letters run with increased niceness.
If a job is submitted to a queue designated with an uppercase letter, it
is treated as if it had been submitted to batch at that time.
If the user specified the
.Fl l
option and
.Nm at
is given a specific queue, only jobs pending in that queue will be shown.
.It Fl r
Remove the specified job(s) from the
.Nm at
queue.
.It Fl t Ar time_arg
Specify the job time using the format specified by
.Xr touch 1 .
The argument should be in the form
.Ar [[CC]YY]MMDDhhmm[.SS]
where each pair of letters represents the following:
.Pp
.Bl -tag -width Ds -compact -offset indent
.It Ar CC
The first two digits of the year (the century).
.It Ar YY
The second two digits of the year.
.It Ar MM
The month of the year, from 1 to 12.
.It Ar DD
the day of the month, from 1 to 31.
.It Ar hh
The hour of the day, from 0 to 23.
.It Ar mm
The minute of the hour, from 0 to 59.
.It Ar SS
The second of the minute, from 0 to 61.
.El
.Pp
If the
.Ar CC
and
.Ar YY
letter pairs are not specified, the values default to the current
year.
If the
.Ar SS
letter pair is not specified, the value defaults to 0.
.It Fl v
When used in conjuction with the
.Fl l
option, shows completed but not yet deleted jobs in the queue.
.El
.Pp
.Nm at
allows some moderately complex
.Ar timespec
specifications.
It accepts times of the form
.Ar HHMM
or
.Ar HH:MM
to run a job at a specific time of day.
(If that time is already past, the next day is assumed.)
You may also specify
.Sy midnight ,
.Sy noon ,
or
.Sy teatime
(4pm)
and you can have a time-of-day suffixed with
.Dq AM
or
.Dq PM
for running in the morning or the evening.
You can also say what day the job will be run,
by giving a date in the form
.Ar \%month-name day
with an optional
.Ar year ,
or giving a date of the form
.Ar DD.MM.CCYY ,
.Ar DD.MM.YY ,
.Ar MM/DD/CCYY ,
.Ar MM/DD/YY ,
.Ar MMDDCCYY ,
or
.Ar MMDDYY .
.Pp
The year may be given as two or four digits.
If the year is given as two digits, it is taken to occur as soon as
possible in the future, which may be in the next century --
unless it's last year, in which case it's considered to be
a typo.
.Pp
The specification of a date must follow the specification of
the time of day.
You can also give times like
.Op Sq now
.Sy + Ar count \%time-units ,
where the time-units can be
.Sy minutes ,
.Sy hours ,
.Sy days ,
or
.Sy weeks
and you can tell
.Nm at
to run the job today by suffixing the time with
.Sy today
and to run the job tomorrow by suffixing the time with
.Sy tomorrow .
.Pp
For example, to run a job at 4pm three days from now, you would do
.Ic at 4pm + 3 days .
To run a job at 10:00am on July 31, you would do
.Ic at 10am Jul 31 .
To run a job at 1am tomorrow, you would do
.Ic at 1am tomorrow .
.Pp
The
.Nm at
utility also supports the time format used by
.Xr touch 1
(see the
.Fl t
option).
.Pp
For both
.Nm at
and
.Nm batch ,
commands are read from standard input (or the file specified
with the
.Fl f
option) and executed.
The working directory, the environment (except for the variables
.Ev TERM ,
.Ev TERMCAP ,
.Ev DISPLAY ,
and
.Ev _ ) ,
and the
.Ar umask
are retained from the time of invocation.
An
.Nm at
or
.Nm batch
command invoked from a
.Xr su 1
shell will retain the current user ID.
The user will be mailed standard error and standard output from his
commands, if any.
Mail will be sent using
.Xr sendmail 8 .
If
.Nm at
is executed from a
.Xr su 1
shell, the owner of the login shell will receive the mail.
.Pp
For non-root users, permission to run
.Nm
is determined by the files
.Pa /var/at/at.allow
and
.Pa /var/at/at.deny .
.Em Note :
these files must be readable by group crontab (if they exist).
.Pp
If the file
.Pa /var/at/at.allow
exists, only usernames mentioned in it are allowed to use
.Nm at .
If
.Pa /var/at/at.allow
does not exist,
.Pa /var/at/at.deny
is checked.
Every username not mentioned in it is then allowed to use
.Nm at .
If neither exists, only the superuser is allowed to run
.Nm at .
.Pp
An empty
.Pa /var/at/at.deny
means that every user is allowed use these commands.
This is the default configuration.
.Sh FILES
.Bl -tag -width /var/at/at.allow -compact
.It Pa /var/at/jobs
directory containing job files
.It Pa /var/at/at.allow
allow permission control
.It Pa /var/at/at.deny
deny permission control
.It Pa /var/at/.SEQ
job sequence file
.El
.Sh SEE ALSO
.Xr nice 1 ,
.Xr sh 1 ,
.Xr touch 1 ,
.Xr umask 2 ,
.Xr cron 8 ,
.Xr sendmail 8
.Sh AUTHORS
.Nm at
was mostly written by Thomas Koenig <ig25@rz.uni-karlsruhe.de>.
The time parsing routines are by David Parsons <orc@pell.chi.il.us>.
.Sh BUGS
.Nm at
and
.Nm batch
as presently implemented are not suitable when users are competing for
resources.
If this is the case for your site, you might want to consider another
batch system, such as
.Nm nqs .
