.\"   $OpenBSD: htpasswd.1,v 1.2 2014/03/17 13:42:02 jmc Exp $
.\"
.\" Copyright (c) 2014 Florian Obser <florian@openbsd.org>
.\"
.\" Permission to use, copy, modify, and distribute this software for any
.\" purpose with or without fee is hereby granted, provided that the above
.\" copyright notice and this permission notice appear in all copies.
.\"
.\" THE SOFTWARE IS PROVIDED "AS IS" AND THE AUTHOR DISCLAIMS ALL WARRANTIES
.\" WITH REGARD TO THIS SOFTWARE INCLUDING ALL IMPLIED WARRANTIES OF
.\" MERCHANTABILITY AND FITNESS. IN NO EVENT SHALL THE AUTHOR BE LIABLE FOR
.\" ANY SPECIAL, DIRECT, INDIRECT, OR CONSEQUENTIAL DAMAGES OR ANY DAMAGES
.\" WHATSOEVER RESULTING FROM LOSS OF USE, DATA OR PROFITS, WHETHER IN AN
.\" ACTION OF CONTRACT, NEGLIGENCE OR OTHER TORTIOUS ACTION, ARISING OUT OF
.\" OR IN CONNECTION WITH THE USE OR PERFORMANCE OF THIS SOFTWARE.
.\"
.Dd $Mdocdate: March 17 2014 $
.Dt HTPASSWD 1
.Os
.Sh NAME
.Nm htpasswd
.Nd create and update user authentication files
.Sh SYNOPSIS
.Nm
.Op Ar file
.Ar login
.Sh DESCRIPTION
.Nm
is used to create and update user authentication files for
.Xr nginx 8
and other HTTP daemons.
.Nm
prompts for a password and generates a hash using
.Xr bcrypt 3 .
A line suitable for
.Xr nginx 8
.Ic auth_basic_user_file
is written on standard output if
.Nm
is invoked with one argument.
If invoked with two arguments the
.Ar file
user authentication file is updated.
.Sh SEE ALSO
.Xr bcrypt 3 ,
.Xr nginx.conf 5 ,
.Xr nginx 8
.Sh HISTORY
This reimplemented version of
.Nm
has been available since
.Ox 5.6 .
.Sh AUTHORS
.An Florian Obser Aq Mt florian@openbsd.org
implemented
.Nm
from scratch after httpd was removed from
.Ox
base.
