.\" $OpenBSD: keynote-keygen.1,v 1.2 1999/05/24 01:50:03 angelos Exp $
.\"
.\" The author of this code is Angelos D. Keromytis (angelos@dsl.cis.upenn.edu)
.\"
.\" This code was written by Angelos D. Keromytis in Philadelphia, PA, USA,
.\" in April-May 1998
.\"
.\" Copyright (C) 1998, 1999 by Angelos D. Keromytis.
.\"      
.\" Permission to use, copy, and modify this software without fee
.\" is hereby granted, provided that this entire notice is included in
.\" all copies of any software which is or includes a copy or
.\" modification of this software. 
.\" You may use this code under the GNU public license if you so wish. Please
.\" contribute changes back to the author.
.\"
.\" THIS SOFTWARE IS BEING PROVIDED "AS IS", WITHOUT ANY EXPRESS OR
.\" IMPLIED WARRANTY. IN PARTICULAR, THE AUTHORS MAKES NO
.\" REPRESENTATION OR WARRANTY OF ANY KIND CONCERNING THE
.\" MERCHANTABILITY OF THIS SOFTWARE OR ITS FITNESS FOR ANY PARTICULAR
.\" PURPOSE.
.\"
.Dd April 29, 1999
.Dt keynote-keygen 1
.Os
.\" .TH keynote-keygen 1 local
.Sh NAME
.Nm keynote-keygen
.Nd command line tool for generating public/private keys
.Sh SYNOPSIS
.Nm keynote keygen
.Ar AlgorithmName
.Ar KeySize
.Ar PublicKeyFile
.Ar PrivateKeyFile
.Op print-offset
.Op print-length
.Sh DESCRIPTION
For details on
.Nm KeyNote ,
see the web page 
.Bd -literal -offset indent
 http://www.cis.upenn.edu/~keynote
.Ed
.Pp
.Nm keynote-keygen
creates a public/private key of size
.Fa KeySize ,
for the algorithm specified by
.Fa AlgorithmName .
Typical keysizes are 512, 1024, or 2048 (bits). The minimum key size
for DSA keys is 512 (bits). Supported
.Fa AlgorithmName
identifiers are:
.Bl -tag -width indent
.It ``dsa-hex:''
.It ``dsa-base64:''
.It ``rsa-hex:''
.It ``rsa-base64:''
.El
.Pp
Notice that the trailing colon is required.
The resulting public key is stored in file
.Fa PublicKeyFile .
Similarly, the resulting private key is stored in file
.Fa PrivateKeyFile .
Either of the filenames can be specified to be ``-'', in which
case the corresponding key(s) will be printed in standard output.
.Pp
The optional parameters
.Fa print-offset
and
.Fa print-length
specify the offset from the begining of the line where the key
will be printed, and the number of characters of the key that will
be printed per line.
.Fa print-length
includes
.Fa AlgorithmName
for the first line and has to be longer (by at least 2) than
.Fa AlgorithmName .
.Fa print-length
also accounts for the line-continuation character (backslash) at
the end of each line, and the doublequotes at the begining and end
of the key encoding.  Default values are 12 and 50 respectively.
.Pp
.Sh SEE ALSO
.Xr keynote 1 ,
.Xr keynote 3 ,
.Xr keynote 4 ,
.Xr keynote-sign 1 ,
.Xr keynote-sigver 1 ,
.Xr keynote-verify 1
.Bl -tag -width "AAAAAAA"
.It ``The KeyNote Trust-Management System'' 
M. Blaze, J. Feigenbaum, A. D. Keromytis,
Internet Drafts, draft-ietf-trustmgt-keynote-00.txt
.It ``Decentralized Trust Management'' 
M. Blaze, J. Feigenbaum, J. Lacy,
1996 IEEE Conference on Privacy and Security
.It ``Compliance-Checking in the PolicyMaker Trust Management System''
M. Blaze, J. Feigenbaum, M. Strauss,
1998 Financial Crypto Conference
.El
.Sh AUTHOR
Angelos D. Keromytis (angelos@dsl.cis.upenn.edu)
.Sh WEB PAGE
http://www.cis.upenn.edu/~keynote
.Sh BUGS
None that we know of.
If you find any, please report them at
.Bd -literal -offset indent -compact
keynote@research.att.com
.Ed
