.\"	$OpenBSD: eeprom.8,v 1.4 1998/07/04 19:28:58 deraadt Exp $
.\"	$NetBSD: eeprom.8,v 1.2 1996/02/28 01:13:24 thorpej Exp $
.\"
.\" Copyright (c) 1996 The NetBSD Foundation, Inc.
.\" All rights reserved.
.\"
.\" This code is derived from software contributed to The NetBSD Foundation
.\" by Jason R. Thorpe.
.\"
.\" Redistribution and use in source and binary forms, with or without
.\" modification, are permitted provided that the following conditions
.\" are met:
.\" 1. Redistributions of source code must retain the above copyright
.\"    notice, this list of conditions and the following disclaimer.
.\" 2. Redistributions in binary form must reproduce the above copyright
.\"    notice, this list of conditions and the following disclaimer in the
.\"    documentation and/or other materials provided with the distribution.
.\" 3. All advertising materials mentioning features or use of this software
.\"    must display the following acknowledgement:
.\"        This product includes software developed by the NetBSD
.\"        Foundation, Inc. and its contributors.
.\" 4. Neither the name of The NetBSD Foundation nor the names of its
.\"    contributors may be used to endorse or promote products derived
.\"    from this software without specific prior written permission.
.\"
.\" THIS SOFTWARE IS PROVIDED BY THE NETBSD FOUNDATION, INC. AND CONTRIBUTORS
.\" ``AS IS'' AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED
.\" TO, THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR
.\" PURPOSE ARE DISCLAIMED.  IN NO EVENT SHALL THE REGENTS OR CONTRIBUTORS BE
.\" LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR
.\" CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF
.\" SUBSTITUTE GOODS OR SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS
.\" INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN
.\" CONTRACT, STRICT LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE)
.\" ARISING IN ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE
.\" POSSIBILITY OF SUCH DAMAGE.
.\"
.Dd May 25, 1995
.Dt EEPROM 8
.Os
.Sh NAME
.Nm eeprom
.Nd display or modify contents of the EEPROM or OpenProm
.Sh SUN 3 SYNOPSIS
.Nm eeprom
.Op Fl
.Op Fl c
.Op Fl f Ar device
.Op Fl i
.Oo
.Ar field Ns Oo
.Li = Ns Ar value
.Oc ...
.Oc
.Sh SPARC SYNOPSIS
.Nm eeprom
.Op Fl
.Op Fl c
.Op Fl f Ar device
.Op Fl i
.Op Fl v
.Op Fl N Ar system
.Oo
.Ar field Ns Oo
.Li = Ns Ar value
.Oc ...
.Oc
.Sh DESCRIPTION
.Nm Eeprom
provides an interface for displaying and changing the contents of the
EEPROM or OpenProm.  Without any arguments,
.Nm eeprom
will list all of the known fields and their corresponding values.
When given the name of a specific field,
.Nm eeprom
will display that value or set it if the field name is followed by
.Sq =
and a value.  Only the super-user may modify the contents of the EEPROM
or OpenProm.
.Pp
The options are as follows:
.Bl -tag -width indent
.It Fl
Commands are taken from stdin and displayed on stdout.
.It Fl c
.Nm Eeprom
will fix incorrect checksum values and exit.  This flag is quietly ignored
on systems with an OpenProm.
.It Fl f Ar device
On systems with an EEPROM, use
.Ar device
instead of the default
.Pa /dev/eeprom .
On systems with an OpenProm, use
.Ar device
instead of the default
.Pa /dev/openprom .
.It Fl i
If checksum values are incorrect,
.Nm eeprom
will ignore them and continue after displaying a warning.  This flag is
quietly ignored on systems with an OpenProm.
.El
.Pp
The following options are valid only on the SPARC and will produce an
error when used on a Sun 3:
.Bl -tag -width indent
.It Fl v
On systems with an OpenProm, be verbose when setting a value.  Systems
with an EEPROM are always verbose.
.It Fl N Ar system
Use the system image
.Ar system
instead of the default
.Pa /bsd .
.El
.Sh FIELDS AND VALUES
The following fields and values are for systems with an EEPROM:
.Bl -tag -width "watchdog_reboot  "
.It hwupdate
A valid date, such as
.Dq 7/12/95 .
The strings
.Dq today
and
.Dq now
are also acceptable.
.It memsize
How much memory, in megabytes, is installed in the system.
.It memtest
How much memory, in megabytes, is to be tested upon power-up.
.It scrsize
The size of the screen.  Acceptable values are
.Dq 1024x1024 ,
.Dq 1152x900 ,
.Dq 1600x1280 ,
and
.Dq 1440x1440 .
.It watchdog_reboot
If true, the system will reboot upon reset.  Otherwise, the system will fall
into the monitor.
.It default_boot
If true, the system will use the boot device stored in
.Pa bootdev .
.It bootdev
Specifies the default boot device in the form cc(x,x,x), where
.Sq cc
is a combination of two letters such as
.Sq sd
or
.Sq le
and each
.Sq x
is a hexadecimal number between 0 and ff, less the prepending
.Sq 0x .
.It kbdtype
This value is
.Dq 0
for all Sun keyboards.
.It console
Specifies the console type.  Valid values are
.Dq b&w ,
.Dq ttya ,
.Dq ttyb ,
.Dq color ,
and
.Dq p4opt .
.It keyclick
If true, the keys click annoyingly.
.It diagdev
This is a string very similar to that used by
.Pa bootdev .
It specifies the default boot device when the diagnostic switch is
turned on.
.It diagpath
A 40-character, NULL-terminated string specifying the kernel or standalone
program to load when the diagnostic switch is turned on.
.It columns
An 8-bit integer specifying the number of columns on the console.
.It rows
An 8-bit integer specifying the number of rows on the console.
.It ttya_use_baud
Use the baud rate stored in
.Pa ttya_baud
instead of the default 9600.
.It ttya_baud
A 16-bit integer specifying the baud rate to use on ttya.
.It ttya_no_rtsdtr
If true, disables RTS/DTR.
.It ttyb_use_baud
Similar to
.Pa ttya_use_baud ,
but for ttyb.
.It ttyb_baud
Similar to
.Pa ttya_baud ,
but for ttyb.
.It ttyb_no_rtsdtr
Similar to
.Pa ttya_no_rtsdtr ,
but for ttyb.
.It banner
An 80-character, NULL-terminated string to use at power-up instead
of the default Sun banner.
.El
.Pp
Note that the
.Pa secure ,
.Pa bad_login ,
and
.Pa password
fields are not currently supported.
.Pp
Since the OpenProm is designed such that the field names are arbitrary,
explaining them here is dubious.  Below are field names and values that
one is likely to see on a system with an OpenProm.  NOTE: this list
may be incomplete or incorrect due to differences between revisions
of the OpenProm.
.Bl -tag -width "last-hardware-update  "
.It sunmon-compat?
If true, the old EEPROM-style interface will be used while in the monitor,
rather than the OpenProm-style interface.
.It selftest-#megs
A 32-bit inteteger specifying the number of megabytes of memory to
test upon power-up.
.It oem-logo
A 64bitx64bit bitmap in Sun Iconedit format.  To set the bitmap, give
the pathname of the file containing the image.  NOTE: this proprty is
not yet supported.
.It oem-logo?
If true, enables the use of the bitmap stored in
.Pa oem-logo
rather than the default Sun logo.
.It oem-banner
A string to use at power up, rather than the default Sun banner.
.It oem-banner?
If true, emables the use of the banner stored in
.Pa oem-banner 
rather than the default Sun banner.
.It ttya-mode
A string of five comma separated fields in the format
.Dq 9600,8,n,1,- .
The first field is the baud rate.  The second field is the
number of data bits.  The third field is the parity; acceptable values
for parity are
.Sq n
(none),
.Sq e
(even),
.Sq o
(odd),
.Sq m
(mark), and
.Sq s
(space).  The
fourth field is the number of stop bits.  The fifth field is the
.Sq handshake
field; acceptable values are
.Sq -
(none),
.Sq h
(rts/cts), and
.Sq s
(xon/xoff).
.It ttya-rts-dtr-off
If true, the system will ignore RTS/DTR.
.It ttya-ignore-cd
If true, the system will ignore carrier detect.
.It ttyb-mode
Similar to
.Pa ttya-mode ,
but for ttyb.
.It ttyb-rts-dtr-off
Similar to
.Pa ttya-rts-dtr-off ,
but for ttyb.
.It ttyb-ignore-cd
Similar to
.Pa ttya-ignore-cd ,
but for ttyb.
.It sbus-probe-list
Four digits in the format
.Dq 0123
specifying which order to probe the sbus at power-up.  It is unlikely that
this value should ever be changed.
.It screen-#columns
An 8-bit integer specifying the number of columns on the console.
.It screen-#rows
An 8-bit integer specifying the number of rows on the console.
.It auto-boot?
If true, the system will boot automatically at power-up.
.It watchdog-reboot?
If true, the system will reboot upon reset.  Otherwise, system will fall
into the monitor.
.It input-device
One of the strings
.Dq keyboard ,
.Dq ttya ,
or
.Dq ttyb
specifying the default console input device.
.It output-device
One of the strings
.Dq screen ,
.Dq ttya ,
or
.Dq ttyb
specifying the default console output device.
.It keyboard-click?
If true, the keys click annoyingly.
.It sd-targets
A string in the format
.Dq 31204567
describing the translation of physical to logical target.
.It st-targets
Similar to
.Pa sd-targets ,
but for tapes.  The default translation is
.Dq 45670123 .
.It scsi-initiator-id
The SCSI ID of the on-board SCSI controller.
.It hardware-revision
A 7-character string describing a date, such as
.Dq 25May95 .
.It last-hardware-update
Similar to
.Pa hardware-revision ,
describing when the CPU was last updated.
.It diag-switch?
If true, the system will boot and run in diagnostic mode.
.El
.Sh WARNINGS
The fields and their values are not necessarily well defined on
systems with an OpenProm.  Your mileage may vary.
.Pp
There are a few fields known to exist in some revisions of the EEPROM
and/or OpenProm that are not yet supported.  Most notable are those
relating to password protection of the EEPROM or OpenProm.
.Pp
Avoid gratuitously changing the contents of the EEPROM.  It has a limited
number of write cycles.
.Pp
The date parser isn't very intelligent.
.Sh FILES
.Bl -tag -width "/dev/openprom  "
.It /dev/eeprom
The EEPROM device on systems with an EEPROM.
.It /dev/openprom
The OpenProm device on systems with an OpenProm.
.El
