.\"
.\" Copyright (c) 2005 Jacob Meuser <jakemsr@jakemsr.com>
.\"
.\" Permission to use, copy, modify, and distribute this software for any
.\" purpose with or without fee is hereby granted, provided that the above
.\" copyright notice and this permission notice appear in all copies.
.\"
.\" THE SOFTWARE IS PROVIDED "AS IS" AND THE AUTHOR DISCLAIMS ALL WARRANTIES
.\" WITH REGARD TO THIS SOFTWARE INCLUDING ALL IMPLIED WARRANTIES OF
.\" MERCHANTABILITY AND FITNESS. IN NO EVENT SHALL THE AUTHOR BE LIABLE FOR
.\" ANY SPECIAL, DIRECT, INDIRECT, OR CONSEQUENTIAL DAMAGES OR ANY DAMAGES
.\" WHATSOEVER RESULTING FROM LOSS OF USE, DATA OR PROFITS, WHETHER IN AN
.\" ACTION OF CONTRACT, NEGLIGENCE OR OTHER TORTIOUS ACTION, ARISING OUT OF
.\" OR IN CONNECTION WITH THE USE OR PERFORMANCE OF THIS SOFTWARE.
.\"
.\"	$OpenBSD: tunerctl.1,v 1.2 2005/07/04 23:27:05 robert Exp $
.\"
.Dd Mar 27, 2005
.Dt TUNERCTL 1
.Os
.Sh NAME
.Nm tunerctl
.Nd manipulate
.Xr bktr 4
tuner devices.
.Sh SYNOPSIS
.Nm
.Op Fl nv
.Op Fl f Ar file
.Fl a
.Nm
.Op Fl nv
.Op Fl f Ar file
.Ar name
.Op Ar ...
.Nm
.Op Fl q
.Pf \ \& Op Fl f Ar file
.Xo
.Ar name Ns = Ns Ar value
.Op Ar ...
.Xc
.Sh DESCRIPTION
The
.Nm
command displays or sets various variables that affect the behaviour of
.Xr bktr 4
device tuners.
If a list of variables is present on the command line,
.Nm
prints the current value of those variables for the specified device.
By default,
.Nm
operates on the
.Pa /dev/tuner0
device.
.Pp
The options are as follows:
.Bl -tag -width "name=value"
.It Fl a
Print all device variables and their current values.
.It Fl f Ar file
Specify an alternative tuner device.
.It Fl n
Suppress printing of the variable names.
.It Fl q
Suppress all printing when setting a variable.
.It Fl v
Show the possible values of enumeration and range valued queries.
Enumeration values are show in
.Dq []
and ranges are show in
.Dq () .
.It Ar name Ns = Ns Ar value
Attempt to set the specified variable
.Ar name
to
.Ar value .
.El
.Pp
Depending on the features of a specific tuner, the setting of some
variables may not have any effect.
.Pp
Variable names explained:
.Bl -tag -width contrast
.It Ic chanset
TV tuner channel set.
.It Ic channel
TV tuner channel.
.It Ic freq
Frequency in MHz.
.It Ic afc
Automatic Frequency Control.
.It Ic audio
Audio source.
.It Ic mute
Audio mute.
.It Ic bright
Video brightness.
.It Ic contrast
Video contrast.
.It Ic hue
Video hue.
.It Ic usat
Video
.Ql U
(blue) saturation.
.It Ic vsat
Video
.Ql V
(red) saturation.
.El
.Sh FILES
.Bl -tag -width /dev/tuner0
.It Pa /dev/tuner0
default tuner device
.El
.Sh EXAMPLES
The command
.Pp
.Dl "$ tunerctl chanset=nabcst channel=13"
.Pp
sets the tuner to North American broadcast TV channel 13.
.Sh SEE ALSO
.Xr bktr 4
.Sh AUTHORS
.Nm
and this manual page were written by
.An Jacob Meuser Aq jakemsr@jakemsr.com .
.Sh HISTORY
The
.Nm
command first appeared in
.Ox 3.8 .
