# !!!!!!!   DO NOT EDIT THIS FILE   !!!!!!!
# This file is machine-generated by lib/unicore/mktables from the Unicode
# database, Version 5.2.0.  Any changes made here will be lost!

# !!!!!!!   INTERNAL PERL USE ONLY   !!!!!!!
# This file is for internal use by the Perl program only.  The format and even
# the name or existence of this file are subject to change without notice.
# Don't use it directly.

# This file is for tables that are not necessarily related:  To conserve
# resources, every table that matches the identical set of code points in
# this version of Unicode uses this file.  Each one is listed in a separate
# group below.  It could be that the tables will match the same set of code
# points in other Unicode releases, or it could be purely coincidence that
# they happen to be the same in Unicode 5.2.0, and hence may not in other
# versions.
# 
# This file returns the 103 code points in Unicode Version 5.2.0 that match
# any of the following regular expression constructs:
# 
#         \p{NFKC_Quick_Check=Maybe}
#         \p{NFKC_QC=M}
#         \p{Is_NFKC_Quick_Check=Maybe}
#         \p{Is_NFKC_QC=M}
# 
#         \p{NFC_Quick_Check=Maybe}
#         \p{NFC_QC=M}
#         \p{Is_NFC_Quick_Check=Maybe}
#         \p{Is_NFC_QC=M}
# 
# perluniprops.pod should be consulted for the syntax rules for any of these,
# including if adding or subtracting white space, underscore, and hyphen
# characters matters or doesn't matter, and other permissible syntactic
# variants.  Upper/lower case distinctions never matter.
# 
# A colon can be substituted for the equals sign, and within each group
# above, anything to the left of the equals (or colon) can be combined with
# anything to the right.  Thus, for example,
#         \p{Is_NFC_QC: Maybe}
# is also valid.
# 
# The format of the lines of this file is: START\tSTOP\twhere START is the
# starting code point of the range, in hex; STOP is the ending point, or if
# omitted, the range has just one code point.  Numbers in comments in
# [brackets] indicate how many code points are in the range.

return <<'END';
0300	0304	 # [5]
0306	030C	 # [7]
030F		
0311		
0313	0314	 # [2]
031B		
0323	0328	 # [6]
032D	032E	 # [2]
0330	0331	 # [2]
0338		
0342		
0345		
0653	0655	 # [3]
093C		
09BE		
09D7		
0B3E		
0B56	0B57	 # [2]
0BBE		
0BD7		
0C56		
0CC2		
0CD5	0CD6	 # [2]
0D3E		
0D57		
0DCA		
0DCF		
0DDF		
102E		
1161	1175	 # [21]
11A8	11C2	 # [27]
1B35		
3099	309A	 # [2]
110BA		
END
