#	$OpenBSD: Makefile,v 1.47 2002/11/16 05:01:26 marc Exp $
#	$NetBSD: Makefile,v 1.20.4.1 1996/06/14 17:22:38 cgd Exp $

SUBDIR=	csu libarch libc libc_r libcom_err libcompat libcurses libcurses++ \
	libdes libedit libevent libform libkeynote libkvm libl libm libmenu \
	libocurses libossaudio libpanel libpcap libpthread libresolv librpcsvc \
	libskey libsectok libssl libtelnet libusbhid libutil libwrap liby libz

.include <bsd.subdir.mk>
