#	$OpenBSD: Makefile,v 1.2 2002/04/30 03:23:57 deraadt Exp $

.PATH: ${.CURDIR}/../ramdisk
RAMDISK=RAMDISK_CD
FLOPPYSIZE=288
FLOPPYTYPE=floppy288
XNAME=cdrom
FLOPPYSECS=36

.include "${.CURDIR}/../common/Makefile.inc"

LISTS+=		${.CURDIR}/list.local
