# !!!!!!!   DO NOT EDIT THIS FILE   !!!!!!!
# This file is machine-generated by lib/unicore/mktables from the Unicode
# database, Version 6.2.0.  Any changes made here will be lost!

# !!!!!!!   INTERNAL PERL USE ONLY   !!!!!!!
# This file is for internal use by core Perl only.  The format and even the
# name or existence of this file are subject to change without notice.  Don't
# use it directly.



# The name this swash is to be known by, with the format of the mappings in
# the main body of the table, and what all code points missing from this file
# map to.
$utf8::SwashInfo{'ToSB'}{'format'} = 's'; # string
$utf8::SwashInfo{'ToSB'}{'missing'} = 'Other';

return <<'END';
0009		Sp
000A		LF
000B	000C	Sp
000D		CR
0020		Sp
0021		STerm
0022		Close
0027	0029	Close
002C	002D	SContinue
002E		ATerm
0030	0039	Numeric
003A		SContinue
003F		STerm
0041	005A	Upper
005B		Close
005D		Close
0061	007A	Lower
007B		Close
007D		Close
0085		Sep
00A0		Sp
00AA		Lower
00AB		Close
00AD		Format
00B5		Lower
00BA		Lower
00BB		Close
00C0	00D6	Upper
00D8	00DE	Upper
00DF	00F6	Lower
00F8	00FF	Lower
0100		Upper
0101		Lower
0102		Upper
0103		Lower
0104		Upper
0105		Lower
0106		Upper
0107		Lower
0108		Upper
0109		Lower
010A		Upper
010B		Lower
010C		Upper
010D		Lower
010E		Upper
010F		Lower
0110		Upper
0111		Lower
0112		Upper
0113		Lower
0114		Upper
0115		Lower
0116		Upper
0117		Lower
0118		Upper
0119		Lower
011A		Upper
011B		Lower
011C		Upper
011D		Lower
011E		Upper
011F		Lower
0120		Upper
0121		Lower
0122		Upper
0123		Lower
0124		Upper
0125		Lower
0126		Upper
0127		Lower
0128		Upper
0129		Lower
012A		Upper
012B		Lower
012C		Upper
012D		Lower
012E		Upper
012F		Lower
0130		Upper
0131		Lower
0132		Upper
0133		Lower
0134		Upper
0135		Lower
0136		Upper
0137	0138	Lower
0139		Upper
013A		Lower
013B		Upper
013C		Lower
013D		Upper
013E		Lower
013F		Upper
0140		Lower
0141		Upper
0142		Lower
0143		Upper
0144		Lower
0145		Upper
0146		Lower
0147		Upper
0148	0149	Lower
014A		Upper
014B		Lower
014C		Upper
014D		Lower
014E		Upper
014F		Lower
0150		Upper
0151		Lower
0152		Upper
0153		Lower
0154		Upper
0155		Lower
0156		Upper
0157		Lower
0158		Upper
0159		Lower
015A		Upper
015B		Lower
015C		Upper
015D		Lower
015E		Upper
015F		Lower
0160		Upper
0161		Lower
0162		Upper
0163		Lower
0164		Upper
0165		Lower
0166		Upper
0167		Lower
0168		Upper
0169		Lower
016A		Upper
016B		Lower
016C		Upper
016D		Lower
016E		Upper
016F		Lower
0170		Upper
0171		Lower
0172		Upper
0173		Lower
0174		Upper
0175		Lower
0176		Upper
0177		Lower
0178	0179	Upper
017A		Lower
017B		Upper
017C		Lower
017D		Upper
017E	0180	Lower
0181	0182	Upper
0183		Lower
0184		Upper
0185		Lower
0186	0187	Upper
0188		Lower
0189	018B	Upper
018C	018D	Lower
018E	0191	Upper
0192		Lower
0193	0194	Upper
0195		Lower
0196	0198	Upper
0199	019B	Lower
019C	019D	Upper
019E		Lower
019F	01A0	Upper
01A1		Lower
01A2		Upper
01A3		Lower
01A4		Upper
01A5		Lower
01A6	01A7	Upper
01A8		Lower
01A9		Upper
01AA	01AB	Lower
01AC		Upper
01AD		Lower
01AE	01AF	Upper
01B0		Lower
01B1	01B3	Upper
01B4		Lower
01B5		Upper
01B6		Lower
01B7	01B8	Upper
01B9	01BA	Lower
01BB		OLetter
01BC		Upper
01BD	01BF	Lower
01C0	01C3	OLetter
01C4	01C5	Upper
01C6		Lower
01C7	01C8	Upper
01C9		Lower
01CA	01CB	Upper
01CC		Lower
01CD		Upper
01CE		Lower
01CF		Upper
01D0		Lower
01D1		Upper
01D2		Lower
01D3		Upper
01D4		Lower
01D5		Upper
01D6		Lower
01D7		Upper
01D8		Lower
01D9		Upper
01DA		Lower
01DB		Upper
01DC	01DD	Lower
01DE		Upper
01DF		Lower
01E0		Upper
01E1		Lower
01E2		Upper
01E3		Lower
01E4		Upper
01E5		Lower
01E6		Upper
01E7		Lower
01E8		Upper
01E9		Lower
01EA		Upper
01EB		Lower
01EC		Upper
01ED		Lower
01EE		Upper
01EF	01F0	Lower
01F1	01F2	Upper
01F3		Lower
01F4		Upper
01F5		Lower
01F6	01F8	Upper
01F9		Lower
01FA		Upper
01FB		Lower
01FC		Upper
01FD		Lower
01FE		Upper
01FF		Lower
0200		Upper
0201		Lower
0202		Upper
0203		Lower
0204		Upper
0205		Lower
0206		Upper
0207		Lower
0208		Upper
0209		Lower
020A		Upper
020B		Lower
020C		Upper
020D		Lower
020E		Upper
020F		Lower
0210		Upper
0211		Lower
0212		Upper
0213		Lower
0214		Upper
0215		Lower
0216		Upper
0217		Lower
0218		Upper
0219		Lower
021A		Upper
021B		Lower
021C		Upper
021D		Lower
021E		Upper
021F		Lower
0220		Upper
0221		Lower
0222		Upper
0223		Lower
0224		Upper
0225		Lower
0226		Upper
0227		Lower
0228		Upper
0229		Lower
022A		Upper
022B		Lower
022C		Upper
022D		Lower
022E		Upper
022F		Lower
0230		Upper
0231		Lower
0232		Upper
0233	0239	Lower
023A	023B	Upper
023C		Lower
023D	023E	Upper
023F	0240	Lower
0241		Upper
0242		Lower
0243	0246	Upper
0247		Lower
0248		Upper
0249		Lower
024A		Upper
024B		Lower
024C		Upper
024D		Lower
024E		Upper
024F	0293	Lower
0294		OLetter
0295	02B8	Lower
02B9	02BF	OLetter
02C0	02C1	Lower
02C6	02D1	OLetter
02E0	02E4	Lower
02EC		OLetter
02EE		OLetter
0300	036F	Extend
0370		Upper
0371		Lower
0372		Upper
0373		Lower
0374		OLetter
0376		Upper
0377		Lower
037A	037D	Lower
0386		Upper
0388	038A	Upper
038C		Upper
038E	038F	Upper
0390		Lower
0391	03A1	Upper
03A3	03AB	Upper
03AC	03CE	Lower
03CF		Upper
03D0	03D1	Lower
03D2	03D4	Upper
03D5	03D7	Lower
03D8		Upper
03D9		Lower
03DA		Upper
03DB		Lower
03DC		Upper
03DD		Lower
03DE		Upper
03DF		Lower
03E0		Upper
03E1		Lower
03E2		Upper
03E3		Lower
03E4		Upper
03E5		Lower
03E6		Upper
03E7		Lower
03E8		Upper
03E9		Lower
03EA		Upper
03EB		Lower
03EC		Upper
03ED		Lower
03EE		Upper
03EF	03F3	Lower
03F4		Upper
03F5		Lower
03F7		Upper
03F8		Lower
03F9	03FA	Upper
03FB	03FC	Lower
03FD	042F	Upper
0430	045F	Lower
0460		Upper
0461		Lower
0462		Upper
0463		Lower
0464		Upper
0465		Lower
0466		Upper
0467		Lower
0468		Upper
0469		Lower
046A		Upper
046B		Lower
046C		Upper
046D		Lower
046E		Upper
046F		Lower
0470		Upper
0471		Lower
0472		Upper
0473		Lower
0474		Upper
0475		Lower
0476		Upper
0477		Lower
0478		Upper
0479		Lower
047A		Upper
047B		Lower
047C		Upper
047D		Lower
047E		Upper
047F		Lower
0480		Upper
0481		Lower
0483	0489	Extend
048A		Upper
048B		Lower
048C		Upper
048D		Lower
048E		Upper
048F		Lower
0490		Upper
0491		Lower
0492		Upper
0493		Lower
0494		Upper
0495		Lower
0496		Upper
0497		Lower
0498		Upper
0499		Lower
049A		Upper
049B		Lower
049C		Upper
049D		Lower
049E		Upper
049F		Lower
04A0		Upper
04A1		Lower
04A2		Upper
04A3		Lower
04A4		Upper
04A5		Lower
04A6		Upper
04A7		Lower
04A8		Upper
04A9		Lower
04AA		Upper
04AB		Lower
04AC		Upper
04AD		Lower
04AE		Upper
04AF		Lower
04B0		Upper
04B1		Lower
04B2		Upper
04B3		Lower
04B4		Upper
04B5		Lower
04B6		Upper
04B7		Lower
04B8		Upper
04B9		Lower
04BA		Upper
04BB		Lower
04BC		Upper
04BD		Lower
04BE		Upper
04BF		Lower
04C0	04C1	Upper
04C2		Lower
04C3		Upper
04C4		Lower
04C5		Upper
04C6		Lower
04C7		Upper
04C8		Lower
04C9		Upper
04CA		Lower
04CB		Upper
04CC		Lower
04CD		Upper
04CE	04CF	Lower
04D0		Upper
04D1		Lower
04D2		Upper
04D3		Lower
04D4		Upper
04D5		Lower
04D6		Upper
04D7		Lower
04D8		Upper
04D9		Lower
04DA		Upper
04DB		Lower
04DC		Upper
04DD		Lower
04DE		Upper
04DF		Lower
04E0		Upper
04E1		Lower
04E2		Upper
04E3		Lower
04E4		Upper
04E5		Lower
04E6		Upper
04E7		Lower
04E8		Upper
04E9		Lower
04EA		Upper
04EB		Lower
04EC		Upper
04ED		Lower
04EE		Upper
04EF		Lower
04F0		Upper
04F1		Lower
04F2		Upper
04F3		Lower
04F4		Upper
04F5		Lower
04F6		Upper
04F7		Lower
04F8		Upper
04F9		Lower
04FA		Upper
04FB		Lower
04FC		Upper
04FD		Lower
04FE		Upper
04FF		Lower
0500		Upper
0501		Lower
0502		Upper
0503		Lower
0504		Upper
0505		Lower
0506		Upper
0507		Lower
0508		Upper
0509		Lower
050A		Upper
050B		Lower
050C		Upper
050D		Lower
050E		Upper
050F		Lower
0510		Upper
0511		Lower
0512		Upper
0513		Lower
0514		Upper
0515		Lower
0516		Upper
0517		Lower
0518		Upper
0519		Lower
051A		Upper
051B		Lower
051C		Upper
051D		Lower
051E		Upper
051F		Lower
0520		Upper
0521		Lower
0522		Upper
0523		Lower
0524		Upper
0525		Lower
0526		Upper
0527		Lower
0531	0556	Upper
0559		OLetter
055C		STerm
055D		SContinue
055E		STerm
0561	0587	Lower
0589		STerm
0591	05BD	Extend
05BF		Extend
05C1	05C2	Extend
05C4	05C5	Extend
05C7		Extend
05D0	05EA	OLetter
05F0	05F3	OLetter
0600	0604	Format
060C	060D	SContinue
0610	061A	Extend
061F		STerm
0620	064A	OLetter
064B	065F	Extend
0660	0669	Numeric
066B	066C	Numeric
066E	066F	OLetter
0670		Extend
0671	06D3	OLetter
06D4		STerm
06D5		OLetter
06D6	06DC	Extend
06DD		Format
06DF	06E4	Extend
06E5	06E6	OLetter
06E7	06E8	Extend
06EA	06ED	Extend
06EE	06EF	OLetter
06F0	06F9	Numeric
06FA	06FC	OLetter
06FF		OLetter
0700	0702	STerm
070F		Format
0710		OLetter
0711		Extend
0712	072F	OLetter
0730	074A	Extend
074D	07A5	OLetter
07A6	07B0	Extend
07B1		OLetter
07C0	07C9	Numeric
07CA	07EA	OLetter
07EB	07F3	Extend
07F4	07F5	OLetter
07F8		SContinue
07F9		STerm
07FA		OLetter
0800	0815	OLetter
0816	0819	Extend
081A		OLetter
081B	0823	Extend
0824		OLetter
0825	0827	Extend
0828		OLetter
0829	082D	Extend
0840	0858	OLetter
0859	085B	Extend
08A0		OLetter
08A2	08AC	OLetter
08E4	08FE	Extend
0900	0903	Extend
0904	0939	OLetter
093A	093C	Extend
093D		OLetter
093E	094F	Extend
0950		OLetter
0951	0957	Extend
0958	0961	OLetter
0962	0963	Extend
0964	0965	STerm
0966	096F	Numeric
0971	0977	OLetter
0979	097F	OLetter
0981	0983	Extend
0985	098C	OLetter
098F	0990	OLetter
0993	09A8	OLetter
09AA	09B0	OLetter
09B2		OLetter
09B6	09B9	OLetter
09BC		Extend
09BD		OLetter
09BE	09C4	Extend
09C7	09C8	Extend
09CB	09CD	Extend
09CE		OLetter
09D7		Extend
09DC	09DD	OLetter
09DF	09E1	OLetter
09E2	09E3	Extend
09E6	09EF	Numeric
09F0	09F1	OLetter
0A01	0A03	Extend
0A05	0A0A	OLetter
0A0F	0A10	OLetter
0A13	0A28	OLetter
0A2A	0A30	OLetter
0A32	0A33	OLetter
0A35	0A36	OLetter
0A38	0A39	OLetter
0A3C		Extend
0A3E	0A42	Extend
0A47	0A48	Extend
0A4B	0A4D	Extend
0A51		Extend
0A59	0A5C	OLetter
0A5E		OLetter
0A66	0A6F	Numeric
0A70	0A71	Extend
0A72	0A74	OLetter
0A75		Extend
0A81	0A83	Extend
0A85	0A8D	OLetter
0A8F	0A91	OLetter
0A93	0AA8	OLetter
0AAA	0AB0	OLetter
0AB2	0AB3	OLetter
0AB5	0AB9	OLetter
0ABC		Extend
0ABD		OLetter
0ABE	0AC5	Extend
0AC7	0AC9	Extend
0ACB	0ACD	Extend
0AD0		OLetter
0AE0	0AE1	OLetter
0AE2	0AE3	Extend
0AE6	0AEF	Numeric
0B01	0B03	Extend
0B05	0B0C	OLetter
0B0F	0B10	OLetter
0B13	0B28	OLetter
0B2A	0B30	OLetter
0B32	0B33	OLetter
0B35	0B39	OLetter
0B3C		Extend
0B3D		OLetter
0B3E	0B44	Extend
0B47	0B48	Extend
0B4B	0B4D	Extend
0B56	0B57	Extend
0B5C	0B5D	OLetter
0B5F	0B61	OLetter
0B62	0B63	Extend
0B66	0B6F	Numeric
0B71		OLetter
0B82		Extend
0B83		OLetter
0B85	0B8A	OLetter
0B8E	0B90	OLetter
0B92	0B95	OLetter
0B99	0B9A	OLetter
0B9C		OLetter
0B9E	0B9F	OLetter
0BA3	0BA4	OLetter
0BA8	0BAA	OLetter
0BAE	0BB9	OLetter
0BBE	0BC2	Extend
0BC6	0BC8	Extend
0BCA	0BCD	Extend
0BD0		OLetter
0BD7		Extend
0BE6	0BEF	Numeric
0C01	0C03	Extend
0C05	0C0C	OLetter
0C0E	0C10	OLetter
0C12	0C28	OLetter
0C2A	0C33	OLetter
0C35	0C39	OLetter
0C3D		OLetter
0C3E	0C44	Extend
0C46	0C48	Extend
0C4A	0C4D	Extend
0C55	0C56	Extend
0C58	0C59	OLetter
0C60	0C61	OLetter
0C62	0C63	Extend
0C66	0C6F	Numeric
0C82	0C83	Extend
0C85	0C8C	OLetter
0C8E	0C90	OLetter
0C92	0CA8	OLetter
0CAA	0CB3	OLetter
0CB5	0CB9	OLetter
0CBC		Extend
0CBD		OLetter
0CBE	0CC4	Extend
0CC6	0CC8	Extend
0CCA	0CCD	Extend
0CD5	0CD6	Extend
0CDE		OLetter
0CE0	0CE1	OLetter
0CE2	0CE3	Extend
0CE6	0CEF	Numeric
0CF1	0CF2	OLetter
0D02	0D03	Extend
0D05	0D0C	OLetter
0D0E	0D10	OLetter
0D12	0D3A	OLetter
0D3D		OLetter
0D3E	0D44	Extend
0D46	0D48	Extend
0D4A	0D4D	Extend
0D4E		OLetter
0D57		Extend
0D60	0D61	OLetter
0D62	0D63	Extend
0D66	0D6F	Numeric
0D7A	0D7F	OLetter
0D82	0D83	Extend
0D85	0D96	OLetter
0D9A	0DB1	OLetter
0DB3	0DBB	OLetter
0DBD		OLetter
0DC0	0DC6	OLetter
0DCA		Extend
0DCF	0DD4	Extend
0DD6		Extend
0DD8	0DDF	Extend
0DF2	0DF3	Extend
0E01	0E30	OLetter
0E31		Extend
0E32	0E33	OLetter
0E34	0E3A	Extend
0E40	0E46	OLetter
0E47	0E4E	Extend
0E50	0E59	Numeric
0E81	0E82	OLetter
0E84		OLetter
0E87	0E88	OLetter
0E8A		OLetter
0E8D		OLetter
0E94	0E97	OLetter
0E99	0E9F	OLetter
0EA1	0EA3	OLetter
0EA5		OLetter
0EA7		OLetter
0EAA	0EAB	OLetter
0EAD	0EB0	OLetter
0EB1		Extend
0EB2	0EB3	OLetter
0EB4	0EB9	Extend
0EBB	0EBC	Extend
0EBD		OLetter
0EC0	0EC4	OLetter
0EC6		OLetter
0EC8	0ECD	Extend
0ED0	0ED9	Numeric
0EDC	0EDF	OLetter
0F00		OLetter
0F18	0F19	Extend
0F20	0F29	Numeric
0F35		Extend
0F37		Extend
0F39		Extend
0F3A	0F3D	Close
0F3E	0F3F	Extend
0F40	0F47	OLetter
0F49	0F6C	OLetter
0F71	0F84	Extend
0F86	0F87	Extend
0F88	0F8C	OLetter
0F8D	0F97	Extend
0F99	0FBC	Extend
0FC6		Extend
1000	102A	OLetter
102B	103E	Extend
103F		OLetter
1040	1049	Numeric
104A	104B	STerm
1050	1055	OLetter
1056	1059	Extend
105A	105D	OLetter
105E	1060	Extend
1061		OLetter
1062	1064	Extend
1065	1066	OLetter
1067	106D	Extend
106E	1070	OLetter
1071	1074	Extend
1075	1081	OLetter
1082	108D	Extend
108E		OLetter
108F		Extend
1090	1099	Numeric
109A	109D	Extend
10A0	10C5	Upper
10C7		Upper
10CD		Upper
10D0	10FA	OLetter
10FC	1248	OLetter
124A	124D	OLetter
1250	1256	OLetter
1258		OLetter
125A	125D	OLetter
1260	1288	OLetter
128A	128D	OLetter
1290	12B0	OLetter
12B2	12B5	OLetter
12B8	12BE	OLetter
12C0		OLetter
12C2	12C5	OLetter
12C8	12D6	OLetter
12D8	1310	OLetter
1312	1315	OLetter
1318	135A	OLetter
135D	135F	Extend
1362		STerm
1367	1368	STerm
1380	138F	OLetter
13A0	13F4	OLetter
1401	166C	OLetter
166E		STerm
166F	167F	OLetter
1680		Sp
1681	169A	OLetter
169B	169C	Close
16A0	16EA	OLetter
16EE	16F0	OLetter
1700	170C	OLetter
170E	1711	OLetter
1712	1714	Extend
1720	1731	OLetter
1732	1734	Extend
1735	1736	STerm
1740	1751	OLetter
1752	1753	Extend
1760	176C	OLetter
176E	1770	OLetter
1772	1773	Extend
1780	17B3	OLetter
17B4	17D3	Extend
17D7		OLetter
17DC		OLetter
17DD		Extend
17E0	17E9	Numeric
1802		SContinue
1803		STerm
1808		SContinue
1809		STerm
180B	180D	Extend
180E		Sp
1810	1819	Numeric
1820	1877	OLetter
1880	18A8	OLetter
18A9		Extend
18AA		OLetter
18B0	18F5	OLetter
1900	191C	OLetter
1920	192B	Extend
1930	193B	Extend
1944	1945	STerm
1946	194F	Numeric
1950	196D	OLetter
1970	1974	OLetter
1980	19AB	OLetter
19B0	19C0	Extend
19C1	19C7	OLetter
19C8	19C9	Extend
19D0	19D9	Numeric
1A00	1A16	OLetter
1A17	1A1B	Extend
1A20	1A54	OLetter
1A55	1A5E	Extend
1A60	1A7C	Extend
1A7F		Extend
1A80	1A89	Numeric
1A90	1A99	Numeric
1AA7		OLetter
1AA8	1AAB	STerm
1B00	1B04	Extend
1B05	1B33	OLetter
1B34	1B44	Extend
1B45	1B4B	OLetter
1B50	1B59	Numeric
1B5A	1B5B	STerm
1B5E	1B5F	STerm
1B6B	1B73	Extend
1B80	1B82	Extend
1B83	1BA0	OLetter
1BA1	1BAD	Extend
1BAE	1BAF	OLetter
1BB0	1BB9	Numeric
1BBA	1BE5	OLetter
1BE6	1BF3	Extend
1C00	1C23	OLetter
1C24	1C37	Extend
1C3B	1C3C	STerm
1C40	1C49	Numeric
1C4D	1C4F	OLetter
1C50	1C59	Numeric
1C5A	1C7D	OLetter
1C7E	1C7F	STerm
1CD0	1CD2	Extend
1CD4	1CE8	Extend
1CE9	1CEC	OLetter
1CED		Extend
1CEE	1CF1	OLetter
1CF2	1CF4	Extend
1CF5	1CF6	OLetter
1D00	1DBF	Lower
1DC0	1DE6	Extend
1DFC	1DFF	Extend
1E00		Upper
1E01		Lower
1E02		Upper
1E03		Lower
1E04		Upper
1E05		Lower
1E06		Upper
1E07		Lower
1E08		Upper
1E09		Lower
1E0A		Upper
1E0B		Lower
1E0C		Upper
1E0D		Lower
1E0E		Upper
1E0F		Lower
1E10		Upper
1E11		Lower
1E12		Upper
1E13		Lower
1E14		Upper
1E15		Lower
1E16		Upper
1E17		Lower
1E18		Upper
1E19		Lower
1E1A		Upper
1E1B		Lower
1E1C		Upper
1E1D		Lower
1E1E		Upper
1E1F		Lower
1E20		Upper
1E21		Lower
1E22		Upper
1E23		Lower
1E24		Upper
1E25		Lower
1E26		Upper
1E27		Lower
1E28		Upper
1E29		Lower
1E2A		Upper
1E2B		Lower
1E2C		Upper
1E2D		Lower
1E2E		Upper
1E2F		Lower
1E30		Upper
1E31		Lower
1E32		Upper
1E33		Lower
1E34		Upper
1E35		Lower
1E36		Upper
1E37		Lower
1E38		Upper
1E39		Lower
1E3A		Upper
1E3B		Lower
1E3C		Upper
1E3D		Lower
1E3E		Upper
1E3F		Lower
1E40		Upper
1E41		Lower
1E42		Upper
1E43		Lower
1E44		Upper
1E45		Lower
1E46		Upper
1E47		Lower
1E48		Upper
1E49		Lower
1E4A		Upper
1E4B		Lower
1E4C		Upper
1E4D		Lower
1E4E		Upper
1E4F		Lower
1E50		Upper
1E51		Lower
1E52		Upper
1E53		Lower
1E54		Upper
1E55		Lower
1E56		Upper
1E57		Lower
1E58		Upper
1E59		Lower
1E5A		Upper
1E5B		Lower
1E5C		Upper
1E5D		Lower
1E5E		Upper
1E5F		Lower
1E60		Upper
1E61		Lower
1E62		Upper
1E63		Lower
1E64		Upper
1E65		Lower
1E66		Upper
1E67		Lower
1E68		Upper
1E69		Lower
1E6A		Upper
1E6B		Lower
1E6C		Upper
1E6D		Lower
1E6E		Upper
1E6F		Lower
1E70		Upper
1E71		Lower
1E72		Upper
1E73		Lower
1E74		Upper
1E75		Lower
1E76		Upper
1E77		Lower
1E78		Upper
1E79		Lower
1E7A		Upper
1E7B		Lower
1E7C		Upper
1E7D		Lower
1E7E		Upper
1E7F		Lower
1E80		Upper
1E81		Lower
1E82		Upper
1E83		Lower
1E84		Upper
1E85		Lower
1E86		Upper
1E87		Lower
1E88		Upper
1E89		Lower
1E8A		Upper
1E8B		Lower
1E8C		Upper
1E8D		Lower
1E8E		Upper
1E8F		Lower
1E90		Upper
1E91		Lower
1E92		Upper
1E93		Lower
1E94		Upper
1E95	1E9D	Lower
1E9E		Upper
1E9F		Lower
1EA0		Upper
1EA1		Lower
1EA2		Upper
1EA3		Lower
1EA4		Upper
1EA5		Lower
1EA6		Upper
1EA7		Lower
1EA8		Upper
1EA9		Lower
1EAA		Upper
1EAB		Lower
1EAC		Upper
1EAD		Lower
1EAE		Upper
1EAF		Lower
1EB0		Upper
1EB1		Lower
1EB2		Upper
1EB3		Lower
1EB4		Upper
1EB5		Lower
1EB6		Upper
1EB7		Lower
1EB8		Upper
1EB9		Lower
1EBA		Upper
1EBB		Lower
1EBC		Upper
1EBD		Lower
1EBE		Upper
1EBF		Lower
1EC0		Upper
1EC1		Lower
1EC2		Upper
1EC3		Lower
1EC4		Upper
1EC5		Lower
1EC6		Upper
1EC7		Lower
1EC8		Upper
1EC9		Lower
1ECA		Upper
1ECB		Lower
1ECC		Upper
1ECD		Lower
1ECE		Upper
1ECF		Lower
1ED0		Upper
1ED1		Lower
1ED2		Upper
1ED3		Lower
1ED4		Upper
1ED5		Lower
1ED6		Upper
1ED7		Lower
1ED8		Upper
1ED9		Lower
1EDA		Upper
1EDB		Lower
1EDC		Upper
1EDD		Lower
1EDE		Upper
1EDF		Lower
1EE0		Upper
1EE1		Lower
1EE2		Upper
1EE3		Lower
1EE4		Upper
1EE5		Lower
1EE6		Upper
1EE7		Lower
1EE8		Upper
1EE9		Lower
1EEA		Upper
1EEB		Lower
1EEC		Upper
1EED		Lower
1EEE		Upper
1EEF		Lower
1EF0		Upper
1EF1		Lower
1EF2		Upper
1EF3		Lower
1EF4		Upper
1EF5		Lower
1EF6		Upper
1EF7		Lower
1EF8		Upper
1EF9		Lower
1EFA		Upper
1EFB		Lower
1EFC		Upper
1EFD		Lower
1EFE		Upper
1EFF	1F07	Lower
1F08	1F0F	Upper
1F10	1F15	Lower
1F18	1F1D	Upper
1F20	1F27	Lower
1F28	1F2F	Upper
1F30	1F37	Lower
1F38	1F3F	Upper
1F40	1F45	Lower
1F48	1F4D	Upper
1F50	1F57	Lower
1F59		Upper
1F5B		Upper
1F5D		Upper
1F5F		Upper
1F60	1F67	Lower
1F68	1F6F	Upper
1F70	1F7D	Lower
1F80	1F87	Lower
1F88	1F8F	Upper
1F90	1F97	Lower
1F98	1F9F	Upper
1FA0	1FA7	Lower
1FA8	1FAF	Upper
1FB0	1FB4	Lower
1FB6	1FB7	Lower
1FB8	1FBC	Upper
1FBE		Lower
1FC2	1FC4	Lower
1FC6	1FC7	Lower
1FC8	1FCC	Upper
1FD0	1FD3	Lower
1FD6	1FD7	Lower
1FD8	1FDB	Upper
1FE0	1FE7	Lower
1FE8	1FEC	Upper
1FF2	1FF4	Lower
1FF6	1FF7	Lower
1FF8	1FFC	Upper
2000	200A	Sp
200B		Format
200C	200D	Extend
200E	200F	Format
2013	2014	SContinue
2018	201F	Close
2024		ATerm
2028	2029	Sep
202A	202E	Format
202F		Sp
2039	203A	Close
203C	203D	STerm
2045	2046	Close
2047	2049	STerm
205F		Sp
2060	2064	Format
206A	206F	Format
2071		Lower
207D	207E	Close
207F		Lower
208D	208E	Close
2090	209C	Lower
20D0	20F0	Extend
2102		Upper
2107		Upper
210A		Lower
210B	210D	Upper
210E	210F	Lower
2110	2112	Upper
2113		Lower
2115		Upper
2119	211D	Upper
2124		Upper
2126		Upper
2128		Upper
212A	212D	Upper
212F		Lower
2130	2133	Upper
2134		Lower
2135	2138	OLetter
2139		Lower
213C	213D	Lower
213E	213F	Upper
2145		Upper
2146	2149	Lower
214E		Lower
2160	216F	Upper
2170	217F	Lower
2180	2182	OLetter
2183		Upper
2184		Lower
2185	2188	OLetter
2329	232A	Close
24B6	24CF	Upper
24D0	24E9	Lower
275B	275E	Close
2768	2775	Close
27C5	27C6	Close
27E6	27EF	Close
2983	2998	Close
29D8	29DB	Close
29FC	29FD	Close
2C00	2C2E	Upper
2C30	2C5E	Lower
2C60		Upper
2C61		Lower
2C62	2C64	Upper
2C65	2C66	Lower
2C67		Upper
2C68		Lower
2C69		Upper
2C6A		Lower
2C6B		Upper
2C6C		Lower
2C6D	2C70	Upper
2C71		Lower
2C72		Upper
2C73	2C74	Lower
2C75		Upper
2C76	2C7D	Lower
2C7E	2C80	Upper
2C81		Lower
2C82		Upper
2C83		Lower
2C84		Upper
2C85		Lower
2C86		Upper
2C87		Lower
2C88		Upper
2C89		Lower
2C8A		Upper
2C8B		Lower
2C8C		Upper
2C8D		Lower
2C8E		Upper
2C8F		Lower
2C90		Upper
2C91		Lower
2C92		Upper
2C93		Lower
2C94		Upper
2C95		Lower
2C96		Upper
2C97		Lower
2C98		Upper
2C99		Lower
2C9A		Upper
2C9B		Lower
2C9C		Upper
2C9D		Lower
2C9E		Upper
2C9F		Lower
2CA0		Upper
2CA1		Lower
2CA2		Upper
2CA3		Lower
2CA4		Upper
2CA5		Lower
2CA6		Upper
2CA7		Lower
2CA8		Upper
2CA9		Lower
2CAA		Upper
2CAB		Lower
2CAC		Upper
2CAD		Lower
2CAE		Upper
2CAF		Lower
2CB0		Upper
2CB1		Lower
2CB2		Upper
2CB3		Lower
2CB4		Upper
2CB5		Lower
2CB6		Upper
2CB7		Lower
2CB8		Upper
2CB9		Lower
2CBA		Upper
2CBB		Lower
2CBC		Upper
2CBD		Lower
2CBE		Upper
2CBF		Lower
2CC0		Upper
2CC1		Lower
2CC2		Upper
2CC3		Lower
2CC4		Upper
2CC5		Lower
2CC6		Upper
2CC7		Lower
2CC8		Upper
2CC9		Lower
2CCA		Upper
2CCB		Lower
2CCC		Upper
2CCD		Lower
2CCE		Upper
2CCF		Lower
2CD0		Upper
2CD1		Lower
2CD2		Upper
2CD3		Lower
2CD4		Upper
2CD5		Lower
2CD6		Upper
2CD7		Lower
2CD8		Upper
2CD9		Lower
2CDA		Upper
2CDB		Lower
2CDC		Upper
2CDD		Lower
2CDE		Upper
2CDF		Lower
2CE0		Upper
2CE1		Lower
2CE2		Upper
2CE3	2CE4	Lower
2CEB		Upper
2CEC		Lower
2CED		Upper
2CEE		Lower
2CEF	2CF1	Extend
2CF2		Upper
2CF3		Lower
2D00	2D25	Lower
2D27		Lower
2D2D		Lower
2D30	2D67	OLetter
2D6F		OLetter
2D7F		Extend
2D80	2D96	OLetter
2DA0	2DA6	OLetter
2DA8	2DAE	OLetter
2DB0	2DB6	OLetter
2DB8	2DBE	OLetter
2DC0	2DC6	OLetter
2DC8	2DCE	OLetter
2DD0	2DD6	OLetter
2DD8	2DDE	OLetter
2DE0	2DFF	Extend
2E00	2E0D	Close
2E1C	2E1D	Close
2E20	2E29	Close
2E2E		STerm
2E2F		OLetter
3000		Sp
3001		SContinue
3002		STerm
3005	3007	OLetter
3008	3011	Close
3014	301B	Close
301D	301F	Close
3021	3029	OLetter
302A	302F	Extend
3031	3035	OLetter
3038	303C	OLetter
3041	3096	OLetter
3099	309A	Extend
309D	309F	OLetter
30A1	30FA	OLetter
30FC	30FF	OLetter
3105	312D	OLetter
3131	318E	OLetter
31A0	31BA	OLetter
31F0	31FF	OLetter
3400	4DB5	OLetter
4E00	9FCC	OLetter
A000	A48C	OLetter
A4D0	A4FD	OLetter
A4FF		STerm
A500	A60C	OLetter
A60E	A60F	STerm
A610	A61F	OLetter
A620	A629	Numeric
A62A	A62B	OLetter
A640		Upper
A641		Lower
A642		Upper
A643		Lower
A644		Upper
A645		Lower
A646		Upper
A647		Lower
A648		Upper
A649		Lower
A64A		Upper
A64B		Lower
A64C		Upper
A64D		Lower
A64E		Upper
A64F		Lower
A650		Upper
A651		Lower
A652		Upper
A653		Lower
A654		Upper
A655		Lower
A656		Upper
A657		Lower
A658		Upper
A659		Lower
A65A		Upper
A65B		Lower
A65C		Upper
A65D		Lower
A65E		Upper
A65F		Lower
A660		Upper
A661		Lower
A662		Upper
A663		Lower
A664		Upper
A665		Lower
A666		Upper
A667		Lower
A668		Upper
A669		Lower
A66A		Upper
A66B		Lower
A66C		Upper
A66D		Lower
A66E		OLetter
A66F	A672	Extend
A674	A67D	Extend
A67F		OLetter
A680		Upper
A681		Lower
A682		Upper
A683		Lower
A684		Upper
A685		Lower
A686		Upper
A687		Lower
A688		Upper
A689		Lower
A68A		Upper
A68B		Lower
A68C		Upper
A68D		Lower
A68E		Upper
A68F		Lower
A690		Upper
A691		Lower
A692		Upper
A693		Lower
A694		Upper
A695		Lower
A696		Upper
A697		Lower
A69F		Extend
A6A0	A6EF	OLetter
A6F0	A6F1	Extend
A6F3		STerm
A6F7		STerm
A717	A71F	OLetter
A722		Upper
A723		Lower
A724		Upper
A725		Lower
A726		Upper
A727		Lower
A728		Upper
A729		Lower
A72A		Upper
A72B		Lower
A72C		Upper
A72D		Lower
A72E		Upper
A72F	A731	Lower
A732		Upper
A733		Lower
A734		Upper
A735		Lower
A736		Upper
A737		Lower
A738		Upper
A739		Lower
A73A		Upper
A73B		Lower
A73C		Upper
A73D		Lower
A73E		Upper
A73F		Lower
A740		Upper
A741		Lower
A742		Upper
A743		Lower
A744		Upper
A745		Lower
A746		Upper
A747		Lower
A748		Upper
A749		Lower
A74A		Upper
A74B		Lower
A74C		Upper
A74D		Lower
A74E		Upper
A74F		Lower
A750		Upper
A751		Lower
A752		Upper
A753		Lower
A754		Upper
A755		Lower
A756		Upper
A757		Lower
A758		Upper
A759		Lower
A75A		Upper
A75B		Lower
A75C		Upper
A75D		Lower
A75E		Upper
A75F		Lower
A760		Upper
A761		Lower
A762		Upper
A763		Lower
A764		Upper
A765		Lower
A766		Upper
A767		Lower
A768		Upper
A769		Lower
A76A		Upper
A76B		Lower
A76C		Upper
A76D		Lower
A76E		Upper
A76F	A778	Lower
A779		Upper
A77A		Lower
A77B		Upper
A77C		Lower
A77D	A77E	Upper
A77F		Lower
A780		Upper
A781		Lower
A782		Upper
A783		Lower
A784		Upper
A785		Lower
A786		Upper
A787		Lower
A788		OLetter
A78B		Upper
A78C		Lower
A78D		Upper
A78E		Lower
A790		Upper
A791		Lower
A792		Upper
A793		Lower
A7A0		Upper
A7A1		Lower
A7A2		Upper
A7A3		Lower
A7A4		Upper
A7A5		Lower
A7A6		Upper
A7A7		Lower
A7A8		Upper
A7A9		Lower
A7AA		Upper
A7F8	A7FA	Lower
A7FB	A801	OLetter
A802		Extend
A803	A805	OLetter
A806		Extend
A807	A80A	OLetter
A80B		Extend
A80C	A822	OLetter
A823	A827	Extend
A840	A873	OLetter
A876	A877	STerm
A880	A881	Extend
A882	A8B3	OLetter
A8B4	A8C4	Extend
A8CE	A8CF	STerm
A8D0	A8D9	Numeric
A8E0	A8F1	Extend
A8F2	A8F7	OLetter
A8FB		OLetter
A900	A909	Numeric
A90A	A925	OLetter
A926	A92D	Extend
A92F		STerm
A930	A946	OLetter
A947	A953	Extend
A960	A97C	OLetter
A980	A983	Extend
A984	A9B2	OLetter
A9B3	A9C0	Extend
A9C8	A9C9	STerm
A9CF		OLetter
A9D0	A9D9	Numeric
AA00	AA28	OLetter
AA29	AA36	Extend
AA40	AA42	OLetter
AA43		Extend
AA44	AA4B	OLetter
AA4C	AA4D	Extend
AA50	AA59	Numeric
AA5D	AA5F	STerm
AA60	AA76	OLetter
AA7A		OLetter
AA7B		Extend
AA80	AAAF	OLetter
AAB0		Extend
AAB1		OLetter
AAB2	AAB4	Extend
AAB5	AAB6	OLetter
AAB7	AAB8	Extend
AAB9	AABD	OLetter
AABE	AABF	Extend
AAC0		OLetter
AAC1		Extend
AAC2		OLetter
AADB	AADD	OLetter
AAE0	AAEA	OLetter
AAEB	AAEF	Extend
AAF0	AAF1	STerm
AAF2	AAF4	OLetter
AAF5	AAF6	Extend
AB01	AB06	OLetter
AB09	AB0E	OLetter
AB11	AB16	OLetter
AB20	AB26	OLetter
AB28	AB2E	OLetter
ABC0	ABE2	OLetter
ABE3	ABEA	Extend
ABEB		STerm
ABEC	ABED	Extend
ABF0	ABF9	Numeric
AC00	D7A3	OLetter
D7B0	D7C6	OLetter
D7CB	D7FB	OLetter
F900	FA6D	OLetter
FA70	FAD9	OLetter
FB00	FB06	Lower
FB13	FB17	Lower
FB1D		OLetter
FB1E		Extend
FB1F	FB28	OLetter
FB2A	FB36	OLetter
FB38	FB3C	OLetter
FB3E		OLetter
FB40	FB41	OLetter
FB43	FB44	OLetter
FB46	FBB1	OLetter
FBD3	FD3D	OLetter
FD3E	FD3F	Close
FD50	FD8F	OLetter
FD92	FDC7	OLetter
FDF0	FDFB	OLetter
FE00	FE0F	Extend
FE10	FE11	SContinue
FE13		SContinue
FE17	FE18	Close
FE20	FE26	Extend
FE31	FE32	SContinue
FE35	FE44	Close
FE47	FE48	Close
FE50	FE51	SContinue
FE52		ATerm
FE55		SContinue
FE56	FE57	STerm
FE58		SContinue
FE59	FE5E	Close
FE63		SContinue
FE70	FE74	OLetter
FE76	FEFC	OLetter
FEFF		Format
FF01		STerm
FF08	FF09	Close
FF0C	FF0D	SContinue
FF0E		ATerm
FF1A		SContinue
FF1F		STerm
FF21	FF3A	Upper
FF3B		Close
FF3D		Close
FF41	FF5A	Lower
FF5B		Close
FF5D		Close
FF5F	FF60	Close
FF61		STerm
FF62	FF63	Close
FF64		SContinue
FF66	FF9D	OLetter
FF9E	FF9F	Extend
FFA0	FFBE	OLetter
FFC2	FFC7	OLetter
FFCA	FFCF	OLetter
FFD2	FFD7	OLetter
FFDA	FFDC	OLetter
FFF9	FFFB	Format
10000	1000B	OLetter
1000D	10026	OLetter
10028	1003A	OLetter
1003C	1003D	OLetter
1003F	1004D	OLetter
10050	1005D	OLetter
10080	100FA	OLetter
10140	10174	OLetter
101FD		Extend
10280	1029C	OLetter
102A0	102D0	OLetter
10300	1031E	OLetter
10330	1034A	OLetter
10380	1039D	OLetter
103A0	103C3	OLetter
103C8	103CF	OLetter
103D1	103D5	OLetter
10400	10427	Upper
10428	1044F	Lower
10450	1049D	OLetter
104A0	104A9	Numeric
10800	10805	OLetter
10808		OLetter
1080A	10835	OLetter
10837	10838	OLetter
1083C		OLetter
1083F	10855	OLetter
10900	10915	OLetter
10920	10939	OLetter
10980	109B7	OLetter
109BE	109BF	OLetter
10A00		OLetter
10A01	10A03	Extend
10A05	10A06	Extend
10A0C	10A0F	Extend
10A10	10A13	OLetter
10A15	10A17	OLetter
10A19	10A33	OLetter
10A38	10A3A	Extend
10A3F		Extend
10A56	10A57	STerm
10A60	10A7C	OLetter
10B00	10B35	OLetter
10B40	10B55	OLetter
10B60	10B72	OLetter
10C00	10C48	OLetter
11000	11002	Extend
11003	11037	OLetter
11038	11046	Extend
11047	11048	STerm
11066	1106F	Numeric
11080	11082	Extend
11083	110AF	OLetter
110B0	110BA	Extend
110BD		Format
110BE	110C1	STerm
110D0	110E8	OLetter
110F0	110F9	Numeric
11100	11102	Extend
11103	11126	OLetter
11127	11134	Extend
11136	1113F	Numeric
11141	11143	STerm
11180	11182	Extend
11183	111B2	OLetter
111B3	111C0	Extend
111C1	111C4	OLetter
111C5	111C6	STerm
111D0	111D9	Numeric
11680	116AA	OLetter
116AB	116B7	Extend
116C0	116C9	Numeric
12000	1236E	OLetter
12400	12462	OLetter
13000	1342E	OLetter
16800	16A38	OLetter
16F00	16F44	OLetter
16F50		OLetter
16F51	16F7E	Extend
16F8F	16F92	Extend
16F93	16F9F	OLetter
1B000	1B001	OLetter
1D165	1D169	Extend
1D16D	1D172	Extend
1D173	1D17A	Format
1D17B	1D182	Extend
1D185	1D18B	Extend
1D1AA	1D1AD	Extend
1D242	1D244	Extend
1D400	1D419	Upper
1D41A	1D433	Lower
1D434	1D44D	Upper
1D44E	1D454	Lower
1D456	1D467	Lower
1D468	1D481	Upper
1D482	1D49B	Lower
1D49C		Upper
1D49E	1D49F	Upper
1D4A2		Upper
1D4A5	1D4A6	Upper
1D4A9	1D4AC	Upper
1D4AE	1D4B5	Upper
1D4B6	1D4B9	Lower
1D4BB		Lower
1D4BD	1D4C3	Lower
1D4C5	1D4CF	Lower
1D4D0	1D4E9	Upper
1D4EA	1D503	Lower
1D504	1D505	Upper
1D507	1D50A	Upper
1D50D	1D514	Upper
1D516	1D51C	Upper
1D51E	1D537	Lower
1D538	1D539	Upper
1D53B	1D53E	Upper
1D540	1D544	Upper
1D546		Upper
1D54A	1D550	Upper
1D552	1D56B	Lower
1D56C	1D585	Upper
1D586	1D59F	Lower
1D5A0	1D5B9	Upper
1D5BA	1D5D3	Lower
1D5D4	1D5ED	Upper
1D5EE	1D607	Lower
1D608	1D621	Upper
1D622	1D63B	Lower
1D63C	1D655	Upper
1D656	1D66F	Lower
1D670	1D689	Upper
1D68A	1D6A5	Lower
1D6A8	1D6C0	Upper
1D6C2	1D6DA	Lower
1D6DC	1D6E1	Lower
1D6E2	1D6FA	Upper
1D6FC	1D714	Lower
1D716	1D71B	Lower
1D71C	1D734	Upper
1D736	1D74E	Lower
1D750	1D755	Lower
1D756	1D76E	Upper
1D770	1D788	Lower
1D78A	1D78F	Lower
1D790	1D7A8	Upper
1D7AA	1D7C2	Lower
1D7C4	1D7C9	Lower
1D7CA		Upper
1D7CB		Lower
1D7CE	1D7FF	Numeric
1EE00	1EE03	OLetter
1EE05	1EE1F	OLetter
1EE21	1EE22	OLetter
1EE24		OLetter
1EE27		OLetter
1EE29	1EE32	OLetter
1EE34	1EE37	OLetter
1EE39		OLetter
1EE3B		OLetter
1EE42		OLetter
1EE47		OLetter
1EE49		OLetter
1EE4B		OLetter
1EE4D	1EE4F	OLetter
1EE51	1EE52	OLetter
1EE54		OLetter
1EE57		OLetter
1EE59		OLetter
1EE5B		OLetter
1EE5D		OLetter
1EE5F		OLetter
1EE61	1EE62	OLetter
1EE64		OLetter
1EE67	1EE6A	OLetter
1EE6C	1EE72	OLetter
1EE74	1EE77	OLetter
1EE79	1EE7C	OLetter
1EE7E		OLetter
1EE80	1EE89	OLetter
1EE8B	1EE9B	OLetter
1EEA1	1EEA3	OLetter
1EEA5	1EEA9	OLetter
1EEAB	1EEBB	OLetter
20000	2A6D6	OLetter
2A700	2B734	OLetter
2B740	2B81D	OLetter
2F800	2FA1D	OLetter
E0001		Format
E0020	E007F	Format
E0100	E01EF	Extend
END
