#! /usr/bin/perl

# ex:ts=8 sw=4:
# $OpenBSD: pkg_add,v 1.120 2004/11/14 12:54:30 espie Exp $
#
# Copyright (c) 2003-2004 Marc Espie <espie@openbsd.org>
#
# Permission to use, copy, modify, and distribute this software for any
# purpose with or without fee is hereby granted, provided that the above
# copyright notice and this permission notice appear in all copies.
#
# THE SOFTWARE IS PROVIDED "AS IS" AND THE AUTHOR DISCLAIMS ALL WARRANTIES
# WITH REGARD TO THIS SOFTWARE INCLUDING ALL IMPLIED WARRANTIES OF
# MERCHANTABILITY AND FITNESS. IN NO EVENT SHALL THE AUTHOR BE LIABLE FOR
# ANY SPECIAL, DIRECT, INDIRECT, OR CONSEQUENTIAL DAMAGES OR ANY DAMAGES
# WHATSOEVER RESULTING FROM LOSS OF USE, DATA OR PROFITS, WHETHER IN AN
# ACTION OF CONTRACT, NEGLIGENCE OR OTHER TORTIOUS ACTION, ARISING OUT OF
# OR IN CONNECTION WITH THE USE OR PERFORMANCE OF THIS SOFTWARE.

# this is it ! The hard one
use strict;
use warnings;
use OpenBSD::PackingList;
use OpenBSD::PackageInfo;
use OpenBSD::PackageLocator;
use OpenBSD::PackageName;
use OpenBSD::PkgCfl;
use OpenBSD::PkgSpec;
use OpenBSD::Vstat;
use OpenBSD::Getopt;
use OpenBSD::Error;
use OpenBSD::ProgressMeter;
use OpenBSD::Add;

our %forced = ();

package main;

sub fill_conflict_lists
{
	my $state = shift;
	# first, find all possible potential conflicts
	for my $pkg (installed_packages()) {
		my $plist = OpenBSD::PackingList->from_installation($pkg, 
		    \&OpenBSD::PackingList::ConflictOnly);
		next unless defined $plist;
		$state->{conflict_list}->{$plist->pkgname()} = 
		    OpenBSD::PkgCfl->make_conflict_list($plist);
	}
}

my $errors = 0;

sub find_conflicts($$)
{
	my ($pkgname, $state) = @_;
	my @bad = ();
	if (is_installed $pkgname) {
		push(@bad, $pkgname);
	}
	while (my ($name, $l) = each %{$state->{conflict_list}}) {
		next if $name eq $pkgname;
		if ($l->conflicts_with($pkgname)) {
			push(@bad, $name);
		}
	}
	return @bad;
}

sub can_install($$)
{
	my ($pkgname, $state) = @_;

	my @l = find_conflicts($pkgname, $state);

	return 1 if @l == 0;
	if (!$state->{replace} || @l >= 2) {
		print "Can't install $pkgname because of conflicts (",join(',', @l), ")\n";
		$errors++;
		return undef;
	}

	require OpenBSD::Update;

	my $plist = OpenBSD::Update::can_do($l[0], $pkgname, $state);
	if ($plist) {
		$plist->{dir} = installed_info($l[0]);
		return $plist;
	} else {
		print "Can't update $l[0] into $pkgname\n";
		$errors++;
		return undef;
	}
}


# This does pre_add a package: finding it and reading its package information
sub pre_add($$)
{
	my ($pkg, $state) = @_;
	my $pkgname1;
	my $toreplace;
	
	if ($pkg ne '-') {
		if ($state->{verbose}) {
			if (defined $state->{deptree}->{$pkg}) {
			    print $state->{deptree}->{$pkg},":";
			}
			print "parsing $pkg\n";
		}
		$pkgname1 = OpenBSD::PackageName::url2pkgname($pkg);
		$toreplace = can_install($pkgname1, $state);
		return undef unless $toreplace;
	}

	my $handle = OpenBSD::PackageLocator->find($pkg);
	if (!$handle) {
		print "Can't find $pkg\n";
		$errors++;
		return undef;
	}
	my $dir = $handle->info();
    	my $plist = $handle->{plist} = 
	    OpenBSD::PackingList->fromfile($dir.CONTENTS);
	unless (defined $plist) {
		print "Can't find CONTENTS from $pkg\n";
		$errors++;
		return undef;
	}
	if ($plist->pkgbase() ne $state->{localbase}) {
		print "Localbase mismatch: package has: ", $plist->pkgbase(), " , user wants: ", $state->{localbase}, "\n";
		$errors++;
		return undef;
	}
	my $pkgname = $plist->pkgname();
	if (defined $pkgname1) {
		if ($pkgname ne $pkgname1) {
			print "Package name is not consistent ???\n";
			$errors++;
			return undef;
		}
	} else {
		if ($state->{verbose}) {
			if (defined $state->{deptree}->{$pkg}) {
			    print $state->{deptree}->{$pkg},":";
			}
			print "parsing $pkgname\n";
		}
		$toreplace = can_install($pkgname, $state);
		return undef unless $toreplace;
	}
	my $avoid = '';
	if ($toreplace ne '1') {
		$plist->{replacing} = $toreplace;
		$avoid = $toreplace->pkgname();

		require OpenBSD::Update;

		if (!OpenBSD::Update::is_safe($plist, $state)) {
			print "Can't safely update $avoid to $pkgname\n";
			$errors++;
		}
	}
	# second handling of conflicts
	my $l = OpenBSD::PkgCfl->make_conflict_list($plist);
	$handle->{conflicts} = $l;
	if ($l->conflicts_with(grep {$_ ne $avoid} installed_packages())) {
		print "package $pkg has conflicts: ", 
		    join(' ', $l->conflicts_with(installed_packages())), "\n";
		$errors++;
		return undef unless $forced{conflicts};
	}
	return $handle;
}


sub solve_dependencies
{
	my ($verbose, $handle, @extra) = @_;
	my $plist = $handle->{plist};
	my $to_register = $handle->{solved_dependencies} = [];
	my $to_install;

	# do simple old style pkgdep first
	my @deps = ();
	for my $dep (@{$plist->{pkgdep}}) {
		if (!is_installed($dep->{name})) {
			push(@deps, $dep->{name});
		}
		push(@$to_register, $dep->{name});
	}
	for my $dep (@{$plist->{newdepend}}, @{$plist->{libdepend}}) {
	    next if defined $dep->{name} and $dep->{name} ne $plist->pkgname();
	    my @candidates = OpenBSD::PkgSpec::match($dep->{pattern}, installed_packages());
	    if (@candidates >= 1) {
		    push(@$to_register, $candidates[0]);
	    } else {
	    	if (!defined $to_install) {
			$to_install = {};
			for my $fullname (@extra) {
			    $to_install->{OpenBSD::PackageName::url2pkgname($fullname)} = $fullname;
			}
		}
	    	# try against list of packages to install
	    	my @candidates = OpenBSD::PkgSpec::match($dep->{pattern}, keys %{$to_install});
		if (@candidates >= 1) {
		    push(@deps, $to_install->{$candidates[0]});
		    push(@$to_register, $candidates[0]);
		} else {
		    # try with list of packages
		    my @candidates = OpenBSD::PkgSpec::match($dep->{pattern}, OpenBSD::PackageLocator::available());
		    # one single choice
		    if (@candidates == 1) {
			push(@deps, $candidates[0]);
			push(@$to_register, $candidates[0]);
		    } elsif (@candidates > 1) {
			# grab default if available
		    	if (grep {$_ eq $dep->{def}} @candidates) {
			    push(@deps, $dep->{def});
			    push(@$to_register, $dep->{def});
			# grab first one otherwise
			} else {
			    push(@deps, $candidates[0]);
			    push(@$to_register, $candidates[0]);
			}
		    } else {
			# can't get a list of packages, assume default
			# will be there.
			push(@deps, $dep->{def});
			push(@$to_register, $dep->{def});
		    }
		}
	    }
	}

	if ($verbose && @{$to_register} > 0) {
	    print "Dependencies for ", $plist->pkgname(), " resolve to: ", 
	    	join(',', @$to_register);
	    print " (todo: ", join(',', @deps), ")" if @deps > 0;
	    print "\n";
	}
	return @deps;
}

sub check_lib_specs
{
	my ($verbose, $base, $specs, $available) = @_;
	my $dir;
	for my $spec (split(/,/, $specs)) {
		print "checking libspec $spec " if $verbose;
		if ($spec =~ m|(.*)/|) {
			$dir = "$base/$1";
			$spec = $';
		} else {
			$dir = "$base/lib";
		}
		if ($spec =~ m/^(.*)\.(\d+)\.(\d+)$/) {
			my ($libname, $major, $minor) = ($1, $2, $3);
			my $exists = $available->{"$dir/lib$libname.so.$major"};
			if ((defined $exists) && $exists >= $minor) {
				print "found $dir/lib$libname.so.$major.$exists\n" if $verbose;
			} else {
				print "not found\n" if $verbose;
				return undef;
			}
		} else {
			print "bad spec\n" if $verbose;
			return undef;
		}
	}
	return 1;
}

sub do_script
{
	my ($plist, $name, $state, $args) = @_;
	$state->{dir} = $plist->{dir};
	return unless $plist->has($name);
	$plist->get($name)->run($state, $args);
}


sub really_add($$)
{
	my ($handle, $state) = @_;
	my $destdir = $state->{destdir};
	my $not = $state->{not};
	my $plist = $handle->{plist};
	my $dir = $handle->info();
	my $pkgname = $plist->pkgname();
	$state->{archive} = $handle;
	$plist->{dir} = $dir;
	$state->set_pkgname($pkgname);
	if (defined $plist->{replacing}) {
		$state->{replacing} = 1;
	} else {
		$state->{replacing} = 0;
	}

	my $header = $pkgname;

	if (defined $state->{deptree}->{$pkgname}) {
	    $header = $state->{deptree}->{$pkgname}.":".$header;
	}
	if (defined $plist->{replacing}) {
		$header.=" (replacing ". $plist->{replacing}->pkgname(). ")";
	}
	if (!OpenBSD::ProgressMeter::set_header($header)) {
	    print $state->{not} ? "Pretending to add " : "Adding ";
	    print $header;
	    if ($state->{do_faked}) {
		    print " under ", $state->{destdir};
	    }
	    print "\n";
	}
	my $totsize = OpenBSD::Add::validate_plist($plist, $state);

	if (!defined $handle) {
		Fatal "Archive in $pkgname broken";
	}

	$ENV{'PKG_PREFIX'} = $plist->pkgbase();

	my $interrupted;
	local $SIG{'INT'} = sub {
		$interrupted = 1;
	};

	if (defined $plist->{replacing}) {
		require OpenBSD::Update;

		OpenBSD::ProgressMeter::set_header("$pkgname (extracting)");
		OpenBSD::Update::save_old_libraries($plist, $state);
		my $donesize = 0;
		$plist->{done} = [];
		for my $item (@{$plist->{items}}) {
			eval { $item->extract($state); };
			if ($@) {
				Warn $@;
				$errors++;
				last;
			}
			push(@{$plist->{done}}, $item);
			if (defined $item->{size}) {
				$donesize += $item->{size};
				OpenBSD::ProgressMeter::show($donesize, $totsize);
			}
			last if $interrupted;
		}
		OpenBSD::ProgressMeter::next();
		if ($interrupted || $errors) {
			if ($not) {
				Fatal "Installation of $pkgname failed";
		    	} else {
				OpenBSD::Add::borked_installation($plist, $dir);
			}
		}

		OpenBSD::ProgressMeter::set_header($plist->{replacing}->pkgname()." (deleting)");
		$state->set_pkgname($plist->{replacing}->pkgname());
		require OpenBSD::Delete;
		OpenBSD::Delete::delete_plist($plist->{replacing}, $state);
		delete_installed($plist->{replacing}->pkgname());

		OpenBSD::ProgressMeter::set_header("$pkgname (installing)");
		$state->set_pkgname($pkgname);
	}

	do_script($plist, REQUIRE, $state, "INSTALL");

	do_script($plist, INSTALL, $state, "PRE-INSTALL");

	$plist->{done} = [];
	my $donesize = 0;
	$state->{end_faked} = 0;
	for my $item (@{$plist->{groups}}, @{$plist->{users}}, @{$plist->{items}}) {
		eval { $item->install($state); };
		if ($@) {
			Warn $@;
			$errors++;
			last;
		}
		push(@{$plist->{done}}, $item);
		if (defined $item->{size}) {
                        $donesize += $item->{size};
                        OpenBSD::ProgressMeter::show($donesize, $totsize);
                }

		last if $interrupted;
		# stop faked installation there...
		if ($state->{do_faked} && $state->{end_faked}) {
			last;
		}
	}

	$handle->close();
	OpenBSD::ProgressMeter::next();

	if (!($interrupted || $errors)) {
		eval { do_script($plist, INSTALL, $state, "POST-INSTALL") };
		if ($@) {
			Warn $@;
			$errors++;
		}
	}

	unlink($dir.CONTENTS);
	if ($interrupted || $errors) {
		if ($not) {
			Fatal "Installation of $pkgname failed";
		} else {
			OpenBSD::Add::borked_installation($plist, $dir);
		}
	}
	if ($not) {
		$plist->to_cache();
	} else {
		my $dest = installed_info($pkgname);
		OpenBSD::Add::register_installation($dir, $dest, $plist);
		if (!$state->{replace}) {
			$plist->forget();
		}
		if (defined $handle->{solved_dependencies}) {
			require OpenBSD::RequiredBy;

			for my $dep (@{$handle->{solved_dependencies}}) {
				OpenBSD::RequiredBy->new($dep)->add($pkgname);
			}
		}
	}
	add_installed($pkgname);
	if ($plist->has(DISPLAY)) {
		$plist->get(DISPLAY)->prepare($state);
	}
	# and add dependencies corresponding to the replacement
	if (defined $plist->{replacing}) {
		require OpenBSD::RequiredBy;
		require OpenBSD::Update;

		print "Adjusting dependencies for $pkgname\n" 
		    if $state->{beverbose};
		my $d = OpenBSD::RequiredBy->new($pkgname);
		for my $dep (@{$plist->{replacing}->{wantlist}}) {
			print "\t$dep\n" if $state->{beverbose};
			$d->add($dep) unless $state->{not};
			OpenBSD::Update::adjust_dependency($dep, $plist->{replacing}->pkgname(), $pkgname) unless $state->{not};
		}
	}
}

# one-level dependencies tree, for nicer printouts
sub build_deptree
{
	my ($state, $pkg, @deps) = @_;

	my $tree = $state->{deptree};
	$pkg = OpenBSD::PackageName::url2pkgname($pkg);
	# flatten info
	if (defined $tree->{$pkg}) {
		$pkg = $tree->{$pkg};
	}
	for my $i (@deps) {
		$tree->{$i} = $pkg unless defined $tree->{$i};
	}
}

sub find_old_lib
{
	my ($state, $dep, $global_avail, $dependencies) = @_;

	my $pattern = ".libs-".$dep->{pattern};
	for my $try (OpenBSD::PkgSpec::match($pattern, installed_packages())) {
		my $plist = OpenBSD::PackingList->from_installation($try,
			\&OpenBSD::PackingList::LibraryOnly);
		my $available = {};
		$plist->visit('available_lib', $available);
		if (check_lib_specs($state->{very_verbose},
		    $state->{destdir}.$plist->pkgbase(), $dep->{libspec},
		    $available)) {
			Warn "Found libspec ", $dep->{libspec}, " in old package $try\n";
			$plist->visit('available_lib', $global_avail);
			push(@$dependencies, $try);
			return 1;
		}
	}
	return 0;
}

sub install_package
{
	my ($pkg, $state, @todo) = @_;
	my $cache = $state->{cache};

	if (!defined $cache->{$pkg}) {
		$cache->{$pkg} = pre_add($pkg, $state);
	}

	my $handle = $cache->{$pkg};
	if ($errors > 0) {
		Fatal "Fatal error" unless defined $handle;
	} else {
		return () unless defined $handle;
	}

	my $plist = $handle->{plist};

	if (is_installed($plist->pkgname()) && !$state->{forced}->{installed}) {
		$handle->close();
		return ();
	}
	if ($plist->has('arch')) {
		unless ($plist->{arch}->check($state->{arch})) {
			print "$pkg is not for the right architecture\n";
			return () unless $forced{arch};
		}
	}
	if (!defined $handle->{solved_dependencies}) {
		my @deps = solve_dependencies($state->{verbose}, $handle, @todo);
		if (@deps > 0) {
			build_deptree($state, $pkg, @deps);
			return (@deps, $pkg);
		}
	}

	# verify dependencies and register them

	for my $dep (@{$handle->{solved_dependencies}}) {
		next if is_installed($dep);
		print "Can't install $pkg: can't resolve $dep\n";
		return ();
	}

	# grab libraries
	my $available = {};
	for my $dep (@{$handle->{solved_dependencies}}) {
		my $plist = OpenBSD::PackingList->from_installation($dep, 
			\&OpenBSD::PackingList::LibraryOnly);
		$plist->visit('available_lib', $available);
	}
	for my $dep (@{$plist->{libdepend}}) {
		return () if defined $dep->{name} and $dep->{name} ne $plist->pkgname();
		if (!check_lib_specs($state->{very_verbose}, 
		    $state->{destdir}.$plist->pkgbase(), $dep->{libspec}, $available)) {
		    	# second chance
			if (!find_old_lib($state, $dep, $available, $handle->{solved_dependencies})) {
				Warn "Can't install $pkg: incorrect libspec: ",
				    $dep->{libspec}, "\n";
				return () unless $forced{libdepends};
			}
		}
	}
	for my $dep (@{$handle->{solved_dependencies}}) {
		OpenBSD::PackingElement::PkgDep->add($plist, $dep);
	}
	really_add($handle, $state);
	$state->{conflict_list}->{$plist->pkgname()} = $handle->{conflicts};
	return ();
}

our ($opt_a, $opt_v, $opt_n, $opt_I, $opt_f, $opt_L, $opt_B, $opt_A, $opt_P, $opt_Q, $opt_x, $opt_r, $opt_q, $opt_c);
$opt_v = 0;
getopts('aqcvnrxIL:f:B:A:P:Q:',
	{'v' => sub {++$opt_v;} });
if ($opt_f) {
	%forced = map {($_, 1)} split(/,/, $opt_f);
}
$opt_L = '/usr/local' unless defined $opt_L;

my $state = new OpenBSD::Error;
$state->{cache} = {};
$state->{deptree} = {};
$state->{do_faked} = 0;
$state->{replace} = $opt_r;
$state->{localbase} = $opt_L;
$state->{arch} = $opt_A;
$state->{forced} = \%forced;

if (defined $opt_Q and defined $opt_B) {
	Fatal "-Q and -B are incompatible options";
}
if (defined $opt_Q and defined $opt_r) {
	Fatal "-r and -Q are incompatible options";
}
if ($opt_P) {
	if ($opt_P eq 'cdrom') {
		$state->{cdrom_only} = 1;
	}
	elsif ($opt_P eq 'ftp') { 
		$state->{ftp_only} = 1;
	}
	else {
	    Fatal "bad option: -P $opt_P";
	}
}
if (defined $opt_Q) {
	$state->{destdir} = $opt_Q;
	$state->{do_faked} = 1;
} elsif (defined $opt_B) {
	$state->{destdir} = $opt_B;
} elsif (defined $ENV{'PKG_PREFIX'}) {
	$state->{destdir} = $ENV{'PKG_PREFIX'};
}
if (defined $state->{destdir}) {
	$state->{destdir}.='/';
	$ENV{'PKG_DESTDIR'} = $state->{destdir};
} else {
	$state->{destdir} = '';
}


$state->{conflict_list} = {};
$state->{not} = $opt_n;
$state->{quick} = $opt_q;
$state->{extra} = $opt_c;
$state->{dont_run_scripts} = $opt_I;
$state->{very_verbose} = $opt_v >= 2;
$state->{verbose} = $opt_v;
$state->{beverbose} = $opt_n || ($opt_v >= 2);

if (!$opt_x && !$state->{beverbose}) {
	OpenBSD::ProgressMeter::enable();
}

if ($< && !$forced{nonroot}) {
	if ($state->{not}) {
		Warn "$0 should be run as root\n";
	} else {
		Fatal "$0 must be run as root";
	}
}

fill_conflict_lists($state);
my @todo = (@ARGV);

eval {
while (my $pkg = shift @todo) {
	unshift(@todo, install_package($pkg, $state, @todo));
}
};

my $dielater = $@;

OpenBSD::PackingElement::Fontdir::finish_fontdirs($state);
OpenBSD::Add::manpages_index($state);
OpenBSD::PackingElement::Lib::ensure_ldconfig($state);
# delayed directory/user/group removal
if (defined $state->{dirs_to_rm} or defined $state->{users_to_rm} or
	defined $state->{groups_to_rm}) {
	require OpenBSD::SharedItems;

	OpenBSD::SharedItems::cleanup($state);
}

if ($state->{beverbose}) {
	OpenBSD::Vstat::tally();
}
$state->delayed_output();
if ($dielater) {
	die $dielater;
}
