.\"	$OpenBSD: mailq.8,v 1.10 2010/09/23 14:51:57 jmc Exp $
.\"
.\" Copyright (c) 1998-2000, 2002, 2007 Sendmail, Inc. and its suppliers.
.\"	All rights reserved.
.\" Copyright (c) 1983, 1997 Eric P. Allman.  All rights reserved.
.\" Copyright (c) 1985, 1990, 1993
.\"	The Regents of the University of California.  All rights reserved.
.\"
.\" By using this file, you agree to the terms and conditions set
.\" forth in the LICENSE file which can be found at the top level of
.\" the sendmail distribution.
.\"
.\"
.\"     $Sendmail: mailq.1,v 8.21 2007/03/22 18:21:27 ca Exp $
.\"
.Dd $Mdocdate: September 23 2010 $
.Dt MAILQ 8
.Os
.Sh NAME
.Nm mailq
.Nd print the mail queue
.Sh SYNOPSIS
.Nm mailq
.Op Fl \&Ac
.Op Fl q...
.Op Fl v
.Sh DESCRIPTION
.Nm
prints a summary of the mail messages queued for future delivery.
It may only be run by the superuser.
.Pp
The first line printed for each message
shows the internal identifier used on this host
for the message with a possible status character,
the size of the message in bytes,
the date and time the message was accepted into the queue,
and the envelope sender of the message.
The second line shows the error message that caused this message
to be retained in the queue;
it will not be present if the message is being processed
for the first time.
The status characters are either
.Sq *
to indicate the job is being processed;
.Sq X
to indicate that the load is too high to process the job; and
.Sq -
to indicate that the job is too young to process.
The following lines show message recipients,
one per line.
.Pp
.Nm
is identical to
.Dq Li "sendmail -bp" .
.Pp
The options are as follows:
.Bl -tag -width Ds
.It Fl \&Ac
Show the mail submission queue specified in
.Pa /etc/mail/submit.cf
instead of the MTA queue specified in
.Pa /etc/mail/sendmail.cf .
.It Fl qL
Show the
.Dq lost
items in the mail queue instead of the normal queue items.
.It Fl qQ
Show the quarantined items in the mail queue instead of the normal queue
items.
.It Fl q\fR[\fI!\fR] Ns Cm I Ar substr
Limit processed jobs to those containing
.Ar substr
as a substring of the queue ID or not when
.Sq \&!
is specified.
.It Fl q\fR[\fI!\fR] Ns Cm Q Ar substr
Limit processed jobs to quarantined jobs containing
.Ar substr
as a substring of the quarantine reason or not when
.Sq \&!
is specified.
.It Fl q\fR[\fI!\fR] Ns Cm R Ar substr
Limit processed jobs to those containing
.Ar substr
as a substring of one of the recipients or not when
.Sq \&!
is specified.
.It Fl q\fR[\fI!\fR] Ns Cm S Ar substr
Limit processed jobs to those containing
.Ar substr
as a substring of the sender or not when
.Sq \&!
is specified.
.It Fl v
Print verbose information.
This adds the priority of the message and
a single character indicator (``+'' or blank)
indicating whether a warning message has been sent
on the first line of the message.
Additionally, extra lines may be intermixed with the recipients
indicating the
.Dq controlling user
information;
this shows who will own any programs that are executed
on behalf of this message
and the name of the alias this command expanded from, if any.
Moreover, status messages for each recipient are printed
if available.
.El
.Pp
Several sendmail.cf options influence the behavior of the
.Nm
utility.
The number of items printed per queue group is restricted by
.Li MaxQueueRunSize
if that value is set.
The status character
.Sq *
is not printed for some values of
.Li QueueSortOrder ,
e.g.,
.Ar filename ,
.Ar random ,
.Ar modification ,
and
.Ar none ,
unless a
.Fl q
option is used to limit the processed jobs.
.Sh EXIT STATUS
.Ex -std mailq
.Sh SEE ALSO
.Xr mailer.conf 5 ,
.Xr sendmail 8
.Sh HISTORY
The
.Nm
command appeared in
.Bx 4.0 .
