# !!!!!!!   DO NOT EDIT THIS FILE   !!!!!!!
# This file is machine-generated by lib/unicore/mktables from the Unicode
# database, Version 5.2.0.  Any changes made here will be lost!

# !!!!!!!   INTERNAL PERL USE ONLY   !!!!!!!
# This file is for internal use by the Perl program only.  The format and even
# the name or existence of this file are subject to change without notice.
# Don't use it directly.

# 'D' below means that this form is deprecated.  Consult perluniprops.pod
# 
# This file returns the 3778 code points in Unicode Version 5.2.0 that match
# any of the following regular expression constructs:
# 
# D       \p{Other_Default_Ignorable_Code_Point=Yes}
# D       \p{ODI=Y}
# D       \p{Is_Other_Default_Ignorable_Code_Point=T}
# D       \p{Is_ODI=True}
# 
# D       \p{Other_Default_Ignorable_Code_Point}
# D       \p{Is_Other_Default_Ignorable_Code_Point}
# D       \p{ODI}
# D       \p{Is_ODI}
# 
# perluniprops.pod should be consulted for the syntax rules for any of these,
# including if adding or subtracting white space, underscore, and hyphen
# characters matters or doesn't matter, and other permissible syntactic
# variants.  Upper/lower case distinctions never matter.
# 
# A colon can be substituted for the equals sign, and anything to the left of
# the equals (or colon) can be combined with anything to the right.  Thus,
# for example,
#         \p{Is_ODI: Yes}
# is also valid.
# 
# The format of the lines of this file is: START\tSTOP\twhere START is the
# starting code point of the range, in hex; STOP is the ending point, or if
# omitted, the range has just one code point.  Numbers in comments in
# [brackets] indicate how many code points are in the range.

return <<'END';
034F		
115F	1160	 # [2]
2065	2069	 # [5]
3164		
FFA0		
FFF0	FFF8	 # [9]
E0000		
E0002	E001F	 # [30]
E0080	E00FF	 # [128]
E01F0	E0FFF	 # [3600]
END
