# $OpenBSD: Makefile,v 1.14 2020/03/13 00:31:06 schwarze Exp $

REGRESS_TARGETS = font multiarg noarg parsed punct spacing tag
TAG_TARGETS	= tag
LINT_TARGETS	= punct
HTML_TARGETS	= tag
SKIP_TMAN	= tag

.include <bsd.regress.mk>
