#	$OpenBSD: Makefile,v 1.21 2018/07/09 09:04:33 mpi Exp $

SUBDIR+=	csu
SUBDIR+=	libc
SUBDIR+=	libcrypto
SUBDIR+=	libedit
SUBDIR+=	libevent
SUBDIR+=	libexpat
SUBDIR+=	libfuse
SUBDIR+=	libm
SUBDIR+=	libpthread
SUBDIR+=	libradius
SUBDIR+=	libskey
SUBDIR+=	libsndio
SUBDIR+=	libssl
SUBDIR+=	libtls
SUBDIR+=	libusbhid
SUBDIR+=	libutil

install:

.include <bsd.subdir.mk>
