#	$OpenBSD: Makefile,v 1.7 2002/02/18 11:01:24 art Exp $
#	$NetBSD: Makefile,v 1.2 1995/04/20 22:38:24 cgd Exp $

SUBDIR+= libc libc_r csu libssl

regress: _SUBDIRUSE

install:

.include <bsd.subdir.mk>
