#	$OpenBSD: Makefile,v 1.25 2022/03/24 22:11:11 bluhm Exp $

SUBDIR+=	csu
SUBDIR+=	libagentx
SUBDIR+=	libc
SUBDIR+=	libcrypto
SUBDIR+=	libedit
SUBDIR+=	libevent
SUBDIR+=	libexpat
SUBDIR+=	libfuse
SUBDIR+=	libm
SUBDIR+=	libpthread
SUBDIR+=	libradius
SUBDIR+=	libskey
SUBDIR+=	libsndio
SUBDIR+=	libssl
SUBDIR+=	libtls
SUBDIR+=	libusbhid
SUBDIR+=	libutil
SUBDIR+=	libz

install:

.include <bsd.subdir.mk>
