#	$OpenBSD: Makefile,v 1.2 1996/06/26 05:35:50 deraadt Exp $
#	$NetBSD: Makefile,v 1.3 1994/12/22 06:17:41 jtc Exp $

PROG=	locate.code
CFLAGS+=-I${.CURDIR}/../locate
NOMAN=	noman
BINDIR=	/usr/libexec

.include <bsd.prog.mk>
