.\"	$OpenBSD: npppdctl.8,v 1.2 2010/09/23 04:47:40 jsg Exp $
.\"
.\" Copyright (c) 2009 Internet Initiative Japan Inc.
.\" All rights reserved.
.\"
.\" Redistribution and use in source and binary forms, with or without
.\" modification, are permitted provided that the following conditions
.\" are met:
.\" 1. Redistributions of source code must retain the above copyright
.\"    notice, this list of conditions and the following disclaimer.
.\" 2. Redistributions in binary form must reproduce the above copyright
.\"    notice, this list of conditions and the following disclaimer in the
.\"    documentation and/or other materials provided with the distribution.
.\"
.\" THIS SOFTWARE IS PROVIDED BY THE AUTHOR AND CONTRIBUTORS ``AS IS'' AND
.\" ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE
.\" IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE
.\" ARE DISCLAIMED.  IN NO EVENT SHALL THE AUTHOR OR CONTRIBUTORS BE LIABLE
.\" FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL
.\" DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS
.\" OR SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION)
.\" HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT
.\" LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY
.\" OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF
.\" SUCH DAMAGE.
.\"
.Dd $Mdocdate: September 23 2010 $
.Dt NPPPDCTL 8
.Os
.Sh NAME
.Nm npppdctl
.Nd control the npppd daemon
.Sh SYNOPSIS
.Nm npppdctl
.Op Fl slnuh
.Op Fl d Ar ppp_user
.Op Fl r Ar rcvbuf_sz
.Op Fl p Ar npppd_ctl_path
.Nm npppdctl
.Fl R 
.Op Fl p Ar npppd_ctl_path
.Sh DESCRIPTION
The
.Nm
program controls the
.Xr npppd 8
daemon.
.Pp
If no options are specified,
.Nm
displays list of all users currently established, showing for each PPP user
print the PPP user name, assigned IP address, the date and time the PPP
started and the address which the user connected from.
.Pp
The options are as follows:
.Bl -tag -width Ds
.It Fl s
Show I/O statistics instead of default display.  Print bytes, number of
packets and number of errors for input and output.
.It Fl l
Use long line to display information.
.It Fl n
Don't convert addresses/ports to names.
.It Fl u
Show 'since' field as unix time.
.It Fl d Ar ppp_user
Disconnect the user specified by
.Ar ppp_user
.It Fl r Ar rcvbuf_sz
Specify receive buffer size.
.It Fl p Ar npppd_ctl_path
Specify a path
.Nm 's control socket.
.It Fl R 
Request to reset the routing table.
.It Fl h
Show usage.
.El
.Sh EXAMPLES
Following is displayed in default.
.Bd -literal -offset 0
% npppdctl
name             assigned         since         proto  from
user35425        10.100.187.37    Jan 26 18:13  L2TP   h084n074.example.com:1701
user31012        10.100.187.105   Jan 26 18:14  PPTP   h069n074.example.com:49194
.Ed
.Pp
With
.Fl s
option, I/O statistics are shown.
.Bd -literal -offset 0
% npppdctl -s
id       name                  in(Kbytes/pkts/errs)     out(Kbytes/pkts/errs)
    708  user35425                 153.5    1500    37      334.1    1656     0
    709  user31012                4993.0   47179     1    24303.3   64123     0
.Ed
.Pp
With
.Fl d
option, disconnect the PPP that is specified by its user name.
.Bd -literal -offset 0
% npppdctl -d user31012
Disconnected 1 ppp connections
%
.Ed
.Sh SEE ALSO
.Xr npppd 8
.Xr npppd.conf 5
