#	$OpenBSD: Makefile,v 1.25 2012/07/02 12:02:36 espie Exp $
#	$NetBSD: Makefile,v 1.1 1997/12/30 23:27:11 cgd Exp $

SUBDIR+= basename bc cap_mkdb dc diff diff3 dirname file grep gzip gzsig
SUBDIR+= libtool
SUBDIR+= m4 make mandoc patch pkg-config rcs sdiff sed sort ssh tsort
SUBDIR+= xargs xlint

.include <bsd.subdir.mk>
