#define HAVE_VOP_ISLOCKED 1
NNPFS_VOP_DEF(islocked);
#define HAVE_VOP_LOOKUP 1
NNPFS_VOP_DEF(lookup);
#define HAVE_VOP_CREATE 1
NNPFS_VOP_DEF(create);
#define HAVE_VOP_MKNOD 1
NNPFS_VOP_DEF(mknod);
#define HAVE_VOP_OPEN 1
NNPFS_VOP_DEF(open);
#define HAVE_VOP_CLOSE 1
NNPFS_VOP_DEF(close);
#define HAVE_VOP_ACCESS 1
NNPFS_VOP_DEF(access);
#define HAVE_VOP_GETATTR 1
NNPFS_VOP_DEF(getattr);
#define HAVE_VOP_SETATTR 1
NNPFS_VOP_DEF(setattr);
#define HAVE_VOP_READ 1
NNPFS_VOP_DEF(read);
#define HAVE_VOP_WRITE 1
NNPFS_VOP_DEF(write);
#define HAVE_VOP_IOCTL 1
NNPFS_VOP_DEF(ioctl);
#define HAVE_VOP_POLL 1
NNPFS_VOP_DEF(poll);
#define HAVE_VOP_KQFILTER 1
NNPFS_VOP_DEF(kqfilter);
#define HAVE_VOP_REVOKE 1
NNPFS_VOP_DEF(revoke);
#define HAVE_VOP_FSYNC 1
NNPFS_VOP_DEF(fsync);
#define HAVE_VOP_REMOVE 1
NNPFS_VOP_DEF(remove);
#define HAVE_VOP_LINK 1
NNPFS_VOP_DEF(link);
#define HAVE_VOP_RENAME 1
NNPFS_VOP_DEF(rename);
#define HAVE_VOP_MKDIR 1
NNPFS_VOP_DEF(mkdir);
#define HAVE_VOP_RMDIR 1
NNPFS_VOP_DEF(rmdir);
#define HAVE_VOP_SYMLINK 1
NNPFS_VOP_DEF(symlink);
#define HAVE_VOP_READDIR 1
NNPFS_VOP_DEF(readdir);
#define HAVE_VOP_READLINK 1
NNPFS_VOP_DEF(readlink);
#define HAVE_VOP_ABORTOP 1
NNPFS_VOP_DEF(abortop);
#define HAVE_VOP_INACTIVE 1
NNPFS_VOP_DEF(inactive);
#define HAVE_VOP_RECLAIM 1
NNPFS_VOP_DEF(reclaim);
#define HAVE_VOP_LOCK 1
NNPFS_VOP_DEF(lock);
#define HAVE_VOP_UNLOCK 1
NNPFS_VOP_DEF(unlock);
#define HAVE_VOP_BMAP 1
NNPFS_VOP_DEF(bmap);
#define HAVE_VOP_PRINT 1
NNPFS_VOP_DEF(print);
#define HAVE_VOP_PATHCONF 1
NNPFS_VOP_DEF(pathconf);
#define HAVE_VOP_ADVLOCK 1
NNPFS_VOP_DEF(advlock);
#define HAVE_VOP_REALLOCBLKS 1
NNPFS_VOP_DEF(reallocblks);
#define HAVE_VOP_STRATEGY 1
NNPFS_VOP_DEF(strategy);
#define HAVE_VOP_BWRITE 1
NNPFS_VOP_DEF(bwrite);
