#	$NetBSD: Makefile,v 1.5 1995/04/22 08:00:54 cgd Exp $
#	@(#)Makefile	8.1 (Berkeley) 5/31/93

PROG=	worms
MAN=	worms.6
DPADD=	${LIBCURSES} ${LIBTERM}
LDADD=	-lcurses -ltermcap

.include <bsd.prog.mk>
