#	$OpenBSD: Makefile,v 1.1 2000/11/13 20:12:34 aaron Exp $
#	$NetBSD: Makefile,v 1.1 1998/06/12 23:22:54 cgd Exp $

INCSDIR= /usr/include/dev/pckbc

INCS=	pckbdreg.h pckbdvar.h psmreg.h

.include <bsd.kinc.mk>
