# !!!!!!!   DO NOT EDIT THIS FILE   !!!!!!!
# This file is machine-generated by lib/unicore/mktables from the Unicode
# database, Version 5.2.0.  Any changes made here will be lost!

# !!!!!!!   INTERNAL PERL USE ONLY   !!!!!!!
# This file is for internal use by the Perl program only.  The format and even
# the name or existence of this file are subject to change without notice.
# Don't use it directly.

# This file returns the 188_809 code points in Unicode Version 5.2.0 that
# match any of the following regular expression constructs:
# 
#         \p{Present_In=3.0}
#         \p{In=3.0}
# 
#     Meaning: Code point's usage introduced in version 3.0 or earlier
# 
# perluniprops.pod should be consulted for the syntax rules for any of these,
# including if adding or subtracting white space, underscore, and hyphen
# characters matters or doesn't matter, and other permissible syntactic
# variants.  Upper/lower case distinctions never matter.
# 
# A colon can be substituted for the equals sign, and anything to the left of
# the equals (or colon) can be combined with anything to the right.  Thus,
# for example,
#         \p{In: 3.0}
# is also valid.
# 
# The format of the lines of this file is: START\tSTOP\twhere START is the
# starting code point of the range, in hex; STOP is the ending point, or if
# omitted, the range has just one code point.  Numbers in comments in
# [brackets] indicate how many code points are in the range.

return <<'END';
0000	021F	 # [544]
0222	0233	 # [18]
0250	02AD	 # [94]
02B0	02EE	 # [63]
0300	034E	 # [79]
0360	0362	 # [3]
0374	0375	 # [2]
037A		
037E		
0384	038A	 # [7]
038C		
038E	03A1	 # [20]
03A3	03CE	 # [44]
03D0	03D7	 # [8]
03DA	03F3	 # [26]
0400	0486	 # [135]
0488	0489	 # [2]
048C	04C4	 # [57]
04C7	04C8	 # [2]
04CB	04CC	 # [2]
04D0	04F5	 # [38]
04F8	04F9	 # [2]
0531	0556	 # [38]
0559	055F	 # [7]
0561	0587	 # [39]
0589	058A	 # [2]
0591	05A1	 # [17]
05A3	05B9	 # [23]
05BB	05C4	 # [10]
05D0	05EA	 # [27]
05F0	05F4	 # [5]
060C		
061B		
061F		
0621	063A	 # [26]
0640	0655	 # [22]
0660	066D	 # [14]
0670	06ED	 # [126]
06F0	06FE	 # [15]
0700	070D	 # [14]
070F	072C	 # [30]
0730	074A	 # [27]
0780	07B0	 # [49]
0901	0903	 # [3]
0905	0939	 # [53]
093C	094D	 # [18]
0950	0954	 # [5]
0958	0970	 # [25]
0981	0983	 # [3]
0985	098C	 # [8]
098F	0990	 # [2]
0993	09A8	 # [22]
09AA	09B0	 # [7]
09B2		
09B6	09B9	 # [4]
09BC		
09BE	09C4	 # [7]
09C7	09C8	 # [2]
09CB	09CD	 # [3]
09D7		
09DC	09DD	 # [2]
09DF	09E3	 # [5]
09E6	09FA	 # [21]
0A02		
0A05	0A0A	 # [6]
0A0F	0A10	 # [2]
0A13	0A28	 # [22]
0A2A	0A30	 # [7]
0A32	0A33	 # [2]
0A35	0A36	 # [2]
0A38	0A39	 # [2]
0A3C		
0A3E	0A42	 # [5]
0A47	0A48	 # [2]
0A4B	0A4D	 # [3]
0A59	0A5C	 # [4]
0A5E		
0A66	0A74	 # [15]
0A81	0A83	 # [3]
0A85	0A8B	 # [7]
0A8D		
0A8F	0A91	 # [3]
0A93	0AA8	 # [22]
0AAA	0AB0	 # [7]
0AB2	0AB3	 # [2]
0AB5	0AB9	 # [5]
0ABC	0AC5	 # [10]
0AC7	0AC9	 # [3]
0ACB	0ACD	 # [3]
0AD0		
0AE0		
0AE6	0AEF	 # [10]
0B01	0B03	 # [3]
0B05	0B0C	 # [8]
0B0F	0B10	 # [2]
0B13	0B28	 # [22]
0B2A	0B30	 # [7]
0B32	0B33	 # [2]
0B36	0B39	 # [4]
0B3C	0B43	 # [8]
0B47	0B48	 # [2]
0B4B	0B4D	 # [3]
0B56	0B57	 # [2]
0B5C	0B5D	 # [2]
0B5F	0B61	 # [3]
0B66	0B70	 # [11]
0B82	0B83	 # [2]
0B85	0B8A	 # [6]
0B8E	0B90	 # [3]
0B92	0B95	 # [4]
0B99	0B9A	 # [2]
0B9C		
0B9E	0B9F	 # [2]
0BA3	0BA4	 # [2]
0BA8	0BAA	 # [3]
0BAE	0BB5	 # [8]
0BB7	0BB9	 # [3]
0BBE	0BC2	 # [5]
0BC6	0BC8	 # [3]
0BCA	0BCD	 # [4]
0BD7		
0BE7	0BF2	 # [12]
0C01	0C03	 # [3]
0C05	0C0C	 # [8]
0C0E	0C10	 # [3]
0C12	0C28	 # [23]
0C2A	0C33	 # [10]
0C35	0C39	 # [5]
0C3E	0C44	 # [7]
0C46	0C48	 # [3]
0C4A	0C4D	 # [4]
0C55	0C56	 # [2]
0C60	0C61	 # [2]
0C66	0C6F	 # [10]
0C82	0C83	 # [2]
0C85	0C8C	 # [8]
0C8E	0C90	 # [3]
0C92	0CA8	 # [23]
0CAA	0CB3	 # [10]
0CB5	0CB9	 # [5]
0CBE	0CC4	 # [7]
0CC6	0CC8	 # [3]
0CCA	0CCD	 # [4]
0CD5	0CD6	 # [2]
0CDE		
0CE0	0CE1	 # [2]
0CE6	0CEF	 # [10]
0D02	0D03	 # [2]
0D05	0D0C	 # [8]
0D0E	0D10	 # [3]
0D12	0D28	 # [23]
0D2A	0D39	 # [16]
0D3E	0D43	 # [6]
0D46	0D48	 # [3]
0D4A	0D4D	 # [4]
0D57		
0D60	0D61	 # [2]
0D66	0D6F	 # [10]
0D82	0D83	 # [2]
0D85	0D96	 # [18]
0D9A	0DB1	 # [24]
0DB3	0DBB	 # [9]
0DBD		
0DC0	0DC6	 # [7]
0DCA		
0DCF	0DD4	 # [6]
0DD6		
0DD8	0DDF	 # [8]
0DF2	0DF4	 # [3]
0E01	0E3A	 # [58]
0E3F	0E5B	 # [29]
0E81	0E82	 # [2]
0E84		
0E87	0E88	 # [2]
0E8A		
0E8D		
0E94	0E97	 # [4]
0E99	0E9F	 # [7]
0EA1	0EA3	 # [3]
0EA5		
0EA7		
0EAA	0EAB	 # [2]
0EAD	0EB9	 # [13]
0EBB	0EBD	 # [3]
0EC0	0EC4	 # [5]
0EC6		
0EC8	0ECD	 # [6]
0ED0	0ED9	 # [10]
0EDC	0EDD	 # [2]
0F00	0F47	 # [72]
0F49	0F6A	 # [34]
0F71	0F8B	 # [27]
0F90	0F97	 # [8]
0F99	0FBC	 # [36]
0FBE	0FCC	 # [15]
0FCF		
1000	1021	 # [34]
1023	1027	 # [5]
1029	102A	 # [2]
102C	1032	 # [7]
1036	1039	 # [4]
1040	1059	 # [26]
10A0	10C5	 # [38]
10D0	10F6	 # [39]
10FB		
1100	1159	 # [90]
115F	11A2	 # [68]
11A8	11F9	 # [82]
1200	1206	 # [7]
1208	1246	 # [63]
1248		
124A	124D	 # [4]
1250	1256	 # [7]
1258		
125A	125D	 # [4]
1260	1286	 # [39]
1288		
128A	128D	 # [4]
1290	12AE	 # [31]
12B0		
12B2	12B5	 # [4]
12B8	12BE	 # [7]
12C0		
12C2	12C5	 # [4]
12C8	12CE	 # [7]
12D0	12D6	 # [7]
12D8	12EE	 # [23]
12F0	130E	 # [31]
1310		
1312	1315	 # [4]
1318	131E	 # [7]
1320	1346	 # [39]
1348	135A	 # [19]
1361	137C	 # [28]
13A0	13F4	 # [85]
1401	1676	 # [630]
1680	169C	 # [29]
16A0	16F0	 # [81]
1780	17DC	 # [93]
17E0	17E9	 # [10]
1800	180E	 # [15]
1810	1819	 # [10]
1820	1877	 # [88]
1880	18A9	 # [42]
1E00	1E9B	 # [156]
1EA0	1EF9	 # [90]
1F00	1F15	 # [22]
1F18	1F1D	 # [6]
1F20	1F45	 # [38]
1F48	1F4D	 # [6]
1F50	1F57	 # [8]
1F59		
1F5B		
1F5D		
1F5F	1F7D	 # [31]
1F80	1FB4	 # [53]
1FB6	1FC4	 # [15]
1FC6	1FD3	 # [14]
1FD6	1FDB	 # [6]
1FDD	1FEF	 # [19]
1FF2	1FF4	 # [3]
1FF6	1FFE	 # [9]
2000	2046	 # [71]
2048	204D	 # [6]
206A	2070	 # [7]
2074	208E	 # [27]
20A0	20AF	 # [16]
20D0	20E3	 # [20]
2100	213A	 # [59]
2153	2183	 # [49]
2190	21F3	 # [100]
2200	22F1	 # [242]
2300	237B	 # [124]
237D	239A	 # [30]
2400	2426	 # [39]
2440	244A	 # [11]
2460	24EA	 # [139]
2500	2595	 # [150]
25A0	25F7	 # [88]
2600	2613	 # [20]
2619	2671	 # [89]
2701	2704	 # [4]
2706	2709	 # [4]
270C	2727	 # [28]
2729	274B	 # [35]
274D		
274F	2752	 # [4]
2756		
2758	275E	 # [7]
2761	2767	 # [7]
2776	2794	 # [31]
2798	27AF	 # [24]
27B1	27BE	 # [14]
2800	28FF	 # [256]
2E80	2E99	 # [26]
2E9B	2EF3	 # [89]
2F00	2FD5	 # [214]
2FF0	2FFB	 # [12]
3000	303A	 # [59]
303E	303F	 # [2]
3041	3094	 # [84]
3099	309E	 # [6]
30A1	30FE	 # [94]
3105	312C	 # [40]
3131	318E	 # [94]
3190	31B7	 # [40]
3200	321C	 # [29]
3220	3243	 # [36]
3260	327B	 # [28]
327F	32B0	 # [50]
32C0	32CB	 # [12]
32D0	32FE	 # [47]
3300	3376	 # [119]
337B	33DD	 # [99]
33E0	33FE	 # [31]
3400	4DB5	 # [6582]
4E00	9FA5	 # [20_902]
A000	A48C	 # [1165]
A490	A4A1	 # [18]
A4A4	A4B3	 # [16]
A4B5	A4C0	 # [12]
A4C2	A4C4	 # [3]
A4C6		
AC00	D7A3	 # [11_172]
D800	FA2D	 # [8750]
FB00	FB06	 # [7]
FB13	FB17	 # [5]
FB1D	FB36	 # [26]
FB38	FB3C	 # [5]
FB3E		
FB40	FB41	 # [2]
FB43	FB44	 # [2]
FB46	FBB1	 # [108]
FBD3	FD3F	 # [365]
FD50	FD8F	 # [64]
FD92	FDC7	 # [54]
FDF0	FDFB	 # [12]
FE20	FE23	 # [4]
FE30	FE44	 # [21]
FE49	FE52	 # [10]
FE54	FE66	 # [19]
FE68	FE6B	 # [4]
FE70	FE72	 # [3]
FE74		
FE76	FEFC	 # [135]
FEFF		
FF01	FF5E	 # [94]
FF61	FFBE	 # [94]
FFC2	FFC7	 # [6]
FFCA	FFCF	 # [6]
FFD2	FFD7	 # [6]
FFDA	FFDC	 # [3]
FFE0	FFE6	 # [7]
FFE8	FFEE	 # [7]
FFF9	FFFF	 # [7]
1FFFE	1FFFF	 # [2]
2FFFE	2FFFF	 # [2]
3FFFE	3FFFF	 # [2]
4FFFE	4FFFF	 # [2]
5FFFE	5FFFF	 # [2]
6FFFE	6FFFF	 # [2]
7FFFE	7FFFF	 # [2]
8FFFE	8FFFF	 # [2]
9FFFE	9FFFF	 # [2]
AFFFE	AFFFF	 # [2]
BFFFE	BFFFF	 # [2]
CFFFE	CFFFF	 # [2]
DFFFE	DFFFF	 # [2]
EFFFE	10FFFF	 # [131_074]
END
