#	$OpenBSD: Makefile,v 1.4 2001/09/11 19:02:50 millert Exp $

PROG=	vacation
ENVDEF=	-DNOT_SENDMAIL

WANT_LIBSM=1
WANT_LIBSMDB=1
WANT_LIBSMUTIL=1

.include "../../../usr.bin/Makefile.inc"
.include <bsd.prog.mk>
