.\"	$OpenBSD: whatis.1,v 1.15 2011/10/09 02:20:39 schwarze Exp $
.\"
.\" Copyright (c) 1989, 1990, 1993
.\"	The Regents of the University of California.  All rights reserved.
.\"
.\" Redistribution and use in source and binary forms, with or without
.\" modification, are permitted provided that the following conditions
.\" are met:
.\" 1. Redistributions of source code must retain the above copyright
.\"    notice, this list of conditions and the following disclaimer.
.\" 2. Redistributions in binary form must reproduce the above copyright
.\"    notice, this list of conditions and the following disclaimer in the
.\"    documentation and/or other materials provided with the distribution.
.\" 3. Neither the name of the University nor the names of its contributors
.\"    may be used to endorse or promote products derived from this software
.\"    without specific prior written permission.
.\"
.\" THIS SOFTWARE IS PROVIDED BY THE REGENTS AND CONTRIBUTORS ``AS IS'' AND
.\" ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE
.\" IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE
.\" ARE DISCLAIMED.  IN NO EVENT SHALL THE REGENTS OR CONTRIBUTORS BE LIABLE
.\" FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL
.\" DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS
.\" OR SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION)
.\" HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT
.\" LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY
.\" OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF
.\" SUCH DAMAGE.
.\"
.\"     @(#)whatis.1	8.1 (Berkeley) 6/6/93
.\"
.Dd $Mdocdate: October 9 2011 $
.Dt WHATIS 1
.Os
.Sh NAME
.Nm whatis
.Nd describe what a command is
.Sh SYNOPSIS
.Nm whatis
.Op Fl C Ar file
.Op Fl M Ar path
.Op Fl m Ar path
.Ar command ...
.Sh DESCRIPTION
.Nm
looks up a given command and gives the header line from the manual page.
You can then use the
.Xr man 1
command to get more information.
.Nm
will match on a case insensitive basis and for multiple word entries
will match on each individual word.
.Pp
The options are as follows:
.Bl -tag -width Ds
.It Fl C Ar file
Specify an alternate configuration file in
.Xr man.conf 5
format.
The default is
.Pa /etc/man.conf .
.It Fl M Ar path
Override the list of standard directories
.Nm
searches for its database named
.Dq Pa whatis.db .
The supplied
.Ar path
must be a colon
.Pq Ql \&:
separated list of directories.
This search path may also be set using the environment variable
.Ev MANPATH .
.It Fl m Ar path
Augment the list of standard directories
.Nm
searches for its database named
.Dq Pa whatis.db .
The supplied
.Ar path
must be a colon-separated list of directories.
These directories will be searched before the standard directories
or the directories supplied with the
.Fl M
option or the
.Ev MANPATH
environment variable are searched.
.El
.Sh ENVIRONMENT
.Bl -tag -width MANPATH
.It Ev MANPATH
The standard search path used by
.Xr man 1
may be overridden by specifying a path in the
.Ev MANPATH
environment variable.
.El
.Sh FILES
.Bl -tag -width "/etc/man.conf" -compact
.It Pa whatis.db
name of the whatis database
.It Pa /etc/man.conf
default
.Xr man 1
configuration file
.El
.Sh SEE ALSO
.Xr apropos 1 ,
.Xr man 1 ,
.Xr whereis 1 ,
.Xr which 1 ,
.Xr man.conf 5 ,
.Xr makewhatis 8
.Sh HISTORY
The
.Nm
command first appeared in
.Bx 2 .
The
.Fl M
option first appeared in
.Bx 4.3 Tahoe ;
.Fl m
in
.Bx 4.3 Reno ;
and
.Fl C
in
.Nx 1.0 .
.Sh AUTHORS
.An Bill Joy
