.\"	$OpenBSD: grdc.6,v 1.11 2019/01/06 18:27:14 tedu Exp $
.\"
.\" Copyright 2002 Amos Shapir.  Public domain.
.\"
.Dd $Mdocdate: January 6 2019 $
.Dt GRDC 6
.Os
.Sh NAME
.Nm grdc
.Nd grand digital clock (curses)
.Sh SYNOPSIS
.Nm grdc
.Op Fl s
.Op Ar number
.Sh DESCRIPTION
.Nm
runs a digital clock made of reverse-video blanks on a curses
compatible screen.
With an optional numeric argument
.Ar number
it stops after
.Ar number
seconds (defaulting to never).
The optional
.Fl s
flag makes digits scroll as they change.
If the terminal is too slow to keep up,
.Nm
skips seconds.
Pressing the
.Sq q
exits the program.
.Sh AUTHORS
.An -nosplit
.An Amos Shapir ,
modified for curses by
.An John Lupien .
