.\"	$OpenBSD: grdc.6,v 1.3 1998/12/15 19:18:35 pjanzen Exp $
.Dd August 4, 1997
.Dt GRDC 6
.Os OpenBSD
.Sh NAME
.Nm grdc
.Nd grand digital clock (curses)
.Sh SYNOPSIS
.Nm grdc
.Op Fl s
.Op Ar number
.Sh DESCRIPTION
.Nm
runs a digital clock made of reverse-video blanks on a curses
compatible VDU screen.  With an optional numeric argument
.Ar number
it stops after
.Ar number
seconds (defaulting to never).
The optional
.Fl s
flag makes digits scroll as they change.  In this curses mode implementation,
the scrolling option has trouble keeping up.
.Sh AUTHOR
Amos Shapir, modified for curses by John Lupien.
