.\"	$OpenBSD: rcctl.8,v 1.13 2015/01/06 12:28:56 ajacoutot Exp $
.\"
.\" Copyright (c) 2014 Antoine Jacoutot <ajacoutot@openbsd.org>
.\"
.\" Permission to use, copy, modify, and distribute this software for any
.\" purpose with or without fee is hereby granted, provided that the above
.\" copyright notice and this permission notice appear in all copies.
.\"
.\" THE SOFTWARE IS PROVIDED "AS IS" AND THE AUTHOR DISCLAIMS ALL WARRANTIES
.\" WITH REGARD TO THIS SOFTWARE INCLUDING ALL IMPLIED WARRANTIES OF
.\" MERCHANTABILITY AND FITNESS. IN NO EVENT SHALL THE AUTHOR BE LIABLE FOR
.\" ANY SPECIAL, DIRECT, INDIRECT, OR CONSEQUENTIAL DAMAGES OR ANY DAMAGES
.\" WHATSOEVER RESULTING FROM LOSS OF USE, DATA OR PROFITS, WHETHER IN AN
.\" ACTION OF CONTRACT, NEGLIGENCE OR OTHER TORTIOUS ACTION, ARISING OUT OF
.\" OR IN CONNECTION WITH THE USE OR PERFORMANCE OF THIS SOFTWARE.
.\"
.Dd $Mdocdate: January 6 2015 $
.Dt RCCTL 8
.Os
.Sh NAME
.Nm rcctl
.Nd configure and control daemons and services
.Sh SYNOPSIS
.Nm rcctl
.Op Fl df
.Sm off
.Cm enable | disable | get | set | getdef | getall | order | Ar action
.Sm on
.Op Ar service | daemon Oo Ar variable Oo Ar arguments Oc Oc | Ar daemons
.Sh DESCRIPTION
The
.Nm
utility can enable or disable a base system
.Ar service
or a base system or package
.Ar daemon
in
.Xr rc.conf.local 8
or display its configuration and status.
For a daemon, it can also change the command line arguments or call its
.Xr rc.d 8
.Ar daemon
control script.
.Pp
.Ar variable
can be one of
.Ar flags ,
.Ar status ,
.Ar timeout
or
.Ar user .
The following commands are available:
.Bl -tag -width Ds
.It Cm enable Ar service | daemon
Alias for
.Dq Cm set Ar service|daemon Cm status Ar on .
.It Cm disable Ar service | daemon
Alias for
.Dq Cm set Ar service|daemon Cm status Ar off .
.It Cm get Ar daemon Op variable
Display the value of
.Ar service
or
.Ar daemon
variable.
Without a variable, display all variables with their values in a format
compatible with
.Xr rc.conf 8 .
.It Cm set Ar daemon Cm variable Op arguments
For a daemon, set the variable
.Ar daemon Ns _variable
to the specified
.Ar arguments .
If
.Cm variable
is already set,
.Ar daemon Ns _variable
is reset to the optionally provided
.Cm variable .
If
.Cm variable
is appended without any
.Ar arguments ,
.Ar daemon Ns _variable
is reset to its default value.
.Pp
The
.Ar status Cm variable
only takes the
.Ar on
or
.Ar off
argument.
It is used to enable or disable a service or daemon in
.Xr rc.conf.local 8 .
When a disabled package daemon is enabled, it is appended to the end of
.Va pkg_scripts .
When a package daemon is disabled, it is removed from
.Va pkg_scripts .
.It Cm getdef Ar daemon Op variable
Like
.Cm get
but returns the default values.
.It Cm getall
Display all services and daemon values in a format compatible with
.Xr rc.conf 8 .
.It Cm order Op Ar daemons
Move the specified package
.Ar daemons
to the beginning of
.Va pkg_scripts .
They need to be already enabled.
If
.Ar daemons
is empty, display the current order.
.Pp
The
.Cm order
command is only needed after enabling a new daemon
that needs to run before one or more already enabled daemons.
Specify the new daemon preceded by all that need to run before it,
but not the ones depending on it.
.It Oo Fl df Oc Ar action daemon
Run the
.Xr rc.d 8
.Ar daemon
script with the
.Ar action
argument, passing through the specified options, if any.
.El
.Sh EXIT STATUS
.Nm Ar action
returns with the exit status of the
.Xr rc.d 8
.Ar daemon
script.
.Nm Cm get Ar daemon|service Op status
exits with 0 if the daemon or service is enabled and 1 if it is not.
.Nm Cm getdef Ar daemon|service Op status
exits with 0 if the daemon or service is enabled by default
and 1 if it is not.
Otherwise, the
.Nm
utility exits 0 on success, and >0 if an error occurs
.Po 2 indicates a non-existent
.Ar daemon|service
.Pc .
.Sh EXAMPLES
Enable and set
.Xr ntpd 8
flags:
.Bd -literal -offset indent
# rcctl set ntpd status on
# rcctl set ntpd flags -s
# rcctl get ntpd
ntpd_flags=-s
ntpd_timeout=30
ntpd_user=root
# echo $?
0
.Ed
.Sh SEE ALSO
.Xr rc.conf.local 8 ,
.Xr rc.d 8
.Sh HISTORY
.Nm
first appeared in
.Ox 5.7 .
.Sh AUTHORS
.Nm
was written by
.An Antoine Jacoutot Aq Mt ajacoutot@openbsd.org .
