.\"   $OpenBSD: tftpd.8,v 1.18 2004/11/22 00:58:39 jmc Exp $
.\"
.\" Copyright (c) 1983, 1991 The Regents of the University of California.
.\" All rights reserved.
.\"
.\" Redistribution and use in source and binary forms, with or without
.\" modification, are permitted provided that the following conditions
.\" are met:
.\" 1. Redistributions of source code must retain the above copyright
.\"    notice, this list of conditions and the following disclaimer.
.\" 2. Redistributions in binary form must reproduce the above copyright
.\"    notice, this list of conditions and the following disclaimer in the
.\"    documentation and/or other materials provided with the distribution.
.\" 3. Neither the name of the University nor the names of its contributors
.\"    may be used to endorse or promote products derived from this software
.\"    without specific prior written permission.
.\"
.\" THIS SOFTWARE IS PROVIDED BY THE REGENTS AND CONTRIBUTORS ``AS IS'' AND
.\" ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE
.\" IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE
.\" ARE DISCLAIMED.  IN NO EVENT SHALL THE REGENTS OR CONTRIBUTORS BE LIABLE
.\" FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL
.\" DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS
.\" OR SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION)
.\" HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT
.\" LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY
.\" OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF
.\" SUCH DAMAGE.
.\"
.\"	from: @(#)tftpd.8	6.7 (Berkeley) 5/13/91
.\"	$OpenBSD: tftpd.8,v 1.18 2004/11/22 00:58:39 jmc Exp $
.\"
.Dd June 11, 1997
.Dt TFTPD 8
.Os
.Sh NAME
.Nm tftpd
.Nd
.Tn DARPA
Trivial File Transfer Protocol server
.Sh SYNOPSIS
.Nm tftpd
.Op Ar directory ...
.Nm tftpd
.Op Fl cs
.Op Ar directory
.Sh DESCRIPTION
.Nm
is a server which supports the
.Tn DARPA
Trivial File Transfer Protocol.
The TFTP server operates at the port indicated in the
.Ql tftp
service description; see
.Xr services 5 .
The server is normally started by
.Xr inetd 8 .
.Pp
The use of
.Xr tftp 1
does not require an account or password on the remote system.
Due to the lack of authentication information,
.Nm
will allow only publicly readable files to be accessed.
Files may be written only if they already exist and are publicly writable,
unless the
.Fl c
flag is specified
.Pq see below .
Note that this extends the concept of
.Dq public
to include
all users on all hosts that can be reached through the network;
this may not be appropriate on all systems, and its implications
should be considered before enabling TFTP service.
.Pp
The server should have the user ID with the lowest possible privilege,
unless the
.Fl s
flag is specified
.Pq see below ,
in which case it must be started with user ID 0.
.Pp
Access to files may be restricted by invoking
.Nm
with a list of directories by including pathnames
as server program arguments in
.Pa /etc/inetd.conf .
In this case access is restricted to files whose
names are prefixed by one of the given directories.
.Pp
The options are as follows:
.Bl -tag -width Ds
.It Fl c
If the
.Fl c
flag is used,
.Nm
will allow new files to be created; otherwise uploaded files must already
exist.
Files are created with default permissions allowing anyone to read
or write to them.
.It Fl s
When using the
.Fl s
flag with a directory name,
.Nm
will
.Xr chroot 2
on startup; therefore the remote host is not expected to pass the directory
as part of the file name to transfer.
This option is intended primarily for
compatibility with SunOS boot ROMs which do not include a directory name.
.El
.Sh SEE ALSO
.Xr tftp 1 ,
.Xr inetd 8 ,
.Xr pxeboot 8
.Sh HISTORY
The
.Nm
command appeared in
.Bx 4.2 .
.Pp
The
.Fl s
flag appeared in
.Nx 0.9a .
.Pp
The
.Fl c
flag was added in
.Ox 2.1 .
.Sh BUGS
This implementation of
.Nm
does not support blocksize negotiation
.Pq RFC 1783 ,
so files larger than 33488896 octets
.Pq 65535 blocks
cannot be transferred.
.Pp
Many TFTP clients will not transfer files over 16744448 octets
.Pq 32767 blocks .
