#	$OpenBSD: Makefile,v 1.8 2020/12/17 14:16:10 bluhm Exp $

SUBDIR +=	arp autoport
SUBDIR +=	broadcast_bind
SUBDIR +=	carp
SUBDIR +=	frag
SUBDIR +=	in_pcbbind ipsec
SUBDIR +=	mcast
SUBDIR +=	pmtu
SUBDIR +=	recvmsg
SUBDIR +=	sendsrcaddr

.include <bsd.subdir.mk>
