.\"	$OpenBSD: ping6.8,v 1.42 2010/06/26 18:30:03 phessler Exp $
.\"	$KAME: ping6.8,v 1.57 2002/05/26 13:18:25 itojun Exp $
.\"
.\" Copyright (C) 1995, 1996, 1997, and 1998 WIDE Project.
.\" All rights reserved.
.\"
.\" Redistribution and use in source and binary forms, with or without
.\" modification, are permitted provided that the following conditions
.\" are met:
.\" 1. Redistributions of source code must retain the above copyright
.\"    notice, this list of conditions and the following disclaimer.
.\" 2. Redistributions in binary form must reproduce the above copyright
.\"    notice, this list of conditions and the following disclaimer in the
.\"    documentation and/or other materials provided with the distribution.
.\" 3. Neither the name of the project nor the names of its contributors
.\"    may be used to endorse or promote products derived from this software
.\"    without specific prior written permission.
.\"
.\" THIS SOFTWARE IS PROVIDED BY THE PROJECT AND CONTRIBUTORS ``AS IS'' AND
.\" ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE
.\" IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE
.\" ARE DISCLAIMED.  IN NO EVENT SHALL THE PROJECT OR CONTRIBUTORS BE LIABLE
.\" FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL
.\" DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS
.\" OR SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION)
.\" HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT
.\" LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY
.\" OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF
.\" SUCH DAMAGE.
.\"
.Dd $Mdocdate: June 26 2010 $
.Dt PING6 8
.Os
.Sh NAME
.Nm ping6
.Nd send ICMPv6 ECHO_REQUEST packets to network hosts
.Sh SYNOPSIS
.Nm ping6
.Op Fl dEefHmNnqtvWw
.Op Fl a Ar addrtype
.Op Fl b Ar bufsiz
.Op Fl c Ar count
.Op Fl g Ar gateway
.Op Fl h Ar hoplimit
.Op Fl I Ar interface
.Op Fl i Ar wait
.Op Fl l Ar preload
.Op Fl p Ar pattern
.Op Fl S Ar sourceaddr
.Op Fl s Ar packetsize
.Op Ar hops ...
.Ar host
.Sh DESCRIPTION
.Nm
uses the
ICMPv6
protocol's mandatory
.Dv ICMP6_ECHO_REQUEST
datagram to elicit an
.Dv ICMP6_ECHO_REPLY
from a host or gateway.
.Dv ICMP6_ECHO_REQUEST
datagrams (``pings'') have an IPv6 header,
and
ICMPv6
header formatted as documented in RFC 2463.
The options are as follows:
.Bl -tag -width Ds
.It Fl a Ar addrtype
Generate an ICMPv6 Node Information Node Addresses query,
rather than an echo-request.
.Ar addrtype
must be a string constructed of the following characters:
.Pp
.Bl -tag -width Ds -compact
.It Ic A
Requests responder's anycast addresses.
Without this character, the responder will return unicast addresses only.
With this character, the responder will return anycast addresses only.
Note that the specification does not specify how to get the responder's
anycast addresses.
This is an experimental option.
.It Ic a
Requests unicast addresses from all of the responder's interfaces.
If the character is omitted,
only those addresses which belong to the interface which has the
responder's address are requests.
.It Ic c
Requests responder's IPv4-compatible and IPv4-mapped addresses.
.It Ic g
Requests responder's global-scope addresses.
.It Ic l
Requests responder's link-local addresses.
.It Ic s
Requests responder's site-local addresses.
.El
.It Fl b Ar bufsiz
Set the socket buffer size.
.It Fl c Ar count
Stop after sending
.Pq and receiving
.Ar count
.Dv ECHO_RESPONSE
packets.
If
.Ar count
is 0, send an unlimited number of packets.
.It Fl d
Set the
.Dv SO_DEBUG
option on the socket being used.
.It Fl E
Emit an audible beep (by sending an ASCII BEL character to the
standard error output) when no packet is received before the next
packet is transmitted.
To cater for round-trip times that are longer than the interval
between transmissions, further missing packets cause a bell only
if the maximum number of unreceived packets has increased.
This option is disabled for flood pings.
.It Fl e
Emit an audible beep (by sending an ASCII BEL character to the
standard error output) after each non-duplicate response is received.
This option is disabled for flood pings.
.It Fl f
Flood ping.
Outputs packets as fast as they come back or one hundred times per second,
whichever is more.
For every
.Dv ECHO_REQUEST
sent a period
.Pq Sq \&.
is printed, while for every
.Dv ECHO_REPLY
received a backspace is printed.
This provides a rapid display of how many packets are being dropped.
Only the super-user may use this option.
.Bf -emphasis
This can be very hard on a network and should be used with caution.
.Ef
.It Fl g Ar gateway
Specifies to use
.Ar gateway
as the next hop to the destination.
The gateway must be a neighbor of the sending node.
.It Fl H
Specifies to try reverse-lookup of IPv6 addresses.
The
.Nm
command does not try reverse-lookup unless the option is specified.
.It Fl h Ar hoplimit
Set the IPv6 hoplimit.
.It Fl I Ar interface
Source packets with the given interface address.
This flag applies if the ping destination is a multicast address,
or link-local/site-local unicast address.
.It Fl i Ar wait
Wait
.Ar wait
seconds
.Em between sending each packet .
The default is to wait for one second between each packet.
This option is incompatible with the
.Fl f
option.
.It Fl l Ar preload
If
.Ar preload
is specified,
.Nm
sends that many packets as fast as possible before falling into its normal
mode of behavior.
Only the super-user may use this option.
.It Fl m
By default,
.Nm
asks the kernel to fragment packets to fit into the minimum IPv6 MTU.
.Fl m
will suppress the behavior in the following two levels:
when the option is specified once, the behavior will be disabled for
unicast packets.
When the option is specified more than once, it will be disabled for both
unicast and multicast packets.
.It Fl N
Probe the node information multicast group
.Pq Li ff02::2:xxxx:xxxx .
.Ar host
must be the hostname of the target
(i.e. it must not be a numeric IPv6 address).
The node information multicast group is computed based on the given
.Ar host ,
and is used as the final destination.
Since the node information multicast group is a link-local multicast group,
the outgoing interface needs to be specified using the
.Fl I
option.
.It Fl n
Numeric output only.
No attempt will be made to look up symbolic names from addresses in the reply.
.It Fl p Ar pattern
Up to 16
.Dq pad
bytes may be specified to fill out the packet sent.
This is useful for diagnosing data-dependent problems in a network.
For example,
.Dq -p ff
will cause the packet sent to be filled with all
ones.
.\" new ipsec
.\".It Fl P Ar policy
.\".Ar policy
.\"specifies IPsec policy to be used for the probe.
.It Fl q
Quiet output.
Nothing is displayed except the summary lines at startup time and
when finished.
.\".It Fl R
.\"Make the kernel believe that the target
.\".Ar host
.\".Po
.\"or the first
.\".Ar hop
.\"if you specify
.\".Ar hops
.\".Pc
.\"is reachable, by injecting upper-layer reachability confirmation hint.
.\"The option is meaningful only if the target
.\".Ar host
.\".Pq or the first hop
.\"is a neighbor.
.It Fl S Ar sourceaddr
Specifies the source address of request packets.
The source address must be one of the unicast addresses of the sending node,
and must be numeric.
.It Fl s Ar packetsize
Specifies the number of data bytes to be sent.
The default is 56, which translates into 64
ICMP
data bytes when combined
with the 8 bytes of
ICMP
header data.
It may also be necessary to specify
.Fl b
to extend the socket buffer size.
.Pp
This option is ignored if any of the flags
.Op Fl tWw
are specified.
.It Fl t
Generate an ICMPv6 Node Information query,
rather than echo-request.
.Fl s
has no effect if
this option
is specified.
.It Fl v
Verbose output.
All ICMP packets
that are received are listed.
.It Fl W
The
same as
.Fl w ,
but with the old packet format based on the 03 draft.
This option is present for backward compatibility.
.Fl s
has no effect if
this option
is specified.
.It Fl w
Generate an ICMPv6 Node Information DNS Name query,
rather than echo-request.
.Fl s
has no effect if
this option
is specified.
.It Ar hops
IPv6 addresses of intermediate nodes,
which will be put into a type 0 routing header.
.It Ar host
The IPv6 address of the final destination node.
.El
.Pp
When using
.Nm
for fault isolation, it should first be run on the local host, to verify
that the local network interface is up and running.
Then hosts and gateways further and further away can be
.Dq pinged .
Round-trip times and packet loss statistics are computed.
If duplicate packets are received, they are not included in the packet
loss calculation, although the round trip time of these packets is used
in calculating the round-trip time statistics.
When the specified number of packets have been sent
.Pq and received
or if the program is terminated with a
.Dv SIGINT ,
a brief summary is displayed, showing the number of packets sent and
received, and the minimum, maximum, mean, and standard deviation of
the round-trip times.
.Pp
This program is intended for use in network testing, measurement, and
management.
Because of the load it can impose on the network, it is unwise to use
.Nm
during normal operations or from automated scripts.
.Pp
.Nm
exits 0 if at least one reply is received,
and \*(Gt0 if no reply is received or an error occurred.
.\" .Sh ICMP PACKET DETAILS
.\" An IP header without options is 20 bytes.
.\" An
.\" .Tn ICMP
.\" .Tn ECHO_REQUEST
.\" packet contains an additional 8 bytes worth of
.\" .Tn ICMP
.\" header followed by an arbitrary amount of data.
.\" When a
.\" .Ar packetsize
.\" is given, this indicated the size of this extra piece of data
.\" .Pq the default is 56 .
.\" Thus the amount of data received inside of an IP packet of type
.\" .Tn ICMP
.\" .Tn ECHO_REPLY
.\" will always be 8 bytes more than the requested data space
.\" .Pq the Tn ICMP header .
.\" .Pp
.\" If the data space is at least eight bytes large,
.\" .Nm
.\" uses the first eight bytes of this space to include a timestamp which
.\" it uses in the computation of round trip times.
.\" If less than eight bytes of pad are specified, no round trip times are
.\" given.
.Sh DUPLICATE AND DAMAGED PACKETS
.Nm
will report duplicate and damaged packets.
Duplicate packets should never occur when pinging a unicast address,
and seem to be caused by
inappropriate link-level retransmissions.
Duplicates may occur in many situations and are rarely
.Pq if ever
a good sign, although the presence of low levels of duplicates may not
always be cause for alarm.
Duplicates are expected when pinging a broadcast or multicast address,
since they are not really duplicates but replies from different hosts
to the same request.
.Pp
Damaged packets are obviously serious cause for alarm and often
indicate broken hardware somewhere in the
.Nm
packet's path
.Pq in the network or in the hosts .
.Sh TRYING DIFFERENT DATA PATTERNS
The
(inter)network
layer should never treat packets differently depending on the data
contained in the data portion.
Unfortunately, data-dependent problems have been known to sneak into
networks and remain undetected for long periods of time.
In many cases the particular pattern that will have problems is something
that does not have sufficient
.Dq transitions ,
such as all ones or all zeros, or a pattern right at the edge, such as
almost all zeros.
It is not
necessarily enough to specify a data pattern of all zeros (for example)
on the command line because the pattern that is of interest is
at the data link level, and the relationship between what is typed and
what the controllers transmit can be complicated.
.Pp
This means that if there is a data-dependent problem,
a lot of testing will probably have to be done to find it.
It may be possible to find a file that either cannot
be sent across the network or that takes much longer to transfer than
other similar length files.
This file can then be examined for repeated patterns that can be tested
using the
.Fl p
option.
.Sh EXAMPLES
Normally,
.Nm
works just like
.Xr ping 8
would work; the following will send ICMPv6 echo request to dst.foo.com:
.Bd -literal -offset indent
$ ping6 -n dst.foo.com
.Ed
.Pp
The following will probe hostnames for all nodes on the network link
attached to the wi0 interface.
The address
.Dq ff02::1
is named the link-local all-node multicast address, and the packet would
reach every node on the network link:
.Bd -literal -offset indent
$ ping6 -w ff02::1%wi0
.Ed
.Pp
The following will probe addresses assigned to the destination node,
dst.foo.com:
.Bd -literal -offset indent
$ ping6 -a agl dst.foo.com
.Ed
.Sh SEE ALSO
.Xr netstat 1 ,
.Xr icmp6 4 ,
.Xr inet6 4 ,
.Xr ip6 4 ,
.Xr ifconfig 8 ,
.Xr ping 8 ,
.Xr route6d 8 ,
.Xr traceroute6 8
.Rs
.%A A. Conta
.%A S. Deering
.%T "Internet Control Message Protocol (ICMPv6) for the Internet Protocol Version 6 (IPv6) Specification"
.%N RFC 2463
.%D December 1998
.Re
.Rs
.%A Matt Crawford
.%T "IPv6 Node Information Queries"
.%N draft-ietf-ipngwg-icmp-name-lookups-09.txt
.%D May 2002
.%O work in progress material
.Re
.Sh HISTORY
The
.Xr ping 8
command first appeared in
.Bx 4.3 .
The
.Nm
command with IPv6 support first appeared in the WIDE Hydrangea IPv6
protocol stack kit.
.Sh BUGS
.\" except for bsdi
.Nm
is intentionally separate from
.Xr ping 8 .
