#	$OpenBSD: Makefile,v 1.4 2002/04/08 21:40:25 miod Exp $
#	$NetBSD: Makefile,v 1.3 1995/09/06 21:36:38 jtc Exp $

MAN=	MAKEDEV.8 boot_alpha.8
MLINKS=	MAKEDEV.8 makedev.8
MANSUBDIR=alpha

.include <bsd.prog.mk>
