/*	$OpenBSD: tk_extern.h,v 1.3 2002/02/16 21:27:58 millert Exp $	*/

int tk_addstr(SCR *, const char *, size_t);
int tk_attr(SCR *, scr_attr_t, int);
int tk_baud(SCR *, u_long *);
int tk_bell(SCR *);
int tk_clrtoeol(SCR *);
int tk_cursor(SCR *, size_t *, size_t *);
int tk_deleteln(SCR *);
int tk_ex_adjust(SCR *, exadj_t);
int tk_insertln(SCR *);
int tk_keyval(SCR *, scr_keyval_t, CHAR_T *, int *);
int tk_move(SCR *, size_t, size_t);
int tk_refresh(SCR *, int);
int tk_rename(SCR *);
int tk_suspend(SCR *, int *);
void tk_usage(void);
int tk_event(SCR *, EVENT *, u_int32_t, int);
int tk_key(ClientData, Tcl_Interp *, int, char *[]);
int tk_screen(SCR *, u_int32_t);
int tk_quit(GS *);
int tk_term_init(SCR *);
int tk_term_end(GS *);
int tk_fmap(SCR *, seq_t, CHAR_T *, size_t, CHAR_T *, size_t);
int tk_optchange(SCR *, int, char *, u_long *);
int tk_ssize(SCR *, int, size_t *, size_t *, int *);
int tk_op(ClientData, Tcl_Interp *, int, char *[]);
int tk_opt_init(ClientData, Tcl_Interp *, int, char *[]);
int tk_opt_set(ClientData, Tcl_Interp *, int, char *[]);
int tk_version(ClientData, Tcl_Interp *, int, char *[]);
void tk_msg(SCR *, mtype_t, char *, size_t);
