# $OpenBSD: Makefile,v 1.11 2013/08/10 09:07:39 ajacoutot Exp $

SUBDIR=	libasn1 libgssapi libhdb libkadm5clnt libkadm5srv \
	libkafs libkrb5 libroken libsl libvers libkdc \
	libwind libheimbase libheimipcc libheimipcs \
	libcom_err

.include <bsd.subdir.mk>
