# $OpenBSD: Makefile,v 1.9 2013/06/19 19:36:42 robert Exp $

SUBDIR=	libasn1 libgssapi libhdb \
	libkadm5clnt libkadm5srv libkafs5 libkrb5 \
	libroken libsl libvers libkdc libwind libheimbase libheimipcc libheimipcs \
	libcom_err

.include <bsd.subdir.mk>
