# $OpenBSD: Makefile,v 1.2 1996/10/04 22:35:34 niklas Exp $
# $NetBSD: Makefile,v 1.1.2.2 1996/07/31 16:08:59 jtc Exp $

PROG=loadkmap
NOMAN=loadkmap
BINDIR=/usr/sbin
SUBDIR=din sw us

.include <bsd.prog.mk>
