# $OpenBSD: Makefile,v 1.9 2015/01/24 01:59:40 schwarze Exp $

REGRESS_TARGETS	 = breaking broken empty literal lonelyRE
REGRESS_TARGETS	+= nested noRE REarg width
LINT_TARGETS	 = lonelyRE noRE REarg

.include <bsd.regress.mk>
