# $OpenBSD: Makefile,v 1.10 2015/02/06 07:12:34 schwarze Exp $

REGRESS_TARGETS	 = breaking broken empty literal lonelyRE
REGRESS_TARGETS	+= nested noRE REarg width
LINT_TARGETS	 = empty lonelyRE noRE REarg

.include <bsd.regress.mk>
