# !!!!!!!   DO NOT EDIT THIS FILE   !!!!!!!
# This file is machine-generated by lib/unicore/mktables from the Unicode
# database, Version 6.2.0.  Any changes made here will be lost!

# !!!!!!!   INTERNAL PERL USE ONLY   !!!!!!!
# This file is for internal use by core Perl only.  The format and even the
# name or existence of this file are subject to change without notice.  Don't
# use it directly.


return <<'END';
00B2	00B3
00B9		
1369	1371
19DA		
2070		
2074	2079
2080	2089
2460	2468
2474	247C
2488	2490
24EA		
24F5	24FD
24FF		
2776	277E
2780	2788
278A	2792
10A40	10A43
10E60	10E68
11052	1105A
1F100	1F10A
END
