.\"	$OpenBSD: ifconfig.8,v 1.99 2005/02/15 19:45:22 reyk Exp $
.\"	$NetBSD: ifconfig.8,v 1.11 1996/01/04 21:27:29 pk Exp $
.\"     $FreeBSD: ifconfig.8,v 1.16 1998/02/01 07:03:29 steve Exp $
.\"
.\" Copyright (c) 1983, 1991, 1993
.\"	The Regents of the University of California.  All rights reserved.
.\"
.\" Redistribution and use in source and binary forms, with or without
.\" modification, are permitted provided that the following conditions
.\" are met:
.\" 1. Redistributions of source code must retain the above copyright
.\"    notice, this list of conditions and the following disclaimer.
.\" 2. Redistributions in binary form must reproduce the above copyright
.\"    notice, this list of conditions and the following disclaimer in the
.\"    documentation and/or other materials provided with the distribution.
.\" 3. Neither the name of the University nor the names of its contributors
.\"    may be used to endorse or promote products derived from this software
.\"    without specific prior written permission.
.\"
.\" THIS SOFTWARE IS PROVIDED BY THE REGENTS AND CONTRIBUTORS ``AS IS'' AND
.\" ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE
.\" IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE
.\" ARE DISCLAIMED.  IN NO EVENT SHALL THE REGENTS OR CONTRIBUTORS BE LIABLE
.\" FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL
.\" DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS
.\" OR SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION)
.\" HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT
.\" LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY
.\" OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF
.\" SUCH DAMAGE.
.\"
.\"     @(#)ifconfig.8	8.4 (Berkeley) 6/1/94
.\"
.Dd September 3, 1998
.Dt IFCONFIG 8
.Os
.Sh NAME
.Nm ifconfig
.Nd configure network interface parameters
.Sh SYNOPSIS
.Nm ifconfig
.Op Ar interface
.Op Ar address_family
.Oo
.Ar address
.Op Ar dest_address
.Oc
.Op Ar parameters
.Nm ifconfig
.Fl A | Am | a | am
.Op Ar address_family
.Nm ifconfig
.Fl C
.Nm ifconfig
.Fl m
.Ar interface
.Op Ar address_family
.Nm ifconfig
.Ar interface
.Cm create
.Nm ifconfig
.Ar interface
.Cm destroy
.Nm
.Ar interface
.Cm group
.Ar group-name
.Nm ifconfig
.Ar carp-interface
.Cm vhid
.Ar host-id
.Cm carpdev
.Ar iface
.Nm ifconfig
.Ar pfsync-interface
.Cm syncpeer
.Ar peer_address
.Cm syncdev
.Ar iface
.Nm
.Ar pppoe-interface
.Oo
.Cm pppoedev
.Ar parent-interface
.Oc
.Oo
.Cm pppoesvc
.Ar service
.Oc
.Oo
.Cm pppoeac
.Ar access-concentrator
.Oc
.Nm ifconfig
.Ar tunnel-interface
.Cm tunnel
.Ar src_address dest_address
.Nm ifconfig
.Ar tunnel-interface
.Cm deletetunnel
.Nm ifconfig
.Ar vlan-interface
.Cm vlan
.Ar vlan-tag
.Cm vlandev
.Ar parent-interface
.Sh DESCRIPTION
The
.Nm
utility is used to assign an address
to a network interface and/or configure
network interface parameters.
.Nm
must be used at boot-time to define the network address
of each interface present on a machine; it may also be used at
a later time to redefine an interface's address
or other operating parameters.
To configure a bridge interface, use the
.Xr brconfig 8
program instead.
.Pp
.Nm
displays the current configuration for a network interface
when no optional parameters are supplied.
If a protocol family is specified,
.Nm
will report only the details specific to that protocol family.
If no parameters are provided, a summary of all interfaces is provided.
.Pp
Only the superuser may modify the configuration of a network interface.
.Pp
The options are as follows:
.Bl -tag -width Ds
.It Fl A
Causes full interface alias information for each interface to
be displayed.
.It Fl Am
The same as the
.Fl A
option,
but additionally prints interface media information for all interfaces.
.It Fl a
Causes
.Nm
to print information on all interfaces.
The protocol family may be specified as well.
This is the default, if no parameters are given to
.Nm .
.It Fl am
The same as the
.Fl a
option,
but additionally prints interface media information for all interfaces.
.It Fl C
Print the names of all network pseudo-devices that
can be created dynamically at runtime using
.Cm ifconfig create .
.It Fl m Ar interface
Print media information for a given
.Ar interface .
.It Ar address
For the
.Tn DARPA
Internet
family,
the address is either a host name present in the host name database,
.Xr hosts 5 ,
or a
.Tn DARPA
Internet address expressed in the Internet standard
.Dq dot notation .
.Pp
Internet version 6 addresses are either a host name present
in the host name database,
.Xr hosts 5 ,
or an Internet version 6 address in standard colon separated form, as
described in the
.Xr inet 3
manual page.
.Pp
For the Xerox Network Systems(tm) and Internetwork Packet Exchange families,
addresses are of the form
.Dq net:a.b.c.d.e.f ,
where
.Dq net
is the assigned network number (in decimal),
and each of the six bytes of the host number,
.Dq a
through
.Dq f ,
are specified in hexadecimal.
The host number may be omitted on Ethernet interfaces,
which use the hardware physical address,
and on interfaces other than the first.
.Pp
.Tn AppleTalk
(LLAP) addresses are specified as
.Dq nn.na
.Pq Dq Network Number.Node Address .
Node addresses are divided into two classes: User Node IDs and Server Node IDs.
1\-127($01\-$7F) are for User Node IDs while 128\-254($80\-$FE)
are used for Server Node IDs.
Node 0($00) is not allowed (unknown)
while Node 255($FF) is reserved for the AppleTalk broadcast hardware
address (broadcast ID).
.Pp
.Tn IPX
addresses are specified as listed in the
.Xr ipx 3
manual page.
.It Ar address_family
Specifies the address family
which affects interpretation of the remaining parameters.
Since an interface can receive transmissions in differing protocols
with different naming schemes, specifying the address family is recommended.
The address or protocol families currently
supported are
.Dq inet ,
.Dq inet6 ,
.Dq atalk ,
.Dq ipx ,
and
.Dq ns .
.It Ar interface
The
.Ar interface
parameter is a string of the form
.Dq name unit ,
for example,
.Dq en0 .
If no optional parameters are supplied, this string can instead be just
.Dq name .
In this case, all interfaces of that type will be displayed.
For example,
.Dq carp
will display the current configuration of all
.Xr carp 4
interfaces.
.El
.Pp
The following parameters may be set with
.Nm :
.Bl -tag -width dest_addressxx
.It Cm 802.2 802.2tr 802.3 snap EtherII
Set the
.Xr ipx 3
frame type to be either 802.2, 802.2tr, 802.3, snap, or Ethernet II.
.It Cm advbase Ar n
If the driver is a
.Xr carp 4
pseudo-device, set the base advertisement interval to
.Ar n
seconds.
This is an 8-bit number; the default value is 1 second.
.It Cm advskew Ar n
If the driver is a
.Xr carp 4
pseudo-device, skew the advertisement interval by
.Ar n .
This is an 8-bit number; the default value is 0.
.Pp
Taken together the
.Cm advbase
and
.Cm advskew
indicate how frequently, in seconds, the host will advertise the fact that it
considers itself master of the virtual host.
The formula is
.Cm advbase
+
.Cm ( advskew
/ 255 ).
If the master does not advertise within three times this interval, this host
will begin advertising as master.
.It Cm alias
Establish an additional network address for this interface.
This is sometimes useful when changing network numbers, and
one wishes to accept packets addressed to the old interface.
.It Fl alias
Remove the specified network address alias.
.It Cm anycast
(inet6 only)
Set the IPv6 anycast address bit.
.It Fl anycast
(inet6 only)
Clear the IPv6 anycast address bit.
.It Cm arp
Enable the use of the Address Resolution Protocol
(``ARP'';
see
.Xr arp 4 )
in mapping
between network level addresses and link level addresses (default).
This is currently implemented for mapping between
.Tn DARPA
Internet
addresses and Ethernet addresses.
.It Fl arp
Disable the use of ARP.
.It Cm broadcast Ar addr
(inet only)
Specify the address to use to represent broadcasts to the
network.
The default broadcast address is the address with a host part of all 1's.
.It Cm bssid Ar bssid
(IEEE 802.11 devices only)
Set the desired BSSID for IEEE 802.11-based wireless network interfaces.
.It Fl bssid
(IEEE 802.11 devices only)
Unset the desired BSSID for IEEE 802.11-based wireless network interfaces.
The interface will automatically select a BSSID in this mode, which is
the default.
.It Cm carpdev Ar iface
If the driver is a
.Xr carp 4
pseudo-device, attach it to
.Ar iface .
If not specified, the kernel will attempt to select an interface with
a subnet matching that of the carp interface.
.It Cm chan Ar n
(IEEE 802.11 devices only)
Set the channel (radio frequency) to be used for IEEE 802.11-based
wireless network interfaces from the given channel ID
.Ar n .
.It Fl chan
(IEEE 802.11 devices only)
Unset the desired channel to be used for IEEE 802.11-based wireless
network interfaces.
It doesn't affect the channel to be created for IBSS or hostap mode.
.It Cm create
Create the specified network pseudo-device.
At least the following devices can be created on demand:
.Pp
.Xr bridge 4 ,
.Xr carp 4 ,
.Xr gif 4 ,
.Xr gre 4 ,
.Xr lo 4 ,
.Xr ppp 4 ,
.Xr pppoe 4 ,
.Xr sl 4 ,
.Xr tun 4 ,
.Xr vlan 4
.It Cm debug
Enable driver-dependent debugging code; usually, this turns on
extra console error logging.
.It Fl debug
Disable driver-dependent debugging code.
.It Cm delete
Remove the network address specified.
This would be used if you incorrectly specified an alias, or it
was no longer needed.
If you have incorrectly set an NS address having the side effect
of specifying the host portion, removing all NS addresses will
allow you to respecify the host portion.
.It Cm deletetunnel
Removes the source and destination tunnel addresses,
configured onto a tunnel interface.
.It Cm description Ar value
Specify a description of the interface.
This can be used to label interfaces in situations where they may
otherwise be difficult to distinguish.
.It Ar dest_address
Specify the address of the correspondent on the other end
of a point-to-point link.
.It Cm destroy
Destroy the specified network pseudo-device.
.It Cm down
Mark an interface
.Dq down .
When an interface is marked
.Dq down ,
the system will not attempt to
transmit messages through that interface.
If possible, the interface will be reset to disable reception as well.
This action automatically disables routes using the interface.
.It Cm group Ar group-name
Assign the interface to a
.Dq group .
Any interface can be in multiple groups.
Interface groups are described in
.Xr netintro 4 .
.It Cm -group Ar group-name
Remove the interface from the given
.Dq group .
.It Cm eui64
(inet6 only)
Fill the interface index
.Pq the lowermost 64th bit of an IPv6 address
automatically.
.It Cm instance Ar minst
Set the media instance to
.Ar minst .
This is useful for devices which have multiple physical layer interfaces
(PHYs).
Setting the instance on such devices may not be strictly required
by the network interface driver as the driver may take care of this
automatically; see the driver's manual page for more information.
.It Cm ipdst Ar addr
This is used to specify an Internet host which is willing to receive
IP packets encapsulating NS packets bound for a remote network.
An apparent point-to-point link is constructed, and
the address specified will be taken as the NS address and network
of the destination.
IP encapsulation of Connectionless Network Protocol
(``CLNP'')
packets is done differently.
.It Cm link[0-2]
Enable special processing of the link level of the interface.
These three options are interface specific in actual effect; however,
they are in general used to select special modes of operation.
An example
of this is to enable SLIP compression, or to select the connector type
for some Ethernet cards.
Refer to the man page for the specific driver for more information.
.It Fl link[0-2]
Disable special processing at the link level with the specified interface.
.It Cm maxupd Ar n
If the driver is a
.Xr pfsync 4
pseudo-device, indicate the maximum number
of updates for a single state which can be collapsed into one.
This is an 8-bit number; the default value is 128.
.It Cm media Ar type
Set the media type of the interface to
.Ar type .
Some interfaces support the mutually exclusive use of one of several
different physical media connectors.
For example, a 10Mb/s Ethernet interface might support the use of either
.Tn AUI
or twisted pair connectors.
Setting the media type to
.Dq 10base5
or
.Dq AUI
would change the currently active connector to the AUI port.
Setting it to
.Dq 10baseT
or
.Dq UTP
would activate twisted pair.
Refer to the interface's driver-specific man page for a complete
list of the available types,
or use
.Bd -literal -offset indent
$ ifconfig -m interface
.Ed
.Pp
for a listing of choices.
.It Cm mediaopt Ar opts
Set the specified media options on the interface.
.Ar opts
is a comma delimited list of options to apply to the interface.
Refer to the interface's driver-specific man page for a complete
list of available options,
or use
.Bd -literal -offset indent
$ ifconfig -m interface
.Ed
.Pp
for a listing of choices.
.It Fl mediaopt Ar opts
Disable the specified media options on the interface.
.It Cm metric Ar nhops
Set the routing metric of the interface to
.Ar nhops ,
default 0.
The routing metric is used by the routing protocol
(see
.Xr routed 8 ) .
Higher metrics have the effect of making a route
less favorable; metrics are counted as addition hops
to the destination network or host.
.It Cm mode Ar mode
If the driver for the interface supports the media selection system,
set the specified operating mode on the interface to the given
.Ar mode .
For IEEE 802.11 wireless interfaces that support multiple operating modes,
this directive is used to select between 802.11a
.Pq Dq 11a ,
802.11b
.Pq Dq 11b ,
and 802.11g
.Pq Dq 11g
operating modes.
.It Cm mtu Ar value
Set the MTU for this device to the given
.Ar value .
Cloned routes will inherit this value as a default.
Currently, not all devices support setting the MTU.
.It Cm netmask Ar mask
(inet and inet6)
Specify how much of the address to reserve for subdividing
networks into subnetworks.
The mask includes the network part of the local address
and the subnet part, which is taken from the host field of the address.
The mask can be specified as a single hexadecimal number
with a leading 0x, with a dot-notation Internet address,
or with a pseudo-network name listed in the network table
.Xr networks 5 .
The mask contains 1's for the bit positions in the 32-bit address
which are to be used for the network and subnet parts,
and 0's for the host part.
The mask should contain at least the standard network portion,
and the subnet field should be contiguous with the network
portion.
.\" see
.\" Xr eon 5 .
.It Cm nwid Ar id
(IEEE 802.11 devices only)
Configure network ID for IEEE 802.11-based wireless network interfaces.
The
.Ar id
can either be any text string up to 32 characters in length,
or a series of hexadecimal digits up to 64 digits.
The empty string allows the interface to connect to any available
access points.
.It Cm nwkey Ar key
(IEEE 802.11 devices only)
Enable WEP encryption for IEEE 802.11-based wireless network interfaces
using the specified
.Ar key .
The
.Ar key
can either be a string, a series of hexadecimal digits (preceded by
.So 0x Sc ) ,
or a set of keys
of the form
.Dq n:k1,k2,k3,k4
where
.Sq n
specifies which of the keys will be used for transmitted packets,
and the four keys,
.Dq k1
through
.Dq k4 ,
are configured as WEP keys.
If a set of keys is specified, a comma
.Pq Sq \&,
within the key must be escaped with a backslash.
Note that if multiple keys are used, their order must be the same within
the network.
For IEEE 802.11 wireless networks, the length of each key is restricted to
40 bits, i.e. a 5-character string or 10 hexadecimal digits.
WaveLAN/IEEE Gold and newer Prism cards will also accept a 104-bit
(13-character) key.
.It Fl nwkey
(IEEE 802.11 devices only)
Disable WEP encryption for IEEE 802.11-based wireless network interfaces.
.It Cm nwkey Cm persist
(IEEE 802.11 devices only)
Enable WEP encryption for IEEE 802.11-based wireless network interfaces
with the persistent key stored in the network card.
.It Cm nwkey Cm persist : Ns Ar key
(IEEE 802.11 devices only)
Write
.Ar key
to the persistent memory of the network card, and
enable WEP encryption for IEEE 802.11-based wireless network interfaces
using that
.Ar key .
.It Cm pass Ar passphrase
If the driver is a
.Xr carp 4
pseudo-device, set the authentication key to
.Ar passphrase .
There is no passphrase by default.
.It Cm phase Ar n
The argument
.Ar n
specifies the version (phase) of the
AppleTalk network attached to the interface.
Values of 1 or 2 are permitted.
.It Cm pltime Ar n
(inet6 only)
Set preferred lifetime for the address.
.It Cm powersave
(IEEE 802.11 devices only)
Enable 802.11 power saving mode.
.It Fl powersave
(IEEE 802.11 devices only)
Disable 802.11 power saving mode.
.It Cm powersavesleep Ar duration
(IEEE 802.11 devices only)
Set the receiver sleep duration (in milliseconds) for 802.11 power saving mode.
.It Cm pppoeac Ar access-concentrator
Set the name of the access-concentrator for the
.Xr pppoe 4
interface.
.It Fl pppoeac
Clear a previously set access-concentrator name.
.It Cm pppoedev Ar parent-interface
Set the name of the interface through which
.Xr pppoe 4
packets will be transmitted and received.
.It Cm pppoesvc Ar service
Set the service name of the
.Xr pppoe 4
interface.
.It Fl pppoesvc
Clear a previously set service name.
.It Cm prefixlen Ar n
(inet and inet6 only)
Effect is similar to
.Cm netmask ,
but you can specify prefix length by digits.
.It Cm range Ar netrange
Under AppleTalk, set the interface to respond to a
.Ar netrange
of the form
.Dq startnet-endnet .
AppleTalk uses this scheme instead of
netmasks though
.Ox
implements it internally as a set of netmasks.
.It Cm state Ar state
Explicitly force the
.Xr carp 4
pseudo-device to enter this state.
Valid states are
.Ar init ,
.Ar backup ,
and
.Ar master .
.It Cm syncdev Ar iface
If the driver is a
.Xr pfsync 4
pseudo-device, use the specified interface
to send and receive pfsync state synchronisation messages.
.It Fl syncdev
If the driver is a
.Xr pfsync 4
pseudo-device, stop sending pfsync state
synchronisation messages over the network.
.It Cm syncpeer Ar peer_address
If the driver is a
.Xr pfsync 4
pseudo-device, make the pfsync link point-to-point rather than using
multicast to broadcast the state synchronisation messages.
The peer_address is the IP address of the other host taking part in
the pfsync cluster.
With this option,
.Xr pfsync 4
traffic can be protected using
.Xr ipsec 4 .
.It Fl syncpeer
If the driver is a
.Xr pfsync 4
pseudo-device, broadcast the packets using multicast.
.It Cm tentative
(inet6 only)
Set the IPv6 tentative address bit.
.It Fl tentative
(inet6 only)
Clear the IPv6 tentative address bit.
.It Cm timeslot Ar timeslot_range
Set the timeslot range map, which is used to control which channels
an interface device uses.
.It Cm txpower Ar dBm
(IEEE 802.11 devices only)
Set the transmit power for IEEE 802.11-based wireless network interfaces.
The driver will disable any auto level and transmit power controls in this
mode.
.It Fl txpower
(IEEE 802.11 devices only)
Disable manual transmit power mode and enable any auto level and transmit
power controls.
.It Cm tunnel Ar src_address dest_address
Set the source and destination tunnel addresses on a tunnel interface,
including
.Xr gif 4 .
Packets routed to this interface will be encapsulated in
IPv4 or IPv6, depending on the source and destination address families.
Both addresses must be of the same family.
.It Cm up
Mark an interface
.Dq up .
This may be used to enable an interface after an
.Cm ifconfig down .
It happens automatically when setting the first address on an interface.
If the interface was reset when previously marked down,
the hardware will be re-initialized.
.It Cm vhid Ar n
If the driver is a
.Xr carp 4
pseudo-device, set the virtual host ID to
.Ar n .
Acceptable values are 1 to 255.
.It Cm vlan Ar vlan_tag
If the interface is a
.Xr vlan 4
pseudo-interface, set the vlan tag value
to
.Ar vlan_tag .
This value is a 12-bit number which is used to create an 802.1Q
vlan header for packets sent from the vlan interface.
Note that
.Cm vlan
and
.Cm vlandev
must both be set at the same time.
.It Cm vlandev Ar iface
If the interface is a
.Xr vlan 4
pseudo-device, associate physical interface
.Ar iface
with it.
Packets transmitted through the vlan interface will be
diverted to the specified physical interface
.Ar iface
with 802.1Q vlan encapsulation.
Packets with 802.1Q encapsulation received
by the parent interface with the correct vlan tag will be diverted to
the associated vlan pseudo-interface.
The vlan interface is assigned a
copy of the parent interface's flags and the parent's Ethernet address.
.Cm vlandev
and
.Cm vlan
must both be set at the same time.
If the vlan interface already has
a physical interface associated with it, this command will fail.
To change the association to another physical interface, the existing
association must be cleared first.
.Pp
Note: if the
.Ar link0
flag is set on the vlan interface, the vlan pseudo-interface's
behavior changes;
.Ar link0
tells the vlan interface that the
parent interface supports insertion and extraction of vlan tags on its
own (usually in firmware) and that it should pass packets to and from
the parent unaltered.
.It Fl vlandev
If the driver is a
.Xr vlan 4
pseudo-device, disassociate the physical interface
from it.
This breaks the link between the vlan interface and its parent,
clears its vlan tag, flags, and link address, and shuts the interface down.
.It Cm vltime Ar n
(inet6 only)
Set valid lifetime for the address.
.El
.Sh EXAMPLES
Assign the
.Xr inet 3
address of 192.168.1.10 with a network mask of
255.255.255.0 to interface fxp0:
.Pp
.Dl # ifconfig fxp0 inet 192.168.1.10 netmask 255.255.255.0
.Pp
Assign the
.Xr ipx 3
address of 12625920 specified in decimal to interface fxp0:
.Pp
.Dl # ifconfig fxp0 ipx 12625920
.Pp
Assign the AppleTalk network 39108 and server node 128 with a network
range of 39107\-39109 to interface fxp0 on a phase 2 AppleTalk network:
.Pp
.Dl # ifconfig fxp0 atalk 39108.128 range 39107-39109 phase 2
.Pp
Configure the xl0 interface to use 10baseT:
.Pp
.Dl # ifconfig xl0 media 10baseT
.Pp
Configure the xl0 interface to use 100baseTX, full duplex:
.Pp
.Dl # ifconfig xl0 media 100baseTX mediaopt full-duplex
.Pp
Label the em0 interface as an uplink:
.Pp
.Dl # ifconfig em0 description \&"Uplink to Gigabit Switch 2\&"
.Pp
Configure the vlan0 interface for IP address 192.168.254.1, vlan tag 4,
and vlan parent device fxp0:
.Pp
.Dl # ifconfig vlan0 192.168.254.1 vlan 4 vlandev fxp0
.Pp
Configure the carp0 interface for IP address 192.168.10.1, virtual host ID 1,
attached to the vlan0 interface:
.Pp
.Dl # ifconfig carp0 vhid 1 carpdev vlan0 192.168.10.1
.Pp
Create the gif1 network interface:
.Pp
.Dl # ifconfig gif1 create
.Pp
Destroy the gif1 network interface:
.Pp
.Dl # ifconfig gif1 destroy
.Sh DIAGNOSTICS
Messages indicating the specified interface does not exist, the
requested address is unknown, or the user is not privileged and
tried to alter an interface's configuration.
.Sh SEE ALSO
.Xr netstat 1 ,
.Xr inet 3 ,
.Xr ipx 3 ,
.Xr arp 4 ,
.Xr bridge 4 ,
.Xr carp 4 ,
.Xr gif 4 ,
.Xr gre 4 ,
.Xr ifmedia 4 ,
.Xr inet 4 ,
.Xr lo 4 ,
.Xr netintro 4 ,
.Xr pfsync 4 ,
.Xr ppp 4 ,
.Xr pppoe 4 ,
.Xr sl 4 ,
.Xr tun 4 ,
.Xr vlan 4 ,
.Xr hostname.if 5 ,
.Xr hosts 5 ,
.Xr networks 5 ,
.Xr brconfig 8 ,
.Xr rc 8 ,
.Xr routed 8
.Sh HISTORY
The
.Nm
command appeared in
.Bx 4.2 .
