# !!!!!!!   DO NOT EDIT THIS FILE   !!!!!!! 
# This file is built by ./mktables from e.g. UnicodeData.txt.
# Any changes made here will be lost!

# This file is for internal use by the Perl program only.  The format and even
# name or existence of this file are subject to change without notice.  Don't
# use it directly.

#
# DecompositionType category 'Vertical'
#
return <<'END';
309F		
30FF		
FE10	FE19	
FE30	FE44	
FE47	FE48	
END
