$OpenBSD: OpenBSD::PkgSpec.pod,v 1.4 2007/05/12 14:54:46 espie Exp $

=head1 NAME

OpenBSD::PkgSpec - C<packages-specs(7)> handling

=head1 SYNOPSIS

   use OpenBSD::PkgSpec;
   my $spec = OpenBSD::PkgSpec->new($pattern);
   @sublist = $spec->match(@list);
   # alternatively
   @sublist = $spec->match_ref(\@list);

=head1 DESCRIPTION

C<OpenBSD::PkgSpec> is the canonical interface to C<packages-specs(7)>
handling.

A package specification C<$pattern> is a string that can be used to
extract matching package names from a C<@list>.  The resulting list
C<@sublist> will only hold the package names that match the specification.

For performance reason, the result may contain duplicates.
