#ifndef HTNESTEDLIST_H
#define HTNESTEDLIST_H

#define HTML_OL1   HTML_ELEMENTS+1
#define HTML_OL2   HTML_ELEMENTS+2
#define HTML_OL3   HTML_ELEMENTS+3
#define HTML_OL4   HTML_ELEMENTS+4
#define HTML_OL5   HTML_ELEMENTS+5
#define HTML_OL6   HTML_ELEMENTS+6

#define HTML_MENU1   HTML_ELEMENTS+7
#define HTML_MENU2   HTML_ELEMENTS+8
#define HTML_MENU3   HTML_ELEMENTS+9
#define HTML_MENU4   HTML_ELEMENTS+10
#define HTML_MENU5   HTML_ELEMENTS+11
#define HTML_MENU6   HTML_ELEMENTS+12

#define HTML_DL1   HTML_ELEMENTS+13
#define HTML_DL2   HTML_ELEMENTS+14
#define HTML_DL3   HTML_ELEMENTS+15
#define HTML_DL4   HTML_ELEMENTS+16
#define HTML_DL5   HTML_ELEMENTS+17
#define HTML_DL6   HTML_ELEMENTS+18

#define HTML_DLC1   HTML_ELEMENTS+19
#define HTML_DLC2   HTML_ELEMENTS+20
#define HTML_DLC3   HTML_ELEMENTS+21
#define HTML_DLC4   HTML_ELEMENTS+22
#define HTML_DLC5   HTML_ELEMENTS+23
#define HTML_DLC6   HTML_ELEMENTS+24

#define HTML_HCENTER  HTML_ELEMENTS+25
#define HTML_HLEFT    HTML_ELEMENTS+26
#define HTML_HRIGHT   HTML_ELEMENTS+27

#define HTML_DCENTER  HTML_ELEMENTS+28
#define HTML_DLEFT    HTML_ELEMENTS+29
#define HTML_DRIGHT   HTML_ELEMENTS+30

#endif /* HTNESTEDLIST_H */
