.\" $OpenBSD: switchd.8,v 1.4 2016/11/29 07:18:23 jmc Exp $
.\"
.\" Copyright (c) 2016 Reyk Floeter <reyk@openbsd.org>
.\"
.\" Permission to use, copy, modify, and distribute this software for any
.\" purpose with or without fee is hereby granted, provided that the above
.\" copyright notice and this permission notice appear in all copies.
.\"
.\" THE SOFTWARE IS PROVIDED "AS IS" AND THE AUTHOR DISCLAIMS ALL WARRANTIES
.\" WITH REGARD TO THIS SOFTWARE INCLUDING ALL IMPLIED WARRANTIES OF
.\" MERCHANTABILITY AND FITNESS. IN NO EVENT SHALL THE AUTHOR BE LIABLE FOR
.\" ANY SPECIAL, DIRECT, INDIRECT, OR CONSEQUENTIAL DAMAGES OR ANY DAMAGES
.\" WHATSOEVER RESULTING FROM LOSS OF USE, DATA OR PROFITS, WHETHER IN AN
.\" ACTION OF CONTRACT, NEGLIGENCE OR OTHER TORTIOUS ACTION, ARISING OUT OF
.\" OR IN CONNECTION WITH THE USE OR PERFORMANCE OF THIS SOFTWARE.
.\"
.Dd $Mdocdate: November 29 2016 $
.Dt SWITCHD 8
.Os
.Sh NAME
.Nm switchd
.Nd software-defined networking (SDN) sflow controller
.Sh SYNOPSIS
.Nm switchd
.Op Fl dnv
.Op Fl c Ar cachesize
.Op Fl D Ar macro Ns = Ns Ar value
.Op Fl f Ar file
.Op Fl t Ar timeout
.Sh DESCRIPTION
.Nm
is a controller for software-defined networking (SDN) and is
compatible with the OpenFlow protocol.
.Pp
The options are as follows:
.Bl -tag -width "-c cachesize"
.It Fl c Ar cachesize
Number of MAC addresses to cache.
The default is 4096.
.It Fl D Ar macro Ns = Ns Ar value
Set a
.Ar macro
to a
.Ar value .
Macros can be referenced in the configuration files.
.It Fl d
Debug mode.
Don't detach or become a daemon.
This allows for easy monitoring of
.Nm .
.It Fl f Ar file
Specifies the configuration file.
The default is
.Pa /etc/switchd.conf .
.It Fl n
Check that the configuration is valid, but don't start the daemon.
.It Fl t Ar timeout
Timeout in seconds for learned MAC addresses.
The default is 240 seconds.
.It Fl v
Verbose mode.
Multiple
.Fl v
options increase the verbosity.
.El
.Sh FILES
.Bl -tag -width "/etc/switchd.conf" -compact
.It Pa /etc/switchd.conf
Default configuration file.
.El
.Sh SEE ALSO
.Xr switchd.conf 5 ,
.Xr switchctl 8
.Sh STANDARDS
.Rs
.%A Open Networking Foundation (ONF)
.%D December 31, 2009
.%R Version 1.0.0 (Wire Protocol 0x01)
.%T OpenFlow Switch Specification
.Re
.Pp
.Rs
.%A Open Networking Foundation (ONF)
.%D March 26, 2015
.%R Version 1.3.5 (Protocol version 0x04)
.%T OpenFlow Switch Specification
.Re
.Sh HISTORY
The
.Nm
program first appeared in
.Ox 6.1 .
.Sh AUTHORS
The
.Nm
program was written by
.An Reyk Floeter Aq Mt reyk@openbsd.org .
