/* $OpenBSD: cond_int.h,v 1.6 2010/07/19 19:46:44 espie Exp $ */

/* List of all keywords recognized by the make parser */
#define COND_IF		"if"
#define COND_IFDEF	"ifdef"
#define COND_IFNDEF	"ifndef"
#define COND_IFMAKE	"ifmake"
#define COND_IFNMAKE	"ifnmake"
#define COND_ELSE	"else"
#define COND_ELIF	"elif"
#define COND_ELIFDEF	"elifdef"
#define COND_ELIFNDEF	"elifndef"
#define COND_ELIFMAKE	"elifmake"
#define COND_ELIFNMAKE	"elifnmake"
#define COND_ENDIF	"endif"
#define COND_FOR	"for"
#define COND_ENDFOR	"endfor"
#define COND_INCLUDE	"include"
#define COND_UNDEF	"undef"
#define COND_POISON	"poison"
