# !!!!!!!   DO NOT EDIT THIS FILE   !!!!!!!
# This file is machine-generated by lib/unicore/mktables from the Unicode
# database, Version 5.2.0.  Any changes made here will be lost!

# !!!!!!!   INTERNAL PERL USE ONLY   !!!!!!!
# This file is for internal use by the Perl program only.  The format and even
# the name or existence of this file are subject to change without notice.
# Don't use it directly.

# This file returns the 34 code points in Unicode Version 5.2.0 that match
# any of the following regular expression constructs:
# 
#         \p{Line_Break=Exclamation}
#         \p{Lb=EX}
#         \p{Is_Line_Break=Exclamation}
#         \p{Is_Lb=EX}
# 
# perluniprops.pod should be consulted for the syntax rules for any of these,
# including if adding or subtracting white space, underscore, and hyphen
# characters matters or doesn't matter, and other permissible syntactic
# variants.  Upper/lower case distinctions never matter.
# 
# A colon can be substituted for the equals sign, and anything to the left of
# the equals (or colon) can be combined with anything to the right.  Thus,
# for example,
#         \p{Is_Lb: Exclamation}
# is also valid.
# 
# The format of the lines of this file is: START\tSTOP\twhere START is the
# starting code point of the range, in hex; STOP is the ending point, or if
# omitted, the range has just one code point.  Numbers in comments in
# [brackets] indicate how many code points are in the range.

return <<'END';
0021		
003F		
05C6		
061B		
061E	061F	 # [2]
06D4		
07F9		
0F0D	0F11	 # [5]
0F14		
1802	1803	 # [2]
1808	1809	 # [2]
1944	1945	 # [2]
2762	2763	 # [2]
2CF9		
2CFE		
2E2E		
A60E		
A876	A877	 # [2]
FE15	FE16	 # [2]
FE56	FE57	 # [2]
FF01		
FF1F		
END
