# !!!!!!!   DO NOT EDIT THIS FILE   !!!!!!!
# This file is machine-generated by lib/unicore/mktables from the Unicode
# database, Version 5.2.0.  Any changes made here will be lost!

# !!!!!!!   INTERNAL PERL USE ONLY   !!!!!!!
# This file is for internal use by the Perl program only.  The format and even
# the name or existence of this file are subject to change without notice.
# Don't use it directly.

# This file returns the 43 code points in Unicode Version 5.2.0 that match
# any of the following regular expression constructs:
# 
#         \p{Line_Break=Prefix_Numeric}
#         \p{Lb=PR}
#         \p{Is_Line_Break=Prefix_Numeric}
#         \p{Is_Lb=PR}
# 
# perluniprops.pod should be consulted for the syntax rules for any of these,
# including if adding or subtracting white space, underscore, and hyphen
# characters matters or doesn't matter, and other permissible syntactic
# variants.  Upper/lower case distinctions never matter.
# 
# A colon can be substituted for the equals sign, and anything to the left of
# the equals (or colon) can be combined with anything to the right.  Thus,
# for example,
#         \p{Is_Lb: Prefix_Numeric}
# is also valid.
# 
# The format of the lines of this file is: START\tSTOP\twhere START is the
# starting code point of the range, in hex; STOP is the ending point, or if
# omitted, the range has just one code point.  Numbers in comments in
# [brackets] indicate how many code points are in the range.

return <<'END';
0024		
002B		
005C		
00A3	00A5	 # [3]
00B1		
09FB		
0AF1		
0BF9		
0E3F		
17DB		
20A0	20A6	 # [7]
20A8	20B5	 # [14]
20B7	20B8	 # [2]
2116		
2212	2213	 # [2]
FE69		
FF04		
FFE1		
FFE5	FFE6	 # [2]
END
