$NetBSD: To.Do,v 1.4 1995/06/09 06:03:45 phil Exp $

This is the "To Do" list for NetBSD/pc532
  (Order is not in order of importance.)

- improve scn driver (integrate mods from Phil Bunde)

- get kernel debugger working

- get the dp scsi driver working

- write an aic scsi driver

- improve copyin/out and friends

- get gdb working (partially done)

- ptrace syscall (?)

- improve bim (detect a non-writeable disklabel, ...)

- man4 man pages

- man8 man pages

- mods to better support ufs boot loader

- integrate printer driver from matthias  (partially done)

- verify all devices including vn, tun, ...

- integrate other machine independent "devices"

- write a bim.8

- find or write a "usable" comm package to replace kermit for
	initial downloading.

- find out why profiling does not accumulate any time

