#	$OpenBSD: Makefile,v 1.5 2010/10/18 04:07:50 deraadt Exp $

.PATH: ${.CURDIR}/../ramdisk
RAMDISK=RAMDISK_CD
FLOPPYSIZE=11520
FLOPPYTYPE=floppy576
XNAME=cdrom
NOFS=1

.include "${.CURDIR}/../common/Makefile.inc"

LISTS+=		${.CURDIR}/list.local

