.\" Copyright (c) 1992, 1993
.\"	The Regents of the University of California.  All rights reserved.
.\"
.\" This software was developed by the Computer Systems Engineering group
.\" at Lawrence Berkeley Laboratory under DARPA contract BG 91-66 and
.\" contributed to Berkeley.
.\"
.\" Redistribution and use in source and binary forms, with or without
.\" modification, are permitted provided that the following conditions
.\" are met:
.\" 1. Redistributions of source code must retain the above copyright
.\"    notice, this list of conditions and the following disclaimer.
.\" 2. Redistributions in binary form must reproduce the above copyright
.\"    notice, this list of conditions and the following disclaimer in the
.\"    documentation and/or other materials provided with the distribution.
.\" 3. All advertising materials mentioning features or use of this software
.\"    must display the following acknowledgement:
.\"	This product includes software developed by the University of
.\"	California, Berkeley and its contributors.
.\" 4. Neither the name of the University nor the names of its contributors
.\"    may be used to endorse or promote products derived from this software
.\"    without specific prior written permission.
.\"
.\" THIS SOFTWARE IS PROVIDED BY THE REGENTS AND CONTRIBUTORS ``AS IS'' AND
.\" ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE
.\" IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE
.\" ARE DISCLAIMED.  IN NO EVENT SHALL THE REGENTS OR CONTRIBUTORS BE LIABLE
.\" FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL
.\" DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS
.\" OR SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION)
.\" HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT
.\" LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY
.\" OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF
.\" SUCH DAMAGE.
.\"
.\"	from: Header: le.4,v 1.2 92/10/13 05:31:33 leres Exp
.\"	from: @(#)le.4	8.1 (Berkeley) 6/9/93
.\"	$Id: le.4,v 1.5 1998/07/13 02:42:20 jason Exp $
.\"
.Dd June 9, 1993
.Dt LE 4 sparc
.Os
.Sh NAME
.Nm le
.Nd SPARC AMD 7990 LANCE ethernet interface
.Sh SYNOPSIS
.Cd "le* at sbus? slot ? offset ?            " Pq "sun4c onboard"
.Cd "lebuffer* at sbus? slot ? offset ?      " Pq Sbus
.Cd "le* at lebuffer?                        " Pq Sbus
.Cd "ledma0 at sbus0 slot ? offset ?         " Pq "sun4m onboard"
.Cd "le0 at ledma0                           " Pq "sun4m onboard"
.Cd "le0 at obio0 addr 0xf9000000 level 6    " Pq sun4/300
.Sh DESCRIPTION
The 
.Nm
interface provides access to the 10 Mb/s
.Tn Ethernet
network via the
.Tn AMD
Am7990
Local Area Network Controller for Ethernet
.Pq Tn LANCE
chip set.
.Pp
Each of the host's network addresses
is specified at boot time with an
.Dv SIOCSIFADDR
.Xr ioctl .
The
.Nm
interface employs the address resolution protocol described in
.Xr arp 4
to dynamically map between Internet and
.Tn Ethernet
addresses on the local network.
.Pp
The sun4m interface has two types of connectors:
.Pp
.Bl -tag -width xxxxxxxxxxxxxxxxxxxx
.It AUI/DIX
Standard 15 pin connector
.It 10BaseT
UTP, also known as twisted pair
.El
.Pp
The system will not automatically select the correct port unless the kernel
was loaded via the network. Thus one of the following flags should be used
with
.Xr ifconfig 8
or in your /etc/hostname.le? file:
.Pp
.Bl -tag -width xxxxxxxxxxxxxxxxxxxx
.It link0
Use the UTP port.
.It link1
Use the AUI port.
.It -link0 -link1
Use the existing port selection (useful only for network booting).
.El
.Pp
.Sh SEE ALSO
.Xr intro 4 ,
.Xr inet 4 ,
.Xr arp 4
