#	$OpenBSD: Makefile,v 1.18 2000/03/02 14:46:48 todd Exp $
#	from: @(#)Makefile	8.2 (Berkeley) 2/16/94

MAN=	intro.4
MAN+=	audioamd.4 audiocs.4 be.4 bwtwo.4 cgtwo.4 cgthree.4 cgfour.4 cgsix.4
MAN+=	cgeight.4 cgfourteen.4 esp.4 fd.4 fga.4 hme.4 ie.4 kbd.4 le.4 magma.4
MAN+=	mem.4 ms.4 openprom.4 pnozz.4 qe.4 qec.4 scf.4 si.4 spif.4 sw.4
MAN+=	tctrl.4 tcx.4 xbox.4 xd.4 xy.4 zs.4
MLINKS=		mem.4 kmem.4
MLINKS+=	fga.4 fvme.4
MANSUBDIR=/sparc

.include <bsd.prog.mk>
