.\"	$OpenBSD: tcx.4,v 1.34 2011/09/03 22:59:07 jmc Exp $
.\"	$NetBSD: tcx.4,v 1.3 1997/10/08 22:00:14 jtc Exp $
.\"
.\" Copyright (c) 1996 The NetBSD Foundation, Inc.
.\" All rights reserved.
.\"
.\" This code is derived from software contributed to The NetBSD Foundation
.\" by Paul Kranenburg.
.\"
.\" Redistribution and use in source and binary forms, with or without
.\" modification, are permitted provided that the following conditions
.\" are met:
.\" 1. Redistributions of source code must retain the above copyright
.\"    notice, this list of conditions and the following disclaimer.
.\" 2. Redistributions in binary form must reproduce the above copyright
.\"    notice, this list of conditions and the following disclaimer in the
.\"    documentation and/or other materials provided with the distribution.
.\"
.\" THIS SOFTWARE IS PROVIDED BY THE NETBSD FOUNDATION, INC. AND CONTRIBUTORS
.\" ``AS IS'' AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED
.\" TO, THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR
.\" PURPOSE ARE DISCLAIMED.  IN NO EVENT SHALL THE FOUNDATION OR CONTRIBUTORS
.\" BE LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR
.\" CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF
.\" SUBSTITUTE GOODS OR SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS
.\" INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN
.\" CONTRACT, STRICT LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE)
.\" ARISING IN ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE
.\" POSSIBILITY OF SUCH DAMAGE.
.\"
.Dd $Mdocdate: September 3 2011 $
.Dt TCX 4 sparc
.Os
.Sh NAME
.Nm tcx
.Nd accelerated 8/24-bit color frame buffer
.Sh SYNOPSIS
.Cd "tcx* at sbus?"
.Cd "wsdisplay* at tcx?"
.Sh DESCRIPTION
The
.Nm
is an 8 bit color frame buffer, with graphics acceleration,
found on-board the SPARCstation 4, and also available in a 24 bit version
as an AFX board for the SPARCstation 5, called the S24.
.Pp
The
.Nm
driver interfaces the frame buffer with the
.Xr wscons 4
console framework.
It does not provide direct device driver entry points
but makes its functions available via the internal
.Xr wsdisplay 4
interface.
.Sh DISPLAY RESOLUTION
The
.Nm
frame buffer will by default select its resolution and refresh rate
according to the monitor sense information obtained from the 13W3
connector.
If the
.Nm
frame buffer is used as the console display, a different resolution can
be selected by changing the OpenPROM environment.
.Pp
If the
.Nm
frame buffer is a secondary display, or a serial console is used, the
display resolution can not be changed without using an
.Em nvramrc
OpenPROM script.
Refer to the
.Em Sun Frame Buffer FAQ
for details.
.Pp
The supported video modes depend on the particular frame buffer type.
.\"
.Ss TCX (8 bit) video modes
The 8 bit frame buffer supports the following video modes:
.Bl -column "Mode identifier" "Resolution" "Refresh Rate" -offset indent
.It Sy "Mode identifier" Ta Sy "Resolution" Ta Sy "Refresh Rate (MHz)"
.\" refresh rate not confirmed for the following mode
.It Li r640x480x21 Ta 640x480 Ta 56Hz
.It Li r640x480x25 Ta 640x480 Ta 60Hz
.\"
.\" refresh rate not confirmed for the following mode
.It Li r744x1273x105 Ta 744x1273 Ta 76Hz
.\"
.It Li r1000x1022x105 Ta 1000x1022 Ta 76Hz
.\"
.\" refresh rate not confirmed for the following mode
.It Li r1024x768x54 Ta 1024x768 Ta 50Hz
.It Li r1024x768x64 Ta 1024x768 Ta 60Hz
.It Li r1024x768x70 Ta 1024x768 Ta 66Hz
.It Li r1024x768x74 Ta 1024x768 Ta 70Hz
.It Li r1024x768x81 Ta 1024x768 Ta 75Hz
.It Li r1024x768x84 Ta 1024x768 Ta 77Hz
.\"
.It Li r1024x800x81 Ta 1024x800 Ta 74Hz
.It Li r1024x800x92 Ta 1024x800 Ta 84Hz
.It Li r1024x800x94 Ta 1024x800 Ta 85Hz
.\"
.It Li r1024x1024x92 Ta 1024x1024 Ta 62Hz
.\"
.\" refresh rate not confirmed for the following mode
.It Li r1152x900x54 Ta 1152x900 Ta 38Hz
.It Li r1152x900x92 Ta 1152x900 Ta 66Hz
.It Li r1152x900x94 Ta 1152x900 Ta 67Hz
.It Li r1152x900x105 Ta 1152x900 Ta 76Hz
.It Li r1152x900x108 Ta 1152x900 Ta 77Hz
.El
.Pp
With the addition of a 1MB VSIMM, the following higher resolution models
become available:
.Bl -column "Mode identifier" "Resolution" "Refresh Rate" -offset indent
.It Sy "Mode identifier" Ta Sy "Resolution" Ta Sy "Refresh Rate (MHz)"
.It Li r1280x1024x117 Ta 1280x1024 Ta 66Hz
.It Li r1280x1024x118 Ta 1280x1024 Ta 67Hz
.It Li r1280x1024x135 Ta 1280x1024 Ta 76Hz
.\"
.\" refresh rate not confirmed for the following mode
.It Li r1600x1280x76 Ta 1600x1280 Ta 66Hz
.\"
.\" refresh rate not confirmed for the following mode
.It Li r1920x1080x71 Ta 1920x1080 Ta 72Hz
.El
.Pp
To change the default resolution, type the following:
.Pp
.Bl -item -compact
.It
.Em \   ok
setenv
.Em fcode-debug?
true
.It
.Em \   ok
setenv
.Em output-device
screen:r1024x800x94
.El
.Pp
to change to an 85Hz 1024x800 resolution.
Note that setting
.Em fcode-debug?
is absolutely necessary for the resolution settings to be honoured.
.\"
.Ss S24 (24 bit) video modes
The 24 bit frame buffer only supports the following video modes:
.Bl -column "Mode identifier" "Resolution" "Refresh Rate" -offset indent
.It Sy Mode identifier Ta Sy "Resolution" Ta Sy "Refresh Rate (MHz)"
.It Li r1024x768x70 Ta 1024x768 Ta 70Hz
.It Li r1152x900x66 Ta 1152x900 Ta 66Hz
.It Li r1152x900x76 Ta 1152x900 Ta 76Hz
.El
.Pp
To change the default resolution, type the following:
.Pp
.Em \   ok
setenv
.Em output-device
screen:r1024x768x70
.Pp
to change to a 70Hz 1024x768 resolution.
Unlike the TCX, it is not necessary to alter the value of
.Em fcode-debug?
for the resolution settings to be honoured.
.Sh SEE ALSO
.Xr intro 4 ,
.Xr sbus 4 ,
.Xr wscons 4 ,
.Xr wsdisplay 4
