.\"	$OpenBSD: xy.4,v 1.2 1998/03/08 01:16:11 johns Exp $
.\"
.\" Copyright (c) 1998 The OpenBSD Project 
.\" All rights reserved.
.\"
.\"
.Dd March 4, 1998
.Dt XY 4 sparc
.Os
.Sh NAME
.Nm xy 
.Nd Xylogics 450 or 451 VME SMD disk controller driver
.Sh SYNOPSIS
.Cd "xyc0    at vmes0 addr 0xffffee40 level 3 vect 0x48" Pq sun4
.Cd "xyc1    at vmes0 addr 0xffffee48 level 3 vect 0x49" Pq sun4
.Cd "xy*     at xyc? drive ?                           " Pq sun4
.Sh DESCRIPTION
The 
.Nm
is a Xylogics 450/451 SMD disk controller found on sun4 systems with
the VME bus. 
.Sh SEE ALSO
.Xr xd 4
.Sh HISTORY
The 
.Nm
driver first appeared in NetBSD and was written by 
.br
Charles D. Cranor.
