.\" $OpenBSD: login_krb4-or-pwd.8,v 1.8 2002/11/09 03:03:14 fgsch Exp $
.\"
.\" Copyright (c) 2000 Todd C. Miller <Todd.Miller@courtesan.com>
.\" All rights reserved.
.\"
.\" Redistribution and use in source and binary forms, with or without
.\" modification, are permitted provided that the following conditions
.\" are met:
.\" 1. Redistributions of source code must retain the above copyright
.\"    notice, this list of conditions and the following disclaimer.
.\" 2. The name of the author may not be used to endorse or promote products
.\"    derived from this software without specific prior written permission.
.\"
.\" THIS SOFTWARE IS PROVIDED ``AS IS'' AND ANY EXPRESS OR IMPLIED WARRANTIES,
.\" INCLUDING, BUT NOT LIMITED TO, THE IMPLIED WARRANTIES OF MERCHANTABILITY
.\" AND FITNESS FOR A PARTICULAR PURPOSE ARE DISCLAIMED.  IN NO EVENT SHALL
.\" THE AUTHOR BE LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL,
.\" EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT LIMITED TO,
.\" PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; LOSS OF USE, DATA, OR PROFITS;
.\" OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY,
.\" WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR
.\" OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF
.\" ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
.\"
.Dd December 11, 2000
.Dt LOGIN_KRB-OR-PWD 8
.Os
.Sh NAME
.Nm login_krb4-or-pwd
.Nd provide KerberosIV or password authentication type
.Sh SYNOPSIS
.Nm login_krb4-or-pwd
.Op Fl s Ar service
.Op Fl v Ar wheel=yes|no
.Op Fl v Ar lastchance=yes|no
.Ar user
.Op Ar class
.Sh DESCRIPTION
The
.Nm
utility first attempts to authenticate the user via KerberosIV
and, failing that, falls back to standard password authentication.
.Pp
If KerberosIV is not configured on the system,
.Nm
is equivalent to calling
.Xr login_passwd 8 .
.Pp
.Nm
accepts any command line arguments described in
.Xr login_krb4 8
or
.Xr login_passwd 8 .
.Sh SEE ALSO
.Xr kerberos 1 ,
.Xr login_krb4 8 ,
.Xr login_passwd 8

