# !!!!!!!   DO NOT EDIT THIS FILE   !!!!!!! 
# This file is built by ./mktables from e.g. UnicodeData.txt.
# Any changes made here will be lost!

#
# This file supports:
# 	\p{Bengali} (and fuzzy permutations)
# 
# Meaning: Script 'BENGALI'
#
return <<'END';
0981	0983	BENGALI
0985	098C	BENGALI
098F	0990	BENGALI
0993	09A8	BENGALI
09AA	09B0	BENGALI
09B2		BENGALI
09B6	09B9	BENGALI
09BC	09C4	BENGALI
09C7	09C8	BENGALI
09CB	09CD	BENGALI
09D7		BENGALI
09DC	09DD	BENGALI
09DF	09E3	BENGALI
09E6	09F1	BENGALI
END
