# !!!!!!!   DO NOT EDIT THIS FILE   !!!!!!! 
# This file is built by ./mktables from e.g. UnicodeData.txt.
# Any changes made here will be lost!

#
# This file supports:
# 	\p{BidiRLO}
# 
# Meaning: Bi-directional category 'RLO'
#
return <<'END';
202E		
END
