# !!!!!!!   DO NOT EDIT THIS FILE   !!!!!!! 
# This file is built by ./mktables from e.g. UnicodeData.txt.
# Any changes made here will be lost!

#
# This file supports:
# 	\p{CanadianAboriginal} (and fuzzy permutations)
# 
# Meaning: Script 'CANADIAN_ABORIGINAL'
#
return <<'END';
1401	166C	CANADIAN_ABORIGINAL
166F	1676	CANADIAN_ABORIGINAL
END
