# !!!!!!!   DO NOT EDIT THIS FILE   !!!!!!! 
# This file is built by ./mktables from e.g. UnicodeData.txt.
# Any changes made here will be lost!

#
# This file supports:
# 	\p{DCsquare}
# 
# Meaning: Compatible with 'square'
#
return <<'END';
3300	3357	
3371	3376	
337B	33DD	
END
