# !!!!!!!   DO NOT EDIT THIS FILE   !!!!!!! 
# This file is built by ./mktables from e.g. UnicodeData.txt.
# Any changes made here will be lost!

#
# This file supports:
# 	\p{Hangul} (and fuzzy permutations)
# 
# Meaning: Script 'HANGUL'
#
return <<'END';
1100	1159	HANGUL
115F	11A2	HANGUL
11A8	11F9	HANGUL
3131	318E	HANGUL
AC00	D7A3	HANGUL
FFA0	FFBE	HANGUL
FFC2	FFC7	HANGUL
FFCA	FFCF	HANGUL
FFD2	FFD7	HANGUL
FFDA	FFDC	HANGUL
END
