# !!!!!!!   DO NOT EDIT THIS FILE   !!!!!!! 
# This file is built by ./mktables from e.g. UnicodeData.txt.
# Any changes made here will be lost!

#
# This file supports:
# 	\p{Osmanya} (and fuzzy permutations)
# 
# Meaning: Script 'OSMANYA'
#
return <<'END';
10480	1049D	OSMANYA
104A0	104A9	OSMANYA
END
