# !!!!!!!   DO NOT EDIT THIS FILE   !!!!!!! 
# This file is built by ./mktables from e.g. UnicodeData.txt.
# Any changes made here will be lost!

#
# This file supports:
# 	\p{Syriac} (and fuzzy permutations)
# 
# Meaning: Script 'SYRIAC'
#
return <<'END';
0710	072C	SYRIAC
0730	074A	SYRIAC
END
