# !!!!!!!   DO NOT EDIT THIS FILE   !!!!!!! 
# This file is built by ./mktables from e.g. UnicodeData.txt.
# Any changes made here will be lost!

#
# This file supports:
# 	\p{Ugaritic} (and fuzzy permutations)
# 
# Meaning: Script 'UGARITIC'
#
return <<'END';
10380	1039D	UGARITIC
END
