# !!!!!!!   DO NOT EDIT THIS FILE   !!!!!!! 
# This file is built by ./mktables from e.g. UnicodeData.txt.
# Any changes made here will be lost!

#
# This file supports:
# 	\p{Yi} (and fuzzy permutations)
# 
# Meaning: Script 'YI'
#
return <<'END';
A000	A48C	YI
A490	A4A1	YI
A4A4	A4B3	YI
A4B5	A4C0	YI
A4C2	A4C4	YI
A4C6		YI
END
