.\"	$OpenBSD: installboot.8,v 1.17 2010/03/06 16:16:43 jmc Exp $
.\"
.\" Copyright (c) 1994 Paul Kranenburg
.\" All rights reserved.
.\"
.\" Redistribution and use in source and binary forms, with or without
.\" modification, are permitted provided that the following conditions
.\" are met:
.\" 1. Redistributions of source code must retain the above copyright
.\"    notice, this list of conditions and the following disclaimer.
.\" 2. Redistributions in binary form must reproduce the above copyright
.\"    notice, this list of conditions and the following disclaimer in the
.\"    documentation and/or other materials provided with the distribution.
.\" 3. All advertising materials mentioning features or use of this software
.\"    must display the following acknowledgement:
.\"      This product includes software developed by Paul Kranenburg.
.\" 4. The name of the author may not be used to endorse or promote products
.\"    derived from this software without specific prior written permission
.\"
.\" THIS SOFTWARE IS PROVIDED BY THE AUTHOR ``AS IS'' AND ANY EXPRESS OR
.\" IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED WARRANTIES
.\" OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE DISCLAIMED.
.\" IN NO EVENT SHALL THE AUTHOR BE LIABLE FOR ANY DIRECT, INDIRECT,
.\" INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT
.\" NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; LOSS OF USE,
.\" DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON ANY
.\" THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT
.\" (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF
.\" THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
.\"
.Dd $Mdocdate: March 6 2010 $
.Dt INSTALLBOOT 8 mvme68k
.Os
.Sh NAME
.Nm installboot
.Nd install a bootstrap on an FFS disk
.Sh SYNOPSIS
.Nm installboot
.Op Fl n
.Op Fl v
.Ar boot
.Ar bootxx
.Ar rawdev
.Sh DESCRIPTION
.Nm installboot
is used to install a "first-stage" boot program into the boot area
of an FFS disk partition, and initialize the table of block numbers the
.Ar bootxx
program uses to load the second-stage boot program.
.Pp
The options are as follows:
.Bl -tag -width flag
.It Fl n
Do not actually write anything on the disk.
.It Fl v
Be verbose, printing out the block numbers that
.Ar bootxx
will use to load
.Ar boot .
.El
.Pp
The arguments are:
.Bl -tag -width bootxx
.It Ar boot
the name of the second-stage boot program in the file system
where the first-stage boot program is to be installed.
.It Ar bootxx
the name of the prototype file for the first stage boot program.
.It Ar rawdev
the name of the raw device in which the first-stage boot program
is to be installed.
This should correspond to the block device on which the file system containing
.Ar boot
is mounted.
.El
.Sh EXAMPLES
.Bd -literal
cp /usr/mdec/bootsd /boot
/usr/mdec/installboot /boot /usr/mdec/bootxx /dev/rsd0a
.Ed
.Sh SEE ALSO
.Xr disklabel 8 ,
.Xr init 8
