.\"	$OpenBSD: wsfontload.8,v 1.10 2003/02/17 07:24:33 jmc Exp $
.\"	$NetBSD: wsfontload.8,v 1.5 1999/04/06 04:54:22 cgd Exp $
.\"
.Dd January 13, 1999
.Dt WSFONTLOAD 8
.Os
.Sh NAME
.Nm wsfontload
.Nd load a font bitmap into a wscons display device
.Sh SYNOPSIS
.Nm wsfontload
.Bk -words
.Op Fl B
.Ek
.Bk -words
.Op Fl b
.Ek
.Bk -words
.Op Fl e Ar encoding
.Ek
.Bk -words
.Op Fl f Ar file
.Ek
.Bk -words
.Op Fl h Ar height
.Ek
.Bk -words
.Op Fl l
.Ek
.Bk -words
.Op Fl N Ar name
.Ek
.Bk -words
.Op Fl w Ar width
.Ek
.Op Ar fontfile
.Sh DESCRIPTION
The
.Nm
utility loads a font bitmap to a wscons device if the device driver
supports it.
The font gets assigned a name in this process which it can be referred to
by later for use on a display screen.
The font is loaded from the specified
.Ar fontfile ,
or from
.Pa stdin
if
.Ar fontfile
is not provided.
.Pp
The options are as follows:
.Bl -tag -width Ds
.It Fl b
Specifies that the font data is ordered right-to-left bit wise.
The default is left-to-right.
.It Fl B
Specifies that the font data is ordered right-to-left byte wise.
The default is left-to-right.
.It Fl e Ar encoding
Sets the encoding of the font.
This can be either a symbolic abbreviation or a numeric value.
Currently recognized abbreviations are
.Dq iso
for ISO-8859-1 encoding,
.Dq ibm
for IBM encoded fonts, and
.Dq pcvt
for the custom encoding of the supplemental fonts which came with the BSD
PCVT console driver.
Per default,
.Dq iso
is assumed.
.It Fl f Ar file
Specify the control device of the wscons display to operate on.
Default is
.Pa /dev/ttyCcfg .
.It Fl h Ar height
Sets the height of a font character in pixels.
Default is 16.
.It Fl l
Specifies to print out a list of loaded fonts, no other
arguments should be specified.
.It Fl N Ar name
Specifies a name which can be used later to refer to the font.
If none is given, the
.Ar fontfile
name is used to create one.
.It Fl w Ar width
Sets the width of a font character in pixels.
Default is 8.
.El
.Pp
Typically, the
.Nm
utility will be executed in system startup by the
.Pa /etc/rc.wscons
script, controlled by the
.Pa /etc/wscons.conf
configuration file.
.Pp
No font files are provided with the wscons framework.
The fonts installed by PCVT can be used instead, as can raw font files from
other operating system distributions.
.Sh EXAMPLES
.Cm "# wsfontload -N myname -h 8 -e ibm /usr/share/misc/pcvtfonts/vt220l.808"
.Pp
Load the IBM-encoded 8x8-font from the PCVT distribution.
This (or another 8x8-font) is necessary to use the 50-line screen type on
.Xr vga 4
displays.
.Sh FILES
.Bl -tag -width /etc/wscons.conf -compact
.\" .It Pa /etc/wscons.conf
.\" wscons configuration file
.It Pa /usr/share/misc/pcvtfonts/
fonts directory.
.El
.Sh SEE ALSO
.Xr wscons 4 ,
.Xr wsconscfg 8 ,
.Xr wsconsctl 8
.Sh HISTORY
The
.Nm
program appeared in
.Ox 2.8 .
.Sh BUGS
Many features are missing.
.Pp
There is no way to remove a loaded font.
