.\"	$OpenBSD: syspatch.8,v 1.16 2017/04/08 20:36:50 schwarze Exp $
.\"
.\" Copyright (c) 2016 Antoine Jacoutot <ajacoutot@openbsd.org>
.\"
.\" Permission to use, copy, modify, and distribute this software for any
.\" purpose with or without fee is hereby granted, provided that the above
.\" copyright notice and this permission notice appear in all copies.
.\"
.\" THE SOFTWARE IS PROVIDED "AS IS" AND THE AUTHOR DISCLAIMS ALL WARRANTIES
.\" WITH REGARD TO THIS SOFTWARE INCLUDING ALL IMPLIED WARRANTIES OF
.\" MERCHANTABILITY AND FITNESS. IN NO EVENT SHALL THE AUTHOR BE LIABLE FOR
.\" ANY SPECIAL, DIRECT, INDIRECT, OR CONSEQUENTIAL DAMAGES OR ANY DAMAGES
.\" WHATSOEVER RESULTING FROM LOSS OF USE, DATA OR PROFITS, WHETHER IN AN
.\" ACTION OF CONTRACT, NEGLIGENCE OR OTHER TORTIOUS ACTION, ARISING OUT OF
.\" OR IN CONNECTION WITH THE USE OR PERFORMANCE OF THIS SOFTWARE.
.\"
.Dd $Mdocdate: April 8 2017 $
.Dt SYSPATCH 8
.Os
.Sh NAME
.Nm syspatch
.Nd manage base system binary patches
.Sh SYNOPSIS
.Nm syspatch
.Op Fl c | l | r
.Sh DESCRIPTION
.Nm
is a utility to fetch, verify, install and revert
.Ox
binary patches.
.Pp
When run without any options,
.Nm syspatch
will apply
.Em all
missing patches by saving the original release kernel if needed, creating a
rollback tarball containing the files it is about to replace, then extracting
and installing all files contained in the syspatch tarball.
.Pp
The options are as follows:
.Bl -tag -width Ds
.It Fl c
List available patches; suitable for
.Xr cron 8 .
.It Fl l
List installed patches.
.It Fl r
Revert the most recently installed patch.
.El
.Sh FILES
.Bl -tag -width "/bsd.syspatch${OSrev}" -compact
.It Pa /bsd.syspatch${OSrev}
Backup of the original
.Pa /bsd
release kernel.
.It Pa /etc/installurl
.Ox
mirror top-level URL for fetching patches.
.It Pa /var/syspatch/*
Directories containing the rollback tarball and original signed
.Xr diff 1
of installed patches.
.El
.Sh SEE ALSO
.Xr signify 1 ,
.Xr installurl 5 ,
.Xr release 8
.Sh HISTORY
.Nm
first appeared in
.Ox 6.1 .
.Sh AUTHORS
.Nm
was written by
.An Antoine Jacoutot Aq Mt ajacoutot@openbsd.org .
.Sh CAVEATS
.Nm
is designed to work solely on official
.Ox
releases.
