.\"	$OpenBSD: syspatch.8,v 1.5 2016/09/10 16:07:33 ajacoutot Exp $
.\"
.\" Copyright (c) 2016 Antoine Jacoutot <ajacoutot@openbsd.org>
.\"
.\" Permission to use, copy, modify, and distribute this software for any
.\" purpose with or without fee is hereby granted, provided that the above
.\" copyright notice and this permission notice appear in all copies.
.\"
.\" THE SOFTWARE IS PROVIDED "AS IS" AND THE AUTHOR DISCLAIMS ALL WARRANTIES
.\" WITH REGARD TO THIS SOFTWARE INCLUDING ALL IMPLIED WARRANTIES OF
.\" MERCHANTABILITY AND FITNESS. IN NO EVENT SHALL THE AUTHOR BE LIABLE FOR
.\" ANY SPECIAL, DIRECT, INDIRECT, OR CONSEQUENTIAL DAMAGES OR ANY DAMAGES
.\" WHATSOEVER RESULTING FROM LOSS OF USE, DATA OR PROFITS, WHETHER IN AN
.\" ACTION OF CONTRACT, NEGLIGENCE OR OTHER TORTIOUS ACTION, ARISING OUT OF
.\" OR IN CONNECTION WITH THE USE OR PERFORMANCE OF THIS SOFTWARE.
.\"
.Dd $Mdocdate: September 10 2016 $
.Dt SYSPATCH 8
.Os
.Sh NAME
.Nm syspatch
.Nd manage base system binary patches
.Sh SYNOPSIS
.Nm syspatch
.Op Fl c | l | r
.Sh DESCRIPTION
.Nm
is a utility to fetch, verify, install and rollback
.Ox
binary patches.
.Pp
The options are as follows:
.Bl -tag -width Ds
.It Fl c
List available patches.
.It Fl l
List installed patches.
.It Fl r
Remove the most recently installed patch (rollback).
.El
.Sh SEE ALSO
.Xr signify 1 ,
.Xr release 8
.Sh HISTORY
.Nm
first appeared in
.Ox 6.1 .
.Sh AUTHORS
.Nm
was written by
.An Antoine Jacoutot Aq Mt ajacoutot@openbsd.org .
