.\" $OpenBSD: clct.4,v 1.1 2001/01/13 19:53:51 aaron Exp $
.\"
.Dd January 13, 2001
.Dt CLCT 4
.Os
.Sh NAME
.Nm clct
.Nd Cirrus Logic CS4281 audio device driver
.Sh SYNOPSIS
.Cd "clct*  at pci? dev ? function ?"
.Cd "audio* at clct?"
.Sh DESCRIPTION
The
.Nm
driver provides support for the Cirrus Logic CS4281 chip.
.Sh SEE ALSO
.Xr audio 4 ,
.Xr pci 4
.Sh HISTORY
The
.Nm
device driver appeared in
.Ox 2.9 .
