.\"	$OpenBSD: dpt.4,v 1.19 2011/06/21 20:25:49 matthew Exp $
.\"	$NetBSD: dpt.4,v 1.7 2000/01/17 16:34:44 ad Exp $
.\"
.\" Copyright (c) 1999, 2000 Andy Doran <ad@NetBSD.org>
.\" All rights reserved.
.\"
.\" Redistribution and use in source and binary forms, with or without
.\" modification, are permitted provided that the following conditions
.\" are met:
.\" 1. Redistributions of source code must retain the above copyright
.\"    notice, this list of conditions and the following disclaimer.
.\" 2. The name of the author may not be used to endorse or promote products
.\"    derived from this software without specific prior written permission
.\"
.\" THIS SOFTWARE IS PROVIDED BY THE AUTHOR ``AS IS'' AND ANY EXPRESS OR
.\" IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED WARRANTIES
.\" OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE DISCLAIMED.
.\" IN NO EVENT SHALL THE AUTHOR BE LIABLE FOR ANY DIRECT, INDIRECT,
.\" INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT
.\" NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; LOSS OF USE,
.\" DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON ANY
.\" THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT
.\" (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF
.\" THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
.\"
.Dd $Mdocdate: June 21 2011 $
.Dt DPT 4
.Os
.Sh NAME
.Nm dpt
.Nd DPT EATA SCSI RAID controller
.Sh SYNOPSIS
.Cd "dpt* at eisa?"
.Cd "dpt* at pci?"
.Cd "scsibus* at dpt?"
.Sh DESCRIPTION
The
.Nm
driver provides support for the following
.Tn SCSI
adapters:
.Pp
.Bl -tag -width Ds -offset indent -compact
.It Tn DPT SmartCache III
.It Tn DPT SmartCache IV
.It Tn DPT SmartRAID III
.It Tn DPT SmartRAID IV
.El
.Sh DIAGNOSTICS
None of these messages should be encountered under normal circumstances.
It should be noted that the list below is not complete.
.Bl -diag
.It dpt0: readcfg failed - see dpt(4)
The EATA configuration data did not appear upon request.
This may be caused by older firmware.
Generally the solution is to power-cycle the affected machine.
.It dpt0: spurious intr
A spurious interrupt was received from the HBA.
.It dpt0: bogus status (returned CCB id NNNN)
A corrupt or incomplete status packet was received from the HBA.
.El
.Sh SEE ALSO
.Xr cd 4 ,
.Xr ch 4 ,
.Xr eisa 4 ,
.Xr intro 4 ,
.Xr pci 4 ,
.Xr scsi 4 ,
.Xr sd 4 ,
.Xr st 4
.Sh HISTORY
This manpage is inadequate.
.Pp
The
.Nm
driver first appeared in
.Ox 2.5 .
.Sh AUTHORS
The
.Nm
driver was written by
.An Andy Doran Aq ad@netbsd.org ,
based upon the
.Nm uha
and
.Nm bha
drivers, which are the work of others.
.Sh BUGS
EATA adapters other than listed may function correctly with the
.Nm
driver, however a definitive list is not available.
.Pp
Older firmware may prove problematic.
It is recommended that the latest available firmware be used.
Contact DPT for a firmware update.
.Pp
Older boards that do not support scatter-gather I/O or DMA are not supported.
.Pp
An ISA front-end is needed.
.Pp
ECC formatted disk and arrays (i.e., with a sector size of 528 bytes) do not
work correctly with the PM2041 and certain firmware revisions of the PM3334.
