.\"	$OpenBSD: gdt.4,v 1.20 2004/03/21 19:50:25 miod Exp $
.\"
.\" Copyright (c) 2000 Niklas Hallqvist.  All rights reserved.
.\"
.\"
.Dd February 17, 2000
.Dt GDT 4
.Os
.Sh NAME
.Nm gdt
.Nd Intel (and formerly ICP-Vortex) GDT RAID driver
.Sh SYNOPSIS
.Cd "gdt* at pci? dev ? function ?"
.Cd "scsibus* at gdt?"
.Sh DESCRIPTION
The
.Nm
driver provides support for all currently known adapters:
.Pp
.Bl -tag -width Ds -offset indent -compact
.It Tn GDT6000/6020/6050 ,
.It Tn GDT6000B/6010 ,
.It Tn GDT6110/6510 ,
.It Tn GDT6120/6520 ,
.It Tn GDT6530 ,
.It Tn GDT6550 ,
.It Tn GDT6x17 ,
.It Tn GDT6x27 ,
.It Tn GDT6537 ,
.It Tn GDT6557 ,
.It Tn GDT6x15 ,
.It Tn GDT6x25 ,
.It Tn GDT6535 ,
.It Tn GDT6555 ,
.It Tn GDT6x17RP ,
.It Tn GDT6x27RP ,
.It Tn GDT6537RP ,
.It Tn GDT6557RP ,
.It Tn GDT6x11RP ,
.It Tn GDT6x21RP ,
.It Tn GDT6x17RP1 ,
.It Tn GDT6x27RP1 ,
.It Tn GDT6537RP1 ,
.It Tn GDT6557RP1 ,
.It Tn GDT6x11RP1 ,
.It Tn GDT6x21RP1 ,
.It Tn GDT6x18RD ,
.It Tn GDT6x28RD ,
.It Tn GDT6x38RD ,
.It Tn GDT6x58RD ,
.It Tn GDT6x17RP2 ,
.It Tn GDT6x27RP2 ,
.It Tn GDT6537RP2 ,
.It Tn GDT6557RP2 ,
.It Tn GDT6x11RP2 ,
.It Tn GDT6x21RP2 ,
.It Tn GDT6513RS ,
.It Tn GDT6523RS ,
.It Tn GDT6518RS ,
.It Tn GDT6x28RS ,
.It Tn GDT6x38RS ,
.It Tn GDT6x58RS ,
.It Tn GDT6x33RS ,
.It Tn GDT6x43RS ,
.It Tn GDT6x53RS ,
.It Tn GDT6x63RS ,
.It Tn GDT7x13RN ,
.It Tn GDT7x23RN ,
.It Tn GDT7x18RN ,
.It Tn GDT7x28RN ,
.It Tn GDT7x38RN ,
.It Tn GDT7x58RN ,
.It Tn GDT7x43RN ,
.It Tn GDT7x53RN ,
.It Tn GDT7x63RN ,
.It Tn GDT4x13RZ ,
.It Tn GDT4x23RZ ,
.It Tn GDT8x13RZ ,
.It Tn GDT8x23RZ ,
.It Tn GDT8x33RZ ,
.It Tn GDT8x43RZ ,
.It Tn GDT8x53RZ ,
.It Tn GDT8x63RZ ,
.It Tn GDT6x19RD ,
.It Tn GDT6x29RD ,
.It Tn GDT7x19RN ,
.It Tn GDT7x29RN ,
.It Tn GDT8x22RZ and
.It Tn GDT8x23RZ .
.El
.Pp
Although the controllers are actual RAID controllers the driver makes them
look just like SCSI controllers.
All RAID configuration is done through the controllers' BIOSes.
.Sh DIAGNOSTICS
.Bl -diag
.It "pci_mem_find: expected mem type 00000000, found 00000002"
This message occurs during autoconfiguration if jumper J4 is set to map
the controller memory below 1MB in physical memory.
The driver primarily wants this jumper to be set the other way round,
but it will work with it in any setting.
If the diagnostic is considered a nuisance, alter jumper J4's setting.
.El
.Sh SEE ALSO
.Xr intro 4 ,
.Xr pci 4 ,
.Xr scsi 4 ,
.Xr sd 4
.Sh HISTORY
The
.Nm
driver first appeared in
.Ox 2.7 .
.Sh AUTHORS
The
.Nm
driver was written by
.An Niklas Hallqvist Aq niklas@openbsd.org ,
inspired by the Linux driver by
.An Achim Luebner Aq achim@vortex.de .
.Sh BUGS
An ISA & EISA front-end is needed.
.Pp
The driver does not yet support transparent raw SCSI mode.
.Pp
It would be nice to configure the RAID units after boot
but the information on how to do that is not public.
