.\"	$OpenBSD: ioprbs.4,v 1.8 2002/08/29 07:34:31 wcobb Exp $
.\"
.\" Copyright (c) 2000 Niklas Hallqvist.  All rights reserved.
.\"
.\"
.Dd July 4, 20010
.Dt IOPRBS 4
.Os
.Sh NAME
.Nm ioprbs
.Nd I2O random block storage
.Sh SYNOPSIS
.Cd "ioprbs* at iop? tid ?"
.Cd "scsibus* at ioprbs?"
.Sh DESCRIPTION
The
.Nm
driver provides support for I2O random block storages, like RAID-sets.
So far only the following adapters has been tested:
.Pp
.Bl -item -offset indent -compact
.It
.Tn Adaptec 2100S
.It
.Tn Adaptec 2110S
.It
.Tn Adaptec 3200S
.El
.Pp
Although only those two adapters have been tested, the I2O interface is
a generic one, and the driver should cope with all I2O random block
storages with no further adaptions.
.Pp
The storage is presented to the system as SCSI disks for uniformity
with other RAID controllers we support.
All RAID configuration is done through the controllers' BIOSes.
.Sh SEE ALSO
.Xr intro 4 ,
.Xr iop 4 ,
.Xr iopsp 4 ,
.Xr scsi 4 ,
.Xr sd 4
.Sh AUTHORS
The
.Nm
driver was written by
.An Niklas Hallqvist Aq niklas@openbsd.org ,
inspired by the
.Nx
ld_iop driver by
.An Andrew Doran Aq ad@netbsd.org .
.Sh HISTORY
The
.Nm
driver first appeared in
.Ox 3.0 .
