.\"	$OpenBSD: ips.4,v 1.4 2007/05/31 19:19:50 jmc Exp $
.\"
.\" Copyright (c) 2006 Alexander Yurchenko <grange@openbsd.org>
.\"
.\" Permission to use, copy, modify, and distribute this software for any
.\" purpose with or without fee is hereby granted, provided that the above
.\" copyright notice and this permission notice appear in all copies.
.\"
.\" THE SOFTWARE IS PROVIDED "AS IS" AND THE AUTHOR DISCLAIMS ALL WARRANTIES
.\" WITH REGARD TO THIS SOFTWARE INCLUDING ALL IMPLIED WARRANTIES OF
.\" MERCHANTABILITY AND FITNESS. IN NO EVENT SHALL THE AUTHOR BE LIABLE FOR
.\" ANY SPECIAL, DIRECT, INDIRECT, OR CONSEQUENTIAL DAMAGES OR ANY DAMAGES
.\" WHATSOEVER RESULTING FROM LOSS OF USE, DATA OR PROFITS, WHETHER IN AN
.\" TORTIOUS ACTION, ARISING OUT OF
.\" PERFORMANCE OF THIS SOFTWARE.
.\"
.Dd $Mdocdate: May 31 2007 $
.Dt IPS 4
.Os
.Sh NAME
.Nm ips
.Nd IBM SATA/SCSI ServeRAID controller
.Sh SYNOPSIS
.Cd "ips* at pci?"
.Cd "scsibus* at ips?"
.Sh DESCRIPTION
The
.Nm
driver provides support for IBM ServeRAID controllers, including:
.Pp
.Bl -bullet -width Ds -offset indent -compact
.It
ServeRAID 3H/3L
.It
ServeRAID 4H/4L/4Lx/4M/4Mx
.It
ServeRAID 5i/5i II
.It
ServeRAID 6i/6M
.It
ServeRAID 7k/7M/7t
.El
.Pp
Although the controllers are actual RAID controllers,
the driver makes them look just like SCSI controllers.
All RAID configuration is done through the controllers' BIOSes.
.Sh SEE ALSO
.Xr intro 4 ,
.Xr pci 4 ,
.Xr scsi 4 ,
.Xr sd 4
.Sh HISTORY
The
.Nm
driver first appeared in
.Ox 4.1 .
.Sh AUTHORS
.An -nosplit
The
.Nm
driver was written by
.An Alexander Yurchenko Aq grange@openbsd.org .
