.\"	$OpenBSD: mbg.4,v 1.8 2007/11/05 20:03:32 mbalmer Exp $
.\"
.\" Copyright (c) 2006 Marc Balmer <mbalmer@openbsd.org>
.\"
.\" Permission to use, copy, modify, and distribute this software for any
.\" purpose with or without fee is hereby granted, provided that the above
.\" copyright notice and this permission notice appear in all copies.
.\"
.\" THE SOFTWARE IS PROVIDED "AS IS" AND THE AUTHOR DISCLAIMS ALL WARRANTIES
.\" WITH REGARD TO THIS SOFTWARE INCLUDING ALL IMPLIED WARRANTIES OF
.\" MERCHANTABILITY AND FITNESS. IN NO EVENT SHALL THE AUTHOR BE LIABLE FOR
.\" ANY SPECIAL, DIRECT, INDIRECT, OR CONSEQUENTIAL DAMAGES OR ANY DAMAGES
.\" WHATSOEVER RESULTING FROM LOSS OF USE, DATA OR PROFITS, WHETHER IN AN
.\" ACTION OF CONTRACT, NEGLIGENCE OR OTHER TORTIOUS ACTION, ARISING OUT OF
.\" OR IN CONNECTION WITH THE USE OR PERFORMANCE OF THIS SOFTWARE.
.\"
.Dd $Mdocdate: November 5 2007 $
.Dt MBG 4
.Os
.Sh NAME
.Nm mbg
.Nd Meinberg Funkuhren timedelta sensor
.Sh SYNOPSIS
.Cd "mbg* at pci?"
.Sh DESCRIPTION
The
.Nm
driver provides support for Meinberg Funkuhren radio clocks (time signal
station receivers and GPS devices).
.Nm
implements a timedelta sensor and the delta (in nanoseconds) between the
received time information and the local time can be accessed through the
.Xr sysctl 8
interface.
.Pp
The card type is indicated in the sensor description.
Currently, the following cards are supported by
.Nm :
.Pp
.Bl -tag -width "GPS170XXX" -offset indent -compact
.It GPS170PCI
3.3V/5V 6-channel GPS receiver card
.It PCI32
5V DCF77 time signal station receiver card
.It PCI509
5V DCF77 time signal station receiver card
.It PCI511
3.3V/5V DCF77 time signal station receiver card
.It PEX511
PCI Express DCF77 time signal station receiver card
.El
.Sh SEE ALSO
.Xr intro 4 ,
.Xr pci 4 ,
.Xr ntpd 8 ,
.Xr sysctl 8
.Sh HISTORY
The
.Nm
driver first appeared in
.Ox 4.1 .
.Sh AUTHORS
The
.Nm
driver was written by
.An Marc Balmer Aq mbalmer@openbsd.org .
