.\" $OpenBSD: urtw.4,v 1.15 2010/04/29 09:20:17 jmc Exp $
.\"
.\" Copyright (c) 2008 Weongyo Jeong <weongyo@FreeBSD.org>
.\"
.\" Permission to use, copy, modify, and distribute this software for any
.\" purpose with or without fee is hereby granted, provided that the above
.\" copyright notice and this permission notice appear in all copies.
.\"
.\" THE SOFTWARE IS PROVIDED "AS IS" AND THE AUTHOR DISCLAIMS ALL WARRANTIES
.\" WITH REGARD TO THIS SOFTWARE INCLUDING ALL IMPLIED WARRANTIES OF
.\" MERCHANTABILITY AND FITNESS. IN NO EVENT SHALL THE AUTHOR BE LIABLE FOR
.\" ANY SPECIAL, DIRECT, INDIRECT, OR CONSEQUENTIAL DAMAGES OR ANY DAMAGES
.\" WHATSOEVER RESULTING FROM LOSS OF USE, DATA OR PROFITS, WHETHER IN AN
.\" ACTION OF CONTRACT, NEGLIGENCE OR OTHER TORTIOUS ACTION, ARISING OUT OF
.\" OR IN CONNECTION WITH THE USE OR PERFORMANCE OF THIS SOFTWARE.
.\"
.Dd $Mdocdate: April 29 2010 $
.Dt URTW 4
.Os
.Sh NAME
.Nm urtw
.Nd Realtek RTL8187L/RTL8187B USB IEEE 802.11b/g wireless network device
.Sh SYNOPSIS
.Cd "urtw* at uhub? port ?"
.Sh DESCRIPTION
The
.Nm
driver supports USB 802.11b/g wireless adapters based on the
Realtek RTL8187L and RTL8187B.
.Pp
These are the modes the
.Nm
driver can operate in:
.Bl -tag -width "IBSS-masterXX"
.It BSS mode
Also known as
.Em infrastructure
mode, this is used when associating with an access point, through
which all traffic passes.
This mode is the default.
.It monitor mode
In this mode the driver is able to receive packets without
associating with an access point.
This disables the internal receive filter and enables the card to
capture packets from networks which it wouldn't normally have access to,
or to scan for access points.
.El
.Pp
The
.Nm
driver can be configured to use
Wired Equivalent Privacy (WEP) or
Wi-Fi Protected Access (WPA-PSK and WPA2-PSK).
WPA is the de facto encryption standard for wireless networks.
It is strongly recommended that WEP
not be used as the sole mechanism
to secure wireless communication,
due to serious weaknesses in it.
The
.Nm
driver relies on the software 802.11 stack for both encryption and decryption
of data frames.
.Pp
The
.Nm
driver can be configured at runtime with
.Xr ifconfig 8
or on boot with
.Xr hostname.if 5 .
.Sh HARDWARE
The following adapters should work:
.Pp
.Bl -tag -width Ds -offset indent -compact
.It Alfa AWUS036H
.It ASUS P5B Deluxe
.It Belkin F5D7050E
.It Linksys WUSB54GC v2
.It Netgear WG111v2
.It Netgear WG111v3
.It Shuttle XPC Accessory PN20
.It Sitecom WL-168 v1
.It Sitecom WL-168 v4
.It Surecom EP-9001-g rev 2A
.It TRENDnet TEW-424UB V3.xR
.El
.Sh EXAMPLES
The following
.Xr hostname.if 5
example configures urtw0 to join whatever network is available on boot,
using WEP key
.Dq 0x1deadbeef1 ,
channel 11, obtaining an IP address using DHCP:
.Bd -literal -offset indent
dhcp NONE NONE NONE nwkey 0x1deadbeef1 chan 11
.Ed
.Pp
Configure urtw0 to join network
.Dq my_net
using WPA-PSK with passphrase
.Dq my_passphrase :
.Bd -literal -offset indent
# ifconfig urtw0 nwid my_net wpa wpapsk \e
	`wpa-psk my_net my_passphrase`
.Ed
.Pp
Return urtw0 to its default settings:
.Bd -literal -offset indent
# ifconfig urtw0 -bssid -chan media autoselect \e
	nwid "" -nwkey -wpa -wpapsk
.Ed
.Pp
Join an existing BSS network,
.Dq my_net :
.Bd -literal -offset indent
# ifconfig urtw0 192.168.1.1 netmask 0xffffff00 nwid my_net
.Ed
.Sh SEE ALSO
.Xr arp 4 ,
.Xr ifmedia 4 ,
.Xr intro 4 ,
.Xr netintro 4 ,
.Xr usb 4 ,
.Xr hostname.if 5 ,
.Xr hostapd 8 ,
.Xr ifconfig 8 ,
.Xr wpa-psk 8
.Pp
Realtek Semiconductor:
.Pa http://www.realtek.com.tw/
.Sh HISTORY
The
.Nm
device driver first appeared in
.Ox 4.5 .
.Sh AUTHORS
The
.Nm
driver was written by
.An Weongyo Jeong Aq weongyo@FreeBSD.org .
