# !!!!!!!   DO NOT EDIT THIS FILE   !!!!!!! 
# This file is built by ./mktables from e.g. UnicodeData.txt.
# Any changes made here will be lost!

# This file is for internal use by the Perl program only.  The format and even
# name or existence of this file are subject to change without notice.  Don't
# use it directly.

#
# This file supports:
# 	\p{Devanagari} (and fuzzy permutations)
# 
# Meaning: Script 'Devanagari'
#
return <<'END';
0900	0939	Devanagari
093C	094E	Devanagari
0950		Devanagari
0953	0955	Devanagari
0958	0963	Devanagari
0966	096F	Devanagari
0971	0972	Devanagari
0979	097F	Devanagari
A8E0	A8FB	Devanagari
END
