# !!!!!!!   DO NOT EDIT THIS FILE   !!!!!!! 
# This file is built by ./mktables from e.g. UnicodeData.txt.
# Any changes made here will be lost!

# This file is for internal use by the Perl program only.  The format and even
# name or existence of this file are subject to change without notice.  Don't
# use it directly.

#
# This file supports:
# 	\p{InCjkSymbolsAndPunctuation} (and fuzzy permutations)
# 
# Meaning: Block 'CJK Symbols and Punctuation'
#
return <<'END';
3000	303F	CJK Symbols and Punctuation
END
