# !!!!!!!   DO NOT EDIT THIS FILE   !!!!!!! 
# This file is built by ./mktables from e.g. UnicodeData.txt.
# Any changes made here will be lost!

# This file is for internal use by the Perl program only.  The format and even
# name or existence of this file are subject to change without notice.  Don't
# use it directly.

#
# This file supports:
# 	\p{InLatin1Supplement} (and fuzzy permutations)
# 
# Meaning: Block 'Latin-1 Supplement'
#
return <<'END';
0080	00FF	Latin-1 Supplement
END
