# !!!!!!!   DO NOT EDIT THIS FILE   !!!!!!! 
# This file is built by ./mktables from e.g. UnicodeData.txt.
# Any changes made here will be lost!

# This file is for internal use by the Perl program only.  The format and even
# name or existence of this file are subject to change without notice.  Don't
# use it directly.

#
# This file supports:
# 	\p{Javanese} (and fuzzy permutations)
# 
# Meaning: Script 'Javanese'
#
return <<'END';
A980	A9CD	Javanese
A9CF	A9D9	Javanese
A9DE	A9DF	Javanese
END
