.\"	$OpenBSD: rlog.1,v 1.24 2010/09/03 11:09:29 jmc Exp $
.\"
.\" Copyright (c) 2005 Xavier Santolaria <xsa@openbsd.org>
.\" All rights reserved.
.\"
.\" Permission to use, copy, modify, and distribute this software for any
.\" purpose with or without fee is hereby granted, provided that the above
.\" copyright notice and this permission notice appear in all copies.
.\"
.\" THE SOFTWARE IS PROVIDED "AS IS" AND THE AUTHOR DISCLAIMS ALL WARRANTIES
.\" WITH REGARD TO THIS SOFTWARE INCLUDING ALL IMPLIED WARRANTIES OF
.\" MERCHANTABILITY AND FITNESS. IN NO EVENT SHALL THE AUTHOR BE LIABLE FOR
.\" ANY SPECIAL, DIRECT, INDIRECT, OR CONSEQUENTIAL DAMAGES OR ANY DAMAGES
.\" WHATSOEVER RESULTING FROM LOSS OF USE, DATA OR PROFITS, WHETHER IN AN
.\" ACTION OF CONTRACT, NEGLIGENCE OR OTHER TORTIOUS ACTION, ARISING OUT OF
.\" OR IN CONNECTION WITH THE USE OR PERFORMANCE OF THIS SOFTWARE.
.Dd $Mdocdate: September 3 2010 $
.Dt RLOG 1
.Os
.Sh NAME
.Nm rlog
.Nd display information about RCS files
.Sh SYNOPSIS
.Nm
.Op Fl bhLNRtV
.Op Fl d Ns Ar dates
.Op Fl l Ns Op Ar lockers
.Op Fl r Ns Op Ar revs
.Op Fl s Ns Ar states
.Op Fl w Ns Op Ar logins
.Op Fl x Ns Ar suffixes
.Op Fl z Ns Ar tz
.Ar
.Sh DESCRIPTION
The
.Nm
program displays information about RCS files.
.Pp
A file's complete RCS history can be displayed
(the default if no options are specified)
or a subset of its history log can be requested,
depending on which options are specified.
RCS keywords are displayed using the
.Xr ident 1
utility.
.Pp
The following options are supported:
.Bl -tag -width Ds
.It Fl b
Print information about revisions of the default branch only.
.It Fl d Ns Ar dates
Specify revisions with dates matching the specification.
The specification might be as follows:
.Bl -tag -width Ds
.It date1<date2 or date2>date1
Select all revisions between
.Ar date1
and
.Ar date2 .
.It <date or date>
Select all revisions before
.Ar date .
.It >date or date<
Select all revisions after
.Ar date .
.It date
Select the latest revision before or equal to
.Ar date .
.El
.Pp
The
.Sq \*(Gt
and
.Sq \*(Lt
characters can be followed by the
.Sq =
character to imply an inclusive specification.
Several specifications can be used by separating them with the
.Sq \&;
character.
.Pp
See also the
.Fl z
option, below.
.It Fl h
Print the RCS header,
describing a file's branch, lock details, symbolic names, etc.
.It Fl L
Ignore RCS files with no locks set.
.It Fl l Ns Op Ar lockers
Print information about locked revisions only.
If a comma-separated list of login names is specified,
ignore all locks other than those held in the list.
.It Fl N
Do not print symbolic names.
.It Fl R
Print name of RCS file only.
.It Fl r Ns Op Ar revs
Specify revision(s) to list:
.Bl -tag -width Ds
.It rev1,rev2,...
A list of revisions is specified by separating names or numbers
of revisions by the
.Sq \&,
character.
.It rev1:rev2
List all revisions between
.Ar rev1
and
.Ar rev2
(they must be on the same branch).
.It :rev
List all revisions since the beginning of the branch until
.Ar rev
included.
.It rev:
List all revisions of the branch beginning with
.Ar rev .
.It branch
List all revisions of a branch.
.It branch.
List the latest revision of the branch
.Ar branch .
.It branch1:branch2
List all revisions of branches between
.Ar branch1
and
.Ar branch2 .
.El
.Pp
Without argument, the
.Fl r
option means the latest revision of the default branch.
.It Fl s Ns Ar states
Print information about revisions whose state matches one of the
specified
.Ar states .
Multiple states may be specified as a comma-separated list.
.It Fl t
Print header and description only.
.It Fl V
Print RCS's version number.
.It Fl w Ns Op Ar logins
Print information about revisions checked in by users specified
in a comma-separated list.
If
.Ar logins
is omitted, the user's login is assumed.
.It Fl x Ns Ar suffixes
Specifies the suffixes for RCS files.
Suffixes should be separated by the
.Sq /
character.
.It Fl z Ns Ar tz
Specify the date output format.
The
.Ar tz
argument should be a numeric UTC offset
(e.g. +02:45 would specify an offset of 2 hours 45 minutes).
.Sq LT
may instead be used to specify local time.
If no argument is given, a default format is used.
This option is also used to set the default time zone for
dates used in the
.Fl d
option.
.El
.Sh ENVIRONMENT
.Bl -tag -width RCSINIT
.It Ev RCSINIT
If set, this variable should contain a list of space-delimited options that
are prepended to the argument list.
.El
.Sh EXIT STATUS
.Ex -std rlog
.Sh EXAMPLES
Print complete information about files:
.Pp
.Dl $ rlog RCS/*
.Pp
Print the names of RCS files with locks set:
.Pp
.Dl $ rlog -L -R RCS/*
.Sh SEE ALSO
.Xr ci 1 ,
.Xr co 1 ,
.Xr ident 1 ,
.Xr rcs 1 ,
.Xr rcsclean 1 ,
.Xr rcsdiff 1 ,
.Xr rcsmerge 1
.Sh STANDARDS
The flags
.Op Fl qT
have no effect and are provided
for compatibility only.
