#	$OpenBSD: Makefile,v 1.2 2000/03/02 14:46:43 todd Exp $
#	from: @(#)Makefile	8.2 (Berkeley) 2/16/94

MAN=	ae.4 afsc.4 ahsc.4 atzsc.4 autoconf.4 console.4 bah.4 ed.4 es.4 gtsc.4 \
	intro.4 ite.4 le.4 mem.4 mfcs.4 mgnsc.4 qn.4 ser.4 wesc.4 zssc.4
MLINKS=	mem.4 kmem.4
MANSUBDIR=/amiga

.include <bsd.prog.mk>
