#	$OpenBSD: Makefile,v 1.43 2016/12/30 22:26:57 deraadt Exp $

SUBDIR=	libstubs \
	arch bioctl cat chmod chroot cp date dd df dhclient disklabel dmesg \
	doas ed eeprom encrypt fdisk fsck fsck_ext2fs fsck_ffs fsck_msdos ftp \
	ftp-ssl grep gzip hostname ifconfig init installboot kbd ksh ln ls md5 \
	mkdir mknod mkuboot more mount mount_cd9660 mount_ext2fs \
	mount_ffs mount_msdos mount_nfs mount_udf mt mv newfs newfs_ext2fs \
	newfs_msdos pax pdisk ping pwd_mkdb reboot restore rm route sed \
	signify sleep stty sync sysctl umount

install:

.include <bsd.subdir.mk>


