#	$OpenBSD: Makefile,v 1.31 2014/01/19 05:25:59 deraadt Exp $

SUBDIR=	libstubs \
	arch date dd dhclient dmesg ed ftp grep gzip ifconfig init \
	installboot kbd less md5 more mt newfs pax ping restore \
	sed sysctl signify ztsscale

install:

.include <bsd.subdir.mk>
