/* $OpenBSD: tls12_handshake.h,v 1.1 2026/09/22 18:57:11 jsing Exp $ */
/*
 * Copyright (c) 2019 Theo Buehler <tb@openbsd.org>
 * Copyright (c) 2026 Joel Sing <jsing@openbsd.org>
 *
 * Permission to use, copy, modify, and/or distribute this software for any
 * purpose with or without fee is hereby granted, provided that the above
 * copyright notice and this permission notice appear in all copies.
 *
 * THE SOFTWARE IS PROVIDED "AS IS" AND THE AUTHOR DISCLAIMS ALL WARRANTIES
 * WITH REGARD TO THIS SOFTWARE INCLUDING ALL IMPLIED WARRANTIES OF
 * MERCHANTABILITY AND FITNESS. IN NO EVENT SHALL THE AUTHOR BE LIABLE FOR ANY
 * SPECIAL, DIRECT, INDIRECT, OR CONSEQUENTIAL DAMAGES OR ANY DAMAGES
 * WHATSOEVER RESULTING FROM LOSS OF USE, DATA OR PROFITS, WHETHER IN AN ACTION
 * OF CONTRACT, NEGLIGENCE OR OTHER TORTIOUS ACTION, ARISING OUT OF OR IN
 * CONNECTION WITH THE USE OR PERFORMANCE OF THIS SOFTWARE.
 */

#ifndef HEADER_TLS12_HANDSHAKE_H
#define HEADER_TLS12_HANDSHAKE_H

#include <stddef.h>	/* for NULL */

__BEGIN_HIDDEN_DECLS

#define INITIAL			0x00
#define WITH_SERVER_CERT	0x04
#define WITH_SERVER_KEX		0x08

enum tls12_message_type {
	INVALID,
	HELLO_REQUEST,
	CLIENT_HELLO,
	SERVER_HELLO,
	SERVER_CERTIFICATE,
	SERVER_KEY_EXCHANGE,
	SERVER_CERTIFICATE_REQUEST,
	SERVER_HELLO_DONE,
	CLIENT_CERTIFICATE,
	CLIENT_KEY_EXCHANGE,
	CLIENT_CERTIFICATE_VERIFY,
	CLIENT_CHANGE_CIPHER_SPEC,
	CLIENT_FINISHED,
	SERVER_NEW_SESSION_TICKET,
	SERVER_CHANGE_CIPHER_SPEC,
	SERVER_FINISHED,
	APPLICATION_DATA,
	TLS12_NUM_MESSAGE_TYPES,
};

__END_HIDDEN_DECLS

#endif /* !HEADER_TLS12_HANDSHAKE_H */
