.\"     $OpenBSD: ie.4,v 1.1 2001/12/17 00:25:41 deraadt Exp $
.\"
.\" Copyright (c) 1998 The OpenBSD Project
.\" All rights reserved.
.\"
.Dd March 9, 1998
.Dt IE 4 mvme68k
.Os
.Sh NAME
.Nm ie
.Nd Intel 82586 ethernet interface
.Sh SYNOPSIS
.Cd "ie0 at mc0 offset 0x46000 ipl 1"
.Cd" ie0 at pcctwo0 offset 0x46000 ipl 1"
.Sh DESCRIPTION
The
.Nm
interface provides access to the 10 Mb/s Ethernet network via the
.Tn Intel
82586
Ethernet chip set.
The
.Pp
Each of the host's network addresses
is specified at boot time with an
.Dv SIOCSIFADDR
.Xr ioctl 2 .
The
.Nm
interface employs the address resolution protocol described in
.Xr arp 4
to dynamically map between Internet and Ethernet addresses on the local
network.
.Sh SEE ALSO
.Xr arp 4 ,
.Xr inet 4 ,
.Xr intro 4 ,
.Xr le 4
