.\"     $OpenBSD: ie.4,v 1.7 2007/05/31 19:19:55 jmc Exp $
.\"
.\" Copyright (c) 1988 John E. Stone <j.stone@acm.org>
.\"
.\" Permission to use, copy, modify, and distribute this software for any
.\" purpose with or without fee is hereby granted, provided that the above
.\" copyright notice and this permission notice appear in all copies.
.\"
.\" THE SOFTWARE IS PROVIDED "AS IS" AND THE AUTHOR DISCLAIMS ALL WARRANTIES
.\" WITH REGARD TO THIS SOFTWARE INCLUDING ALL IMPLIED WARRANTIES OF
.\" MERCHANTABILITY AND FITNESS. IN NO EVENT SHALL THE AUTHOR BE LIABLE FOR
.\" ANY SPECIAL, DIRECT, INDIRECT, OR CONSEQUENTIAL DAMAGES OR ANY DAMAGES
.\" WHATSOEVER RESULTING FROM LOSS OF USE, DATA OR PROFITS, WHETHER IN AN
.\" ACTION OF CONTRACT, NEGLIGENCE OR OTHER TORTIOUS ACTION, ARISING OUT OF
.\" OR IN CONNECTION WITH THE USE OR PERFORMANCE OF THIS SOFTWARE.
.\"
.Dd $Mdocdate: May 31 2007 $
.Dt IE 4 mvme68k
.Os
.Sh NAME
.Nm ie
.Nd Intel i82586 Ethernet device
.Sh SYNOPSIS
.Cd "ie0 at mc0 offset 0x46000 ipl 1" Pq "MVME162"
.Cd "ie0 at pcctwo0 offset 0x46000 ipl 1" Pq "MVME167/177"
.Sh DESCRIPTION
The
.Nm
interface provides access to the 10 Mb/s Ethernet network via the
.Tn Intel
82586
Ethernet chip set.
.Sh SEE ALSO
.Xr arp 4 ,
.Xr inet 4 ,
.Xr intro 4 ,
.Xr le 4 ,
.Xr netintro 4 ,
.Xr hostname.if 5 ,
.Xr ifconfig 8
