#	$OpenBSD: Makefile,v 1.7 2003/09/02 21:32:13 miod Exp $
#	from: @(#)Makefile	8.2 (Berkeley) 2/16/94

# TODO: cl clock flash ipic lp mc memc nvram pcc pcctwo sram vme vs wdsc zs
MAN=	autoconf.4 intro.4 le.4 ie.4 mem.4 ssh.4
MLINKS=	mem.4 kmem.4
MANSUBDIR=mvme68k

.include <bsd.prog.mk>
