#	$NetBSD: Makefile,v 1.3 1995/09/30 21:43:41 pk Exp $

.PATH:	${.CURDIR}/..
PROG=	installboot
MAN=	installboot.8
BINDIR=/usr/sbin

# XXX - prevent sa clutter
__stand_makefile_inc=1

.include <bsd.prog.mk>
