.\"	$OpenBSD: compat_ultrix.8,v 1.12 2003/02/19 09:10:36 jmc Exp $
.\"
.\" Copyright (c) 1997 Jonathan Stone
.\" All rights reserved.
.\"
.\" Redistribution and use in source and binary forms, with or without
.\" modification, are permitted provided that the following conditions
.\" are met:
.\" 1. Redistributions of source code must retain the above copyright
.\"    notice, this list of conditions and the following disclaimer.
.\" 2. Redistributions in binary form must reproduce the above copyright
.\"    notice, this list of conditions and the following disclaimer in the
.\"    documentation and/or other materials provided with the distribution.
.\" 3. All advertising materials mentioning features or use of this software
.\"    must display the following acknowledgement:
.\"	This product includes software developed by Jonathan Stone.
.\" 4. Neither the name of the author nor the names of its contributors
.\"    may be used to endorse or promote products derived from this software
.\"    without specific prior written permission.
.\"
.\" THIS SOFTWARE IS PROVIDED BY THE AUTHOR ``AS IS'' AND
.\" ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE
.\" IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE
.\" ARE DISCLAIMED.  IN NO EVENT SHALL THE AUTHOR BE LIABLE
.\" FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL
.\" DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS
.\" OR SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION)
.\" HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT
.\" LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY
.\" OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF
.\" SUCH DAMAGE.
.\"
.Dd June 7, 1997
.Dt COMPAT_ULTRIX 8
.Os
.Sh NAME
.Nm compat_ultrix
.Nd setup for running Ultrix binaries under emulation
.Sh DESCRIPTION
OpenBSD/mips and OpenBSD/vax architectures can run Risc ULTRIX and Vax
ULTRIX executables, respectively.
However, the user is responsible for
the legal issues of ensuring that they have a right to use any ULTRIX
binaries on their machine.
.Pp
Most executables will work.
The exceptions include programs that use
proprietary, Ultrix-specific features (LAT, CI support, DECnet
support) and various system calls, ioctl()'s, or Ultrix kernel
semantics that are difficult to emulate (e.g., Ultrix packetfilter) or
buggy (e.g., Ultrix YP).
.Pp
All Ultrix executables are static, so no shared libraries are required
for Ultrix compatibility.
However, Ultrix is based on a
.Bx 4.3
alpha release.
Ultrix commands and libraries are often much older than their
.Ox
or even SunOS 4.x equivalents, and may require incompatible
configuration files.
.Sh SYSTEM CONFIGURATION FILES
Set up resolv.conf and svc.conf as below:
.Pp
.Bl -tag -width 123 -compact -offset indent
.It # mkdir -p /emul/ultrix/etc
.br
.It # cd /emul/ultrix/etc
.br
.It # egrep 'domain|nameserver' /etc/resolv.conf  > ./resolv.conf
.br
.It # cp -p /usr/share/samples/emul/ultrix/etc/*	./
.El
.Ss /etc/resolv.conf
The Ultrix resolver library only understands
.Sy domain
and
.Sy nameserver
lines in
.Xr resolv.conf 5 .
A copy of
.Pa /etc/resolv.conf
should be created containing only those commands and put in
.Pa /emul/ultrix/etc/resolv.conf .
Note that the domain search order used by Ultrix executables may
not be the same as native binaries; there is no good way around this.
.Ss /etc/svc.conf
Ultrix uses
.Pa /etc/svc.conf
to select an ordered search of YP, Hesiod, or local flat-file mappings.
Create an
.Pa /emul/ultrix/etc/svc.conf
file specifying either
local files or bind (DNS) lookups for all Ultrix name services.
.Sh BUGS
RISC Ultrix YP(NIS) is known to not work.
The Ultrix YP libraries have a consistent endian-ness bug.
Ultrix YP client will not inter-operate with the
.Ox
.Xr ypbind 8
process.
The only workaround is to use
.Pa /etc/svc.conf
to disable YP(NIS).
.Pp
The ndbm hashed-password file used by Ultrix is incompatible with the
db hashed-password file used by
.Ox .
There is no good solution for this.
(YP would be a good one, if Ultrix YP worked.)
.Pp
The API used by Xservers to talk to the kernel is currently compatible
with Ultrix 4.1.
An implementation of the Ultrix 4.2 Xws interface (used by X11R6) is
in progress.
.Pp
A complete list of things which fail to work in Ultrix compatibility
mode should be added here.
.Sh SEE ALSO
.Xr resolv.conf 5
