#	$OpenBSD: Makefile,v 1.11 1997/06/11 01:14:13 deraadt Exp $
#	$NetBSD: Makefile,v 1.13 1996/03/28 21:36:40 mark Exp $
#	@(#)Makefile	8.1 (Berkeley) 6/5/93

MAN=	compat_freebsd.8 compat_linux.8 compat_sunos.8 \
	compat_svr4.8 compat_ultrix.8 diskless.8 intro.8 rc.8 \
	sticky.8 update.8 yp.8 boot_config.8
SUBDIR=	man8.amiga man8.arm32 man8.atari man8.hp300 man8.i386 man8.mac68k \
	man8.sparc man8.sun3 man8.vax

.include <bsd.prog.mk>
