.\"
.\" Copyright (c) 1997 Ian F. Darwin
.\" All rights reserved.
.\"
.\" Redistribution and use in source and binary forms, with or without
.\" modification, are permitted provided that the following conditions
.\" are met:
.\" 1. Redistributions of source code must retain the above copyright
.\"    notice, this list of conditions and the following disclaimer.
.\" 2. Redistributions in binary form must reproduce the above copyright
.\"    notice, this list of conditions and the following disclaimer in the
.\"    documentation and/or other materials provided with the distribution.
.\" 3. The name of the author may not be used to endorse or promote
.\"    products derived from this software without specific prior written
.\"    permission.
.\"
.\" THIS SOFTWARE IS PROVIDED BY THE AUTHOR ``AS IS'' AND ANY EXPRESS
.\" OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED
.\" WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE
.\" ARE DISCLAIMED.  IN NO EVENT SHALL THE AUTHOR BE LIABLE FOR ANY
.\" DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL
.\" DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS
.\" OR SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION)
.\" HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT
.\" LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY
.\" OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF
.\" SUCH DAMAGE.
.\"
.Dd January 5, 1998
.Os OpenBSD 2.2
.Dt RC.CONF 8 SMM
.Sh NAME
.Nm rc.conf
.Nd system daemon configuration database
.Sh DESCRIPTION
This file contains a series of Bourne-shell syntax assinments
that are used to configure the system daemons.
It is not read by the kernel, but is sourced by various other files
in the
.Pa /etc/rc.*
series in order to set shell variables used therein
to control the behaviour of the scripts.
.Pp
There are three sections to the file. The first is used to turn features
on or off. For example, whether your system runs the 
.Nm sendmail
daemon is determined by the line in this section
.Bd -literal -indent xxx
sendmail_flags=NO
.Ed
.Pp
If you edit this line to contain some valid sendmail daemon command-line
flags, such as
.Bd -literal -indent xxx
sendmail_flags="-bd -q30m"
.Ed
.Pp
then the sendmail daemon will be started with those options.
.Pp
The second section contains some other programs that can either be run or not,
but that don't need options. They can be set to YES or NO. For example,
the distributed system contains the line
.Bd -literal -indent xxx
nfs_server=NO
.Ed
.Pp
which prevents the NFS server daemons from starting. If you wish to 
run NFS, you need to change this line's value from NO to YES,
.Sy plus
you also need to make whatever changes are needed for the server
to have something to do (like, set up the exports file).
.Pp
The third section contains values that parameterize servers started by
one of the first two sections, and are ignored if the corresponding
server is not running. For example, if you enabled 
.Nm nfs_server ,
you should also be aware of the value here
.Bd -literal -indent xxx
nfsd_flags="-tun 4"
.Ed
.Pp
which starts four copies of the server; on a busy file server you'd
probably change to 8 or more.
.Sh SEE ALSO
.Xr init 8 ,
.Xr rc 8 .
.Pp
and the detailed documentation given for each server that is
configurable in this fashion.
.Sh HISTORY
The file 
.Nm rc.conf
first appeared in
.Ox 2.2 .
