OBSOLETE /* COPYRIGHT  (C)  1998
OBSOLETE  * THE REGENTS OF THE UNIVERSITY OF MICHIGAN
OBSOLETE  * ALL RIGHTS RESERVED
OBSOLETE  * 
OBSOLETE  * PERMISSION IS GRANTED TO USE, COPY, CREATE DERIVATIVE WORKS 
OBSOLETE  * AND REDISTRIBUTE THIS SOFTWARE AND SUCH DERIVATIVE WORKS 
OBSOLETE  * FOR ANY PURPOSE, SO LONG AS THE NAME OF THE UNIVERSITY OF 
OBSOLETE  * MICHIGAN IS NOT USED IN ANY ADVERTISING OR PUBLICITY 
OBSOLETE  * PERTAINING TO THE USE OR DISTRIBUTION OF THIS SOFTWARE 
OBSOLETE  * WITHOUT SPECIFIC, WRITTEN PRIOR AUTHORIZATION.  IF THE 
OBSOLETE  * ABOVE COPYRIGHT NOTICE OR ANY OTHER IDENTIFICATION OF THE 
OBSOLETE  * UNIVERSITY OF MICHIGAN IS INCLUDED IN ANY COPY OF ANY 
OBSOLETE  * PORTION OF THIS SOFTWARE, THEN THE DISCLAIMER BELOW MUST 
OBSOLETE  * ALSO BE INCLUDED.
OBSOLETE  * 
OBSOLETE  * THIS SOFTWARE IS PROVIDED AS IS, WITHOUT REPRESENTATION 
OBSOLETE  * FROM THE UNIVERSITY OF MICHIGAN AS TO ITS FITNESS FOR ANY 
OBSOLETE  * PURPOSE, AND WITHOUT WARRANTY BY THE UNIVERSITY OF 
OBSOLETE  * MICHIGAN OF ANY KIND, EITHER EXPRESS OR IMPLIED, INCLUDING 
OBSOLETE  * WITHOUT LIMITATION THE IMPLIED WARRANTIES OF 
OBSOLETE  * MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE. THE 
OBSOLETE  * REGENTS OF THE UNIVERSITY OF MICHIGAN SHALL NOT BE LIABLE 
OBSOLETE  * FOR ANY DAMAGES, INCLUDING SPECIAL, INDIRECT, INCIDENTAL, OR 
OBSOLETE  * CONSEQUENTIAL DAMAGES, WITH RESPECT TO ANY CLAIM ARISING 
OBSOLETE  * OUT OF OR IN CONNECTION WITH THE USE OF THE SOFTWARE, EVEN 
OBSOLETE  * IF IT HAS BEEN OR IS HEREAFTER ADVISED OF THE POSSIBILITY OF 
OBSOLETE  * SUCH DAMAGES.
OBSOLETE  */
OBSOLETE 
OBSOLETE #include "arla_local.h"
OBSOLETE 
OBSOLETE RCSID("$arla: darla.c,v 1.8 2002/07/23 15:22:51 lha Exp $");
OBSOLETE 
OBSOLETE int DARLA_Open(DARLA_file *Dfp, char *fname, int oflag)
OBSOLETE {
OBSOLETE 
OBSOLETE   int fd;
OBSOLETE 
OBSOLETE   fd = open(fname, oflag, 0600);
OBSOLETE   if (fd == -1)
OBSOLETE       arla_log(ADEBMISC, "DARLA_Open: errno=%d", errno); 
OBSOLETE   if (fd > 0)
OBSOLETE   {
OBSOLETE     Dfp->fd = fd;
OBSOLETE     Dfp->offset=0;
OBSOLETE     Dfp->log_entries = 0;
OBSOLETE   }
OBSOLETE 
OBSOLETE   return fd;
OBSOLETE }
OBSOLETE 
OBSOLETE int DARLA_Close(DARLA_file *Dfp)
OBSOLETE {
OBSOLETE   int ret;
OBSOLETE   
OBSOLETE   ret = close(Dfp->fd);
OBSOLETE   Dfp->fd = 0;
OBSOLETE   Dfp->offset =0;
OBSOLETE   arla_log(ADEBMISC, "DARLA_Close: ret=%d", ret);
OBSOLETE   return ret;
OBSOLETE }
OBSOLETE 
OBSOLETE int DARLA_Read(DARLA_file *Dfp, char *cp, int len)
OBSOLETE {
OBSOLETE   ssize_t read_size;
OBSOLETE   
OBSOLETE   if (Dfp->fd)
OBSOLETE   {
OBSOLETE     read_size = read (Dfp->fd, cp, len);
OBSOLETE   }
OBSOLETE   else
OBSOLETE     read_size = 0;
OBSOLETE 
OBSOLETE   return read_size;
OBSOLETE }
OBSOLETE 
OBSOLETE int DARLA_Write(DARLA_file *Dfp, char *cp, int len)
OBSOLETE {
OBSOLETE   ssize_t write_size;
OBSOLETE 
OBSOLETE   if (Dfp->fd)
OBSOLETE   {
OBSOLETE     write_size = write(Dfp->fd, cp, len);
OBSOLETE   }
OBSOLETE   else
OBSOLETE     write_size = 0;
OBSOLETE   
OBSOLETE   return write_size;
OBSOLETE }
OBSOLETE 
OBSOLETE int DARLA_Seek(DARLA_file *Dfp, int offset, int whence)
OBSOLETE {
OBSOLETE 
OBSOLETE   off_t lseek_off;
OBSOLETE 
OBSOLETE   if (Dfp->fd)
OBSOLETE   {
OBSOLETE     lseek_off = lseek(Dfp->fd, offset, whence);
OBSOLETE   }
OBSOLETE   else
OBSOLETE     lseek_off = 0;
OBSOLETE 
OBSOLETE   return lseek_off;
OBSOLETE }
