#!/usr/bin/perl

# $RCSfile: dus,v $$Revision: 1.1.1.1 $$Date: 1996/08/19 10:11:53 $

# This script does a du -s on any directories in the current directory that
# are not mount points for another filesystem.

($mydev,$ino,$mode,$nlink,$uid,$gid,$rdev,$size,$atime,$mtime,$ctime,
   $blksize,$blocks) = stat('.');

open(ls,'ls -F1|');

while (<ls>) {
    chop;
    next unless s|/$||;
    ($dev,$ino,$mode,$nlink,$uid,$gid,$rdev,$size,$atime,$mtime,$ctime,
       $blksize,$blocks) = stat($_);
    next unless $dev == $mydev;
    push(@ary,$_);
}

exec 'du', '-s', @ary;
