#	from: @(#)Makefile	5.6.1.2 (Berkeley) 5/8/91
#	$Id: Makefile,v 1.3 1996/03/02 03:01:29 dm Exp $

SUBDIR=	makedbm mknetid stdethers stdhosts ypinit ypserv yptest yppush ypxfr

.include <bsd.subdir.mk>
