#define PACKAGE_NAME "pkgconf-lite"
#define PACKAGE_BUGREPORT "https://github.com/pkgconf/pkgconf/issues"
#define PACKAGE_VERSION "3.0.5"
#define PACKAGE PACKAGE_NAME " " PACKAGE_VERSION

#define HAVE_DECL_STRNDUP	1
#define HAVE_DECL_REALLOCARRAY	1
#define HAVE_DECL_PLEDGE	1
#define HAVE_DECL_UNVEIL	1
#define HAVE_DECL_READLINKAT	1
#define HAVE_DECL_GETC_UNLOCKED	1
#define HAVE_DECL_NL_LANGINFO_L	1
